### PR TITLE
reporting excel cell shading in case of conditional formatting and background pattern reporting

### PR DESCRIPTION
**Pull request by ManshulBelani**
reporting excel cell shading in case of conditional formatting and reporting excell cell pattern

### CODE REVIEW

**Comment by jcsteh** [comment]
Is there a reason you created a new pull request rather than updating the branch for #5626? Or am I missing something? Thanks!

**Comment by ManshulBelani** [comment]
I created a new branch for this issue, since my old branch was made on an
old repository and the remote URLs in that repo were incorrect. So i had to
discard that repo and make a new repo and this new branch is made from the
new repo.

On Wed, Jan 13, 2016 at 12:24 PM, James Teh <notifications@github.com>
wrote:

> Is there a reason you created a new pull request rather than updating the
> branch for #5626 <https://github.com/nvaccess/nvda/pull/5626>? Or am I
> missing something? Thanks!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/nvaccess/nvda/pull/5649#issuecomment-171195235>.
>



-- 
Regards
Manshul V Belani

**Comment by jcsteh** [comment]
That's unfortunate. When this happens, you can just change the remote 
URLs (see the git remote command) and push the branch to the new remote. 
It's difficult for me to see what's changed between your old and new 
code this way. Still, it's done now; I'll close the previous pull request.

**Comment by ManshulBelani** [comment]
Ok.. Thanks.. I will take care in future.

On Wed, Jan 13, 2016 at 4:01 PM, James Teh <notifications@github.com> wrote:

> That's unfortunate. When this happens, you can just change the remote
> URLs (see the git remote command) and push the branch to the new remote.
> It's difficult for me to see what's changed between your old and new
> code this way. Still, it's done now; I'll close the previous pull request.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/nvaccess/nvda/pull/5649#issuecomment-171248868>.
>



-- 
Regards
Manshul V Belani

**Comment by jcsteh** [comment]
I've now merged this into next with a few changes, including:

* Rather than building the background color string for both the current and old colors, just build the string for the current colors. We don't need the string for the old colors, so building it is unnecessary/inefficient. Instead, just compare the current and old colors directly.
* Put the "background pattern" text before the pattern instead of after. It sounds less natural in some cases, but it's more consistent, plus it avoids the confusion of "none background color".
* Added missing translators comment.
* Fixed indentation problems and extraneous white space.
* Renamed background-colorTwo to background-color2 (number 2 instead of word two).

**Pull request closed without merging**
