### PR TITLE
UI Automation in Windows Console: remove the isTyping logic from UIA consoles

### PR DESCRIPTION
**Pull request by codeofdusk**
### Link to issue number:
Builds on #9614.

### Summary of the issue:
Currently, in UIA consoles:

* In console applications that update the screen while the user is typing (i.e. before `winConsoleUIA._isTyping` is cleared), reporting of new text and speak typed words may not function correctly.

### Description of how this pull request fixes the issue:
This PR removes the `_isTyping` check from consoles. Instead:

* `LiveText` objects strip spaces when filtering typed characters from new text.
* In UIA consoles, if a new text line (after stripping spaces) contains two characters or fewer, it is not reported.
* when a new line is written to the console, the typed word buffer and typed character queue are flushed.

### Testing performed:
On Windows 10 1903, with "speak typed words" and UIA in consoles enabled:

1. Opened a command console.
2. In a git repository, typed `git log`.
3. pressed q.
4. typed git and pressed space.

Before this change: NVDA says "qgit".
After this change: NVDA says "git".

### Known issues with pull request:
When typing quickly, a few typed characters may bypass the filter, resulting in doubled or incorrectly echoed characters. A more severe form of this issue also occurs in legacy consoles. We might want to filter more aggressively at the risk of missing some new text.

### Change log entry:
None.

### CODE REVIEW

**Comment by codeofdusk** [comment]
CC @feerrenrut @leonardder @michaelDCurran

**Comment by codeofdusk** [comment]
@michaelDCurran Mind having another look at this?

**Review by michaelDCurran — CHANGES_REQUESTED** [review]
Looks like the liblouis submodule has accidentally been updated to a different commit.

**Comment by codeofdusk** [comment]
@michaelDCurran Did this fix it?

**Review by michaelDCurran — APPROVED** [review]
This is all good now.

**Pull request merged**
