### PR TITLE
Break up sentences in user guide

### PR DESCRIPTION
**Pull request by seanbudd**
### Link to issue number:
None

### Summary of the issue:
Some messages in the user guide are difficult to translate due to their length, as raised in this [translators google group](https://groups.io/g/nvda-translations/message/2871?reply=1).

### Description of how this pull request fixes the issue:
Break up these sentences to make reading and translation easier.

### Testing strategy:
- [x] Check generated HTML file

### Known issues with pull request:
None

### Change log entries:
N/A

### Code Review Checklist:

- [x] Pull Request description:
  - description is up to date
  - change log entries
- [x] Testing:
  - Unit tests
  - System (end to end) tests
  - Manual testing
- [x] API is compatible with existing add-ons.
- [x] Documentation:
  - User Documentation
  - Developer / Technical Documentation
  - Context sensitive help for GUI changes
- [x] UX of all users considered:
  - Speech 
  - Braille
  - Low Vision
  - Different web browsers
  - Localization in other languages / culture than English

### CODE REVIEW

**Comment by CyrilleB79** [comment]
@seanbudd could you indicate how you have found the sentences to break up? Is this an exhaustive search (regexp)? Or did you just break up sentences that were reported? Did you also check the nvda.pot?


Also for testing, I guess that you have at least checked the result in the generated html document?

**Comment by seanbudd** [comment]
@CyrilleB79 - these changes are based on the references requested in the email.
I think the translator might follow up with more fixes based on our discussion on the mailing list.

**Comment by manhcuong0312** [comment]
Hi all  
I reported this in [NVDA Translation Mailling list](https://groups.io/g/nvda-translations/message/2871?reply=1)

- I'm a translator, and I've never touch the pot file of NVDA
- This issue is for the user guide file, and I think iti should be fixed to make the translation process easier to updated.
- The generated HTML is fine because this is not a wrong syntax. This just affects translator in case one lines contains two or more sentances, and each of them is long.
Cuong

**Comment by XLTechie** [comment]
>  *  The generated HTML is fine because this is not a wrong syntax. This just affects translator in case one lines contains two or more sentances, and each
>     of them is long.

What is long?

**Comment by XLTechie** [comment]
> What is long?

That should be more clear. I mean: what do you mean by "long"? What constitutes 
too long? Too many words? Too many characters in the line? How many is too many?

**Comment by seanbudd** [comment]
@XLTechie - I don't think this a specific answer here, just that shorter sentences improve readability of text.

A common suggestion for making readable, accessible documentation is 20-25 words or less.
https://readabilityguidelines.co.uk/clear-language/simple-sentences/

For developer legibility, NVDA has a max line length of 110, which is roughly equivalent to 20-25 words as well.
*.t2t` files should keep 1 sentence per line for translatability.

**Comment by manhcuong0312** [comment]
Hi @XLTechie 
I mean a line contains two or more sentances, and also contains long sentance. As @seanbudd said, the t2t should place each sentance on one line. Please read [my e-mail on translation mailing list](https://groups.io/g/nvda-translations/message/2871?reply=1) for the reason why I requested this.

**Review by Qchristensen — APPROVED** [review]
Looks good, great work!

**Pull request merged**
