### PR TITLE
nvwave: Fix occasional exception related to close timer.

### LINKED ISSUE #11482: Traceback occurs when switching synths in latest alpha
### Steps to reproduce:
1. Switch between two synthesizers several times and wait a bit. I was able to reproduce this reliably using ESpeak and Vocalizer, but it may happen for other synths as well.
### Actual behavior:
A traceback is displayed. The following log fragment demonstrates me switching from ESpeak to Vocalizer and then getting the traceback.
INFO - synthDriverHandler.setSynth (09:26:49.664) - MainThread (2068):
Loaded synthDriver espeak
DEBUGWARNING - synthDriverHandler.getSynthList (09:26:52.441) - MainThread (2068):
Synthesizer 'mssp' doesn't pass the check, excluding from list
DEBUGWARNING - external:synthDrivers.vocalizer_expressive._voiceManager.VoiceManager.setDefaultVoice (09:26:54.850) - MainThread (2068):
Voice not available, using default voice.
DEBUGWARNING - external:synthDrivers.vocalizer_expressive.SynthDriver._set_variant (09:26:54.855) - MainThread (2068):
Model not available: full_155mrf22
INFO - synthDriverHandler.setSynth (09:26:54.856) - MainThread (2068):
Loaded synthDriver vocalizer_expressive
ERROR - unhandled exception (09:26:59.835) - MainThread (2068):
Traceback (most recent call last):
  File "wx\core.pyc", line 2196, in Notify
  File "nvwave.pyc", line 349, in _close
  File "nvwave.pyc", line 90, in _winmm_errcheck
OSError: [Errno 5] The specified device handle is invalid.
### Expected behavior:
No error.
#### NVDA installed/portable/running from source:
Installed.
#### NVDA version:
alpha-20718,633435db.
#### Windows version:
Windows 10, version	10.0.20185 Build 20185.

#### Name and version of other software in use when reproducing the issue:
N/a
#### Other information about your system:
N/a
#### Does the issue still occur after restarting your computer?
Yes.
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
Yes, this seems to have started when #11024 was merged.
#### If addons are disabled, is your problem still occuring?
Yes.
#### Did you try to run the COM registry fixing tool in NVDA menu / tools?
N/a.

### LINKED ISSUE #11490: NVDA seems to have lost the ability to recover from a lost audio device
Possibly related to #11482.
### Steps to reproduce:
1. Perform the steps to reproduce in #11482, by installing RHVoice, and then switching to ESpeak and back to RHVoice again. If the error doesn't occur after a few seconds, you may need to try it again, pressing the control key quickly after you switch synths, for example switch to ESpeak, press control quickly, and then switch to RHVoice and press control again.
2. Restart the Windows Audio service. This is sometimes useful for some programs or resolving audio issues.
### Actual behavior:
Repeated device handle is invalid errors are logged and NVDA can lose the ability to speak.
Here is a log fragment.
ERROR - queueHandler.flushQueue (08:59:19.701) - MainThread (1640):
Error in func cancelSpeech
Traceback (most recent call last):
  File "C:\Users\Owner\AppData\Roaming\nvda\addons\RHVoice\synthDrivers\RHVoice\__init__.py", line 850, in cancel
    self.__tts_queue.get_nowait()
  File "queue.pyc", line 198, in get_nowait
  File "queue.pyc", line 167, in get
_queue.Empty

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "queueHandler.pyc", line 55, in flushQueue
  File "speech\__init__.pyc", line 146, in cancelSpeech
  File "speech\manager.pyc", line 737, in cancel
  File "C:\Users\Owner\AppData\Roaming\nvda\addons\RHVoice\synthDrivers\RHVoice\__init__.py", line 854, in cancel
    self.__player.stop()
  File "C:\Users\Owner\AppData\Roaming\nvda\addons\RHVoice\synthDrivers\RHVoice\__init__.py", line 289, in stop
    player.stop()
  File "nvwave.pyc", line 331, in stop
  File "nvwave.pyc", line 298, in _idleUnbuffered
  File "nvwave.pyc", line 253, in sync
  File "nvwave.pyc", line 90, in _winmm_errcheck
OSError: [Errno 5] The specified device handle is invalid.
### Expected behavior:
NVDA should e able to recover from the lost audio device.
#### NVDA installed/portable/running from source:
Installed.
#### NVDA version:
alpha-20725,d7e80693.
#### Windows version:
Windows 10, version 10.0.20190 Build 20190.

#### Name and version of other software in use when reproducing the issue:
N/a
#### Other information about your system:
N/a.
#### Does the issue still occur after restarting your computer?
Yes.
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
Yes, this does not happen in 2020.2. Another regression introduced by #11024, perhaps?
#### If addons are disabled, is your problem still occuring?
Yes.
#### Did you try to run the COM registry fixing tool in NVDA menu / tools?
N/a.

### PR DESCRIPTION
**Pull request by jcsteh**
### Link to issue number:
Fixes #11482. Fixes #11490.

### Summary of the issue:
Occasional exceptions from nvwave, particularly when switching synthesisers.

### Description of how this pull request fixes the issue:
The idle close timer must be started on the main thread.
However, it's possible that the player might be closed while the timer start call is waiting to run.
Previously, this would cause an exception when the timer expired because we'd try to close when we were already closed.
To fix this, we now check (on the main thread) if the player is closed, and if it is, we don't start the timer.

### Testing performed:
1. Ensured that the device is still being closed on idle as expected by adding a debugging beep to `_close()`.
2. Switched synthesisers as described in #11482. No exception. However, I was never able to reproduce the original problem, so this doesn't count for much. We should probably have someone who experiences this verify the fix in a try build.

### CODE REVIEW

**Comment by Mohamed00** [comment]
I was unable to reproduce the issue with the try build. #11490 is fixed as well.

**Comment by jcsteh** [comment]
Oh fascinating. I didn't expect it to fix #11490. I'll update the PR description. Thanks for testing.

**Comment by feerrenrut** [comment]
@jcsteh I would like your opinion on the following:

Given that keeping the audio device "open" (or at least the audio API initialized) results in a significant performance improvement. Or at least the inverse, opening and closing the device results in a noticeable delay. I propose that we no longer close the device at all (except for changing output / shutdown etc).

The reasons for this:
- Performance is improved in more situations. Eg after 12 seconds of non-usage, or 15,  30 etc
- Simplify the code
- Less potential for bugs, I believe there are still race conditions existing with the current timer approach. 
- Make exploring the idea of prepending or appending silence easier

I'm aware we will have to work around disconnected / reconnected devices. But other than that, do you have any specific concerns about keeping the device open, since you have a lot of background in this area of the code.

I'm surprised this fixes #11490, perhaps there was already 10 seconds after the last speech before the device was disconnected? I think this will need specific testing.

**Comment by jcsteh** [comment]
The original closeWhenIdle change was implemented in 03ae3f670e08:

> Introduce a closeWhenIdle option to the constructor to close the output device when idle. This facilitates switching devices when the default audio output device changes. It also allows audio to finish playing correctly when playing to a Remote Desktop client.

I don't know how much we care about Remote Desktop audio now. The performance is pretty bad anyway, and we now have solutions like NVDA Remote and Unicorn which offer a far better experience. In addition, the delay in #11024 will break this anyway.

> I'm aware we will have to work around disconnected / reconnected devices.

This is going to be the trickiest part of this proposal. I'm not sure how this can be managed. We do have a way of watching for hardware notifications now, but I believe changing the default device might also need us to take action, and that's not going to fire a hardware notification. (There are specific APIs to get audio device notifications, but we don't have code to watch for those yet, plus they don't map well to the old winmm API we're using.) In addition, you'll need to close all WavePlayers, but only when they're idle, since you can't close them while they're playing without losing audio.

>     * Less potential for bugs, I believe there are still race conditions existing with the current timer approach.

I'm not aware of any further race conditions, but I guess it's possible. On the other hand, safely closing all devices when audio devices change is likely to introduce a whole new set of bugs.

> * Make exploring the idea of prepending or appending silence easier

I don't really see how getting rid of closeWhenIdle makes this easier. On the contrary, you'll potentially need similar timer code to handle appending of silence (unless you just throw out a massive buffer of audio). Still, this doesn't really impact my overall opinion.

> But other than that, do you have any specific concerns about keeping the device open, since you have a lot of background in this area of the code.

It's worth noting that we actually keep the audio device open once a tone is played by the tones module, until the next tone is played. This is because tones never calls WavePlayer.idle. So, we can pretty much eliminate any concerns about non-audible impacts of keeping the device open.

One thing to check is whether this breaks automatic system sleep, and that'll need to be checked on Windows 7 as well. If it does, that would have been true before if at least one tone was played, but the concern is that removing this code will make it impossible to fix that bug (if it exists).

**Comment by jcsteh** [comment]
> I believe changing the default device might also need us to take action, and that's not going to fire a hardware notification.

Note that there are two cases that need to be tested here:

1. Changing the system's default output device while NVDA is set to use the default output device.
2. Changing the system's default output device while NVDA is set to use a specific output device (not the default). The reason for this test is that I vaguely recall that changing the system's default output device might renumber the other devices on the system. I'm not sure, though.

**Comment by feerrenrut** [comment]
Thanks for all the information @jcsteh. 

Perhaps we should merge this approach, while we look into removing the timer and fixing #11490 more generally. 

>I'm not aware of any further race conditions

I haven't gone through it with a fine comb, but the case I specifically noticed was:
When trying to open the device, if there is a pending close timer then cancelling the close timer is queued to the main thread. There is then a race between the timer being triggered and the timer being cancelled. 

There also is a potential deadlock here. Open acquires the `_waveout_lock`, if there is a close timer pending, and we are already on the main thread, close is called immediately, it can't acquire the `_waveout_lock`. Though now I notice it is an `RLock`. 

https://github.com/nvaccess/nvda/pull/11505/files#diff-ea1b000a4d25ba3adfccce3616353820R179

> I don't really see how getting rid of closeWhenIdle makes this easier. 

Only because more asynchronous shared state makes code harder to reason about. There will be a dependence between pushing silence and the device being open, if they both need async code, there are more variations in execution sequence.

**Review by LeonarddeR — APPROVED** [review]

**Comment by beqabeqa473** [comment]
not fully related to this pr, but as discussion is going to way about
improving performance, what do you think, won't it be better to change
audio subsystem to wasapi?

for example in reaper, and such software, wasapi has much less latency
compared to other audio subsystems windows have.



On 8/18/20, Leonard de Ruijter <notifications@github.com> wrote:
> @leonardder approved this pull request.
>
>
>
>
>
> --
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/nvaccess/nvda/pull/11505#pullrequestreview-469671301


-- 
with best regards beqa

**Comment by dingpengyu** [comment]
> not fully related to this pr, but as discussion is going to way about improving performance, what do you think, won't it be better to change audio subsystem to wasapi? for example in reaper, and such software, wasapi has much less latency compared to other audio subsystems windows have.
> […](#)
> On 8/18/20, Leonard de Ruijter ***@***.***> wrote: @leonardder approved this pull request. -- You are receiving this because you are subscribed to this thread. Reply to this email directly or view it on GitHub: [#11505 (review)](https://github.com/nvaccess/nvda/pull/11505#pullrequestreview-469671301)
> -- with best regards beqa

I support switching from NVDA to WASAPI because this is the latest audio API (Windows 7/8/10/Vista).
thanks

**Comment by leonardder** [comment]
I've seen another interesting bug when running from source, probably a timing issue:

```
INFO - core.main (19:27:02.302) - MainThread (5052):
Using Windows version 10.0.20197 workstation
INFO - core.main (19:27:02.302) - MainThread (5052):
Using Python version 3.7.8 (tags/v3.7.8:4b47a5b6ba, Jun 28 2020, 07:55:33) [MSC v.1916 32 bit (Intel)]
INFO - core.main (19:27:02.302) - MainThread (5052):
Using comtypes version 1.1.7
INFO - core.main (19:27:02.302) - MainThread (5052):
Using configobj version 5.1.0 with validate version 1.0.1
ERROR - stderr (19:27:03.354) - nvwave.playWaveFile(start.wav) (9880):
Exception in thread nvwave.playWaveFile(start.wav):
Traceback (most recent call last):
  File "C:\Python37\lib\threading.py", line 926, in _bootstrap_inner
    self.run()
  File "C:\Python37\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "D:\Development\nvda\source\nvwave.py", line 292, in idle
    return self._idleUnbuffered()
  File "D:\Development\nvda\source\nvwave.py", line 307, in _idleUnbuffered
    self._closeTimer = wx.PyTimer(self._close)
  File "D:\Development\nvda\include\wxPython\wx\core.py", line 2191, in __init__
    Timer.__init__(self)
wx._core.PyNoAppError: The wx.App object must be created first!
```

This is explainable when the start sound plays before the wx app is actually there. Not a big issue but may be it's something you can look into as part of this pr?

**Comment by feerrenrut** [comment]
I'm going to close this given PR #11531 was merged.

**Pull request closed without merging**
