### PR TITLE
Fix status reporting of speech modes checkboxes

### LINKED ISSUE #16005: Speech modes status not announced when enabling/disabling from settings
### Steps to reproduce:

1. open voice settings;
2. scroll to the new list with speech modes;
3. try to enable or disable one.

### Actual behavior:

NVDA says nothing, and Braille is not refreshed.

### Expected behavior:

NVDA should say "enabled" or "disabled", and Braille update accordingly.

#### NVDA installed/portable/running from source:

Installed and ran from source.

#### NVDA version:

Alpha, but also last commit on beta branch (after release-2024.1beta2 tag).

#### Windows version:

Windows 10 22H2.

#### Does the issue still occur after restarting your computer?

Yes.

#### Have you tried any other versions of NVDA? If so, please report their behaviors.

I tried source at release-2024.1beta2 tag, that not include [this commit](https://github.com/nvaccess/nvda/commit/e4a2474e7155a8e61ae2d9df3ff9e60c1a3cb05b) from #15960, that introduced the issue.

I'll provide a fix in minutes; but considering the above commit, I'll try to make a PR on beta branch.

#### If NVDA add-ons are disabled, is your problem still occurring?

Yes.

#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?

Not relevant.

### PR DESCRIPTION
**Pull request by ABuffEr**
### Link to issue number:

Fixes #16005.

### Summary of the issue:

When enabling/disabling checkboxes in the speech modes list, under voice settings, the new status was not reported by speech or Braille.

### Description of user facing changes

Now user hears "enabled" or "disabled", and gets his Braille display refreshed.

### Description of development approach

PR #15960 has introduced a new handler of EVT_CHECKLISTBOX event for speechModesList.

But this latter is an nvdaControls.CustomCheckListBox, that already defines an handler for that event, to fix specifically this accessibility issue of wx.

So I simply put evt.Skip() at the beginning of new handler, to propagate event to custom control handler.

### Testing strategy:

Manual, with steps of #16005.

I verified also that, unchecking "talk" mode, the warning dialog (introduced by PR #15960) is still shown, and choosing "yes" or "no" the behavior remains coherent (checkbox disabled answering "yes" to continue, still enabled answering "no").

### Known issues with pull request:

None.

### Code Review Checklist:

- [ ] Documentation:
  - Change log entry
  - User Documentation
  - Developer / Technical Documentation
  - Context sensitive help for GUI changes
- [x] Testing:
  - Unit tests
  - System (end to end) tests
  - Manual testing
- [x] UX of all users considered:
  - Speech 
  - Braille
  - Low Vision
  - Different web browsers
  - Localization in other languages / culture than English
- [x] API is compatible with existing add-ons.
- [ ] Security precautions taken.

### CODE REVIEW

**Review by lukaszgo1 — COMMENTED** [review]
Please explicitly mention in your testing steps that you have verified that when the 'talk' mode is unchecked warning is shown, and answering both affirmative and negative behaves as expected.

**Comment by ABuffEr** [comment]
> Please explicitly mention in your testing steps that you have verified that when the 'talk' mode is unchecked warning is shown, and answering both affirmative and negative behaves as expected.

Done.

**Comment by CyrilleB79** [comment]
@ABuffEr, you have branched from beta branch and you have indicated that you want to have this fix merged into beta. That's OK since this fix an unreleased bug.

However this PR still targets the master branch. To target beta branch, you need to edit the title of this PR. Below the editable field allowing you to change the title of the PR, you will find combo-boxes. One of them is the target branch and you can replace master by beta, and then validate. HTH.

**Comment by ABuffEr** [comment]
Hi @CyrilleB79, thanks a lot for your tip! Done, despite some unresponsive behaviors (at least with Firefox).

**Review by seanbudd — APPROVED** [review]
Thanks @ABuffEr

**Pull request merged**
