### PR TITLE
Emoji panel: emoji search results, automation ID based event handler, catch attribute error exception when closing the panel

### LINKED ISSUE #9103: Composable Shell/cloud clipboard: clipboard status is not announced when there are no items to be pasted
Hi,

NOte: due to changes introduced to emoji panel in Windows 10 19H1 build 18305, along with Compsable Shell hosting other features such as cloud clipboard, I'll refer to "emoji panel" as Composable Shell.

The following issue arose due to oversight from 2018.3 days - resolved in Windows 10 App Essentials add-on: cloud clipboard paste won't announce things when there is nothing to be pasted.

### Background:
Windows 10 October 2018 Update (build 17763) introduces cloud clipboard, a way to synchronize clipboard data between devices and paste items from the clipboard. The user interface is powered by Composable Shell (WindowsInternal.ComposableShell.Experiences.TextInput.InputApp.exe) and resembles a list of items to be pasted.

When the computer starts, the clipboard is empty. If so, Composable Shell displays a status message. At the moment NVDA does not announce this, caused by changes to the interface/UIA tree in later Version 1809 development builds.

### Steps to reproduce:
Prerequisite: Windows 10 Version 1809 (build 17763) must be installed.

1. Press Windows+V to open cloud clipboard paste screen.
2. Close the window (Escape), then copy some text to the clipboard.
3. Go to another place (another app, for instance) and press Windows+V.
4. Press Delete while clipboard screen is displayed to remove the selected clipboard data.
5. Repeat step 4 until all items are gone.
6. Close the clipboard window and reopen it 9Windows+V).
\
### Actual behavior:
No announcement when clipboard is empty.

### Expected behavior:
NVDA says, "your clipboard is empty".

#### NVDA installed/portable/running from source:
Installed

#### NVDA version:
Alpha.16477

#### Windows version:
Windows 10 Version 1809 (build 17763)

#### Name and version of other software in use when reproducing the issue:
None

#### Other information about your system:
None

#### Does the issue still occur after restarting your PC?
Yes

#### Have you tried any other versions of NVDA?
Yes - 2018.3, 2018.4

Thanks.

### LINKED ISSUE #9104: Composable Shell: handle different aspects of modern input panel via automation ID lookup
Hi,

A slightly better way of handling #9103:

### Background
Windows 10 Fall Creators Update (Version 1709/build 16299) introduced emoji panel (powered by Composable Shell) for browsing and inserting emojis. This facility was expanded in April 2018 Update (Version 1803/build 17134) to include hardware keyboard input suggestions and dictation, and October 2018 Update (Version 1809/build 17763) introduced cloud clipboard paste along with adding skin tone modifiers for people emoji. The current 19H1 preview (build 18305) expands emoji panel portion to include kaomoji and symbols, and emoji panel will open to the last browsed emoji category instead of most recently used group when it opens.

Until now NVDA just assumed that an object located on a specific UIA tree node was emoji list. However, it led to problems such as not announcing clipboard empty status (#9103), not announcing top emoji search suggestion in Version 1809 and later (#9105), and attribute error due to the input panel parent object not being a UIA object (#9106). This became more prominent in October 2018 Update where the UIA automation ID's are different for different features of input panel.

### Describe the solution you'd like
The pull request to follow reorganizes modern input panel support by grouping handlers based on automation ID's instead of just build number. This brings several benefits:

1. Easier isolation of different features of input panel via automation ID's.
2. Better readability.
3. Solutions for problems from future builds can be traced via feature sets/build combination.

One possible drawback is lengthy event handler routine for one or more events, but with descriptions of features and bug fixes, it should make it easy for people to spot things. Also, note that automation ID's can change without notice, so one needs to keep an eye on it.

### Describe alternatives you've considered
The alternative is using build lookup, but given a release may introduce multiple features to input panel with different automation ID's it would be unmanageable.

### Additional context
Due to advances in UIA throughout Windows 10 development cycle, things can change (automation ID's, for instance), so one must keep an eye on it.

Thanks.

### LINKED ISSUE #9105: Composable Shell/emoji panel: search results for emojis are not announced
Hi,

The following issue affects Windows 10 Fall Creators Update and later but is most prominent in October 2018 Update and later. This is another one of those that requires Windows 10 App Essentials add-on:

### Steps to reproduce:
1. Open emoji panel (Windows+period).
2. Search for emojis by typing part of its name.

### Actual behavior:
Only search result count is announced, or in Fall Creators Update and April 2018 Update, the first result count is announced.

### Expected behavior:
Emoji is announced.

#### NVDA installed/portable/running from source:
Installed

#### NVDA version:
Alpha.16477

#### Windows version:
Windows 10 Version 1809 (build 17763)

#### Name and version of other software in use when reproducing the issue:
None

#### Other information about your system:
None

#### Does the issue still occur after restarting your PC?
Yes

#### Have you tried any other versions of NVDA?
Yes - 2018.3, 2018.4

### Solution:
In October 2018 Update and later, name change event is fired while emoji search is in progress, with the progress message having a unique automation ID. Thus catch this and announce the top emoji if possible.

Thanks.

### LINKED ISSUE #9106: Composable Shell: attribute error is raised when trying to obtain parent of the input panel window
Hi,

Continuing from #9104: in some cases, attribute error is raised when trying to obtain parent window of the input panel.

### Steps to reproduce:
1. Open emoji panel or cloud clipboard screen.
2. Close the screen, or if using cloud clipboard, delete items.

### Actual behavior:
A traceback is raised, pointing to AttributeError on line 39 of Composable Shell app module where the parent object retrieval is attempted.

### Expected behavior:
No errors.

#### NVDA installed/portable/running from source:
Installed

#### NVDA version:
Alpha.16477

#### Windows version:
Windows 10 Version 1809 (build 17763)

#### Name and version of other software in use when reproducing the issue:
None

#### Other information about your system:
This error does not appear all the time.

#### Does the issue still occur after restarting your PC?
Yes (sometimes).

#### Have you tried any other versions of NVDA?
Yes - 2018.3, 2018.4

Thanks.

### PR DESCRIPTION
**Pull request by josephsl**
Hi,

The foundation pull request to support Windows 10 Version 19H1 (tentatively 1903) emoji panel (the expanded input panel) and making the Composable Shell app module cleaner.

### Link to issue number:
Fixes #9103 
Fixes #9104 
Fixes #9105 
Fixes #9106 

### Summary of the issue:
Redesigned the Composable Shell app module/various event handlers, resolves some outstanding issues with Version 1809 and 19H1 emoji panel changes.

### Description of how this pull request fixes the issue:
Resolves the following:

* Window open event: instead of using build numbers and child count, automation ID will be used to select how to handle specific cases.
* Version 1809 and later: top emoji character will be announced when searching for emojis, as well as clipboard empty status will be announced.
* Attribute error will be caught when closing the panel.

### Testing performed:
Tested with various modern input features in build 17763 and later (including build 18305).

### Known issues with pull request:
Currently first selected emoji nor clipboard status won't be announced in 19H1 (build 18305) because File Explorer (not Composable Shell) is responsible for handling UIA window open event, whereas this PR works in Version 1809 (build 17763) since the latter is the one handling window open event. This limitation is subject to change.

### Change log entry:
Bug fixes:

* In Windows 10 October 2018 Update and later, when opening cloud clipboard history with clipboard empty, NVDA will announce clipboard status.
* In Windows 10 October 2018 Update and later, when searching for emojis in emoji panel, NVDA will announce top search result.

Thanks.

### CODE REVIEW

**Comment by josephsl** [comment]
Hi,

Besides Mick, if possible, I'd like to ask @feerrenrut for a visual review - that is, to see if NVDA announces things as you use the emoji panel (Windows+period) in October 2018 Update and later, specifically if clipboard status is announced and emoji search result is actually announced. Thanks.

**Comment by josephsl** [comment]
Hi,

Update: given 19h1_release branch from Microsoft has been activated (as of build 18323), this will mean a companion pull request will be created this weekend that brings UIA window open event support to File Explorer app module.

Thanks.

**Comment by michaelDCurran** [comment]
I take it that this pr is still needed as well though?

**Comment by josephsl** [comment]
Hi, yes please, as it takes care of changes to emoji panel introduced in 1809 and 19H1. Thanks.

**Review by michaelDCurran — APPROVED** [review]

**Pull request merged**
