### PR TITLE
Fix: "Selection removed" is not announced properly in Input Gestures dialog filter field (#11326)

### LINKED ISSUE #11326: Unselected is not announced properly in gesture filter field
### Steps to reproduce:

* Open gesture dialog
* In the filter field, type something, e.g. "braille"
* Press control+home and then Delete to delete the content of the filter field
* Type slowly "enable" (with English NVDA UI)

### Actual behavior:

Strangely "selection removed" message is heard when typing the "b" letter.

### Expected behavior:

Selection removed should be heard when typing the Delete key.

#### NVDA installed/portable/running from source:

From source

#### NVDA version:

alpha (commit 7023085104cc83d50775f5fa813442366abb7d50 )

#### Windows version:

Windows 10 (2004)

#### Name and version of other software in use when reproducing the issue:

N/A

#### Does the issue still occur after restarting your computer?

Yes

#### Have you tried any other versions of NVDA? If so, please report their behaviors.

Yes. 2020.2beta2 works correctly.

#### If addons are disabled, is your problem still occuring?

Yes

#### Did you try to run the COM registry fixing tool in NVDA menu / tools?

No

### Note

This issue appears in the master branch after #10307 was merged. It was known at the time of this merge. But it was decided to merge anyway since the present issue is relatively minor and to open a new Github issue. See https://github.com/nvaccess/nvda/pull/10307#issuecomment-653048505.

### PR DESCRIPTION
**Pull request by JulienCochuyt**
### Link to issue number:

Fixes #11326 
Fix-up of #10307

### Summary of the issue:

As noted by @CyrilleB79 while thoroughly testing PR #10307 (thanks again):
> * In the filter field, type something, e.g. "braille"
> * Press control+home and then Delete to delete the content of the filter field
> * Type slowly "enable" (with English NVDA UI)
> Actual behavior:
> Strangely "selection removed" message is heard when typing the "b" letter.

Also, braille does not refresh until "selection removed" is announced, despite all review commands reporting the correct content.
Investigation shows that `IAccessible.event_valueChange` is not called at all in the meantime.

### Description of how this pull request fixes the issue:

Add a small delay upon resetting the filter, so that `valueChange` events have time to propagate and be handled.

### Known issues with pull request:

I really do not feel comfortable with the proposed solution.
It is effective - at least on my side - but does not tackle the source of the issue...

### Change log entry:

None, as PR #10307 has not yet been released.

### CODE REVIEW

**Comment by JulienCochuyt** [comment]
@CyrilleB79, @feerrenrut: As you both could reproduce the issue, could you please test the try-build to check if the fix is effective on your side too?

**Comment by feerrenrut** [comment]
Given what you have found here, I think I would try to get rid of the python thread and look for a way to get a callback from wx when the thread is idle. I'm thinking of wx.timer, but that may not be correct.

**Comment by lukaszgo1** [comment]
I'd be interesting to check what events are fired using some external tool e.g. Inspect from Windows SDK. Perhaps they are fired at the proper time and the issue is somewhere in NVDA;s event handling code

**Comment by feerrenrut** [comment]
Oh, by the way this change does remove the symptoms. Though I do share your concerns about this being the right way to address the problem. It would be good to explore other options.

**Comment by JulienCochuyt** [comment]
@feerrenrut wrote:
> Given what you have found here, I think I would try to get rid of the python thread and look for a way to get a callback from wx when the thread is idle. I'm thinking of wx.timer, but that may not be correct.

If I'm not wrong, wx timers do execute in the main thread.
The point of #10307 is precisely to avoid locking the main thread with the computation effort.
Still, the `VirtualTree` refresh an category expansion occurs in the main thread - not because it is mandatory, but rather because wx otherwise consumes too much resources in ensuring thread safety, leading to a slower process.

@lukaszgo1 wrote:
> I'd be interesting to check what events are fired using some external tool e.g. Inspect from Windows SDK. Perhaps they are fired at the proper time and the issue is somewhere in NVDA's event handling code.

Please do. I'd be interested in your conclusions / fix. I didn't dig up to the `EventHandler`, only high enough to check that the `valueChanged` event didn't show up at the `NVDAObject` level. My guess is that the events emitted by the tree items being created and category expanded is taking up too much resource. Enclosing the refresh in `Freeze`/`Thaw` does not seem to affect the issue, though.

@feerrenrut wrote:
> Oh, by the way this change does remove the symptoms. Though I do share your concerns about this being the right way to address the problem. It would be good to explore other options.

Thus I guess we can fix the symptoms for now so that alpha testers aren't affected and leave an open ticket to track research of a better solution.

**Comment by lukaszgo1** [comment]
@JulienCochuyt wrote:

> @lukaszgo1 wrote:
> 
> > I'd be interesting to check what events are fired using some external tool e.g. Inspect from Windows SDK. Perhaps they are fired at the proper time and the issue is somewhere in NVDA's event handling code.
> 
> Please do. I'd be interested in your conclusions / fix. I didn't dig up to the `EventHandler`, only high enough to check that the `valueChanged` event didn't show up at the `NVDAObject` level. My guess is that the events emitted by the tree items being created and category expanded is taking up too much resource. Enclosing the refresh in `Freeze`/`Thaw` does not seem to affect the issue, though.



Testing with AccEvent from Windows SDK shows that OBJECT_TEXTSELECTIONCHANGED is fired at the right time i.e. once when selecting the entire text in the edit field and for the second time when the selection is deleted. The problem is that, as far as I can see, we are not handling OBJECT_TEXTSELECTIONCHANGED at all.

**Comment by JulienCochuyt** [comment]
@lukaszgo1 wrote:
> Testing with AccEvent from Windows SDK shows that OBJECT_TEXTSELECTIONCHANGED is fired at the right time i.e. once when selecting the entire text in the edit field and for the second time when the selection is deleted. The problem is that, as far as I can see, we are not handling OBJECT_TEXTSELECTIONCHANGED at all.

I guess we are, or some relative of it, as we properly detect selection changes in this control, even when triggered by unhandled gestures or with the mouse. Eg. type in "braille" then `control+a` leads to proper selection announce.
As far as I can tell, it really is the value change event - which should be triggered when deleting the selected text - that misses to be handled when the tree refresh kicks in at the same time.

**Comment by feerrenrut** [comment]
@lukaszgo1 Can you get some estimate for the number of events being fired?

> The point of #10307 is precisely to avoid locking the main thread with the computation effort.
My guess is that the conversion to a virtual tree has a much bigger impact on performance than filtering the items in a separate thread. The filtering is only running grep less than 1000 times. 

I suggested using `wx.Timer` (or similar) so that wx can schedule the filtering work when the app is otherwise idle.  My thinking is that if the user is rapidly typing out a filter, many events and updates are currently happening, and there is no point in doing the filter until the user has finished typing. I also get the impression (perhaps I've seen it in the wx docs somewhere) that running long running processing in the event callbacks is discouraged.

Again, before worrying about any of this it would be good to be certain that the filtering is actually taking enough time to be worth worrying about.

**Comment by feerrenrut** [comment]
I'm trying to simplify this area of code while updating #7784 it will likely make the changes here obsolete. I'd recommend not working on this one further until after #7784 is merged.

**Comment by leonardder** [comment]
I'm afraid this needs a rebase ;)

**Comment by feerrenrut** [comment]
@JulienCochuyt I have fixed the merge conflicts, and modified this solution slightly. Please take a look.

**Comment by CyrilleB79** [comment]
Any chance to merge this in beta branch rather than in alpha?
The bug is not so big. But since #10307 is integrated in 2020.3 beta branch (not yet released), it would make sense to include this PR as well.

**Comment by feerrenrut** [comment]
@CyrilleB79 Potentially, it's low risk, and self contained. I'm for the idea, but the approach still needs a review.

There is a little hesitation because this masks a real problem (likely in wx) that becomes less likely to be investigated. Ideally a minimal test case could reproduce the problem in wx and an issue opened for them to investigate.

**Review by michaelDCurran — APPROVED** [review]

**Comment by feerrenrut** [comment]
Closing this PR.

The issue is almost certainly in `editableText.py`. The likely cause (in `class EditableText`) is that `_backspaceScriptHelper` and `_deleteScriptHelper` don't take the current selection into account and how `detectPossibleSelectionChange` works.

It will likely take some fiddling to get this right.

**Comment by CyrilleB79** [comment]
> Closing this PR.
> 
> The issue is almost certainly in `editableText.py`. The likely cause (in `class EditableText`) is that `_backspaceScriptHelper` and `_deleteScriptHelper` don't take the current selection into account and how `detectPossibleSelectionChange` works.

Do you really think that `_backspaceScriptHelper` and `_deleteScriptHelper` are causing this issue? The following STR let me think that it is not the case:
* type "hello" in the filter field (without quotation marks)
* with the mouse select the word hello
* type "activatedX" (without quotation marks)
Result: the selection removal is reported only when the letter "X" is typed. I have also tried the same STR typing NVDA+F2 before each letter of "activatedX" and the result is the same.
If I am not mistaken, `_backspaceScriptHelper` nor `_deleteScriptHelper` nor any of the editing scripts of `EditableText` is called during this STR.

Moreover, if you type "qw" instead of "activatedX" the selection removal is announced as soon as you type the 2nd character (instead of the 10th for "activatedX"). It seems to me that this issue is directly linked to the filter functionality since the number of character that may be typed before the selection removal is reported seems to depend on the number of output results of the filter.

This would be something that needs to be looked into if this type of filter is implemented elsewhere.

**Comment by feerrenrut** [comment]
My last comment was a generalization. Essentially the selection change is not being tracked correctly. As you point out there are a variety of circumstances where this is true. 

But either way, I don't think the correct solution is to add a delay to changing the filter. 

When looking at this I did notice that the the maximum number of MSAA events was reached, this would be worth investigating further. Thinking about this more (and now confirming that this doesn't happen with other edit controls), I'd look into this next.

**Comment by CyrilleB79** [comment]
OK thanks.
Let's continue the discussion in #11326 if required.

**Pull request closed without merging**
