### PR TITLE
Update liblouis to 3.19.0

### PR DESCRIPTION
**Pull request by AAClause**
### Link to issue number:
None

### Summary of the issue:
Liblouis 3.19.0 has been released.

### Description of how this pull request fixes the issue:
Updates liblouis to 3.19.0 which adds 3 new braille tables, fixes several bugs and cleans the codebase. [Changelog](https://github.com/liblouis/liblouis/releases/tag/v3.19.0).

### Testing strategy:
Played with new braille tables and some others (input and output). Everything works as expected.

### Known issues with pull request:
None

### Change log entries:
Section: Changes

```
- Updated liblouis braille translator to [3.19.0 https://github.com/liblouis/liblouis/releases/tag/v3.19.0]. (#12810)
  - New braille tables: Russian grade 1, Tshivenda grade 1, Tshivenda grade 2
```

### Code Review Checklist:

- [x] Pull Request description is up to date.
- [x] Unit tests.
- [x] System (end to end) tests.
- [x] Manual testing.
- [x] User Documentation.
- [x] Change log entry.
- [x] Context sensitive help for GUI changes.
- [x] UX of all users considered:
  - Speech 
  - Braille
  - Low Vision
  - Different web browsers

### CODE REVIEW

**Comment by lukaszgo1** [comment]
It'd be great to  include this PR into 2021.3 if possible.

**Comment by Futyn-Maker** [comment]
In this release the back translation in Russian uncontracted braille was added. Can you, please, remove `input=False` in 'ru-litbrl.ctb' and 'ru-litbrl-detailed.utb'? Now the only forward translation is relevant only for 'ru-ru-g1.ctb'.
Another thing is that in the change log you've mentioned 'Russian grade 2', but it's 'Russian grade 1'.
Thanks :)

**Review by LeonarddeR — APPROVED** [review]

**Comment by aaclause** [comment]
> In this release the back translation in Russian uncontracted braille was added. Can you, please, remove `input=False` in 'ru-litbrl.ctb' and 'ru-litbrl-detailed.utb'? Now the only forward translation is relevant only for 'ru-ru-g1.ctb'.
Thanks! I had forgotten about it.


> Another thing is that in the change log you've mentioned 'Russian grade 2', but it's 'Russian grade 1'.
> Thanks :)

Also done. But something is bugging me: 
The display-name is "Russian contracted braille".
And the first line of the file is "liblouis: Russian literary (grade 1)"
Should this table be considered contracted (g2) or literary (g1)?
Thanks again!

**Comment by Futyn-Maker** [comment]
> Should this table be considered contracted (g2) or literary (g1)?

It doesn't work like in English braille, for example. As the contracted braille isn't used in Russia oficially, we don't call literary braille "uncontracted" (a lot of people won't understand it). But the system of contracted braille was developed and now consists of two grades: grade 1 (partial contraction which includes syllables, prepositions, etc. and grade 2 which includes full words).
Thus, uncontracted braille may be called "grade 0", but such name isn't recommended.

**Comment by aaclause** [comment]
@Futyn-Maker Thank for clarifying! Maybe should we add " (partial)" to the display-name (in NVDA)?

**Comment by Futyn-Maker** [comment]
@aaclause maybe later, if the grade 2 table will be made.

**Comment by codeofdusk** [comment]
NVDA uses "grade 0" in English to refer to uncontracted German Braille. For consistency, I think "grade 0" is appropriate.

**Comment by Futyn-Maker** [comment]
Maybe this is acceptable for English names of these tables, but then these names shouldn't be translated on Russian like "нулевая ступень" (grade 0) as it can result in confusions for users.
Anyway, don't recommend change them at all.

**Comment by lukaszgo1** [comment]
> 
> 
> NVDA uses "grade 0" in English to refer to uncontracted German Braille. For consistency, I think "grade 0" is appropriate.


It does so only because German braille standard refers to uncontracted Braille as grade 0. Regardless of that I don't think consistency should be a factor here. When naming LibLouis tables we should remain as close to names used in LibLouis because we're not familiar with particular Braille codes being implemented, and since someone named these tables in a particular way they presumably did so in accordance with the local Braille jargon which in turn ensures that for users of these tables they can tell from the name what notation the given table implements.

**Comment by lukaszgo1** [comment]
@michaelDCurran  Are you planning to review this in time for 2021.3?

**Review by michaelDCurran — APPROVED** [review]

**Pull request merged**
