### PR TITLE
Updating copying.txt using copying.md 

### PR DESCRIPTION
**Pull request by dpy013**
### Link to issue number:
follow up https://github.com/nvaccess/nvda/pull/16830
### Summary of the issue:
In pr 16830
copying.txt The markdown syntax has been used
### Description of user facing changes
No user changes
### Description of development approach
First the format of copying.txt was updated using copying.md
Secondly, also update the copying.txt reference in pyproject.toml to copying.md
### Testing strategy:
Need to see if appveyor can be built successfully
### Code Review Checklist:

- [ ] Documentation:
  - Change log entry
  - User Documentation
  - Developer / Technical Documentation
  - Context sensitive help for GUI changes
- [ ] Testing:
  - Unit tests
  - System (end to end) tests
  - Manual testing
- [ ] UX of all users considered:
  - Speech
  - Braille
  - Low Vision
  - Different web browsers
  - Localization in other languages / culture than English
- [ ] API is compatible with existing add-ons.
- [ ] Security precautions taken.

@coderabbitai summary

### CODE REVIEW

**Comment by seanbudd** [comment]
You'd also have to update every reference in NVDA, particularly copyright headers, to use the new file name / link. I don't think this is a good idea for now

**Comment by XLTechie** [comment]
@seanbudd what about making the old file a reference to the new one, and update specific headers as PRs come through?

Could retain the content but with a note at the top.

"This file has moved ..."

**Comment by seanbudd** [comment]
I don't think it's a good use of time but feel free to open an issue

**Comment by XLTechie** [comment]
@dpy013 I have no great interest, it was just an idea, but maybe that's a direction you could go.

**Pull request closed without merging**
