### PR TITLE
pr11650 with fix for addon paths

### PR DESCRIPTION
**Pull request by michaelDCurran**
This is a replacement of pr #11650  containing all original commits, but with one extra commit that stops an infinite while loop in addonHandler.getCodeAddon when loading an addon that has translations (such as nvdaRemote).

### CODE REVIEW

**Comment by michaelDCurran** [comment]
for those reviewing, only commit 2ae3811a1c50edac is new.

**Comment by michaelDCurran** [comment]
I can successfully run this commit with NVDARemote. But I would welcome testing by others.

**Review by codeofdusk — APPROVED** [review]
Looks okay to me.

**Review by josephsl — APPROVED** [review]
At least add-ons are working.

**Pull request merged**
