### PR TITLE
metec braille display driver to communicate with TCP-IP on localport 2018

### PR DESCRIPTION
**Pull request by metecAB**
**Link to issue number:**
Does not apply.

**Summary of the issue:**
TCP-IP communication with all metec braille devices over the metec MVBD software.
It uses the port 2018 on the localhost.

**Description of how this pull request fixes the issue:**
This branch is kept up to date with new Braille displays from metec

**Testing performed:**
Tested with current models and MVBD v. 137

**Known issues with pull request:**
None

**Change log entry:**
Support of all metec devices

### CODE REVIEW

**Comment by josephsl** [comment]
Hi,

Two important questions:

1. Is there other connection method besides LAN?
2. Can you fill out the template please?

Thanks.

**Comment by metecAB** [comment]
1. No. At the moment we support only LAN.
2 . It is filled out

**Comment by Adriani90** [comment]
Is this PR ready for review? Or is it a draft?
If it is ready for review, you can request a review from NV Access.

**Comment by metecAB** [comment]
Yes it is ready for review

**Comment by feerrenrut** [comment]
> TCP-IP communication with all metec braille devices over the metec MVBD software.

I assume this is intended for end users, not just for developers? The application and technical documentation is available here:
https://download.metec-ag.de/MVBD/

Please fix flake8 (code lint) failures, see AppVeyorBot comment: https://github.com/nvaccess/nvda/pull/10712#issuecomment-577652121
The comment by that bot has a link to 'test results'. Click on `flake8.lint.flake8_diff_lint` to see the test output. 

It is much faster to fix these errors if you run this on your machine locally with `scons lint base=origin/master` (see readme.md in NVDA repository for more info) 

A quick browse of this code shows me that there are lots of ["magic numbers" ](https://en.wikipedia.org/wiki/Magic_number_(programming)) which will make this hard for us to maintain longer term. Please add more information about what these lines mean so we have a chance to maintain it, in particular:
- `data = "{cmd}{l0}{l1}{s}".format( cmd=chr(29), l0=chr(1), l1=chr(0), s=chr(2) )`
- `data = "{cmd}{l0}{l1}{mask0}{mask1}{mask2}{mask3}{enabled}".format( cmd=chr(56), l0=chr(5),l1=chr(0),   mask0=chr(64), mask1=chr(0), mask2=chr(0), mask3=chr(0),   enabled=chr(1) )`
- There are several other examples.

Instead of:
```
l=len(s)
l0 = (l >> 0 ) & 0xFF
l1 = (l >> 8 ) & 0xFF
```
Please dont use just `l` as a variable name, it's hard to differentiate from `I`, maybe `sLen` or just use the result directly.
use `sLen.to_bytes(length=2, byteorder="little", signed=False)` where `someInt` 
For examples of this in other drivers take a look at the following: https://github.com/nvaccess/nvda/search?q=to_bytes&type=Code

**Comment by dingpengyu** [comment]
hello @metecAB 
Please fix flake8 (code lint) failures,
thanks

**Review by feerrenrut — CHANGES_REQUESTED** [review]
It may not have been clear that I had questions and requests for changes in my last comment:
https://github.com/nvaccess/nvda/pull/10712#issuecomment-579326777

**Comment by Adriani90** [comment]
@metecAB could you please follow up on the questions and comments from @feerrenrut and address the coresponding review actions? Thanks.

**Comment by feerrenrut** [comment]
@Adriani90 Given the time past, I'm going to mark this as abandoned. Someone else will need to take over this work. Though given the reluctance of @metecAB to address this feedback, it doesn't bode well for their inclination to maintain this driver on an ongoing basis, perhaps the PR should be rejected instead?

**Comment by metecAB** [comment]
Please make all undo and delete it.

Von: Reef Turner <notifications@github.com>
Gesendet: Dienstag, 18. August 2020 10:16
An: nvaccess/nvda <nvda@noreply.github.com>
Cc: Andreas Baumüller <ab@metec-ag.de>; Mention <mention@noreply.github.com>
Betreff: Re: [nvaccess/nvda] metec braille display driver to communicate with TCP-IP on localport 2018 (#10712)


@Adriani90<https://github.com/Adriani90> Given the time past, I'm going to mark this as abandoned. Someone else will need to take over this work. Though given the reluctance of @metecAB<https://github.com/metecAB> to address this feedback, it doesn't bode well for their inclination to maintain this driver on an ongoing basis, perhaps the PR should be rejected instead?

**Comment by feerrenrut** [comment]
It seems that part of the difficulty here may be due to a language barrier. Is there anyone willing to translate?

**Comment by lukaszgo1** [comment]
Since  no one expressed interest in moving this forward for several months  what about closing this PR and marking as closed/needs-new-author?

**Comment by feerrenrut** [comment]
@lukaszgo1 Yes, unfortunately that seems to be the way this will have to go. I'd love to take this on, but I can't justify it against our other priorities. Happy to provide guidance to anyone willing to work on this. But I fear that without the appropriate hardware to test it will be difficult to verify correctness.

**Pull request closed without merging**
