### PR TITLE
Update liblouis to 3.24.0

### PR DESCRIPTION
**Pull request by AAClause**
### Link to issue number:
None

### Summary of the issue:
Liblouis 3.24.0 has been released.

### Description of user facing changes
Updates liblouis to 3.24.0 which adds new braille tables. [Changelog](https://github.com/liblouis/liblouis/releases/tag/v3.24.0).

### Description of development approach
Update liblouis submodule and make new braille tables available from the NVDA settings.

### Testing strategy:
Ran from sources and loaded new braille tables. LGTM.

### Known issues with pull request:
None

### Change log entries:
Section: Changes

```
- Updated liblouis braille translator to [3.24.0 https://github.com/liblouis/liblouis/releases/tag/v3.24.0]. (#14436)
  - Major updates to Hungarian, UEB, and Chinese bopomofo braille.
  - Support for the Danish braille standard 2022.
  - New braille tables for Georgian literary braille, Swahili (Kenya) and Chichewa (Malawi).
```

### Code Review Checklist:

- [x] Pull Request description:
  - description is up to date
  - change log entries
- [ ] Testing:
  - Unit tests
  - System (end to end) tests
  - Manual testing
- [x] API is compatible with existing add-ons.
- [x] Documentation:
  - User Documentation
  - Developer / Technical Documentation
  - Context sensitive help for GUI changes
- [x] UX of all users considered:
  - Speech 
  - Braille
  - Low Vision
  - Different web browsers
  - Localization in other languages / culture than English
- [x] Security precautions taken.

### CODE REVIEW

**Comment by leonardder** [comment]
Could you please remove the following lines from nvdaHelper/liblouis/sconscript?

```
# Starting from Clang 15, the -Wint-conversion warning diagnostic for implicit int <-> pointer conversions
# now defaults to an error in all C language modes.
# Downgrade this to a warning so we can still build.
env.Append(CCFLAGS='-Wno-error=int-conversion')
```

This was fixed in https://github.com/liblouis/liblouis/pull/1263 and is therefore no longer necessary.

**Comment by zstanecic** [comment]
Hi,

I am voting here as one of the translators:

It doesn’t make a difference, because users should have access both to the new and old standard. The example is Korean. As I recall, Korean has pre 2006 and after 2006 standard, and both braille tables, as wel as g1 and g2 are available.

So, why to make here exception or difference?

The Danish people, who are used to old standard, should have access to it, as well as to the new one.

By the way, why we need to specify braille tables manually every release of liblouis?

Why we cannot use metadata and get rid of this shame?

**Comment by seanbudd** [comment]
Is there anything NVAccess needs to do or decide to unstick this PR?

**Comment by zstanecic** [comment]
Hi Andre!

Yes, i suggest exactly the solution you provided,

First instead of second.

**Comment by zstanecic** [comment]
So, it will be good to have tables named like this:

• Danish 8 dot grade 1

• Danish 8 dot grade 1 (1993)

• Danish 8 dot grade 2

• Danish 8 dot grade 2 (1993)

**Comment by seanbudd** [comment]
Either option seems fine to me

**Review by seanbudd — APPROVED** [review]

**Pull request merged**
