### PR TITLE
Update NSIS to 3.08

### LINKED ISSUE #13270: NVDA installer does not start if special characters are in the installer path
See also: #9134

### Steps to reproduce:

1. Create a new folder named: `Testé ç ş ğ`
   - copy and paste to preserve characters, there are 4 special characters in this string
1. Place a copy of a NVDA installer (eg 2021.3.1) in the folder named "`Testé ç ş ğ`"
1. Run the installer from the folder
1. Observe popup dialog "NSIS Error" "Error launching installer" 
1. Note that no nvda log is created, this is an early failure.

### Actual behavior:

NVDA installer does not start if special characters are in the installer path

### Expected behavior:

NVDA installer should start if special characters are in the installer path

#### NVDA installed/portable/running from source:

Installer

#### NVDA version:

2021.1 , 2021.1.3, alpha-24501,b45926cd

#### Windows version:

Windows 11 (10.0.22000 Build 22000)

### LINKED ISSUE #13329: problems installing nvda in windows 11 insider preview for ARM
I can't install nvda in windows 11 for arm. When I launch the installer it gives me an NSI error loading installer and there's nothing I can do about it.

### PR DESCRIPTION
**Pull request by seanbudd**
### Link to issue number:

Fixes #13270, #9134

May fix #13329, #13222

- NSIS 2.51 has been removed from miscDeps in https://github.com/nvaccess/nvda-misc-deps/pull/24
- NSIS 3.08 has been added to a new submodule in https://github.com/nvaccess/NSIS-build/pull/2
- Steps for updating NSIS have been added in https://github.com/nvaccess/NSIS-build/pull/1

### Summary of the issue:

NSIS is outdated (version 2.51 is from 2016).
A variety of issues have been coming up with the installer:
- If special characters are in the path, the NSIS fails to run the installer
- Installer is failing to start on certain builds of Windows (Windows 7 SP1, Windows 11 ARM, Windows 10 21H2)

### Description of how this pull request fixes the issue:

- NSIS has been moved to its own submodule (currently private while reviewing the repository settings).
  - this includes adding steps for updating in the future
- NSIS has been updated to 3.08.
- The UAC plugin has been removed, as it is now redundant.
    - NSIS elevates the uninstaller automatically now, rather than needing the UAC plugin. This has been confirmed with testing.
- Minor build warnings have been fixed.

### Testing strategy:

Follow the testing strategy in the [NSIS submodule readme](https://github.com/nvaccess/NSIS-build/blob/3c884aefe7cbf943036fefd9488466c5522d101e/readme.md#testing)

Testing confirmed on:
- [ ] Windows 11 ARM
- [x] Windows 11
- [x] Windows 10
- [ ] Windows 7 SP1

### Known issues with pull request:

None

### Change log entries:

Bug fixes
```t2t
- The NVDA installer can now run from directories with special characters. (#31270)
- Other entries if #13329, #13222 being fixed is confirmed.
```

Changes
```t2t
- NSIS has been updated to version 3.08. (#9134)
```

### Code Review Checklist:

- [x] Pull Request description:
  - description is up to date
  - change log entries
- [ ] Testing:
  - Unit tests
  - System (end to end) tests
  - Manual testing
- [x] API is compatible with existing add-ons.
- [x] Documentation:
  - User Documentation
  - Developer / Technical Documentation
  - Context sensitive help for GUI changes
- [x] UX of all users considered:
  - Speech 
  - Braille
  - Low Vision
  - Different web browsers
  - Localization in other languages / culture than English

### CODE REVIEW

**Comment by leonardder** [comment]
I think there are several reasons to no longer bundle nsis with NVDA:

* It is part of the [Appveyor image](https://www.appveyor.com/docs/windows-images-software/). This ensures we're always up to date with NSIS, which shouldn't be a problem as we no longer use a separate plugin now.
* People who build launchers usually have the knowledge to keep nsis up to date. We can simply list it as an optional dependency if you want to create a launcher. To put it the other way around, why should we bother about bundling nsis while we want people to install Visual Studio and Python themselves? They can also install NSIS which is pretty straight forward. There is more to be said for bundling Python 3.7 now that installers are no longer being built and the version on appveyor is no longer up to date.
* No longer bundling NSIS means there's no longer a maintenance burden to keep it up to date.

**Comment by lukaszgo1** [comment]
>     * The UAC plugin has been removed, as it is now redundant.

I would like to have more explanation on this preferably with the link to some relevant NSIS documentation. At the very least something more than "the plugin is redundant" as that does not answer "why".

**Comment by seanbudd** [comment]
>I would like to have more explanation on this preferably with the link to some relevant NSIS documentation. 

Sadly this is undocumented - or at least I could not find any after spending a long time searching.
NSIS elevates the uninstaller automatically now, rather than needed the UAC plugin.
This has been confirmed with testing.

**Comment by seanbudd** [comment]
>No longer bundling NSIS means there's no longer a maintenance burden to keep it up to date.

I don't think this is true. Like any dependency, an update might break NVDA.
Without being able to pin a version, that maintenance cost becomes an immediate pressure, rather than an scheduled task.
As NSIS is used for the installer, updating it has relatively higher risk.
By using the latest NSIS on AppVeyor, without pinning to a version, we risk the installer breaking without us knowing.
If NSIS updates around the time of a release, and the update breaks Windows 7 compatibility, we could push out a broken release.

On the other hand, the process of updating NSIS (once it is it's own submodule) is relatively straightforward.
Keeping it up to date should have a low maintenance cost moving forward.

**Review by feerrenrut — APPROVED** [review]
Changes look good, though the miscDeps commit should be updated if there is a new commit created when https://github.com/nvaccess/nvda-misc-deps/pull/24 is merged to ensure it is left in an easy to understand state (miscDeps submodule will then point to the most recent commit on miscDeps master)

**Review by michaelDCurran — APPROVED** [review]

**Comment by CyrilleB79** [comment]
@seanbudd, if it is confirmed that this upgrade fixes the various installation issues, would you consider cherry-pick this commit to beta for 2022.1?
It would seem strange to me not to provide a solution as soon as possible for people who can not install NVDA at all.
Cc @feerrenrut  for his opinion.

**Comment by lukaszgo1** [comment]
> if it is confirmed that this upgrade fixes the various installation issues, would you consider cherry-pick this commit to beta for 2022.1? It would seem strange to me not to provide a solution as soon as possible for people who can not install NVDA at all. 

This seems pretty risky to me. Granted for some people the situation may be improved but this is a rather significant change to a critical component, and there is no saying if  installer would not become broken on some other configurations.

**Pull request merged**
