### PR TITLE
Upgraded comtypes to 1.1.7

### LINKED ISSUE #9440: Upgrade to comtypes 1.1.7
### Is your feature request related to a problem? Please describe.

I saw that UIA is a bit slow than other screen readers (in stable releases), but after some testing I saw a better performance with this version of comtypes, not so much, but it is notable.

### Describe the solution you'd like

I don't know what should be the correct solution, because a comment from @leonardder on #8522. I was searching for the particular bug and I didn't found anything.

### Describe alternatives you've considered

I whas thinking about NVDA object caching, primarily for UIAHandler because it has a bad performance, same to JABHandler. I'm planning to do some testing today.

### Additional context

I saw in UIAHandler that every time that an event ocurs a new object is created. I suppose that it takes some time to instantiate it, and it impacts to NVDA's performance in heavy UIAutomation applications, such Visual Studio.

### PR DESCRIPTION
**Pull request by francipvb**
### Link to issue number:

Closes #9440, #8522

### Summary of the issue:

This PR is mainly to improve UIAutomation support.

I use visual studio regularly and it is a particularly heavy application. It runs background tasks and these impacts the user interface.

However, I upgraded comtypes locally to do some testing and I saw some results regarding performance.

### Description of how this pull request fixes the issue:

This upgrades from enthought/comtypes@edbaf3bfb7b0c68daa6ee8eac4a770dc66e296ec to  enthought/comtypes@1d3d38b2a616674309e7eabe6b5c581042caf32a

### Testing performed:

Tested NVDA running from source code against Visual Studio 2017 and 2019. Got performance improvements with both of versions.

### Known issues with pull request:

None known.

### Change log entry:

Added by @leonardder 
* Changes for developers
    + Updated comtypes package to 1.1.7. (#9440)

### CODE REVIEW

**Comment by francipvb** [comment]
P.S: I'm posting this mainly to test binary builds from the build server.

Cheers,

**Comment by michaelDCurran** [comment]
Do you have any guess as to what exactly changed to give the better performance? I don't see anything too interesting in their changelog...

**Comment by leonardder** [comment]
[Here](https://ci.appveyor.com/api/buildjobs/y12fqgwnf18nklhm/artifacts/output%2Fnvda_snapshot_try-comtypes-17006%2C0e44718f.exe) is a signed try build, which really helps in testing these things.

**Comment by leonardder** [comment]
We have:

* Fix hang in ``CreateObject`` for restricted user (enthought/comtypes#124).

I don't think that's related.

**Review by LeonarddeR — CHANGES_REQUESTED** [review]
It looks like I can't reproduce the issue I had that was caused by https://github.com/enthought/comtypes/commit/98f6a42e8b452c67a65848d1c4476fb37df2aa6a, so that's good.

Could you please update the readme to refer to comtypes 1.1.7?

**Comment by lukaszgo1** [comment]
As readme is now updated could you add #8522 to the list which this pr closes @francipvb ?

**Comment by francipvb** [comment]
Hello,

I have addressed the changes you requested.



@MichaelDCurran wrote
> Do you have any guess as to what exactly changed to give the better performance? I don't see anything too interesting in their changelog...

About performance comment on the issue, I did some testing before posting this PR and I saw that the performance improvement is a side effect of another change, but I was unable to determine what is the cause, there are no changes on UIAHandler's code nor UIA objects since release 2019.1 (python part).

Well, perhaps I didn't found them.

---

I think that this is interesting for addon developers:

> 
> 
> * Fix using temp directory as a cache folder when it has no write permission.

Cheers,

**Comment by leonardder** [comment]
> the performance improvement is a side effect of another change

Just to make sure, are you saying that Comtypes 1.1.7 does not affect performance?

**Comment by francipvb** [comment]
Hello,

I ran two profiling sessions and I got some results.

In fact, there is no difference in the performance, so I don't know where is the change that caused this.

For completeness, here are the profile session files.

Cheers,

[profiler-output.zip](https://github.com/nvaccess/nvda/files/3065428/profiler-output.zip)

**Review by LeonarddeR — APPROVED** [review]

**Review by feerrenrut — APPROVED** [review]

**Comment by feerrenrut** [comment]
Ah... it looks like in commit 92d8487ac3b2d425814eccbf6444148c2bdae320 the readme file has been changed causing a conflict here. I assume line endings have been changed.

**Comment by feerrenrut** [comment]
I've merged master and pushed the result.

**Comment by zstanecic** [comment]
Hi,

Will this be merged to treshold?

**Comment by feerrenrut** [comment]
For now it's been merged to master. The threshold branch will be updated from master occasionally. Why do you ask?

**Comment by zstanecic** [comment]
I ask, as i’ve switched to it, and I am wanting to help as a translator and as a tester, especially when testing braille in py3.

**Comment by feerrenrut** [comment]
I expect the threshold branch to be quite unstable initially, we will likely be quite aware of this. You are welcome to continue using it, however, please wait until we start requesting testers and feedback before creating new issues for it.

**Pull request merged**
