### PR TITLE
Downgrade to Python 3.7 due to stack corruption in Python 3.8+

### LINKED ISSUE #12152: SAPI4 crashes in alpha-21882,528d5708
### Steps to reproduce:
1. Install SAPI4 along with a synthesizer. The SAPI4 runtimes can be found at http://web.archive.org/web/20150910165037/http://activex.microsoft.com/activex/controls/sapi/spchapi.exe, and a free and legal synthesizer can be found at http://web.archive.org/web/20150910005021if_/http://activex.microsoft.com/activex/controls/agent2/tv_enua.exe.
2. Load sapi4.
### Actual behavior:
The synthesizer loads, but NVDA crashes soon after.
### Expected behavior:
No Crash.
#### NVDA installed/portable/running from source:
Installed.
#### NVDA version:
alpha-21882,528d5708
#### Windows version:
Windows 10, Build 21327.
#### Name and version of other software in use when reproducing the issue:
N/A.
#### Other information about your system:
N/A
#### Does the issue still occur after restarting your computer?
Yes.
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
Yes, alpha-21877,8e4b189b works normally.
#### If add-ons are disabled, is your problem still occurring?
Yes
#### Did you try to run the COM registry fixing tool in NVDA menu / tools?
Yes.

### LINKED ISSUE #12154: Python 3.8:  Impossible to navigate in Windows Explorer under Windows Server 2012.
### Steps to reproduce:
1. Launch recent Alpha based on Python 3.8
2. Open run dialog with Windows + R, type `%temp%` press enter and attempt to navigate in the newly opened folder.

### Actual behavior:
Windows error sound plays and NVDA crashes and restarts. If the folder view is still focused after restart NVDA crashes again.

### Expected behavior:
Windows Explorer should be navigable with NVDA
#### NVDA installed/portable/running from source:
Tested with both portable and installed
#### NVDA version:
alpha-21882,528d5708
#### Windows version:
Windows Server 2012.
#### Name and version of other software in use when reproducing the issue:
Windows Explorer
#### Other information about your system:
None relevant.
#### Does the issue still occur after restarting your computer?
Yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
2020.4 works okay, latest Python 3.7 based Alpha works okay.

#### If add-ons are disabled, is your problem still occurring?
Yes
#### Did you try to run the COM registry fixing tool in NVDA menu / tools?
Yes with no effect.

The attached zip file contains log at debug level and NVDA crash dump file.
[crash.zip](https://github.com/nvaccess/nvda/files/6123381/crash.zip)

### PR DESCRIPTION
**Pull request by michaelDCurran**
### Link to issue number:
Fixes #12152 
Fixes #12154 

### Summary of the issue:
Since upgrading to Python 3.8, several serious crashes in NVDA have been reported. Specifically:
* NVDA crashing when using the SAPI4 speech synthesizer: #12152 
* NVDA crashing when using Windows Explorer on Windows Server 2012: #12154 

Both of these issues were traced to stack corruption after a Python callback of NVDA's was called from external libraries. In SAPI4's case, after calling NVDA's implementation of `ITTSBufNotifySink::TextDataStarted`, and in the Windows Server 2012 case: `IUIAutomationPropertyChangedEventHandler::handlePropertyChangedEvent`.

It seems as though `libFFI` / Python `ctypes` is not cleaning the stack properly after executing a Python callback with the `stdcall` calling convention (`ctypes WINFUNCTYPE`), where the callback contained at least one argument larger than 4 bytes (E.g. a `long long`, or a `VARIANT struct`), and the arguments preceding it were such that this argument was not aligned to an 8 byte boundary. E.g. the callback might be:
* `callback(void*, long long)` or
* `callback(void*, void*, int, VARIANT)`

See Python bug: https://bugs.python.org/issue38748
On that bug I have attached a minimal testcase.

This bug affects both Python 3.8 and Python 3.9.
The bug is most likely in the [`libFFI` project](https://github.com/libFFI/libFFI) used by Python's `ctypes` module. Python 3.8 switched to a much more recent and official version of `libFFI` I believe.

Although we do really want to move to Python 3.8+ as soon as we can, right now this bug makes it impossible to do so. We could specifically work around the currently known manifestations by moving some of that code into C++, but that brings its own risks, and we still don't know where else this issue may appear in our code. The appropriate thing to do right now is stay on Python 3.7 until we can work with Python / `libFFI` to get this resolved. 

 ### Description of how this pull request fixes the issue:
Downgrades to Python 3.7 by referencing Python 3.7 (rather than 3.8) in NVDA's build system.

The existing PRs that needed to be reverted were:

* Updating `brlAPI` to a Python 3.8 build: nvaccess/nvda-misc-deps#20
* Switching to using Python's own `pgettext`: #12109 
* calling `os.add_dll_directory` when loading `liblouis`: #12020  

None of these PRs provided any user visible changes.

The rest of the Python 3.8 work, including the switch to a virtual 
environment etc is all compatible with Python 3.7 and can remain.

### Testing strategy:
* Successfully Ran unit tests
* Successfully ran system tests
* Ran locally for a while
* The reporters of the SAPI4 and Windows server 2012 issues report the crashes are gone when testing a try build of this branch.

### Change log entry:

None needed.

### Code Review Checklist:

This checklist is a reminder of things commonly forgotten in a new PR.
Authors, please do a self-review and confirm you have considered the following items.
Mark items you have considered by checking them.
You can do this when editing the Pull request description with an x: `[ ]` becomes `[x]`.
You can also check the checkboxes after the PR is created.

- [x] Pull Request description is up to date.
- [x] Unit tests.
- [x] System (end to end) tests.
- [x] Manual tests.
- [x] User Documentation.
- [x] Change log entry.
- [x] Context sensitive help for GUI changes.

### CODE REVIEW

**Comment by XLTechie** [comment]
Assuming that this is likely to take a while to be resolved (given that they 
didn't before now), is it possible we could jump straight to 3.10 instead of 
continuing incrementally to 3.8, after this is fixed?

**Comment by michaelDCurran** [comment]
This definitely should be considered, yes.

**Comment by dingpengyu** [comment]
> Assuming that this is likely to take a while to be resolved (given that they didn't before now), is it possible we could jump straight to 3.10 instead of continuing incrementally to 3.8, after this is fixed?
Support in one step

**Comment by lukaszgo1** [comment]
Please also revert #12141.

**Comment by lukaszgo1** [comment]
Have you considered bringing back code from #12042 which  prevents people from attempting to build with Python 3.7.6?  While it is unlikely someone would try the warning in the readme and in the sconscript does no harm and the code is already written.

**Comment by josephsl** [comment]
Hi, I think it doesn’t matter as latest binary release is 3.7.9 (of course the latest release is 3.7.10 which is source code only release). Thanks.

**Review by feerrenrut — CHANGES_REQUESTED** [review]
Looks good to me. 

- As mentioned by @lukaszgo1, we should remove the lines from the userguide: https://github.com/nvaccess/nvda/pull/12141
- It makes sense to reintroduce the code to check for 3.7.6 from #12042. That version of python does not work with NVDA, although it is old, people are often unaware they are on an old version.

``` python
# in sconscript
if sys.version_info.micro == 6:
	# #10696: Building with Python 3.7.6 fails. Innform user and exit.
	Py376FailMsg = "Building with Python 3.7.6 is not possible.\nPlease use more  recent version of Python 3."
	raise RuntimeError(Py376FailMsg)
```

**Comment by XLTechie** [comment]
Although perhaps correct the spelling of "inform" from "Innform".
And insert the word "a" before the word "more" in the error message.

Reef Turner wrote:

> # in sconscript
> if sys.version_info.micro == 6:
> 	# #10696: Building with Python 3.7.6 fails. Innform user and exit.
> 	Py376FailMsg = "Building with Python 3.7.6 is not possible.\nPlease use more  recent version of Python 3."
> 	raise RuntimeError(Py376FailMsg)

**Review by feerrenrut — APPROVED** [review]
Thanks @michaelDCurran

**Pull request merged**
