### PR TITLE
Beta to master

### PR DESCRIPTION
**Pull request by seanbudd**
## Summary by CodeRabbit

- **New Features**
	- Enhanced upload process for translation files to Crowdin, improving efficiency by checking for changes before uploading.
	- Updated braille table descriptions for better clarity and added new options for Greek and Thai braille tables.
	- Significant updates to localization files for various languages, improving accuracy and clarity of translations for braille tables and NVDA commands.

- **Bug Fixes**
	- Improved string formatting in the Albatross driver for clearer user instructions.

- **Documentation**
	- Updated development environment documentation to reflect the latest version of the `liblouis` dependency.

### CODE REVIEW

**Comment by codeofdusk** [comment]
This merge overwrote the 2025.1 changelog: when I look at "what's new" on the latest `master`, I only see 2024.4 changes, no 2025.1 ones.

**Comment by seanbudd** [comment]
I see it just fine here: https://github.com/nvaccess/nvda/blob/master/user_docs/en/changes.md

**Comment by codeofdusk** [comment]
The [generated artefact](https://appveyor-artifacts-enam.7b474ce6bd9813bd1e711f7cdc19151f.r2.cloudflarestorage.com/nvaccess-33499/nvda/master-33901/5txkm3f77l75f0ib/output/nvda_snapshot_alpha-33901%2C88be74a6_changes.html?X-Amz-Expires=300&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=23e97e8f2c472db9a7966a0f1cd5e0c6/20240909/us-east-1/s3/aws4_request&X-Amz-Date=20240909T072940Z&X-Amz-SignedHeaders=host&X-Amz-Signature=e3bf921208d3d6876043f7e0f108ed310b0c1406546930f622d60181d392281c) isn't...

**Comment by seanbudd** [comment]
@codeofdusk - I believe that's because we are using the xliff data from beta to generate html files now. @michaelDCurran - can you please confirm this is expected?

**Comment by michaelDCurran** [comment]
Hmm. That should be true for all languages other than English.
For English it should not generate intermediate markdown from its xliff 
for building the html. Rather It should just use the markdown file that 
was there.
I'll look into this.

**Pull request merged**
