### PR TITLE
Add support for VitalSource Bookshelf (#7155)

### PR DESCRIPTION
**Pull request by nvdaes**
### Link to issue number:
#7155

### Summary of the issue:
When closing dialogs or menus from a document of Bookshelf, a pane is wrongly focused and the cursor doesn't move to the book automatically, which is anoying for instance after searching text with NVDA+control+f.

### Description of how this pull request fixes the issue:
windowUtils is used to get the current document, and when event_gainFocus in pane objects is fired, the setFocus() method of the document object is used so that the cursor moves to the right position of the book.

### Testing performed:
Tested in master-14289,6c85ce59, and NVDA 2017.2 for several months.

### Known issues with pull request:
None

### Change log entry:
* New features
- Add support for VitalSource Bookshelf (#7155)

### CODE REVIEW

**Comment by codeofdusk** [comment]
Any updates on this one?

**Comment by nvdaes** [comment]
Hi, the same app module is implemented in an add-on posted on the NVDA add-ons community website. Also, you can use Azardi in Nvda 2017.-4.

Enviado desde mi iPhone

**Review by feerrenrut — APPROVED** [review]
Code looks ok to me, I don't use VitalSource so I personally haven't tested this. Given that this has already been tested in the form of an addon I think it is fairly low risk. I will incubate it and we will find out what the community thinks.

**Comment by nvdaes** [comment]
Thanks @albzan for reviewing the add-on and accepting is as appropiate to the add-ons website for the community testing and usage, and @feerrenrut for this.
I've tested it in nvda_snapshot_next-14766,cfd96306 and it works fine for me.

**Pull request merged**
