### PR TITLE
Improve presentation of checkable list items

### LINKED ISSUE #8554: Handle selectable checkboxes as list items when speaking selected state
cc @dkager

### Steps to reproduce:
1. Open windows disk cleanup by typing cleanmgr in the run window.
2. Select a drive if applicable
3. Use arrow keys and object navigation in the resulting list.

### Actual behavior:
For a focused (selected) item, NVDA says: Downloaded Program Files  check box  selected checked  0 bytes  1 of 10
For an unselected item, NVDA says: Downloaded Program Files  check box  checked  0 bytes  1 of 10

### Expected behavior:
For a focused (selected) item, NVDA says: Downloaded Program Files  check box  checked  0 bytes  1 of 10
For an unselected item, NVDA says: Downloaded Program Files  check box  not selected checked  0 bytes  1 of 10

### LINKED ISSUE #8857: Handle checkable list view controls as list views with columns
### Steps to reproduce:
1. Install the "Add-on Updater" add-on, since as far as I know, for the time being that is the only component for NVDA that has the new checkable list view controls with multiple columns.
2. Make sure that you have at least 2 add-ons that require updating.
3. Check for updates for your installed add-ons, by going to NVDA menu -> Tools -> Check for add-on updates.
4. When the dialog with the available add-on updates appears, focus the checkable list view control listing the available add-on updates.
5. Use NVDA's table navigation commands (Control+Alt+Arrows by default) to navigate between rows and columns in the checkable list view control.

### Actual behavior:
NVDA's table navigation commands appear not to work for this type of checkable list view control, as they do for standard list view controls with multiple columns. NVDA stays silent when the commands are executed.

### Expected behavior:
NVDA's table navigation commands should work for this type of checkable list view control, as they do for standard list view controls with multiple columns. NVDA should be able to read information column by column in this type of checkable list view control, as it does in standard list view controls.

### System configuration:
- Operating system: Windows 10 Pro version 1809 (build 17763.55), 64-bit, in Bulgarian with all locale settings set to "Bulgarian".
- NVDA version: alpha-16164,8a7da1d4.
- "Add-on Updater" add-on version: 20181018.
- Processor: Intel Core i5-4670 at 3.40GHz.
- RAM Memory: 8.00GB.
- Graphics: MSI GeForce GTX-1050TI Gaming X 4G, 4096MB dedicated memory + 4065MB shared system memory, desktop resolution set to 1920x1080.
- Sound Card: Realtek ALC887 at Intel Lynx Point PCH - High Definition Audio Controller.

#### Does the issue still occur after restarting your PC?
Yes, it does.

#### Have you tried any other versions of NVDA?
No.

### PR DESCRIPTION
**Pull request by LeonarddeR**
### Link to issue number:
Fixes #8554
Fixes #8857

### Summary of the issue:
SysListView32 Checkable list items, such as in disk cleanup manager, are presented differently from regular Syslistview32 list items.

For regular list items, we have custom code that constructs a name from all the columns of the list item. However, for checkable list items, this logic does not apply. Therefore, only the first column is presented in the name, the other columns in the description. Also, fake table navigation is not available on these items.

### Description of how this pull request fixes the issue:
1. syslistvie32 items with a role of CHECKBUTTON will now also have the syslistview32 ListItem class, which adds table navigation support to them. For fake table cells, the checked state is discarded.
2. Checkboxes with the selectable state are now treated as list items in such a way that the unselected state is announced for them instead of the selected state.

### Testing performed:
Tested table navigation and object navigation in disk cleanup, all worked as expected.

### Known issues with pull request:
None

### Change log entry:
* Changes
    + You can now utilize table navigation in list boxes with checkable list items when the particular list has multiple columns. (##8857)

* Bug fixes
    + For checkable list items, the selected state is no longer announced redundantly, and if applicable, the unselected state is announced instead. (#8554)

### CODE REVIEW

**Comment by michaelDCurran** [comment]
The only side affect to this is that the states are announced right at the very end. And this can be very annoying when having to work out if one of them is checked.
Perhaps we could consider having the first column exposed in the name as it currently is, but the rest of the columns exposed in the value?
Or, we could again consider moving states before name for all controls.  We used to have a config option for this, but I think its gone now.

**Comment by leonardder** [comment]
> > Perhaps we could consider having the first column exposed in the name as it currently is, but the rest of the columns exposed in the value?
> 
> In my opinion, this makes much sense. We could go for this as part of this pr?

Mmmm. The value is not spoken for checkable list items it seems. I can't find out why not, though.

**Comment by leonardder** [comment]
The value for checkboxes is suppressed, as ROLE_CHECKBOX is in controlTypes.silentValuesForRoles. Even when I remove CHECKBOX from there, the order of speech is "name check box value not checked", which is certainly not the intention here.

**Comment by leonardder** [comment]
> Perhaps we could consider having the first column exposed in the name as it currently is, but the rest of the columns exposed in the value?

@michaeldcurran: What do you think about exposing the rest of the columns in the description? It will make the columns silent if one disables reporting of descriptions, but I guess that's an acceptable drawback.

**Comment by leonardder** [comment]
@michaelDCurran In https://github.com/nvaccess/nvda/pull/8858#issuecomment-463151569, I suggested having the first column in the name and the rest in the description. I'm not sure whether I still agree with this suggestion, though. We couldn't make sure that the first column is of more importance than the other columns. In some list view controls, the first column is either empty or an identifier.

**Comment by leonardder** [comment]
It is a bit unclear where this pr is heading to. Any suggestions to bring this forward @josephsl or @feerrenrut?

**Comment by lukaszgo1** [comment]
Would it be possible to special case  checkable lists to report role and the state first. This is not ideal, but we have done something similar for reporting selection i.e. selected is reported before selection when gaining focus, but after in all other cases

**Comment by leonardder** [comment]
> Would it be possible to special case checkable lists to report role and the state first.

It should be possible, yes. However, not with a whole bunch of refactoring. Currently it isn't quite trivial to swap properties speech.

**Comment by lukaszgo1** [comment]
@leonardder I've tested your code and it is awesome! In addition to the fixes listed in the PR description this also causes proper position info to be reported for these controls, and makes reporting of their full  content working regardless of the reporting of description being enabled or not. If the only downside to this is the fact that states are reported at the end I personally would consider it to be a non-issue - the same happens for regular checkboxes and while having it configurable would be nice it should not block this work IMO.

**Comment by feerrenrut** [comment]
@leonardder Can you update the description please? It currently says:
> are presented differently from regular list items.

Can you explain how, with examples? This makes it so much quicker to understand the intent of a PR.

**Comment by leonardder** [comment]
@feerrenrut done. Let me know if you need additional details.

**Comment by Adriani90** [comment]
@leonardder could you please add some lines about table navigation command working also in list views? This would also close issue #3193. Thanks.

**Review by michaelDCurran — APPROVED** [review]

**Comment by michaelDCurran** [comment]
I have decided that the disadvantage of the states now being announced later is not a large enough problem to refuse the other benefits of this pr. The order and way we handle states in general does need to be rethought, but I'm happy to merge this pr as is.

**Comment by CyrilleB79** [comment]
That's a good point to have this PR merged to allow table navigation in this type of list. Also this fixes the issue in the file list of Tortoise SVN commit window where hidden column content were read.

However, I think that the "checked" / "unchecked" information should be available earlier; the user should not be forced to wait until NVDA has read the whole line to have this information.
In the "Disk clean-up" window, this is not so much a problem since there are only 2 columns and the second column contains information that is read quickly.
Regarding add-on updater's list, the user has to wait a bit more (3 columns).
And regarding Tortoise the file list in Tortoise SVN commit window, it is still worse (4 columns).

In practice, in tortoise SVN, I will need to press 2 times the space bar to uncheck/check the current item; it is faster than waiting for NVDA to read the whole line.

@michaelDCurran do you agree that these points still need to be discussed, even if we do not reverse this PR. May I open a new issue for this?

Here are also my thoughts regarding the discussion in this PR:

@leonardder wrote:
> @michaelDCurran In [#8858 (comment)](https://github.com/nvaccess/nvda/pull/8858#issuecomment-463151569), I suggested having the first column in the name and the rest in the description. I'm not sure whether I still agree with this suggestion, though. We couldn't make sure that the first column is of more importance than the other columns. In some list view controls, the first column is either empty or an identifier.

It seems that IAccessible uses the first column as object's name and the remaining columns as object's description. This let me think that the first column has a specific role.
At least in the 3 examples I have provided ("Disc clean-up" window, add-on updater and Tortoise SVN commit window) the most important information actually resides in the first column.
@leonardder could you provide some other example where this would not be the case and where the most important information is in another column?

@lukaszgo1 wrote:
> If the only downside to this is the fact that states are reported at the end I personally would consider it to be a non-issue - the same happens for regular checkboxes and while having it configurable would be nice it should not block this work IMO.

I partially disagree here since a checkable list item contains generally more information than a single checkbox especially when there are more columns.

**Pull request merged**
