### PR TITLE
Pull out wx to top level import, improve typing for core

### PR DESCRIPTION
**Pull request by seanbudd**
### Link to issue number:

Follow up of #13699 

### Summary of the issue:

NVDA core is dependent on wx in many implicit cases.

### Description of how this pull request fixes the issue:

Make the wx dependency explicit.
Add additional linting and typing for work done in #13699.

Future work is needed to make core no longer dependent on wx.

### Testing strategy:

Test starting NVDA with a built launcher and running from source

### Change log entries:
No user facing changes

### Code Review Checklist:

- [x] Pull Request description:
  - description is up to date
  - change log entries
- [x] Testing:
  - Unit tests
  - System (end to end) tests
  - Manual testing
- [x] API is compatible with existing add-ons.
- [x] Documentation:
  - User Documentation
  - Developer / Technical Documentation
  - Context sensitive help for GUI changes
- [x] UX of all users considered:
  - Speech 
  - Braille
  - Low Vision
  - Different web browsers
  - Localization in other languages / culture than English

### CODE REVIEW

**Comment by Brian1Gaff** [comment]
What about the times when it thinks there is no audio interface, and 
although it does not actually crash, it has set the program to no sound even 
though the sound gets initialised later during boot up.
 I think this occurs when some kind of windows update occurs very fast 
during the boot up or perhaps due to a slow hard drive.
 Brian

***@***.***
Sent via blueyonder.
Please address personal E-mail to:-
***@***.***, putting 'Brian Gaff'
in the display name field.
Newsgroup monitored: alt.comp.blind-users
----- Original Message ----- 
From: "Sean Budd" ***@***.***>
To: "nvaccess/nvda" ***@***.***>
Cc: "Subscribed" ***@***.***>
Sent: Tuesday, May 17, 2022 1:14 AM
Subject: [nvaccess/nvda] Prevent callLater when NVDA not initialized (PR 
#13701)

**Comment by lukaszgo1** [comment]
How you've determined that not importing `wx`lazily  is safe?

**Comment by seanbudd** [comment]
> How you've determined that not importing `wx`lazily  is safe?

I've run the launcher and run from source. I'd be incredibly surprised if it wasn't safe. Our main reason for lazy imports is circular dependencies. This is an external dependency, and as such shouldn't execute code that depends on NVDA when being imported.

**Comment by seanbudd** [comment]
Another reason for deferred imports is one dependency may need another dependency initialized first. `wx` doesn't rely on any NVDA modules to be initialized first.

**Comment by feerrenrut** [comment]
Another thing to consider here, where some other module needs to import core before wx is imported. A reason for this may be the time it takes to import wx.

**Comment by seanbudd** [comment]
running from source, with the following code at the start of core.py

```py
"""NVDA core"""
import time
s = time.time()
import wx
print(time.time()-s)
```

0.037993431091308594

**Comment by seanbudd** [comment]
This is a slight increase to the sum of the other imports: 0.00799

**Comment by leonardder** [comment]
Will it also be considered to improve the code style of core, i.e. by taking the class definitions of App, CorePump and MessageWindow out of the main function?

**Comment by seanbudd** [comment]
> Another thing to consider here, where some other module needs to import core before wx is imported. A reason for this may be the time it takes to import wx.

I believe imports are cached, and wx must be imported in `core.main`, before NVDA starts.

For add-ons, this is already imported in the namespace: https://www.nvaccess.org/files/nvda/documentation/developerGuide.html#toc47

**Comment by michaelDCurran** [comment]
Way back in NVDA's infancy, we did deliberately import wx after 
initializing speech, so that on slow machines or when running off a USB 
key, we could speak a message first, as loading wx would add up to 10 
seconds of time back then.

But I really don't think this is relevant anymore, and no doubt we 
already broke this rule a long time back.

**Comment by XLTechie** [comment]
> For add-ons, this is already imported in the namespace: https://www.nvaccess.org/files/nvda/documentation/developerGuide.html#toc47

For the console, you mean, not for add-ons.

**Comment by seanbudd** [comment]
Another approach can be started to add typing to core, without moving the `wx` import.

**Pull request closed without merging**
