### PR TITLE
Remove old winTerminalUIA module attribute

### PR DESCRIPTION
**Pull request by codeofdusk**
### Link to issue number:
Fix-up of #14047.

### Summary of the issue:
Code to support a previously used `WinTerminalUIA` class name was added during a deprecation period, now over a year. See the deprecation note in 2023.1 developer changes.

### Description of how this pull request fixes the issue:
Remove the attribute. This code is unlikely to be used by add-ons.

### Testing strategy:
Verified functionality of terminal support.

### Known issues with pull request:
None known

### Change log entry:
In PR

### Code Review Checklist:

- [x] Documentation:
  - Change log entry
  - User Documentation
  - Developer / Technical Documentation
  - Context sensitive help for GUI changes
- [x] Testing:
  - Unit tests
  - System (end to end) tests
  - Manual testing
- [x] UX of all users considered:
  - Speech 
  - Braille
  - Low Vision
  - Different web browsers
  - Localization in other languages / culture than English
- [ ] API is compatible with existing add-ons.
- [x] Security precautions taken.

## Summary by CodeRabbit

- **Refactor**
  - Removed backward compatibility logic related to `WinTerminalUIA` deprecation.

### CODE REVIEW

**Comment by seanbudd** [comment]
This API breaking change will need a change log entry in the 2025.1 changes

**Review by seanbudd — APPROVED** [review]

**Comment by seanbudd** [comment]
Can you fix merge any conflicts and add an API removal notice to the changes for developers for 2025.1?

**Comment by SaschaCowley** [comment]
@codeofdusk per https://github.com/nvaccess/nvda/pull/16820#issuecomment-2311467950, can you please add an API removal notice to the "Changes for developers" section of the changelog for 2025.1?

**Review by SaschaCowley — APPROVED** [review]
Thanks, @codeofdusk

**Pull request merged**
