### PR TITLE
Fix backspace issue with QLineEdit + Password echo mode with Qt 5.9

### PR DESCRIPTION
**Pull request by masakotoda**
### Link to issue number:
NA

### Summary of the issue:
The issue is specific to the applications built with Qt 5.9. The password field doesn't accept backspace key.

### Description of how this pull request fixes the issue:
In Qt application, by setting echoMode Password to QLineEdit, we can have a password edit box.
When the user hits backspace key, NVDA reaches here:
https://github.com/nvaccess/nvda/blob/release-2019.3/source/NVDAObjects/IAccessible/__init__.py#L261
And it hits this Qt code:
https://github.com/qt/qtbase/blob/5.9/src/widgets/accessible/simplewidgets.cpp#L848-L849
So, ```start``` and ```end``` are -1 and ```text``` is None.
That raises an error here:
https://github.com/nvaccess/nvda/blob/release-2019.3/source/NVDAObjects/IAccessible/__init__.py#L264

### Testing performed:
1. Create a Qt widget base application with Qt 5.9.
2. Place a QLineEdit and set echoMode Password.
3. Build application and enter characters in the password edit box.
4. Press backspace key.

Without the fix, nothing gets deleted.
With the fix, the characters get deleted normally.

### Change log entry:

Section: New features, Changes, Bug fixes

### CODE REVIEW

**Comment by josephsl** [comment]
Hi, thanks for this pull request. Unfortunately, we won’t be able to review this without test cases and how you tested this PR. Also, please try using NVDA 2020.1 and 2020.2 beta, as things might have changed. Thanks.

**Comment by masakotoda** [comment]
I checked the master, and it still has the issue. I'll add test cases.

**Comment by josephsl** [comment]
Hi, one more thing to test: is this specific to QT 5.9 applications? What about apps built with later QT releases such as 5.11? Thanks.

**Comment by masakotoda** [comment]
Qt 5.10+ doesn't seem to have this issue. With Qt 5.10, NVDA doesn't hit https://github.com/nvaccess/nvda/blob/release-2019.3/source/NVDAObjects/IAccessible/__init__.py#L261 for some reason.

**Comment by josephsl** [comment]
Hi, in this case, I think a better solution is talking to app vendors about updating to newer QT releases rather than letting NVDA take care of this unless we hear from an app developer that they are not going to upgrade the GUI toolkit. Thanks.

**Comment by masakotoda** [comment]
Regardless, not checking None in isHighSurrogate/isLowSurrogate function is not good. I'd like you to fix it anyway.

**Comment by josephsl** [comment]
Hi, I think that’s a different issue to this PR if it turns out if that is what’s really going on. My request still stands: please ask the app vendor about GUI toolkit updates, and if they can’t do it for a legitimate reason (or two), we might consider this PR. Thanks.

**Comment by josephsl** [comment]
Hi,

By the way, tests via AppVeyor didn't work.

Thanks.

**Comment by leonardder** [comment]
> 
> Hi, in this case, I think a better solution is talking to app vendors about updating to newer QT releases rather than letting NVDA take care of this unless we hear from an app developer that they are not going to upgrade the GUI toolkit. Thanks.

I disagree here. Please keep in mind that QT 5.9 is the last long term support release of QT that uses IAccessible instead of UIA for accessibility. I know for one thing that the guys at Musescore  for example, aren't ready to update to newer builds of Qt because of breaking changes they haven't been able to address in a stable release.

**Review by LeonarddeR — CHANGES_REQUESTED** [review]
Thanks for your attempt to fix this.

1. I really prefer a fix *not* to go into textUtils. These textUtils functions are really expected to work with characters. Rather, I'd like the `if textUtils.isHighSurrogate(text) or textUtils.isLowSurrogate(text)` statement not to be called at all.
2. I think there are several ways to do this:

	* Expand the mentioned statement like: `if text and (textUtils.isHighSurrogate(text) or textUtils.isLowSurrogate(text))`. This ensures that this never gets called when text is None.
	* Negative offsets aren't expected here. If either start or end are -1, we'd somehow want to revert to the super implementation or raise a LookupError. I'm pretty sure that LookupErrors are caught properly.

For now, I think the first solution is the easiest and least risky one.

**Comment by masakotoda** [comment]
Thanks @leonardder for the suggestion. I will change my fix and push shortly.

**Review by LeonarddeR — APPROVED** [review]
This returns (-1, -1) now. I think that's ok. The behavior of what should be returned from getCharacterOffsets is undefined anyway.

**Review by michaelDCurran — APPROVED** [review]

**Pull request merged**
