### PR TITLE
Add support for IA2_ROLE_LANDMARK

### LINKED ISSUE #10101: Support the IA2_ROLE_LANDMARK
### Steps to reproduce:

1. In Firefox, open this: `data:text/html,<header>I am a banner</header><section><header>I am not a banner</header></section>`
2. Examine the hierarchy for the "I am a banner" text.

### Actual behavior:

For the parent, which corresponds to the header element that is a direct descendant of the document and therefore treated as a landmark, the role is spoken as "unknown". The developer info (NVDA+F1) is:

Developer info for navigator object:
name: None
role: ROLE_UNKNOWN
states: 
isFocusable: False
hasFocus: False
Python object: <NVDAObjects.IAccessible.mozilla.Mozilla object at 0x056244F0>
Python class mro: (<class 'NVDAObjects.IAccessible.mozilla.Mozilla'>, <class 'NVDAObjects.IAccessible.ia2Web.Ia2Web'>, <class 'NVDAObjects.IAccessible.IAccessible'>, <class 'NVDAObjects.window.Window'>, <class 'NVDAObjects.NVDAObject'>, <class 'documentBase.TextContainerObject'>, <class 'baseObject.ScriptableObject'>, <class 'baseObject.AutoPropertyObject'>, <type 'object'>)
description: u''
location: RectLTWH(left=20, top=205, width=3800, height=47)
value: None
appModule: <'firefox' (appName u'firefox', process ID 15784) at address 4e9be50>
appModule.productName: u'Firefox Nightly'
appModule.productVersion: u'70.0a1'
TextInfo: <class 'NVDAObjects.IAccessible.IA2TextTextInfo'>
windowHandle: 590956L
windowClassName: u'MozillaWindowClass'
windowControlID: 0
windowStyle: 399441920
extendedWindowStyle: 256
windowThreadID: 1460
windowText: u'Firefox Nightly'
displayText: u''
IAccessibleObject: <POINTER(IAccessible2) ptr=0xa0120a4 at e72be40>
IAccessibleChildID: 0
IAccessible event parameters: windowHandle=590956L, objectID=-4, childID=-67110976
IAccessible accName: None
IAccessible accRole: u'header'
IAccessible accState:  (0)
IAccessible accDescription: u''
IAccessible accValue: None
IAccessible2 windowHandle: 590956
IAccessible2 uniqueID: -67110976
IAccessible2 role: IA2_ROLE_LANDMARK
IAccessible2 states: IA2_STATE_SELECTABLE_TEXT, IA2_STATE_OPAQUE (5120)
IAccessible2 attributes: u'margin-left:0px;text-align:start;text-indent:0px;margin-right:0px;tag:header;margin-top:0px;margin-bottom:0px;xml-roles:banner;display:block;formatting:block;'

### Expected behavior:

NVDA should not treat IA2_ROLE_LANDMARK as an unknown role, but read it as "landmark" or something sensibly similar.

#### NVDA installed/portable/running from source:

Installed.

#### NVDA version:

All versions, including 2019.3alphas.

#### Windows version:

All Windows 10 versions.

#### Name and version of other software in use when reproducing the issue:

Firefox current release, beta, or nightly. IA2_ROLE_LANDMARK has been exposed since Firefox 65, see [Bug 614572](https://bugzilla.mozilla.org/show_bug.cgi?id=614572).

#### Other information about your system:

Also happens in Chrome, which also exposes this role.

#### Does the issue still occur after restarting your PC?

Yes.

#### Have you tried any other versions of NVDA? If so, please report their behaviors.

Several, all yield the same result.

### PR DESCRIPTION
**Pull request by LeonarddeR**
### Link to issue number:
Fixes #10101

### Summary of the issue:
IA2 version 3 introduced IA2_ROLE_LANDMARK which is set on landmarks in recent Firefox and Chrome versions. This role was not supported.

### Description of how this pull request fixes the issue:
1. Add a new role: controlTypes.ROLE_LANDMARK and map this appropriately
2. When speaking a landmark object in focus mode, also speak the landmark itself, e.g. `banner landmark`. This works in Internet Explorer, Firefox, Chrome, Edge legacy and Edge beta. This is accomplished by using the roleText attribute on objects.
3. IA2 virtual buffrs now also use the landmark role for landmark quick navigation.

### Testing performed:
Tested the following snippet:
```
data:text/html,<header><button>I am a banner with a button in it</button></header>
```

When moving with tab to the button, ensure that `banner landmark` is spoken before the button name. Also make sure that the landmark is silenced when reporting of landmarks is off.

### Known issues with pull request:
1. Strange enough, the landmark isn't spoken when navigating by landmark itself.
2. In internet explorer, HTML node name to aria landmark roles mapping still doesn't work.

### Change log entry:
* New features
    + In Internet Explorer, Microsoft Edge and recent versions of Firefox and Chrome, landmarks are now reported in focus mode. (#10101)

### CODE REVIEW

**Comment by MarcoZehe** [comment]
> @MarcoZehe: Do you know in what exact Chrome version this support was introduced?

Unfortunately, no, I just found out through testing that the current version of Chrome does.

**Comment by leonardder** [comment]
@feerrenrut The remaining lint error is about using IA2_ROLE_LANDMARK which is imported using `from from comInterfaces.IAccessible2Lib import *`. The IAccessibleHandler relies on this method of importing, if we don't, things get really painful.
I think we should either ignore these errors for now or come up with a documented alternative to ensure consistency across the code base.

**Comment by michaelDCurran** [comment]
My first thought would be that we should move towards importing it as 
```
import comInterfaces.Ia2Lib as ia2
```
Then doing things like ia2.IA2_ROLE_LANDMARK

**Comment by leonardder** [comment]
I like that. Probably will go for IA2 (upper case) for consistency reasons.

**Review by michaelDCurran — COMMENTED** [review]
Are the types of landmarks presented in braille?
I wonder if it might be less complicated to just expose the landmark type via roleText (which is already supported in both speech and braille). E.g.  the roleText for a landmark of type "main" could be "main landmark". This would remove the need for the specific code for landmarks in speakObjectProperties etc.

**Comment by leonardder** [comment]
I like the idea of using roleText!

**Comment by leonardder** [comment]
Ugh, problem with using roleText is actually that we couldn't use landmark abbreviations in braille.

**Comment by michaelDCurran** [comment]
Take a look at the nvaccess/ariaRoleDescriptionBraille branch. That implements roleTextBraille on NVDAObjects and handles it in braille.py. We won't want to take all of that code yet as aria-roleDescription-braille is not at all in the aria standard yet, but it was prototyped by Sina, Reef and myself last year at a math workshop. But you can certainly take the code in ```NVDAObjects/__init__.py``` and ```source/braille.py```

**Comment by leonardder** [comment]
@michaelDCurran I finished the implementation based on roleText. Everything uses roleText for landmarks now, i.e. the special code for landmarks has been removed from browseMOde and control field speech now uses roleText if there is a landmark in the field.

Please note that the first known issue isn't caused by this pr.

Code snippet: `<div role="search" aria-label="This is a search landmark">test</div>`

Control field for the landmark: `FieldCommand controlStart with {'runtimeID': (42, 329956, 4, 10), '_startOfNode': False, '_endOfNode': False, 'role': 86, 'states': set(), 'nameIsContent': False, 'name': 'This is a search landmark', 'description': '', 'level': None, 'embedded': False, 'isBlock': True, 'roleText': 'search landmark', 'landmark': 'search', 'current': None}`

Note the _startOfNode value, which is False and really should be True here, as I were positioned at the start of the landmark. We only add the name if _startOfNode is True. This code is there for historical reasons, but I can probably remove it because the contro field presentation category now takes landmarks into account.

**Comment by leonardder** [comment]
@michaelDCurran I finished the implementation based on roleText. Everything uses roleText for landmarks now, i.e. the special code for landmarks has been removed from browseMode and control field speech now uses roleText if there is a landmark in the field.

Please note that the first known issue isn't caused by this pr.

**Comment by michaelDCurran** [comment]
@leonardder  just a reminder there are failing flake8 checks on this pr.

**Comment by leonardder** [comment]
@michaelDCurran Sorry, should have been fixed now.

**Review by michaelDCurran — CHANGES_REQUESTED** [review]
There is a possibility that a landmark will be ignored if the landmark is not the first role in the ARIA roles. E.g. role="list navigation". 
For instance, when fetching xml-roles, after splitting, you should take the first role that also appears in aria.landmarkRoles, rather than just the first thing in the list.
In other words, the check for aria.landmarkRoles should be done in each implementation of the landmark property, rather than in the base roleText property, as this is too late.

**Comment by leonardder** [comment]
Thanks for pointing this out. I actually wasn't aware that you are 
officially allowed to have multiple roles on a HTML node.

**Comment by leonardder** [comment]
@michaelDCurran how do you actually expect `role="list navigation"` to be reported by NVDA?

In the current implementation, landmarks are treated separately from role, so this case will be reported as `navigation landmark list`. However, in the new implementation, it is either navigation landmark or list. Current code even reports `navigation landmark with 1 item` because the underlying role is LIST, but roletext is overriden because it's a landmark, which is of course a bit problematic

**Comment by michaelDCurran** [comment]
Hmm that is a tricky one.


I seem to think landmark should override role, but I can't really back 
up why I think that.

**Comment by leonardder** [comment]
In firefox with IA2ROLE_LANDMARK support:

* `<div role="list navigation">` is a list
* `<div role="navigation list">` is a landmark

May be @MarcoZehe and @jcsteh would like to share their ideas?

**Comment by MarcoZehe** [comment]
Perhaps [this section](https://www.youtube.com/watch?v=DhSpU_IJuR0&list=PLn7dsvRdQEfFd5n_h8gltIoTfzUE_zywu) of the WAI-ARIA 1.1 spec or the listed Core-AM 1.1 section 5.4.1 help clarify: The list of tokens acts as a fallback mechanism, so if a user agent doesn't know the first role, it falls back to the second, etc. Since list is known, the landmark role, whichever that may be, will never be evaluated, and List wins. The first non-abstract role is what gets exposed. So if you have "list banner", "banner" would be considered a fall-back and would not get exposed since "list" is already there. Except for through the attribute XML-Roles, since that always gets the full token list.

**Review by michaelDCurran — APPROVED** [review]

**Comment by leonardder** [comment]
Ugh, turns out that I entirely forgot about the braille implementation for this. I will file a fixup pr later this week. cc @bramd

**Pull request merged**
