### PR TITLE
Change the PlaySound routine in the launcher to prevent warnings on systems without a sound card

### PR DESCRIPTION
**Pull request by LeonarddeR**
This was initially reported as part of #6289.
In the current pr, I changed the PlaySound routine according to [this](http://nsis.sourceforge.net/mediawiki/index.php?title=WinAPI:winmm:PlaySound&oldid=13110) NSIS example. It uses windows standard [PlaySound function](https://msdn.microsoft.com/en-us/library/ms712879.aspx), which is a nicer approach anyway. I tested with with a soundless vm, and all works fine.

CC @WJdZ

### CODE REVIEW

**Review by jcsteh — CHANGES_REQUESTED** [review]
This makes sense. This should also at least partly address #5419.

I assume you got this code from http://nsis.sourceforge.net/WinAPI:winmm:PlaySound? If so, this should be referenced in a comment. The thing that confused me was the IntOp call being given "SND_ASYNC" as its first parameter. The [documentation for IntOp](http://nsis.sourceforge.net/Reference/IntOp) doesn't say anything about this. If you got the code from the above link, that's fine; just reference it and we can assume it works (or at least know who to blame if it doesn't :) ).

**Comment by leonardder** [comment]
Not sure why IntOB is used there either. However, they probably added it 
to the example for a reason, and it seems it works correctly on several 
systems. Lets see whether this survives a stress test in the next branch 
for a while.

Sent on behalf of @BabbageCom

**Comment by jcsteh** [comment]
I suspect it's just a cute way of defining a constant. Maybe the string
value gets treated as 0, so the logical or picks up the 1. Or something?
Anyway, whatever; NSIS is weird. Long as it works in the wild and you've
included the reference now, we can move on.

**Comment by leonardder** [comment]
I actually had forgotten that I had to apply the requested changes. There we go.

**Review by jcsteh — APPROVED** [review]

**Pull request merged**
