### PR TITLE
Add-Ons Manager: Change default Button to "No" for Delete Add-On Confirmation Dialog (#10015)

### LINKED ISSUE #10015: Add-Ons Manager: Change default Button to "No" for Delete Add-On Confirmation Dialog
When choosing to remove an add-on via the Add-Ons Manager, a warning is displayed; however, the "Yes" button is set as the default. To prevent accidental deletion of add-ons, would it be possible to change the default button that receives focus to "No"? This way, users will need to explicitly move focus to the "Yes" button; implementing this will decrease the likelyhood that add-ons are accidentally deleted.

### PR DESCRIPTION
**Pull request by JulienCochuyt**
### Link to issue number:

Fixes #10015

### Summary of the issue:

When choosing to remove an add-on via the Add-Ons Manager, a warning is displayed; however, the "Yes" button is set as the default.
@elliott94 requested the default be changed to "No" instead in https://github.com/nvaccess/nvda/issues/10015#issue-475834944
@DrSooom suggested the escape key be used to cancel as well in https://github.com/nvaccess/nvda/issues/10015#issuecomment-517421049

### Description of how this pull request fixes the issue:

Set the "No" button as the default.
Add a "Cancel" button as well so it is automatically mapped to the escape key.
Alternatively, this yes/no turned into a yes/no/cancel could have been replaced by a ok/cancel, but this would require a rewording of the confirmation message and thus translation effort.

### Testing performed:

Removed an add-on.
Denied removal of an add-on.

### Change log entry:

Section: Changes

In the Add-ons manager, when prompted to confirm removal of an add-on, "No" is now the default.

### CODE REVIEW

**Comment by feerrenrut** [comment]
I don't really like the idea of having three buttons. There are really only two outcomes: proceed, do not proceed. I think this message should be re worded anyway, something like:
"Remove the selected add-on from NVDA?" Then use OK | CANCEL.

**Comment by XLTechie** [comment]
Instead of yes/no/cancel, why not just do Remove and Cancel, with 
Cancel as the default?

**Comment by DrSooom** [comment]
I agree with @feerrenrut – Yes/No/Cancel is one button to much. I suggest the following:
+ [Text] Do you really want to remove this add-on?
WARNING: After restarting NVDA, this step cannot be reversed!
+ [Buttons] "Yes, remove this add-on" and "Cancel" (has focus, allocated to the ESC key)

See also: Issue #10016

Question: What shall we do if such a removed add-on in the userConfig folder is still available in the systemConfig? Removing both at the same time would require admin privileges. Therefore I wouldn't prefer this.

**Review by josephsl — COMMENTED** [review]
Hi,

In addition to changing the user interface, I think what can improve things a bit is mentioning the name of the add-on, similar to what is done when installing it. For example, something to the effect of:

Are you sure you wish to remove Screen Curtain add-on? This cannot be undone.

Notice that the wording is very similar to the prompt in Configuration Profiles/Delete dialog (editing the prompt in configuration profiles is a different story). Also, you may wish to take a look at seeing if the user guide section on add-ons need tweaking if the user interface changes.

Thanks.

**Comment by JulienCochuyt** [comment]
@feerrenrut:
> I don't really like the idea of having three buttons [...] this message should be re worded anyway

My first aim was to limit translation impact, but I agree OK/Cancel fits better here.

@XLTechie:
> Instead of yes/no/cancel, why not just do Remove and Cancel, with
Cancel as the default?

This sadly does not fit the standard Windows / WX message boxes.
You can have either Yes / No with an optional Candel or OK with an optional Cancel.
In any case, Cancel is the only answer one can map to the escape key, No cannot.

@josephl:
> Are you sure you wish to remove Screen Curtain add-on? This cannot be undone.

This would further reduce ambiguity and enhance user confidence.
I'll have a look at the user guide as well.

**Comment by feerrenrut** [comment]
> You can have either Yes / No with an optional Cancel or OK with an optional Cancel.

For what it's worth [`MessageBox` is a helper function](https://wxpython.org/Phoenix/docs/html/wx.functions.html?highlight=messagebox#wx.MessageBox) that wraps the [`MessageDialog` class](https://wxpython.org/Phoenix/docs/html/wx.MessageDialog.html). If you use the class directly you can change the labels for the buttons with `SetOKLabel` etc.

**Comment by JulienCochuyt** [comment]
Further testing of the OK/Cancel with Cancel as default felt pretty awkward.
We are so used of validating OK/Cancel with the enter or space keys and this Cancel as default forbids it, forcing to tab.
My proposal is then to stick with Yes/No and simply have No as default, as originally requested in #10015.
Nevertheless, the confirmation prompt now mentions the name of the add-on as suggested in https://github.com/nvaccess/nvda/pull/10087#pullrequestreview-274671006

**Comment by leonardder** [comment]
Why do we actually want no as the default button? If a user tries to remove an add-on, in most cases he is expected to choose yes. If I press shift+delete in Windows Explorer, Yes is also chosen as the default button when removing a file/folder.

**Comment by XLTechie** [comment]
Personally, I don't like having no as the default. However I know it was 
requested by a few people. I think the idea was that you might press enter too 
many times, and accidentally answer yes without knowing there was even a prompt?

Since add-ons are pretty easy to get back, I don't really get it.

-- 
Luke
Moderator: NVDA Help mailing list (NVDAHelp+subscribe@groups.io)
Author: Debug Helper NVDA add-on (https://github.com/XLTechie/debugHelper)

**Comment by JulienCochuyt** [comment]
> Why do we actually want no as the default button?

I must confess I also am not that much convinced, but feel like it does not arm either.
Main motivation here was to satisfy a request from a prolific reporter while we probably won't invest much time on somewhat related issues like #10025.

Please note the addition of the add-on name in the confirmation message, also included in this PR as suggested by @josephsl, does indeed improve user experience IMHO.

**Comment by elliott94** [comment]
@leonardder - For the average or less-experienced Windows user, in my opinion they'd more likely use the delete key by itself - in which case, if they accidentally delete a file/folder they have the option in most cases of recovering from the Recycle Bin. However, it's not currently possible to recover a deleted add-on so making No the default choice at least makes it less likely that an add-on will accidentally be deleted.

**Comment by JulienCochuyt** [comment]
Damn, caught again by my own fix on `checkPot`...

**Review by feerrenrut — APPROVED** [review]
Thanks @JulienCochuyt

**Pull request merged**
