### PR TITLE
Windows 11: suppress UIA focus event on InputSite pane window when switching tasks

### LINKED ISSUE #12648: Windows 11: a "pane" window gets focus when switching to certain apps, including Command Prompt
Hi,

Related: #12585 

The following was reported on Twitter, and a discussion about this took place between I, @CToth, and several users.

### Steps to reproduce:
With Windows 11 preview installed:

1. Open several apps.
2. Run Command Prompt, Windows Terminal, or other application, preferably running Windows Subsystem for Linux (WSL) 2 shell active.
3. Switch to a different app.
4. Switch to Command Prompt.

### Actual behavior:
Focus lands on "pane" window.

### Expected behavior:
Focus lands on Command Prompt.

#### NVDA installed/portable/running from source:
Installed

#### NVDA version:
2021.1, alpha-23336,9409b9dd

#### Windows version:
Windows 11 preview (build 22000.65)

#### Name and version of other software in use when reproducing the issue:
Command Prompt, Windows Terminal 1.9

#### Other information about your system:
A virtual machine running Insider Preview builds

#### Does the issue still occur after restarting your computer?
Yes

#### Have you tried any other versions of NVDA? If so, please report their behaviors.
Older versions such as 2020.4 behave the same.

#### If add-ons are disabled, is your problem still occurring?
Yes

#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
Not applicable

### Additional context:
Currently a fix was deployed through Windows App Essentials, and @CToth points out that it should be part of NVDA to begin with as this is a basic user experience issue.

#### Developer info for the pane object:
name: ''
role: ROLE_PANE
roleText: None
states: STATE_FOCUSED
isFocusable: False
hasFocus: True
Python object: <NVDAObjects.UIA.UIA object at 0x06EEB5B0>
Python class mro: (<class 'NVDAObjects.UIA.UIA'>, <class 'NVDAObjects.window.Window'>, <class 'NVDAObjects.NVDAObject'>, <class 'documentBase.TextContainerObject'>, <class 'baseObject.ScriptableObject'>, <class 'baseObject.AutoPropertyObject'>, <class 'garbageHandler.TrackedObject'>, <class 'object'>)
description: ''
location: RectLTWH(left=0, top=0, width=1600, height=1152)
value: None
appModule: <'explorer' (appName 'explorer', process ID 5928) at address 6d0e890>
appModule.productName: 'Microsoft® Windows® Operating System'
appModule.productVersion: '10.0.22000.51'
TextInfo: <class 'NVDAObjects.NVDAObjectTextInfo'>
windowHandle: 853144
windowClassName: 'Windows.UI.Input.InputSite.WindowClass'
windowControlID: 0
windowStyle: 1342177280
extendedWindowStyle: 0
windowThreadID: 6424
windowText: ''
displayText: ''
UIAElement: <POINTER(IUIAutomationElement) ptr=0x397a728 at 701c120>
UIA automationID: 
UIA frameworkID: XAML
UIA runtimeID: (42, 853144)
UIA providerDescription: [pid:4556,providerId:0xD0498 Main:Nested [pid:5928,providerId:0xD0498 Main(parent link):Unidentified Provider (unmanaged:Windows.UI.Xaml.dll)]; Hwnd(parent link):Microsoft: HWND Proxy (unmanaged:UIAutomationCore.dll)]
UIA className: Windows.UI.Input.InputSite.WindowClass
UIA patterns available: LegacyIAccessiblePattern

#### Proposed solution:
Let NvDA ignore UIA focus event for this window, which then allows NVDA to notice that Command Prompt was focused. The ideal solution should come from Microsoft, and since Windows 11 is in preview, things can change, making the PR a bit risky (we need to revert changes if Microsoft fixes this).

Thanks.

### PR DESCRIPTION
**Pull request by josephsl**
Hi,

Would it be possible to put this into 2021.3 unless it should be delayed to 2022.1?

### Link to issue number:
Closes #12648

### Summary of the issue:
When switching tasks in Windows 11, a "pane" window gets focused instead of the app being switched to in some cases.

### Description of how this pull request fixes the issue:
Treat InputSite window class window as a Windows 10 MultitaskingViewFrameWindow object which suppresses UIA focus event.

### Testing strategy:
Manual testing on Windows 11 (prerequisite: Windows App Essentials add-on must be disabled):

1. Without the patch applied, try switching between tasks.
2. With the patch applied, try switching between tasks.

Expected: NVDA will say "pane" in scenario 1, whereas NVDA will not say "pane" in scenario 2 when switching tasks.

### Known issues with pull request:
None yet

### Change log entries:
Bug fixes:

In Windows 11, NVDA will no longer announce "pane" when pressing Alt+Tab to switch between programs. (#12648)

### Code Review Checklist:

- [x] Pull Request description:
  - description is up to date
  -xchange log entries
- [x] Testing:
  - Unit tests
  - System (end to end) tests
  - Manual testing
- [x] API is compatible with existing add-ons.
- [x] Documentation:
  - User Documentation
  - Developer / Technical Documentation
  - Context sensitive help for GUI changes
- [x] UX of all users considered:
  - Speech 
  - Braille
  - Low Vision
  - Different web browsers
  - Localization in other languages / culture than English

### Additional context:
This problem was reported on Feedback Hub several months ago. This PR was originally part of Wnidows App Essentials add-on but was delayed to see if newer Windows 11 builds resolves it (not resolved so far).

Thanks.

### CODE REVIEW

**Comment by josephsl** [comment]
CC @codeofdusk

**Comment by lukaszgo1** [comment]
+1 for merging into 2021.3 if possible - this problem is quite annoyingh when using win 11.

**Review by seanbudd — APPROVED** [review]
Thanks @josephsl

**Comment by ivnc** [comment]
A Spanish-speaking user has contacted us, reporting that he hears the message "Task Switching" when switching between windows in Windows 11, although in most cases NVDA only speaks the initial "T". Log fragment follows ("Conmutación de tareas" is "Task Switching" in Spanish). According to his report, this is reproducible also with add-ons disabled. Could the PR be related to this?
NVDA 2021.3.3, Windows 11 21H2 (x64) build 22000.527, not reproducible in Windows 10 (by same user nor me).
IO - inputCore.InputManager.executeGesture (15:05:29.118) - winInputHook (10668):
Input: kb(laptop):alt+tab
IO - speech.speech.speak (15:05:29.181) - MainThread (5260):
Speaking ['Conmutación de tareas', CancellableSpeech (still valid)]
IO - speech.speech.speak (15:05:29.221) - MainThread (5260):
Speaking ['La Sala de Juegos [(xxx)]', 'fila 1', 'columna 1', '1 de 2', CancellableSpeech (still valid)]
DEBUGWARNING - IAccessibleHandler.internalWinEventHandler._shouldGetEvents (15:05:29.734) - MainThread (5260):
Foreground took too long to change. Foreground still 131982 (wxWindowNR). Should be 393430 (WorkerW)
IO - speech.speech.speak (15:05:29.781) - MainThread (5260):
Speaking ['La Sala de Juegos [(xxx)]', CancellableSpeech (still valid)]
IO - speech.speech.speak (15:05:29.813) - MainThread (5260):
Speaking ['Menú', 'lista', CancellableSpeech (still valid)]
IO - speech.speech.speak (15:05:29.817) - MainThread (5260):
Speaking ['Tirar 6 dados', CancellableSpeech (still valid)]
A Spanish-speaking user has contacted us, reporting that he hears the message "Task Switching" when switching between windows in Windows 11, although in most cases NVDA only speaks the initial "T". Log fragment follows ("Conmutación de tareas" is "Task Switching" in Spanish). According to his report, this is reproducible also with add-ons disabled. Could the PR be related to this?
NVDA 2021.3.3, Windows 11 21H2 (x64) build 22000.527, not reproducible in Windows 10 (by same user nor me).
IO - inputCore.InputManager.executeGesture (15:05:29.118) - winInputHook (10668):
Input: kb(laptop):alt+tab
IO - speech.speech.speak (15:05:29.181) - MainThread (5260):
Speaking ['Conmutación de tareas', CancellableSpeech (still valid)]
IO - speech.speech.speak (15:05:29.221) - MainThread (5260):
Speaking ['La Sala de Juegos [(xxx)]', 'fila 1', 'columna 1', '1 de 2', CancellableSpeech (still valid)]
DEBUGWARNING - IAccessibleHandler.internalWinEventHandler._shouldGetEvents (15:05:29.734) - MainThread (5260):
Foreground took too long to change. Foreground still 131982 (wxWindowNR). Should be 393430 (WorkerW)
IO - speech.speech.speak (15:05:29.781) - MainThread (5260):
Speaking ['La Sala de Juegos [(xxx)]', CancellableSpeech (still valid)]
IO - speech.speech.speak (15:05:29.813) - MainThread (5260):
Speaking ['Menú', 'lista', CancellableSpeech (still valid)]
IO - speech.speech.speak (15:05:29.817) - MainThread (5260):
Speaking ['Tirar 6 dados', CancellableSpeech (still valid)]

**Comment by josephsl** [comment]
Hi, highly unlikely. I also know that it sometimes happens with Narrator as well. Thanks.

**Pull request merged**
