### PR TITLE
Skype for Business: Remove excessive error logging.

### PR DESCRIPTION
**Pull request by CyrilleB79**
### Link to issue number:
None.
Fix-up of #9295 .

### Summary of the issue:
Some excessive errors were logged in the log while using Skype for Business.
In #9295, an error is logged when the new chat message does not follow the person+content+timestamp message.
The majority of message have such pattern but some information message don't, e.g.:
* message indicating the start or end of a call
* first message of the chat containing a warning about privacy

Excessive error logging is misleading when making NVDA or add-on tests.

### Description of how this pull request fixes the issue:
`log.error` replaced by `log.debug` since this codepath is expected.
The log is still kept in case an unknown message pattern is found in another version of Skype or with another usage.

### Testing strategy:

Manual testing with the appModule in the scratchpad.

### Known issues with pull request:
None
### Change log entries:
Not needed for such a minor fix.

### Code Review Checklist:

- [x] Pull Request description:
  - description is up to date
  - change log entries
- [x] Testing:
  - Unit tests
  - System (end to end) tests
  - Manual testing
- [x] API is compatible with existing add-ons.
- [x] Documentation:
  - User Documentation
  - Developer / Technical Documentation
  - Context sensitive help for GUI changes
- [x] UX of all users considered:
  - Speech 
  - Braille
  - Low Vision
  - Different web browsers
  - Localization in other languages / culture than English

### CODE REVIEW

**Comment by seanbudd** [comment]
>* message indicating the start or end of a call
>* first message of the chat containing a warning about privacy

Is there a way we can determine these cases and handle them separately?

**Comment by CyrilleB79** [comment]
> > * message indicating the start or end of a call
> > * first message of the chat containing a warning about privacy
> 
> Is there a way we can determine these cases and handle them separately?

I did not find any difference. I will make some further tests in the next days.

Note: during the tests, I have found another situation where the pattern does not match. It is when you send a message to a person which is away (and will not receive the message).
Thus, I convert this PR to draft until this issue is fixed. I plan to fix it changing the pattern regexp appropriately.

**Comment by seanbudd** [comment]
@CyrilleB79 should this or something simpler be merged as-is in the mean time?

**Comment by CyrilleB79** [comment]
Sorry for late response.
I have to make some further tests. I will try to do it in the next days.

**Review by seanbudd — APPROVED** [review]

**Pull request merged**
