### PR TITLE
Native driver for Hims displays

### LINKED ISSUE #3157: Braillesense u2: a lot of shortcuts don't work
**Reported by PZajda on 2013-04-16 10:05**
Braille input work, but I have all these shortcut keys, and none of them work for me.

Example, F2, F3 et F4 (those around the space bar called Advance 2, Advance 3 and Advance 4). 
Advance 2 should emulate Alt, Advance  3 Tab and Advance  4 Escape.

Combinated shortcuts don't work too:
- Space + Advance 3
- Space+dot1+dot8
- Space+Dot1+Dot4+Dot8
- Space+Dot1+Dot2+Dot3+Dot6+Dot8
- Space+Dot1+Dot3+Dot4+Dot6+Dot8

I cannot test anymore by myself, but a French vendor reported me these problem.

### LINKED ISSUE #6063: Mapping more braille display keys by default on Hims braille displays
As an employee at Babbage (the Netherlands), I've talked to BrailleEdge customers who are interested in more default key mappings for the Hims Braille driver. For example, several keys lack mappings by default, while they are mapped to emulated system keyboard keys in other screen readers.

I might be able to work on this either in work or spare time, so feel free to assign this issue to me. I wil also investigate the SmartBeetle. Though if the main devs aren't interested in those additions, let me know.

### LINKED ISSUE #6086: hims smart beetle not working as expected
When connecting a smart beetle display from hims, I get the following issues:
1. Many keys on the display do not work: the two scrolling keys don't work and the function keys for control, windows, alt and home don't work either. The braille input keyboard does work though.
2. When the display is disconected and reconnected, nvda doesn't automatically use the display again. I have to go into the braille settings dialog and press ok for it to work.

### LINKED ISSUE #7459: Provide a native driver for Hims displays
I've started investigating some more details for a native driver for Hims devices today. This should fix #6063 and #6086.

One major problem is that Hims devices use a custom USB driver, which presents itself as a generic USB serial. However, it is neither native serial nor HID. I've tried to sniff the data sent from and to the device using a free tool called Device Monitoring Studio or [Free USB Analyzer](https://freeusbanalyzer.com/), and I'm perfectly able to interpred the data, so that's at least one positive thing.

I started with creating a new class called Usb in the hwIo module, which is actually a copy of the Hid class excluding the Hid specific part (i.e. the Hid __init function in hwIo.py except for line 244--256. According to the USB sniffer, it seems output packages are at least 10 bytes in size for the current driver, incoming packages seem to be 4 bytes or more. So, I create a new Usb object with the proper path, onReceiveSize=4 and writeSize=10, but writing using this object doesn't seem to deliver anything to the device, that is, the USB sniffer doesn't detect any traffic.

@JCSTeh: I'd like to have your advice on this. Is this the proper way to pump data into a device, or should I set up the file handle differently for example?

### LINKED ISSUE #7679: Using HIMS Smart Beetle, pressing "scroll back" or "scroll forward" does not scroll the display
When I press the scroll buttons on either side of the Smart Beetle display, NVDA does nothing, when it should scroll the display. I'm using NVDA 2017.3.

### LINKED ISSUE #7837: HIMS Smart Beetle Scroll Buttons Say "malformed"
I still get the issue of scroll buttons on the Smart Beetle not working as expected in NVDA 2017.4, so tried to assign them to the scroll commands by using the "Input gestures" dialog. Here are the results.

### Steps to reproduce:

* Connect the Smart Beetle over Bluetooth.
* Open the "Input gestures" dialog.
* Open the "Braille" branch and navigate to the "Scrolls the braille display back" entry.
* Press the "Add" button.
* Press one of the scroll buttons on the Smart Beetle.

### Expected behavior:

NVDA should register the scroll button.

### Actual behavior:

NVDA assigns "malformed:br(hims)" when the scroll button is pressed. Interestingly, this lets me scroll, but since both the scroll back and scroll forward buttons both register "malformed:br(hims)", I can only scroll in one direction. I have to assign different dot combinations to the scroll commands to get the Smart Beetle to actually scroll. When I do this (for example, assigning dots 2-3-space to scroll backwards,) pressing dots 2-3-space does scroll the display backward. So the gesture is working, it is only that the scroll buttons are not being recognized.

### System configuration:

NVDA version: 2017.4

NVDA Installed or portable: Installed

Other information:

Windows version: 10, Fall Creator's Update

Name and version of other software in use when reproducing the issue:

### Other questions:

Does the issue still occur after restarting your PC? Yes

Have you tried any other versions of NVDA? Yes

Using 2017.3, I also could not scroll the display.

### PR DESCRIPTION
**Pull request by LeonarddeR**
This driver has been written by @babbagecom with the consent of Hims.

[Try build](https://ci.appveyor.com/api/buildjobs/5dcmf2ctol5e417r/artifacts/output%2Fnvda_snapshot_try-hims-native-14573%2C8dd4b89a.exe)
### Link to issue number:
Closes #7459.
Fixes #7679.
Closes #6063
Fixes #6086.
Fixes #3157.
fixes #7837.

### Summary of the issue:
The current Hims and syncBraille drivers currently require a vendor library and aren't thread safe. Furthermore, other prerequisites (such as disabling the driver when a write error occurs) aren't met by these drivers.

### Description of how this pull request fixes the issue:
This:

1. Implements a native driver based on the hims data protocol, version 1.1
2. Properly supports all keys on Smart Beetle displays
3. Has many more key assignments by default
4. Has support for Sync Braille displays, although untested as of yet, since I don't have a Sync Braille myself. The Sync Braille is FTDI2, but according to Hims, it also exposes a generic COM port. Testing of Sync Braille devices would be greatly appreciated.
5. Adds a Bulk class to hwIO, thereby adding support for Bulk style USB devices. This is specific to Hims displays for now, but Freedom Scientific displays also use Bulk style communication. This also contains code by @bramd

In comparison with the earlier Hims driver, this remaps the scroll keys for devices with multiple scroll keys to follow the conventions of the internal functionality and other screen readers. Furthermore, the keys that were known as advance keys earlier are now named f keys, since this is how Hims names them.

### Testing performed:
Tested the following devices:

* Smart Beetle (USB)
* Braille Sense u2 mini (Both USB and Bluetooth)

I've also tested a Braille Edge, a Braille Sense u2 Qwerty and a Braille Sense u2 Perkins with earlier iterations of this driver.

### Known issues with pull request:
* Sync Braille is currently untested.

### Change log entry:
* Changes
    + The HIMS Braille Sense/Braille EDGE/Smart Beetle and Hims Sync Braille display drivers have been replaced by one driver. The new driver will automatically be activated for former syncBraille driver users. (#7459)
        - Some keys , notably scroll keys, have been reassigned to follow the conventions used by Hims products. Consult the user guide for more details.

* Bug fixes
    + Detection of scroll keys on Hims Smart Beetle displays is no longer unreliable. (#6086)

* Changes for developers
    + A new dictionary (braille.RENAMED_DRIVERS) has been added to allow for smooth transition for users using driver that have been superseded by others. (#7459)

### CODE REVIEW

**Comment by leonardder** [comment]
Note, I opened a pr for this to allow for easier tracking of progress. Though I consider this driver ready, I'd like feedback from Sync Braille users before this is ready for review.

**Comment by leonardder** [comment]
I've received positive test results from a Sync Braille user and made some changes based on the feedback I've gotten. This is now ready for a review.

**Review by michaelDCurran — APPROVED** [review]

**Comment by michaelDCurran** [comment]
Can hansoneConnect.dll be removed now that this pr is merged? Happy to do it, but just checking.

**Comment by leonardder** [comment]
Yes, as well as de dll for sync braille.

**Pull request merged**
