### PR TITLE
Fix translatable strings using f strings

### LINKED ISSUE #10532: When testing Vision framework with NVDA beta-19263 and alpha-19262: Always &show a warning when loading {screenCurtainTranslatedName} String does not take effect after translation
### Steps to reproduce:
First download the translation test template from [here](https://ci.appveyor.com/api/buildjobs/wuvi0ditnx1v80l4/artifacts/output%2Fnvda_snapshot_beta-19263%2C04569185.pot)
Then copy zh_CN-nvda.po Open the nvda.po with poedit and update the .po file with snapshot_beta-19263,04569185.pot
Final translation
Always &show a warning when loading {screenCurtainTranslatedName} String
Generate nvda.mo to cover NVDA-locale-zh_CN-LC_MESSAGES nvda.mo restart NVDA for testing
### Actual behavior:
Post-translation string does not take effect
### Expected behavior:
Post-translation string does not take effect
#### NVDA installed/portable/running from source:
install version
#### NVDA version:
beta-19263 and alpha-19262
#### Windows version:
windows10-1909
#### Name and version of other software in use when reproducing the issue:
NVDA-alpha-19262
#### Other information about your system:
none
#### Does the issue still occur after restarting your PC?
yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
no
NVDA-log:
none
thanks

### PR DESCRIPTION
**Pull request by LeonarddeR**
### Link to issue number:
Fixes #10532 

### Summary of the issue:
Translatable strings using the f literal are not supported, yet we use them in the vision framework.

### Description of how this pull request fixes the issue:
Use the format function on these strings instead.

### Testing performed:
T.b.d.

### Known issues with pull request:
None known

### Change log entry:
None

### CODE REVIEW

**Comment by dingpengyu** [comment]
hi
Tested nvda_snapshot_pr10534-19265 using Simplified Chinese zh_CN:
now
Always &show a warning when loading {screenCurtainTranslatedName}
The translated string can be displayed normally
thanks

**Comment by feerrenrut** [comment]
Ah, yes. This is a mistake! There are several other instances of this. Worth searching the code base and fixing them all.

**Comment by leonardder** [comment]
Ugh, I did that actually, but it looks like it wasn't pushed.

**Review by feerrenrut — APPROVED** [review]
Thanks @leonardder. I searched too, and got the same results as you.

**Comment by lijianwei2019** [comment]
@leonardder @feerrenrut 
This issue returns in alpha-19488

**Comment by leonardder** [comment]
Ugh, we must make a test for this somehow

**Comment by feerrenrut** [comment]
@leonardder shouldn't be too hard. Anyone interested in making a flake8 lint plugin could start with the docs: https://flake8.pycqa.org/en/latest/plugin-development/

**Comment by lijianwei2019** [comment]
Sorry. Translation issues have been fixed. Thank you for your reply.

**Pull request merged**
