### PR TITLE
Disable application volume and mute features when sound split is off or when wasapi is off

### LINKED ISSUE #16402: Unmuting other apps does not work as expected
### Steps to reproduce:
1. Launch NVDA and an audio stream in the background, e.g. youtube playing music in  a browser
2. Press NVDA+alt+delete to mute all apps except NVDA.
As expected, Youtube is muted.
3. Exit NVDA
4. Start NVDA again
5. Press NVDA+alt+delete
6. Press NVDA+alt+delete

### Actual behavior:
2. Youtube stream is muted
3. Youtube stream remains muted
4. Youtube stream remains muted
5. NVDA says "Applications muted" and Youtube stream remains muted
6. NVDA says "Applications unmuted" and Youtube stream is restored (unmuted)

### Expected behavior:
At least, at step 5, NVDA should already know that the other apps are muted and it should unmute them.

I really think that NVDA should not store in its config nor manage an additional muted state. For clarity it should be able to mute and unmute directly the sound as configured in Windows Volume mixer. Else people may have muted through the volume mixer and can wonder why they cannot unmute through NVDA. In other words, putting two switches serially leads to a confusing user experience.

I have not tested but we may encounter the same issues with other apps volume management commands.

In #16273, you indicate that you are using the same framework for mute other apps or other apps volume commands than in sound split. IMO muted state and volume of ther apps should not be stored in NVDA's config, nor should they be restored or re-configured at NVDA exit/startup. They should just be a more easy way to control Windows Mixer's parameters. On the other side, Split mode should be set up according to NVDA's config and disabled when NVDA exits since it's a feature that only has sense when NVDA is active; thus it makes sense to manage it internally to NVDA and Windows Volume Mixer should not be touched for Sound Split feature.

### NVDA logs, crash dumps and other attachments:
None
#### NVDA installed/portable/running from source:
From source
#### NVDA version:
Last alpha, commit 3d4a0a8f7b1d124231e9774d30d07cc549dac3fc.
#### Windows version:
Windows 10 22H2 (AMD64) build 19045.4170
#### Name and version of other software in use when reproducing the issue:
N/A
#### Other information about your system:
N/A
#### Does the issue still occur after restarting your computer?
Not tested.
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
No; new feature
#### If NVDA add-ons are disabled, is your problem still occurring?
Yes
#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
Not tested

### LINKED ISSUE #16409: Apps mute and volume features work very unexpectedly with WASAPI disabled
### Steps to reproduce:

1. IN NVDA Advanced settings, set WASAPI to disabled.
2. Apply, save config, and restart NVDA.
3. Start some sound playing. I used Firefox, playing a video.
4. Attempt to mute other apps (`NVDA+Alt+Del`).
5. Attempt to change volume of other apps (`NVDA+Alt+pgDn`).
6. Continue lowering volume of other apps to 20 or so.
7. In NVDA Advanced settings, enable WASAPI.
8. Save config and restart NVDA.

#### At step 4, NVDA says:

>Sound split cannot be used. Please enable WASAPI in the Advanced category in NVDA Settings to use it.
>Applications muted

First,. I was not trying to use Sound Split. Why is it being mentioned?
Second, Applications have not been muted, so the message is false.

#### At step 5, NVDA says:

>Sound split cannot be used. Please enable WASAPI in the Advanced category in NVDA Settings to use it.
>Applications volume 95

First, I was not using Sound Split, again.
Second, the application volume was not changed, so the message is false.

#### At step 8:

Upon NVDA restart, the volume of the other application--which was previously not changed--suddenly drops precipitously to match the volume that was set while WASAPI was disabled.

### Expected behavior:

At step 4, NVDA should speak only something like:

>Application mute is only supported when WASAPI is enabled in NVDA advanced settings.

At step 5, NVDA should speak only something like:

>Application volume changes are only supported when WASAPI is enabled in NVDA advanced settings.

At step 8, the volume should not change on NVDA startup, because step 4 should not have changed any volume in configuration.

#### NVDA installed/portable/running from source:

Portable.

#### NVDA version:
alpha-31622,11a2b4f1

#### Windows version:
11 HOME 23H3

#### Name and version of other software in use when reproducing the issue:
N/A

#### Does the issue still occur after restarting your computer?
N/A

#### Have you tried any other versions of NVDA? If so, please report their behaviors.
No.

#### If NVDA add-ons are disabled, is your problem still occurring?
Yes.

#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
Of course.

### PR DESCRIPTION
**Pull request by mltony**
### Link to issue number:
Closes #16402
Closes #16409
### Summary of the issue:
Mute applications command works incorrectly when sound split is off. or when wasapi is off.
### Description of user facing changes
Now muting other apps or adjusting other apps volume only works when sound split is not set to off.
Also speaking error message when wasapi is off.
### Description of development approach
Since #16287 I had to introduce explicit sound split off mode, which is not supposed to touch volumes of other applications through wasapi. Since adjusting and muting volume of other apps done through the same logic, disabling it for sound split off mode.
### Testing strategy:
Tested the following conditions:
* Muting and adjusting volumes of other apps doesn't work when sound split is off.
* muting is temporary when sound split is enabled. That is after restart all apps are unmuted.
* Adjusting volumes of other apps is permanent across restarts - as expected.

### Known issues with pull request:
N/A
### Code Review Checklist:

- [x] Documentation:
  - Change log entry
  - User Documentation
  - Developer / Technical Documentation
  - Context sensitive help for GUI changes
- [x] Testing:
  - Unit tests
  - System (end to end) tests
  - Manual testing
- [x] UX of all users considered:
  - Speech 
  - Braille
  - Low Vision
  - Different web browsers
  - Localization in other languages / culture than English
- [x] API is compatible with existing add-ons.
- [x] Security precautions taken.

### CODE REVIEW

**Comment by CyrilleB79** [comment]
@mltony, this PR totally defeats the use of the mute other apps feature, at least in the majority of its use case.

The users will use NVDA with sound split disabled most of the time. But during this time, they may still want to mute other apps quickly with a handy shortcut.

I understand that there is a correlation in your implementation between sound split and other apps muting or volume changing. But as already written elsewhere, I really think that you should de-correlate these two features. And if possible link other apps volume setting or muting to Windows Volume Mixer instead, while keeping sound split internal to NVDA.

I guess that we should really re-clarify why the mute other apps feature was requested, but probably not in this PR...

**Comment by mltony** [comment]
Decorellating is hard. Since sound split and apps volume use the same API and if we separate them in NVDA codebase, we'll have to deal with all the pain from their inevitable interference.
And there's been a strong push by @LeonarddeR et al to have soundSplit off = don't touch anything via wasapi. I would think that implies not muting other applications.
So it seems to me "you can't both have a cake and eat it" type of situation.
Also in order to mute apps you can switch sound split to NVDA_BOTH_APPS_BOTH - which is in most situations equivalent to sound split off.

**Comment by CyrilleB79** [comment]
> Decorellating is hard. Since sound split and apps volume use the same API and if we separate them in NVDA codebase, we'll have to deal with all the pain from their inevitable interference.

I think a path to investigate is to see if it's possible to modify apps mute/volume so that it is reflected in Windows Volume Mixer.
But if there is no other way to do it, I really think that dealing with the interference of both features is needed.

> And there's been a strong push by @LeonarddeR et al to have soundSplit off = don't touch anything via wasapi. I would think that implies not muting other applications.

Why do you think that the same reason apply for other apps muting. As I describe in #16402, the use case between other apps muting and sound split are not the same IMO.
Muting or modifying volume of other apps should be considered as a way to control Windows Volume Mixer thanks to shortcuts implemented in NVDA. Whereas sound split should not touch Windows Volume Mixer at all and should remain internal to NVDA.

> Also in order to mute apps you can switch sound split to NVDA_BOTH_APPS_BOTH - which is in most situations equivalent to sound split off.

Yes, I know, but NVDA_BOTH_APPS_BOTH is not the default setting; and I do not say that it should be.

Another strange thing is that if your other apps are muted and you turn back to sound split off, the other apps are unmuted. That's quite a strange and bad UX.

**Comment by mltony** [comment]
Shall we drop apps mute then? Looks like you're not happy with this implementation and originally I only intended to add adjusting other apps volume specifically for sound split. I only added apps mute as per your request, but now it seems like it might not be that good of a fit here in the end. Then perhaps you or someone else can implement apps mute later using some other technique. WDYT?

**Comment by LeonarddeR** [comment]
> Shall we drop apps mute then?

I would at least take it back to the drawing board. Note that #16273 was merged without some comments in #16042 being addressed. In my opinion, there is also a task for NV Access to manage these types of processes and to be very cautious in merging features about which there is doubt among part of the core community. afterwards.

**Comment by XLTechie** [comment]
@mltony asked:
       Shall we drop apps mute then?

It is my personal opinion that mute makes more sense to keep than volume. I don't think I was convinced of the value of having these in core, but as I am a power user who has no difficulty using Windows Volume Mixer, I figure I am not the target audience for either feature.

But in thinking on this further, I have come to the conclusion that if I was going to use one of them ever, it would most likely be mute, if I was in a situation where audio ducking didn't work (like a portable copy).

So having a "mute everything but NVDA" toggle, that was active only as long as NVDA was active, makes some sense as a screen reader support feature.

We have gone around and around about why people want the volume feature, and I'm not going to bother arguing against that any more. It's done, it's in core, and that's what users wanted for some reason.

**Comment by amirsol81** [comment]
@mltony Honestly muting other apps when Sound Split is disabled is what, IMO, most users might want to do, so if muting would be disabled when Sound Split is off, it'll lose most of its usefulness and appeal. As such, I think if we are supposed to keep muting other apps, it should work regardless of whether or not Sound Split is enabled. If these can't be separated or if issues like #16402 can't be fixed easily, I suggest removing the mute feature and retaining the volume adjustment.

**Comment by amirsol81** [comment]
@XLTechie Oddly enough, I think volume adjustment makes more sense compared with muting, but I understand that this is absolutely personal. Ideally both should be retained if issues can be resolved - I mean stuff like restoring the mute state upon exiting, or restarting, NVDA. But if one is to be retained, I think it should be app volume adjustment.

**Comment by CyrilleB79** [comment]
IMO the discussion here is not should we keep mute or volume? Both feature are quite similar and the issues found with one of them will probably be found with the other one.

I guess that most of us also agree or at least accept that these features be integrated in core since they answer to the need of many people.

Though, there is an on-going discussion in #16402 about reverting the whole feature. And it should be clarified before going further with this PR.

**Comment by mltony** [comment]
@CyrilleB79, I checked source code of Sound Manager, they just use simple audio volume. I think you're right in the sense that this might allow us to decouple apps volume adjusting from sound splitting. I would need to make a prototype to confirm that ISimpleAudioVolume and IChannelAudioVolume interfaces don't interfere with each other in some weird unexpected way.
There is going to be new interference with Sound Manager  add-on though. But I can make it so that when volume=100% and mute=False, the feature will be effectivly off and so in this mode Sound Manager  or any other addons that use ISimpleAudioVolume should work without problems.

**Comment by Adriani90** [comment]
It was clear from the beginning of the feature design that the use case is in situations where sound split is used and still the other apps are too loud. There was never the discussion to control Windows volume mixer via NVDA. So I think there was always actually the understanding that these settings are linked to the sound split which is restored after NVDA exit.
I don't agree with controlling the volume mixer via NVDA.
Use case reported by @CyrilleB79: 
> I use NVDA and have set my other apps volume quite low (e.g. 5%) to continue having music played in the background. During my tasks, I install an add-on and restart NVDA. As soon as NVDA exits, the music begins shouting loud.

I understand this use case, but this happens with audio ducking set to always as well. The volume is restored. At the other end if you are using a computer together with a person with hearing problems, and this person needs the loudness for its tasks, it is really not a good idea to let any negative traces after using NVDA.
I suggest @mltony continues with its solution and I propose to restore the volume of apps as well after NVDA exits.
I think NVDA could remember the volume of apps as it remembers the sound split setting when starting NVDA, but the muted / unmuted state should still remain temporary.

**Comment by Adriani90** [comment]
Why is there the desire to control the volume mixer at all via NVDA when the mixer itself is accessible? The use case for these settings in NVDA are for on demand purpose and are only linked to the NVDA user. I don't see any arguments to link the volume mixer here.

**Comment by Adriani90** [comment]
@CyrilleB79 wrote:
> The users will use NVDA with sound split disabled most of the time. But during this time, they may still want to mute other apps quickly with a handy shortcut.

I don't think this is true. If users will discover the benefits of using sound split, they will rather use that. And I think even having this feature to mute other apps when sound split is on it will make this feature more attractive anyway.
Users who are not using sound split can still use the audio ducking feature for less volume, or use the accessible mixer for muting the apps.

But yeah, I am not against having that decoupled from sound split if possible as long as it stays a temporary setting until NVDA exits. The same for apps volume.

**Comment by amirsol81** [comment]
@Adriani90 I have discovered the benefits of the Sound Split, but they really don't fit into my daily use case. I guess there will be many users like me. However, I do want to be able to alter the volume or mute other apps via NVDA's easy-to-access key strokes when the Sound Split is disabled. As @CyrilleB79 mentioned, the feature will be utterly defeated if it fails to work with Sound Split disabled.

**Comment by Adriani90** [comment]
@amirsol81 as I said, I am not against decoupling as long as it restores after exiting NVDA.
But if this is not technically possible at this stage, this should not block this PR. And still lots of users will benefit from these settings, even though it works only with sound split on.
Making this work with sound split disabled can be handled in a separate PR if it turns out to be technically too complex at this stage.

**Comment by XLTechie** [comment]
@Adriani90 asked:
> Why is there the desire to control the volume mixer at all via NVDA when the mixer itself is accessible?

At least for me, the reason is this. Consider the following circumstance:

1. NVDA and sighted user share the same computer.
2. NVDA user mutes other apps while playing a video in Firefox.
3. NVDA user quits NVDA and leaves.
4. Sighted user tries to play a video in Firefox, but finds it muted.
5. Sighted user goes to volume mixer to unmute it, only to find that it is already unmuted in volume mixer. In fact, pressing mute/unmute has no effect.
How does the sighted user get audio back? The same question can be asked for volume changes.

Further, if an NVDA user mutes audio/changes volume accidentally, and is not experienced, how is a sighted user (or Microsoft accessibility support, etc.) likely to help, with or without NVDA? By going to the system volume mixer, I would think.

So not having these changes synchronized with the standard way that Windows manipulates audio, seems like a degraded UX all around.

**Comment by seanbudd** [comment]
Can you please re-target this PR to beta

**Comment by seanbudd** [comment]
Generally you would have to do `git rebase -i beta`. I would encourage reading up on this and testing it out first on a separate branch.

In this case I just needed to retarget via the GitHub interface, as master is now identical to beta, so no need to take further action.

**Comment by Adriani90** [comment]
@XLTechie  
> How do sighted people get volume back?

NVDA restores it after exit.


@mltony
Not restoring things after NVDA exit will introduce inconsistencies e.g. with audio ducking feature and will break user experience. @seanbudd  this PR fixes this, because the feature as is now in alpha is not acceptable. So I would say it is important to remove the blocked label and continue working on this.

re decoupling in my view it is out of scope for this PR and can be handled in a separate discussion.

**Comment by LeonarddeR** [comment]
@Adriani90 
> The feature as is now in alpha is not acceptable. So I would say it is important to remove the blocked label and continue working on this.

If the feature as is is not acceptable and the current pr needs a product decision (i agree with both), then the preferable solution is reverting the feature and providing a new pr that is in line with the product decision to be made.

**Comment by Adriani90** [comment]
This PR makes it acceptable, no product decision needed.Von meinem iPhone gesendetAm 18.04.2024 um 08:13 schrieb Leonard de Ruijter ***@***.***>:﻿
@Adriani90

The feature as is now in alpha is not acceptable. So I would say it is important to remove the blocked label and continue working on this.

If the feature as is is not acceptable and the current pr needs a product decision (i agree with both), then the preferable solution is reverting the feature and providing a new pr that is in line with the product decision to be made.

**Comment by cary-rowen** [comment]
I also agree that sound split and application volume should be decoupled.

**Comment by Adriani90** [comment]
In a separate PRVon meinem iPhone gesendetAm 18.04.2024 um 08:27 schrieb Rowen ***@***.***>:﻿
I also agree that sound split and application volume should be decoupled.

**Comment by XLTechie** [comment]
@Adriani90 you wrote something puzzling:

> Not restoring things after NVDA exit will introduce inconsistencies e.g. with audio ducking feature and will break user experience. @seanbudd this PR fixes this, because the feature as is now in alpha is not acceptable. So I would say it is important to remove the blocked label and continue working on this.

All this PR does is make mute/volume features only work with sound split enabled. It does not claim to do anything about restoring states after NVDA closes. Can you explain why you say it fixes that issue?

Personally, I agree with those who believe that this PR should be closed--if muting and volume changes exist in NVDA, they should work with or without sound split.

**Comment by Adriani90** [comment]
This will be solved by this PR as far as I understand. Audio ducking feature does this already and there is no risk NVDA messes up  any audio. That problem won‘t exist after this PR is merged.Von meinem iPhone gesendetAm 18.04.2024 um 09:05 schrieb Luke Davis ***@***.***>:﻿
To my question "How do sighted people get volume back?" @Adriani90 answered:

> NVDA restores it after exit.

Not currently, but that's only a small part of the problem. Please read the remainder of my previous comment, and answer what is likely to happen if Microsoft disability or another sighted assistant, is trying to help a user restore sound if that user accidentally messed up other apps sound through NVDA? In that case, NVDA will likely still be running, but the SVM will do nothing.
That could lead to long and unnecessary Windows repair actions, driver reinstallation, etc. All because NVDA is using an unusual mechanism to manipulate app volume.

**Comment by XLTechie** [comment]
@Adriani90
> This will be solved by this PR as far as I understand

The title and description of this PR say otherwise. The code, which I have read, doesn't appear to contain any change that would do what you are saying as far as I can tell.

**Comment by CyrilleB79** [comment]
There are many discussions and various open issues/PRs following the mute and volume control for other apps introduced in #16273. This leads to various impacts of this feature being discussed in various places, which is inefficient. This reveals that this feature is not mature enough or that the design and the use cases have not been correctly explained and listed.

I think that @LeonarddeR suggestion to revert the feature until a design with clear use cases is discussed and understood by all is the best course of action.

I am quite disappointed to request this revert because @mltony has done a great job to push this in core and because his availability period may reach its end, so there is a risk that this feature may not be reintegrated soon if he is not available to work on it anymore.
But this seems the best solution if we want a clear and centralized discussion on this feature.

@seanbudd, @gerald-hartig what do you think?

**Comment by Adriani90** [comment]
@XLTechie 
> Can you explain why you say it fixes that issue?

See description of user facing changes. @mltony writes:
> Now muting other apps or adjusting other apps volume only works when sound split is not set to off.

And sound split restores apps volume after NVDA exits as far as I understand. @mltony can you comment on this?

> Personally, I agree with those who believe that this PR should be closed--if muting and volume changes exist in NVDA, they should work with or without sound split.

I disagree. Decoupling from sound split can be handled afterwards at a later stage, we don't have to wait for the perfect world until something is merged in my view at least. If decoupling is the only point we have to solve, this can be discussed separately.

> This leads to various impacts of this feature being discussed in various places, which is inefficient. This reveals that this feature is not mature enough or that the design and the use cases have not been correctly explained and listed.

This will be the case for lots of new features which might come into NVDA in the future. Things will be discussed in different places. These discussions have been taken place because of 3 things:
1. Reverting the feature (which is not really needed in my view because this feature doesn't degradate user experience, but it improves it)
2. Decoupling from sound split (which is a different issue and can be handled separately and should not block this feature from being merged)
3. And restoring volume and mute / unmute state (which will be added after merging this PR and which is the expected behavior in line with audio ducking feature).

> I am quite disappointed to request this revert because @mltony has done a great job to push this in core and because his availability period may reach its end, so there is a risk that this feature may not be reintegrated soon if he is not available to work on it anymore.
But this seems the best solution if we want a clear and centralized discussion on this feature.

I strongly disagree with reverting this. Further improvements can be discussed separately and there are alot of features which were introduced in NVDA earlier and did not have enough discussions with the community, still they are accepted and improvement requests are in place. For example OCR feature, Add-on store, object navigation etc.

**Comment by josephsl** [comment]
Hi, one thing we need to remind ourselves: master branch code was just merged into beta (for documentation file preparation among other reasons) and 2024.2 release blurb was published. On one hand we could ask Tony to rebase his fix on beta branch in May. On the other hand deferring app volume mute would be better to provide a more stable (and slightly more polished) experience for 2024.2 users. Thanks.

**Comment by mltony** [comment]
I just squeezed in a fix for#16409 as well here - hope that's ok.

As for decoupling aplication volume from sound split, it seems to me that more people are in favor of decoupling. Personally I am biased towards decoupling too: I especially like the argument that by switching to ISimpleAudioVolume mute/volume changes will be reflected in Windows Volume mixer. Unless there are any concerns, I'll try to prepare anotehr PR for beta branch in the next couple of days. Or please LMK if that shouldn't go into beta.

@LeonarddeR 

> I would at least take it back to the drawing board.

It has been at the drawing board stage for quite a while - #16052 was opened in January. It would seem counterproductive to me to roll back features because of concerns (unless such concerns are critical). Open source projects typically don't move very fast to begin with, so we don't want to have analysis paralysis.

**Comment by Adriani90** [comment]
Tony, as long as the reflected changes in the volume mixer are restored after NVDA exit, I don’t see any issue with that. I think the audio ducking feature reflects also changes there but restores them after NVDA exit.

 

 

 

Von: mltony ***@***.***> 
Gesendet: Freitag, 19. April 2024 00:03
An: nvaccess/nvda ***@***.***>
Cc: Adriani90 ***@***.***>; Mention ***@***.***>
Betreff: Re: [nvaccess/nvda] Disable application volume and mute features when sound split is off or when wasapi is off (PR #16404)

 

I just squeezed in a fix for#16409 as well here - hope that's ok.

As for decoupling aplication volume from sound split, it seems to me that more people are in favor of decoupling. Personally I am biased towards decoupling too: I especially like the argument that by switching to ISimpleAudioVolume mute/volume changes will be reflected in Windows Volume mixer. Unless there are any concerns, I'll try to prepare anotehr PR for beta branch in the next couple of days. Or please LMK if that shouldn't go into beta.

@LeonarddeR <https://github.com/LeonarddeR> 

I would at least take it back to the drawing board.

It has been at the drawing board stage for quite a while - #16052 <https://github.com/nvaccess/nvda/issues/16052>  was opened in January. It would seem counterproductive to me to roll back features because of concerns (unless such concerns are critical). Open source projects typically don't move very fast to begin with, so we don't want to have analysis paralysis.

**Comment by CyrilleB79** [comment]
> Tony, as long as the reflected changes in the volume mixer are restored after NVDA exit, I don’t see any issue with that. I think the audio ducking feature reflects also changes there but restores them after NVDA exit.

No, the audio ducking has no impact on Windows Volume Mixer. It's considered a change internal to the screen reader, not from a coding point of view, but in consideration to the fact that the audio ducking volume lowering disappears when the screen reader is exited.

There is no automatic process modifying the Volume Mixer today, and that's why I am advocating for the volume mixer not being modified automatically when NVDA exits. Since they will be reflected in the Volume Mixer, the other apps volume or mute commands should just be considered convenience shortcut to modify settings in the Volume Mixer in one keystroke. This makes it the simplest and clearest user experience.

@mltony by the way, since the volume / mute other apps become convenience shortcuts to control Windows Volume Mixer, I wonders if it's still useful to keep the associated controls in NVDA's GUI (audio panel). Keeping them leads to a greater risk of synchronization issues with the Volume Mixer. You also do not need to consider profile switch or config reset anymore.

**Comment by Adriani90** [comment]
In this case I vote for this feature to be an NVDA internal feature like audio ducking as well, due to my real use case above and the negative impact from not restoring volume and mute state after NVDA exit.If restore volume and mute state after NVDA exit is not possible, only in this case I vote for reverting this feature.Von meinem iPhone gesendetAm 21.04.2024 um 22:30 schrieb Cyrille Bougot ***@***.***>:﻿

Tony, as long as the reflected changes in the volume mixer are restored after NVDA exit, I don’t see any issue with that. I think the audio ducking feature reflects also changes there but restores them after NVDA exit.

No, the audio ducking has no impact on Windows Volume Mixer. It's considered a change internal to the screen reader, not from a coding point of view, but in consideration to the fact that the audio ducking volume lowering disappears when the screen reader is exited.
There is no automatic process modifying the Volume Mixer today, and that's why I am advocating for the volume mixer not being modified automatically when NVDA exits. Since they will be reflected in the Volume Mixer, the other apps volume or mute commands should just be considered convenience shortcut to modify settings in the Volume Mixer in one keystroke. This makes it the simplest and clearest user experience.
@mltony by the way, since the volume / mute other apps become convenience shortcuts to control Windows Volume Mixer, I wonders if it's still useful to keep the associated controls in NVDA's GUI (audio panel). Keeping them leads to a greater risk of synchronization issues with the Volume Mixer. You also do not need to consider profile switch or config reset anymore.

**Comment by seanbudd** [comment]
Closing in favour of reverting the mute application feature

**Comment by mltony** [comment]
@seanbudd,
I would urge you to reconsider. This feature is an integral part of sound split and without this feature sound split functionality is going to be inadequate - since we'll be able to only split volumes, but not adjust left and right  volumes separately.
I think my mistake was to spin it off as a separate feature which causes a lot of confusion.
And BTW this particular bug is fixed in

**Comment by cary-rowen** [comment]
I also hope to reconsider this. The community has a need for this, and Tony is willing to implement this. If further discussion is needed, please let the community know.

**Comment by gerald-hartig** [comment]
Hello everyone. With the public holiday calendar in Australia and various ongoing discussions this week, we have not been able to respond in detail to this issue or https://github.com/nvaccess/nvda/pull/16440. Rather than rush something out and risk a misunderstanding, I wanted to let you know that it's on our list and we'll respond shortly.

**Comment by gerald-hartig** [comment]
@cary-rowen I've updated the description of #16440 and put a comment in there.

**Pull request closed without merging**
