### PR TITLE
Update brlapi to 0.8

### PR DESCRIPTION
**Pull request by LeonarddeR**
### Link to issue number:
None

### Summary of the issue:
With the migration to Python 3, we had to update our brlapi dependency to 0.7 to support the brltty braille display driver. However, there wasn't an upstream build of the brlapi python bindings, therefore we had to build them ourselves.

### Description of how this pull request fixes the issue:
Thanks to @davemielke, BRLTTY 6.1 bundles a brlapi binding built against Python 3.7 we could use directly from upstream. Note that it is still bundled inside our misc-deps repository.

### Testing performed:
Tested a try build with brlapi 0.8 against an installed build of brltty 6.1. I'm pretty sure however that this brlapi should still be able to work with older versions of brltty, may be @davemielke can give some info on that.

### Known issues with pull request:
None

### Change log entry:
* Changes for developers
    + Updated BrlApi to version 0.8 (BRLTTY 6.1). (#11065)

### CODE REVIEW

**Review by feerrenrut — APPROVED** [review]
Thanks @leonardder

**Comment by lukaszgo1** [comment]
@leonardder While I no longer have the old ALVA which requires BRLTTY and therefore no BRLTTY is installed on my system, in the previous Alpha's it was possible to import brlapi anyway, and BRLTTY was present in the braille displays list whereas now it is not. Additionally there is no brlapi.dll in the NVDA folder anymore. Is this a change in brlapi bindings?

**Comment by leonardder** [comment]
Ugh, you're correct. Interesting enough, I tested this with a try build and that all went fine. It's [this](https://ci.appveyor.com/api/buildjobs/ofk6m1j4onrdn106/artifacts/output%2Fnvda_snapshot_try-brlapi0.8-20052%2Cc9c9ed6f.exe) try build. Let me investigate what went wrong here.

**Comment by leonardder** [comment]
filed https://github.com/nvaccess/nvda-misc-deps/pull/18

**Pull request merged**
