### PR TITLE
Less rigorous attempt to fix window point conversion functions not exposing failure

### PR DESCRIPTION
**Pull request by LeonarddeR**
### Link to issue number:
Follow up of #9269

### Summary of the issue:
There are 4 functions wrappers related to screen, client, logical and physical coordinate conversions.

* windowUtils.logicalToPhysicalPoint
* windowUtils.physicalToLogicalPoint
* winUser.ClientToScreen
* winUser.ScreenToClient

These functions take a window handle and a point structure and return 1 on success and 0 on failure. The user32 functions also set the last error when the functions fail. The point in the structure is used to calculate a new point, and on success, the coordinates in the structure are replaced. On failure, the coordinates stay the same.

However, the wrappers of these functions silently return whatever is in the structure, thereby silently ignoring whether the underlying function succeeded or failed.
As far as I've seen, for the user32 functions this is only a problem when giving it a wrong window handle. Converting coordinates falling out of the client area of the window works just fine. However, for physicalToLogicalPoint and logicalToPhysicalPoint, the functions also fail when the given coordinates fall outside the window. While normally, providing the wrong coordinates to these functions should not happen, not being able to see whether the underlying function succeeded or failed is problematic for debugging reasons. 

### Description of how this pull request fixes the issue:
1. On failure, the winUser wrappers will now log an error to the log with the windows error included. Note that this does not occur when providing it coordinates that fall outside the client window.
2. the windowUtils functions also log an error. Unfortunately, when these functions fail, they do not set the last error, so there's no way to see why the function failed.
3. Windows XP code is removed from windowUtils.

### Testing performed:
Mainly adds logging, I tested the log calls in the python console.

### Known issues with pull request:
Idially, we'd bring back #9269 later, so this pr is mainly meant to log cases where we need to improve things, rather than making them crash.

### Change log entry:
* Changes for developers
    + The following functions now log an error if they fail. In that case, they return their input. In a future release, they may be changed to raise exceptions instead. (#9269)
        * windowUtils.logicalToPhysicalPoint and windowUtils.physicalToLogicalPoint
        * winUser.ClientToScreen and winUser.ScreenToClient

### Code Review Checklist:
- [x] Pull Request description is up to date.
- [x] Unit tests.
- [x] System (end to end) tests.
- [ ] Manual testing.
- [x] User Documentation.
- [x] Change log entry.
- [x] Context sensitive help for GUI changes.
- [x] UX of all users considered:
  - Speech 
  - Braille
  - Low Vision
  - Different web browsers

### CODE REVIEW

**Comment by leonardder** [comment]
@lukaszgo1: could you possibly play with this given #10751 and #10704 as well as Notepad++ made it necessary to revert the previous attempt?

**Comment by lukaszgo1** [comment]
Hi @leonardder.

Unfortunately #10751 is back though STR given there are no longer valid since OpenTween has been banned by Twitter. You should be able to reproduce as follows:

1. Download Tween from: https://aa9646bd-a-62cb3a1a-s-sites.googlegroups.com/site/tweentwitterclient/download/Tween1760.zip?attachauth=ANoY7cqoFgFvOlM-vPgnajemB7hamTrLm4--R1aFwnPTa6WPBsfeIEVvBi47yUCG07Qt1As4qauAUqcAMs2sFakRu3kWxglLupxBTExUlHCVXNcrqkJPEe7jpM6nANAdArcrhLZwMo3Z0UvsdLG6H2tX4JWE9HG-h3tVwq5Cq5KgJlrfyr4qP5LlUWPZARnGvZkEOGxAOB-TczVGOgjyxy7z9OkQVJnNKjxulPos6N2Z0Qn-oalluE0%3D&attredirects=0&d=1
2. Login to Twitter with it.
3. Try to navigate list of tweets.
The error in the log is as follows:

ERROR - eventHandler.executeEvent (19:09:42.127) - MainThread (6316):
error executing event: gainFocus on <appModules.tween.TweetListItem object at 0x06D3A2D0> with extra args of {}
Traceback (most recent call last):
  File "eventHandler.pyc", line 217, in executeEvent
  File "eventHandler.pyc", line 96, in __init__
  File "eventHandler.pyc", line 105, in next
  File "NVDAObjects\__init__.pyc", line 1105, in event_gainFocus
  File "NVDAObjects\behaviors.pyc", line 610, in reportFocus
  File "NVDAObjects\__init__.pyc", line 991, in reportFocus
  File "speech\__init__.pyc", line 478, in speakObject
  File "speech\__init__.pyc", line 517, in getObjectSpeech
  File "speech\__init__.pyc", line 381, in getObjectPropertiesSpeech
  File "baseObject.pyc", line 42, in __get__
  File "baseObject.pyc", line 146, in _getPropertyViaCache
  File "appModules\tween.pyc", line 26, in _get_name
  File "baseObject.pyc", line 42, in __get__
  File "baseObject.pyc", line 146, in _getPropertyViaCache
  File "NVDAObjects\IAccessible\sysListView32.pyc", line 438, in _get_name
  File "NVDAObjects\IAccessible\sysListView32.pyc", line 382, in _getColumnContent
  File "appModules\tween.pyc", line 44, in _getColumnContentRaw
  File "displayModel.pyc", line 292, in __init__
  File "textInfos\offsets.pyc", line 475, in __init__
  File "displayModel.pyc", line 418, in _getStoryLength
  File "baseObject.pyc", line 42, in __get__
  File "baseObject.pyc", line 146, in _getPropertyViaCache
  File "displayModel.pyc", line 311, in _get__storyFieldsAndRects
AttributeError: 'tuple' object has no attribute 'toLogical'


The issues in Notepad++ are also back.
You need to install add-on for NPP by @derekriemer and start coding with autocomplete enabled. Most of the time everything works as it should, but every so often auto completion is not announced, error sound plays and the following is in the log:

ERROR - windowUtils.physicalToLogicalPoint (19:05:17.633) - MainThread (6888):
Couldn't convert point(x=130, y=479) from physical to logical coordinates for window 3211704
ERROR - windowUtils.physicalToLogicalPoint (19:05:17.649) - MainThread (6888):
Couldn't convert point(x=262, y=496) from physical to logical coordinates for window 3211704



I cannot commend on #10704 since I was never able to reproduce it even with the previous PR.

**Comment by leonardder** [comment]
@lukaszgo1 The first problem you mention is an issue in this pr, so I should be able to fix it. The second error hhonestly is one of the reasons why I think this pr is necessary, the error really is an error that should be fixed somewhere.

**Comment by lukaszgo1** [comment]
@leonardder wrote:

> @lukaszgo1 The first problem you mention is an issue in this pr, so I should be able to fix it. 

Great!

> The second error hhonestly is one of the reasons why I think this pr is necessary, the error really is an error that should be fixed somewhere.



I understand that technically this error is not directly caused by your PR, that this function was failing even before and NVDA was simply ignoring the error, but for an average user these details aren't and shouldn't be important. For him/her auto complete in Notepad++ worked with the old version of NVDA and it doesn't anymore. Knowingly merging PR which introduces regression is not good IMHO and since we are aware that auto complete is going to be broken by this, and we need to fix it eventually at some point  fixing it as part of this PR seems appropriate.

**Comment by XLTechie** [comment]
> The issues in Notepad++ are also back.
> You need to install add-on for NPP by @derekriemer and start coding with autocomplete enabled. Most of the time everything works as it should, but every so
> often auto completion is not announced, error sound plays and the following is in the log:

I can definitely confirm that one, as it just happened to me for the first time 
last night.

I have come to rely very much on autocomplete in notepad++ for speedy Python 
work, it will be very sad if this can not be solved.

Unfortunately this area is far outside my knowledge, so I can not contribute.

**Comment by akash07k** [comment]
Ya, I too notice this problem with Notepad PlusPlus that the auto
complete is not being announced at all which is quite problematic as I
can't use visual studio code because NVDA laggs badly with it, I can't
either use Visual Studio since intelisense bug is impacts the
productivity quite a lot and notepad PlusPlus is not even an option if
auto complete is not being announced.

**Comment by leonardder** [comment]
@lukaszgo1 i'm pretty sure I fixed the issue in Tween now. Now for the NP++ issue.

**Comment by leonardder** [comment]
I found the issue with NP++, which is actually an issue in locationHelper assumptions.
We say about rectangles:

> By convention, the right and bottom edges of the rectangle are normally considered exclusive.

Therefore, the top right, bottom left and bottom right angles of the rectangle contain either one or two exclusive coordinates.
Now, if we convert the location of the text to from one to another coordinate system and we're converting an exclusive coordinate, that coordinate falls outside the windows rectangle and therefore the window handle of the coordinate doesn't match.
@feerrenrut, would you like to assist with thinking here?

**Comment by lukaszgo1** [comment]
@leonardder I can confirm that issue in Tween is indeed fixed. Thanks for looking into  the NPP problem.

**Comment by leonardder** [comment]
@feerrenrut: would you be able to address my question in https://github.com/nvaccess/nvda/pull/11565#issuecomment-691226742 ? Thanks in advance!
I think it would be great to address these issues in 2021.1.

**Comment by feerrenrut** [comment]
Sorry for the delay @leonardder. I'm not quite sure I understand the question, could you clarify the situation for me.

My current interpretation of the question is that we end up comparing a "converted to exclusive coord" with a "not yet converted but based on the same object" resulting in a false negative for the comparison.

If I'm right about this interpretation, I think the solution from a design perspective is stronger typing. Detecting the types being compared and either automatically converting one of them or accommodating the difference.

**Comment by leonardder** [comment]
I have no intentions to bring this any forward. Closing as abandoned.

**Comment by leonardder** [comment]
I also reopened this one because I have some time to address potential review comments.

**Comment by LeonarddeR** [comment]
Never mind, abandoning it again. I'm sorry.

**Pull request closed without merging**
