### PR TITLE
Decouple contextHelp from the GUI module to avoid circular imports when installing add--ons

### LINKED ISSUE #11950: Crash on startup when installing add-ons importing gui at installTasks module level
### Steps to reproduce:

1. Install an add-on which imports gui in installTasks at the module level, such as [reportPasswords 1.0](https://github.com/nvdaes/reportPasswords/releases/download/1.0/reportPasswords-1.0.nvda-addon)
 
### Actual behavior:
NVDA crashes and a message is presented informing that NVDA needs to be running to install add-ons.

This maybe produced by a circular import related to gui.contextHelp, according to this [old issue](https://github.com/nvaccess/nvda/issues/4496). It seems to be fixed following the suggestion provided there by @jcsteh , that is, importing gui at the onInstall() method level. 

### Expected behavior:
NVDA should be restarted without crashing.
#### NVDA installed/portable/running from source:
Installed
#### NVDA version:
2020.4beta1
#### Windows version:
10
#### Name and version of other software in use when reproducing the issue:
n/a
#### Other information about your system:
n/a
#### Does the issue still occur after restarting your computer?
Yes.
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
Yes. In previous versions NVDA is restarted without crashing.
#### If addons are disabled, is your problem still occuring?
Yes.
#### Did you try to run the COM registry fixing tool in NVDA menu / tools?
Yes.

### PR DESCRIPTION
**Pull request by lukaszgo1**
This is opened against beta, since this PR fixes regression introduced during 2020.4 dev cycle

### Link to issue number:
Fixes #11950 
### Summary of the issue:
When installing add-ons which imported gui in their InstallTasks module NVDA failed to restart properly. This was caused by the fact that when gui was imported it also imported contextHelp.ContextHelpMixin and contextHelp in turn also imports gui causing circular import.

### Description of how this pull request fixes the issue:
I've decoupled gui from the ContextHelp. Specific changes:
- All places which were previously using gui.ContextHelpMixin are now using it from gui.contextHelp.ContextHelpMixin and main gui module no longer imports ContextHelpMixin at all. This necessitated moving UsageStatsDialog,, LauncherDialog, and WelcomeDialog to a separate file in the gui package.
- gui.contextHelp no longer needs to import gui to do that it has been necessary to move getDocFilePath to a separate `documentationUtils` module - to preserve backwards compatibility it is imported into the main gui module.
### Testing performed:
- Tried installing problematic add-on package from #11950 - installation succeeded both when installing it to a clean config and when upgrading with it - without this fix NVDA failed to start when upgrading. 
- Ensured that WelcomeDialog and LauncherDialog still works correctly.
- Ensured that context help can still be invoked with f1 in NVDA's settings dialog
- Ensured that user guide can be opened from the help menu.

### Known issues with pull request:
Since this is a large change it would be great to merge it into beta as soon as possible to give it plenty of testing.

### Change log entry:
None needed - this regression is not in a release yet.

### CODE REVIEW

**Comment by lukaszgo1** [comment]
I've no idea why AppVeyor fails to report status for this one - when looking at it on AppVeyor's website build is successful.

**Comment by lukaszgo1** [comment]
cc @michaelDCurran @feerrenrut

**Review by feerrenrut — CHANGES_REQUESTED** [review]
I think it would be good to move the classes out of `gui/__init__` however, is it necessary for this PR? It looks like the import cycle is broken by moving `getDocFilePath` out of gui, and dynamically importing it in `contextHelp` (no longer importing `gui`)

Moving the classes (and not importing them back to expose them as `gui.X`) is technically an API break. This isn't a problem for `getDocFilePath` because it is imported back into Gui. That said, it probably isn't necessary to move that either?

**Comment by lukaszgo1** [comment]
@feerrenrut wrote:

> I think it would be good to move the classes out of `gui/__init__` however, is it necessary for this PR? It looks like the import cycle is broken by moving `getDocFilePath` out of gui, and dynamically importing it in `contextHelp` (no longer importing `gui`)

It unfortunately is since `contextHelp` imports `ui` which in turns imports `gui` again causing circular imports.

> 
> Moving the classes (and not importing them back to expose them as `gui.X`) is technically an API break.

I don't think any add-on should modify these classes. If you're really worried about  This I can define a module level `__getattr__` which would lazily import them if needed.

**Comment by feerrenrut** [comment]
I have created an alternative approach which I think resolves the issue. Would you please take a look? https://github.com/nvaccess/nvda/pull/11958

**Comment by feerrenrut** [comment]
Since #11958 has been merged I will close this. As I said before, I'd be happy for the various `gui` classes to be reorganised in the 2021.1 release.

**Pull request closed without merging**
