### PR TITLE
Theoretical: code edits required to upgrade to Python 3.6/3.7

### PR DESCRIPTION
**Pull request by josephsl**
### Link to issue number:
#7105

### Summary of the issue:
Code edits required to upgrade to Python 3.6/3.7 (theoretical PR, should not be merged).

### Description of how this pull request fixes the issue:
This theoretical pull request provides code edits required to upgrade to Python 3.6/3.7. As this is strictly text and meant to stir discussions and further edits and testing from the community, this PR should not be merged.

Before #7105 can be incubated or considered for review, several dependencies must be satisfied:

* wxPython: version 4.0.0 (phoenix) official version and the corresponding NVDA PR must be included.
* Six module must be included, as wxPython 4 and other dependencies requires this module.
* Extensive testing and edits must be done.

### Testing performed:
Attempting to run Python 3 version of NVDA with mixed success.

### Known issues with pull request:
NVDA may not start when you try to use it on Python 3.6 due to old code in use. You should not run this PR code, or if you do, please provide commits that'll fix these issues.

### Change log entry:
Many things must be edited.

### CODE REVIEW

**Comment by josephsl** [comment]
Hi,

Note that this is a theoretical pull request, meant to gauge initial reaction before proceeding. Edits are welcome (and if you do have a PR for this pull request, please do it against my repo at github.com/josephsl/nvda under py3000 branch). Also, a related branch named py3wx4 is available to let you preview the actual GUI code required to transition to Python 3 and wxPython 4.

Thanks.

**Comment by josephsl** [comment]
Hi,

One more thing I forgot to add: this PR will be closed once the actual Python 3 work begins. Thanks.

**Comment by leonardder** [comment]
[**@josephsl**](https://github.com/josephsl) commented on [24 dec. 2017 20:08 CET](https://github.com/nvaccess/nvda/pull/7876#issuecomment-353799169 "2017-12-24T19:08:31Z - Replied by Github Reply Comments"):
> One more thing I forgot to add: this PR will be closed once the actual Python 3 work begins. Thanks.

I'm afraid I don't follow this. Isn't this pr supposed to be merged into the eventual py3 work?

**Comment by josephsl** [comment]
Hi, no, because this PR is meant to let folks see the current state of Python 3 edits required. Thanks.

**Comment by josephsl** [comment]
Hi,

July 2018 updates:

1. This PR will remain open for a while.
2. wxPython 4.0.3 is used, so this dependency is satisfied (seethe issue about py2exe regarding incompatible versions).
3. Ideas from this pR will be split into multiple issue/PR pairs for ease of reviewing code edits.

Thanks.

**Comment by beqabeqa473** [comment]
what do you thing about moving to pyinstaller which supports python 3?

2018-07-20 6:01 GMT+04:00, Joseph Lee <notifications@github.com>:
> Hi,
>
> July 2018 updates:
>
> 1. This PR will remain open for a while.
> 2. wxPython 4.0.3 is used, so this dependency is satisfied (seethe issue
> about py2exe regarding incompatible versions).
> 3. Ideas from this pR will be split into multiple issue/PR pairs for ease of
> reviewing code edits.
>
> Thanks.
>
> --
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/nvaccess/nvda/pull/7876#issuecomment-406466507


-- 
with best regards beqa

**Comment by josephsl** [comment]
Hi,

Updates:

1. This theoretical pull request will be replaced by the real one in the next few days. Thus, I'm closing this one for now.
2. For folks looking out for branches and snapshots, please keep an eye on Project Threshold.
3. The real pull request will use native Python 3 functionality, modules, and assumptions (trying to minimize use of six module as much as possible, too).

Thanks.

**Pull request closed without merging**
