### PR TITLE
Fix math not being read in Chromium-based browsers (#17421)

### LINKED ISSUE #17421: NVDA cannot navigate math content in Chromium
This is most likely a Chromium regression, but it's not known which version introduced it, I hope the community can provide more information, in the meantime, I will report to chromium.

### Steps to reproduce:
1 Open the following Wikipedia page: https://en.wikipedia.org/wiki/Quadratic_equation
2. Use NVDA to locate the mathematical content on the page. You can use Single Letter Navigation commands.
3. Press the space key on the math content to try to interact with it
4. Try pressing the left/right arrow to find math content.
### Actual behavior:
Try step 3: Unable to enter interactive mode.
Try step 4: You can't find the math object.

p.s. Using object navigation (NVDA+numpad4/6) you can navigate to the mathematical content. but can't interact with it### Expected behavior:

#### NVDA installed/portable/running from source:
Installed
#### NVDA version:
2024.4.1,Alpha snapshot 
#### Windows version:
Windows 10 22H2 (AMD64) build 19045.5131
#### Name and version of other software in use when reproducing the issue:
Chrome 131.0.6778.86
#### Other information about your system:
None
#### Does the issue still occur after restarting your computer?
Yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
This can be reproduced in 2024.1, 2024.2 and 2024.3

#### If NVDA add-ons are disabled, is your problem still occurring?
Yes
#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
Yes

### PR DESCRIPTION
**Pull request by NSoiffer**
Fix math not being read in Chromium-based browsers. Chromium made a change that causes a call to (correctly) return E_NOTIMPL.

This simple fix catches the exception and moves on. The NVDA behavior should be the same as before the Chromium change. Only E_NOTIMPL is caught, other COMErrors are re-raised.

Fixes #17421.

_This fixes a very serious user-issue. I recommend that a 2024.4.2 build happen with this fix if possible._

### Link to issue number:
Fixes #17421

### Summary of the issue:
Chromium-browsers were changed to return E_NOTIMPL and broke speech and braille of _all_ math equations (i.e., no speech or braille for math) in those browsers because NVDA passes along a 'not implemented' COM exception.

### Description of user facing changes
This restores the behavior of NVDA (i.e., math reads) as before the change.

### Description of development approach
A try/except block is added around the call. If the error is E_NOTIMPL, the code moves on as before. Otherwise, the error is re-raised as before.

### Testing strategy:
Make sure that some math addon is present. I tested with MathCAT, but any math addon will do. Go to any page with math (e.g., https://en.wikipedia.org/wiki/Quadratic_equation). Navigate to a math expression. Without the change, you will not hear any math. With the change, you will hear the math expression being read.

### Known issues with pull request:
None.

### Code Review Checklist:

I did _not_ make a change log entry because I don't know what version this change will go into.  I think a simple entry like
> Restore reading of math in Chromium-based browsers (Chrome/Edge/...) by handling a change they made.

- [x] Documentation:
  - Change log entry
  - User Documentation
  - Developer / Technical Documentation
  - Context sensitive help for GUI changes
- [x] Testing:
  - Unit tests
  - System (end to end) tests
  - Manual testing
- [x] UX of all users considered:
  - Speech
  - Braille
  - Low Vision
  - Different web browsers
  - Localization in other languages / culture than English
- [x] API is compatible with existing add-ons.
- [x] Security precautions taken.

@coderabbitai summary

### CODE REVIEW

**Comment by CyrilleB79** [comment]
The issue is quite serious. Though, it seems that it is fixed (at least temporarily) in Chrome 133. The question is When should Chrome 133 stable be released? An NVDA 2024.4.2 only makes sense if Chrome 133 stable release is not planned so soon.

**Comment by NSoiffer** [comment]
Maybe someone from the chrome team can comment. I just got an update and it is 131. I suspect (but again, some from Chrome should verify) that the fix needs to make it from alpha, to beta, to release and each step is about four weeks. So that puts it two months out if I am correct.

**Comment by cary-rowen** [comment]
Please wait and test 132.0.6834.40
In addition, according to the [comment of cc @michaelDCurran](https://github.com/nvaccess/nvda/issues/17421#issuecomment-2518826887), NV Access may have other improvement plans, please confirm.

**Comment by seanbudd** [comment]
@NSoiffer - [please ensure NV Access can push to your fork's branch when making a contribution](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/about-permissions-and-visibility-of-forks#about-permissions-of-forks). I'm not sure this is possible using master as your base branch for this PR. By default, NV Access should be able to push to forks, so something is going wrong here.

This PR needs to be rebased to RC, and a changelog entry added. I've pushed what this should look like here: https://github.com/nvaccess/nvda/compare/rc...fix17528?expand=1

**Comment by CyrilleB79** [comment]
@NSoiffer this branch should be rebased onto `rc`, should not be based anymore onto `master`.

**Comment by NSoiffer** [comment]
@seanbudd: I wasn't aware that pushes from a master branch causes a problem. I created #17548 from a non-master branch.  One of these should be closed.

I'll deal with the 2024.4 rebase. Hopefully I'll get it right. Thanks for head start.

**Comment by NSoiffer** [comment]
Are changes to the "rc" branch brought forward into master at some point or do there need to be specific commits to both rc and master?

**Comment by CyrilleB79** [comment]
Changes in the rc branch are back merged to beta branch and beta branch is back merged in the master branch. So you to care of master branch when rebasing to rc.

**Comment by josephsl** [comment]
Hi, I advise staring over from scratch by: checkout rc branch, createa new branch form that, do the work, commit changes, push to your GitHub repo, then create a pull request with nvaccess/rc as base. This is because master and rc branches have diverged and master branch content contains code marked as API breaking (and we don’t want to see that happening in 2024.4.2). Thanks.

**Comment by seanbudd** [comment]
Closing in favour of #17548

**Pull request closed without merging**
