### PR TITLE
Don't leave focus mode if focused on a grid cell and user presses escape

### LINKED ISSUE #12413: NVDA is not passing the Escape key in ARIA grids
This is almost exactly the same issue as https://github.com/nvaccess/nvda/issues/3215, but for grid cells instead of menu items.

Per the authoring practice for grids with widgets in each cell https://www.w3.org/TR/wai-aria-practices/#gridNav_inside, one of the common keyboard convention is to use the escape key to restore grid navigation while the focus in on a widget inside one of the cells. 

However, when user press escape in such situation, NVDA instead switches to browse mode. This causes confusion, especially since there are also no messages announced to the user about this switch or any instructions on how to switch back.

### PR DESCRIPTION
**Pull request by ctoth**
### Link to issue number:
Fixes #12413

### Summary of the issue:

See the link to the issue.

### Description of how this pull request fixes the issue:

By adding the grid cell to the existing set of controls that don't process escape outside browse mode.

### Testing strategy:

See https://www.w3.org/TR/wai-aria-practices-1.1/examples/grid/dataGrids.html
Enter the grid, arrow around, hit escape, ensure that NVDA doesn't switch back to browse mode.

### Change log entries:
Bug fixes
In ARIA data grid cells on the web, the Escape key will now be passed through to the grid and no longer turn off focus mode unconditionally. (#12413)

### Code Review Checklist:

- [x] Pull Request description is up to date.
- [ ] Unit tests.
- [ ] System (end to end) tests.
- [x] Manual testing.
- [x] User Documentation.
- [x] Change log entry.
- [x] Context sensitive help for GUI changes.
- [x] UX of all users considered:
  - Speech 
  - Braille
  - Low Vision
  - Different web browsers

### CODE REVIEW

**Comment by codeofdusk** [comment]
Please fill in the PR template. Thanks.

**Comment by ctoth** [comment]
@codeofdusk  Done!

**Review by seanbudd — APPROVED** [review]
Sorry @ctoth - this fell of my radar as I waited for any dissent on this change. Could you merge in master, resolve the conflicts, and move the changelog entry up, so I can merge this?

**Comment by ctoth** [comment]
I was attempting to help close some of the massive backlog of issues here. If each PR is going to take months to close, this task seems far less useful and I’ll take my efforts elsewhere. I don’t really wanna play the constant re-merging game.If you want to create a process that depends on getting people to sign off on a PR, please set a timeout for this process to avoid this problem in future.

**Pull request merged**
