### PR TITLE
Enhanced readability of script_moveMouseToNavigatorObject

### PR DESCRIPTION
**Pull request by nvdaes**

### CODE REVIEW

**Comment by josephsl** [comment]
Hi,

Looks fine to me - no visible user impact.

One thing though: as part of this merge (although @derekriemer can do this later), would you like to update the copyright year and add your name to authors list? Also, please let us know if you find other parts of the source code that could benefit from readability improvements.

Thanks.

**Comment by nvdaes** [comment]
Hi, my name is added in the copyright of addonHandler (see #2634) and 
also in the contributors.txt file.
I suppose this change is very very small to add my name again.
Cheers.

**Comment by nvdaes** [comment]
Sorry, I wanted to say #2694.

**Review by feerrenrut — APPROVED** [review]
Generally we would prefer not to see code churn like this. However, in this case we will incubate it.

**Comment by nvdaes** [comment]
OK.

**Pull request merged**
