### PR TITLE
Introduce support for Windows 10 Version 2004 (May 2020 Update/build 19041)

### PR DESCRIPTION
**Pull request by josephsl**
### Link to issue number:
None

### Summary of the issue:
Introduce support for Windows 10 Version 2004 (build 19041).

### Description of how this pull request fixes the issue:
In isWin10 function/map, recognize build 19041 as Version 2004, along with updating COM interfaces/UIA module to 10.0.19041, which introduces AnnotationTypeSensitive (60024). Also updated readme to point to Windows SDK version 10.0.19041.

### Testing performed:
Tested with source copy of NVDA running on Windows 10 build 19041.172.

### Known issues with pull request:
None

### Change log entry:
None needed.

### Special commit message and 2020.2 inclusion:
The commit message may need to mention "May 2020 Update". As for 2020.2, although this change is minimal, it is consistent with Windows 10 release updates and how NVDA responded to these in the past (take October 2018 Update and changes such as dialog reading, which was included in a 2018.x release).

Thanks.

### CODE REVIEW

**Comment by josephsl** [comment]
Hi,

COM interfaces/UIA module will not be updated, as doing so causes hundreds of Flake8 issues to show up, as this Python module isn't generated by NVDA but rather by comtypes.client.

Thanks.

**Comment by codeofdusk** [comment]
> Once release date and marketing name for 20H1 comes out, the commit message should mention both (along with build number).

Is the marketing name for 21H1 not 2004? I thought 21H1 was the codename...

**Comment by josephsl** [comment]
Hi,

Nope - Microsoft usually releases a separate marketing name that will be used to advertise the new feature update to the public.

In short, Version 2004 is known by different names depending on who you ask when:

* Vibranium: internal codename for Microsoft Azure release that powers internals of Version 2004. In late 2019, in preparation for Version 2004 RTM, vb_rlease branch was forked from rs_prerelease branch, and Vibranium was finalized in December 2019. The bits the Azure team have been working on became a significant part of Version 2004, as internal release schedule between Windows and Azure are synchronized. Internally, Microsoft Azure team uses chemical element names for codenames. Version 1903 was internally codenamed Vanadium by Azure team, the next element is Chromium, but it became the codebase for Edge 79 and later. The next release (likely 20H2 or 21H1) is internally codenamed "Manganese" by Azure team.
* 20H1: this is the codename used by Windows Insider Program participants to denote early builds of the next feature update, and is the codename that is widely used to refer to Version 2004 until the next hing happened.
* 2004: what we call "2004" is actually a release ID - it isn't called 2003 because Windows server 2003 already took that name, hence 2004 became the release ID.
* A marketing name: eventually Microsoft will reveal a public marketing name to refer to Version 2004. The most likely marketing name is "May 2020 Update" unless Microsoft releases build 19041 to release preview ring Insiders and to the public in April, in which case Microsoft may call it "April 2020 Update".

Whenever I talk about Windows Insider features, I usually follow Windows Insider codename (20H1) or the build where a feature made its debut or a change was made. Once the releae ID is revealed will I start using YYMM.

Hope this clarifies a lot.

**Comment by josephsl** [comment]
Possibly blocked by #10964 to avoid possible conflicts.

**Comment by codeofdusk** [comment]
How so? This PR is presumably intended for 2020.2 where #10964 is intended for immediately after (2020.3).

**Comment by josephsl** [comment]
Hi, because of Windows 10 version map – this PR adds 2004 whereas #10964 adds 2103. Also, this PR will not be ready for review until Version 2004 goes out to semi-annual channel (SAC). Thanks.

**Comment by josephsl** [comment]
Hi,

Update: sources say Version 2004 will be released in late May. Nevertheless, I'll make it an official PR as soon as Windows 10 SDK build 19041 is released to everyone (not just Insiders), as that's the one remaining thing to be done (documenting it).

Thanks.

**Comment by josephsl** [comment]
Hi,

And now, ready for official pull request review.

Thanks.

**Comment by leonardder** [comment]
I think this deserves a place in 2020.2.

**Comment by codeofdusk** [comment]
Cc @feerrenrut @michaelDCurran

**Comment by dingpengyu** [comment]
hi @josephsl 
Appveyor's visual studio2019 mirror has been updated
[Visual Studio 2019 image update on May 29, 2020](https://www.appveyor.com/updates/2020/05/29/)
What’s new
Windows 10 SDK/WDK, version 2004 (10.0.19041.0)
thanks

**Comment by feerrenrut** [comment]
@josephsl (or others) could you update the description with why you feel this is important to include in 2020.2? What does this give us?

**Comment by josephsl** [comment]
Hi,

Done. Thanks.

**Review by feerrenrut — APPROVED** [review]

**Pull request merged**
