### PR TITLE
Update issue templates

### LINKED ISSUE #8494: Add an issue template for feature requests
### Steps to reproduce:
1. Create a new issue at
https://github.com/nvaccess/nvda
2. Try to suggest a new feature.
### Actual behavior:

A template designed for reporting bugs is shown.

### Expected behavior:

A template designed for requesting a new feature should be shown.
Fields like example/s of use cases, suggestions about design and others could be included.
An example of this can be found at:
https://github.com/nvdaes/emoticons/
More info:
https://help.github.com/articles/creating-issue-templates-for-your-repository/

### PR DESCRIPTION
**Pull request by feerrenrut**
Closes #8494 
Update github issue templates so that feature requests can be provided.

This keeps the bug report issue template the same, and creates a feature request issue template. I am using the suggested headings given by Github. Once we are happy with this PR I suggest that we create a new wiki page to explain the feature request template (and change the existing ones title). The new wiki page could include the following text:

# New Feature request template
This page is meant to serve as an explanation for how to fill out our feature request Github issue template.

The template uses github markdown, to provide formatting for headings, lists, quotes etc. If you are not familiar, please take some time to learn about Github markdown

Warning: In all but exceptional circumstances we require this template to be completed. Your issue will likely be closed if this template has not been followed. However, please feel free to add more headings if you feel it provides more clarity into your request.

## Tips
* Consider swapping to the preview tab in order to read through your issue at any stage to confirm the issue reads as expected.
* If you have trouble following this template, or with the initial investigation that is required, please politely ask for assistance from the fantastic community of people on the NVDA users mailing list

## The template
The following headings match those that are found in the template, with a short description of how to fill in each section.

### Is your feature request related to a problem? Please describe.
This section should provide a clear and concise description of what the problem is. Ex. I'm always frustrated when [...]

### Describe the solution you'd like
A clear and concise description of what you want to happen. If you can provide technical details about how to address the problem, please do so. Feel free to add a subheading.

### Additional context
Add any other context for the feature request here. This might be the other applications and their versions that the feature is expected to work with (EG Firefox or Microsoft Word). Also consider whether you can upload an attachment document that will help to serve as a test case for the feature.

### CODE REVIEW

**Comment by nvdaes** [comment]
Thanks for addressing this. For me you can merge this like that, or may remove the context section for simplicity (this can be explained just in previous sections or ommited).

**Comment by DrSooom** [comment]
> Is your feature request related to a problem? Please describe.
This is quite similar to STR and the actual behaviour. If there is an existing problem, the issue template would be the right place for it – in most cases.
> Describe the solution you'd like
And this one is similar to expected behaviour. So I would rename both to them.
> Additional context
This isn't really clear. Maybe the wiki article will help here out.

And please replace the bold markdown code with headlines level 3. Then it would be similar to the issue template. Thanks.

**Comment by leonardder** [comment]
It might be good to have additional headings in the feature request template for that urges one to provide possible technical details or known limitations in the suggested approach.

**Comment by feerrenrut** [comment]
> It might be good to have additional headings in the feature request template for that urges one to provide possible technical details or known limitations in the suggested approach.

I'll certainly add this to the wiki page, it's always ok to add more details. I'd prefer feature requests first focus on the problem to be solved, rather then jumping straight to the solution. There may be several ways to approach it, or similar problems that could be addressed with a more general solution. Getting deep on the solution can close peoples minds to alternative approaches.

**Comment by DrSooom** [comment]
@feerrenrut: Could you please correct the following typo ("installed" instead of "Installed") in the template and in the wiki article too?
> NVDA Installed/portable/running from source:

And deleting the blank lines between the 3rd and 4th level headlines in the bug template might be helpful too – as they aren't necessary here. Thanks.

Ah, and one more suggestion to the wiki article in the section "Other information about your system:". Maybe it would be helpful in some circumstances to add the current synthesizer and the current braille display in the example quotation.

**Comment by feerrenrut** [comment]
There will be quite a bit of duplicated information if there is one wiki page for each template. Instead, I will put the information on one page with links to each template explanation at the start.

**Review by michaelDCurran — APPROVED** [review]

**Comment by DrSooom** [comment]
I already thought that this will happen. More and more unfamiliar users are using no template instead of the bug report template to report a bug. We should keep an eye on it. If this behaviour doesn't change in the upcoming weeks/months, we should delete the feature request template, so that the bug report template will always be shown when creating a new issue.

**Comment by feerrenrut** [comment]
> we should delete the feature request template

It looks like we can have a default template that shows when visiting `/issues/new`. I think this would be a better pathway. This is achieved by placing a file at '.github/ISSUE_TEMPLATE.md`.

The next question is, what should this contain. I would prefer to link to the `/issues/new/choose/` URL.

**Comment by feerrenrut** [comment]
I have added a default template, the main body is the bug report. It has a note at the top mentioning that the /issues/choose/ URL should be used. See https://github.com/nvaccess/nvda/issues/new/

**Comment by DrSooom** [comment]
A simple link to the feature request template within the comment section should be enough as l
long as the default template is exactly the same like the bug report one.

So remove the new added introduction and add the following:
> `>!--`
`Please visit https://github.com/nvaccess/nvda/issues/new?template=f.md if you want to submit a feature request.`
`[Old text] Please thoroughly read …`

You can also rename the two .md files to "br.md" and "fr.md" or just "b.md" and "f.md". The shorter the better. And it's easier to copy the link directly from the text field instead of switching to the preview mode first.

**Comment by leonardder** [comment]
> The shorter the better.

But also, the shorter the more unclear. I think the names are good as they are and the introduction is fine as it is.

**Comment by DrSooom** [comment]
@leonardder: The new introduction isn't good at all, because there are also users out there who don't delete the introduction text. So the new introduction would be visible at all new issues. That's why we added the HTML comment section, which needn't to be deleted by the user.

**Comment by feerrenrut** [comment]
If we start getting many issues created with that text left in them, we will reassess the situation. I expect that those who are regular's to github will either bookmark the direct links, or the "/choose" link and no longer use the "/new" link. For those who are not, and somehow end up on the "/new" link, it's not so friendly to have a handful of markup symbols as the first thing presented, hopefully they read it and follow the redirect.

**Comment by DrSooom** [comment]
> Have you tried any other versions of NVDA?
» Have you tried any other versions of NVDA? If so, please report their behaviors too.

On some issues, only the NVDA versions are listed, but it isn't clear, if the described issue already occurred in these versions too. So please expand the Bug Report and the default issue draft with this little additional sentence. Hopefully it helps. Thanks.

**Comment by feerrenrut** [comment]
> On some issues, only the NVDA versions are listed, but it isn't clear, if the described issue already occurred in these versions too.

I have added the suggested sentence, thanks for making the suggestion.

**Pull request merged**
