### PR TITLE
Touch gestures: add right mouse click (tap and hold) command

### LINKED ISSUE #3886: Emulate mouse on touch screens
**Reported by k_kolev1985 on 2014-02-14 13:53**
At present, on a touch screen, NVDA can interact with things on the screen only via object navigation. If an object is well designed, it is OK. But if not - problems arise. For example, if an object has no default action assigned, there is no way (at least as far as I know) to interact with it, only via the touch screen - NVDA will say "no action" and nothing will happen. For other cases in witch object exploring fails when working only with a touch screen, see tickets #3779 and #3780. To read text on a touch screen with gestures, there is the so called "text mode", To switch between those 2 modes (text and objects), the user must tap with 3 fingers on the touch screen.

So, to improve the touch screen experience with NVDA, I suggest that a third mode of screen exploration is added to NVDA. The mode will emulate the mouse cursor. When this new mode is activated and the user explores the screen with his finger, NVDA will behave as if the mouse cursor is following the user's finger and NVDA will read things on the screen as if the user is moving the mouse cursor on the screen with "mouse tracking" enabled. Gestures for performing various actions with the mouse buttons must be added, but I think that at least some of them (eg. left single click, right single click, mouse buttons lock) are already available and only gestures for those actions must be assigned. Also, gestures for left double click, middle button single click and wheel scrolling must also be added.

I don't know however if my suggestion of mouse emulation is even possible to implement, but I wont know until I ask - don't I (?) :).

### PR DESCRIPTION
**Pull request by josephsl**
Hi,

Another pull request that was buried for a very long time, now resurrected:

### Link to issue number:
Fixes #3886 

### Summary of the issue:
There is no mouse commands for touch users.

### Description of how this pull request fixes the issue:
Adds a right mouse click command for touch users: tap and hold.

### Testing performed:
Tested as part of Enhanced Touch Gestures add-on.

### Known issues with pull request:
None

### Change log entry:
New features:

You can now perform right mouse clicks on touch devices by doing a one finger tap and hold. (#3886)

### CODE REVIEW

**Comment by josephsl** [comment]
Hi,

Also, if you can: @LeonardDer and @michaelDCurran 

Thanks.

**Comment by josephsl** [comment]
Hi,

As for improving review activate script to do a left mouse click: I think it should be a separate pull request, because the discussion we had five years ago may need some tweaking, as well as allowing all input mechanisms (keyboard, mouse, braille, touch, etc.) to take advantage of solutions proposed in #3886 in one sweep.

Thanks.

**Comment by XLTechie** [comment]
There is an issue of terminology here.

By "tap and hold", is this what apple calls a "double tap and hold"? In other 
words: tap with one finger, lift the finger, put it down again, and leave it 
there the second time?
So that your finger actually "taps" the screen twice, with the second being 
rather longer than the first?

Or is it truly a tap and hold (single tap and hold): lower the finger once, and 
leave it there?

I can't imagine it's the latter, since that would be indistinguishable from a 
location adjust gesture.

**Comment by josephsl** [comment]
Hi, yes, the former is what NVDA uses as well. Thanks.

**Comment by josephsl** [comment]
Hi,

I think it is ready for another round of reviews and comments, now that 2019.3 has been released.

Thanks.

**Review by michaelDCurran — APPROVED** [review]

**Comment by Adriani90** [comment]
@josephsl please don't forget to add the coresponding touch gesture into the user guide, section 5.7. Thanks.

**Comment by josephsl** [comment]
Hi, I thought I did, but it looks like I may have not. Thanks.

**Pull request merged**
