### PR TITLE
Fix auto-tether after moving mouse and using review_currentLine, Revi…

### PR DESCRIPTION
**Pull request by rob-aph**
…ew_currentWord, and review_currentCharacter

### Change log entries:
New features
Changes
Bug fixes
For Developers

### Code Review Checklist:

- [ ] Pull Request description:
  - description is up to date
  - change log entries
- [ ] Testing:
  - Unit tests
  - System (end to end) tests
  - Manual testing
- [ ] API is compatible with existing add-ons.
- [ ] Documentation:
  - User Documentation
  - Developer / Technical Documentation
  - Context sensitive help for GUI changes
- [ ] UX of all users considered:
  - Speech 
  - Braille
  - Low Vision
  - Different web browsers
  - Localization in other languages / culture than English

### CODE REVIEW

**Comment by josephsl** [comment]
Hi, could you mind “adding” more ingredients to the salad please i.e. fill out the PR template? Thanks.

**Comment by rob-aph** [comment]
I see no way to update the template after accidental creation of this pr. How do I start over? Do I just close this and start over with a new branch? Or, can I close this and use the same branch?

**Comment by seanbudd** [comment]
@rob-aph you should be able to edit your PR text

**Comment by CyrilleB79** [comment]
For more detailed information on how to edit your PR's initial description:
* Find the first title of level 3 on the page, which is the title of the first comment, i.e. the initial description
* Press up arrow once to go on the button "Show options" and press it
* Go through the menu that has just opened; you will find an item to edit your comment.

**Pull request closed without merging**
