### PR TITLE
Composable Shell touch keyboard: support emoji panel and other features in Windows 10 Fall Creators Update and later. re #7273

### LINKED ISSUE #7273: support the new emoji panel in windows 10
### Steps to reproduce:
In windows 10 windows insider build 16215 Microsoft introduced the Emoji panel. 
1. focus on any text field and then press the windows key + ; or + . 
2. the emoji panel appears. 
### Expected behavior:
NVDA doesn't speak anything, and moving with the right and left keys moves between Emojies but NVDA doesn't read any of them. if you press enter the emoji would get entered as expected and announced.
### Actual behavior:
NVDA doesn't tell us that the panel has opned nor does it read when moving between items. Note that Narrator reads those fine as expected.
### System configuration:
NVDA version:
NVDA Version: next-14106,059e7f02

NVDA Installed or portable:
installed

Other information:
none needed

Windows version:
Windows Version 1703 (OS Build 16215.1000)

the other questions in the template don't apply here.

### PR DESCRIPTION
**Pull request by josephsl**
Hi,

Revision: revised in July 2018 to base it on the template.

### Link to issue number:
Fixes #7273

### Summary of the issue:
Support modern keyboard features, including emoji panel, hardware input suggestions, dictation, and cloud clipboard.

### Description of how this pull request fixes the issue:
Adds an app module for Composable Shell keyboard. This overlay app provides the following features:

### Testing performed:
Searching for emojis, dictating text, cloud clipboard paste, entering text with hardware input suggestion turned on in various Windows 10 releases. Note that because it is an app module, it was tested with Windows 10 App Essentials add-on first.

### Known issues with pull request:
None, although features are subject to change.

### Change log entry:
Section: new features:
Added support for modern input features in recent Windows 10 releases. These include emoji panel (Fall Creators Update), dictation (Fall Creators Update), hardware keyboard input suggestions (April 2018 Update), and cloud clipboard (RS5).

### Technical details:

* The new XAML touch keyboard has its own app module.
* If one has United States English keyboard layout and is running build 16215 or later, one can press Windows+period or Windows+semicolon to search for and enter emojis. The keyboard layout requirement was relaxed in build 17134.
* One can also type emoji descriptions to find the exact emoji.
* Each emoji candidate raises element selected event when selected.
* In some cases, when the emoji panel first opens, the first emoji isn't announced because element selected event is not fired then, although window open event is fired.
* This app was later exte3nded to cover dictation (Windws+H), cloud clipboard and announcing hardware input suggestion candidates.

Thanks.

### CODE REVIEW

**Review by michaelDCurran — DISMISSED** [review]

**Comment by josephsl** [comment]
Hi,

Note that this app module also supports dictation, so we get that for free.

Thanks.

**Comment by josephsl** [comment]
Hi,

Hmmm, I don't know why, but when I was assigned, the review status was set to "review required" when in fact this was reviewed before.

Thanks.

**Comment by josephsl** [comment]
Hi,

Yet again, Microsoft has changed emoji panel in 17704, although in a subtle way: when browsing emoji, in addition to element selected event, name change event is fired by an ancestor control which displays selected emoji character and how many items there are in a category. Unfortunately, this element is the one that says things such as "emoji panel is closed", announces categories when browsing them in Redstone 5 and such. Also, name change is fired by emoji grid items when people/skin tone is selected.

Thanks.

**Comment by michaelDCurran** [comment]
It would be great if you could rewrite your pr description to follow the template. Also, can you provide some clear steps to reproduce in order to test the features? I think I understand how emoji input works, but I'm not sure how to test dictation.

**Comment by josephsl** [comment]
Hi,

To test dictation, you need a microphone and:

1. Opoen Notepad.
2. Press Windows+H to dictate something.

NVDA will then announce dictated text via name change event.

Thanks.

**Comment by michaelDCurran** [comment]
Sometimes I am seeing the following traceback when starting to type a search string into the emoji panel:
```
ERROR - eventHandler.executeEvent (17:32:57.532):
error executing event: UIA_elementSelected on <NVDAObjects.UIA.ListItem object at 0x03AC4C50> with extra args of {}
Traceback (most recent call last):
  File "eventHandler.py", line 152, in executeEvent
    _EventExecuter(eventName,obj,kwargs)
  File "eventHandler.py", line 92, in __init__
    self.next()
  File "eventHandler.py", line 100, in next
    return func(*args, **self.kwargs)
  File "appModules\windowsinternal_composableshell_experiences_textinput_inputapp.py", line 37, in event_UIA_elementSelected
    if obj.UIAElement.cachedClassName == "ListViewItem" and obj.parent.UIAElement.cachedAutomationID != "TEMPLATE_PART_ClipboardItemsList":
AttributeError: 'ContentGenericClient' object has no attribute 'UIAElement'
```
I think some extra checks for UIA are required.

**Review by michaelDCurran — APPROVED** [review]

**Pull request merged**
