### PR TITLE
Upgrade NVDA codebase to Python 3.7

### LINKED ISSUE #7105: Upgrade NVDA codebase to Python 3
Hi,

This issue serves as an umbrella issue for several related issues, one of them being #7077.

Python 3 introduces changes to syntax and inner workings of Python. Some of the changes include:

* Unicode strings.
* Use range function.
* _winreg -> winreg.
* threading.Barrier.
* collections.ChainMap.
* Reorganized standard library folder structure.
* Timer-based GIL instead of instruction count.
* Possibilities with asynchronous functions (async/await).
* Virtual environments.
* Built-in compatibility with Windows 10 (Python 3.5 or later).
* Losing Windows XP support (Python 3.5 and later).
* No more .pyo files.

Upgrading to Python 3 will require huge coordination, as NVDA developers, add-on writers, translators, users and others will need to adapt new attitudes, assumptions and so on. In terms of dependencies, the only thing left is SCons (wxPython is discussed in #7077).

Thanks.

### PR DESCRIPTION
**Pull request by josephsl**
Hi,

Note: the branch is based on master, but it might be possible to rebase this on threshold. This is a different kind of pull request, in that I would like to invite everyone to participate - comments, commits, reviews, and so on.

### Link to issue number:
Fixes #7105

Note: issues that are fixed by this pull request will be added as commits come in.

### Summary of the issue:
Upgrades NVDA source code to Python 3, specifically, to Python 3.7.

### Description of how this pull request fixes the issue:
Various issues were identified and fixed, including xrange vs. range, use of Python 3 module names for imports, dictionary iteration and key access (has_key vs key in dict) and others. Note that Python 3 work involves more than source code - see the linked issue for details.

### Testing performed:
Source code level testing done since September 2018.

### Known issues with pull request:
Dependencies will need to be edited and/or satisfied, some unforeseen errors. Note that these will be rectified as pull request writing progresses.

### Change log entry:
Changes for developers:
* NVDA source code has been upgraded to Python 3.7. (#7105)

And so many things to write.

### Additional notes:
A while ago there was a theoretical pull request meant to test viability of Python 3 transition, which was based on a combination of Python 2 and 3 syntax, semantics, and assumptions. This is the real pull request that will use Python 3 native syntax, semantics, and assumptions. In short, I am donating the work done over the last few months to NV Access to help speed things up a bit.

Thanks.

### CODE REVIEW

**Comment by josephsl** [comment]
Hi,

Don't worry about failing tests - this is expected due to many differences. In order to resolve this, we need to move to Python 3 all the way - dependencies, scons, etc.

Thanks.

**Comment by leonardder** [comment]
The conversion from basestring to str and unicode to str worries me a bit. Of course it is perfectly valid, however, we can no longer distinguish between code that used str initially and str after the conversion, other than looking at the code without these commits. I'd rather suggest to revert these commits, then look at every current use of str and change that into bytes if needed. Then, you can apply the conversion again.

**Comment by leonardder** [comment]
Also, please change the base branch to threshold

**Comment by feerrenrut** [comment]
Joseph, I haven't started looking at this code yet. But I imagine this process is uncovering lots of lessons on how this should be approached. I imagine the change set for the python 3 migration is going to be quite large, at least in terms of different areas of the code changed, if not the line count. This is going to make reviewing the code quite difficult. An alternative might be to review the process used (with explanations of why it should be done this way). 

To be honest, I'd be quite hesitant to merge in any large PR that "muddies the waters" when it comes to the state of the transition.

**Comment by josephsl** [comment]
Hi, I’ll look into changing the base today. Thanks.

**Comment by josephsl** [comment]
Hi,

Currently, I am doing the following:

1. Test changes with another copy of the repo with Python 3 source code and dependencies applied.
2. I'm actively avoiding speech module in case speech refactor introduces changes.
3. I'm adding source code comments for some changes that appear to be unclear at first in aiding with review (for example, language handler and others).
4. I'm grouping commits by syntax and semantic changes because they are scattered everywhere.

As for Leonard's request, I'll revert last night's commits on basestring/unicode/str/unichr/chr changes until we figure out how to proceed with this (see textUtils pull request for details).

Thanks.

**Comment by feerrenrut** [comment]
@josephsl Thanks for the comment on your process, this makes sense to me. Could you elaborate on how you test (step 1). Does this come down to running NVDA? Any particular actions you aim to take?

I think it is wise to adding source code comments for any change we are remotely uncertain about. string -> unicode string | bytes decisions are of particular concern. I would like these to be highlighted with a comment so we can have several people review those changes easily. We can remove the comments easily once we have gained confidence.

**Comment by josephsl** [comment]
Hi,

Hope the following answer is sufficient (let me know if it isn't): I have a personal repo/branch (josephsl/py3000) that has all the necessary source code changes applied, and a zipped copy of Python 3 version of NVDA that includes source code changes and dependencies in it (host on my personal website). The git log for py3000 is a mess of merges, rebases, and all sorts of edits, with i7105 branch (the one for this PR) being the real-life version of that repo.

As for passing in "-3" switch: source code, yes. Note that it won't check newer changes such as async/await, reintroduction of "u" prefix and what not, but for transition purposes, I concur with having this on.

Thanks.

**Comment by feerrenrut** [comment]
What is your process for testing that branch? It would be good to make sure we are all on the same page here.

Obviously getting NVDA running from source is a good start, though this doesn't provide full coverage. Not all files are imported / compiled.

1. We want to be able to ensure all files are compiled with python 3 to check for syntax errors.
1. We need focused (run time) testing over each of the areas changed to look for logic bugs. I expect this will be done manually rather than being automated, in case anyone is wondering.
1. For any uncertain changes (especially strings) these should be tagged with a comment and reviewed by several people. 
   - These reviews will require the reviewer to become familiar with the area in which the string is used, and determine enough about the context to make a call about whether it should be bytes / bytearray or unicode string.
   - I'd like to suggest the following process for these reviews:
      - Add a comment before any uncertain change with `# py3 review required.`
      - The reviewer should then add a comment "review required" comment to say what they think the line should be, even if it matches what it currently is.
        - This should be in the form `# py3 review: <code here>`
        - This will help us to quickly see whether this decision has been reviewed and by who (with `git blame` ) 
        - It tells us if we have agreement between reviewers or not
        - Adding a comment even when it matches, allows us to be certain that the line has not been changed after the review was made.
      - The reviewer should then create a commit with the message `py3 review` and push to the branch.
      - Generally, I'm not expecting broad changes to the context around these lines post review, if so we would have to remove the comments and ask for a re-review.

**Comment by josephsl** [comment]
Hi,

From time to time I used to generate a zipped snapshot of latest code edits and dependencies.

As for feature testing, I would test latest features from whatever the base branch is (master/threshold) in Python 3 mode.

As for generating Python 3 version of comtypes, I did it by running scons in Python 3.7 (note that sconstruct will also need to be edited). At least compilation works until t2t to HTML step, at which point Python will complain a lot about txt2tags (see the relevant ticket for more info).

Thanks.

**Comment by josephsl** [comment]
Hi,

As for source code comments: I will follow the ones proposed above with the added stipulation that issue numbers should be mentioned if appropriate. I won't work on this until #4877 is declared as functioning well because speech module will need some important edits (such as xrange to range and such).

Thanks.

**Comment by josephsl** [comment]
Hi,

All conflicting files have something to do with speech refactor, which is expected (except for settings dialogs I think).

Here's what might happen if people agree to this:

1. Resolve conflicts by using the contents of speech refactor instead of what I have at the moment.
2. For trivial conversion such as xrange to range, I will take care of it first.
3. For imports, I'll add a comment about it (prefixing it with "py3review:").
4. For harder cases such as Unicode conversion, comments will be added (see the above suggestion from Reef as to how it'll be written).

This pull request will focus mainly on source code edits with minor adjustments to sconstruct. The sconstruct work may become a separate PR provided that:

1. Python 3 port of py2exe is ready to go.
2. Txt2tags is ready to go.
3. In addition to me, at least two people must be willing to compile NVDA straight from Python 3 and report findings.

I'm not focusing on testing framework yet due to source code edits in progress. As for Appvayor status and source based tests, don't worry if they fail.

Comments are appreciated (once we get comments, I'll pick this up again this weekend).

Thanks.

**Comment by josephsl** [comment]
Hi all,

I would like to request assistance from the community in documenting transition issues directly in source code (so far, I covered add-on handler, API module, app module, braille display detector, and main config module); it isn't enough for one person to do this, hence this request for participation from the entire community (and an invitation to people outside our project to provide guidance for us, along with helping us with this huge marathon).

For comment writers:

1. Study the code carefully.
2. Write down the comments in the following format:

Issue number (Py3 review required): short explanation.
Py2: current code
Py3: suggestion

This is so that NV Access people and others can think about differences and take appropriate action when it is time to review this pull request and related ones. Please pay careful attention to #8661 - basestring vs str, Unicode, encoding/decoding and others - and do suggest workarounds to @leonardDer.

For reviewers:

1. As suggested by Reef, "Py3 review required" text has been added to comments for ease of review.
2. I have added both Python 2 and 3 code fragments for ease of comparing differences and also to leave room for additional suggestions.

Thanks.

**Comment by michaelDCurran** [comment]
This pr has been replaced by other smaller prs (some of which were cherry-picked from this pr). This pr has proven very useful in the conversion to Python3.

**Comment by josephsl** [comment]
Hi, your welcome – I can finally put this to rest – I’ll keep it alive in my fork for historical reasons. Thanks.

**Pull request closed without merging**
