### PR TITLE
Fix-up of 12814: Ensure that role label for landmark is once again abbreviated in braille

### LINKED ISSUE #13158: The word landmark is no longer abbreviated in braille
### Steps to reproduce:
1. Connect a braille display.
2. Go to www.nvaccess.org.
3. Ensure that browse mode is turned on.
3. Press Ctrl+Home.

### Actual behavior:
The braille display shows:
"landmark navi h1 lnk gra NV Access"

### Expected behavior:
The display shows:
"lmk navi h1 lnk gra NV Access"
That is, "landmark" should be "lmk", just as "navigation" is shortened to "navi".

#### NVDA installed/portable/running from source:
Installed

#### NVDA version:

2021.3

#### Windows version:
Windows 10 21H2 (10.0.19044) workstation

#### Name and version of other software in use when reproducing the issue:
Firefox 95.0

#### Other information about your system:
N/A

#### Does the issue still occur after restarting your computer?
Yes

#### Have you tried any other versions of NVDA? If so, please report their behaviors.
Yes, "lmk" is shown in 2021.2 and the release notes does not mention this change.

#### If NVDA add-ons are disabled, is your problem still occurring?
Yes

#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
Yes

### PR DESCRIPTION
**Pull request by lukaszgo1**
Opened against beta since this PR fixes regression introduced in 2021.3 development cycle and   including in a point release seems very low risk.

### Link to issue number:
Fixes #13158
### Summary of the issue:
PR #12814 replaced usages of deprecated `controlTypes.roleLabels` with `role.displayString`. However braille has its own mapping of roles to labels which should be used for abbreviations of roles for braille. The role label used for speech has been mistakenly used for a role of landmark.
### Description of how this pull request fixes the issue:
Once again uses braille abbreviation of landmark for landmarks.
### Testing strategy:
Performed STR from #13158 - made sure that 'lmk' is shown on a braille display for landmarks.
### Known issues with pull request:
None known
### Change log entries:
Bug fixes
`- Landmark is once again abbreviated in braille (#13158)`

### Code Review Checklist:

- [X] Pull Request description:
  - description is up to date
  - change log entries
- [X] Testing:
  - Unit tests
  - System (end to end) tests
  - Manual testing
- [X] API is compatible with existing add-ons.
- [X] Documentation:
  - User Documentation
  - Developer / Technical Documentation
  - Context sensitive help for GUI changes
- [X] UX of all users considered:
  - Speech 
  - Braille
  - Low Vision
  - Different web browsers
  - Localization in other languages / culture than English

### CODE REVIEW

**Comment by lukaszgo1** [comment]
cc @feerrenrut

**Review by feerrenrut — DISMISSED** [review]

**Comment by feerrenrut** [comment]
Please test and confirm this is fixed in the RC for 2021.3.1 https://www.nvaccess.org/post/nvda-2021-3-1rc1/

**Comment by feerrenrut** [comment]
Virus total results:
- Files scan: https://www.virustotal.com/gui/file/b27565f4835f815886b4bd31600d9843056888aba565d3033a80f13c005be0f1/detection
- URL scan: https://www.virustotal.com/gui/url/2cc7acdc1acf4812fd4d991171e1775075b550921c309a4cca26fd5a9e79f026/detection

**Comment by CyrilleB79** [comment]
RC is already available. Does it mean that the translated change log will not be included in 2021.3.1, i.e. all languages except English will not have any 2021.3.1 section in the change log?
Or 2021.3.1rc1 willl differ from 2021.3.1? (on the contrary to usual rc that are identical to final releases if no issue is found)
Thanks.

**Comment by lukaszgo1** [comment]
I can confirm the issue is fixed in 2021.3.1 RC1. Are you planning to merge RC to master?

**Comment by feerrenrut** [comment]
@CyrilleB79 Historically we haven't allowed translation updates into point releases, there is some risk that translation updates can break NVDA. Ideally we would allow updates ONLY to the changes files, we don't have that ability at this stage.

We prefer not to have a long RC period for point releases, just confirm that the addressed issues are fixed, and do the release.

We'll be discussing this internally to try to improve the process in the future, however this will likely rely on updates to our translation system.

**Comment by CyrilleB79** [comment]
OK @feerrenrut no problem.

It seemed to me that all the PRs for 2021.3.1 were opened and merged on top of beta branch, not rc.
And in https://github.com/nvaccess/nvda/pull/13154#issue-1076557047, you wrote:
> A point release is required to address #13153. This will require updates from translators, and confirmation from affected individuals that this issue is resolved.

That's why I have thought that the change log content would have been translated.

Anyway, everything is clarified now. I understand why new translations will not be integrated in 2021.3.1 and agree with this process. Thanks.
We will send the translated change log for 2021.3.1 by e-mail in local communities.

**Comment by feerrenrut** [comment]
Yes, that was the initial plan and so we merged the changes to beta. I cherry picked the changes into the RC branch to prevent any risk from updated translations and made the RC from there. Sorry for the confusion this caused.

**Pull request merged**
