### PR TITLE
Revert #8727 - built-ins, relative imports, importlib

### PR DESCRIPTION
**Pull request by josephsl**
### Link to issue number:
Various regressions from #8727.

### Summary of the issue:
Regressions such as inability to correctly load app modules for multibyte file names were observed.

### Description of how this pull request fixes the issue:
There are several pull requests meant to resolve regressions, but it was decided to revert changes and reserve them for Threshold/Python 3.

### Testing performed:
TBD (to be done via try builds).

### Known issues with pull request:
None so far.

### Change log entry:
None

### CODE REVIEW

**Comment by josephsl** [comment]
Hi,

Hmmm, when asking for a revert pull request on GitHub, it defaults to generating it from master. I'll forcefully replace this one with the one from beta branch.

Thanks.

**Comment by Brian1Gaff** [comment]
Lets hope that beta is not the e one I had issues installing on windows 7 
this morning with a total crash. I had to reboot windows, though I git it to 
run eventually by downloading it and not doing it as an update, but running 
it and then making it overwrite the old portable. The logs are on the dev 
list if anyone is interested. I have been out all day and I'm frazzled.
 Brian

bglists@blueyonder.co.uk
Sent via blueyonder.
Please address personal E-mail to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.
Newsgroup monitored: alt.comp.blind-users
----- Original Message -----

**Comment by josephsl** [comment]
Hi,

To @nishimotz, can you try the following build and see if it is resolved?

https://ci.appveyor.com/api/buildjobs/20sxysxt0duaphwu/artifacts/output%2Fnvda_snapshot_pr9657-17432%2C35710fab.exe

**Comment by nishimotz** [comment]
@josephsl issue #9583 does not occur with nvda_snapshot_pr9657-17432,35710fab.exe.

**Comment by josephsl** [comment]
Hi, yep, this means importlib will be reserved for Threshold (I need to also add some more relative imports that were missed in the initial run). Thanks. CC @LeonardDer for comments please.

**Review by michaelDCurran — APPROVED** [review]

**Pull request merged**
