### PR TITLE
Restore NVDA process helper's name

### LINKED ISSUE #16094: Rename NVDA process helper name from "A free and open source screen reader for Microsoft Windows" to "NVDA process helper"
### Is your feature request related to a problem? Please describe.

When installing NVDA 2024.1 Beta 5 or running a COM Registration fixing tool, the UAC dialog gives the application name of NVDA as "A free and open source screen reader for Microsoft Windows".

### Describe the solution you'd like

It would be beneficial to at least include "NVDA" in there.  In discussion with Sean, his suggestion is:
"NVDA Process Helper"

### Describe alternatives you've considered

In previous versions of NVDA (2023.3) this name was simply given as "NVDA".

### Additional context

From Sean: "This is a change made during our upgrade of py2exe."

### PR DESCRIPTION
**Pull request by SaschaCowley**
### Link to issue number:

Fixes #16094 

### Summary of the issue:

UAC requests were informing users that "A free and open source screen reader for Microsoft Windows" wanted to make changes to their PC.

### Description of user facing changes

Changed back to the old behaviour where UAC dialogs called the launcher "NVDA".

### Description of development approach

Updated `nvda_slave.pyw`'s script in `setup.py` to have `version_info.description` be `name` rather than `description`.

### Testing strategy:

Created self-signed build and attempted install to ensure the change had taken effect.

### Known issues with pull request:

None.

### Code Review Checklist:

- [x] Documentation:
  - Change log entry
  - User Documentation
  - Developer / Technical Documentation
  - Context sensitive help for GUI changes
- [x] Testing:
  - Unit tests
  - System (end to end) tests
  - Manual testing
- [x] UX of all users considered:
  - Speech 
  - Braille
  - Low Vision
  - Different web browsers
  - Localization in other languages / culture than English
- [x] API is compatible with existing add-ons.
- [x] Security precautions taken.

### CODE REVIEW

**Comment by CyrilleB79** [comment]
Just a detail for clarity:

@SaschaCowley could you please modify the current PR's title to avoid the word "Revert"?
Using "Revert" is a bit confusing and lets think that a previously merged PR has to be reverted.

What about the following instead?
"Restore NVDA process helper's name"

**Review by seanbudd — DISMISSED** [review]

**Review by gerald-hartig — DISMISSED** [review]

**Comment by seanbudd** [comment]
before merging this, this need to be retargeted to beta and rebased on beta

**Comment by seanbudd** [comment]
Hi @SaschaCowley - this still need to be rebased on beta (`git rebase -i beta`)

**Comment by XLTechie** [comment]
@SaschaCowley did you mean to push 102 commits on this? You're at 175 commits now, modifying 146 files. It appears to graft in all of the diff between beta and master.

**Comment by SaschaCowley** [comment]
> @SaschaCowley did you mean to push 102 commits on this? You're at 175 commits now, modifying 146 files. It appears to graft in all of the diff between beta and master.

Major mess-up on my part, I think it's fixed now 😅

**Comment by XLTechie** [comment]
Yeah, looks like it.

Avoiding (or at least fixing) this sort of thing, is one of the multiple reasons why I work in a work branch, and check that out into a PR only branch. Then if I royally screw something up, I can just delete the PR branch locally, check it out from the base again, cherry-pick my commits on top of it, and force-push a new copy to the remote. It preserves the most important part of my work in the work branch, which I can rebase or whatever to my heart's content with nobody the wiser. :)

**Review by seanbudd — APPROVED** [review]

**Pull request merged**
