### PR TITLE
Fix table navigation in browse mode in MS Word for PR #13345

### PR DESCRIPTION
**Pull request by mltony**
### Link to issue number:
Issue with navigating over merged cells in MS Word while in browse mode discussed in PR #13345.
### Summary of the issue:
PR #13345 fixes navigating over merged cells in tables by caching the last column/row. Testing showed that it doesn't work in MS Word  while in browse mode (focus mode works fine). This was tracked down to class UIABrowseModeDocumentTextInfo not implementing __eq__ method. 

### Description of how this pull request fixes the issue:
Fixing that by implementing __eq__ and __hash__ functions in parent class RootProxyTextInfo.

### Testing strategy:
Tested in MS Word. Tried with both checked and unchecked value of "Always use UI Automation to access Microsoft Word document controls when available".
### Known issues with pull request:
N/A
### Change log entries:
Doesn't deserve a separate entry, should be merged with #13345.
### Code Review Checklist:

- [x] Pull Request description:
  - description is up to date
  - change log entries
- [x] Testing:
  - Unit tests
  - System (end to end) tests
  - Manual testing
- [x] API is compatible with existing add-ons.
- [x] Documentation:
  - User Documentation
  - Developer / Technical Documentation
  - Context sensitive help for GUI changes
- [x] UX of all users considered:
  - Speech 
  - Braille
  - Low Vision
  - Different web browsers
  - Localization in other languages / culture than English

### CODE REVIEW

**Comment by seanbudd** [comment]
has this been tested with browse mode and focus mode?

**Comment by mltony** [comment]
@seanbudd,
Yes, tested with both browse mode and focus mode.

I cannot call parent __hash__ function here - I spent quite some time debugging this. Here is the reason.
RootProxyTextInfo is a subclass of TextInfo, which is a subclass of baseObject.AutoPropertyObject. The latter overrides
```
def __new__(cls, *args, **kwargs):
    ...
    self.__instances[self]=None
    ...
```
So it uses the object as key in a dictionary during a call to `__new__`, which in turn calls `__hash__()`. However at this time none of the fields of the object are initialized, since `__new__` is called before `__init__`. So `self.innerTextInfo` doesn't even exist at this point. So using identity hash function seems to be the only possibility here.

BTW on a tengential note, there seems to be a fundamental problems with `__eq__` and `__Hash__` functions. It appears that Python expects the object to be immutable to support custom `__eq` and `__hash__` functions, whereas TextInfos are mutable. I don't quite understand caching in `AutoPropertyObject`, but it seems to me that identity hashing with custom `__eq__` function might not work as expected. Python expects that for any two objects `a` and `b` if `a == b` then it must be that `a.__hash__() == b.__hash__()`, but this assumption is violated at least with TextInfos. Please note that I am not breaking things in this PR, as this is the way it works in for example `class UIATextInfo`. Not sure if this might cause some hard-to-debug problems in the future.

**Comment by mltony** [comment]
@seanbudd, This PR is ready for review (sorry if I confused you by my previous comment). What should be the next steps to have this one and #13345 merged?

**Comment by Adriani90** [comment]
Does this handle also i.e. rows of different number of cells? See for example isue #2683.

**Comment by mltony** [comment]
This only forwards __eq__ function for certain instances of TextInfo, it doesn't directly change any table-related behavior.

**Review by seanbudd — APPROVED** [review]

**Pull request merged**
