### PR TITLE
Fix bug where NVDA would not speak until restarted after add-on installation.

### LINKED ISSUE #14525: NVDA does not speak after add-on installation until it is restarted
### Steps to reproduce:
1. Take any add-on, e.g. the simple add-on [Say Product Name and Version](https://addons.nvda-project.org/addons/sayProductNameAndVersion.en.html)
2. In an NVDA without any add-on installed, install your add-on and restart
3. Once NVDA is restarted, open the add-on manager dialog
4. Alt+Tab to Windows Explorer, keeping Add-on manager window opened in the background
5. Install again your add-on from Windows Explorer
6. When prompted to restart, press Yes

### Actual behavior:
After step 6., NVDA does not restart and does not speak anymore. Windows is responsive though. You need to press Yes again (with no vocal feedback) to have it restarted.

Also, the following error is found in the log:
```
ERROR - core.restart (15:01:57.486) - MainThread (2692):
NVDA already in process of exiting, this indicates a logic error.
```

### Expected behavior:
NVDA should read the dialog box.

The error should not appear in the log.

### NVDA logs, crash dumps and other attachments:
[nvda-old.log](https://github.com/nvaccess/nvda/files/10373783/nvda-old.log)

#### NVDA installed/portable/running from source:
Installed
#### NVDA version:
2022.4
#### Windows version:
Windows 10 20H2 (AMD64) build 19042.2364
#### Name and version of other software in use when reproducing the issue:
N/A
#### Other information about your system:
N/A
#### Does the issue still occur after restarting your computer?
Yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
Issue reproduced on the following older versions:
* 2021.2 portable
* 2022.1 portable
#### If NVDA add-ons are disabled, is your problem still occurring?
N/A but tested with two different add-ons, to exclude the possibility of an issue with the add-on.
#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
Not tested, unrelated.

### PR DESCRIPTION
**Pull request by seanbudd**
### Link to issue number:
Fixes #14525

### Summary of the issue:
NVDA blocks exit on modal dialogs which require an answer.
If a message box is created after NVDA has triggered a shutdown, NVDA blocks exit on the message box, even after synthesizers have been terminated.

### Description of user facing changes
Fix bug where NVDA would not speak until restarted after add-on installation.
Similar bugs with the same root cause may also be fixed.

### Description of development approach
Open, pending modal dialogs should block the exit of NVDA.
To prevent a deadlock NVDA should prevent opening new modal dialogs if the core shutdown has been triggered.

### Testing strategy:
Test STR in #14525

### Known issues with pull request:
None

### Change log entries:
refer to diff

### Code Review Checklist:

- [x] Pull Request description:
  - description is up to date
  - change log entries
- [x] Testing:
  - Unit tests
  - System (end to end) tests
  - Manual testing
- [x] API is compatible with existing add-ons.
- [x] Documentation:
  - User Documentation
  - Developer / Technical Documentation
  - Context sensitive help for GUI changes
- [x] UX of all users considered:
  - Speech 
  - Braille
  - Low Vision
  - Different web browsers
  - Localization in other languages / culture than English
- [x] Security precautions taken.

### CODE REVIEW

**Comment by seanbudd** [comment]
@CyrilleB79 would you be able to confirm this build fixes #14525

**Comment by CyrilleB79** [comment]
@seanbudd, tests on the commit 8a1601407317251aef592081c07b38a98a1e99b6 show that STR of #14525 is fixed.

There is however a slightly different use case that remains problematic.
STR:
0. Use a brand new NVDA config
1. Take any add-on, e.g. the simple add-on Say Product Name and Version
2. In an NVDA without any add-on installed, install your add-on and restart
3. Once NVDA is restarted, open the add-on manager dialog, but do not validate the warning dialog (keep it open)
4. Alt+Tab to Windows Explorer, keeping Add-on manager window opened in the background
5. Install again your add-on from Windows Explorer
6. When prompted to restart, press Yes

Actual behavior:
NVDA does not restart and an error is logged.
No problem with NVDA speech this time.

Expected behavior:
NVDA should restart, or a message should indicate why it cannot execute restart.

Note however that this issue is much more less concerning because we can imagine that people usually do not keep this dialog open. If you cannot find any fix for this, I'd suggest to merge the current PR anyway because it's already an improvement.

**Review by michaelDCurran — DISMISSED** [review]

**Comment by seanbudd** [comment]
@CyrilleB79 this should be fixed now

**Review by michaelDCurran — DISMISSED** [review]

**Comment by CyrilleB79** [comment]
> @CyrilleB79 this should be fixed now

Confirmed in beta branch: I get now the "Unavailable action" message after clicking Yes in the restart message.
Thanks!

**Pull request merged**
