### PR TITLE
UI/doc tweaks for "Announce formatting changes after the cursor"

### PR DESCRIPTION
**Pull request by jcsteh**
In NVDA's Document Formatting settings, "Announce formatting changes after the cursor" has been renamed to "Report formatting changes after the cursor", as it affects braille as well as speech.
Also, the User Guide previously gave Microsoft Word as an example of an application where this setting needs to be enabled. However, this setting is never checked for Word. Change this example to Wordpad instead.

### CODE REVIEW

**Comment by jcsteh** [comment]
@feerrenrut, mind taking a look?

**Comment by feerrenrut** [comment]
@jcsteh Looks good to me

**Comment by jcsteh** [comment]
This is incorporated into #6402. There is one tiny User Guide change that isn't included yet, however. CC @feerrenrut.

**Comment by feerrenrut** [comment]
@jcsteh I didn't back out this pull request, the conflicts were minimal. If all changes required are included in this PR then we are good to go. This PR will still need to be merged to master once incubated.

**Pull request merged**
