### PR TITLE
Add a script to start the wx inspection tool.

### PR DESCRIPTION
**Pull request by feerrenrut**
### Summary of the issue:
When working on the NVDA GUI, it's helpful to be able to inspect the layout and properties of controls and sizers. WxPython includes an inspection tool, while this can be started from the python console, starting it interrupts ones workflow.

### Description of how this pull request fixes the issue:
Adds a global command and shortcut `NVDA+ctrl+w` to open the Wx Inspector tool.

### Testing performed:
Run NVDA, executed the command with the shortcut

### Known issues with pull request:
This command is not really applicable to general users. Ideally these tools would be hidden behind an option in an advanced settings panel, something like "Enable Dev tools".

### Change log entry:

Section: Developers:
```
A new command has been added to start the wx Inspection Tool. The default keyboard shortcut is NVDA+ctrl+w (#9246).
```

### CODE REVIEW

**Comment by Adriani90** [comment]
Could this be changed to nvda+ctrl+f2? NVDA+ctrl+w is already part of the addon virtual revision which is still being used by many users. But since this key stroke would only apply when the coresponding check box has been enabled in advanced settings, I guess this is not high priority. cc: @josephsl

**Comment by leonardder** [comment]
> This command is not really applicable to general users. Ideally these tools would be hidden behind an option in an advanced settings panel, something like "Enable Dev tools".

I think an appropriate way to hide this is by leaving the script unassigned by default. People who need it can assign it from the input gestures dialog, and people who don't will only see it when going through the tools category in that dialog.

**Comment by josephsl** [comment]
Hi, I agree with Leonard on this, although it might be possible that I might give up the command mentioned by Reef. Thanks.

**Comment by feerrenrut** [comment]
> NVDA+ctrl+w is already part of the addon virtual revision

> hide this is by leaving the script unassigned by default

Fair points. I'll remove the default key assignment.

**Comment by feerrenrut** [comment]
While I will remove the shortcut. I don't think I should have used the word "hide". My intention was not to hide the dev tools; they should still be easily discoverable by developers, while preventing users from accidentally triggering tools that get in their way. That said keyboard shortcuts come at a premium, and should not be tied up to a feature that is used by very few.

**Review by michaelDCurran — APPROVED** [review]
Code is fine.   Note though that the Inspection tool has a few accessibility issues such as tab getting stuck in the details edit field. Plus that edit field is not accessible and NVDA fallsback to displayModel, sometimes producing some garbled text at the end of each line. However, as is, it is still a useful tool, even for me.

**Pull request merged**
