### PR TITLE
Use an older version of setuptools when installing requirements

### PR DESCRIPTION
**Pull request by seanbudd**
### Link to issue number:
None

### Summary of the issue:
setuptools has been updated, breaking support with py2exe: https://github.com/py2exe/py2exe/issues/208.

When installing packages, pip automatically pulls in the latest build dependences as specified in [PEP 518](https://peps.python.org/pep-0518/).
pip creates a custom temporary build environment to install packages using the latest pip environment.

### Description of development approach
Create a `pyproject.toml` to specify the build environment we are using.
https://packaging.python.org/en/latest/guides/writing-pyproject-toml/

Use the flag `no-build-isolation` when installing requirements.txt.
This prevent pip from using the custom build environment and automatically pulling the latest setuptools when installing packages.

As such, we need to manually install the desired version of setuptools, and manually install pip's dependency wheel.
https://stackoverflow.com/questions/62889093/what-does-no-build-isolation-do

### Testing strategy:
Ensure build completes successfully

### Known issues with pull request:
None

### Code Review Checklist:

- [x] Documentation:
  - Change log entry
  - User Documentation
  - Developer / Technical Documentation
  - Context sensitive help for GUI changes
- [x] Testing:
  - Unit tests
  - System (end to end) tests
  - Manual testing
- [x] UX of all users considered:
  - Speech 
  - Braille
  - Low Vision
  - Different web browsers
  - Localization in other languages / culture than English
- [x] API is compatible with existing add-ons.
- [x] Security precautions taken.

### CODE REVIEW

**Comment by CyrilleB79** [comment]
Isn't there any impact for local builds?

**Comment by dpy013** [comment]
Looks like py2 didn't follow up with setuptools?
Also I noticed that pyinstaller is more actively updated than py2, could we possibly use pyinstaller to replace py2?

**Comment by seanbudd** [comment]
@CyrilleB79 - yes there may be, the current approach should fix this for local environments. I haven't been able to reproduce this locally so I cannot confirm.

**Comment by seanbudd** [comment]
@dpy013 - we will likely have to migrate from py2exe due to no python 3.12 support.
This is out of scope of this PR, we need to fix the build system immediately and this is a large project.

https://github.com/py2exe/py2exe/issues/191

**Review by gerald-hartig — APPROVED** [review]

**Pull request merged**
