### PR TITLE
Support math content in MS Word build 14326+ via UIA

### LINKED ISSUE #12941: nvda alpha no longer works with math player
### Steps to reproduce:
with recent builds of nvda 2021.3 alpha, after commiting "make UI automation for recent office365 builds" install math type, (demo will be sufficient), and math player 4. 
try to read math, once you focus a math equasion, nvda just announces "graphic, math type x.x equasion"
### Actual behavior:
math is not recognized nor can it be navigated.
### Expected behavior:
NVDA should still be able to work with math in word
#### NVDA installed/portable/running from source:
installed
#### NVDA version:
(NVDA)
Version: alpha-23953,f8df880a

#### Windows version:
windows 11
#### Name and version of other software in use when reproducing the issue:
Math type 6.x or 7.x and math player 4
#### Other information about your system:
I think this is errelivant to the issue.
#### Does the issue still occur after restarting your computer?
yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
yes, nvda 2021.2 works as expected as long as "use UI automation with word" is not checked. 
#### If NVDA add-ons are disabled, is your problem still occurring?
yes
#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
yes

### LINKED ISSUE #12946: Support mathML UIA custom property in MS Word
### Is your feature request related to a problem? Please describe.
NVDA provides rich reading and navigation of math content via MayPlayer. As long as NVDA can fetch raw mathML from an app, it can then provide this to mathPlayer which will then handle the navigation and generating of speech strings.
To access math content in Microsoft word, the user would install MathType and MathPlayer. The user or author of the document would create mathType equations, or convert Office Math equations to mathType, and then NVDA could use the MS word object model and a mathType API to fetch the mathML.
 
However, when accessing MS Word via UIA, there is no mechanism to fetch the mathML from mathType.

MS Word does however provide a UIA custom property for fetching mathML from Office math equation nodes.
C++ formatted GUID: `{ 0x25330951, 0xa372, 0x4db9, { 0xa8, 0x8a, 0x85, 0x13, 0x7a, 0xd0, 0x8, 0xd2 }`
Available in MS Word build 14326 and higher.

### Describe the solution you'd like
NVDA should support the mathML UIA custom property, and send the mathML to mathPlayer, thereby providing reach reading and navigation of Office math equations in MS word.

However, if a user has an existing document with mathType equations, they will have to highlight each one, and choose Convert to Office Math equation in the context menu.

### PR DESCRIPTION
**Pull request by michaelDCurran**
### Link to issue number:
Fixes #12946
Fixes #12941 

### Summary of the issue:
NVDA was able to provide rich support of mathematical content in Microsoft Word by making use of MathPlayer, MathType and the MS Word object model.
However, when NVDA only relies on UI Automation to access MS Word docuents, it is no longer possible to fetch mathMl from MathType equations via the MS Word object model.
However, Microsoft very recently added a new UI Automation custom property for fetching raw mathMl from an Office Equation node, thus if NVDa were to fetch this mathMl, then it could pass it along to mathPlayer as usual, then providing rich reading / navigation of math content in MS word again.

### Description of how this pull request fixes the issue:
* Register the mathMl UIA custom property.
* Fetch the raw mathMl from an MS Word Office Equation node.
* Expose it for the rest of NVDA to find and use with mathPlayer.

Note that MS Word also provides a basic form of linea symbol navigation in equations, so we make sure that the mathMl is exposed to mathPlayer when moving by line, replacing MS Word's own inner math content. But if moving by word/character, then MS Word's own inner math content is left in tact.

### Testing strategy:
* Opened an MS Word document
* Started typing a math equation by pressing alt+=
* Typed an equation like `x^2+x+1` and pressed enter.
* Pressed up arrow to move back up to the equation, confirming that NVDA read out the equation with mathPlayer, and also brailled the equation in Nemeth code. 
* Used the left and right arrow keys to move through the equation by symbol. Confirming that Microsoft Word's own navigation was used, and each symbol was reported.
* Pressed NvDA+alt+m to interact with the Math using MathPlayer and moved aorund the math tree with the arrows.
* Pressed escape to exit Math interaction mode.
* Switched to Browse mode with NVDA+space.
* Pressed enter to activate the current item in browse mode, ensuring that mat interaction mode was entered.
* Pressed ecape to exit math interaction mode.
* Still in browse mode, pressed NvDA+alt+m to enter math interaction mode.
* Pressed escape to exit math interaction mode.

### Known issues with pull request:
Users / authors will have to convert any old MathType equations to Office Equations by selecting each equation, and then choosing Equation Options -> Convert to Office math in the context menu.
The experience for typing math equations is now slightly different in that the user needs to now use Microsoft Word's own math input feature. I.e. pressing alt+= and typing the equation. However, MS Word does now support several input syntaxes, including LateX similar to MathType.

### Change log entries:
New features
In Microsoft Word accessed via UI Automation, NVDA will now make use of mathPlayer to read and navigate Office math equations. (#12946)
    - For this to work, you must be running Microsoft Word 365/2016 build 14326 or later. 
    - MathType equations must also be manually converted to Office Math by selecting each and choosing Equation options -> Convert to Office Math in the context menu.
Changes
Bug fixes
For Developers

### Code Review Checklist:

- [ ] Pull Request description:
  - description is up to date
  - change log entries
- [ ] Testing:
  - Unit tests
  - System (end to end) tests
  - Manual testing
- [ ] API is compatible with existing add-ons.
- [ ] Documentation:
  - User Documentation
  - Developer / Technical Documentation
  - Context sensitive help for GUI changes
- [ ] UX of all users considered:
  - Speech 
  - Braille
  - Low Vision
  - Different web browsers
  - Localization in other languages / culture than English

### CODE REVIEW

**Comment by michaelDCurran** [comment]
Assuming that we keep accessing UIA by default in recent builds of MS Word for NvDA 2021.4, it is necessary for this pr to be also included, otherwise users will loose access to mathematical content.

**Review by seanbudd — DISMISSED** [review]

**Review by Qchristensen — DISMISSED** [review]
This is good and will be appreciated by users, great work :)

**Review by LeonarddeR — CHANGES_REQUESTED** [review]

**Review by seanbudd — APPROVED** [review]

**Comment by codeofdusk** [comment]
This PR is still listed under 2021.3 changes. Is this a mistake?

**Comment by CyrilleB79** [comment]
Yes it's a mistake due to retargetting from beta to master. Good catch!
I have submitted #13095 to fix this.

**Pull request merged**
