### PR TITLE
Reprocess speech at symbol level all if symbol level processing causes an empty sequence

### LINKED ISSUE #15024: PR#13483 caused NVDA to report unexpected Blank
### Steps to reproduce:
1. nvda+Ctrl+Z Type the following, then press enter:
  - `print("hello")`
  - `print(['hello'])`
### Actual behavior:
NVDA speaks "" "blank" after each output:
  - 'hello' blank
  - ['hello'] blank
### Expected behavior:
No redundant "" "blank" should be reported.
### NVDA logs, crash dumps and other attachments:
[nvda_log.txt](https://github.com/nvaccess/nvda/files/11783704/nvda_log.txt)

#### NVDA installed/portable/running from source:
Installed
#### NVDA version:
NVDA-2023.1
#### Windows version:
Windows 10 22H2 (AMD64) build 19045.3086
#### Name and version of other software in use when reproducing the issue:
None
#### Other information about your system:
None
#### Does the issue still occur after restarting your computer?
Yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
No
#### If NVDA add-ons are disabled, is your problem still occurring?
Yes
#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
yes

### PR DESCRIPTION
**Pull request by seanbudd**
### Link to issue number:
Fixes #15024
Fixup/follow up of #13483

### Summary of the issue:
After #13483 was merged, empty speech sequences were announced as blank.
If a sequence just containing symbols is processed, and the final result is empty sequence, NVDA says blank.
This can be misleading, and the ideal behaviour is to announce symbols if there is no other text to read in a sequence.

### Description of user facing changes

- The NVDA Python console now says "Greater than, greater than, greater than" after reading out the results of a command. This should be suppressed from the NVDA GUI ideally.
- A line in a document just containing symbols that are usually suppressed is now read at symbol level all

### Description of development approach
Speech is reprocessed at symbol level all if the processed speech becomes empty due to symbol suppression.

### Testing strategy:
System tests must be changed to document the new behaviour.
This PR build will fail initially, and tests will be updated based on the failures.

### Known issues with pull request:
If this PR doesn't achieve a satisfactory result, #13483 should be reverted

### Change log entries:
Changes
Update the changes for #13483

### Code Review Checklist:

- [ ] Pull Request description:
  - description is up to date
  - change log entries
- [ ] Testing:
  - Unit tests
  - System (end to end) tests
  - Manual testing
- [ ] API is compatible with existing add-ons.
- [ ] Documentation:
  - User Documentation
  - Developer / Technical Documentation
  - Context sensitive help for GUI changes
- [ ] UX of all users considered:
  - Speech 
  - Braille
  - Low Vision
  - Different web browsers
  - Localization in other languages / culture than English
- [ ] Security precautions taken.

### CODE REVIEW

**Comment by XLTechie** [comment]
@seambudd wrote:
>  *  The NVDA Python console now says "Greater than, greater than, greater than" after reading out the results of a command. This should be suppressed from
>     the NVDA GUI ideally.

Why?

Is that not the standard prompt of pretty much every Python console everywhere?

It appears in docstrings to indicate console example use. It is quite common.
How is one to know a long-running command has completed, if there is no prompt?

**Comment by robin24** [comment]
Hey @seanbudd and all,
I've just been reading through the entire discussion around this change, starting with @SamKacer's original PR.
I'd like to bring up a use case here which I think hasn't received a lot of attention yet, but is super critical for a lot of users.
When using NVDA, I rely heavily on a combination of speech and Braille for things like navigation, coding and proofreading.
My punctuation settings and speech dictionaries are customized so that only the symbols that I want to hear are spoken by NVDA, for everything else I'll refer to my Braille display to check exactly what is written on the currently focused line.

Considering the Python console example, if I'm on a line that has nothing but three greater than symbols on it (>>>) and my punctuation level / dictionary rules are set up in a way where these symbols aren't spoken, I absolutely wouldn't want some custom "magic" occurring in the background causing them to be spoken in spite of my verbosity settings.
The expected behavior in my opinion would be for no text to be spoken, resulting in silence when the >>> line is focused.
I disagree with @SamKacer's opinion that no speech output automatically makes a user think that NVDA might have frozen or crashed, even if it did it would be simple enough to perform some other action that would be guaranteed to result in speech output so long as NVDA is operating normally.
Please do note that I'm really not trying to bash the idea, I 100% feel that bringing behaviors like this one up and discussing possible ideas for improvement is super important, it's what helps projects like NVDA evolve over time.
I just have to say that, after reading through all the related comments, I'm super concerned that this will severely break the workflows of myself and others, especially those using a Braille display.
It might perhaps be useful for those relying on speech exclusively so I'm not going to suggest scratching this entirely, but really it should be a user-configurable setting that is off by default IMO.

**Comment by SamKacer** [comment]
@seanbudd Thanks for putting together this alternative. I think we will just come to the same conclusion as the discussion in #13483. That is we need this to be configurable and there is no single behavior that is universally preferable.

Just to quickly point out why this proposed behavior would also cause regressions in certain cases, consider the original use case I was trying to "fix". Say you are working on source code that uses tabs for indentation. Some lines might only contain tabs and nothing else. Silence sucks because there might be multiple lines in a row like this or it might be the last/first line, in which case you might keep arrowing until you realize you are at the end/beginning. So you'd ideally just want to hear "blank" same as if indentation was spaces instead. However, with this approach you would here something like "tab tab tab". Which is better than silence in my opinion, but probably quite annoying.

I think the major mistake I made in #13483 is even that behavior should have been configurable with the old silence behavior remaining the default.

So I am thinking it would probably be best to revert #13483. Instead I would raise a PR that gives the option of having the "blank" behavior, but have it off by default. In addition it could also give this proposed behavior as another alternative. 

So there would be a config option like "what to do with empty speech sequences" with options:

* silence (default)
* speak "blank"
* temporarily increase symbol level

Although now that I am thinking through it, what about when a speech sequence is made empty by a dictionary substitution and not because of symbol level. Then even with this it would be silent in those cases.

So instead it would then make sense to have 2 checkboxes:

* output blank for empty speech sequences (default: false)
* temporarily increase symbol level for empty speech sequences (default: false)

**Comment by SamKacer** [comment]
@robin24 thanks for the info. I didn't consider that. I am a speech only user myself. That makes sense

**Comment by XLTechie** [comment]
@SamKacer wrote:

> Say you are working on source code that uses tabs for indentation. Some lines might only contain tabs and nothing else. Silence sucks because there might be
> multiple lines in a row like this or it might be the last/first line, in which case you might keep arrowing until you realize you are at the end/beginning.
> So you'd ideally just want to hear "blank" same as if indentation was spaces instead. However, with this approach you would here something like "tab tab
> tab". Which is better than silence in my opinion, but probably quite annoying.

I would argue that while it may be annoying, it is informational. If you have 
lines that are only invisible indent characters, "ideally" you would want to get 
rid of them, and replace them with actual blank lines.
You would have a hard time doing that if they were all resolved to "blank".

Imo you are replacing the un-ideal with the inaccurate, and calling it an 
improvement.

**Comment by XLTechie** [comment]
@SamKacer wrote:

> So instead it would then make sense to have 2 checkboxes:
>
>  *  output blank for empty speech sequences (default: false)
>  *  temporarily increase symbol level for empty speech sequences (default: false)

Can we avoid the technality of "speech sequences"? Users don't really know what 
those are, not in the way that developers do, and using the term when it's not 
necessary just muddies the water.

Something like "when there is nothing to speak", or "when speech is empty", or 
"when nothing would be spoken", seems more gentle on the user.

**Comment by leonardder** [comment]
> Imo you are replacing the un-ideal with the inaccurate, and calling it an improvement.

This is exactly my opinion. Therefore I will personally disagree with a follow up that reintroduces this behavior, even if it is configurable. Reporting blank for something that isn't blank is and remains a case of misrepresentation. That said, it is probably better suited as an add-on. Therefore I'd rather see investment in a proper extension point that allows implementing this behavior in an add-on.

**Comment by SamKacer** [comment]
> This is exactly my opinion. Therefore I will personally disagree with a follow up that reintroduces this behavior, even if it is configurable. Reporting blank for something that isn't blank is and remains a case of misrepresentation. That said, it is probably better suited as an add-on. Therefore I'd rather see investment in a proper extension point that allows implementing this behavior in an add-on.

I don't understand. Why would you be against leaving it as a configurable option. You might have that opinion, but other users like myself have the opposite opinion. Aren't user settings partly meant for letting some people have one set of behaviors and other users have a different set of behaviors.

I have to say I don't really appreciate the implication that my preffered behavior is just strictly irrational and for some reason I am just working against my own self interest. Or perhaps that I just don't know what is good for me

**Comment by leonardder** [comment]
> I don't understand. Why would you be against leaving it as a configurable option. You might have that opinion, but other users like myself have the opposite opinion. Aren't user settings partly meant for letting some people have one set of behaviors and other users have a different set of behaviors.

The latter is certainly true, as long as the different options represent reality. This is not the case when announcing blank for something that is not.

> I have to say I don't really appreciate the implication that my preffered behavior is just strictly irrational and for some reason I am just working against my own self interest. Or perhaps that I just don't know what is good for me

I'm sorry if I gave this impression. As a community, we want to make this product the best it can be. For me, this works both ways, contributing code or ideas to new features or bug fixes, but also stepping into the breach if a change causes the product to present inaccurate information to the user. And yes, to be honest, announcing blank for something that isn't, I can't rationalize that. That is not a criticism of you personally.

**Pull request closed without merging**
