### PR TITLE
Update espeak-ng to most recent release 1.49.1

### PR DESCRIPTION
**Pull request by feerrenrut**
### Link to issue number:
See comment https://github.com/nvaccess/nvda/pull/7115#issuecomment-308062764

### Summary of the issue:
The goal is to incubate the [most recent release of Espeak-ng](https://github.com/espeak-ng/espeak-ng/releases/tag/1.49.1), to test for stability. Ideally this can then be merged to master (which is using an arbitrary espeak commit from the 10th of Jan). The 1.49.1 release was made on Jan 22nd.

### Testing performed:
Built NVDA locally, smoke tested by setting espeak as the synth, and moving through a few applications / web pages. Only tested with English.

### Change log entry:
Changes:
Espeak-ng has been updated to release 1.49.1.

### CODE REVIEW

**Comment by michaelDCurran** [comment]
This pr had to be reverted in a6efeab as when building the rc (which is compiled as a release), the 'ar' dictionary failed to compile. This is most likely related to espeak-ng/espeak-ng#287

**Comment by michaelDCurran** [comment]
Slight false alarm.  In the end we were able to get a release build made with espeak 1.49.1. However, it is hit and miss as to whether it fails or not. Before 2017.4 we *must* switch to an espeak-ng build  with the fixes for espeak-ng/espeak-ng#287

**Comment by derekriemer** [comment]
Is this going to build for 17.3?

**Comment by michaelDCurran** [comment]
The build fails intermittently. However we know it can succeed. When it 
comes time for the release, it simply may need to be built multiple 
times.  Certainly not a great position to be in, but  later builds of 
espeak-ng no longer have the issue we know, so we will ensure we upgrade 
for 2017.4.

**Pull request merged**
