### PR TITLE
added __ne__ to textInfos.TextInfo class

### PR DESCRIPTION
**Pull request by mohammad-suliman**
I tested NVDA's behavior after the change: unfortunately, backspace script no longer works. no errors in the log, the char before the caret is deleted, but NVDA doesn't make any announcement

### CODE REVIEW

**Comment by mohammad-suliman** [comment]
also, the new line script bounded to enter doesn't work after this change.

**Comment by jcsteh** [comment]
Just to clarify, I assume you mean this only breaks for UIA? Or were you 
seeing it break elsewhere as well?

**Comment by mohammad-suliman** [comment]
Yes, with the text edit fields you recommended to test withVS text editorSearch field of start menu 

Get Outlook for iOS




On Tue, May 24, 2016 at 3:43 PM -0700, "James Teh" <notifications@github.com> wrote:










Just to clarify, I assume you mean this only breaks for UIA? Or were you 

seeing it break elsewhere as well?

**Comment by jcsteh** [comment]
Regarding backspace, we think expanding to character before creating the bookmark in EditableText._backspaceScriptHelper might fix this. This needs testing, though.

I'm not sure why enter isn't working. Does it just say nothing (instead of the start of the line)? That issue seems strange to me because the bookmarks before and after enter is sent should definitely be different because the cursor has moved, and we're adding to the text, not deleting, so there's no ambiguity.

**Comment by mohammad-suliman** [comment]
if I remember correctly, I concluded it doesn't work depending on prints 
to the log. will double check and get back.

**Comment by mohammad-suliman** [comment]
unfortunately, it didn't work, I did the following:
*    added a print to the log before the last line of hasCaretMoved method:
         log.debug("after the while loop")
         return (False,newInfo)
*   tested with VS text editor.
*    in the log: after enter gesture is received, I get the print "after 
while loop"
something to mention is that NVDA didn't announce anything when pressing 
enter even before the change. and don't think this is a problem because, 
only indents are reported on enter gesture. and indents aren't reported 
for empty lines in VS text editor.

**Comment by jcsteh** [comment]
> Regarding backspace, we think expanding to character before creating the bookmark in EditableText._backspaceScriptHelper might fix this. This needs testing, though.

Ug. It fixes the issue for the search box in Explorer, but not the search box in the Win 10 Start Menu.

**Comment by mohammad-suliman** [comment]
Jamie, why we can't use TextSelectionChanged event to determine whether the caret has moved as mentioned in this link under "Interoperability with the System Caret" heading:
https://msdn.microsoft.com/en-us/library/windows/desktop/ff384841%28v=vs.85%29.aspx#SystemCaret
tried to remap the mentioned event to caret event, and added an empty implementation to event_caret in UIA class. and in hasCaretMoved, if there are pending caret events, we return true.
if eventHandler.isPendingEvents("caret"):
    return (True, None)
it works fine
maybe if we want to make the code safer, the design will be ugly a bit. is this the problem here?

**Comment by jcsteh** [comment]
Yeah, Mick and I discussed this too. We previously listened for that event. Unfortunately, some controls (I believe WPF 2.5 text controls, but I'd need to hunt down specifics) flood those events, causing major performance problems. There's no way for us to block events for specific controls. Welcome to the agony of UI Automation and it's myriad of stupidly broken implementations, one of the great banes of my existence.

**Comment by mohammad-suliman** [comment]
Fixing this seems to be a not easy challenge!

**Comment by jcsteh** [comment]
For reference, this event got disabled (again) in 0df44ab (#1205).

**Comment by leonardder** [comment]
Could you please update the initial description of this pull request according to the pull request template?

**Comment by jcsteh** [comment]
Adding blocked label since there are open issues for which we don't yet have solutions. See comments above, especially https://github.com/nvaccess/nvda/pull/5991#issue-156435428 and https://github.com/nvaccess/nvda/pull/5991#issuecomment-221310485.

**Comment by feerrenrut** [comment]
I'm going to close this PR, there has not been any meaningful activity in a long time, and it's not clear what the initial intention was.

**Pull request closed without merging**
