### PR TITLE
Remove previous add-on version before installing the next

### LINKED ISSUE #14991: Regression: Unable to update add-ons containing dynamic link libraries.
### Steps to reproduce:
1. Install this add-on: https://github.com/cary-rowen/AudioControl/releases/download/v1.8.1/AudioControl-1.8.1.nvda-addon
2. After the add-on has been installed and restarted, try installing it again to simulate the update process.
### Actual behavior:
You will get an error:Failed to install add-on from D:\audioControl-1.8.1.nvda-addon
Error log snippet:
```
ERROR - gui.addonGui.installAddon (09:25:32.966) - MainThread (3700):
Error installing  addon bundle from D:\audioManager-1.0.0.nvda-addon
Traceback (most recent call last):
  File "addonHandler\__init__.pyc", line 464, in completeRemove
PermissionError: [WinError 5] 拒绝访问。: 'C:\\Users\\cary\\AppData\\Roaming\\nvda\\addons\\audioManager' -> 'C:\\Users\\cary\\AppData\\Roaming\\nvda\\addons\\tmpbzig4yv2.delete'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "gui\addonGui.pyc", line 553, in installAddon
  File "addonHandler\__init__.pyc", line 438, in requestRemove
  File "addonHandler\__init__.pyc", line 466, in completeRemove
RuntimeError: Cannot rename add-on path for deletion
```
Restarting NVDA gives the following error:
```
ERROR - addonHandler.Addon.completeInstall (09:34:02.103) - MainThread (808):
Failed to complete addon installation for audioControl
Traceback (most recent call last):
  File "addonHandler\__init__.pyc", line 429, in completeInstall
FileExistsError: [WinError 183] 当文件已存在时，无法创建该文件。: 'C:\\Users\\cary\\AppData\\Roaming\\nvda\\addons\\audioControl.pendingInstall' -> 'C:\\Users\\cary\\AppData\\Roaming\\nvda\\addons\\audioControl'
DEBUG - addonHandler._getAvailableAddonsFromPath (09:34:02.264) - MainThread (808):
Found add-on audioControl - 1.8.1. Requires API: (2022, 4, 0). Last-tested API: (2023, 1, 0)
DEBUG - addonHandler._getAvailableAddonsFromPath (09:34:02.264) - MainThread (808):
Loading add-on from C:\Users\cary\AppData\Roaming\nvda\addons\audioControl.pendingInstall
DEBUG - addonHandler.Addon.__init__ (09:34:02.264) - MainThread (808):
Using manifest translation from C:\Users\cary\AppData\Roaming\nvda\addons\audioControl.pendingInstall\locale\zh_CN\manifest.ini
```
### Expected behavior:
The add-on is installed without popping up an error dialog, although the old add-on directory cannot be deleted immediately because it contains occupied files(DLL files).
After the next restart of NVDA, the old add-on directory is deleted and the add-on is updated.
This is the behavior of NVDA-2023.1
### NVDA logs, crash dumps and other attachments:
Logs have been provided above.
#### NVDA installed/portable/running from source:
installed and portable
#### NVDA version:
alpha-28387

#### Windows version:
Windows 10 22H2 (AMD64) build 19045.2965
#### Name and version of other software in use when reproducing the issue:
None
#### Other information about your system:
None
#### Does the issue still occur after restarting your computer?
Yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
NVDA-2023.1 cannot reproduce.
#### If NVDA add-ons are disabled, is your problem still occurring?
Yes
#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
Yes

### PR DESCRIPTION
**Pull request by seanbudd**
### Link to issue number:
Fixes #14991 

### Summary of the issue:
When installing an add-on from an external source, install tasks for the new add-on version are started before the previous add-on version is removed.
This causes the install to fail, as initialized DLLs as part of the install tasks may block the remove from occurring.
This is legacy behaviour (before #13985) so it is uncertain why this is a recent regression.

### Description of user facing changes
Should allow updating add-ons with DLL files from an external source.

### Description of development approach
Move install tasks to after removal

### Testing strategy:
- [ ] Confirm manual testing with @cary-rowen 

### Known issues with pull request:
none

### Change log entries:
N/A

### Code Review Checklist:

- [x] Pull Request description:
  - description is up to date
  - change log entries
- [ ] Testing:
  - Unit tests
  - System (end to end) tests
  - Manual testing
- [x] API is compatible with existing add-ons.
- [x] Documentation:
  - User Documentation
  - Developer / Technical Documentation
  - Context sensitive help for GUI changes
- [x] UX of all users considered:
  - Speech 
  - Braille
  - Low Vision
  - Different web browsers
  - Localization in other languages / culture than English
- [x] Security precautions taken.

### CODE REVIEW

**Comment by seanbudd** [comment]
@cary-rowen - can you please test #14991 with this try build and confirm you can no longer reproduce the issue?

https://ci.appveyor.com/api/buildjobs/q3udp9sprnt9sywa/artifacts/output%2Fnvda_snapshot_try-removeAddonBeforeInstall-28455%2C622da650.exe

**Comment by leonardder** [comment]
I wonder whether this should be treated as API breaking. Some add-ons might rely on the current order of install tasks being executed, e.g. they might check whether they're updating and perform a configuration update based on whether the previous version is installed.
Any thoughts about this @josephsl?

**Comment by seanbudd** [comment]
>I wonder whether this should be treated as API breaking. Some add-ons might rely on the current order of install tasks being executed, e.g. they might check whether they're updating and perform a configuration update based on whether the previous version is installed.

If this is the case, we would also need to fix `_addonStore.install.installAddon` which follows the order that this PR changes to.

**Comment by leonardder** [comment]
The underlying issue is actually a bug in the store I just discovered. I will write down my findings in #14991.

**Comment by seanbudd** [comment]
Good to know there is a different cause. When addressing it, we should make both `installAddon` functions work the same way to prevent the issues Joseph outlined.

**Pull request closed without merging**
