### PR TITLE
Again allow closing audio device on idle, opt in

### PR DESCRIPTION
**Pull request by LeonarddeR**
### Link to issue number:
https://github.com/nvaccess/nvda/issues/11615#issuecomment-764619365

### Summary of the issue:
On some Dell laptops, e.g. one owned by @jcsteh and my corporate laptop, NVDA tends to trigger an issue in the Waves Audio component installed on these laptops that causes a severe memory leak. This effectively means that you have to reboot your system at least an hour. There is a workaround to disable the waves audio suite on these machines, but that has several drawbacks.

### Description of how this pull request fixes the issue:
As an attempt to fix this, I added a flag to advanced settings to restore the old audio behavior (i.e. directly close on idle by default).

### Testing strategy:
t.b.d.

### Known issues with pull request:
None known

### Change log entries:
New features

### Code Review Checklist:

- [ ] Pull Request description:
  - description is up to date
  - change log entries
- [ ] Testing:
  - Unit tests
  - System (end to end) tests
  - Manual testing
- [ ] API is compatible with existing add-ons.
- [ ] Documentation:
  - User Documentation
  - Developer / Technical Documentation
  - Context sensitive help for GUI changes
- [ ] UX of all users considered:
  - Speech 
  - Braille
  - Low Vision
  - Different web browsers
  - Localization in other languages / culture than English

### CODE REVIEW

**Comment by leonardder** [comment]
Turns out this doesn't fix the actually problem I"m having.

**Comment by CyrilleB79** [comment]
On my job's DELL laptop, I work with USB headset always plugged.
When I resume from standby, it happens frequently that NVDA's TTS is played by the internal PC speaker rather than in the USB headset. It continues through the speaker as long as I perform the following action: press NVDA+control+S, do not change anything (the USB headset is already selected) and press Enter.

I have not tested this build (and cannot test it as an installed one). But it should probably allow to have the TTS sound played via the headset as soon as NVDA speaks something for the second time, as it was the case before with older versions of NVDA where the audio device was closed.

Another alternative could be to close/reopen only in case there has been an error while trying to play the audio via the USB without success.

What do you think? Would you mind reopening this PR to consider these use cases?

**Comment by leonardder** [comment]
I'm sure happy to reopen it, at least when it fixes something. However, for your particular issue, I think what you propose sounds like a better approach

**Comment by jcsteh** [comment]
My understanding is that there is code to detect changes to the default device and to switch accordingly. Your issue suggests that isn't working correctly. I'd suggest filing an issue for this, as there's probably a better solution than closing the device for every utterance.

**Pull request closed without merging**
