### PR TITLE
Fixed mistake in f-string Eurobraille

### PR DESCRIPTION
**Pull request by FalkoBabbage**
### Link to issue number:
Fix-up for #14690 
### Summary of the issue:
f-string was written as "f ...." instead of f"...." 
### Testing strategy:
None
### Change log entries:
New features
Changes
Bug fixes
For Developers

### Code Review Checklist:

- [ ] Pull Request description:
  - description is up to date
  - change log entries
- [ ] Testing:
  - Unit tests
  - System (end to end) tests
  - Manual testing
- [ ] API is compatible with existing add-ons.
- [ ] Documentation:
  - User Documentation
  - Developer / Technical Documentation
  - Context sensitive help for GUI changes
- [ ] UX of all users considered:
  - Speech 
  - Braille
  - Low Vision
  - Different web browsers
  - Localization in other languages / culture than English
- [ ] Security precautions taken.

### CODE REVIEW

**Comment by seanbudd** [comment]
Could you please rebase this on beta, and make this target beta instead?

**Comment by FalkoBabbage** [comment]
Hi @seanbudd,
Looks like you already rebased it?  I am not sure why there are 8 commits related to this pr.

**Comment by seanbudd** [comment]
I retargeted the PR to beta. The other commits are because your commit is based on master.

These are commits from master that we don't want on our beta branch.

To rebase a commit, you can follow this guide
https://git-scm.com/book/en/v2/Git-Branching-Rebasing

**Comment by seanbudd** [comment]
Apologies, that guide is not particularly accessible.

I'm not sure if anyone has suggestions on a non-visual guide to git rebases?

**Comment by seanbudd** [comment]
for reference I performed `git rebase -i beta`

**Comment by FalkoBabbage** [comment]
Thanks @seanbudd, I tried preforming `git rebase beta` but it seemed I made a greater mess.

**Pull request merged**
