### PR TITLE
Merge alpha into beta for 2021.1

### PR DESCRIPTION
**Pull request by seanbudd**
**This must be a merge commit (not squash merge)**

Currently blocked by: 

- [x] A further review of `changes.t2t`, including fixing some formatting

**This must be a merge commit (not squash merge)**

### CODE REVIEW

**Comment by josephsl** [comment]
Hi, mostly for Quentin: can we also look into duplicate entries in 2021.1 what’s new, specifically duplicates in changes for developers section? Thanks.

**Comment by codeofdusk** [comment]
Can #12094 please be merged into 2021.1 as well? Thanks.

**Comment by seanbudd** [comment]
> Can #12094 please be merged into 2021.1 as well? Thanks.

It'll come in with another merge from master, there a few more fixes that need to get in.

**Comment by leonardder** [comment]
I assume #11912 and #12376 should be merged in first as well, at least the former.

**Comment by feerrenrut** [comment]
This PR is primarily to let translators get started. We'll do a follow up alpha to beta merges as necessary. We won't do a beta release until we are confident with the changes.

**Comment by feerrenrut** [comment]
Let's not block this by the milestone issues. I want to allow translators to get started on the translations. This will make the first beta more widely relevant. We can do a follow up alpha -> beta merge once those milestone issues are fixed.

**Review by feerrenrut — APPROVED** [review]
Yep, lets go ahead and merge this.

**Pull request merged**
