### PR TITLE
Add ability to run commands from the input gestures dialog

### LINKED ISSUE #17209: NVDA Command Palette
### Is your feature request related to a problem? Please describe.

Currently, there are several commands in NVDA that can only be executed if an input gesture is assigned to them. This can present a problem where a user wishes to execute a script that does not have an input gesture assigned, but which they do not wish to give an input gesture, for example because it is rarely used. This may also be problematic for users who have difficulty remembering or executing complex input gestures, for whom there are a limited number of available key combinations to choose from.

### Describe the solution you'd like

Introduce a "command palette" that the user can open with a single input gesture (or via the NVDA menu), which presents all scripts that are possible in the current context. Allow the user to type to search for gestures (preferably with some sort of "fuzzy logic" to allow for imprecise matches). Allow the user to activate the selected script, with the effect of the script taking place in the context from which they invoked the command palette. Optionally, display the input gesture(s) associated with the script (according to the method used to open the command palette (desktop layout/laptop layout/touch)) alongside the script.

### Describe alternatives you've considered

Add an "Activate" button to the input gestures dialog, which performs the selected script in the context from which the user opened the input gestures dialog.

### Additional context

The command palette paradigm is present in many software products. For instance, Visual Studio Code and Windows Terminal both offer such functionality (by default both invoked with `Ctrl+Shift+P`). Some other screen readers, including Voiceover on the Mac, offer a "Commands Menu" which is functionally equivalent to a command palette.

#### Example user stories:

* As a user with a cognitive impairment, I want to be able to use natural language to search for NVDA commands so that I can use my computer without struggling to remember a lot of keystrokes.
* As a new NVDA user, I want to be able to search for the command I need so that I can carry out tasks without having to switch to and from NVDA’s documentation.
* As a user with arthritis, I want to be able to execute NVDA scripts without complex keyboard shortcuts that are painful to input.
* As a power user, I want to be able to search for NVDA scripts to help me quickly activate less frequently used actions.

### PR DESCRIPTION
**Pull request by nvdaes**
- **Initial commit to add ability to run commands from input gestures dialog**
- **Run onCancel in input gestures dialog just for certain categories**

### Link to issue number:
Fixes #17209

### Summary of the issue:
A commands palettte may be very useful, especially for new users, or people with mobility or cognitive disabilities.
### Description of user facing changes
The input gestures dialog has a Run button, to execute the selected command. 👍 
* Braille, touch and emulate gestures categories aren't supported. A message will report this when trying to run these commands.
* Many global commands will be run inmediately from the input gestures dialog. When this is not possible, i.e., when the dialog shouldn't be opened, for example, to get the status bar of the current application, the command will be saved to be run with a dedicated gesture (`NVDA+j` by default, after pressing the OK button. To run saved commands, the focus must be the same that the previous focus.
* For global plugins, app modules or custom classes, commands will be saved to be run later. This may not be needed in all cases, but we don't know if this will be necessary, so it will be done for all these cases.
### Description of development approach

A Run button with an event to run commands has been added.
Script categories, class names and gesture classes are used to determine if the command should be run inmediately, saved or if it shouldn't be supported.
Pieces of available add-ons (namely, commandHelper, and Global Extensions) have been consulted.
A dedicated gesture has been added to run the last saved command when the dialog has been closed.
### Testing strategy:
Tested manually.
### Known issues with pull request:
None.
### Code Review Checklist:

- [x] Documentation:
  - Change log entry
  - User Documentation
  - Developer / Technical Documentation
  - Context sensitive help for GUI changes
- [x] Testing:
  - Unit tests
  - System (end to end) tests
  - Manual testing
- [x] UX of all users considered:
  - Speech
  - Braille
  - Low Vision
  - Different web browsers
  - Localization in other languages / culture than English
- [x] API is compatible with existing add-ons.
- [x] Security precautions taken.

@coderabbitai summary

### CODE REVIEW

**Comment by Adriani90** [comment]
Does this work properly with e.g. object navigation gestures or quick navigation in browse mode? And how about the mouse routing gesture?

**Comment by cary-rowen** [comment]
Hi @nvdaes 
Thanks for your work.

To be honest, I prefer the command palette like VS Code.
Perhaps, this PR should not use wording like command palette, since you are just adding new features to the input gesture dialog.

**Comment by nvdaes** [comment]
@cary-rowen , I've edited the pull request title.
I like VS Code commands palette. Anyway, I think we should use the input gestures dialog, since a palette like VS Code's, imo, has the drawback that the text typed to search is not reported easily, and with the filter edit box of the input gestures dialog we can manage it better. I've moved the run button to be the first one. Hope this improves the user experience. Comments are appreciated.

**Comment by nvdaes** [comment]
Adriani wrote:

 Does this work properly with e.g. object navigation gestures or quick navigation in browse mode? 

Not for now.

**Comment by XLTechie** [comment]
Honestly, while I think that the addition of a run button to the input gestures dialog is a good idea, I think this will not replace the command helper add-ons.

That is not @nvdaes's fault, as this is good work, but the user experience of the input gestures dialog is just not designed for this kind of usage.

If the user knows some keywords of a command, and wants a quick way to type those and then arrow down a list of related commands, then press enter on the found command: the Input Gestures dialog simply wasn't designed to give that experience.

**Comment by nvdaes** [comment]
@XLTechie , I agree about add-ons, which shouldn't be dropped. I think we should make the run button the default one, to be activated with Enter from the command list.
I have thought about just making a list of scripts, but I think we should preserve the tree, since a same script may have different effects deppending of the user gesture. An example may be scripts to speak the column corresponding with a number in a table. So, honestly I don't find a better way to work on this, but feedfback is welcome.

**Comment by XLTechie** [comment]
@nvdaes I agree about run as the default. This is a start on what is desired for sure, even if it doesn't get all the way there.

**Comment by nvdaes** [comment]
@XLTechie , now we can run commands from items (after expanding categories, selecting scripts or gestures, by pressing the space bar without moving the focus to the run button. In this way we can press Enter to activate the OK button, like always in this dialog.
So we can navigate objects, for example going to next repeating the space bar from the corresponding command.
I've tested in the Python console, and seems that in browse mode we can run commands too without leaving the dialog, i.e., with the input gestures dialog opened to be closed when we want. I'm thinking about storing also the foreground object and textInfo.CARET in gui.mainFrame, so we may perform many commands from the dialog, even, perhaps, reporting the window title.

**Comment by nvdaes** [comment]
For reviewers, my current approach is to store variables like focus, navigator object, foreground etc in the input gestures dialog. This is similar to the Python console: if the dialog is open with a keystroke, not using NVDA's menu, the variables will correspònd to snapshots outside the gui.mainFrame.
Also, for appModules, scripts need to be run in the app, so seems that in this (and probably other cases), the dialog needs to be closed. In other cases, like objet navigation, seems that we can run several scripts from the dialog, and also to change settings, for example toggling booleans like checkboxes. For me this is very convenient.

**Comment by CyrilleB79** [comment]
Hi Noelia

I have not yet tested this PR.

For my personal use, I'll probably continue to use Command Helper which offers more possibilities as indicated in #17209 (e.g. https://github.com/nvaccess/nvda/issues/17209#issuecomment-2376655053).

Though, I'd like to comment on this issue, because I am interested by the subject and have just worked on this topic for Command Helper add-on.

Your implementation isn't probably able to run all the listed scripts. I have faced some issues in Command Helper add-on, that I have tried to fix in https://github.com/javidominguez/commandHelper that has just been merged. You may have a look.

In `scriptHandler._yieldObjectsForFindScript, `you have the list of all possible scriptable objects:
* Gesture specific scriptable object (emulated keys)
* Global plugins
* App module
* Braille display
* Vision enhancement provider
* Tree interceptor
* Focused NVDAObject
* Focus ancestors
* Configuration profile activation scripts
* Global commands

I'd request that you indicate in the description of this PR if some of them are not supported and why.

Also, you should test more complex cases such as NVDA Dev & Test Toolbox add-on (e.g. "Toggles the stack trace log when the speech function is called."). The script is not defined in the "ndtt" global plugin but in one of the mother class it is inheriting from, so I guess the current implementation of this PR would not work? (not tested myself)

**Comment by nvdaes** [comment]
Hi Cyrille:
I'll mention some of the available add-ons, indicating that this PR is not intended to replace them. Also, I'll indicate what and what not is supported.
For now, globalCommands should generally be supported, ass well as AppModule scripts, GlobalPlugin scripts and scripts in focused objects. Also scripts available in the Profile configuration category like activating and deactivating profiles.
Braille scripts are generally supported, but I think I'll disable input and scripts activated with routing keys, not working now. I'm thinking when the dialog should or not be closed before running scripts.
For AppModules, GlobalPlugins and focused object, I think we should close the dialog in case some scripts needs it, for example if a script may consist in selecting text or send chars etc. Since we aren't sure, it's better to close the dialog.
For configuration profile category, we need to close it since an NVDA dialog cannot be active to run them.
I may request you help to test the Toolbox add-on.

**Comment by nvdaes** [comment]
@seanbudd , since you added the product decision label, i'll wait until your guidance before working on this.
Imo, a controversial point is if the dialog should be always closed before running commands or not, but sometimes it would be useful not to close it, for example to facilitate object navigation.
I think that qukck navigation keys may also be used in browse mode documents without closing the dialog. I tested it locally and this worked, but this may not be a good experience.
If dialog is closed just sometimes, the run button should indicate it with a different label or something.
Also, I don't think that speech should be canceled when the dialog is closed, but certainly this may be also controversial.

**Comment by XLTechie** [comment]
@nvdaes I don't have any great opinions on this, but regarding quick nav for browse mode: the continuous use of those features are more reasonably handled by the Elements List dialog. So maybe you don't need to keep it open for quick nav commands, since someone needing to do a lot of that should be encouraged to use the elements list anyway, if they can't remember the quick nav commands.

**Comment by nvdaes** [comment]
Thanks @XLTechie I think that having this dialog open while navigating, for example, by list items may cause a waird experience, listening list items and seeing an open dialog.
But for example, to report the window title, I don't know if the dialog should be closed.

**Comment by CyrilleB79** [comment]
To NV Access team (@seanbudd, @SaschaCowley):
The proposed design in this PR is to add a "Run" button in the input gesture dialog to execute the selected script.
This may be handy in many cases and the advantage with this PR is that it is more easy to implement than another command palette-like solution.
Though as seen in the questions opened in this PR as well as in the discussions in #17209, this PR does not address all the use cases of a command palette.
Thus,, even if your decision is finally to accept the design of this PR, I'd keep #17209 open for a potential more general command palette solution.

**Comment by nvdaes** [comment]
@CyrilleB79 , I think that theissue may be closed or keept open deppending on the final implementation, which maybe improved with precisse guidance about the desired design.
If some cases are not covered, they can be discussed here to try to address them if possible.

**Comment by seanbudd** [comment]
Hi - we're just waiting on a final UX design proposal before we decide whether we accept this. Please mark as ready for review when you think its ready

**Comment by nvdaes** [comment]
Sean wrote:

 Please mark as ready for review when you think its ready

OK, then I'll continue working on this, maybe asking some users of the spanish community on several mailing lists since they may not read this repo, and I'll mark as ready when appropriate waiting for your feedback too.

**Review by CyrilleB79 — COMMENTED** [review]
Here are some little comments while reading the code.

I'll have to provide more general comments later and after having tested the branch. I can tell though that I am a bit concerned with the chosen user experience. I will write something later when I can.

**Comment by nvdaes** [comment]
@CyrilleB79 , thanks for your review.
In fact, log.info is for debugging.
Do you think that emulate gestures should be saved to be run with NVDA+j after closing the dialog? Otherwise, if you have suggestions for the presented message, please let me know.
I'll try to fix the issue with AppModule classes, and then I'll accept your suggestions regarding log.debug.
About the user experience, I'm open to suggestions.

**Comment by nvdaes** [comment]
Also, for mouse users I'm thinking about providing a button or a configuration option to run the script after closing the dialog, automatically, without pressing NVDA+j.
I thought about this configuration option previously, but I requested a review with a proposed design to see if this would be accepted or not.

**Comment by seanbudd** [comment]
Thanks for your work so far @nvdaes . After further internal discussions, we don't think this UX approach is going to be feasible or appropriate. Instead, we really need a virtual command pallette interface (#17209 ) for the UX to be intuitive and useful to users.

**Pull request closed without merging**
