### PR TITLE
Rewording in Input Gestures

### LINKED ISSUE #10301: Input gesture name for NVDA+b command is not obvious
### Is your feature request related to a problem? Please describe.

A user asked what the command was called that was invoked with NVDA+b as they could not find it in the Input Gestures dialog.

In the User guide, it is listed as:
Name: Read active window
Description: reads all the controls in the currently active window (useful for dialogs)

In the Input Gestures dialog, it is "Speaks the current foreground object".

### Describe the solution you'd like

Change the description in the Input Gestures dialog to something like "Reads active window" or "Reads all controls in the active window".

Aside from anything else, the current name is not actually correct as it does read the whole active window and not the active object (open WINVER, leave the focus on the OK button and press NVDA+B - it reads the dialog even though the active object, is that OK button).

### LINKED ISSUE #10814: Update description for Revert Configuration in Input Gestures dialog
### Is your feature request related to a problem? Please describe.

The text for resetting configuration in NVDA's input gestures dialog is: "Pressing once reverts the current configuration to the most recently saved state. Pressing three times reverts to factory defaults."

In the menu, we use "Revert to saved configuration" and "Reset configuration to factory defaults".

Someone searching input gestures for "reset configuration" would not find it.

### Describe the solution you'd like

Update the second sentence:  "Pressing three times reverts to factory defaults." to use the word reset rather than revert ("Pressing three times resets to factory defaults.")

### PR DESCRIPTION
**Pull request by ehollig**
### Link to issue number:
Fixes #10814 
Fixes #10301

### Summary of the issue:
Someone searching input gestures for "reset configuration" would not find the keystroke for resetting configuration in NVDA's input gestures dialog because the word reset is not used in the description.

Also, the shortcut key NVDA+B (speakForeground), in the input gestures dialog has a description that does not align with the user guide. Someone searching for this script using keywords that is present in the user guide will not be able to find this keystroke.

### Description of how this pull request fixes the issue:
Update the word reset in the input gestures dialog for the reset configuration script so it now says:
Pressing three times resets to factory defaults

Also updated the script description for speakForeground so it aligns with the user guide and now says:
Reads all controls in the active window

### Known issues with pull request:
None known

### Change log entry:
A few scripts have been clarified in the input gestures dialog

### CODE REVIEW

**Comment by lukaszgo1** [comment]
@ehollig When modifying scripts it is a good practice to convert them to script decorator.

**Comment by josephsl** [comment]
Hi, I think it might be helpful to put a source code level comment in there so we can investigate this further in coming weeks. Thanks.

**Comment by lukaszgo1** [comment]
While commend at the top of globalCommands would be helpful indeed, it should also be added to the contributing page on the wiki IMO.

**Comment by lukaszgo1** [comment]
@ehollig Are you planning to work further on this one?

**Comment by ehollig** [comment]
I would like to work further on this one, however I am not sure how to proceed or why AppVeyorBot failed.

**Comment by josephsl** [comment]
Hi,

After merging latest master, you must do the following in order:

scons source (optional but highly recommended)
scons tests
scons lint base=origin/master

For the latter two, read the output carefully and fix issues. Run the item again until no errors are found, then move onto the next item.

Thanks.

**Review by feerrenrut — APPROVED** [review]
I'll look at fixing the appveyor build failure.

**Pull request merged**
