### PR TITLE
Option in document formatting dialog to enable/disable reporting of comments #5108

### PR DESCRIPTION
**Pull request by LeonarddeR**
This issue has been open for a while now and I noticed I never created a pr for it. This adds an option to the document formatting dialog to report comments. I also fixed some code inconsistencies with some checkboxes.

### CODE REVIEW

**Comment by michaelDCurran** [comment]
* There are extra changes that are unrelated here. I.e.  Code for the auto update checkbox in General settings, and report clickables in Document formatting settings... Those changes should be removed. 
* The user guide needs to be updated to mention the new report comments checkbox.

**Comment by leonardder** [comment]
I agree about unrelated code, although it improves consistency.
      Do you want me to create a separate pull request just for that
      code?
    
    
    Op 30-6-2016 om 4:03 schreef Michael
      Curran:
    
    
      
        There are extra changes that are unrelated here. I.e. Code
          for the auto update checkbox in General settings, and report
          clickables in Document formatting settings... Those changes
          should be removed. 
        The user guide needs to be updated to mention the new report
          comments checkbox.
      
      —
        You are receiving this because you authored the thread.
        Reply to this email directly, view
          it on GitHub, or mute
          the thread.

**Comment by michaelDCurran** [comment]
Definitely should be another pull request.

It is unclear exactly what was changed, especially when its in the 
context of something else unrelated.

Thanks

On 30/06/2016 3:56 PM, Leonard de Ruijter wrote:
>
>
>
>
>
> I agree about unrelated code, although it improves consistency.
> Do you want me to create a separate pull request just for that
> code?
>
>
> Op 30-6-2016 om 4:03 schreef Michael
> Curran:
>
>
>
> There are extra changes that are unrelated here. I.e. Code
> for the auto update checkbox in General settings, and report
> clickables in Document formatting settings... Those changes
> should be removed.
> The user guide needs to be updated to mention the new report
> comments checkbox.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view
> it on GitHub, or mute
> the thread.
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub 
> <https://github.com/nvaccess/nvda/pull/6087#issuecomment-229566373>, 
> or mute the thread 
> <https://github.com/notifications/unsubscribe/ANf5ndXfNk-k6fXBHEPG1ZRCqbnESNJFks5qQ1qagaJpZM4I4W3T>.
>

-- 
Michael Curran
Executive Director, NV Access Limited
Phone: +61 7 3149 3306
Website: http://www.nvaccess.org/
Twitter: @NVAccess
Facebook: http://www.facebook.com/NVAccess

**Comment by leonardder** [comment]
I updated the branch.
    I noticed that editor revisions is without a capital "E" in the user
    guide. Do you want me to file a separate pull request for this as
    well?

**Comment by michaelDCurran** [comment]
Yes please.




On 30/06/2016 9:51 PM, Leonard de Ruijter wrote:
>
>
>
>
>
> I updated the branch.
> I noticed that editor revisions is without a capital "E" in the user
> guide. Do you want me to file a separate pull request for this as
> well?
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub 
> <https://github.com/nvaccess/nvda/pull/6087#issuecomment-229636513>, 
> or mute the thread 
> <https://github.com/notifications/unsubscribe/ANf5nXZAPdzTGuxCJBqkreCzy18eWiUYks5qQ62xgaJpZM4I4W3T>.
>

-- 
Michael Curran
Executive Director, NV Access Limited
Phone: +61 7 3149 3306
Website: http://www.nvaccess.org/
Twitter: @NVAccess
Facebook: http://www.facebook.com/NVAccess

**Comment by nvaccessAuto** [comment]
Incubated in 2b66ef81e2fa57e1ba729a1f547b682381f0f664.

**Pull request merged**
