### PR TITLE
Python 3: use floor division (//) to obtain integer results from division operations

### LINKED ISSUE #9641: Python 3: division operator differences between classic and the new division
### Steps to reproduce:
Run Python 2 and 3 interpreters and try performing division operation such as "3 / 2" and "3 // 2".

### Actual behavior:
Errors such as not being converted to integer in Python 3.

### Expected behavior:
No errors.

#### NVDA installed/portable/running from source:
Source and installed

#### NVDA version:
master.17384

#### Windows version:
Windows 10 Version 1903

#### Name and version of other software in use when reproducing the issue:
N/A

#### Other information about your system:
N/A

#### Does the issue still occur after restarting your PC?
Yes

#### Have you tried any other versions of NVDA? If so, please report their behaviors.
Yes - source code version of Python 3 NVDA

### Context:
Division operator semantics has changed between Python 2 and 3:

* /: floor division for integers in Python 2, regular division in Python 3
* //: integer division for both Python 2 and 3.

There are places in NVDA that will expect integers via single slash operator when in fact it will return float in Python 3. These include Windows Console handler, GUI, mouse handler and others. Thus either standardize around calling int, or use two slashes. Note that this must be tested extensively to make sure regressions are not introduced.

Thanks.

### PR DESCRIPTION
**Pull request by josephsl**
### Link to issue number:
Fixes #9641 

### Summary of the issue:
Python 2 and 3 shows different behavior for traditional division (/) operator; classic versus true.

### Description of how this pull request fixes the issue:
Use floor division (//) operator to obtain integers because Python 3 will perform true division when only one slash (/) is written, which will result in returning floats instead of integers.

### Testing performed:
Tested with both Python 2 and 3 - Python Console, Python interpreters.

### Known issues with pull request:
There might be other cases not covered in this pull request, and in some cases, erroneous integer result may appear due to use of floor division (moving to the left side of the number line, especially for negative numbers).

### Change log entry:
None

### CODE REVIEW

**Review by michaelDCurran — APPROVED** [review]

**Review by feerrenrut — COMMENTED** [review]
Great!

**Comment by josephsl** [comment]
Hi,

Found a runtime problem: SAPI5 synth did not work because percentage to pitch/rate returns float when it should be returning integers. This has been corrected (same branch).

Thanks.

**Comment by feerrenrut** [comment]
>  This has been corrected (same branch).

@josephsl could you create a new PR for this?

**Comment by josephsl** [comment]
Hi,

Resolved and merged into py3 staging by Mick not long ago.

The other day I came across more int/float conflicts, which I'll do my best to resolve them in a separate PR.

Thanks.

**Pull request merged**
