### PR TITLE
Ensure that NVDA can get file version information for binaries in system32 on 64-bit versions of Windows

### PR DESCRIPTION
**Pull request by lukaszgo1**
### Link to issue number:
None, discussion in #12852

### Summary of the issue:
NVDA can retrieve information for a binary file such as application name and version from which given appModule has been created. While they're not shown to the user directly they can be inspected as part of the developer info - also NVDA relies on them for various stuff internally. For binaries placed in system32 (such as `LogonUI.exe`) this process fails on 64-bit versions of Windows as follows:
```
  File "appModuleHandler.pyc", line 413, in _get_productName
  File "appModuleHandler.pyc", line 405, in _setProductInfo
  File "appModuleHandler.pyc", line 363, in _getExecutableFileInfo
  File "fileUtils.pyc", line 48, in getFileVersionInfo
RuntimeError: The file C:\Windows\System32\consent.exe does not exist
```
This occurs because NVDA is a  32-bit process and when trying to access `C:\Windows\System32` Windows redirects it to `C:\Windows\SysWOW64` and some binaries aren't duplicated there.
### Description of how this pull request fixes the issue:
For a duration of  retrieving file info for a binary placed in `system32` and when running on a version of Windows which have both `system32` and `SysWOW64` WOW64 redirection is disabled. While at it I've  removed deprecated `shlobj.SHGetFolderPath` and replaced it with `SHGetKnownFolderPath` and removed unused function from the config module ((while not strictly related it relied on `SHGetFolderPath`).
### Testing strategy:
On 64-bit version of Windows installed self signed build from this branch, enabled service debug, started an application with the admin privileges, inspected developer info for the UAC screen and made sure that for `consent.exe` file version and file name can be retrieved. Made sure that this code is not executed on 32-bit version of Windows and that file version info can still be retrieved there.
### Known issues with pull request:
- Breaks backward compatibility - it is unlikely to be merged before 2022.1 so not a big deal IMO.
### Change log entries:

Bug fixes
- NVDA can report application name and version for binaries placed in system32 when running under 64-bit version of Windows.

For Developers
- `config.getSystemConfigPath` has been removed - there is no replacement
- `shlobj.SHGetFolderPath` has been removed - please use `shlobj.SHGetKnownFolderPath` instead
### Code Review Checklist:

- [X] Pull Request description:
  - description is up to date
  - change log entries
- [X] Testing:
  - Unit tests
  - System (end to end) tests
  - Manual testing
- [ ] API is compatible with existing add-ons.
- [X] Documentation:
  - User Documentation
  - Developer / Technical Documentation
  - Context sensitive help for GUI changes
- [X] UX of all users considered:
  - Speech 
  - Braille
  - Low Vision
  - Different web browsers
  - Localization in other languages / culture than English

### CODE REVIEW

**Comment by lukaszgo1** [comment]
@leonardder  Given our discussion in #12852 you may be interested in reviewing this.

**Review by LeonarddeR — CHANGES_REQUESTED** [review]

**Review by seanbudd — COMMENTED** [review]
Thanks @lukaszgo1

**Comment by michaelDCurran** [comment]
Although Wow64DisableWow64FsRedirection only affects the current thread (which at least means we don't need to worry about concurrency issues), the more work we do with redirect disabled hightens the chance that Windows or a component in this thread may try to load a dll from system32. And while redirection is disabled, this would be the wrong system32. Thus per the documentation of Wow64DisableWow64FsRedirection, it is strongly recommended to only do this around the lowest API calls possible.
Thus, rather than wrapping _setProductInfo, it may be better as a with-statement around the call to getFileVersionInfo in _getExecutableFileInfo.
I'm assuming that code inside _getImmersivePackageInfo does not require redirection to be disabled?

**Review by seanbudd — APPROVED** [review]

**Comment by seanbudd** [comment]
@michaelDCurran  - thoughts on the updated approach? I've reviewed the code otherwise

**Review by michaelDCurran — APPROVED** [review]

**Pull request merged**
