### PR TITLE
In browse mode, it is now possible to skip past landmarks if there is one using the skip to end/beginning of container command.  #5482

### LINKED ISSUE #5482: add keystroke to jump to the end of landmarks
Rationale: Sometimes, mostly in news sites, an aside landamark is found inside a main landmark. That makes the reading experience rather unpleasant. Adding a keyboard command to jump to the end of a landmark would improve the reading experience. Maybe it will make the announcement of the ending would make nVDA too chatty thoguh.

### PR DESCRIPTION
**Pull request by derekriemer**
If there is a container inside of a landmark, this command retains the behavior of only skipping to the end of the container.
This needs testing in edge, and look over from someone who knows more about browse mode. Also, I'm not sure why there are two methods, one in virtualBuffers/**init**.py and browseMode.py, so if someone can check my code for sanity, that would be great.

Fixes #5482.

### CODE REVIEW

**Comment by derekriemer** [comment]
I'll fix this one bug (I can't seem to test this code in browse mode).

**Comment by derekriemer** [comment]
And my previous id10t error has been resolved and I rebased that ugliness away.

**Comment by derekriemer** [comment]
Hi:
Needs code review when time is found.
Thanks.

**Comment by derekriemer** [comment]
Hi: This is ready for review when time allows. It should be a fairly quick bang for the buck.

**Review by jcsteh — COMMENTED** [review]
This looks pretty good; thanks.

Can you detail what testing you performed? If you haven't already, it'd be good if you can test this in Edge, Adobe Reader and Microsoft Word (the latter two don't support landmarks).

[**@derekriemer**](https://github.com/derekriemer) commented on [Oct 17, 2016, 10:09 PM GMT+10](https://github.com/nvaccess/nvda/pull/6474#issue-183398940 "2016-10-17T12:09:42Z - Replied by Github Reply Comments"):
> I'm not sure why there are two methods, one in `virtualBuffers/__init_.py` and browseMode.py, so if someone can check my code for sanity, that would be great.

Before browseMode was generalised, only the VirtualBuffer implementation existed. Because we can easily get a TextInfo for a ControlField in buffers, it's easier to just walk the fields. When it got generalised, this wasn't an option, so we invented the "container" node iteration type. It was easier to just leave buffers as is rather than implementing this new node iteration type. Long story short: updating both as you have done is correct.

**Comment by jcsteh** [comment]
Oh, and the VirtualBuffer implementation is actually more efficient, since it can check for containers and landmarks in the same walk... but there's no abstract base equivalent.

**Comment by derekriemer** [comment]
I tested this both in adobe reader, word, and in edge. I can't think of even one accessible flash app, I'm sorry, but I can't really test this there. It worked in the above 3 situations, however, I'm gonna push something for edge which will use the fields because that's faster.

**Comment by derekriemer** [comment]
@jcsteh Is it even possible to get a UIA object from a controlField? I don't think so. If not, is there a better way to get the container than the default behavior?

**Comment by jcsteh** [comment]
No. Just let Edge use the base functionality as it does now.

**Comment by derekriemer** [comment]
@jcsteh Is it even possible to get a UIA object from a controlField? I don't think so. If not, is there a better way to get the container than the default behavior?Okay. The testing you asked for was completed.

**Comment by derekriemer** [comment]
I tested in firefox, chrome, IE, and edge, and adobe and word. I used several test pages such as nvaccess.org, my site (Derekriemer.org), and other sites with and without landmarks. I also tested nested landmarks, and lists within landmarks. 
I verified that 
1. If there  is a list or table in a landmark, comma jumps out of the list, and shift+comma jumps to the list beginning.
2. If there is a list with a landmark in it, the keys jump out of the landmark first, if you are in one, or out of the list otherwise.
3. If I am before a landmark, in a container, comma jumps out of one and skips the landmark.

One weird thing, I am not sure how to remove.
NVDA says bottom if I press comma and I land on the bottom of a page.

**Review by jcsteh — APPROVED** [review]

**Comment by jcsteh** [comment]
Sorry it took me so long to get back to this.

**Comment by derekriemer** [comment]
Hmm, why did it add that to a already released milestone?

**Comment by jcsteh** [comment]
A change on our server didn't get applied correctly. I've updated the release documentation so that doesn't happen again. :)

**Pull request merged**
