### PR TITLE
Add the ClientToScreen function from user32.dll to the winUser module

### PR DESCRIPTION
**Pull request by LeonarddeR**
For a @BabbageCom project, I needed the ClientToScreen function from user32.dll which wasn't yet available in the winUser module. So, I decided to at it to winUser for ease of use. Might be handy for #4703 as well, cc @dkager

### CODE REVIEW

**Comment by dkager** [comment]
I think I tried that function, but it still failed to be reliable. Something odd going on with high-DPI.

**Comment by leonardder** [comment]
I assume you tried this function in tandem with windowUtilslogicalToPhysicalPoint as well?

**Comment by dkager** [comment]
Yes, and pretty much every permutation on that scheme.

**Comment by dkager** [comment]
Although it doesn't fix my Notepad++ problem I would say this looks good and is useful to have.

**Comment by leonardder** [comment]
Will be superseded by another pr if #7444 gets merged into master. Closing

**Pull request closed without merging**
