### PR TITLE
Fix more cases of grand child window focus failures

### LINKED ISSUE #15432: NVDA doesn't read contents of grandchild windows (Win32)
### Steps to reproduce:
1. Open a Win32 application which makes use of parent/child-window relationships.
2. Open a child window of the main window (in this case a non-modal dialog).
3. Open a child window of the child window of the main window (grandchild window) (in this case a floating pane).

### Actual behavior:
NVDA does not follow focus or speak in response to events from the grandchild window.

### Expected behavior:
NVDA works in the grandchild window as though it’s a normal window.

### NVDA logs, crash dumps and other attachments:
Speech logs when opening a popup menu which is a child window of the main window:
```
Output Type  combo box  Ext. Out  collapsed
Ext. Out
```

Speech logs when opening an identical popup window which is a grandchild of the main window.
```
Language Selection  combo box  US-English  collapsed
```

In both cases, I pressed the “Enter” key to expand the focused combo box. NVDA does not say anything when navigating within the grandchild popup window. Both Narrator and JAWS work fine with these windows.

It’s clear to me that this is an issue of the popup menu being a grandchild, because when windows are hard-coded to not have parent/child relationships, NVDA reads the contents as expected. However, the application in question relies on the parent/child relationships of the Win32 framework, so this is not an acceptable solution.

#### NVDA installed/portable/running from source:
Installed

#### NVDA version:
2023.1

#### Windows version:
Windows 11 Version 22H2

#### Name and version of other software in use when reproducing the issue:
Non-public prototype.

#### Does the issue still occur after restarting your computer?
Yes

#### Have you tried any other versions of NVDA? If so, please report their behaviors.
I have tested with the latest release version, as well as running a recent commit on `master` locally. The behavior is the same.

#### If NVDA add-ons are disabled, is your problem still occurring?
I don’t have any NVDA add-ons installed.

#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA’s tools menu?
Yes, the COM Registration Fixing Tool does not resolve this issue.

### PR DESCRIPTION
**Pull request by LeonarddeR**
### Link to issue number:
Closes #15432

### Summary of the issue:
Some events for grand child windows in applications seem to be ignored.

### Description of user facing changes
Focus changes are reported in these cases.

### Description of development approach
Generalize the workaround that was expanded for Edge in #15300 

### Testing strategy:
- [x] Test #15432

### Known issues with pull request:
None known

### Change log entries:
Bug fixes
- NVDA no longer ignores focus changes when a nested window (grand child window) gets focus. (#15432)

### Code Review Checklist:

- [x] Pull Request description:
  - description is up to date
  - change log entries
- [x] Testing:
  - Unit tests
  - System (end to end) tests
  - Manual testing
- [x] API is compatible with existing add-ons.
- [x] Documentation:
  - User Documentation
  - Developer / Technical Documentation
  - Context sensitive help for GUI changes
- [x] UX of all users considered:
  - Speech 
  - Braille
  - Low Vision
  - Different web browsers
  - Localization in other languages / culture than English
- [x] Security precautions taken.

### CODE REVIEW

**Comment by josephsl** [comment]
Hi, can this also explain a recent problem in Windows 11 start menu where search results are not announced by NVDA due to use of MS Edge Webview 2 component from Bing (separate issue)? Thanks.

**Comment by leonardder** [comment]
I don't know that issue, but if you could test drive it, that would be most helpful.

**Comment by seanbudd** [comment]
Is this ready for review now that #15432 has been confirmed as fixed? It would be nice to get this into alpha for testing before a final beta3 early next week

**Comment by leonardder** [comment]
Sure, Go ahead.

**Comment by seanbudd** [comment]
any suggestions on a changelog entry?

**Comment by leonardder** [comment]
I just updated the initial description.

**Comment by seanbudd** [comment]
Thanks

**Review by seanbudd — APPROVED** [review]

**Pull request merged**
