### PR TITLE
Collapsible sections for readme for usablity

### PR DESCRIPTION
**Pull request by CosmicVolcano**
### Change log entries: Changes
New features
Changes
Bug fixes
For Developers

### Code Review Checklist:

- [x] Pull Request description:
  - description is up to date
  - change log entries
- [x] Testing:
  - Unit tests
  - System (end to end) tests
  - Manual testing
- [x] API is compatible with existing add-ons.
- [x] Documentation:
  - User Documentation
  - Developer / Technical Documentation
  - Context sensitive help for GUI changes
- [x] UX of all users considered:
  - Speech 
  - Braille
  - Low Vision
  - Different web browsers
  - Localization in other languages / culture than English

### CODE REVIEW

**Comment by seanbudd** [comment]
Rather than hiding important information, I would suggest splitting out some of the content to `./devDocs/`, such as building NVDA and developing NVDA locally.

**Comment by seanbudd** [comment]
It would be ideal to create a new issue to discuss this first

**Comment by Brian1Gaff** [comment]
This to me sounds like it needs to be a toggle to stop confusing people.

Of course it presupposes that all web sites are created logically, which of 
course they are  grin... Brian

***@***.***
Sent via blueyonder.
Please address personal E-mail to:-
***@***.***, putting 'Brian Gaff'
in the display name field.
Newsgroup monitored: alt.comp.blind-users
----- Original Message ----- 
From: "CosmicVolcano" ***@***.***>
To: "nvaccess/nvda" ***@***.***>
Cc: "Subscribed" ***@***.***>
Sent: Wednesday, May 25, 2022 3:46 AM
Subject: [nvaccess/nvda] Collapsible sections for readme for usablity (PR 
#13734)

**Comment by CyrilleB79** [comment]
The drawback of collapsible section is also that searching for an information in a collapsed section give no result.
So IMO, it's not a good way to present the information.

Personally, I have never been embarassed by the amount of information on this page. It is always easy to hit 'h' to navigate quickly in the document structure.

But if we want to reduce the page size anyway, @seanbudd's suggestion to split some parts of the file in more specific        pages seems better to me.

**Comment by seanbudd** [comment]
Please open a new issue to propose moving content out from the README

**Pull request closed without merging**
