### PR TITLE
Read config path and log file path as unicode

### LINKED ISSUE #7113: When the -c option is used when starting NVDA user configuration can not be saved
Steps to reproduce:

- Open a command prompt and cd to the nvda.exe directory.
- start nvda with `nvda.exe -c "C:\myTemp"
- open the nvda menu and select "save configuration"

An error is shown "Could not save configuration - probably read only file system".

Regression caused by atomic rename/write fix. Config path is unicode without `-c`, but when `-c` is passed, the config path is ANSI. fileUtils assumes path is always Unicode.

### PR DESCRIPTION
**Pull request by feerrenrut**
Fixes #7113
Set the type on `argParse` to `unicode`. This will probably stop working in python 3. See https://codereview.stackexchange.com/questions/124434/get-argument-as-unicode-string-from-argparse-in-python-2-and-3

Now the configuration path, and the log file path are provided to NVDA as unicode strings.

To test the configuration path, I opened nvda with `pythonw.exe nvda.pyw -c "C:\tmp\nvda_user_dir"` and ensured that I could now change and save the config without error and the changes would still be present when exiting and restarting with the same command.

To test the logfile path, I ran nvda with `pythonw.exe nvda.pyw -f "C:\tmp\nvda_user_dir\nvdalog.log"` and ensured that the file was created and contained the log information that matched my behaviour with nvda.

### CODE REVIEW

**Review by jcsteh — COMMENTED** [review]
I really briefly looked at argparse and I don't see explicit support for unicode conversion. Therefore, I very much suspect that non-ASCII paths (which can happen on non-English systems) are going to fail. Try something like this:

```
pythonw.exe nvda.pyw c:\users\someUser\nvda•
```

The • character is intentional. I'm guessing you'll get an encoding exception.

If the `type` for arguments takes a callable (as I think it does), you could pass your own little function to decode according to the ANSI locale on the system. This is not guaranteed to work for all Unicode strings, but it should work most of the time and we already rely on this elsewhere:

```
def decodeMbcs(string):
    return string.decode("mbcs")
# Now pass decodeMbcs as the type for arguments.
```

**Comment by feerrenrut** [comment]
Yep, I have tested using the approach you suggested. This will now handle the paths with non-ASCII characters.

**Review by jcsteh — APPROVED** [review]

**Comment by jcsteh** [comment]
@feerrenrut, can you please review ? Tested as follows:

> ```
> >>> with fileUtils.FaultTolerantFile("foo.txt") as f:
> ...  f.write("foo")
> ... 
> Traceback (most recent call last):
>   File "<console>", line 1, in <module>
>   File "C:\Python27\lib\contextlib.py", line 17, in __enter__
>     return self.gen.next()
>   File "C:\Users\jamie\src\nvda\source\fileUtils.py", line 31, in FaultTolerantFile
>     raise TypeError("name must be unicode")
> TypeError: name must be unicode
> >>> with fileUtils.FaultTolerantFile(u"foo.txt") as f:
> ...  f.write("foo")
> ... 
> >>> file('foo.txt').read()
> 'foo'
> ```

**Comment by feerrenrut** [comment]
yep, looks good. As we discussed, this is quite unlikely (but possible) to cause a very serious error. But the new error message is much more clear than the error you would get otherwise:

```
Traceback (most recent call last):
  File "<console>", line 2, in <module>
  File "contextlib.pyc", line 24, in __exit__
  File "fileUtils.pyc", line 38, in FaultTolerantFile
WindowsError: [Error 2] The system cannot find the file specified.
```

**Comment by jcsteh** [comment]
@MichaelDCurran, @feerrenrut and I all agreed this should be merged into master before the translation freeze despite it not being fully incubated, as it it is a p1 fix which needs to be included in the release.

**Pull request merged**
