### PR TITLE
Update liblouis to 3.18.0

### PR DESCRIPTION
**Pull request by AAClause**
### Link to issue number:
None

### Summary of the issue:
Liblouis 3.18.0 has just been released.

### Description of how this pull request fixes the issue:
Updates liblouis to 3.18.0 which adds support for many new languages and [other awesome things](https://github.com/liblouis/liblouis/releases/tag/v3.18.0).

### Testing strategy:
- Ran from sources.
- Tested new braille tables (input and output).

### Known issues with pull request:
None

### Change log entries:
Section: Changes

```
- Updated liblouis braille translator to [3.18.0 https://github.com/liblouis/liblouis/releases/tag/v3.18.0]. (#12526)
  - New braille tables: Bulgarian grade 1, Burmese grade 1, Burmese grade 2, Kazakh grade 1, Khmer grade 1, Northern Kurdish grade 0, Sepedi grade 1, Sepedi grade 2, Sesotho grade 1, Sesotho grade 2, Setswana grade 1, Setswana grade 2, Tatar grade 1, Vietnamese grade 0, Vietnamese grade 2, Southern Vietnamese grade 1, Xhosa grade 1, Xhosa grade 2, Yakut grade 1, Zulu grade 1, Zulu grade 2
```

### Code Review Checklist:

- [x] Pull Request description is up to date.
- [x] Unit tests.
- [x] System (end to end) tests.
- [x] Manual testing.
- [x] User Documentation.
- [x] Change log entry.
- [x] Context sensitive help for GUI changes.
- [x] UX of all users considered:
  - Speech 
  - Braille
  - Low Vision
  - Different web browsers

### CODE REVIEW

**Review by LeonarddeR — APPROVED** [review]

**Comment by aaclause** [comment]
There are several grade 2 tables that are not declared as contracted. I think these are mistakes. Here are the corresponding lines (`git blame` format):

```
ec877feab2 (Leonard de Ruijter 2018-12-06 03:48:12 +0100 105) addTable("ar-ar-g2.ctb", _("Arabic grade 2"))
ec877feab2 (Leonard de Ruijter 2018-12-06 03:48:12 +0100 222) addTable("es-g2.ctb", _("Spanish grade 2"))
83738d7d91 (André-Abush Clause 2021-03-22 11:15:08 +0100 444) addTable("ur-pk-g2.ctb", _("Urdu grade 2"))
d1ba63ab8f (Leonard de Ruijter 2018-09-04 07:46:41 +0200 459) addTable("zhcn-g2.ctb", _("Chinese (China, Mandarin) grade 2"))
```

Should I make another Pull Request for that?

CC @leonardder

**Comment by Futyn-Maker** [comment]
Hello! Can it be included in NVDA 2021.1? Or Or is it too late?

**Comment by leonardder** [comment]
I'm afraid it's too late for that.

**Comment by seanbudd** [comment]
Thanks again, this looks like a great update! I noticed that the "PR description is up to date is unticked. Can you say why that is? Is it because we are uncertain of the following known issue:

>There are several grade 2 tables that are not declared as contracted. I think these are mistakes. 

@leonardder @aaclause - should we proceed with this given the raised issue?

>Hello! Can it be included in NVDA 2021.1? Or Or is it too late?

Sorry, this will have to wait until 2021.2.

**Comment by aaclause** [comment]
> @leonardder @aaclause - should we proceed with this given the raised issue?
That's my question :) Only 4 SLOC are affected but given that it is not related to liblouis 3.18 it's likely irrelevant in this PR (??).

Also I'd like to suggest to change the display names of some braille tables in the GUI, like this:

- Northern Kurdish grade 0 → Kurdish (Northern) grade 0
- Central Kurdish grade 1 → Kurdish (Central) grade 1
- Southern Vietnamese grade 1 → Vietnamese (Southern) grade 1

This way all Kurdish and Vietnamese tables would be gathered (currently scattered due to alphanumeric sorting). What do you think?

**Comment by seanbudd** [comment]
>That's my question :). Only 4 SLOC are affected but given that it is not related to liblouis 3.18 it's likely irrelevant in this PR (?).

Cool, I will wait to see what @leonardder thinks as well. 

>This way all Kurdish and Vietnamese tables would be gathered (currently scattered due to alphanumeric sorting). What do you think?

I agree, that would also be a good change. Might be worth noting that it differs to liblouis in a comment if that is the case.

**Comment by leonardder** [comment]
I think it would be best to merge this pr as is. @aaclause raises valid points and therefore it makes sense to address them, but preferably in a follow up.

**Review by seanbudd — APPROVED** [review]

**Pull request merged**
