### PR TITLE
liblouis 3.3.0: new and renamed Croatian tables, removed wrappers.c

### PR DESCRIPTION
**Pull request by josephsl**
### Link to issue number:
#7565 

### Summary of the issue:
New and renamed tables for Croatian

### Description of how this pull request fixes the issue:
New table: hr-g1.ctb for Croatian grade 1.
renamed hr.ctb to hr-comp8.utb for Croatian computer braille table.

### Known issues with pull request:
None.

### Change log entry:
New features: New braille translation table: Croatian grade 1.
Changes: upgraded liblouis braille translator to 3.3.0.

Note: this PR is blocked by a master PR for #7565 that allows NVDA to support liblouis 3.3.0 features.

Thanks.

### CODE REVIEW

**Comment by jcsteh** [comment]
Please update the liblouis submodule and readme.md as well. There's no reason to do this in a separate PR. Thanks.

**Comment by josephsl** [comment]
Hi, the reason for bringing up a master PR was in case someone was working on incorporating various improvements from liblouis 3.3.0, among them security enhancements. Thanks.

**Comment by jcsteh** [comment]
The security enhancements are in the liblouis code base, so all we need do
is upgrade. Thus, this PR just needs to update the submodule and the
readme, as well as making any build system changes necessary to build it
(but I suspect none are necessary).

**Comment by josephsl** [comment]
Hi, I’ll test the new release this week and report findings, and morph the PR accordingly. Thanks.

**Comment by josephsl** [comment]
Hi,

Wrappers.c is gone from liblouis, so looks like a code change is in order...

Thanks.

**Comment by leonardder** [comment]
@josephsl: Is this ready for review yet?

**Comment by josephsl** [comment]
Hi, feel free to review it (and also ask if @DKager wouldn’t mind taking a look as well). Thanks.

**Review by LeonarddeR — APPROVED** [review]
Looks good. Let's incubate this to test drive! :)

**Review by dkager — APPROVED** [review]
Looks good.
As a side note, it would be really neat to use the NMake script from liblouis instead of a separate scons script at some point.

**Pull request merged**
