### PR TITLE
Encapsulate IA2 relations constants

### PR DESCRIPTION
**Pull request by feerrenrut**
### Link to issue number:
None

### Summary of the issue:
IAccessible2 code that depends on fetching objects related to other objects uses these constants.
Since these values are strings, and not defined in an IDL file, we should encapsulate them in an
Enum.

### Description of how this pull request fixes the issue:
Encapsulate the constants in a Relations enum under IAccessibleHandler.

- Removed IA2_RELATION_FLOWS_FROM
- Removed IA2_RELATION_FLOWS_TO
- Removed IA2_RELATION_CONTAINING_DOCUMENT
- Replaced with IAccessibleHandler.RelationType enum

This is a compatibility breaking change, however it's not expected that many Addons use this code.

All internal usages of the constants have been updated:
- Double checked with `git grep -i IA2_RELATION_`
- The only remaining results are in C++ files.

### Testing strategy:
- Run locally
- System tests
- Usage on alpha prior to release of NVDA 2022.1

### Known issues with pull request:
Compatibility breaking change.

### Change log entries:
For Developers
`- IAccessibleHandler IA2_RELATION_* constants have been replaced with the IAccessibleHandler.RelationType enum.`

### Code Review Checklist:

- [x] Pull Request description:
  - description is up to date
  - change log entries
- [x] Testing:
  - Unit tests
  - System (end to end) tests
  - Manual testing
- [x] API is compatible with existing add-ons.
- [x] Documentation:
  - User Documentation
  - Developer / Technical Documentation
  - Context sensitive help for GUI changes
- [x] UX of all users considered:
  - Speech 
  - Braille
  - Low Vision
  - Different web browsers
  - Localization in other languages / culture than English

### CODE REVIEW

**Review by michaelDCurran — APPROVED** [review]

**Comment by michaelDCurran** [comment]
We currently define all the IA2 relation constants in NVDA ourself, as although they are defined in IAccessible2's accessibleRelation.idl, they are all separate constants, not referenced directly or indirectly by the IAccessible2 Library definition, thus never included in the type library, and therefore never exposed to NVDA via comtypes.
I suppose they really should have been wrapped in their own namespace block in the idl file, and then that namespace block should be mentioned by the library definition. 
I'm just mentioning this here to clarify why we do define the relation constants in NVDA.

**Comment by feerrenrut** [comment]
Thanks @michaelDCurran that is helpful to know. I guess we'll progress with this PR as it is, and consider getting that IDL changed?

**Comment by leonardder** [comment]
This breaks in Thunderbid:

```
error executing event: focusEntered on <NVDAObjects.IAccessible.mozilla.Mozilla object at 0x07481250> with extra args of {}
Traceback (most recent call last):
  File "eventHandler.pyc", line 284, in executeEvent
  File "eventHandler.pyc", line 98, in __init__
  File "eventHandler.pyc", line 105, in next
  File "eventHandler.pyc", line 133, in gen
  File "NVDAObjects\__init__.pyc", line 394, in _get_treeInterceptor
  File "treeInterceptorHandler.pyc", line 25, in getTreeInterceptor
  File "virtualBuffers\gecko_ia2.pyc", line 262, in __contains__
  File "virtualBuffers\gecko_ia2.pyc", line 238, in _iterIdsToTryWithAccChild
  File "virtualBuffers\gecko_ia2.pyc", line 196, in _getEmbedderFrame
  File "comtypes\__init__.pyc", line 851, in __call__
  File "monkeyPatches\comtypesMonkeyPatches.pyc", line 32, in __call__
ctypes.ArgumentError: argument 1: <class 'TypeError'>: unicode string expected instead of RelationType instance
```

**Comment by feerrenrut** [comment]
@leonardder a fix is in progress (see PR #13112). If possible, please test the [PR build](https://ci.appveyor.com/api/buildjobs/tspmub36g6k2j93m/artifacts/output%2Fnvda_snapshot_pr13112-24297%2Cdd0b7748.exe), thanks!

**Pull request merged**
