### PR TITLE
Update Bengali characterDescriptions.dic

### PR DESCRIPTION
**Pull request by Oymate**
### Link to issue number:
N/A added missing entries

### Summary of the issue:
Entries were missing 

### Description of how this pull request fixes the issue:
These entries fulfills the alphabet word list.

### Change log entries:
Bug fixes

### Code Review Checklist:

- [x] Pull Request description is up to date.
- [x] Unit tests.
- [x] System (end to end) tests.
- [x] Manual testing.
- [x] User Documentation.
- [ ] Change log entry.
- [x] Context sensitive help for GUI changes.
- [x] UX of all users considered:
  - Speech 
  - Braille
  - Low Vision
  - Different web browsers

### CODE REVIEW

**Comment by gregjozk** [comment]
Hello,

please first read carefully articles about translation on NVDA's github wiki and then join NVDA translation list where you can search existing Bengali maintainer if there is someone. He/she would incorporate your suggested changes into appropriate file. if there is no one, then you can become a bengali maintainer and start to translate NVDA, when you would resieved and accept assembla invitation sent to you by one of admins of translation list and system.
hope, it helps.

**Comment by lukaszgo1** [comment]
It seems Bengali is sort of a special case - see #4410  especially comments 5 and 13. To recap there is no interest in translating NVDA into Bengali whereas there was demand to have Bengali letters reported so it was decided to commit these symbol files directly to Git as not to create unneeded work in the translations system.

**Comment by Oymate** [comment]
How much time do you think translating to Bengali would require? This software is advertised on Bangladesh gov site as a screen reading solution so this is worrying

**Comment by zstanecic** [comment]
Hi,

The translations proces is not something done once and for all. It is a process which lasts a long.

**Comment by Oymate** [comment]
Given the character description is already there, wouldn't it make more sense to merge them?

Side question: where can I find out how good espeak ng supports Bengali?

**Comment by CyrilleB79** [comment]
@Oymate, can you indicate the reason why you have closed this PR.
According to https://github.com/nvaccess/nvda/pull/12502#issuecomment-853309924, it seems it's a valid case to merge these modifications via GitHub and not via the SVN repo.
I am not qualified however to judge of the content of this PR, knowing nothing about Bengali language.

**Comment by Oymate** [comment]
@CyrilleB79 I mainly didn't keep this open, because the devs seems not interested to merge this unless someone does full work on speech synthesis in Bangla. It really won't be any different since the char description is already here just not updated.

**Comment by CyrilleB79** [comment]
@Oymate there has not yet been any comment from NVAccess core dev in this PR, just from contributors (even if some of them are quite active).
NVAccess priorize PRs as they wantand can . But being low priority does not mean uninteresting.
Also, NVAccess will review and merge PRs when they are set ready, i.e. not in draft state anymore. This PR is currently still in draft state.

**Review by seanbudd — APPROVED** [review]
Looks good to me. If there is interest in people translating Bengali in our standard translation system (likely, the new one we are working on), please raise a new issue.

**Comment by seanbudd** [comment]
Or contact the translations google group mailing list https://groups.io/g/nvda-translations

**Pull request merged**
