### PR TITLE
Fix message hooking regression

### LINKED ISSUE #14784: Regression of #14759: Unable to use Sogou Pinyin to input Chinese characters in NVDA's editable controls
### Steps to reproduce:
1. Download and install Sogou Pinyin Input Method:https://shurufa.sogou.com/
2. Find editable control in NVDA, such as filter in input gesture dialogs.
3. ctrl+shift switch input method to Sogou Pinyin.
4. Try typing 'duixiang' and press the space to confirm.

### Actual behavior:
The character actually entered into the edit box is 'duixiang' or blank instead of '对象'.
### Expected behavior:
The Chinese word '对象' is entered into the edit box.

### NVDA logs, crash dumps and other attachments:
[log.txt](https://github.com/nvaccess/nvda/files/11147782/log.txt)

#### NVDA installed/portable/running from source:
Installed
#### NVDA version:
alpha-28022
#### Windows version:
Windows 10 22H2 (AMD64) build 19045.2728
#### Name and version of other software in use when reproducing the issue:
Sogou Pinyin Input Method 13
#### Other information about your system:
None
#### Does the issue still occur after restarting your computer?
Yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
The previous alpha version could not reproduce the issue, But the build of #14759 reproduces the issue.
#### If NVDA add-ons are disabled, is your problem still occurring?
Yes
#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
Yes

### PR DESCRIPTION
**Pull request by LeonarddeR**
### Link to issue number:
Follow up of #14759
Fixes #14784
Partially reverts 9b97de0d20eb4720230771d301e3f2e486f6b0a5

### Summary of the issue:
At least one custom IME is reported to no longer work in editable controls within NVDA.

### Description of user facing changes
Fix the regression

### Description of development approach
We no longer use the background thread to handle cancellable messages, as it seems using the background thread causes IME messages to be discareded. This means a partial revert of 9b97de0d20eb4720230771d301e3f2e486f6b0a5. In fact, this pr removes the background thread but keeps the event based approach to cancel calls from NVDA's watchdog.

### Testing strategy:
- [x] Ensure that #14784 can no longer be reproduced
- [x] Ensure that #14746 still can't be reproduced any more
- [x] Ensure that #13335 still can't be reproduced any more

### Known issues with pull request:
None known

### Change log entries:
Add this pr and issue #14784 to the changelog entry for #14759

### Code Review Checklist:

- [ ] Pull Request description:
  - description is up to date
  - change log entries
- [ ] Testing:
  - Unit tests
  - System (end to end) tests
  - Manual testing
- [x] API is compatible with existing add-ons.
- [x] Documentation:
  - User Documentation
  - Developer / Technical Documentation
  - Context sensitive help for GUI changes
- [x] UX of all users considered:
  - Speech 
  - Braille
  - Low Vision
  - Different web browsers
  - Localization in other languages / culture than English
- [x] Security precautions taken.

### CODE REVIEW

**Comment by cary-rowen** [comment]
I tested the latest build and #14784 is still reproducible.

**Comment by leonardder** [comment]
Is this ime easily testable for people who do not understand Chinese?

**Comment by cary-rowen** [comment]
Just need to install Sogou Pinyin input method, if the steps in #14784 are not easy to understand, please let me know, I am more than willing to provide further explanation.

**Comment by cary-rowen** [comment]
Hi, I tested the latest build and #14784 is still reproducible.
For debugging purposes, would it be helpful if I could provide a virtual machine with NVDARemote installed for you to test?

**Comment by leonardder** [comment]
I hadn't thought about that, I have a vm myself, so that'll work.

**Comment by leonardder** [comment]
@cary-rowen The build that's currently being produced should fix your issue.

**Comment by cary-rowen** [comment]
Yes, I tested, and the latest build fixes #14784 , thanks.

**Comment by leonardder** [comment]
Thanks @cary-rowen. How about #13335?

**Comment by cary-rowen** [comment]
Hi @leonardder 

#13335 can also be covered by this PR, very nice.

Thanks

**Comment by cary-rowen** [comment]
@seanbudd This is ready.

**Review by michaelDCurran — APPROVED** [review]

**Pull request merged**
