### PR TITLE
Visual Studio: fix bugs in object model implementation, majorly stripping down the appModule

### PR DESCRIPTION
**Pull request by LeonarddeR**
### Link to issue number:
None

### Summary of the issue:
De current appModule of visual studio contains out of date code for very old versions of Visual Studio, 2008 and older.

### Description of how this pull request fixes the issue:
I revised the appModule and removed much code, in particular the code on the object model TextInfo impl that was required to calculate offsets from points. This code turned out to be unreliable on newer versions of Visual Studio anyway.

I also tried to increase the robustness of the acces to the DTE, as instances of the visual studio com objects are tied to a single thread.

### Testing performed:
Tested the object model text implementation with Visual Studio 2019 by enforcing the VsTextEditPane overlay class on the WPF Text Edit control. Note that this code is not in the actual pull request, as the WPF implementation is still far more resposnive than the object model one.

### Known issues with pull request:
Not tested with older versions of Visual Studio that rely on the object model.

### Change log entry:
Mainly stripping out of date code, so may be not applicable here.

### CODE REVIEW

**Comment by feerrenrut** [comment]
This is still a draft, @leonardder do you have plans to work on this further? What is outstanding? Do you want feedback on any specific aspects?

**Comment by leonardder** [comment]
I might be able to look into this in the weekend.

**Comment by leonardder** [comment]
@feerrenrut I had another look and believe this is ready for review.

**Review by feerrenrut — APPROVED** [review]
There are a lot of different changes in here. Typically I'd like to see a more focused PR, but given you are a long term contributor and I believe you will be around to follow up on any potential regressions I'd like to proceed with this. 

Is this ok with you @leonardder?

**Comment by leonardder** [comment]
> I believe you will be around to follow up on any potential regressions

As i use VS daily, this is very likely indeed.
I'd be happy to provide a more focused pr, unfortunately there is just a whole bunch of removed outdatedness in here. I hope this pr sets the base to allow for a much more focused approach in the future.

**Pull request merged**
