### PR TITLE
Enforced UIA implementation of Object Explorer window

### PR DESCRIPTION
**Pull request by francipvb**
### Link to issue number:

Issue #9311

### Summary of the issue:

The objects tree of the object explorer was not working correct in Visual Studio 15.3 and up.

### Description of how this pull request fixes the issue:

I made some research and figured out that the three panes of the object explorer are being instantiated as IAccessible objects.

Basically, this enforces instantiation of all objects as UIA instances if it detects a version up from 15.3.

By doing this, NVDA is enforced to pick UIA versions of these objects, which work better.

### Testing performed:

Unfortunately, I can't test with more systems than my one because I didn't set up VMs for other configurations.

### Known issues with pull request:

The only problem is with level detection if the expanded is the last item on the tree, but this is an issue that occurs also with narrator.

I will keep doing research on this to see if it can be solved somehow.

### Change log entry:

Section: Bug fixes

* Visual Studio 2017: _Objects tree_ in _Objects Explorer_ was not working properly. (#9311)

### CODE REVIEW

**Review by LeonarddeR — CHANGES_REQUESTED** [review]
1. Please revert the changes to the changes file. This will be done around merge time.
2. This implementation is a bit aggressive.Is there a particular window class in use for these inaccessible items? You could get the windowClass of a handle with `winUser.getClassName(hwnd)`

**Comment by francipvb** [comment]
Hello @leonardder 

I made the changes you requested.

Cheers,

**Comment by leonardder** [comment]
I've had another look and also tried it in practise now. Honestly, I'm not convinced that this is the right solution:

1. When expanding/collapsing tree items, the new state isn't automatically reported.
2. This pr also enforces UIA for RICHEDIT50W, which is not necessary.

I'd rather see an implementation based on MSAA. Looking at the developer info when UIA is enforced, the MSAA proxy is used and there is no framework identifier, so Improprietypretty sure that this is native MSAA and therefore should be treated a such.

**Comment by francipvb** [comment]
Hello @leonardder 
I received a response from Microsoft saying that they filed a bug with the information you provided in [this comment](https://github.com/nvaccess/nvda/issues/7504#issuecomment-466076588).
I Will remove the text view class from the check, but the tree view needs this temporary fix until they fix this annoying problem.
Without this, it is impossible to use the object explorer to review a library object tree.
About the Richedit, I've added this because it has links to navigate between objects, but unfortunately they aren't reported neither with the UIA implementation.
Cheers,

**Comment by leonardder** [comment]
> ... the tree view needs this temporary fix until they fix this annoying problem.

Are you sure that this can't be fixed when using MSAA?

**Comment by francipvb** [comment]
Hello @leonardder,

> Are you sure that this can't be fixed when using MSAA?

At least I don't know how to, my knoledge is not enough, I think.

Regards,

**Comment by francipvb** [comment]
Hello again @leonardder 

I was doing some tests against visual studio's object explorer, particularli testing the IA2 implementation of the object explorer trees

Here are the results:

* `event_gainFocus` are called only for top-level items.
* `event_selection` is called only for top-level items, too.
* These events are called for the next top-level item even with an expanded item in place of the child.
* However, the correct item is selected when you focus the tree from the menu bar, a curious behavior.

I don't know so much about IA2, but I cannot see a way to solve it without replacing the IA2 implementation by the UIA ones.

Note that this applies to Visual Studio 2019 too, same errors.

Cheers,

**Comment by francipvb** [comment]
Hello @leonardder 

I found a way to solve this without enforcing UIA implementation.

The only thing is the treeview level, I don't know how to instruct NVDA to report it, but the rest works as expected.

Cheers,

**Comment by francipvb** [comment]
Closing this because it is not valid anymore.

**Pull request closed without merging**
