### PR TITLE
Stop using UnidentifiedEdit in Fast Log Entry edit field

### LINKED ISSUE #8996: NVDA does not read in the Fast Log Entry
### Steps to reproduce:
-1. Download Fast Log Entry installer from http://df3cb.com/fle/
0. Install FLE
1. Open FLE
2. Try to navigate using cursor keys

### Actual behavior:
The text (log content) is not read. There are unknown symbols on the braille display eg. '\x2023''\x6548''\x6461''\x7265'...

### Expected behavior:
An edit field similar to Notepad filled with example log should be readable.

#### NVDA Installed/portable/running from source:
Installed

#### NVDA version:
2018.3.2

#### Windows version:
Windows 7 64bit Version 6.1.7601 Service Pack 1 Build 7601

#### Name and version of other software in use when reproducing the issue:
Fast Log Entry 2.12

#### Does the issue still occur after restarting your PC?
Yes

#### Have you tried any other versions of NVDA?
- NVDA 2017.3, Windows XP 32bit - works
- NVDA 2018.3.2, Windows 10 32bit - doesn't work
- NVDA 2018.3.2, Windows 10 64bit - doesn't work

### Remarks
- Commercial screenreaders work properly.

### PR DESCRIPTION
**Pull request by lukaszgo1**
### Link to issue number:
Fixes #8996
### Summary of the issue:
In #8165 we started using Unidentifiededit for editable text fields in which there is a caret and which seems to support Edit API. While both of these criterion's are true for Fast Log Entry edit fields their WindowText contains complete garbage and UnidentifiedEdit relies on Windowtext being correct.
### Description of how this pull request fixes the issue:
1. For edit field in Fast Log Entry DisplayModelEditableText is used similar to the pre #8165 
2. DisplayModelEditableText no longer inherits from EditableText rather from EditableTextWithoutAutoSelectDetection which makes selection announced when the color used for highlight in a particular app is the default Windows highlight color  - This has been suggested by @jcsteh in #4535.
### Testing performed:
Ensured that main edit field in Fast Log Entry is once again readable and that selection is announced in most cases.
The try build has also been tested by the original reporter and the issue is fixed for him as well.
### Known issues with pull request:
- For some lines selection is signaled with colors different than one used by Windows by default. For them NVDA fails to announce selected text. This shouldn't block this pr - it can be fixed only after #10040 is merged anyway.
### Change log entry:

Section: Bug fixes
- NVDA once again works correctly in Fast Log Entry edit field.
- NVDA should announce text selection in more cases.

### CODE REVIEW

**Comment by lukaszgo1** [comment]
@leonardder You may be interested in reviewing this.

**Comment by feerrenrut** [comment]
What else uses `DisplayModelEditableText`? Changing it's behavior runs the risk of introducing regressions elsewhere, unless those usages have been checked, and will benefit from the change.

**Comment by leonardder** [comment]
DisplayModelEditableText is still used in quite a few places in the wild. Having said that, I think it makes sense to test this and see whether any regressions are reported.

**Review by LeonarddeR — CHANGES_REQUESTED** [review]
This appModule shares logic in thechooseNVDAObjectOverlayClasses and event_NVDAObject_init methods. Therefore, I prefer this to be changed in such a way that you create a new overlay class  that's added in chooseNVDAObjectOverlayClasses, which inherrits both from DisplayModelEditableText and EditableTextWithoutAutoSelectDetection. It can then override name to return None. I think this causes the least chance of regression possible so it also addresses @feerrenrut 's concern

**Comment by lukaszgo1** [comment]
@feerrenrut wrote:
> What else uses `DisplayModelEditableText`?

It is used in various editable text cases when NVDA cannot access text otherwise.

> Changing it's behavior runs the risk of introducing regressions elsewhere, unless those usages have been checked, and will benefit from the change.



First of all `EditableTextWithoutAutoSelectDetection` extends `EditableText` the only difference lies in the fact that `EditableText` does not support selection changes. and most, (probably all) edit fields using `DisplayModelEditableText` allows for text selection. IMHO using `EditableText` for `DisplayModelEditableText` was a mistake in the first place.   In addition I've worked with a custom appmodule for Becky! Internet Mail with this change for for half a year now and there was no problems for `DisplayModelEditableText` cases and it allows for selection to be announced. Even if we decide not to change this in this PR it is something which has to be changed eventually - using class which has no support for selection for controls which allows for it makes no sense.

**Comment by leonardder** [comment]
[**@lukaszgo1**](https://github.com/lukaszgo1) commented on [Aug 13, 2020, 2:59 PM GMT+2](https://github.com/nvaccess/nvda/pull/11488#issuecomment-673463329 "2020-08-13T12:59:45Z - Replied by Github Reply Comments"):
> First of all `EditableTextWithoutAutoSelectDetection` extends `EditableText` the only difference lies in the fact that `EditableText` does not support selection changes. and most, (probably all) edit fields using `DisplayModelEditableText` allows for text selection. 

While this is true, theoretically it might be the case that selection is reported erroneously in controls using this.
Would be interested to know what @michaelDCurran  thinks. I have no opinion, there are good reasons for both decisions.

**Comment by lukaszgo1** [comment]
@leonardder wrote:

> This appModule shares logic in thechooseNVDAObjectOverlayClasses and event_NVDAObject_init methods. Therefore, I prefer this to be changed in such a way that you create a new overlay class that's added in chooseNVDAObjectOverlayClasses,...


Done

> which inherrits both from DisplayModelEditableText and EditableTextWithoutAutoSelectDetection. It can then override name to return None. I think this causes the least chance of regression possible so it also addresses @feerrenrut 's concern



While we are avoiding possible regressions this way we then have to either do that for every `DisplayModelEditableText` for which it gives better results  or do that for Fast Log Entry and then, in a subsequent PR, make `DisplayModelEditableText` inherit from `EditableTextWithoutAutoSelectDetection`.

If we consider #8996 serious enough to include a fix for it into 2020.3 then I agree option 2 is the proper fix and I'll implement it. If the fix can wait until 2020.4 however, I'd rather leave this pr as is and ask @feerrenrut or @michaelDCurran to merge it early during 2020.4 development cycle and let the change from `EditableText` to `EditableTextWithoutAutoSelectDetection` have proper testing in Alpha and prove itself.


Also regarding this:

> While this is true, theoretically it might be the case that selection is reported erroneously in controls using this.

I agree that it is theoretically possible, however: 
- for now selection in `DisplayModelEditableText` cannot be reported at all
- I don't see any possibility to prove that this  is causing spurious selection announcements other than having this changed in Alpha for a while and reacting to user reports.

**Comment by leonardder** [comment]
> If the fix can wait until 2020.4 however, I'd rather leave this pr as is and ask @feerrenrut or @michaelDCurran to merge it early during 2020.4 development cycle and let the change from `EditableText` to `EditableTextWithoutAutoSelectDetection` have proper testing in Alpha and prove itself.

This makes sense to me. I believe the merge window for 2020.3 is now closed.

**Comment by leonardder** [comment]
Looking at this again, It occurs to me that TSynMemo is a Delphi control that is likely to be used much more generally. See https://github.com/SynEdit/SynEdit/
I'd also agree if you apply this change more generally.
You can add it to the IAccessible.delphi module. Note that you can simply override name and set windowTextLineCount to 0 there, it ensures that later on, DisplayModelEditableText is added.
I agree it is a bit of a change, though. Sorry for not coming across this earilier.

**Comment by lukaszgo1** [comment]
@leonardder  wrote:
> Looking at this again, It occurs to me that TSynMemo is a Delphi control that is likely to be used much more generally. See https://github.com/SynEdit/SynEdit/
> I'd also agree if you apply this change more generally.

I don't think this is a good idea. This control is used, for example, in Dev-C++ and there WindowText contains the real text of the control.

**Comment by leonardder** [comment]
Ah, that's great.

**Review by LeonarddeR — DISMISSED** [review]

**Review by feerrenrut — DISMISSED** [review]
Thanks @lukaszgo1 looks good to me.

**Review by feerrenrut — APPROVED** [review]

**Pull request merged**
