### PR TITLE
Handle incompatible add-ons when upgrading/downgrading NVDA API versions

### LINKED ISSUE #15412: Incompatible NVDA Version Keeps Add-ons Disabled in Compatible Versions
### Steps to reproduce:
1. Upgrading from 2023.2 to the latest alpha-29134 There are some installed add-ons that are disabled because they are incompatible with 2024.1.
2. Downgrade NVDA back to 2023.2.
### Actual behavior:
Add-ons that are disabled because they are incompatible with the NVDA version that breaks compatibility are still disabled in compatible NVDA versions
### Expected behavior:
These add-ons should be available again in NVDA2023.2 as they are actually compatible with NVDA-2023.2.
#### NVDA installed/portable/running from source:
Installed
#### NVDA version:
NVDA-alpha-29134, and NVDA-2023.2
#### Windows version:
Windows 10 22H2 (AMD64) build 19045.3393
#### Name and version of other software in use when reproducing the issue:
none

#### Other information about your system:
None
#### Does the issue still occur after restarting your computer?
Yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
No
#### If NVDA add-ons are disabled, is your problem still occurring?
Not tested
#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
Yes

### LINKED ISSUE #15414: The incompatible add-ons dialog can lead users to believe that add-ons enabled by overriding compatibility will be disabled again.
### Steps to reproduce:
1. Upgrade to NVDA-alpha-29119 (not the latest Alpha version), then override compatibility and enable some add-ons.
2. Try upgrading from alpha-29119 to a newer version, such as alpha-29134.
3. Before upgrading alpha-29134, you will see an incompatibility dialog. View incompatible add-ons in the dialog.

### Actual behavior:
Those add-ons whose compatibility was overridden and enabled in step (1) will appear in the list.
This situation may lead users to believe that these add-ons will be disabled after installing alpha-29134.
### Expected behavior:
Add-ons that are enabled by overriding compatibility should not appear in this list, as they will not be disabled after installing a new version of NVDA.
#### NVDA installed/portable/running from source:
Installed
#### NVDA version:
Alpha Version
#### Windows version:
Windows 10 22H2 (AMD64) build 19045.3393
#### Name and version of other software in use when reproducing the issue:
None
#### Other information about your system:
None
#### Does the issue still occur after restarting your computer?
Yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
n/a
#### If NVDA add-ons are disabled, is your problem still occurring?
Not tested
#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
Yes

### LINKED ISSUE #15437: Users cannot uninstall and reinstall to make the add-on available again because their configuration is corrupted
### Steps to reproduce:
1. Install NVDA-2023.2;
2. Install an add-on whose API version should be less than 2024.1.0, that is, compatible with 2023.2.
3. Install the NVDA-alpha version (API version is 2024.1.0).
4. Check the add-on status in the add-on store: Add-on installed in stap2 is disabled.
5. Uninstall the NVDA Alpha version through the NVDA uninstaller in the control panel.
6. Restart your computer and install NVDA-2023.2
7. Check the add-on status in the add-on store.

### Actual behavior:
Perform step 7: You will find that the status of the add-on is the same as step 4, that is, it is still disabled.
### Expected behavior:
Add-on should be enabled.

When I tested using NVDA-2022.1 and NVDA2023.1, it performed as expected. So this could also be considered a regression.

Alternatives I Considered:
1. When uninstalling NVDA, it ask to delete the user configuration.
2. Ask user to delete legacy user configuration or reset add-on status when installing NVDA.

#### NVDA installed/portable/running from source:
Installed
#### NVDA version:
NVDA-Alpha Version
#### Windows version:
Windows 10 22H2 (AMD64) build 19045.3393
#### Name and version of other software in use when reproducing the issue:
None
#### Other information about your system:
None
#### Does the issue still occur after restarting your computer?
Yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
When I tested using NVDA-2022.1 and NVDA2023.1, it performed as expected. So this could also be considered a regression.
#### If NVDA add-ons are disabled, is your problem still occurring?
n/a
#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
n/a

### PR DESCRIPTION
**Pull request by seanbudd**
### Link to issue number:
Fixes #15437
Fixes #15412
Fixes #15414

### Summary of the issue:

There are several scenarios which need to be supported when updating/downgrading NVDA with incompatible add-ons

| Test Name | Upgrade from | Upgrade to | Test notes |
|---|---|---|---|
| Upgrade to different NVDA version in the same API breaking release cycle | X.1 | X.1 | Add-ons which remain incompatible are listed as incompatible on upgrading. Preserves state of enabled incompatible add-ons |
| Upgrade to a different but compatible API version | X.1 | X.2 | Add-ons which remain incompatible are listed as incompatible on upgrading. Preserves state of enabled incompatible add-ons |
| Downgrade to a different but compatible API version | X.2 | X.1 | Add-ons which remain incompatible are listed as incompatible on downgrading. Preserves state of enabled incompatible add-ons |
| Upgrade to an API breaking version | X.1 | (X+1).1 | All incompatible add-ons are listed as incompatible on upgrading, overridden compatibility is reset. |
| Downgrade to an API breaking version | (X+1).1 | X.1 | Add-ons which remain incompatible listed as incompatible on downgrading. Preserves state of enabled incompatible add-ons. Blocked add-ons which are now compatible are re-enabled. |

### Description of user facing changes
- NVDA will reset compatibility overrides when updating to a different API breaking release, this means incompatible add-ons will be blocked again.
- If an add-on is blocked due to compatibility and becomes compatible, e.g. via downgrading, it will be re-enabled.

### Description of development approach
Store the BACK_COMPAT_TO version in the addon state pickle.
When updating the BACK_COMPAT_TO version, reset the incompatibility override state.
When downgrading, re-check add-on compatibility

### Testing strategy:
Refer to manual test plan.

Builds:
https://drive.google.com/file/d/1iSsnwp3yg4LRl3p0v0mVINyU8YDmVe1f/view?usp=sharing

### Known issues with pull request:
There may be minor issues when downgrading to versions that don't include this patch from a version with this patch.
Nothing major has been discovered.

### Change log entries:
Bug fixes
- Fix issues with handling incompatible add-ons when upgrading NVDA

### Code Review Checklist:

- [x] Pull Request description:
  - description is up to date
  - change log entries
- [x] Testing:
  - Unit tests
  - System (end to end) tests
  - Manual testing
- [x] API is compatible with existing add-ons.
- [x] Documentation:
  - User Documentation
  - Developer / Technical Documentation
  - Context sensitive help for GUI changes
- [x] UX of all users considered:
  - Speech 
  - Braille
  - Low Vision
  - Different web browsers
  - Localization in other languages / culture than English
- [x] Security precautions taken.

### CODE REVIEW

**Comment by leonardder** [comment]
What happens if a downgrade would enable an incompatible add-on, but the add-on was previously disabled explicitly?Op 13 sep 2023 om 06:34 heeft Sean Budd ***@***.***> het volgende geschreven:﻿
Link to issue number:
Fixes #15437
Fixes #15412
Fixes #15414
Summary of the issue:
There are several scenarios which need to be supported when updating/downgrading NVDA with incompatible add-ons



Test Name
Upgrade from
Upgrade to
Test notes




Upgrade to different NVDA version in the same API breaking release cycle
X.1
X.1
Add-ons which remain incompatible are listed as incompatible on upgrading. Preserves state of enabled incompatible add-ons


Upgrade to a different but compatible API version
X.1
X.2
Add-ons which remain incompatible are listed as incompatible on upgrading. Preserves state of enabled incompatible add-ons


Downgrade to a different but compatible API version
X.2
X.1
Add-ons which remain incompatible are listed as incompatible on upgrading. Preserves state of enabled incompatible add-ons


Upgrade to an API breaking version
X.1
(X+1).1
All incompatible add-ons are listed as incompatible on upgrading, overridden compatibility is reset.


Downgrade to an API breaking version
(X+1).1
X.1
Add-ons which remain incompatible listed as incompatible on upgrading. Preserves state of enabled incompatible add-ons. Add-ons which are now compatible are re-enabled.



Description of user facing changes

NVDA will reset compatibility overrides when updating to a different API breaking release, this means incompatible add-ons will be blocked again.
If an add-on is blocked due to compatibility and becomes compatible, e.g. via downgrading, it will be re-enabled.

Description of development approach
Store the BACK_COMPAT_TO version in the addon state pickle.
When updating the BACK_COMPAT_TO version, reset the incompatibility override state.
Testing strategy:
Refer to manual test plan.
Builds:

X.1:
X.2:
(X+1).1:

Known issues with pull request:
Change log entries:
Bug fixes

Fix issues with handling incompatible add-ons when upgrading NVDA

Code Review Checklist:


 Pull Request description:

description is up to date
change log entries


 Testing:

Unit tests
System (end to end) tests
Manual testing


 API is compatible with existing add-ons.
 Documentation:

User Documentation
Developer / Technical Documentation
Context sensitive help for GUI changes


 UX of all users considered:

Speech
Braille
Low Vision
Different web browsers
Localization in other languages / culture than English


 Security precautions taken.




You can view, comment on, or merge this pull request online at:
  https://github.com/nvaccess/nvda/pull/15439

Commit Summary

  ffbdc8e  Handle incompatible add-ons when upgrading/downgrading NVDA API versions
  ac5faac  Manual test plan


File Changes  (4 files)

  
    M
    source/_addonStore/models/status.py
    (4)
  
  
    M
    source/_addonStore/models/version.py
    (6)
  
  
    M
    source/addonHandler/__init__.py
    (78)
  
  
    M
    tests/manual/addonStore.md
    (20)
  


Patch Links:

  https://github.com/nvaccess/nvda/pull/15439.patch
  https://github.com/nvaccess/nvda/pull/15439.diff

**Comment by seanbudd** [comment]
This should not be affected - however I'd note that we generally don't support downgrades, and that the goal of this PR is to prevent add-ons from getting a state where they are stuck as incompatible and blocked.

**Comment by CyrilleB79** [comment]
So maybe it would be nice to clarify (elsewhere than in comments of issues/PRs) what is supported or not while downgrading NVDA. E.g.:
* NVDA does not fully support downgrade meaning that there is no guarantee that the configuration or the add-on states is kept while downgrading, e.g.:
  * a disabled add-on can be reenabled during downgrading process
  * an option could be restored to default or modified during downgrading process
* NVDA tries to offer a limited support of downgrade so that it remains usable after downgrade, e.g.:
  * options that have been restored during a downgrade process can be modified again manually
  * add-ons that were disabled during a downgrade process can be reenabled or reinstalled or uninstalled

**Comment by wmhn1872265132** [comment]
There are two cases of downgrade:
1. Install the old version directly;
2. Uninstall the new version through the uninstaller and then reinstall the old version.

In my opinion, the fact that NVDA does not support downgrading refers to the first situation. There should be better support for the second situation, at least there should be no serious errors or missing functions.
Since the configuration of NVDA can be called by multiple different versions of software through the command line, etc., this situation becomes more complicated.

**Review by michaelDCurran — DISMISSED** [review]

**Pull request merged**
