### PR TITLE
Make add-on store base end point part of the public API

### PR DESCRIPTION
**Pull request by seanbudd**
### Link to issue number:
Relates to #14974 

### Summary of the issue:
Add-on authors wish to have a stable API so that they can change the base URL of the add-on store.
This allows add-ons to use a mirror for the add-on store.

### Description of user facing changes
None

### Description of development approach
Change BASE_URL for the add-on store to be public

### Testing strategy:
Confirm with add-on authors that changes are sufficient

### Known issues with pull request:
None
### Code Review Checklist:

- [x] Documentation:
  - Change log entry
  - User Documentation
  - Developer / Technical Documentation
  - Context sensitive help for GUI changes
- [ ] Testing:
  - Unit tests
  - System (end to end) tests
  - Manual testing
- [x] UX of all users considered:
  - Speech 
  - Braille
  - Low Vision
  - Different web browsers
  - Localization in other languages / culture than English
- [x] API is compatible with existing add-ons.
- [x] Security precautions taken.

### CODE REVIEW

**Comment by seanbudd** [comment]
@cary-rowen can you confirm that these changes are sufficient to create a stable API for your mirroring add-on?

**Comment by LeonarddeR** [comment]
Isn't it possible to provide a default host that is also available from China? Why not use github pages, for example?

**Comment by seanbudd** [comment]
@LeonarddeR - I would consider that out of scope and somewhat covered by #14974 
I'm not sure if GitHub pages supports the functionality we need and use on the server, it would require a separate investigation

**Comment by lukaszgo1** [comment]
Note that Add-on Updater allows user to select one of the supported mirrors from its GUI, which IMHO is a much nicer UX. While I don't think we should promote any particular mirrors in NVDA as such, offering ability to add an URL from the config dialog seems much better than just making API for add-ons more stable.

**Comment by cary-rowen** [comment]
Hi @seanbudd,
I haven't tested this yet, but I think that this might not be the best solution, In China, in addition to the add-on store mirror of NVDA, we have created an updated mirror of NVDA.
The ideal effect may be that users can smoothly use the NVDA add-on store and automatic updates without installing mirror add-on.
Because users cannot access the add-on store until the mirror add-on is installed.

**Comment by seanbudd** [comment]
Hi @cary-rowen, as mentioned earlier, that is out of scope of what we are trying to do here, the issue exists to track that further work. Now that the add-on API is considered stable we can ensure the API your add-on needs is stable.

**Comment by cary-rowen** [comment]
If only exposing the add-on store API is considered then this can be considered stable.

**Pull request merged**
