### PR TITLE
Hide invisible columns in syslistview32 lists

### LINKED ISSUE #8268: sysListView32.ListItem._getColumnLocationRaw can return malformed rectangles (i.e. with a left coordinate that is greather than the right coordinate)
### Steps to reproduce:
1. Install NVDA Version: next-15126,d5e58ddf
2. Launch Becky! Internet Mail and focus a list of messages.
3. Try to navigate with arrow keys.
### Expected behavior:
NVDA should read list columns such as subject send date and from

### Actual behavior:
An error sound is played. I am attaching a  fragment of the log with specific error.

### System configuration:
NVDA version:
next-15126,d5e58ddf

NVDA Installed or portable:
Installed
Other information:
It is probably caused by #8190. The problematic column seems to be the first column, which contain graphical presentation of the message state read, unread etc. I am also attaching developer info for this column.

Windows version:
Windows 8 x64

Name and version of other software in use when reproducing the issue:
Becky! Internet Mail version 2.74 [en] 
### Other questions:

Does the issue still occur after restarting your PC?
Yes
Have you tried any other versions of NVDA?
Yes next 15121,7fcd6fe7 and it was possible to read this list.
[Issue.zip](https://github.com/nvaccess/nvda/files/2005295/Issue.zip)

### PR DESCRIPTION
**Pull request by LeonarddeR**
### Link to issue number:
Fixes #8268

### Summary of the issue:
Some syslistview32 controls, for example in Becky internet mail or [Dualtask DPS](https://www.dualtask.nl/dps-productie/) have columns that are invisible to the user, i.e. their width is less than or equal to 0. Yet in NVDA, they are shown if they have content.

### Description of how this pull request fixes the issue:
When creating the name of a syslistview32 list item, don't add text for invisible columns.

### Testing performed:
Tested in Becky internet mail and Dualtask DPS that hidden columns are no longer read.

### Known issues with pull request:
None

### Change log entry:
* Bug fixes
   + NVDA will no longer report content of visually hidden columns for list items in SysListView32 controls. (##8268)

### CODE REVIEW

**Comment by DrSooom** [comment]
@leonardder: You interchanged the text regarding the last two headlines in the PR description.

**Comment by leonardder** [comment]
Thanks for pointing this out.

**Comment by michaelDCurran** [comment]
Looks like checks are failing on this pr. I'll hold off on review until that is addressed.

**Comment by leonardder** [comment]
Should now be fixed!

**Review by michaelDCurran — APPROVED** [review]

**Comment by zstanecic** [comment]
Hi!

Is this planned to be backported to 2019.2?

**Comment by michaelDCurran** [comment]
No.

**Pull request merged**
