### PR TITLE
Python syntax: replace identity comparison (var is/is not literal) with equality comparison (var ==/!= literal)

### LINKED ISSUE #10966: Python 3.8 (porting): "variable is value" aka identity comparison with a literal raises syntax error if warn on error option is specified
Although syntax warning is given, if Python is run with -Werror (convert warnings to errors) switch, the following raises syntax error exception:

### Steps to reproduce:
1. Prepare NVDA from source with `Python 3.7`.
2. If `Python 3.8 32-bit` is installed, install `Python 3.8` versions of `wxPython` (latest `4.1.0 snapshot` is required).
3. Run NVDA from source with errors turned on (`py -3.8 -Werror path/to/nvda/source/nvda.pyw`).

### Actual behavior:
If statement of the form:
`variable is var:`
is encountered, Python 3.8 raises syntax error.

### Expected behavior:
NO errors.

#### NVDA installed/portable/running from source:
Source

#### NVDA version:
master.2d73010

#### Windows version:
Windows 10 Version 2004 (build 19041.172)

#### Name and version of other software in use when reproducing the issue:
Python 3.7.7, 3.8.2 (both 32-bit)

#### Other information about your system:
Being used to test Python 3.8 compatibility

#### Does the issue still occur after restarting your computer?
Yes

#### Have you tried any other versions of NVDA? If so, please report their behaviors.
NO errors in Python 3.7 version of NVDA (including latest alpha snapshot)

#### If addons are disabled, is your problem still occuring?
Yes

#### Did you try to run the COM registry fixing tool in NVDA menu / tools?
Does not apply

### Motivation for running with errors turned on:
Although syntax warning would suffice in that errors will not be logged, running with errors turned on ensures testing for Python syntax errors that are easily ignored.

### Solution:

Convert instances of "variable is value" statement to "variable {condition} value" statement such as:

* `someStr is value` -> `someStr == value`
* `someNum is not something` -> `someNum != something`

This issue was observed with:

* `buildVersion`: constructing NVDA version string
* `Browse mode`: checking for headers

### PR DESCRIPTION
**Pull request by josephsl**
Hi,

Although the issue noted below relates to Python 3.8, it is compatible with Python 3.7:

### Link to issue number:
Fixes #10966 

### Summary of the issue:
With Python 3.8 run with warnings to errors (-Werror) switch, identity comparison of the form is flagged as syntax errors:

* var is literal
* var is not literal

### Description of how this pull request fixes the issue:
Replace identity comparison with equality check:

* var == literal
* var != literal

### Testing performed:
Tested under:

* Flake8 checks.
* Running source code copy multiple times to verify changes do work, each time one change is made.

### Known issues with pull request:
None

### Change log entry:
None

### Testing procedure (for future reference):

1. Run source code copy of NVDA with -Werror switch (best to do so with Python 3.8).
2. If one didn't do so, install Flake8 (the easiest way to do so is running scons lint base=origin/master, which will download and install Flake8 and its dependencies via Pip).
3. Run Flake8 against the source directory with error codes related to what Python interpreter says (in this case, F632). To do so, go to drive/path/to/nvda/code, then run "flake8 --select {codeToLookFor} source" e.g. "flake8 --select F632 source".
4. Fix the issues Flake8 reports, one at a time.
5. Run NVDA from source with warnings converted to errors.
6. Run and fi another Flake8 error.
7. Repeat steps 5 and 6 until no issues remain.
8. Run NVDA from source multiple times to make sure there are no regressions.

Thanks.

### CODE REVIEW

**Comment by francipvb** [comment]
Hello,

If you configure flake8 in VSCode you can solve any kind of issues in source code by opening a file and pressing <kbd>CTRL]SHIFT]M</kbd>. You can filter the type of the problems listed.

Cheers,

**Comment by feerrenrut** [comment]
@josephsl as another way to be sure all files are hit, could you run the launcher build step with python 3.8 after modifying the NVDADistGenerator (in `<repo root>/sconstruct` or perhaps in `<repo root>/setup.py` to compile python files with the `-werror` option you mentioned. It would be good to know that we have definitely caught them all. If you do this please confirm first that you do catch an error if one is present.

**Comment by josephsl** [comment]
Hi, if I run scons under Python 3.8 without this PR, it does catch them, and with this PR, no errors. Thanks.

**Comment by feerrenrut** [comment]
Did you also check tests / system tests? And any other python files (including sconscript / sconstruct) files?

**Comment by josephsl** [comment]
Hi,

No problems with sconstruct and tests, although Win32Com included in Py2exe submodule we are using does report F632 erro2.

Thanks.

**Comment by feerrenrut** [comment]
> Win32Com included in Py2exe submodule we are using does report F632 erro2.

For reference: F632 is `use ==/!= to compare str , bytes , and int literals.`
Ok, thanks for testing. I don't think that should block this PR. But it likely means we'll need an update for Py2exe. Can you create/link to a bug on their repo please?

**Review by feerrenrut — APPROVED** [review]

**Comment by feerrenrut** [comment]
How hard would it be to add a test to appveyor to check PR diffs for this issue by the way? It would be great to know that there is minimal chance of this being re-introduced.

**Comment by josephsl** [comment]
Hi, for win32com, that’s something I can raise on NV Access’s bin submodule repo as it comes from there, meaning likely we need to use an updated win32com module. Thanks.

**Comment by josephsl** [comment]
Hi, as for that, I’m not sure.

**Comment by feerrenrut** [comment]
Could the error be enabled in our flake8 config? Would that catch it?

**Comment by josephsl** [comment]
Hi, I think so. Another option is to install pre-commit hook for git which is a local thing.

**Comment by feerrenrut** [comment]
Do you have time to file a followup PR to enable this in Flake8 config? You may also consider whether want to update the flake8 version.

**Comment by josephsl** [comment]
Hi, I’ll do some digging. Thanks.

**Comment by josephsl** [comment]
Hi,

No need to change Flake8 config file, as F632 is now caught and appropriate error is emailed to PR submitter. I'll take a look at updating Flake8 to 3.7./9 or 3.8.0 as it promises better Python 3.8 compatibility.

Thanks.

**Pull request merged**
