### PR TITLE
User guide estetics, solved some spelling errors etc.

### LINKED ISSUE #6315: License documentation discrepancy
There is a discrepancy between the license as documented in Section 1.5 of the User Guide which simply links to the GPL 2.0, and going to Help > License which opens the copying.txt file and contains exceptions and other language.

### LINKED ISSUE #7394: Update User Guide to reflect change in caret location when selecting text, as per #4636
When the review cursor behaviour was changed to require pressing NVDA+f10 twice to copy (issue #4636), the caret is now moved when the text is selected.  In the explanation for the Review Cursor (second paragraph): https://www.nvaccess.org/files/nvda/documentation/userGuide.html#ReviewingText it is noted that when moving the review cursor, the system caret does not follow, so it is worth clarifying the second paragraph, possibly by adding the text:

"If selecting text that the system caret can reach, the caret moves to the selection once NVDA+f10 is pressed." after the existing paragraph so that it reads: "When moving the review cursor, the System caret does not follow along, so you can review text without losing your editing position. However, by default, when the System caret moves, the review cursor follows along. This can be toggled on and off.  If selecting text that the system caret can reach, the caret moves to the selection once NVDA+f10 is pressed".

### LINKED ISSUE #7888: User Guide: Excel's shift+f2 to enter comment editing mode.
Could you please consider to add this command(shift+f2) to User Guide 10.2. Microsoft Excel.

What's New 2014.3:
> Microsoft Excel: Provide an NVDA-specific dialog to edit the comments on the currently selected cell when pressing Excel's shift+f2 command to enter comment editing mode.

### LINKED ISSUE #8314: UserGuide, change reference page for Seika Display Braille
in the  user Guide, the reference website for Seika display braille is seika-braille.com

But if you go there, you will find a german page with no capabilities to choose language and in the homepage there are no information about Seika Braille display.
I recomend to change it with the following page:

http://en.seika-braille.com/down/index.html

This is the download page where people can take the USB Driver.

### LINKED ISSUE #8579: rework documentation of  -s
### Steps to reproduce:
1. read the users guide section on command line options and notice -s.

### Actual behavior:

The users guide says Secure mode (disable Python console)

### Expected behavior:

The reality of this code is that far more than the python console is disabled.
We currently disable the following things:
```
config profile creation: config/__init__.py:525:		if globalVars.appArgs.secure:
delete profiles: config/__init__.py:539:		if globalVars.appArgs.secure:
rename profiles: config/__init__.py:584:		if globalVars.appArgs.secure:
save profile triggers: config/__init__.py:755:		if globalVars.appArgs.secure:
python console: globalCommands.py:1678:		if globalVars.appArgs.secure or config.isAppX:
buttons which would have no affect given above operations: gui/configProfiles.py:96:		if globalVars.appArgs.secure:
gui/configProfiles.py:210:		if globalVars.appArgs.secure:
showing the log viewer: gui/logViewer.py:96:	if globalVars.appArgs.secure:
showing of the language switch list (how is switching the language a security hole)? gui/settingsDialogs.py:632:		if globalVars.appArgs.secure:
The save config on exit checkbox gui/settingsDialogs.py:638:		if globalVars.appArgs.secure:
the start after logon checkbox. gui/settingsDialogs.py:667:		if globalVars.appArgs.secure or not config.isInstalledCopy():
start on logon screens checkbox: gui/settingsDialogs.py:674:		if globalVars.appArgs.secure or not config.canStartOnSecureScreens():
saving config to elevated system config: gui/settingsDialogs.py:681:		if globalVars.appArgs.secure or not config.canStartOnSecureScreens():
checking for updates: gui/settingsDialogs.py:688:			if globalVars.appArgs.secure:
and gui/settingsDialogs.py:695:			if globalVars.appArgs.secure:
and gui/settingsDialogs.py:701:			if globalVars.appArgs.secure:
the save config handler: gui/__init__.py:168:		if globalVars.appArgs.secure:
some stuff in the welcome dlg: gui/__init__.py:653:		if globalVars.appArgs.secure or config.isAppX or not config.isInstalledCopy():
saving gesture maps to disk: inputCore.py:352:		if globalVars.appArgs.secure:
logging: logHandler.py:321:		if globalVars.appArgs.secure:
updates: updateCheck.py:13:if globalVars.appArgs.secure:
```
We should really update the users guide to reflect this. This is simply the result of neglecting to do so in past years.

### LINKED ISSUE #8689: Add "4.1.2. NVDA Usage Statistics Dialog" in the User Guide
### Steps to reproduce:
Open the NVDA User Guide.
### Actual headlines:
4. Getting started with NVDA
4.1. Launching NVDA
4.1.1. Welcome Dialog
4.2. About NVDA keyboard commands
### Expected behaviour:
Add a new chapter called "4.1.2. NVDA Usage Statistics Dialog" with a little description and a reference to "Allow the NVDA project to gather NVDA usage statistics" in the chapter "11.1.1. General (NVDA+control+g)".
#### Update on 2018-09-04:
And please also write down based on [my comment in PR #8708](https://github.com/nvaccess/nvda/pull/8708#issuecomment-418127349) in the description that the NVDA configuration ("nvda.ini") will be saved automatically by pressing the buttons "Yes" and "No", but not when pressing "Later".
#### NVDA version:
NVDA 2018.3 Beta 3

### LINKED ISSUE #9131: NVDA's documentation still references help balloons
While NVDA's Object Presentation dialog presents the option for reporting notifications, the User guide does not reference this setting properly. Instead, it still refers to the option as 'Report help balloons'. The description also still speaks about help balloons only, rather than speaking about balloons and toasts.

I suggest this is fixed in the user guide, and the description be updated to reflect the use of these notifications in later versions of Windows.

As an aside, section 8.1, Control Type, State and Landmark abbreviations still has an abbreviation for 'help baloons' (wrong spelling), but I don't know if this should also be changed.

### LINKED ISSUE #9508: English User Guide: Additions/Corrections
I've carried out an entire read through of the English User Guide, and noticed the following additions/corrections that I hope may be useful - original text will come first on each line, followed by a ">" symbol and my suggested addition/correction. It's worth noting that this is based on alpha-16944,00a63f0a so I totally understand that several of these may already be fixed.

NVDA is copyright 2006-2018 NVDA contributors. > NVDA is copyright 2006-2019 NVDA contributors.

If you have not yet got a copy of NVDA, you can download it from www.nvaccess.org > If you have not yet got a copy of NVDA, you can download it from https://www.nvaccess.org

If created, this shortcut will also be assigned a shortcut key of control+alt+n, allowing you to start NVDA at any time with this key stroke > If created, this shortcut will also be assigned a shortcut key of control+alt+n, allowing you to start NVDA at any time with this keystroke

Tapping twice will result in a double tap. Tapping 3 times will result in a triple tap > Tapping twice will result in a double-tap. Tapping 3 times will result in a triple-tap

it's possible to have gestures like a 2-finger triple tap, a 4-finger tap, etc > it's possible to have gestures like a 2-finger triple-tap, a 4-finger tap, etc

When you find the key you wish to press, double-tap the key or lift your finger, depending on options chosen from Touch Interaction Settings category of the NVDA Settings > When you find the key you wish to press, double-tap the key or lift your finger, depending on options chosen from the Touch Interaction Settings category of the NVDA Settings

To get to the NVDA menu from anywhere in Windows while NVDA is running, press NVDA+n on the keyboard or perform a 2-finger double tap on the touch screen > To get to the NVDA menu from anywhere in Windows while NVDA is running, press NVDA+n on the keyboard or perform a 2-finger double-tap on the touch screen

NVDA Menu
NVDA+n
NVDA+n
2-finger double tap > NVDA Menu
NVDA+n
NVDA+n
2-finger double-tap

Tells NVDA to pass the next key press straight through to the active application, even if it is normally treated as an NVDA key command > Tells NVDA to pass the next key press straight through to the active application - even if it is normally treated as an NVDA key command

sleep mode disables all NVDA commands and speech/braille output for the current application. This is most useful in applications that provide their own speech or screen reading features. Press this command again to disable sleep mode > sleep mode disables all NVDA commands and speech/braille output for the current application. This is most useful in applications that provide their own speech or screen reading features. Press this command again to disable sleep mode - note that NVDA will only retain Sleep Mode settings until it is restarted

Reports the Text in the clipboard if there is any > Reports the Text on the clipboard if there is any

Note: numpad keys require numlock key to be turned off to work properly > Note: numpad keys require the num lock to be turned off to work properly (two instances)

http://www.dessci.com/en/products/mathplayer/ > https://www.dessci.com/mathplayer

• Design Science MathType in Microsoft Word and PowerPoint. MathType needs to be installed in order for this to work. The trial version is sufficient > • Design Science MathType in Microsoft Word and PowerPoint. MathType needs to be installed in order for this to work. The trial version is sufficient and can be downloaded from https://www.dessci.com/en/products/mathtype/

These settings will be stored in the document as bookmarks compatible with other screen readers such as Jaws > These settings will be stored in the document as bookmarks compatible with other screen readers such as JAWS

These settings will be stored in the workbook as defined name ranges compatible with other screen readers such as Jaws > These settings will be stored in the workbook as defined name ranges compatible with other screen readers such as JAWS

For certain dialogs, you can press Apply button to let the settings take effect immediately without closing the dialog > For certain dialogs, you can press the Apply button to let the settings take effect immediately without closing the dialog

Just like input/output, if you are concerned about privacy, you should not set logging level to this option > Just like input/output, if you are concerned about privacy, you should not set your logging level to this option

If this is enabled, NVDA will automatically check for updated versions of NVDA and inform you when an update is available > If this is enabled, NVDA will automatically check for updated versions and inform you when an update is available

The speech category in the NVDA Settings dialog contains options that lets you change the speech synthesizer as well as voice characteristics for the chosen synthesizer > The speech category in the NVDA Settings dialog contains options that allow you to change the speech synthesizer as well as voice characteristics for the chosen synthesizer

If you are using the Espeak NG synthesizer that is packaged with NVDA, this is a combo box that lets you select the Variant the synthesizer should speak with. ESpeak NG's Variants are rather like voices, as they provide slightly different attributes to the eSpeak NG voice. Some variants will sound like a male, some like a female, and some even like a frog > If you are using the Espeak NG synthesizer that is packaged with NVDA, this is a combo box that lets you select the Variant the synthesizer should speak with. ESpeak NG's Variants are rather like voices, as they provide slightly different attributes to the eSpeak NG voice. Some variants will sound like a male, some like a female, and some even like a frog. If using a third-party synthesizer, you may also be able to change this value if your chosen voice supports it.

This option allows you to change the rate of your voice. This is a slider that goes from 0 to 100, (0 being the slowest, 100 being the fastest) > This option allows you to change the rate of your voice. This is a slider that goes from 0 to 100  - 0 being the slowest, 100 being the fastest

This option allows you to change the pitch of the current voice. It is a slider which goes from 0 to 100, (0 being the lowest pitch and 100 being the highest) > This option allows you to change the pitch of the current voice. It is a slider which goes from 0 to 100 - 0 being the lowest pitch and 100 being the highest.

This option is a slider which goes from 0 to 100, (0 being the lowest volume and 100 being the highest) > This option is a slider which goes from 0 to 100 - 0 being the lowest volume and 100 being the highest.

This option is a slider that lets you choose how much inflection (rise and fall in pitch) the synthesizer should use to speak with. (The only synthesizer that provides this option at the present time is eSpeak NG) > This option is a slider that lets you choose how much inflection (rise and fall in pitch) the synthesizer should use to speak with.

This checkbox allows you to toggle whether NVDA should switch speech synthesizer languages automatically if the text being read specifies its language. This option is enabled by default. Currently only the eSpeak NG synthesizer supports automatic language switching > This checkbox allows you to toggle whether NVDA should switch speech synthesizer languages automatically if the text being read specifies its language. This option is enabled by default.

When this checkbox is enabled, NVDA will include additional symbol pronunciation dictionaries when pronouncing characters and symbols > When this checkbox is checked, NVDA will include additional symbol pronunciation dictionaries when pronouncing characters and symbols

Usually, NVDA raises the pitch slightly for any capital letter, but some synthesizers may not support this well, so perhaps this option may be of use > Usually, NVDA raises the pitch slightly for any capital letter, but some synthesizers may not support this well, so this option may be a preferred alternative for some users.

This option allows you to choose the sound card that NVDA should instruct the selected synthesizer to speak through > This option allows you to choose the audio device that NVDA should instruct the selected synthesizer to speak through

The Keyboard category in the NVDA Settings dialog contains options that sets how NVDA behaves as you use and type on your keyboard > The Keyboard category in the NVDA Settings dialog contains options that set how NVDA behaves as you use and type on your keyboard

The first checkbox lets you control if NVDA should use the capslock as an NVDA modifier key > The first checkbox lets you control if NVDA should use the caps lock as an NVDA modifier key

NVDA can be configured so that the numpad Insert, Extended Insert and/or capslock key can be used > NVDA can be configured so that the numpad Insert, Extended Insert and/or caps lock key can be used

e.g. you wish to turn capslock on when you have set capslock to be an NVDA modifier key > e.g. you wish to turn caps lock on when you have set caps lock to be an NVDA modifier key

The Desktop layout makes heavy use of the numpad (with numlock off) > The Desktop layout makes heavy use of the numpad (with num lock off)

If your laptop cannot do this or does not allow you to turn numlock off > If your laptop cannot do this or does not allow you to turn num lock off

If this is unchecked, you need to double-tap on the touch keyboard key to press the key > If this is unchecked, you need to double-tap on the key on the touch keyboard to press the key

Report Tool Tips > Report Tooltips

A checkbox that when checked tells NVDA to report tool tips as they appear. Many Windows and controls show a small message (or tool tip > A checkbox that when checked tells NVDA to report tooltips as they appear. Many Windows and controls show a small message (or tooltip

Help Balloons are like tool tips > Help Balloons are like tooltips

Uncheck this checkbox if you don't wish to have the description reported along with objects - it may be useful to give an example of a typical description that NVDA may encounter here

For example, when you enter text into the search box in Start menu in Windows Vista and later > For example, when you enter text into the search box in the Start menu in Windows 8 and later

As an example, if enabled, if the letter j was pressed, it would be trapped from reaching the document, even though it is not a quick navigation command nor is it likely to be a command in the application itself > As an example, if enabled, if the letter j was pressed, it would be trapped from reaching the document, even though it is not a quick navigation command nor is it likely to be a command in the application itself. If enabled, NVDA will tell Windows to play a default sound whenever a key is pressed that gets trapped.

When this option is enabled, NVDA will try to use the Microsoft UI Automation accessibility api in order to fetch information from Microsoft Word document controls > When this option is enabled, NVDA will try to use the Microsoft UI Automation accessibility API in order to fetch information from Microsoft Word document controls

Section 11.3 - we may wish to remove the laptop key assignments; they match their desktop counterparts

If the add-on was previously "enabled", a status will show "disabled after restart" Just like when you install or remove add-ons, you need to restart NVDA in order for changes to take effect > If the add-on was previously "enabled", the status will show "disabled after restart" - just like when you install or remove add-ons, you need to restart NVDA in order for changes to take effect

The Incompatible Add-ons Manager, which can be accessed via the "view incompatible add-ons" buttons in the Add-on manager > The Incompatible Add-ons Manager, which can be accessed via the "view incompatible add-ons" button in the Add-on manager

The Incompatible add-ons manager also has an "About add-on..." button. This opens will let you know the full details of the add-on, which is helpful when contacting the add-on author > The Incompatible add-ons manager also has an "About add-on..." button. This screen will let you know the full details of the add-on, which is helpful when contacting the add-on author

Please see extra voices page > please see the extra voices page

http://www.microsoft.com/download/en/details.aspx?id=27225 > https://www.microsoft.com/download/en/details.aspx?id=27225

http://www.microsoft.com/download/en/details.aspx?id=27224 > https://www.microsoft.com/download/en/details.aspx?id=27224

Quit already running copy of NVDA > Quit an already running copy of NVDA

Quit already running copy of NVDA and start this one > Quit an already running copy of NVDA and start this one

http://www.nvaccess.org/ > https://www.nvaccess.org/

### PR DESCRIPTION
**Pull request by Adriani90**
### Link to issue number:
fixes #9508.
Fixes #8689,
fixes #9131,
fixes #8579
fixes #8314
fixes #7888
fixes #7394 
fixes #6315

### Summary of the issue:
There are some examples missing in the user guide (i.e. regarding object description)and some text passages should be deleted (i.e. that eSpeak is the only synthesizer which suports infelction and change in pitch or automatic language switch). Also there are some miss spellings. Most links are still http: and not https:
There is also a description for the usage stats dialog missing.
Moreover, the description of help balloons is outdated, as well as the abbreviation for braille displays.
Also the description of -s command line option is outdated.
Some links for braille displays are outdated (i.e. baum and Seika).
A short description for comment editing in MS Excel with shift+f2 is missing.
A short note that the carret is also moved when pressing nvda+f10 if carret can reach the text is missing.
There is an inconsistency between copyright described in userguide and copyright described in license document. Exceptions are missing in user guide.

### Description of how this pull request fixes the issue:
- Edited the user guide accordingly and fixed the spelling errors. In the buildVersionInfo, the URL is a https: now as well as all other links in the user guide.
- A section 4.1.2 has been added to describe shortly the data usage stats dialog.
- "help balloons" has been extended to "notifications" and the description of the checkbox is now consistent with the settings pannel. The braille abbreviation in section 8.1 is now "ntfc" and not "hlp".
- The description of -s command line option includes more examples of what is disabled when entering secure mode (see referenced issue #8579).
- Links for Seika and Baum braille displays are uptodate.
- Added a short description of editing comment in MS Excel with shift+f2.
- Added a short note that carret is moved when pressing nvda+f10 and the carret can reach the text.
- Updated description on copyright and license

### Testing performed:
Ran NVDA from source and checked that formating is not changed and that links are working. Tested on a braille display that the ntfc abbreviation is shown properly. Ran -s --secure from command line and checked what is disabled.

### Known issues with pull request:
none
### Change log entry:
none

### CODE REVIEW

**Comment by DrSooom** [comment]
@Adriani90: Could you please take a look at issue #8689 as well? Thanks.

**Comment by DrSooom** [comment]
Is "ntfc" also displayed on Win7 instead of "hlp"?

**Comment by Adriani90** [comment]
@DrSooom yes because help balloons are also notifications. Even if there is a technical difference between help balloons and notifications, for users this is not of practical interest. Moreover, notifications is also the name of the checkbox in the settings pannel even on Windows 7 and this was not covered in the user guide.

**Comment by Adriani90** [comment]
Joseph could you please review this PR? I think for one PR this is ok now. For the second part I would raise a new one once this is merged. There are still some issues open with regard to the user guide.

**Review by josephsl — CHANGES_REQUESTED** [review]
Hi,

In usage stats section:

* Can you format sentences on their own lines? That way it can help translators translate the text better.
* Can you try separating paragraphs with a blank line? That way translators can focus on one thing at a time.
* I think rather than specifying which chapter to look for usage data, it would be best to add a dedicated section (starting with a heading) describing data that will be gathered. This is so that you don't have to change chapter numbers every time sections are added/changed/removed, as well as giving users a way to move to and read this section quickly.

On braille abbreviations section:

* ntfc: I think it would be best to find a better position for this, as this is a direct replacement for "hlp".

Thanks.

**Comment by Adriani90** [comment]
@josephsl I think I have addressed your comments above. Could you please check again? Thanks.

**Comment by Adriani90** [comment]
In the usage stats dialog, I have referenced the heading "gather usage data" which is already in cahpter 11 but I deleted the reference "chapter 11". I guess in the future the heading will not change even if the chapter number changes.

**Review by josephsl — APPROVED** [review]
@feerrenrut, do you think we can cherry-pick this into beta?

**Review by feerrenrut — CHANGES_REQUESTED** [review]
Thanks for all your work on this @Adriani90.

At the moment this is quite hard to review because it is handling so many different issues at once, please split this PR into multiple PR's. The changes in each PR should be relevant to a single goal if possible. 

There are unexpected changes to espeak in this PR, likely because a merge from master is required.

**Comment by Adriani90** [comment]
Ok it seems something weared is doing on with this branch. I tried everything, rebase, fetch etc. It still shows the eSpeak conflicts and I don't know why. I didn't touch eSpeak at all. I have also updated the submodules but no success. I will address the comments above in new pull requests based on my master branch and NV Access's master branch and I will close this one instead.

**Comment by fisher729** [comment]
Hi.

Any updates on this issue? Notifications vs. help balloons is a real worry for me, especially as it relates to new users.

**Comment by Adriani90** [comment]
I will close this PR for now and will address the issues separately in different PRs when I get some time. Sorry for any inconvenience.

**Pull request closed without merging**
