### PR TITLE
Fix say all error when on Desktop

### LINKED ISSUE #9947: Say all on Desktop raises an error
### Steps to reproduce:
1. Focus the desktop.
2. Invoke caret say all

### Actual behavior:
The following error is raised:

```
ERROR - scriptHandler.executeScript (15:54:57.769):
error executing script: <bound method GlobalCommands.script_sayAll of <globalCommands.GlobalCommands object at 0x05875770>> with gesture 'NVDA+a'
Traceback (most recent call last):
  File "scriptHandler.pyc", line 190, in executeScript
  File "globalCommands.pyc", line 1334, in script_sayAll
  File "sayAllHandler.pyc", line 79, in readText
  File "sayAllHandler.pyc", line 119, in nextLine
AttributeError: '_TextReader' object has no attribute 'reader'
ERROR - stderr (15:54:57.779):
Exception ignored in:
ERROR - stderr (15:54:57.790):
<function _TextReader.__del__ at 0x0462F390>
ERROR - stderr (15:54:57.803):
Traceback (most recent call last):
ERROR - stderr (15:54:57.815):
  File "sayAllHandler.pyc", line 213, in __del__
ERROR - stderr (15:54:57.827):
  File "sayAllHandler.pyc", line 206, in stop
ERROR - stderr (15:54:57.839):
AttributeError
ERROR - stderr (15:54:57.851):
:
ERROR - stderr (15:54:57.863):
'_TextReader' object has no attribute 'reader'
```

### Expected behavior:
NO error

#### NVDA installed/portable/running from source:
Installed

#### NVDA version:
threshold-18069

#### Windows version:
Windows 10 1903 build 18362.239

### PR DESCRIPTION
**Pull request by clementb49**
### Link to issue number:
fixes #9947
### Summary of the issue:
If say all was invoked in non-text, NVDA raise an error. 
### Description of how this pull request fixes the issue:
This PR check that the _TextReader object has an attribute reader
### Testing performed:
1. Focus the desktop.
2. Invoke caret say all
Check that produce no error. 
### Known issues with pull request:
None
### Change log entry:
None

### CODE REVIEW

**Comment by clementb49** [comment]
CC @leonardder

**Comment by feerrenrut** [comment]
Can you please resolve conflicts, and then request a review from me.

**Review by feerrenrut — CHANGES_REQUESTED** [review]

**Comment by feerrenrut** [comment]
Can you mention why you chose not to re-raise the exception?

With this current approach there is still `self.speakTextInfoState` and `self.numBufferedLines` (line 118) that are not set, leaving the instance invalid and susceptible to similar issues in the future.

**Comment by clementb49** [comment]
For you, what is the exception which should be raise?

**Comment by feerrenrut** [comment]
I think it should raise `NotImplementedError` and embed the information from the inner exception.

**Comment by clementb49** [comment]
I don't understand what I supose to do. 
If I raise an 'NotImplementedError' in the except block of the __init__ method, it makes no sense.

**Comment by feerrenrut** [comment]
I'm suggesting that you raise the exception in the init method, and where is used you catch that exception and return early. The class is used in only one place (inside method `def readText(cursor)` Line 76 and is a private class (it starts with an underscore) so it should not be used by addons.

The benefit of this is that a half made instance isn't created.

```
	def __init__(self, cursor):
		self.cursor = cursor
		self.trigger = SayAllProfileTrigger()
		self.trigger.enter()
		# Start at the cursor.
		if cursor == CURSOR_CARET:
			try:
				self.reader = api.getCaretObject().makeTextInfo(textInfos.POSITION_CARET)
			except (NotImplementedError, RuntimeError) as e:
				raise NotImplementedError("Unable to make text info") from e  # Wrap the exception so we can easily add logging to see what happened.
		else:
			self.reader = api.getReviewPosition()
```

Then in `def readText(cursor):`

```
def readText(cursor):
	global lastSayAllMode, _activeSayAll
	lastSayAllMode=cursor
	try:
		reader = _TextReader(cursor)
	except NotImplementedError as e:
		log.debugWarning("Unable to make reader", exc_info=True)
		return
	_activeSayAll = weakref.ref(reader)
	reader.nextLine()
```

**Comment by lukaszgo1** [comment]
@clementb49 Are you planning to work further on this? It looks like only remaining think to be done is addressing a Linter error.

**Review by feerrenrut — APPROVED** [review]
I don't think this needs a change log entry, I don't believe this is a user visible error in a release, though certainly annoying for alpha users.

**Comment by Adriani90** [comment]
There is still an error when pressing nvda+a on desktop (keyboard is laptop layout):

```
IO - inputCore.InputManager.executeGesture (16:31:52.864) - winInputHook (14656):
Input: kb(laptop):NVDA+a
DEBUG - config.ConfigManager._triggerProfileEnter (16:31:52.881) - MainThread (13592):
Activating triggered profile Sayall
DEBUG - synthDriverHandler.SynthDriver.loadSettings (16:31:52.890) - MainThread (13592):
Loaded changed settings for SynthDriver ibmeci
DEBUGWARNING - sayAllHandler.readText (16:31:52.894) - MainThread (13592):
Unable to make reader
Traceback (most recent call last):
  File "sayAllHandler.pyc", line 116, in __init__
  File "documentBase.pyc", line 24, in makeTextInfo
  File "textInfos\offsets.pyc", line 470, in __init__
  File "textInfos\offsets.pyc", line 249, in _getCaretOffset
NotImplementedError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "sayAllHandler.pyc", line 80, in readText
  File "sayAllHandler.pyc", line 118, in __init__
NotImplementedError: Unable to make TextInfo: 
ERROR - stderr (16:31:52.895) - MainThread (13592):
Exception ignored in:
ERROR - stderr (16:31:52.950) - MainThread (13592):
<function _TextReader.__del__ at 0x038A1978>
ERROR - stderr (16:31:53.027) - MainThread (13592):
Traceback (most recent call last):
ERROR - stderr (16:31:53.096) - MainThread (13592):
  File "sayAllHandler.pyc", line 252, in __del__
ERROR - stderr (16:31:53.148) - MainThread (13592):
  File "sayAllHandler.pyc", line 245, in stop
ERROR - stderr (16:31:53.202) - MainThread (13592):
AttributeError
ERROR - stderr (16:31:53.255) - MainThread (13592):
:
ERROR - stderr (16:31:53.321) - MainThread (13592):
'_TextReader' object has no attribute 'reader'
```

This causes following user impact:
* When creating a sayall profile which is deactivated, after pressing NVDA+a the error occurs and the sayall profile is applied. However, looking in the profiles dialog, the sayall profile is still deactivated although the settings from the sayall profile are currently applied. Very strange..

**Comment by Adriani90** [comment]
The only way to turn back to the settings before pressing nvda+a on desktop is to restart NVDA. Even activating and deactivating profiles does not work. The settings are not applied unless you restart NVDA.

**Pull request merged**
