### PR TITLE
fix 9524 Clean up outdated zh directories under locales

### LINKED ISSUE #9524: The zh folder under locales is outdated
### Steps to reproduce:
Switch Windows System language to Simplified Chinese 

### Actual behavior:
WARNING - characterProcessing.SpeechSymbols.load (23:24:32.983):
Invalid line in file locale\zh\symbols.dic: ﹩	錢號all	
### Expected behavior:
No warnings when loading
#### NVDA installed/portable/running from source:
Installed
#### NVDA version:
2019.1
#### Windows version:
Windows 8.1

### Other questions
The folder zh was introduced in this commit for espeak https://github.com/nvaccess/nvda/commit/d6fe1f5c42ac5096caf86a24725934b10dc30c2a
It also provide symbol and  characterDescriptions  for other zh locale which is not in transaltion SVN  repo like (zh_MO or zh_SG).
It comes from an old zh_TW translation which is outdated and contain format errors.
It would be better if we copy them at installation instead of storing it directly in repo.

#### Does the issue still occur after restarting your PC?
Yes

### PR DESCRIPTION
**Pull request by dpy013**
### Link to issue number:
fix #9524  
### Summary of the issue:
Currently, the zh directory under /locales has not been maintained for a long time.
See 9524 above for details of the problem
### Description of user facing changes
Nothing yet.
### Description of development approach
First the /locales/zh directory was deleted,
Then it was compiled using the local visual studio2022、
Finally, an installation file was created for testing.

### Test Details
Tests were performed using modified builds of the installed and portable versions, respectively,
Tested sapi4 and sapi5 speech synthesizers in Simplified Chinese, typing and browsing the desktop worked fine.
Also checked the /locale directory after compilation and the /locale directory in the installed version, and the zh directory was cleared correctly.

### Testing strategy:
Also need to test appveyor compiled builds
### Known issues with pull request:
Nothing yet.
### Code Review Checklist:

- [ ] Documentation:
  - Change log entry
  - User Documentation
  - Developer / Technical Documentation
  - Context sensitive help for GUI changes
- [ ] Testing:
  - Unit tests
  - System (end to end) tests
  - Manual testing
- [ ] UX of all users considered:
  - Speech
  - Braille
  - Low Vision
  - Different web browsers
  - Localization in other languages / culture than English
- [ ] API is compatible with existing add-ons.
- [ ] Security precautions taken.

@coderabbitai summary

### CODE REVIEW

**Comment by cary-rowen** [comment]
Is #9524 pending implementation?
Can you answer the question raised by [this comment](https://github.com/nvaccess/nvda/issues/9524#issuecomment-1871685405)?

**Comment by CyrilleB79** [comment]
At the time of #9524, there were an issue blocking the removal of the zh folder due to  symbol pronunciation issue with eSpeak mandarin)? See https://github.com/nvaccess/nvda/issues/9524#issuecomment-516880870 for details.

Is it now fixed on eSpeak's side?

**Comment by dpy013** [comment]
> At the time of #9524, there were an issue blocking the removal of the zh folder due to symbol pronunciation issue with eSpeak mandarin)? See [#9524 (comment)](https://github.com/nvaccess/nvda/issues/9524#issuecomment-516880870) for details.
> 
> Is it now fixed on eSpeak's side?

hello @CyrilleB79 
I just did the following test with nvda_snapshot_pr17105-33739,0238c041.exe.
I first typed the text in Notepad using eSpeak NG.
Then use the left and right arrows to go through the text word by word.
eSpeak NG reports what was typed properly.
Also I tested the text entered in notepad using sapi4 and sapi5.
Then still using the left and right arrows to browse word by word.
sapi4 and sapi5 report what is typed correctly.
The logs will be attached below

**Comment by dpy013** [comment]
[nvda.log](https://github.com/user-attachments/files/16845306/nvda.log)

**Review by seanbudd — APPROVED** [review]

**Pull request merged**
