### PR TITLE
Add apropriate messages when interacting with empty status lines 

### LINKED ISSUE #7789: Repeat read status bar command 3 times on empty status bar announces nothing
From https://github.com/nvaccess/nvda/issues/1785#issuecomment-345228357 on PR "Make the Read status bar command copy its contents on third press like Report window title"

### Steps to reproduce:
1. Find an empty status bar
1. Press `NVDA+end` (desktop) or `NVDA+shift+end` (laptop) 3 times

### Pre-existing behaviour (other features)
We should try to be consistent with existing features here, or make them consistent

Report title: On an application with not title, pressing `NVDA+t` 3 times you get "no title application" copied to the clipboard and that is also what is announced, ie "no title application copied to clipboard"

Mark start, mark end, copy range:  with `NVDA+F9`, then `NVDA+F10`  twice. I am not able to think of a situation where you can create an empty selection and copy it. 

### Actual behavior:
When the status bar is empty and the read status bar command is triggered, blank is reported. When pressed 3 times, nothing is announced.

### Expected behavior:
I think something should be announced to acknowledge the command in both cases. In the first perhaps "no status bar information" in the the second "unable to copy status bar to clipboard"

I would suggest that in the (rare) case of a blank application title being copied, the behaviour should match.

### PR DESCRIPTION
**Pull request by lukaszgo1**
### Link to issue number:
Fixes #7789
### Summary of the issue:
When user reads empty status line the message "blank" is spoken and when attempting to copy it nothing is announced.
### Description of how this pull request fixes the issue:
When user attempts to read, spell or copy empty status line appropriate message is presented.
### Testing performed:
Tested with Firefox status bar. I'm aware, that Firefox's status bar is simply a badly implemented and not exactly empty, but i cannot find a app with real empty status bar.
### Known issues with pull request:
None
### Change log entry:

Section: Bug fixes

When user interacts with empty status bar NVDA will now inform user about it.

### CODE REVIEW

**Comment by josephsl** [comment]
Hi,

Apparently there is an indentation error in global commands file (line 1395), and Appveyor complains about this.

Thanks.

**Review by josephsl — DISMISSED** [review]
Hi,

Besides going over indentation error, you can do this by simply adding a check for empty text right before counting how many key presses were there. You can do it in two ways:

1. Combine check for no status bar object along with empty text so NvDA will say, "no status line found".
2. Adding a check for empty string, and if it is truly empty, you can say, "no status line text found".

Thanks.

**Comment by josephsl** [comment]
Hi,

A tip: checking for empty text right before counting script count instead of going through each script count case makes this change way simpler to debug and saves bytecode generation.

Thanks.

**Comment by lukaszgo1** [comment]
Hi @josephsl
Your approach has in my opinion one important disadvantage and it is the fact, that regardless of the user action the same message about empty status bar will be presented.

**Comment by josephsl** [comment]
Hi, I’d argue that your approach has the same disadvantage: noa matter how many times users perform status bar command, it’ll say “no status bar information”, which is the same thing as announcing this info right away. Thanks.

**Comment by lukaszgo1** [comment]
Not really, because when user attempts to copy status bar content
different message is presented.

On Mon, 02 Jul 2018 14:12:13 -0700
Joseph Lee <notifications@github.com> wrote:

Hi, Id argue that your approach has the same disadvantage: noa matter how many times users perform status bar command, itll say no status bar information, which is the same thing as announcing this info right away. Thanks.

**Comment by lukaszgo1** [comment]
i've done it in this way, because in #7789 @feerrenrut says
> Expected behavior:
I think something should be announced to acknowledge the command in both cases. In the first perhaps "no status bar information" in the the second "unable to copy status bar to clipboard"

**Comment by feerrenrut** [comment]
>Expected behavior:
I think something should be announced to acknowledge the command in both cases. In the first perhaps "no status bar information" in the the second "unable to copy status bar to clipboard"

I think the reason behind this was to highlight difference in the two actions. It reflects that, despite attempting both similar but distinct actions, neither is able to succeed.

**Comment by lukaszgo1** [comment]
@Andre9642 Thanks for the tip.

**Review by feerrenrut — DISMISSED** [review]

**Review by feerrenrut — APPROVED** [review]

**Pull request merged**
