### PR TITLE
Separate the reporting of superscripts and subscripts from the report font attributes setting

### PR DESCRIPTION
**Pull request by codeofdusk**
### Link to issue number:
Related to #3727.

### Summary of the issue:
The reporting of superscript and subscript is controlled by the "report font attributes" setting (which is far too verbose for reading of mathematical/scientific documents using the `<sup>`/`<sub>` HTML tags).

### Description of how this pull request fixes the issue:
Adds a new setting, "report superscripts and subscripts", which controls whether superscripted/subscripted text is read.

### Testing performed:
With all possible combinations of "report superscripts and subscripts" and "report font attributes", tested that HTML documents in Chrome using the `<sup>` tag read correctly and that no non-selected formatting information is reported.

### Known issues with pull request:
I'm not sure how to make this work in Braille – does NVDA even present superscripts/subscripts to Braille displays?

### Change log entry:

== Changes ==
- The reporting of superscripts and subscripts is now controlled separately to the reporting of font attributes. (#10919)

### CODE REVIEW

**Comment by leonardder** [comment]
I think text position is ambiguous, as alignment also says something about the position of the text.
May be `report script changes` or `report subscript and superscript`?

**Comment by codeofdusk** [comment]
> I think text position is ambiguous, as alignment also says something about the position of the text.
> May be `report script changes` or `report subscript and superscript`?

Fixed.

**Comment by leonardder** [comment]
SOrry for me not being explicit enough

I think that it is ok to call the option reportScript, as that's way shorter than reportSubScriptsAndSUperScripts. At first glance, you could leave the label as is, may be @feerrenrut has suggestions as what wording is used to cover both sub and superscript

Could you also add a config spec update that:

- If report attributes is off (default), report script stays off
- If report attributes is on, turn on script as well.

**Comment by codeofdusk** [comment]
I prefer "report superscripts and subscripts" to "report script".

**Review by feerrenrut — APPROVED** [review]
Thanks @codeofdusk

**Comment by josephsl** [comment]
Hi,

I'm afraid this introduced a regression: a KeyError exception is raised when NVDA+F is pressed to obtain formatting information.

Thanks.

**Comment by josephsl** [comment]
Traceback:

ERROR - scriptHandler.executeScript (20:38:42.761) - MainThread (3928):
error executing script: <bound method GlobalCommands.script_reportFormatting of <globalCommands.GlobalCommands object at 0x07620F10>> with gesture 'NVDA+f'
Traceback (most recent call last):
  File "scriptHandler.pyc", line 205, in executeScript
  File "globalCommands.pyc", line 1435, in script_reportFormatting
  File "globalCommands.pyc", line 1401, in _reportFormattingHelper
  File "textInfos\__init__.pyc", line 564, in getFormatFieldSpeech
  File "speech\__init__.pyc", line 2181, in getFormatFieldSpeech
KeyError: 'reportSuperscriptsAndSubscripts'


This is seen when pressing NVDA+F from browse mode documents. Thanks.

**Comment by Adriani90** [comment]
Is it possible to exclude the reporting of baseline when pressing quick navigation key in browse mode? When I enabe superscripts and subscripts, NVDA always reports "base line" when I press quick navigation keys (i.e. b for buttons in the commenting area). This is quite annoying on some websites. This should be only reported when NVDA detects a mathematical content or if this is part of a text block while navigating with ready commands.

**Comment by codeofdusk** [comment]
Most likely, open a separate issue and hopefully someone will take it.

**Comment by ABuffEr** [comment]
Hi,
sorry, @codeofdusk , but I'm confused by this feature. If I enable or disable it, what should it happen reading
`A<sup><em>i,j</em></sup>`
in a web page? I notice no differences in Chrome or Firefox, excluding what reported by @Adriani90.

**Pull request merged**
