### PR TITLE
Add find functionality to the log viewer

### PR DESCRIPTION
**Pull request by dkager**
First shot at #4929: find functionality in the log viewer. This involved a good bit of copy-catting code from cursorManager and textInfos/offsets. In particular, the FindDialog is virtually identical to that of cursorManager. This dialog could easily be generalized and put in the gui package but that's probably a topic for another issue.

Some other implementation notes:
- Besides performing a case sensitive search you can also supply a regular expression, e.g. to find all errors logged between 8 PM and 9 PM. I figured developers won't get confused by this option and may find it useful.
- The entire text buffer is grabbed from the control and then truncated and/or reversed according to the type of search. With a large log, say 5MB this could be a problem, though I had no trouble while testing with very large strings.
- I added some punctuation to the cursorManager find messages so they are identical to logViewer's.
- Also renamed `onSaveAsCommand` to `onSaveAs` to conform with the other function names.
- I assumed the user wants to preserve both the case sensitivity and regex options across searches, i.e. #5522. We probably want to decide on this for both cursorManager and logViewer so the behavior is consistent.
- Instead of passing a bunch of parameters to FindDialog, e.g. `_lastFindText`, it could also access them directly on the singleton LogViewer instance. I chose to use parameters because this makes it a bit easier to generalize this dialog later.
- When you use the `SetInsertionPoint` function on wx.TextCtrl braille scrolls to the new position but speech doesn't announce anything. So instead I chose to select the matched text, which is also what Notepad and other text editors do anyway. That appears to speak properly, but it could be that I'm forgetting to do something here.

### CODE REVIEW

**Comment by dkager** [comment]
Fixed the merge conflict.
I would appreciate feedback on this implementation. IMO the functionality is still useful.

**Comment by leonardder** [comment]
> This dialog could easily be generalized and put in the gui package but that's probably a topic for another issue.

I think I disagree here. Personally, I'd do a pr with the find dialog in generalized form. Python console output and add-ons can also benefit from this, and regular expression support in browse mode find would also be nice. Furthermore, you can utilize guiHelper in the generalisation process.

**Comment by dkager** [comment]
Note that guiHelper wasn't a thing at the time of this PR. Also, the browse mode find dialog doesn't have regex, so that would have to be made optional in the generalization.

I would prefer to discuss the implementation of the find routine and its usefulness before spending more time on the GUI.

**Comment by leonardder** [comment]
@dkager: What is the actual status of this? Do you still belief this is ready for review, or do you want to have some discussion happening beforehand?

**Comment by dkager** [comment]
I was going to use guiHelper, but am pretty swamped till the end of the year so it's on hold. :(

**Comment by bdorer** [comment]
I like the feature. It is useful if you try to reproduce errors you want to create tickets for. May this could be implemented and the generalisation of the search dialog at a later time.

**Comment by leonardder** [comment]
@feerrenrut: your opinion about the find routine would be valuable here, as @dkager wants to have some discussion about that re https://github.com/nvaccess/nvda/pull/5526#issuecomment-311101402

**Review by feerrenrut — COMMENTED** [review]
Looks ok, but I feel it would be easy to miss logic errors in functionality like this. I think it would make sense to extract the search functionality, and unit test it. Then ideally re-use it for all search functionality. Similarly the GUI components could be extracted and shared.

**Comment by dkager** [comment]
The idea to refactor sounds good. I will make this a weekend project whenever a free weekend presents itself.

**Comment by josephsl** [comment]
Hi,

To @DKager: Before someone reviews this, could you mind rebasing this on master so at least it can be built on Appveyor please?

Thanks.

**Comment by dkager** [comment]
Closing as horribly out of date.

**Pull request closed without merging**
