### PR TITLE
Test PR after line ending normalization, with conflicts before normalizations

### PR DESCRIPTION
**Pull request by seanbudd**
This PR is a test sample for #12387 
This PR simulates an open PR to master, of a branch created before normalization, with conflicts that exist before normalization, after normalization has occurred on master.

In this case `test-normalized-line-endings` has had all line endings changed to LF using the process in #12816 - this simulates origin/master after normalization.
`test-old-master-with-conflicts` has been branched from master, without normalization. The branch has had a small change applied to a file with CRLF line endings, in a way that causes merge conflicts with master, without normalization.

### Message for contributors

~~~md
NVAccess has updated the NVDA repository to make the line endings normalized to LF. 
This created merge conflicts, as this PR has existing merge conflicts this cannot be fixed this fully resolved automatically.
Updating the git config for the local repository will automatically resolve the conflicts created by line ending normalization.
```sh
git config --local merge.renormalize true
```

Then the remaining merge conflicts can be resolved by fetching and merging in master.
```sh
git fetch origin/master
git merge origin/master
```

* Project overview: #12387
* Detailed implementation and justification: #12816.
~~~

### CODE REVIEW

**Comment by seanbudd** [comment]
@feerrenrut  @michaelDCurran - https://github.com/nvaccess/nvda/labels/blocked%2Fmerge-conflicts contains all blocked PRs due to merge conflicts

**Comment by feerrenrut** [comment]
Those all look pretty straightforward to resolve. Though I'm curious, why aren't there any draft PRs in the list?

**Comment by seanbudd** [comment]
> Those all look pretty straightforward to resolve. Though I'm curious, why aren't there any draft PRs in the list?

Either "Conflicting files" isn't always accurate or coincidence. I've triple checked all PRs now, by checking for "Conflicting files" at the bottom of the PR.

**Comment by feerrenrut** [comment]
This PR has conflicts, but perhaps intentionally excluded? The draft PRs I expected to have conflicts don't. I wonder if the check is disabled if they have been drafts for a while?

For instance, if I manually checkout https://github.com/nvaccess/nvda/pull/10556 and try to merge in origin/master locally I get conflicts.

**Comment by seanbudd** [comment]
Yes the two PRs targeting `test-normalized-line-endings` are excluded.

**Pull request closed without merging**
