### PR TITLE
Added Lithuanian locale files

### PR DESCRIPTION
**Pull request by rimas-kudelis**
This is a near-complete Lithuanian locale for NVDA. Only a handful strings are missing or marked fuzzy – those which I wasn't sure how to translate properly.
It would be great if you could accept it before freezing your codebase for the upcoming release.

### CODE REVIEW

**Comment by rimas-kudelis** [comment]
Hm, I just noticed that the punctuation and symbols dialog now lists extended symbols defined in both English and Lithuanian files, which means they are duplicated (because I merely translated their names, such as "sentence ending"). Is this a bug or a feature? If it's a feature, I guess I should rename the ones in my file back to English?

**Comment by josephsl** [comment]
Hi, The best place to send them would be the NVDA translations mailing list. I vaguely remember someone working on this translation a few months ago – if that’s you, feel free to let the translations list know that you are submitting this work. Thanks.

**Comment by rimas-kudelis** [comment]
No Joseph.

No, it wasn't me, it was Paulius Lėveris. However, I'm in contact with him and he's currently beta-testing my work. Furthermore, now that this huge initial amount of work is done, I hope he will be able to take it over from me from here, so that instead of being the main localizer I can just help him if and when necessary.

Can you clarify if your e-mail means this pull request will not be accepted at all, or if you're just saying that Github is not the preferred medium for submitting translations? If it's the former, I hope there is a way for Paulius to submit my work to SVN? By the way, has he submitted anything up till now?

**Comment by josephsl** [comment]
Hi, I’m reluctant to work with this pull request (@jcsteh may have different opinions) – the preferred place to send things like this is the translations mailing list, as we experienced an issue with another language just before NVDA 2016.3 was released, and we don’t want to go through that again. Thanks.

**Comment by rimas-kudelis** [comment]
I'll talk to Paulius. Can you answer my other questions? These are:
1.  I noticed that the punctuation and symbols dialog now lists extended symbols defined in both English and Lithuanian files, which means they are duplicated (because I merely translated their names, such as "sentence ending"). Is this a bug or a feature? If it's a feature, I guess I should rename the ones in my file back to English?
2. I hope there is a way for Paulius to submit my work to SVN? By the way, has he submitted anything up till now? I'm asking this just to assess his experience with Subversion, since we're on a really tight schedule here.

**Comment by jcsteh** [comment]
> I noticed that the punctuation and symbols dialog now lists extended symbols defined in both English and Lithuanian files, which means they are duplicated (because I merely translated their names, such as "sentence ending"). Is this a bug or a feature? If it's a feature, I guess I should rename the ones in my file back to English?

They should have the same names as in English so they override English, since all languages inherit from English. However, when you define the symbol in the symbols section (not the complexSymbols section), you can include a display name at the end of the symbol so that it appears in your language. For example:

```
. sentence ending	dot	all	always	# full stop sentence ending
```

where "full stop sentence ending" is my example translation.

> Can you clarify if your e-mail means this pull request will not be accepted at all, or if you're just saying that Github is not the preferred medium for submitting translations?

Translations need to be submitted via the translations svn, as this ensures they get automatically synced in both directions and that automated checks are performed. So, we cannot accept this pull request. However, if you can't submit your work to svn, we will either help you with that or (at least for now) submit it via svn ourselves.

> If it's the former, I hope there is a way for Paulius to submit my work to SVN?

I imagine he should have access to the repository. Either way, I think it would probably make sense to get you set up with svn, since it'll be easier to submit changes even if you are only doing so occasionally from now on. @josephsl, do you have time to help with this?

> By the way, has he submitted anything up till now?

No, unless I'm missing something.

**Comment by rimas-kudelis** [comment]
> They should have the same names as in English so they override English, since all languages inherit from English. However, when you define the symbol in the symbols section (not the complexSymbols section), you can include a display name at the end of the symbol so that it appears in your language.

Aha! One more question about this: I assume I can override the English regexp, right?

**Comment by jcsteh** [comment]
Yes you can.

**Comment by rimas-kudelis** [comment]
Awesome. I've updated the PR accordingly.

**Comment by josephsl** [comment]
Hi, please ask Paulius to email me directly so he can send your work to me and that I can include it in SVN this weekend on his behalf. Or, let Paulius send an email to the translations mailing list, and ask him to attach your work so I or someone can enter it into our system. Thanks.

**Comment by rimas-kudelis** [comment]
Paulius says he committed my translation to SVN yesterday. It would be great if you could check and make sure everything is fine and the locale can be included.
I have a few other questions, but I guess I'll ask them on the mailing list.

**Comment by josephsl** [comment]
Hi, got the files. Thanks.

**Comment by rimas-kudelis** [comment]
So, my translation is now in SVN, but it wasn't synced to git when the sync happened 3 days ago. How come?

**Comment by jcsteh** [comment]
Automatic syncs happen every Friday, but lt wasn't included due to a misconfiguration. I forced a manual sync. It was added in 52348ad4.

Technical: The system only considers languages which have a settings file. @josephsl added a settings file recently, but that was after the automatic sync. The next automatic sync would have picked this up, but I figured it was best to get this in ASAP so it can be verified, hence the manual sync.

**Pull request closed without merging**
