### PR TITLE
Allow adding emulated system keyboard keys in the Input Gestures GUI

### LINKED ISSUE #6060: Custom emulated system keyboard keys
Several braille display drivers add emulated system keyboard keys to NVDA, such as escape or alt. It might be an interesting feature if one could add other keys for emulation, for example when one wants to add an emulated system keyboard key to a braille function key which they can't choose by default.
I'd suggest adding a separate button to the imput gestures dialog "Add emulated system keyboard key", which allows you to press a random key on the keyboard which is than added to the emulated system keyboard keys category in the dialog. After that, one should be able to add a gesture to it.

### PR DESCRIPTION
**Pull request by LeonarddeR**
### Link to issue number:
Closes #6060.

### Summary of the issue:
In the current situation, emulated system keyboard key scripts can only be added in gestures.ini or by updating a gesture map programmatically.

### Description of how this pull request fixes the issue:
Allows adding custom emulated system keyboard keys from the input gestures gui, by selecting the category root tree view item and pressing add. An user will be able to enter a gesture to emulate, the entered gesture will be added to the tree view as a regular script and can be assigned as normal.

### Testing performed:
Added and removed several gestures from the gui.

### Known issues with pull request:
Some minor UX problems regarding adding and removing custom emulated keys:

1. When adding an emulated key without assigning it, an user can also press the remove button, in which case the emulated script disappears.
2. Same is the case when adding a new emulated key, assigning it and then unassigning it.
3. When you add a custom emulated key and then close the dialog, the custom emulated key is lost. This is documented in the user guide.
4. When you add an emulated key and assign it, then save, the remove the assignment, you can't remove the emulated script. After saving again, the emulated script will be removed anyway.

These issues have to do with the fact that we can't reliably check from the input gestures dialog whether a custom emulation script is part of the user gesture map or another map. IN the latter case, removal should be unsupported. Thus, explicit removal of an emulated script is only possible when it has been added during that instance of the input gestures dialog.

Honestly, I think these are trivial issues, so I'm filing this pr to let initial review take place and discuss the limitations in the current implementation.

### Change log entry:
* New features
    + New emulated system keyboard keys can be added from NVDA's Input gestures dialog. (#6060)
        - To do this, press the add button after you selected the Emulated system keyboard keys category.

### CODE REVIEW

**Comment by dan1982code** [comment]
I notice that moving to "emulated system keyboard keys" and then tabbing does not show the "add" button. I have to hit down arrow once to get to my first emulated key, and then tabbing gets me to the "add" button.

Thank you thank you for adding this. It's super-important for configuring braille displays without having to go into gestures.ini.

**Comment by dan1982code** [comment]
My fault. I thought the PR was incubating. Please ignore. I will run from source now and test further.

**Comment by feerrenrut** [comment]
@dan1982code did you end up testing this?

**Review by feerrenrut — DISMISSED** [review]
I'm not really sure how to test this myself, so hopefully it gets a good workout while incubating.

**Comment by leonardder** [comment]
@feerrenrut, thanks for incubating this. What do you think about the UX issues I outlined above?

@dan1982code: Have you been able to do any tests while running from source? The pr is now incubating, so you should be able to test this from the next branch.

**Comment by dan1982code** [comment]
I was running into a bug before (running from source) where Add wasn't active, but now I can add and Remove successfully. I'm testing with a Brailliant BI here -- a braille display is the key scenario for this PR, I think. So far so good, but I'll test more systematically today and report again.

**Comment by leonardder** [comment]
[**@dan1982code**](https://github.com/dan1982code) commented on [24 jan. 2018 15:03 CET](https://github.com/nvaccess/nvda/pull/7784#issuecomment-360145167 "2018-01-24T14:03:49Z - Replied by Github Reply Comments"):
> I was running into a bug before (running from source) where Add wasn't active...

Are you sure you were running from the correct branch? It should actually be quite impossible for the add button to be inactive on the emulated categories root.

**Comment by dan1982code** [comment]
I was confident that I was using the right source branch, but now I don't know, because I've tried many times today, after computer/NVDA restart etc., and can't reproduce the add button not working. Sorry for the trouble -- all seems fine here now.

**Comment by derekriemer** [comment]
This fails if you do the following:

1. Add on emulated keys.
2. press nvda+1
3. Go into that, and add a gesture, then press d, select all layouts.
4. Now, hit okay, and type d somewhere.

**Comment by leonardder** [comment]
Interesting catch there. This is because keyboardHandler.KeyboardInputGesture.fromName does not know about the NVDA key, which has been fixed as part of #7843. However, when applying that fix, I noticed some other bugs with KeyboardInputGesture.fromName.

```
>>> keyboardHandler.KeyboardInputGesture.fromName("control+l").displayName
u'ctrl+l'
>>> keyboardHandler.KeyboardInputGesture.fromName("l+control").displayName
u'+ctrl'
```

I will commit a fix for that issue tomorrow. I will also write unit tests for the NVDA key as well as several edge cases KeyboardInputGesture.fromName should cover. Furthermore, we really want to have emulate scripts show up as NVDA+1, and definitely not 1+NVDA.

**Comment by derekriemer** [comment]
Interesting, so we'll need to prioritize modifiers.

**Comment by leonardder** [comment]
[**@derekriemer**](https://github.com/derekriemer) commented on [26 Jan 2018, 05:54 CET](https://github.com/nvaccess/nvda/pull/7784#issuecomment-360684221 "2018-01-26T04:54:41Z - Replied by Github Reply Comments"):
> Interesting, so we'll need to prioritize modifiers.

Somehow, yes. The current code just assumes that the last key in the sequence is the main key and the others are modifiers.

**Comment by leonardder** [comment]
@feerrenrut: Could you please review the last 4 commits? Note that 8581b12e1d034f5bfef09adae576461f42df2023 has already been approved by @michaeldcurran as part of #7843.

**Comment by feerrenrut** [comment]
> What do you think about the UX issues I outlined above?

It's hard for me to judge these, I don't think there is any way I can play with this myself. Can you think of any way these issues could be addressed?

**Review by feerrenrut — APPROVED** [review]

**Comment by michaelDCurran** [comment]
Is there actually something holding this back, or is this okay to be merged to master?

**Comment by leonardder** [comment]
I belief there are still some UX issues that need to be discussed here:

1. When you add a custom emulated key and then close the dialog, the custom emulated key is lost. This is documented in the user guide.
2. When you add an emulated key and assign it, then save, the remove the assignment, you can't remove the emulated script. After saving again, the emulated script will be removed anyway.

As for the latter point, this is because from the input gestures dialog, we can't distinguish between the several gesture maps, built-in or user. Of course, someone shouldn't be allowed to remove an emulation script that is part of a built-in map, such as a braille display map.

**Comment by leonardder** [comment]
@feerrenrut: This is incubating for quite a long time now. Though I still believe there are some issues regarding UX, I'm afraid they are quite hard to fix within the scope of this pr. Therefore, I think we could consider a merge to master.

**Comment by michaelDCurran** [comment]
I recently recreated next. However I could not merge this pr due to conflicts. As future work still needs to occur here, and due to conflicts, leaving this out of next for now.

**Comment by leonardder** [comment]
I just fixed the conflicts, but it makes sense to do some additional 
discussion about the UX issues first.

**Comment by leonardder** [comment]
I believe I made this fully python 3 ready now. Won't have the time to look into this any time soon, though.

**Comment by dingpengyu** [comment]
hello
Is the current pr ready to merge?
thanks

**Comment by feerrenrut** [comment]
@dingpengyu Please don't make comments like this, we are aware of this PR. 

The last comment from the author indicated remaining issues, which have not been resolved.

> I just fixed the conflicts, but it makes sense to do some additional discussion about the UX issues first.

**Comment by leonardder** [comment]
This pr is now pretty old and with the UX issues still there, I'm afraid it's getting nowhere without major refactoring, for which I don't have the time now. I'm tempted to close this, donating the code to whoever is interested to take this further.

**Comment by feerrenrut** [comment]
If you are happy for someone else to take this on. You can leave it open for now, I'll apply the abandoned label.

**Comment by leonardder** [comment]
Sure I am. This abandoned label is a nice addition.

**Comment by Adriani90** [comment]
cc: maybe @JulienCochuyt or @Andre9642 could be interested in working on this further?

**Comment by michaelDCurran** [comment]
This pr now contains some pretty big conflicts in gui/settingsDialogs.py probably due to the merging of #10307.
  @feerrenrut  or @JulienCochuyt   either of you may have a better chance at merging master and fixing these conflicts than me.

**Comment by JulienCochuyt** [comment]
@michaelDCurran wrote:
> This pr now contains some pretty big conflicts in gui/settingsDialogs.py probably due to the merging of #10307.

Indeed, we kinda stepped on each other feet here.
@feerrenrut, I won't be able to give it a proper look before the end of the week due to customer obligations.
Let me know if you prefer I try to tackle this one nevertheless.

By the way, this led me to re-read my old code for PR #10307 and notice two errors I made that you'll hopefully help me fix by considering merge of the fix-up PR #11338.

**Comment by dingpengyu** [comment]
hello all
pr 11338 It has been merged.
Whether or not to merge the master discerning fixes source/gui/settingsDialogs .py conflict issues?
thanks

**Comment by feerrenrut** [comment]
@JulienCochuyt Yes, I'll take a look at this.

**Comment by feerrenrut** [comment]
Closing as superseded by #11402

**Pull request closed without merging**
