### PR TITLE
Encapsulate NVDA state write paths

### PR DESCRIPTION
**Pull request by seanbudd**
### Link to issue number:
None

### Summary of the issue:
NVDA uses a variety of paths to write to.
These can be hard to discover or track in the code, as write paths are not stored in globally available named symbols.
For example, if a developer wishes to find code instances where NVDA writes to the profile config directory, searching "profile" will yield additional results, e.g. code comments.

### Description of user facing changes
N/A

### Description of development approach
Created a centralised class to list all available write paths in NVDA.
This improves discoverability of write paths.

### Testing strategy:
Ran NVDA, tested saving some config options.

### Known issues with pull request:
None

### Change log entries:
For Developers

```
``speechDictHandler.speechDictVars.speechDictsPath`` is deprecated, instead use ``WritePaths.speechDictsDir``
```

### Code Review Checklist:

- [x] Pull Request description:
  - description is up to date
  - change log entries
- [x] Testing:
  - Unit tests
  - System (end to end) tests
  - Manual testing
- [x] API is compatible with existing add-ons.
- [x] Documentation:
  - User Documentation
  - Developer / Technical Documentation
  - Context sensitive help for GUI changes
- [x] UX of all users considered:
  - Speech 
  - Braille
  - Low Vision
  - Different web browsers
  - Localization in other languages / culture than English
- [x] Security precautions taken.

### CODE REVIEW

**Review by michaelDCurran — APPROVED** [review]

**Comment by ultrasound1372** [comment]
I have a known issue to this, do I submit it here or create a new issue? This is an API breaking change that unexpectedly broke some add-ons available.

**Comment by seanbudd** [comment]
Please create a new issue - thanks

**Comment by ultrasound1372** [comment]
That and enhanced dictionaries. Looking at the code it looks like there is supposed to be an alias and deprecation warning but it doesn't seem to work.

**Comment by ruifontes** [comment]
@ultrasound1372 , it works, but the information given by @seanbudd  is missleading...
You have to use:
speechDictHandler.WritePaths.speechDictsDir
and not only WritePaths.speechDictsDir...

**Comment by ruifontes** [comment]
@seanbudd , if this broke, at least two add-ons, it should not be done in 2024.1?
Normally, it should remain as a deprecation untill 2024.1, but in the new Alphas the old way do not work at all...

**Comment by seanbudd** [comment]
As mentioned earlier - please open an issue so we can track this.

Note, that removing relative imports is not an API breaking change. API consumers should import symbols from the original place.

For example, `WritePaths` should be imported from `NVDAState`, not `speechDictHandler`. `speechDictsDir` should have originally been imported from `speechDictHandler.speechDictVars` not `speechDictHandler` directly. The alias and deprecation warning should work correctly if the add-on's original import was from the correct module.

**Pull request merged**
