### PR TITLE
Rename statistic checkbox in general settings

### PR DESCRIPTION
**Pull request by Nael-Sayegh**
### Link to issue number:
closes 16136

### Summary of the issue:
Rename the checkbox In general panel: "Allow the NVDA Project to gather NVDA usage statistics"

### Description of user facing changes
The checkbox change of name from "Allow the NVDA Project to gather NVDA usage statistics" to "Allow NV Access to gather NVDA usage statistics".

### Description of development approach
I changed the string of the checkbox in settings files.

### Testing strategy:
go to nvda menu > preferences > settings > general and see the modifications name on the checkbox

### Code Review Checklist:

- [x] Documentation:
  - Change log entry
  - User Documentation
  - Developer / Technical Documentation
  - Context sensitive help for GUI changes
- [x] Testing:
  - Unit tests
  - System (end to end) tests
  - Manual testing
- [x] UX of all users considered:
  - Speech 
  - Braille
  - Low Vision
  - Different web browsers
  - Localization in other languages / culture than English
- [x] API is compatible with existing add-ons.
- [ ] Security precautions taken.

### CODE REVIEW

**Comment by CyrilleB79** [comment]
@Nael-Sayegh, please also update the User Guide. Thankks.

**Comment by Nael-Sayegh** [comment]
@CyrilleB79 I just updated the user guide. I don't think it's necessary to write these changes in the changelog?

**Comment by Nael-Sayegh** [comment]
As #16136 owns the 2024.1 milestone, should we ask for a merge into master or beta?

**Comment by CyrilleB79** [comment]
> As #16136 owns the 2024.1 milestone, should we ask for a merge into master or beta?

I'd say that you should ask a merge in beta branch. Thus you should:
* rebase your branch on beta and push it
* change the target branch of this PR; you can do it clicking on the "Edit" button of the title of this PR.

If you need more help, just let it know.

**Comment by CyrilleB79** [comment]
@Nael-Sayegh why did you close this / remove your branch?

If it was an error, there is a "restore" button to restore your branch on the PR's page.

**Comment by Nael-Sayegh** [comment]
@CyrilleB79 Following the branch changes, I encountered a problem and had to start my work over.
I will open another PR with the changes.

**Pull request closed without merging**
