### PR TITLE
Add shortcut for audio panel

### PR DESCRIPTION
**Pull request by seanbudd**
### Link to issue number:
Fixup of #15472 

### Summary of the issue:
A default gesture to open the new audio panel is desirable

### Description of user facing changes
Adds `nvda+ctrl+u` as a command to open the audio panel

Commands for opening settings panels are now included in the key commands doc

### Description of development approach
Adds `nvda+ctrl+u` as a command to open the audio panel

Adds keyCommands to the appveyor build for easier review of changes.

Updates to user guide

### Testing strategy:
test using the command
### Known issues with pull request:
None
### Code Review Checklist:

- [x] Documentation:
  - Change log entry
  - User Documentation
  - Developer / Technical Documentation
  - Context sensitive help for GUI changes
- [x] Testing:
  - Unit tests
  - System (end to end) tests
  - Manual testing
- [x] UX of all users considered:
  - Speech 
  - Braille
  - Low Vision
  - Different web browsers
  - Localization in other languages / culture than English
- [x] API is compatible with existing add-ons.
- [x] Security precautions taken.

### CODE REVIEW

**Comment by leonardder** [comment]
@seanbudd, given this is a fixup of #15472, I noticed that onOk of the SynthesizerSelectionDialog still has logic to reinitialize the tones module to update the audio device. Is this still required or may be an oversight?

**Comment by seanbudd** [comment]
@leonardder - yes this is to help with recovery if the synth fails to work a certain output device. I'm not sure on how necessary it is to reset tones still but keeping it for safety.

**Comment by seanbudd** [comment]
Apologies - it may be an oversight, however I'd keep it for safety in the beta.
Something to consider fixing in 2024.1

**Comment by leonardder** [comment]
@seanbudd Could you please fix https://github.com/nvaccess/nvda/pull/15472/files#r1335020002 while at it?

**Review by michaelDCurran — DISMISSED** [review]

**Review by Qchristensen — DISMISSED** [review]
All looks good, great work.

**Pull request merged**
