### PR TITLE
Fix context menu bouncing in Edge browse mode

### LINKED ISSUE #15309: NVDA can't access context menus opened on some links/images in Edge, even when Narrator can
### Steps to reproduce:

1. Open Microsoft Edge
2. Browse to, for example, [ebary.com](https://ebary.com/)
3. Press `t` to go to the first table, then `k` to go to the second link (which is probably also a graphic).
4. Press `Applications` or `shift+F10`

### Actual behavior:

NVDA speaks the page title and the link, but does not speak the first context menu item.

Note that this does not always happen--sometimes, with no apparent reason, NVDA will send focus to the context menu. Other times it won't.

### Expected behavior:

NVDA should always focus the context menu.
Narrator does.
In fact, if you try this and NVDA doesn't speak the menu, turning on Narrator simultaneously will rectify the problem, and NVDA is able to see the menu.

### Further context

This has been reported on mailing lists for a few months now. I'm not sure why I can't find an issue for it here, as I thought we had one, but I can only find the Edge context menu not opening for the downloads area issue, which @leonardder has a PR to fix now.

### NVDA logs, crash dumps and other attachments:

In the attached log, the first time I try to open a context menu, it fails. From the log, it appears that it starts to read the menu, but is then redirected to the virtual buffer.

Then I try with the next link NVDA takes me to, which also fails, but differently. The second one fails, I believe, because while NVDA is reading the virtual buffer and claiming the page is what I'm navigating, in fact the context menu is open, and that's actually what I'm navigating.

The third link does the same thing, but then I press `escape`, and try to open the context menu on the third link again. This time it succeeds.

[bad_context_edge.txt](https://github.com/nvaccess/nvda/files/12376359/bad_context_edge.txt)

#### NVDA installed/portable/running from source:

Installed, but have tried portables and PR builds as temporaries, with the same effect.

#### NVDA version:

alpha-28879,a7981cad

#### Windows version:

Microsoft® Windows® Operating System version 10.0.22621.1
(This is 11 Home 22H2, but the same thing happened on 10 Home 22H2)

#### Name and version of other software in use when reproducing the issue:

Microsoft Edge version 115.0.1901.203
(But happened as far back as 113, AFAIK)

#### Does the issue still occur after restarting your computer?

Yes

#### Have you tried any other versions of NVDA? If so, please report their behaviors.

Alphas and productions as far back as 2023.1, maybe even pre-2023.1 versions. This is something Edge introduced, I don't believe it's an NVDA change.

#### If NVDA add-ons are disabled, is your problem still occurring?

Yes

#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?

Yes

### PR DESCRIPTION
**Pull request by LeonarddeR**
### Link to issue number:
Fixes #15309 

### Summary of the issue:
In Edge browse mode, when opening the context menu, NVDA many times goes back to browse mode.

### Description of user facing changes
NVDA will no correctly focus the context menu opened from Edge browse mode.

### Description of development approach
The issue behind this is as follows. Take a link as example:

1. Disabling the option `Automatically set system focus to focusable elements` ensures that an object only gets focus when strictly necessary. This is the case when opening the context menu, because otherwise, the context menu would open for the wrong object.
2. When opening the context menu on the link, NVDA calls script_passThrough
3. script_passThrough calls setFocus on the link's object and sends the gesture.
4. Two focus events are fired, one for the link in the document and one for the context menu
5. NVDA first processes the context menu event and after that, the link object event
6. Focus bounces from the context menu back to the link.

There is a very trivial fix for this. With calling `api.processPendingEvents`, we ensure that NVDA first processes the event generated by setFocus before executing the gesture.

### Testing strategy:
Tested the str from #15309 

### Known issues with pull request:
None known

### Change log entries:
Bug fixes
- NVDA will no longer bounce back to the last browse mode position when opening the context menu in Microsoft Edge. (#15309)

### Code Review Checklist:

- [x] Pull Request description:
  - description is up to date
  - change log entries
- [x] Testing:
  - Unit tests
  - System (end to end) tests
  - Manual testing
- [x] API is compatible with existing add-ons.
- [x] Documentation:
  - User Documentation
  - Developer / Technical Documentation
  - Context sensitive help for GUI changes
- [x] UX of all users considered:
  - Speech 
  - Braille
  - Low Vision
  - Different web browsers
  - Localization in other languages / culture than English
- [x] Security precautions taken.

### CODE REVIEW

**Review by seanbudd — APPROVED** [review]
Thanks @leonardder

**Comment by Shah2** [comment]
Using Microsoft Edge 116 with NVDA 2023.3 Beta 1, the context menu in the Edge history is still not accessible.

**Comment by leonardder** [comment]
@Shah2 Please create a new issue for this. This pull request is closed.

**Comment by brunoprietog** [comment]
Now that I've updated to the latest alpha version, without the option to focus on elements when exploring in browse mode, I frequently see this error. I always have to focus on the link first before pressing shift + f10 so that it doesn't return to exploration mode.

**Comment by seanbudd** [comment]
@brunoprietog - please open a new issue for this. This pull request is closed.

**Comment by brunoprietog** [comment]
@seanbudd, I've opened #18670

**Pull request merged**
