### PR TITLE
Braille input: emulate keys outside text content and support combining input with modifiers

### LINKED ISSUE #7306: Single letter navigation from a braille terminal
When in browse mode, user should be able to type a single letter command from his braille terminal.
For example, typing "h" on the terminal should move to the next title.
I have tested it on 2 braille devices (Eurobraille Esys and Baum Vario Ultra) and it does not work on both.
Maybe does it work on other devices?

### PR DESCRIPTION
**Pull request by LeonarddeR**
### Link to issue number:
Follow up of #6213/#7503
Fixes #7306.

### Summary of the issue
Although the braille input system has been vastly improved due to support of contracted input, combining braille input was not yet supported. Also, even though letter quick navigation was supported in the forward direction, navigating backwards did not work as well.

### Description of how this pull request fixes the issue:
This pr addresses the following:

1. No longer always send unicode characters to the system, but in the case of non-editable text, emulate a gesture. See https://github.com/nvaccess/nvda/issues/7306#issuecomment-316555321 . This means that pressing dot1257 in US English 8 dot, which translates to capital H, results in shift+h being sent to the system, which will go to the previous heading.
2. In the case of key emulation, make sure we only emulate one key stroke at once. This is different from sending unicode chars, which allowed sending whole words at once.
3. The point above means that we had to deal with contracted braille in non-editable cases. It turned out that the liblouis partial trans mode works perfectly for this. I tested with both Unified english braille code grade 2 and English US grade 2 that at least all the alphanumeric characters work. They do not translat to their contracted equivalents, so this seems to be the perfect method to use a contracted table in uncontracted mode .
4. Also discussed in #7306 is the possibility to use braille input together with modifiers. As noted by @jcsteh in https://github.com/nvaccess/nvda/issues/7306#issuecomment-319234741 , the implementation for this had to be quite different from #6213, al though I have been able to integrate them as much as possible.

	A. New, unbound scripts have been added to toggle control, shift, alt, windows and NVDA. Here, toggling means that the state of these keys will be enabled or disabled within the scope of braille input. For example, when you assign control to space+dot7 and you press space+dot7, than dot 125, control+h will be emulated. This also works for contracted tables due to partial translation mode.
	B. The toggable modifier scripts integrate in the modifier system that already existed (#6213/#7503), For example, when key1 is bound to toggle control, key 2 to kb:shift and key3 to kb:down arrow, you can press and release key 1 to enable control, than key2+key3 to emulate control+shift+down arrow.

### Testing performed:
* Tested Unified English braille grade 2 and English US grade 2 in non-editable text cases, no contracted translation did occur and thus the implementation worked as expected.
* Tested assigning modifier toggle scripts and combined them with braille input in both editable and non-editable cases.
* Tested combining modifier toggle scripts with emulate scripts, as explained above.
* Tested some braille input cases that, in contracted tables, always result in multiple characters (e.g. dot123456). NVDA reported correctly that this braille input was not supported.

### Known issues with pull request:
* It is not possible to combine emulated modifiers (e.g. kb:shift) with braille input. Having support for this would mean a rewrite of all drivers that use gesture classes that inherrid both from BrailleDisplayGesture and BrailleInputGesture.
* The way the nVDA key is emulated whe nusing the toggle script is a bit hacky, but coming up with a cleaner way would mean a massive rewrite of the way the NVDA key is used in the keyboard handler. There is now a new function in the keyboardHandler that returns a list of keys that have been set as NVDA key. When emulating a gesture containing the NVDA key, the real key being emulated is either caps lock, extended insert or numpad insert, which internally translates back to the NVDA key. This is a hthing I'm not quite happy with, so any feedback to improve this would be extremely helpful. Note that using the modifier toggle script for the NVDA key will result in undefined behavior when you toggle the NVDA key, then press pass next key through, then press a braille input combination.

### Change log entry:
* New features
	+ You can now toggle control, shift, alt, windows and NVDA from your braille keyboard and combine these modifiers with braille input (e.g. press control+s). (#7306)
		* You can assign these new modifier toggles using the commands found under Emulated system keyboard keys in the Input gestures dialog.

* Changes
	+ Contracted braille input tables will automatically fall back to uncontracted mode in non-editable cases (i.e. controls where there is no cursor or in browse mode). (#7306)

* Bug fixes
	+ Braille input no longer allows you to use contracted braille in cases where it is not supported (i.e. whole words will no longer be sent to the system outside text content and in browse mode).
(#7306)

### CODE REVIEW

**Review by michaelDCurran — APPROVED** [review]

**Comment by Andre9642** [comment]
I've just tested this. It works perfectly. :)

I have two suggestions:

1. When entering a shortcut, NVDA says "NVDA pressed", "Control pressed", etc. but we have no feedback in braille. Could you add this information in braille also?
In my addon [BrailleExtender](https://github.com/andre9642/brailleExtender/), I display this in this form: "Alt+...", "Control+...", "NVDA+Control+...".
2. Could you define some default gestures for some braille displays?
  In BrailleExtender, I have defined these gestures for Baum, Brailliant and Focus displays:
    - Dot1+dot2+space (⠉+space): Control;
    - Dot2+dot5+space (⠒+space): Alt;
    - Dot3+dot6+space (⠤+space): Windows;
    - Dot7+dot8+space (⣀+space): Shift;
    - n+space: NVDA.
  Except the NVDA key, all modifiers can be combined in the same time (NVDA + shift, Control + alt, etc.).

What do you think?

**Comment by leonardder** [comment]
[**@Andre9642**](https://github.com/Andre9642) commented on [15 Jan 2018, 04:40 CET](https://github.com/nvaccess/nvda/pull/7843#issuecomment-357575761 "2018-01-15T03:40:59Z - Replied by Github Reply Comments"):
> 1. When entering a shortcut, NVDA says "NVDA pressed", "Control pressed", etc. but we have no feedback in braille. Could you add this information in braille also?

When does the current code say this? It should only do it when speaking commands is on, when it is off and it says the shortcut, it is actually a bug :) As I'd like to bind this with speaking command keys, I think your request is beyond the scope of this pr.

> 2. Could you define some default gestures for some braille displays?

This will be a part of another issue, most likely #2945.

**Comment by leonardder** [comment]
I'd say, let's delay this until 2018.2. I don't think it's a good idea to have too many braille patches end up in 2018.1. New native drivers as well as auto tethering feels ok to me.

**Comment by derekriemer** [comment]
I just edited the what's new part to fix pres to press.

**Comment by michaelDCurran** [comment]
Was more work going on in this PR, or should this be incubated now that 2018.1 is complete?

**Comment by leonardder** [comment]
I think this is ready to be incubated in order to get tested as broadly as possible.

**Pull request merged**
