### PR TITLE
Fixup of PR 13082: fix a misspell in DefaultAppArgs and no longer use globalVars.appArgs in a boolean context (#13386)

### PR DESCRIPTION
**Pull request by lukaszgo1**
### Link to issue number:
Fix-up of PR #13082
### Summary of the issue:
PR #13082 added fake implementation of `globalVars.appArgs` which is used in cases where command line arguments are not parsed. It introduced two mistakes however:
1. The fake class was named `DefautAppArgs` (note the missing "l")
2. NVDA's logHandler uses `appArgs` in a boolean context to check if log viewer should be opened, determine if log fragment can be marked for copy etc. The new class was always `True` in a boolean context.
### Description of how this pull request fixes the issue:
1. The class is renamed to `DefaultAppArgs`.
2. `logHandler` no longer checks boolean value of `appArgs`. This is safe since:
    - Both `logHandler.Logger.markFragmentStart` and `logHandler.Logger.getFragment` are used only in NVDA and they are invoked by the user action (even before #13082 `appArgs` was always truthy in that context).
    -  The check for `appArgs` being falthy in `logHandler.Logger._log` introduced in 2827a34219e6e9684657039b852c3e0bd63cb3da can also be safely removed since even for NVDA_slave `activateLogViewer` is set to `False` (only two cases where it is set to `True` occur when user invokes log viewer via keyboard command). Also while this is not clarified in this commit at a guess I'd say this check has been added not for any additional security but just to avoid `AttributeError` being raised when trying to access `globalVars.appArgs.secure` when logging from slave.
### Testing strategy:
None needed.
### Known issues with pull request:
None known
### Change log entries:
None needed - at a point where add-ons are loaded `appArgs` was always truthy.

### Code Review Checklist:

- [X] Pull Request description:
  - description is up to date
  - change log entries
- [X] Testing:
  - Unit tests
  - System (end to end) tests
  - Manual testing
- [X] API is compatible with existing add-ons.
- [X] Documentation:
  - User Documentation
  - Developer / Technical Documentation
  - Context sensitive help for GUI changes
- [X] UX of all users considered:
  - Speech 
  - Braille
  - Low Vision
  - Different web browsers
  - Localization in other languages / culture than English

### CODE REVIEW

**Comment by seanbudd** [comment]
I think the correct approach would be to instead remove the use of `globalVars.appArgs` as a boolean.
I am not certain that an additional check here is required, but it appears that `logViewer` needs 2 globalVars: `bool(globalVars.appArgs.logFileName) == True` and `globalVars.appArgs.secure == False`

If this approach is used we may need to add a note in changes for developers about the change in "truthiness" of appArgs.


```diff
diff --git a/source/logHandler.py b/source/logHandler.py
index 43d3dfce6..796b0abcc 100755
--- a/source/logHandler.py
+++ b/source/logHandler.py
@@ -155,7 +155,7 @@ class Logger(logging.Logger):
 			codepath=getCodePath(f)
 		extra["codepath"] = codepath
 
-		if not globalVars.appArgs or globalVars.appArgs.secure:
+		if not globalVars.appArgs.logFileName or globalVars.appArgs.secure:
 			# The log might expose sensitive information and the Save As dialog in the Log Viewer is a security risk.
 			activateLogViewer = False
```

**Comment by lukaszgo1** [comment]
> I think the correct approach would be to instead remove the use of `globalVars.appArgs` as a boolean. I am not certain that an additional check here is required, but it appears that `logViewer` needs 2 globalVars: `bool(globalVars.appArgs.logFileName) == True` and `globalVars.appArgs.secure == False`

I do not really understand why we need to check if the value of `globalVars.appArgs` is truthy or falsy either ((perhaps for NVDA_slave?). @michaelDCurran  Would you be able to shed some light on this?
Since, as I said above, I do not understand what these checks are for I've decided to overload the operator just to be on the safe side.

> 
> If this approach is used we may need to add a note in changes for developers about the change in "truthiness" of appArgs.

At the stage where add-ons or plugins from the scratchpad are loaded `globalVars.appArgs` was always truthy, so this is not API breaking in any sense.

**Comment by lukaszgo1** [comment]
@seanbudd I've removed the overloaded operator and `appArgs` is no longer used as a boolean in the `logHandler`. The PR description explains why this can be safely done.

**Review by seanbudd — APPROVED** [review]
Thanks @lukaszgo1

**Pull request merged**
