### PR TITLE
MS Word: Remove unintended input help message on tab key script (#9943)

### LINKED ISSUE #9943: Odd and possibly confusing key describer message for tab in Word
### Steps to reproduce:

1. Open a document in MS Word.
2. Press NVDA+1 to enter key describer mode.
3. Press tab.

### Actual behavior:

The following message is spoken:

>		A script for the tab key which:
>		* if in a table, announces the newly selected cell or new cell where the caret is, or 
>		* If not in a table, announces the distance of the caret from the left edge of the document, and any remaining text on that line.

### Expected behavior:

1. I would not expect the help message  to start with "A script for the tab key which:". Since every key calls a script of some sort, this is redundant. Further, since it is not usually spoken as such, it could potentially confuse users.
2. Shouldn't the help message mention that the key actually inserts a tab? It is unusual for a text entry key to be overloaded like this, so it seems to me it warrants further clarity about what happens when you press it.
3. And what's with "and any remaining text on that line."? more on that below.

### System configuration

Windows 10, 1903 64bit
NVDA installed or run from installer.
Multiple versions from 2019.1.1 through nvda_snapshot_threshold_py3_staging-18066,131ed840

#### Name and version of other software in use when reproducing the issue:

Microsoft Word 2019

### Suggested Change

I suggest altering the help message to something more along these lines:

> Inserts a tab, and announces the distance of the caret from the left edge of the document, and any remaining text on that line. If in a table, announces the newly selected cell or new cell where the caret is.

#### Further Thoughts

The above not withstanding, I consider this statement to be less than perfectly clear:

> announces the distance of the caret from the left edge of the document, and any remaining text on that line. 

Does it mean that it announces the remaining text on that line? If so, it doesn't.
In fact, it announces exactly the same thing, irrespective of whether there is text to the right of the entered tab.

### PR DESCRIPTION
**Pull request by JulienCochuyt**
### Link to issue number:

Fixes #9943

### Summary of the issue:

In Microsoft Word, there is an unintended input help mode message associated with the tab key script.
Introduced as of 38d28f9ca9 in 2018.1

### Description of how this pull request fixes the issue:

EDIT: Use the new `@script` decorator instead of the legacy construct.

### Testing performed:

Checked in input help mode that the message is no longer spoken.
Checked the script is still executed.

### Change log entry:

I do not think this deserves a changelog entry.

### CODE REVIEW

**Comment by leonardder** [comment]
Lol, I had never realised that setting a scripts doc string like this is much more elegant than setting the __doc__ attribute.
Anyway, I think I'd prefer removing the doc string altogether and change it into a block of comments.

**Comment by JulienCochuyt** [comment]
While checking in the Developer Guide for a mention on avoiding to set a docstring on a script, I realized:
1- You wisely wrote not to avoid it anymore, because
2- `@script` decorator is the "new" way to go

So I guess I should follow that path instead…

**Comment by JulienCochuyt** [comment]
Rebased onto latest master

**Comment by JulienCochuyt** [comment]
Rebased onto latest master.

**Review by michaelDCurran — APPROVED** [review]

**Review by michaelDCurran — CHANGES_REQUESTED** [review]
actually this branch now has conflicts. I will approve and merge this once the conflicts are addressed.

**Comment by JulienCochuyt** [comment]
> actually this branch now has conflicts. I will approve and merge this once the conflicts are addressed.

Conflicts resolved. Thanks.

**Review by michaelDCurran — APPROVED** [review]

**Pull request merged**
