### PR TITLE
Output ARIA live regions in Braille

### LINKED ISSUE #7756: Live Regions are Not Displayed in Braille
When live region information on a web page changes, the new information is only spoken through speech. The Braille display does not update to show this information. I am using NVDA 2017.3 on Windows 10 build 16299.19. I'm using Chrome 62.0.3202.94. I also tested this in Internet Explorer 11 and receive the same result.

For an example, go to https://dequeuniversity.com/library/aria/content-feedback/liveregion-playground and set up a live region by checking the "use role defaults" radio button and the "every 5 seconds" radio button. Finally, press the submit button and observe that NVDA speaks changes but the Braille Display continues to show the line of text NVDA is focused on. It should do something such as displaying a flash message containing the updated information that is spoken.

### PR DESCRIPTION
**Pull request by codeofdusk**
### Link to issue number:
Closes #7756.

### Summary of the issue:
NVDA does not output ARIA live regions in Braille, making them completely inaccessible in Braille-only usage scenarios (for instance, @rperez030 would like to read incoming MS Teams messages in Braille during meetings).

### Description of user facing changes
ARIA live region updates are now displayed as Braille messages, similarly to UIA notification events.

### Description of development approach
Call `brailleHandler.message` on live region updates.

### Testing strategy:
Tested by @simon818 and @rperez030 for their use cases.

### Known issues with pull request:
None known

### Change log entries:
Something along the lines of:
== Changes ==
- Updates to dynamic web content (ARIA live regions) are now displayed in Braille. This can be disabled in NVDA's advanced settings panel. (#7756)

### Code Review Checklist:

- [x] Pull Request description:
  - description is up to date
  - change log entries
- [x] Testing:
  - Unit tests
  - System (end to end) tests
  - Manual testing
- [x] API is compatible with existing add-ons.
- [x] Documentation:
  - User Documentation
  - Developer / Technical Documentation
  - Context sensitive help for GUI changes
- [x] UX of all users considered:
  - Speech 
  - Braille
  - Low Vision
  - Different web browsers
  - Localization in other languages / culture than English
- [x] Security precautions taken.

### CODE REVIEW

**Comment by seanbudd** [comment]
I think there should be a toggle, as raised in https://github.com/nvaccess/nvda/issues/7756#issuecomment-346040943 and below.

Perhaps an option: "Update braille with live messages: ". With 3 options: off (default), any priority (polite), high priority (assertive)

**Comment by rperez030** [comment]
@seanbudd  I agree that a toggle may be a good idea, but right now NVDA doesn't offer that level of granularity for speech. We can disable the announcement of polite updates by turning off the reporting of dynamic changes, but there is no way to ignore aria-live ="assertive" even for speech. This PR extends the Braille support that already exist for all other live updates. If I want Braille to ignore aria-live updates, I just need to disable Braille messages like I would for UIA based notifications, for example. what about adding this basic level of support now, and work on a more comprehensive filter of aria-live updates that encompasses speech and Braille for 2024.1? this PR resolves the biggest shortcoming that exists right now for me in terms of Braille support in NVDA.

**Comment by seanbudd** [comment]
We wish to improve aria live polite behaviour as discussed in https://github.com/nvaccess/nvda/issues/13915.
This would mean that polite notifications are only announced after NVDA is idle (finished with speech).
I think if we are to accept this PR, this behaviour should match speech and polite live regions should not update braille.

Polite behaviour for braille which matches #13915 could be configured via an idle timeout setting, e.g. after braille hasn't been updated for 30sec, update the display with the polite notification.

Proposed ideal options when considering #13915 
- "Interrupt speech with live messages: " - With 2 options: interrupt and wait until idle
- "Announce speech after idle (ms)" - #13915 
- "Refresh braille automatically with live messages: ". With 3 options: interrupt / wait until idle / never"
- "Update braille display after idle (ms) "

**Comment by leonardder** [comment]
I think I would change the report dynamic content changes option to a four state option. Both speech and braille, braille, speech and off.

**Comment by codeofdusk** [comment]
> I think I would change the report dynamic content changes option to a four state option.

@leonardder I agree (and actually thought of this), but that's a config spec breaking change that I'd prefer to save for a larger ARIA refactor (especially if one is planned).

@seanbudd suppression of live regions in Braille is inconsistent with the user experience of many other popular screen readers, such as VoiceOver on iOS/MacOS. Additionally, live regions are currently completely inaccessible to deafblind users or those who otherwise use NVDA only via Braille, as indicated in https://github.com/nvaccess/nvda/issues/7756#issuecomment-1317697802. As @rperez030 suggests, we shouldn't let the perfect be the enemy of the good: merging this pR now makes this information accessible in Braille, and we can always refine the experience later.

Similar to HID Braille support, I'll put this behind a feature flag (enabled by default, but can be disabled if problematic) for now. As a longer term plan, this flag should be removed and merged into "report dynamic content changes" during a config spec upgrade.

**Comment by leonardder** [comment]
> > I think I would change the report dynamic content changes option to a four state option.
> 
> @leonardder I agree (and actually thought of this), but that's a config spec breaking change that I'd prefer to save for a larger ARIA refactor (especially if one is planned).

I guess that's a product decision that is best to be taken by NV Access. I think this pr is too late for 2023.2. Personally I'd rather have the config change all settled instead of introducing a feature flag and then removing that in a follow up.

**Comment by burmancomp** [comment]
What if ARIA live regions would be inaccessible with speech, and there would be pr solving this. Should it be merged or not?

**Comment by rperez030** [comment]
> What if ARIA live regions would be inaccessible with speech, and there would be pr solving this. Should it be merged or not?


That is a great question. That is an example I often use when discussing accessibility issues related to visual content not being accessible to screen reader users. For someone that doesn't use Braille, or is a very ocasional user, this may feel secundary. For someone that depends primarily on Braille output, this is a limitation that should have been fixed years ago.

**Comment by seanbudd** [comment]
This new config setting seems appropriate - but can it be moved out of advanced settings into general braille settings?

**Comment by codeofdusk** [comment]
The placement in advanced is because this feels more like a feature flag to me (something someone might disable in case of issues) rather than a user-facing setting. From the user perspective, you can disable Braille messages which will block both live region updates and any other flash messages that might be similarly disruptive.

**Review by seanbudd — APPROVED** [review]
Given that, the plans outlined in https://github.com/nvaccess/nvda/pull/15078#issuecomment-1614165901 and https://github.com/nvaccess/nvda/pull/15078#issuecomment-1614521327 seem appropriate

**Comment by tmthywynn8** [comment]
Is there an official way of testing this for braille displays? The reason why I ask is because I am not getting incoming chat alerts for either Zoom or Teams (desktop apps), but they are voiced without issue. The same goes for mute/unmute notifications in Zoom, but I am unsure if they are specifically outputted via live regions or not.

**Comment by tmthywynn8** [comment]
Update: With a portable copy of NVDA, live regions are brailled, but not with my installed copy. I even restarted with add-ons disabled and no difference. In NVDA.ini, reportLiveRegions is set to DEFAULT. And yes, I even uninstalled and reinstalled NVDA. Log fragment below:

```log
IO - speech.speech.speak (10:53:48.608) - MainThread (4836):
Speaking ['Static Content The changing content will take place below.  Modified Content #1   ']
IO - braille.BrailleBuffer.update (10:53:48.720) - MainThread (4836):
Braille regions text: ['btn Submit btn Clear added content btn Stop adding content ']
IO - braille.BrailleHandler.update (10:53:48.720) - MainThread (4836):
Braille window dots: 12 2345 1345 - 6 234 136 12 134 24 2345 - 12 2345 1345 - 6 14 123 15 345 - 1 256 1246 - 25 2345 26 2345 - 12 2345 1345 - 6 34 135 1234 -
``

**Pull request merged**
