### PR TITLE
Revert "Give ui.browseableMessage the ability to show copy and close buttons after the message, and add buttons to some instances"

### LINKED ISSUE #16995: In `ui.browseableMessage`, every other line is empty
### Steps to reproduce:
* Press NVDA+V to ensure screen layout is off.
* On a webpage, press 2 times NVDA+F
* Press many times down arrow
* Press NVDA+V to enable screen layout
* Press up/downArrows again to explore the lines

### Actual behavior:
Every other line is empty when screen layout is off.
### Expected behavior:
The content should not contain empty lines between useful lines; screen layout should not have any impact here.
### NVDA logs, crash dumps and other attachments:
N/A
#### NVDA installed/portable/running from source:
Installed
#### NVDA version:
Version : source-master-c8a847b (2024.4.0.0)
#### Windows version:
Windows 10
#### Name and version of other software in use when reproducing the issue:
N/A
#### Other information about your system:
N/A
#### Does the issue still occur after restarting your computer?
Not tested, probably yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
2024.3rc1 is OK, i.e. no such issue.
#### If NVDA add-ons are disabled, is your problem still occurring?
Yes
#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
Not tested, probably unrelated.

### Notes
This issue is very likely introduced by #16369. Cc @XLTechie.
Thus #12004 has been reintroduced unfortunately.

### LINKED ISSUE #16996: NVDA+f browseable message - pressing alt+c makes a ding
Follow-up of #16369; cc @XLTechie.
### Steps to reproduce:
* Press NVDA+f twice on a formatted text, e.g. in a webpage
* Press alt+c
### Actual behavior:
NVDA says "Text copied", a "ding" sound is heard and the text is actually in the clipboard.
### Expected behavior:
NVDA says "Text copied" and the text is actually in the clipboard.
But no "ding" sound should be heard. This sound is quite unusual when pressing alt+letter to activate a button and this may let think that there has been an error.
### NVDA logs, crash dumps and other attachments:
N/A
#### NVDA installed/portable/running from source:
Source
#### NVDA version:
Version : source-master-c8a847b (2024.4.0.0)
#### Windows version:
10
#### Name and version of other software in use when reproducing the issue:
N/A
#### Other information about your system:
N/A
#### Does the issue still occur after restarting your computer?
Not tested; probably yes.
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
N/A
#### If NVDA add-ons are disabled, is your problem still occurring?
Yes
#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
Not tested; probably unrelated.

### PR DESCRIPTION
**Pull request by XLTechie**
### Reverts PR
Reverts #16369 

### Issues fixed
Fixes #16996 
Fixes #16995 

### Issues reopened
Reopens #14641 

### Reason for revert

Security tightening requested by @seanbudd, caused an inadvertent recurrence of #12004. (#16995)

In addition, a known (but I thought minor) quirk of the original PR, was that users pressing the `Alt+C` key combination to activate the copy button, would hear a ding. This is a "feature" of MSHTML, and not something for which I believe there is a solution. NVDA did speak a message indicating that text was successfully copied, but @CyrilleB79 suggested that was not enough to negate the ding. (#16996)

### For the blank lines issue, there are a couple possible paths forward:

1. After escaping the incoming message, replace `\n` with `<br>`, and feed it to `.innerHTML` instead of `.innerText`. This re-raises one of @seanbudd's original concerns about the use of `.innerHTML`, however, so may not be viable.
2. @michaelDCurran has outlined a potential path forward, in https://github.com/nvaccess/nvda/issues/16995#issuecomment-2285154383, but further investigation is required.

### For the ding on `Alt+C` issue, there are two possibilities known to me:

1. Choose a key that doesn't ding. That will probably mean it can not use `Alt`, which makes it unusual for button activation. Perhaps @CyrilleB79 has ideas.
2. Do not use an accelerator for the copy button.

## Summary by CodeRabbit

- **New Features**
	- Enhanced command line options for improved update control.
	- Introduced functionality for redirection of objects from on-screen coordinates.
	- Updated eSpeak NG to support new languages, including Faroese and Xextan.
- **User Interface Improvements**
	- Added "Close" and "Copy" buttons to various dialogs for better accessibility.
- **Performance Enhancements**
	- Improved SCons build system with `--all-cores` parameter for optimized performance.
- **Documentation**
	- Updated developer information with application architecture details.

### CODE REVIEW

**Comment by CyrilleB79** [comment]
Re the ding issue, I had just opened an issue so that it is tracked.

I am not opposed to keep this known issue if it is documented in the known issues of the (possibly future) PR and if the consensus is that the drawback of the ding does not compensate the added value of a shortcut key.

**Comment by XLTechie** [comment]
@CyrilleB79 What do you think of switching to Ctrl+Alt+C? That does not ding.

**Comment by SaschaCowley** [comment]
I wouldn't go with `control+alt+c` as it may conflict with a desktop shortcut hotkey.

**Comment by XLTechie** [comment]
@SaschaCowley I thought of that. Pretty much anything could. Google Docs, for example, uses lots of Ctrl+Alt combinations in their keyboard interfaces. Not that I advocate emulating their style in anything, but my point is it's pretty common not to take possible desktop shortcuts into account.

I'm personally fine with this button not having an accelerator at all, but a couple people seemed to expect one.

**Comment by SaschaCowley** [comment]
@XLTechie that's true, but I suspect a high number of NVDA users use desktop shortcut hotkeys, so I think `control+alt+letter` is probably best avoided. Just my thoughts though :)

**Comment by XLTechie** [comment]
All right, Ctrl+Shift+C it is.

**Comment by seanbudd** [comment]
CTRL + INSERT is a pretty common alternative to ctrl+c in windows, not sure if thats viable

**Comment by XLTechie** [comment]
@seanbudd Would NVDA users expect Insert (i.e. the NVDA key) to be used in this way? I didn't test that one, but shall do for completeness.

**Comment by CyrilleB79** [comment]
Ctrl+insert was common in DOS times, but is much less common, or at least much less advertised, since Windows 95, even if still supported. Moreover, it is clearly still less used by NVDA or Jaws users due to the Insert key being used as NVDA/Jaws key. So that's not a desirable choice at all.

The best solution would be to remove the ding if @SaschaCowley's suggestion works and keep alt+c.

If not possible, I am unsure if no shortcut at all is better or if something else less common (e.g. control+shift+c) would be suitable.

**Comment by CyrilleB79** [comment]
Oh sorry, just realized that Sasha's suggestion does not work.

**Pull request merged**
