### PR TITLE
Speech Dictionary - UI - Regex: Early detect grouping errors (#11407)

### LINKED ISSUE #11047: Aria 1.1 Combo box not getting focused with Single Button navigation shortcuts
NVDA does not jump to edit fields defined using [Aria 1.1 Combobox syntax](https://www.w3.org/TR/wai-aria-practices/examples/combobox/aria1.1pattern/listbox-combo.html). However, it works fined with [Aria 1.0 Combo box examples](https://www.w3.org/TR/wai-aria-practices/examples/combobox/aria1.0pattern/combobox-autocomplete-both.html)

### Steps to reproduce:
1. Open chrome
1. Navigate to https://www.w3.org/TR/wai-aria-practices/examples/combobox/aria1.1pattern/listbox-combo.html
1. Press tab to bring focus to the page
1. Press E

### Actual behavior:
Pressing shortcut E or C does not focus the input box
NVDA announces "No next edit field"

### Expected behavior:
Pressing keyboard shortcut E should focus the input box

#### NVDA installed/portable/running from source:
portable
#### NVDA version:
2019.2.1
#### Windows version:
Windows 10 Pro
10.0.18363
#### Does the issue still occur after restarting your computer?
yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
no 
#### If addons are disabled, is your problem still occuring?
yes
#### Did you try to run the COM registry fixing tool in NVDA menu / tools?
no

### LINKED ISSUE #11407: An error in a regular expression dictionary entry can result in entry deletion rather than giving the user a correction opportunity
### Steps to reproduce:

1.  Open the temporary speech dictionary: NVDA+n, p, d, t.
2.  Press Alt+A to add a new entry.
3.  Set the pattern as "`\(test\)`", and the replacement as "`\1`".
4.  Press Alt+E to set as regular expression.
5.  Press enter.
6.  Press enter.

Note: this is a test string to demonstrate the case. When I encountered this issue, I had entered a very long regexp (about 200 characters), and made some kind of grouping error with one of the groups.

### Actual behavior:

NVDA waits until after the dictionary dialog is closed (not the add dialog, the enclosing dictionary dialog). It then:

* Plays an error sound.
* Irrecoverably deletes the added dictionary entry.
* Records something like the following in the log:

```
ERROR - speechDictHandler.SpeechDict.sub (20:42:36.514) - MainThread (5848):
Invalid dictionary entry 1 in temporary dictionary: "\(test\)", invalid group reference 1 at position 1
```

Possibly even worse than the addition case I demonstrated here, if you edit an existing entry, and cause a grouping error, the entry is also deleted, rather than, at least, reverting back to its pre-edited state.

### Expected behavior:

The dictionary entry is validated when the entry add/edit dialog attempts to close, and if it fails, the user remains in the dialog, and is given a chance to continue work on the entry, without having to re-enter the whole thing as a new entry.

The dictionary already does this for non-grouping errors. For example, try a pattern like: "`(\`", and a replacement of "`test`". In that case, when hitting OK to accept the entry, a dialog is shown as follows:

```
Regular Expression error: "bad escape (end of pattern) at position 1".
```

Pressing OK in that dialog, returns you to the add/edit dialog, with the existing pattern and replacement still available for further editing.
That is what I would expect for group errors as well.

Furthermore, I'm testing this on alpha, with debug logging. I don't know if a user with disabled logging on a stable branch, would even hear the error beep.  If not, then it means the user has no idea this happened.

### System configuration

Installed NVDA alpha-20566,dfbda72e, no other versions tested.
Windows 10 Version 2004 (OS Build 19041.388)

#### Add-ons, reboot, and reg fix tool: N/A

### PR DESCRIPTION
**Pull request by JulienCochuyt**
### Link to issue number:

Fixes #11407

### Summary of the issue:

When editing Speech Dictionary entries, regex compilation errors are reported on the fly.
Some grouping errors arise only when actually attempting substitution, leading to the deletion of the faulty entry without prompting the user for a correction.

### Description of how this pull request fixes the issue:

Upon editing a regex entry, not only compile it, but also attempt substitution.

### Testing performed:

Ensured the error test case in #11407 is properly detected upon submitting the entry.

### Change log entry:

Section: Bug fixes

More regular expression errors are now detected when editing Speech Dictionary entries.

### CODE REVIEW

**Comment by feerrenrut** [comment]
Could you please enable "Allow edits from maintainers" on this PR? It allows us to update the change log and merge all in one.

**Comment by JulienCochuyt** [comment]
@feerrenrut wrote:
> Could you please enable "Allow edits from maintainers" on this PR? It allows us to update the change log and merge all in one.

I'm afraid this seems to work only with forks owned by individuals. See isaacs/github#1681.
Thus, I sent you an invite for write access to accessolutions/nvda.

**Comment by feerrenrut** [comment]
> I'm afraid this seems to work only with forks owned by individuals.

Ah thanks for letting me know, I didn't realize that!

**Review by feerrenrut — DISMISSED** [review]
Looks good to me. Thanks @JulienCochuyt

**Review by feerrenrut — APPROVED** [review]

**Pull request merged**
