### PR TITLE
Added setting beep for capitals via configuration file

### PR DESCRIPTION
**Pull request by ghost**
### Summary of the issue:
Settings of the beep for capitals (pitch, length and volume) currently hardcoded and cannot be changed by the user.
### Description of how this pull request fixes the issue:
In the config/configSpec.py module, in the section for each synth added three new parameters:
beepPitchForCapitals = integer(default=2000,min=100,max=4000)
beepDurationForCapitals = integer(default=50,min=50,max=150)
beepVolumeForCapitals = integer(default=50,min=0,max=100)
And in speech.getSpeechForSpelling function-generator made necessary changes to use these new parameters when playing of the beep for capital letters.

### CODE REVIEW

**Comment by dnz3d4c** [comment]
@kvark128 Please write pr description with pr template.

**Comment by kvark128** [comment]
@dnz3d4c Done

**Comment by leonardder** [comment]
@kvark128 There are still some empty sections in the template. Particularly the Testing performed and known issues sections are important.

Also, I think that I prefer the words to be reordered here:

* beepForCapitalsPtich
* beepDurationForCapitals > beepForCapitalsDuration
* beepVolumeForCapitals > beepForCapitalsVolume

**Comment by Brian1Gaff** [comment]
Which reminds me, some people have asked if the beep can be made less harsh 
sounding, which I believe meens more sine wave like and with a softer start 
and end. The only way to do that I fancy is with bespoke  sound effects 
played at the time though.
 Brian

bglists@blueyonder.co.uk
Sent via blueyonder.
Please address personal E-mail to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.
Newsgroup monitored: alt.comp.blind-users
----- Original Message -----

**Pull request closed without merging**
