### PR TITLE
Recognize Windows 11 build 26100 as 24H2 RTM

### LINKED ISSUE #16439: Windows 11 Version 24H2: recognize build 26100 as RTM build
Hi,

Part of winVersion module maintenance:

### Is your feature request related to a problem? Please describe.
As of NVDA 2024.2, NVDA offers basic support for Windows 11 2024 Update (Version 24H2), specifically #16348. Therefore it makes sense to add the actual build number to winVersion module. Also, signs point to the below build as being the RTM, such as preview cumulative updates adn Xbox build numbers.

### Describe the solution you'd like
Recognize build 26100 as Windows 11 Version 24H2 (and Server 2025) base (RTM) build.

### Describe alternatives you've considered
Leave things as is.

### Additional context
Version 24H2 is an OS upgrade - new build, changed system components, and several removals. Microsoft is putting finishing touches to it, including AI Explorer, fixing bugs, and other things. Windows 11 24H2 will be released in two waves (source: Windows Central):

* Northern summer (June at the earliest): ARM64 version
* Northern fall (September at the earliest): AMD64
At the moment Windows Insiders in dev and canary channels are running the base build (26100) and a staging build (26200), respectively. I expect beta and release preview Insiders to meet 24H2 in the beginning and middle of northern summer, respectively, with general availability being later this year.

Based on how 24H2 updates turn out, the new winVersion.WinVersion entry can be part of NVDA 2024.2 (beta branch_ or 2024.3 (future alpha). For now I'll submit a pull request targeting beta branch in May.

Thanks.

### PR DESCRIPTION
**Pull request by josephsl**
### Link to issue number:
Closes #16439 

### Summary of the issue:
Recognize Windows 11 build 26100 as 24H2 (2024 Update and Server 2025) RTM build.

### Description of user facing changes
None

### Description of development approach
winVersion.WIN11_24H2 constant is defined, as wel as updating last tested Widows version in AppX manifest to 10.0.26100.

### Testing strategy:
Manual testing: on Windows 11 24H2 build 26100, make sure winVersion.getWinVer() == winVersion.WIN11_24H2.

### Known issues with pull request:
None

### Code Review Checklist:

- [x] Documentation:
  - Change log entry
  - User Documentation
  - Developer / Technical Documentation
  - Context sensitive help for GUI changes
- [x] Testing:
  - Unit tests
  - System (end to end) tests
  - Manual testing
- [x] UX of all users considered:
  - Speech 
  - Braille
  - Low Vision
  - Different web browsers
  - Localization in other languages / culture than English
- [x] API is compatible with existing add-ons.
- [x] Security precautions taken.

### Additional context:
With OEM's planning to release AI PC's powered by Windows 11 2024 Update as early as June, the normal timeline for recording new Windows 11 public build was sped up. NOrmaly this pull request would be scheduled once release preview Windows Insiders receive the RTM build (end of northern summer), but for 24H2, build 26100 was finalized in late March (earlier than usual).

Thanks.

### CODE REVIEW

**Review by seanbudd — APPROVED** [review]

**Comment by josephsl** [comment]
Hi,

Build 26120 is an enablement package on top of 26100 (base build). This is also the case with beta channel currently where 22635 is an enablement package on top of 22631, itself an enablement package for 22621. The branch that compiles build 26120 is a beta flight (betaflt) subbranch of ge_release (Germanium platform release and servicing) branch.

Additional evidence:

* PC canary: build 26200 is a ge_prerelease (Germanium feature development/backporting and testing) build. The milestone prerelease branch such as ge_prerelease and ni_prerelease are used to develop and backport features and have higher build numbers than the public build.
* Ability to install 26100.268 on non-Insider systems: I can confirm that it is possible for non-Insiders to instlal build 26100.268 (this is because revision 268 comes from in-market (im) subbranch).
* Base builds were released to the public prior to enablement packages: the best example is Windows 10 build 1904x - base build is still 19041 (Windows 10 Version 2004) because 20H2 and above are enablement package(s) on top of the base build.
* Base build was released to OEM's: build 26100.2 was compiled in April and comes from the OEM subbranch of Germanium platform release.
* No SDK releases above 26100 (yet): if we do have an SDK build in the 261xx series, then we should reconsider this pull request. However, there is none at this time apart from 26100.
* Xbox: typically Xbox system software public builds are based on publicly released milestone build (for example, build 22621 between version 2208 and 2306), with release preparation and support revision numbers above 1500 (the public revision build number is above this, usually 1700 or above). As of this comment, the latest skip ahead (2408) Insider build is 26100.15xx, with 16xx builds to be released to Insiders as early as this week. After 2406 is finalized (internally in late May), I expect Xbox alpha Insiders to receive invitations to upgrade to 2408 (skip ahead) build, with beta, delta, and omega Insiders to follow throughout northern summer.

Thanks.

**Comment by seanbudd** [comment]
Happy to merge this once a public beta release occurs

**Comment by josephsl** [comment]
Hi, in this case, that’ll be northern summer (I expect that is when beta and/or release preview Insiders will receive 24H2 builds). Thanks.

**Comment by LeonarddeR** [comment]
Thanks for the additional evidence @josephsl. I assume we can safely wait a bit longer until some things at Microsoft have settled down a bit more.

**Comment by josephsl** [comment]
Hi,

It looks like Windows 11 2024 Update/Server 2025 evaluation ISO's are up, along with SDK. Also, build 26100.560 was published to what may turn out to be release preview channel as everyone who is not a Windows Insider running 26100 has received it last week (I have confirmed it). I propose looking into this in June (perhaps rebasing it on master).

Thanks.

**Comment by josephsl** [comment]
Hi,

And now build 26100 (revision 712) has arrived in release preview channel (officially). I propose merging it in time for 2024.3 beta.

Thanks.

**Pull request merged**
