### PR TITLE
Add @codeofdusk attribution for 2024.1

### PR DESCRIPTION
**Pull request by codeofdusk**
### Link to issue number:
Fix-up of #15435

### Description of how this pull request fixes the issue:
Add @codeofdusk attribution for 2024.1
### Testing strategy:
N/A

### Code Review Checklist:

- [x] Documentation:
  - Change log entry
  - User Documentation
  - Developer / Technical Documentation
  - Context sensitive help for GUI changes
- [x] Testing:
  - Unit tests
  - System (end to end) tests
  - Manual testing
- [x] UX of all users considered:
  - Speech 
  - Braille
  - Low Vision
  - Different web browsers
  - Localization in other languages / culture than English
- [x] API is compatible with existing add-ons.
- [x] Security precautions taken.

### CODE REVIEW

**Comment by seanbudd** [comment]
Please do not make accreditation on behalf of other authors, it is up to them if they want to have their profile linked.

**Comment by codeofdusk** [comment]
This PR includes contributions by me. How do I opt into accreditation?

**Comment by seanbudd** [comment]
You can remove the other accreditations and we can merge this

**Comment by codeofdusk** [comment]
OK. In case they want to add attributions, CCing @alexmoon, @CyrilleB79, @dmitrii-drobotov, @leonardder, @michaelweghorn.

**Review by seanbudd — APPROVED** [review]

**Pull request merged**
