### PR TITLE
Optionally play sounds when toggling screen curtain

### LINKED ISSUE #10476: Screen curtain should not be based off configuration profiles
#Steps to reproduce:

1. Assign the screen curtain command to a gesture.
2. Turn on screen curtain while in the default profile. It doesn't matter if its only temporarily or permanently on while NVDA is active.
3. Switch to an app which would cause a different profile to load, e.g one for programming.

### Actual behavior:

The screen curtain is automatically disabled when switching to an application which uses a profile where screen curtain has not yet been enabled. Users also receive no alerts about this surprising and potentially dangerous behaviour. The only way to know is to visually see the screen.

### Expected behavior:

The screen curtain should not automatically disable itself when switching profiles. I think this is a setting which makes much more sense to be global to avoid unwanted surprises. I'm also not sure what the use case is for having it automatically turn on only in certain applications, which the current implementation enables.

#### NVDA installed/portable/running from source:

Installed

#### NVDA version:

alpha-19136,0124e647

#### Windows version:

1905

#### Name and version of other software in use when reproducing the issue:

N/a

#### Other information about your system:

N/a

#### Does the issue still occur after restarting your PC?

Yes

#### Have you tried any other versions of NVDA? If so, please report their behaviors.

N/a

### LINKED ISSUE #10602: Re-add Screen Curtain Enabled Beep at NVDA StartUp
### Is your feature request related to a problem? Please describe.
If a user is is expecting the enabled beep that was available in the Screen Curtain add-on when NVDA was started and Screen Curtain was enabled by default, they may incorrectly assume that Screen Curtain is not enabled in NVDA 2019.3beta1 after a restart.

### Describe the solution you'd like
If it is possible, it would be great to have the beep that played when NVDA started and Screen Curtain was enabled by default implemented in NVDA 2019.3. This beep provides piece of mind that Screen Curtain is in deed enabled and saves the user from having to check, especially  if they frequently have to toggle Screen Curtain on or off.

### Describe alternatives you've considered
N/A

### Additional context
N/A

### PR DESCRIPTION
**Pull request by LeonarddeR**
Note: filed against beta.

### Link to issue number:
Fixes #10602 
Closes #10476 

### Summary of the issue:
There is currently no audible indication of the screen curtain turning on/off due to a configuration profile change.

### Description of how this pull request fixes the issue:
Add screen curtain on/off sounds, provided by Andre Louis. Also make sure that the screen curtain is only activated once (i.e not reinitialized) when enabling permanently.

### Testing performed:
Tested enabling/disabling the curtain using a config profile and the global command script.

### Known issues with pull request:
While this strictly spoken does not fix #10476, I think having the ability to enable screen curtain in one profile while disabling it in another has too much benefits to justify making it a global setting. Specifying what settings should be global is a different issue.

### Change log entry:
None needed

### CODE REVIEW

**Review by OzancanKaratas — APPROVED** [review]

**Comment by josephsl** [comment]
Eh? Sorry, but this review approval didn’t count. I’ll take care of it in just a few moments. Thanks.

**Review by josephsl — CHANGES_REQUESTED** [review]
Hi,

Two important things, both in user guide:

1. Vision/screen curtain section: can you add a brief note about sounds to indicate screen curtain toggle?
2. In line 1399: screen curtain is misspelled.

A minor thing about Andre's sounds: the "on" sound is heard predominantly from the left side. I think we should compensate for that somehow (or it could be my hearing or my headset).

Thanks.

**Review by josephsl — APPROVED** [review]
Thanks.

**Review by michaelDCurran — APPROVED** [review]

**Comment by davidacm** [comment]
is just my mind or is the sound (ON / OFF) not clear enough?
I can identify it, but it could be difficult for people with hearing loss.

**Pull request merged**
