### PR TITLE
Braille: show selection when tethered to review in edit controls and documents

### PR DESCRIPTION
**Pull request by burmancomp**
### Link to issue number:
closes #3095, #15994, #16549

### Summary of the issue:
When braille is tethered to review selection is not shown in edit controls and documents.
### Description of user facing changes
Selection is shown when "Show selection" setting is enabled.
### Description of development approach
Variant of #16038 which does not depend on scripts.
### Code Review Checklist:

- [x] Documentation:
  - Change log entry
  - User Documentation
  - Developer / Technical Documentation
  - Context sensitive help for GUI changes
- [x] Testing:
  - Unit tests
  - System (end to end) tests
  - Manual testing
- [x] UX of all users considered:
  - Speech 
  - Braille
  - Low Vision
  - Different web browsers
  - Localization in other languages / culture than English
- [x] API is compatible with existing add-ons.
- [x] Security precautions taken.

### CODE REVIEW

**Comment by burmancomp** [comment]
I wanted to try second time. This version does not depend on scripts.

@LeonarddeR what do you think, is this ready for close?

**Comment by burmancomp** [comment]
Could you @Jykke67 / @irrah68 / @Emil-18 test this build [https://ci.appveyor.com/api/buildjobs/wi5nx56hfrfrwehe/artifacts/output%2Fnvda_snapshot_pr16468-32166%2Cff82fa3e.exe](https://ci.appveyor.com/api/buildjobs/wi5nx56hfrfrwehe/artifacts/output%2Fnvda_snapshot_pr16468-32166%2Cff82fa3e.exe).

Behavior has changed when show selection is disabled; also hopefully a couple of fixes from previous build of this pr.

See also discussion in issue #16549.

**Comment by irrah68** [comment]
I tested this pr but I didn't notice any strange things. My Braille display showed the last line of the selected area as selected.

But I found an interesting thing when I tested with Notepad (Windows 11). When I selected a text area with Shift+DownArrow very slowly, the Braille display was showing the first line of — for example — three selected lines. But when I selected the same lines very fast or in a so called normal way, the display was showing the last selected line. I couldn't reproduce this in Wordpad, only in Notepad.

Braille is tethered to review and review follows caret.

**Comment by LeonarddeR** [comment]
@burmancomp I'm very sorry for the inconvenience, but I'm going to close this pull request for now. As clearly stated by @seanbudd in https://github.com/nvaccess/nvda/pull/16038#issuecomment-2065786592, #12772 needs to be addressed first. Also @michaelDCurran stated in https://github.com/nvaccess/nvda/pull/16038#issuecomment-2065324752 that he has his concerns about the proposed behavior.
I think I speak for everyone when I say that your efforts are greatly appreciated. However, you also honestly indicate that your skills are limited. We are talking about a part of the braille code where in-depth knowledge of the braille module is really necessary.
So if you really want to take a step forward with this, I'd suggest investing your time into fixing #12772, that is if @seanbudd is not planning to do this himself.

**Comment by burmancomp** [comment]
May I ask what were problems in implementation this time?

**Comment by Jykke67** [comment]
I don’t have any answer to you, but I doubt if my testing of the latest PR would give more information of interest. Of courese I can still test it, even though the issue is already closed.

**Comment by Jykke67** [comment]
Updated to this PR but found no difference to the previous ones.

Talking about NVDA pr16468-32166,ff82fa3e.

**Pull request closed without merging**
