### PR TITLE
Update liblouis to 3.17.0

### PR DESCRIPTION
**Pull request by AAClause**
### Link to issue number:
None

### Summary of the issue:
Liblouis 3.17.0 has just been released.

### Description of how this pull request fixes the issue:
Updates liblouis to 3.17.0 which adds Belarusian braille tables and [other awesome things](https://github.com/liblouis/liblouis/releases/tag/v3.17.0).

### Testing strategy:
- Ran from sources.
- Tested new braille tables (input and output).

### Known issues with pull request:
None

### Change log entry:

Section: Changes

```
- Updated liblouis braille translator to [3.17.0 https://github.com/liblouis/liblouis/releases/tag/v3.17.0]. (#12137)
  - New braille tables: Belarusian literary braille, Belarusian computer braille, Urdu grade 1, Urdu grade 2.
```

### Code Review Checklist:

This checklist is a reminder of things commonly forgotten in a new PR.
Authors, please do a self-review and confirm you have considered the following items.
Mark items you have considered by checking them.
You can do this when editing the Pull request description with an x: `[ ]` becomes `[x]`.
You can also check the checkboxes after the PR is created.

- [x] Pull Request description is up to date.
- [x] Unit tests.
- [x] System (end to end) tests.
- [x] Manual tests.
- [x] User Documentation.
- [x] Change log entry.
- [x] Context sensitive help for GUI changes.

### CODE REVIEW

**Comment by lukaszgo1** [comment]
Thanks for this PR @aaclause 
LibLouis 3.17 adds some small but important fixes to the Polish tables - users of Polish braille would appreciate this being merged in time for NVDA 2021.1.

**Comment by aaclause** [comment]
Why the system tests are randomly failing?

**Comment by feerrenrut** [comment]
Does the change log entry for this PR need to refer to the Polish fixes @lukaszgo1 ?

**Comment by feerrenrut** [comment]
Never mind @lukaszgo1 I think it is enough that the new tables are mentioned and the link to the release notes is included.

**Review by feerrenrut — APPROVED** [review]
Thanks @aaclause

**Pull request merged**
