### PR TITLE
Update CLDR to version 38

### PR DESCRIPTION
**Pull request by OzancanKaratas**
### Link to issue number:
None
### Summary of the issue:
The CLDR team released new version of the CLDR.
### Description of how this pull request fixes the issue:
This pull request does not fixes any issue.
### Testing performed:
None
### Known issues with pull request:
None
### Change log entry:

Section: Changes
- Updated CLDR emoji annotation to version 38.

### CODE REVIEW

**Comment by OzancanKaratas** [comment]
@leonardder, can you review?

**Review by LeonarddeR — COMMENTED** [review]
Please revert the changes to the changes file. It will be updated at merge time.

**Comment by OzancanKaratas** [comment]
> Please revert the changes to the changes file. It will be updated at merge time.

@leonardder, I requested a review from you. Your request has been done.

**Review by michaelDCurran — DISMISSED** [review]

**Review by LeonarddeR — DISMISSED** [review]

**Comment by michaelDCurran** [comment]
I have approved this pr and updated What's new. Though I had not gotten around to merging yet as there was unrelated system test failures. There now seem to be extra commits... Can you explain the extra changes?

**Comment by OzancanKaratas** [comment]
While merging from master, multiple commitments occurred and I revert them. My goal was to fix the system test error. But I guess this pull request should be closed or rereview.

**Comment by OzancanKaratas** [comment]
While merging from master, multiple commits occurred and I revert them. My goal was to fix the system test error. But I guess this pull request should be closed or rereview.

**Comment by OzancanKaratas** [comment]
@michaelDCurran This pull request can now be mergable!

**Comment by OzancanKaratas** [comment]
This pull request now includes all changes in the nv access / nvda repository's master branch. Although there are many commits, it will not change things that should not be changed.

**Comment by OzancanKaratas** [comment]
A friend of mine who is a Git expert said I need to address these changes in a different pull request. This pull request will be closed.

**Pull request closed without merging**
