### PR TITLE
UI Automation in Windows Console: revert for 2019.3

### PR DESCRIPTION
**Pull request by codeofdusk**
### Link to issue number:
Completes #10682.

### Summary of the issue:
It was decided to revert to legacy console support for 2019.3, but various UI and user guide elements remain from #9771.

### Description of how this pull request fixes the issue:
* The `auto` config setting is reverted to 2019.2 behavior (i.e. it maps to legacy).
* The UI is returned to 2019.2 state (i.e. a simple checkbox). We really should move users to UIA once it becomes the default, and users who turn on UIA to experiment during development and then switch back to legacy wouldn’t automatically be upgraded.
* References to “legacy” consoles removed from UI and user guide.

### Testing performed:
Tested an upgrade from NVDA 2019.2.1 (stable) to this PR. Insured that legacy console is used by default and the UIA checkboxes are functional.

### Known issues with pull request:
None.

### Change log entry:
None needed.

### CODE REVIEW

**Comment by codeofdusk** [comment]
Cc @leonardder @michaelDCurran

**Comment by michaelDCurran** [comment]
the 'and's need to be on the start of the next line to stop the linting issues I think.

**Comment by leonardder** [comment]
I think this was already done using the https://github.com/nvaccess/nvda/tree/legacyWinConsoleByDefault branch

**Comment by codeofdusk** [comment]
> 
> 
> I think this was already done using the https://github.com/nvaccess/nvda/tree/legacyWinConsoleByDefault branch

No, not quite. This PR reverts some additional UI, user guide, and behavior changes that were needed when UIA was the default.

**Comment by codeofdusk** [comment]
> 
> 
> > I think this was already done using the https://github.com/nvaccess/nvda/tree/legacyWinConsoleByDefault branch
> 
> No, not quite. This PR reverts some additional UI, user guide, and behavior changes that were needed when UIA was the default.

It also keeps "auto" as the default config spec setting, allowing users to freely enable/disable UIA console during development and be automatically switched when it becomes the default.

**Review by michaelDCurran — APPROVED** [review]

**Pull request merged**
