### PR TITLE
Add Bangla locale to windowsPrimaryLCIDsToLocaleNames

### PR DESCRIPTION
**Pull request by seanbudd**
### Link to issue number:

None

### Summary of the issue:

The latest PR (#13338) to merge beta to master has failed, due to Bangla translations being introduced and NVDA not fully supporting them yet. [AppVeyor build failure](https://ci.appveyor.com/project/NVAccess/nvda/builds/42562857/tests)

### Description of how this pull request fixes the issue:

Add Bangla locale to windowsPrimaryLCIDsToLocaleNames

### Testing strategy:

Create a try build of beta merged into this PR: [Note that both unit and system tests pass](https://ci.appveyor.com/project/NVAccess/nvda/builds/42563274/tests)

### Known issues with pull request:

None

### Change log entries:
None

### Code Review Checklist:

- [x] Pull Request description:
  - description is up to date
  - change log entries
- [x] Testing:
  - Unit tests
  - System (end to end) tests
  - Manual testing
- [x] API is compatible with existing add-ons.
- [x] Documentation:
  - User Documentation
  - Developer / Technical Documentation
  - Context sensitive help for GUI changes
- [x] UX of all users considered:
  - Speech 
  - Braille
  - Low Vision
  - Different web browsers
  - Localization in other languages / culture than English

### CODE REVIEW

**Comment by CyrilleB79** [comment]
Hello

Here are 4 threads on the translators mailing list regarding Bangla translation: [thread 1](https://groups.io/g/nvda-translations/topic/bengali_bangla_translator/87534846?p=,,,100,0,0,0::recentpostdate/sticky,,,100,2,0,87534846,previd=1644659407426666309,nextid=1622500367292145478&previd=1644659407426666309&nextid=1622500367292145478), [thread 3](https://groups.io/g/nvda-translations/topic/88273927?p=Created%2C%2C%2C100%2C2%2C0%2C0%3A%3Arecentpostdate%2Fsticky%2C%2C%2C100%2C2%2C0%2C88273927%2Cprevid%3D1644659407426666309%2Cnextid%3D1622500367292145478), [thread 3](https://groups.io/g/nvda-translations/topic/87648876?p=Created%2C%2C%2C100%2C1%2C0%2C0%3A%3Arecentpostdate%2Fsticky%2C%2C%2C100%2C2%2C0%2C87648876%2Cprevid%3D1644659407426666309%2Cnextid%3D1622500367292145478), [thread 4](https://groups.io/g/nvda-translations/topic/want_to_translate_nvda/87996774?p=,,,100,0,0,0::recentpostdate/sticky,,,100,2,0,87996774,previd=1644659407426666309,nextid=1622500367292145478&previd=1644659407426666309&nextid=1622500367292145478)

To summarize two translators are willing to translate NVDA to Bangla/Bengali and we are continuing discussion privately to help them do the job. For now:
* I have added files in SRT repo to have a starting point for Bangla translation
* The Bangla character description file already exists in NVDA so I have copied it to the SRT repo.
* One translator has done a part of the symbol translation but is blocked trying to commit his job with SVN
* The other translator has expressed the will to translate the interface and the user guide. However, I do not know how far is his work and if he has succeded in starting it: I have no news from him for some weeks.

For now only a translated symbol file can be added to NVDA 2022.1. But with the news I have today, I doubt that the interface file will be ready.

What do you suggest to do? For now, I think that Bangla has already appeared in the language list of General settings window in beta branch (to be confirmed). But the interface will be exclusively in English for now.

Thanks.

**Comment by CyrilleB79** [comment]
In addition, here are review feedbacks on this PR:

1. Could you describe in this PR how `windowsPrimaryLCIDsToLocaleNames` is obtained? The comment says:
   `# Generated from: {x&0x3ff:y.split('_')[0] for x,y in locale.windows_locale.iteritems()}`
   But:
   * This comment should at least be updated to Python 3 (`iteritems` -> `items`)
   * This comment does not seem true anymore since there are values above 1023 (0x3FF) in the dictionnary.

2. It would be interesting to explain in the comments or at least in the PR why adding this line is needed whereas there is already a `bn` item in the dictionnary:
`69: 'bn'`
The same for `sr` that appears two times (26 and 9242).

3. Why do values above 1023 appear in this dictionnary (1170: 'ckb', 1109: 'my', 1143: 'so')?

**Comment by josephsl** [comment]
Hi, I vote to delay Bengali to 2022.2. If we caught this in say, late January, I think it would have made it to 2022.1. However, given that beta to master and master to beta exchange was declared today, I think we don’t have time to get a new language into NVDA, especially given that it will take several weeks to test the user interface fully. Folks can say that we can improve things during the beta cycle, but it is a bit risky this time since we are dealing with a year.1 beta, which puts pressure on not only translators, but also on add-ons community as well. Another option is delay beta to master merge for about a week or so in hopes that Bengali interface is in, but then it puts pressure on translators to complete their work and test the interface. Thanks.

**Comment by lukaszgo1** [comment]
[...]
>     * I have added files in SRT repo to have a starting point for Bangla translation

I'm not familiar with the translations system (perhaps this was always done as you've described above) so please don't take this as a criticism but IMO introducing a template .po file into SRT until it is at least partially translated causes more trouble than it is worth. Aside from the issue that there is a  new language which exists in preferences but does not contain translatable messages it just pollutes the SVN commit history unnecessarily.  I tent to agree with @josephsl  that the best course of action for now would be to remove the .po template from SVN and document that only partially translated files should be committed into SVN to avoid similar issues in the future.

**Comment by CyrilleB79** [comment]
No problem for criticism. I try to do my best to drive Bangla translators since no one else had answered their messages. But that's the first time I do it, so I am opened to any remark to improve.

I agree that Bangla translation should not be included in 2022.1 since it is clear that will not be mature enough for that time. At the beginning, I had thought that it would be interesting to have a working translation framework but I realize now that I should have waited a bit more. Sorry for the confusion.

It should now be determined the best way to exclude Bangla translation. I think that:
1. In beta branch, the bn nvda.po should be removed (to avoid Bangla to appear in the language list for now)
and
2. An action in the SVN repo should be done to avoid the copy of nvda.po. It can be:
   * removing nvda.po for now from SVN repo
   * another action in the settings file to avoid triggering the copy of the nvda.po again from SVN to beta branch

If nvda.po can remain in the SRT repo, it would be better since it can help the translator to learn to use SVN. If not, no problem, let's remove it for now.

Let's wait for NVAccess comments to decide how to resolve this issue.
Cc @seanbudd, @feerrenrut

**Comment by seanbudd** [comment]
The existing work done in `characterDescriptions.dic` and `cldr.dic` is valuable, and an improvement to NVDA. 
Instead, we can just hide `bn` from the UX.

**Comment by josephsl** [comment]
Hi, I think that’s a doable short-term solution. Of course the long-term solution is communicating with Bengali translators. Thanks.

**Comment by josephsl** [comment]
Hi, as a follow-up thought: I think we might as well use this opportunity to spell out the order of things to be translated and committed. The order of precedence (as noted in “translating NVDA” document) is user interface (nvda.po) as highest of highest of priorities, followed by character descriptions and symbols, and if time permits, user guide and what’s new document, and based on feedback from the language community, add-ons. Of course we should also think about a possibility like the one we are facing at the moment (no user interface translation but we do have character descriptions and CLDR data). Thanks.

**Comment by seanbudd** [comment]
@josephsl 
For now we propose keeping 'bn' in the UI. we already have several other languages with low completion, there isn't any harm for a user selecting 'bn' (missing translations fall back to English), and we don't want to have to manually reenable 'bn' later.

Also, discussions surrounding translations are better suited to a separate issue/discussion or the mailing list.

**Comment by josephsl** [comment]
Hi, in that case, let’s do as proposed – keep bn interface and transfer communication with translators to translations list. Thanks.

**Comment by CyrilleB79** [comment]
In the beginning, I have asked bn translators (Fahim FARHAN ISHRAK and Abu Faraj ) to continue e-mail exchanges privately to set up SVN and so on since they needed very basic instructions and I did not want to clutter the list with a lot of messages, the translator mailing list being described as a low-traffic mailing list.

But given our discussion here, I understand the need to have exchange with bn translators public on the translator mailing list. I will send a message to ask them to use the list instead of our private e-mail exchanges from now on.

**Comment by seanbudd** [comment]
Closing in favour of #13342.
Note that the addition of Bangla to beta is due to the translation system, and introducing it to alpha will happen with a future merge of beta to master.
These PRs are for improving locale support, in preparation of this.

**Pull request closed without merging**
