### PR TITLE
Mark SysListView32 as bad for UIA in mmc

### LINKED ISSUE #1533: Caret navigation does not work fully in ThinBasic's ThinAir editor
**Reported by oaron on 2011-05-30 21:20**
NVDA is not able to successfully track the cursor when navigating character by character in ThinBasics code editor, ThinAir.
Reading line by line seems to work, however using any other key to navigate, e.g. left and right arrow, home, end, page up or down, NVDA does not seem to follow the cursor.
ThinBasic's latest beta can be downloaded from here:
http://www.thinbasic.biz/projects/thinbasic/thinBasic_1.8.7.0.zip

Some info about the edit control:
Developer info for navigator object:
name: u"' Empty GUI script created on 05-30-2011 23:17:26 by  (ThinAIR)\r\n"
role: ROLE_EDITABLETEXT
states: STATE_FOCUSABLE, STATE_FOCUSED
Python object: <NVDAObjects.Dynamic_IAccessibleDisplayModelEditableTextWindowNVDAObject object at 0x05C3A8B0>
Python class mro: (<class 'NVDAObjects.Dynamic_IAccessibleDisplayModelEditableTextWindowNVDAObject'>, <class 'NVDAObjects.IAccessible.IAccessible'>, <class 'NVDAObjects.window.DisplayModelEditableText'>, <class 'NVDAObjects.behaviors.EditableText'>, <class 'editableText.EditableText'>, <class 'NVDAObjects.window.Window'>, <class 'NVDAObjects.NVDAObject'>, <class 'baseObject.ScriptableObject'>, <class 'baseObject.AutoPropertyObject'>, <type 'object'>)
description: None
location: (201, 87, 1398, 748)
value: None
appModule: <'appModuleHandler' (appName u'thinair', process ID 10256) at address 5c3ae70>
TextInfo: <class 'displayModel.EditableTextDisplayModelTextInfo'>
windowHandle: 3738048
windowClassName: u'CodeSense'
windowControlID: 2150
windowStyle: 1375731712
windowThreadID: 11368
windowText: u"' Empty GUI script created on 05-30-2011 23:17:26 by  (ThinAIR)\r\n"
IAccessibleObject: <POINTER(IAccessible) ptr=0x8143ea8 at 5c47f80>
IAccessibleChildID: 0
IAccessible event parameters: windowHandle=3738048, objectID=-4, childID=0
IAccessible accRole: ROLE_SYSTEM_CLIENT
IAccessible accState: STATE_SYSTEM_FOCUSED, STATE_SYSTEM_FOCUSABLE, STATE_SYSTEM_VALID (1048580)

### LINKED ISSUE #15333: Unable to access some list of Windows components
### Steps to reproduce:
- Try to access for example to services list (services.msc)

### Actual behavior:

- NVDA don't read list item and error shown in the log

### Expected behavior:

- NVDA should read list correctly

### NVDA logs, crash dumps and other attachments:
- Log attach to the comment

#### NVDA installed/portable/running from source:
- Installed

#### NVDA version:
- alpha-28949,1e30951e

#### Windows version:
- Windows 11 22H2 (AMD64) build 22621.2134

#### Name and version of other software in use when reproducing the issue:
- services.msc, gpedit.msc

#### Does the issue still occur after restarting your computer?
- Yes

#### Have you tried any other versions of NVDA? If so, please report their behaviors.
- Works fine with stable NVDA version

#### If NVDA add-ons are disabled, is your problem still occurring?
- Yes

#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
- Yes
[nvda.log](https://github.com/nvaccess/nvda/files/12446825/nvda.log)

### PR DESCRIPTION
**Pull request by LeonarddeR**
### Link to issue number:
Fixes #15333

### Summary of the issue:
In #15295, we removed SysListView32 as a bad UIA class name as there are now decent UIA implementations that should be prefered over their MSAA counterparts. However, it turns out that Windows Management Console, despite advertising a native UIA implementation, offers something quite incomplete.

### Description of user facing changes
Working list navigation in mmc, such as in windows Services list

### Description of development approach
1. Classify SysListView32 as Bad UIA class in the mmc app module. Note. I have also tested several other applications in Windows, including regedit, and there no UIA implementation of SysListView32 is advertised. Therefore I think this might be a onetimer.
2. Ensures that whenever UIA is used wit an incomplete implementation, no errors occur by performing the necessary checks.

### Testing strategy:
Tested the services list with and without mmc appModule change.

### Known issues with pull request:
None known

### Change log entries:
None needed.

### Code Review Checklist:

- [x] Pull Request description:
  - description is up to date
  - change log entries
- [x] Testing:
  - Unit tests
  - System (end to end) tests
  - Manual testing
- [x] API is compatible with existing add-ons.
- [x] Documentation:
  - User Documentation
  - Developer / Technical Documentation
  - Context sensitive help for GUI changes
- [x] UX of all users considered:
  - Speech 
  - Braille
  - Low Vision
  - Different web browsers
  - Localization in other languages / culture than English
- [x] Security precautions taken.

### CODE REVIEW

**Comment by XLTechie** [comment]
@leonardder, can you double check the "Link to issue number" section of this PR 
please?

**Review by seanbudd — APPROVED** [review]
Thanks @leonardder

**Comment by seanbudd** [comment]
I've fixed this @xltechie

**Comment by seanbudd** [comment]
Could you please fix up the lint check? `from logHandler import log` is missing

**Pull request merged**
