### PR TITLE
Set HTML lang attribute for documentation

### LINKED ISSUE #8856: HTML "lang" & "dir" attributes are missing in the NVDA documentations for some languages
NVDA documentations are HTML files that translated into many languages.
Unfortunately, "lang" & "dir" attributes are missing in NVDA docs for many languages.
The HTML documentations files are: "changes.html", "keyCommands.html", and "userGuide.html".
The "LANG" attribute helps NVDA to determine the language of documentation and always use the correct synthesizer.
The "DIR" attribute has the default value of "LTR" that is ok for most languages but for the right-to-left 
languages such as Persian (fa), Arabic (ar), and Hebrew (he), it must be set to "RTL" to show the documents in the correct view that be possible for reading. 
For example, currently the "nvda_2018.3.2\documentation\fa\keyCommands.html" have not even the DIR='RTL' attribute, while the corresponding file in the Arabic translation is ok.
Please fix this issue.
Thanks in advance

### PR DESCRIPTION
**Pull request by bramd**
### Link to issue number:
Closes #8856

### Summary of the issue:
The generated HTML from t2t (changes, quick reference, user guide) has no lang attribute set. So, it will not read in the correct TTS language.

### Description of how this pull request fixes the issue:
Include a locale.t2tconfig for every language to set the lang attribute and ensure it is included in all documents.

### Testing strategy:
Opened a few generated HTML documents and ensured the lang attribute was present and set correctly.

### Known issues with pull request:
Some languages may need RTL (right to left) as a reading direction which would require the `dir="rtl"` attribute as well. However, at least setting lang will improve things and not break anything.

### Change log entries:
New features
Changes
Bug fixes
  - The documentation (What's new in NVDA, User Guide and Quick Reference) will be read with the correct TTS langauge (if a suitable voice is installed) (#8856)
For Developers

### Code Review Checklist:

- [x] Pull Request description:
  - description is up to date
  - change log entries
- [x] Testing:
  - Unit tests
  - System (end to end) tests
  - Manual testing
- [x] API is compatible with existing add-ons.
- [x] Documentation:
  - User Documentation
  - Developer / Technical Documentation
  - Context sensitive help for GUI changes
- [x] UX of all users considered:
  - Speech 
  - Braille
  - Low Vision
  - Different web browsers
  - Localization in other languages / culture than English

### CODE REVIEW

**Comment by lukaszgo1** [comment]
> Some languages may need RTL (right to left) as a reading direction which would require the `dir="rtl"` attribute as well. However, at least setting lang will improve things and not break anything.

While this is certainly an improvement reporter of #8856 asked specifically about setting reading direction and closing this issue when this PR is merged makes it pretty easy for this problem to be forgotten. IMO #8856  should either remain open until reading direction is added for all languages or this should be done as part of this PR.

**Comment by seanbudd** [comment]
@feerrenrut Is updating the translated *.t2t files in this manner safe?

**Comment by bramd** [comment]
> While this is certainly an improvement reporter of #8856 asked specifically about setting reading direction and closing this issue when this PR is merged makes it pretty easy for this problem to be forgotten. IMO #8856 should either remain open until reading direction is added for all languages or this should be done as part of this PR.

That's true. However, I'm not comfortable setting text direction without getting people of the affected localizations involved. For most rtl languages, some text like numbers might need an explicit `dir=ltr` (see for example Arabic).

**Comment by feerrenrut** [comment]
>Is updating the translated *.t2t files in this manner safe?

Not really, this _COULD_ cause merge conflicts. Really only the `en` should be updated here, and the rest of the files via the screenReaderTranslations Subversion repository.

**Comment by bramd** [comment]
@feerrenrut Good to know. I should still have access to that repo due to my work on the NL translation. Should I commit the changes there or should we first discuss this with translation teams?

**Comment by seanbudd** [comment]
Converting this to a draft until a translation strategy is determined.

**Comment by feerrenrut** [comment]
>Should I commit the changes there or should we first discuss this with translation teams?

@bramd it's would be nice to give some advanced warning ([an email to the NVDA translators mailing list](https://groups.io/g/nvda-translations/post)), but I don't expect any opposition to this.

**Comment by zstanecic** [comment]
Lang attribute is good, cause it will allow adding language recognition for reading with our synthesizers.

**Comment by seanbudd** [comment]
This PR is still blocked by only changing this in the "en" file.
I would suggest adding `dir="ltr"` as well.
Translators should handle this change in their respective files.

**Review by Qchristensen — APPROVED** [review]
Good work everyone

**Comment by seanbudd** [comment]
Closing as abandoned, superseded by #14546

**Pull request closed without merging**
