### PR TITLE
New command: Move review cursor to position marked as start for copy (#1969)

### LINKED ISSUE #1969: jump to selection start marker
**Reported by peter on 2011-11-27 11:09**
Hi all,
Is it possible to give the user a possibility to quickly move review cursor to the position of "start of text to be copyed" (nvda+f9)? This should be useful in many situations, e.g. temporary placemarker replacement in virtual buffers, hopefully workaround for patented fs functionality.

### PR DESCRIPTION
**Pull request by JulienCochuyt**
### Link to issue number:

Fixes #1969

### Summary of the issue:

There is currently no way to tell which review position has been marked as the starting point for a select or copy operation.

### Description of how this pull request fixes the issue:

Add a new command to move the review cursor to the position previously marked as starting point.

### Testing performed:

Tested from source in a terminal, an editor and a web browser.

1. On the the licence agreement dialog for NVDA.
1. Use arrow keys to move the caret to the 'G' from GNU.
1. Press `NVDA+F9` to mark the start.
1. Press the down arrow key several times to move to a new line.
1. Press `NVDA+shift+F9` to move review cursor to start mark
1. Press `Numpad 6` and `Numpad 4` to review words either side of the start mark to get context.

### Change log entry:

Section: New features

A command has been added to move the review cursor to the position previously set as start marker for selection or copy: NVDA+shift+F9

### CODE REVIEW

**Review by LeonarddeR — CHANGES_REQUESTED** [review]
Please use the script decorator for this. script_review_currentSymbol contains a good example.

**Comment by JulienCochuyt** [comment]
> Please use the script decorator for this. script_review_currentSymbol contains a good example.

Done. My bad, I had not noticed new global commands did follow the new construct.
Shall we some day refactor the whole `GlobalCommands` class for better readability?
I think the new construct is a plus, but mixed constructs are confusing for newcomers.

**Comment by leonardder** [comment]
> Done. My bad, I had not noticed new global commands did follow the new construct.

No problem at all.

> Shall we some day refactor the whole `GlobalCommands` class for better readability?

I recall @feerrenrut said somewhere that he'd rather not do this, as it also introduces the risk of breaking things.

**Comment by JulienCochuyt** [comment]
e39527c: Rebased onto latest master

**Review by LeonarddeR — APPROVED** [review]

**Comment by dingpengyu** [comment]
Is this PR ready to merge? I saw that he is now in an approved state.
thanks

**Review by feerrenrut — APPROVED** [review]
Thanks @JulienCochuyt

**Pull request merged**
