### PR TITLE
Fallback to eSpeak if OneCore voices are not installed

### LINKED ISSUE #10451: Windows OneCore, if a given language isn't installed, speech does not fall back to default voice
### Steps to reproduce:

This happened on my home laptop which, being installed with German by default, did not have any of the OneCore English UK or US voices installed. The steps were:

1. Had NVDA 2019.2.1 installed, which used Vocalizer voices.
2. Upgraded to latest 2019.3 alpha build, which started to use the German OneCore voice.
3. Went to the Nuance download page, or it could have been any page that has the page language set to English US or English UK, in Firefox.

### Actual behavior:

Whenever NVDA tried to read something in English from that page, the following error was logged, and the text was not spoken:

```
IO - inputCore.InputManager.executeGesture (14:30:50.699) - winInputHook (1524):
Input: kb(laptop):downArrow
DEBUG - synthDrivers.oneCore.SynthDriver.cancel (14:30:50.707) - MainThread (1348):
Cancelling
DEBUG - synthDrivers.oneCore.SynthDriver._callback (14:30:50.709) - Dummy-6 (8980):
Done pushing audio
DEBUG - synthDrivers.oneCore.SynthDriver._processQueue (14:30:50.709) - Dummy-6 (8980):
Calling idle on audio player
DEBUG - synthDrivers.oneCore.SynthDriver._processQueue (14:30:50.711) - Dummy-6 (8980):
Queue empty, done processing
IO - speech.speak (14:30:50.714) - MainThread (1348):
Speaking [LangChangeCommand ('de_DE'), 'Überschrift  Ebene 4', LangChangeCommand ('en'), 'United Kingdom']
DEBUG - synthDrivers.oneCore.SynthDriver._processQueue (14:30:50.728) - MainThread (1348):
Begin processing speech
IO - braille.BrailleBuffer.update (14:30:50.757) - MainThread (1348):
Braille regions text: ['ü4 United Kingdom ']
IO - braille.BrailleHandler.update (14:30:50.759) - MainThread (1348):
Braille window dots: 12568 1456 - 1367 1345 24 2345 15 145 -
ERROR - NVDAHelperLocal (14:30:50.735) - Dummy-7 (16768):
Thread 16768, build\x86\localWin10\oneCoreSpeech.cpp, ocSpeech_speak::<lambda_21151d5a0dfc8f546bcaed819f94e1de>::operator (), 98:
Error -2147024894: Das System kann die angegebene Datei nicht finden.



Das System kann die angegebene Datei nicht finden.



DEBUGWARNING - synthDrivers.oneCore.SynthDriver._callback (14:30:50.763) - Dummy-7 (16768):
ocSpeech_speak failed!
DEBUG - synthDrivers.oneCore.SynthDriver._processQueue (14:30:50.763) - Dummy-7 (16768):
Calling idle on audio player
DEBUG - synthDrivers.oneCore.SynthDriver._processQueue (14:30:50.765) - Dummy-7 (16768):
Queue empty, done processing
DEBUG - synthDrivers.oneCore.SynthDriver.cancel (14:30:53.350) - MainThread (1348):
Cancelling
```

### Expected behavior:

It should have noticed that the language wasn't available and fell back to the default voice instead.

#### Other information about your system:

None relevant. The braille display connected was a Handy Tech Actilino, but the error occurred without braille as well.

#### Does the issue still occur after restarting your PC?

Yes.

#### Have you tried any other versions of NVDA? If so, please report their behaviors.

I noticed version 2019.2.1, when using with OneCore, did fall back to justusing the normal voice in such cases.

### PR DESCRIPTION
**Pull request by seanbudd**
### Link to issue number:

Fixes #10451

### Summary of the issue:

If a device has no OneCore voices installed, speech fails by default when starting a new NVDA copy.

### Description of how this pull request fixes the issue:

Consider OneCore as unusable if there are no available voices

### Testing strategy:

- [ ] Manual confirmation that this issue still exists on the latest alpha build
- [ ] Manual confirmation that the PR build fixes this issue on devices without any OneCore voices installed
- [x] Manual confirmation that all NVDA synths still work

### Known issues with pull request:

#11544 is still a current issue

### Change log entries:

Bug fixes
```
- NVDA will default to eSpeak if no OneCore voices are installed on the device. (#10451)
```

### Code Review Checklist:

- [x] Pull Request description is up to date.
- [x] Unit tests.
- [x] System (end to end) tests.
- [ ] Manual testing.
- [x] User Documentation.
- [x] Change log entry.
- [x] Context sensitive help for GUI changes.
- [x] UX of all users considered:
  - Speech 
  - Braille
  - Low Vision
  - Different web browsers

### CODE REVIEW

**Comment by codeofdusk** [comment]
Maybe only disable this for silence rather than only enabling for OneCore?

**Comment by seanbudd** [comment]
> Maybe only disable this for silence rather than only enabling for OneCore?

It's an easy fix for silence, I am concerned about breaking existing custom synthDrivers that could be installed as addons.

**Comment by seanbudd** [comment]
I'm applying this check to oneCore only as it broke the system test synthdriver and I imagine it will break many others.

**Comment by seanbudd** [comment]
Hi @MarcoZehe, @VovaMobile and any others running a Windows copy which has no OneCore voices installed. You can confirm your device has no OneCore voices by doing the following:

1. Go to Windows "Speech" settings
1. Check "Installed Voice packages"

Can you please verify that:

- the latest alpha build of NVDA still replicates this issue, such that there is no speaking by default unless the synthesizer is changed manually to espeak
- [this PR build](https://ci.appveyor.com/api/buildjobs/g3v7ot4gs6s27owc/artifacts/output%2Fnvda_snapshot_pr12646-23351%2Cf7e69a1e.exe) fixes the above issue

**Comment by VovaMobile** [comment]
Hi! Windows OneCoreVoices absent for some languages, such as
Ukrainian. Your tutorial is not correct.

2021-07-15 3:33 GMT+03:00, Sean Budd ***@***.***>:

**Comment by MarcoZehe** [comment]
My case was a bit different I believe. I had German voices installed, but Windows hadn't included English ones. NVDA acted up when it's automatic language switching wanted to switch to English on a website. I am currently not in a position to test this PR, sorry.

**Comment by seanbudd** [comment]
My mistake, in this case it would probably be better to handle this on failure or on handling LangChangeCommand

Closing in favour of a more generic approach in #12647, and a targeted approach when changing languages

**Pull request closed without merging**
