### PR TITLE
Enable cancellable speech by default

### PR DESCRIPTION
**Pull request by feerrenrut**
### Link to issue number:
First introduced with "Cancellable speech #10885"
Several issues fixed with "Fix several issues in speech manager #11245"

### Summary of the issue:
The experimental fix for rapid focus events was included but disabled by default in 2020.2, this PR enables it for broad testing during alpha for 2020.3.

### Description of how this pull request fixes the issue:
Make 'Attempt to cancel speech for expired focus events' enabled by default.

### Known issues with pull request:
- Dialog title discarded when finding text in browse mode: https://github.com/nvaccess/nvda/issues/11144
- Causes system tests to fail, the welcome dialog is not read as expected. This is likely due to #11144.
- NVDA does not report tab titles when switching with ctrl+tab or ctrl+shift+tab
#11397

If this causes problems for users, it can be manually disabled by setting "Attempt to cancel speech for expired focus events" to "No"

### Change log entry:
Changes
```
- 'Attempt to cancel speech for expired focus events' option in the advanced settings panel now enabled by default.
  - This behaviour can be disabled by default with by setting this option to "No".
  - Web applications (E.G. Gmail) no longer speak outdated information when moving focus rapidly. (#10885)
```

### CODE REVIEW

**Comment by codeofdusk** [comment]
Maybe it's worth updating the changelog entry to show the user impact of this change?

**Comment by feerrenrut** [comment]
@codeofdusk I have a suggested change log entry in the description, does it achieve your intent?

**Comment by codeofdusk** [comment]
> @codeofdusk I have a suggested change log entry in the description, does it achieve your intent?

No – maybe refer to the fact that this setting helps address speech issues with rapid focus on the web? Similar to the 2020.2 entry.

**Comment by feerrenrut** [comment]
The 2020.2 entry won't be removed. But I suppose we could add the same sub point.

**Comment by codeofdusk** [comment]
Correct, don't remove 2020.2. Just say something similar for 2020.3. Something like:

* The experimental fix for the speaking of outdated focus information in web applications (e.g. Gmail) when focus is moved rapidly has been enabled by default.

**Comment by lukaszgo1** [comment]
@feerrenrut I believe #11397 should also be added to the known issues of this pr.

**Comment by feerrenrut** [comment]
Merged in #11632 to verify that system test issues are resolved.

**Comment by feerrenrut** [comment]
As system tests now pass, this will be ready for review once #11632 is merged.

**Comment by codeofdusk** [comment]
#11632 has now been merged. Is this PR still blocked?

**Comment by Adriani90** [comment]
I would say it is really important to solve #1172 first before making this default behavior. There are some more detailed system tests needed to discover more characters which cause a freeze.

**Comment by ramchaitanyap** [comment]
Lets say, I change focus by some timeout, NVDA is still not cancelling expired focus speech.

function getFocus() {
document.getElementById("myAnchor").focus();
setTimeout(() => document.getElementById("myAnchor2").focus(), 500);
}

Its still reading #myAnchor text and then #myAnchor2 text

**Comment by feerrenrut** [comment]
@ramchaitanyap Could you please create a new issue for this?

I have created a [codepen ](https://codepen.io/reefturner/pen/oNLVQpo?editors=1010) to demonstrate this a little more clearly, [see the full view](https://codepen.io/reefturner/full/oNLVQpo) and press the 'do focus changes button'.
I reproduced issue with firefox and chrome.

Although it should be noted this is not a regression due to this feature. It would be good to handle this case, I don't think it should prevent the feature from being turned on by default. There are other situations where this feature drastically improves things.

**Comment by feerrenrut** [comment]
@ramchaitanyap created the following related issue: #11840

**Comment by feerrenrut** [comment]
Blocked by:"NVDA freezes with this character"  #11752

**Comment by lukaszgo1** [comment]
This should also be blocked by #11736 . While it is theoretically possible that this is NVDA Remote's problem rather than an NVDA one we should not knowingly break add-ons that way especially not such popular ones as NVDA Remote.

**Comment by feerrenrut** [comment]
@lukaszgo1 Yes, this is unfortunate. Hopefully there is a simple fix we can apply on the NVDA side, otherwise we will defer the Cancellable speech by default change until the 2021.1 release. It should be noted that we don't believe we have broken any public add-on API with the Cancellable speech change, and if we do break the addon-API we expect add-on authors to help us to identify the breakage. Given the open and flexible nature of how NVDA add-ons interact with NVDA, we can only provide a best-effort approach with no strong guarantees. It is frustrating that NVDA Remote is written in a fragile way, relying on implementation details, and then maintenance falls on NV Access. The intention to make this option the default has been public for quite a while, and the option itself has existed for far longer. It seems NVDA Remote could be considered abandon-ware at this stage, it does not see active maintenance. Now would be a good time for someone new to take it on. The 2021.1 release will almost certainly break it.

**Comment by dingpengyu** [comment]
hi @feerrenrut 
Can we change the milestone from 2020.4 to 2021.1?

**Review by michaelDCurran — APPROVED** [review]

**Comment by michaelDCurran** [comment]
It is appropriate to merge this within this release cycle, sooner rather than later, so that add-ons this affects can be updated. E.g. nvdaRemote.

**Comment by codeofdusk** [comment]
I think it might be clearer to have the change log read:

* Web applications (E.G. Gmail) no longer speak outdated information when moving focus rapidly. (#10885)
    * 'Attempt to cancel speech for expired focus events' option in the advanced settings panel now enabled by default.
    * This behaviour can be disabled by setting this option to "No".

Keeps parity with initial cancellable speech change and puts user impact first (as main change log point).

**Pull request merged**
