### PR TITLE
Fix-up of #12432: Fix key error when reading appointment with categories

### PR DESCRIPTION
**Pull request by CyrilleB79**
### Link to issue number:

Fix-up of #12432

### Summary of the issue:

In Outlook Calendar, KeyError in the log when tabbing on an appointment having an associated  category.

In #12432, `.format` was used without key word argument, whereas the string to be formatted contained a named interpolated value.

#### Details
To reproduce / test:
* Open Outlook
* Press control+2 to go to calendar view
* Tab or shift+tab to focus an appointment

Note: using up/down arrows will read the appointment, but does not focus it and will not read the category.

Tested in Outlook 2016 and 365
- with Calendar view 'working week' and day.

If you do not have an appointment with a category, you can add one the following way:
* Open Outlook
* Press control+2 to go to calendar view (working week for me)
* Tab to an appointment
* Press context menu key
* Select "categorize" item
* Select a category in the sub-menu

### Description of how this pull request fixes the issue:

Call `.format` with the keyword.

### Testing strategy:
Tested in Outlook that appointments with no category, one category or wo categories are correctly reported.

### Known issues with pull request:
None

### Change log entries:
None; fixing a not released PR.

### Code Review Checklist:

- [x] Pull Request description is up to date.
- [x] Unit tests.
- [x] System (end to end) tests.
- [x] Manual tests.
- [x] User Documentation.
- [x] Change log entry.
- [x] Context sensitive help for GUI changes.

Cc @feerrenrut  @seanbudd

### CODE REVIEW

**Comment by feerrenrut** [comment]
I can't reproduce this, @CyrilleB79 can you paste the log message?. It looks like I must have misunderstood how to trigger the initial category reporting. I can report categories on an email, but not on a calendar event.

**Comment by CyrilleB79** [comment]
Here is the log:
```
IO - inputCore.InputManager.executeGesture (11:41:41.864) - winInputHook (16236):
Input: kb(desktop):tab
ERROR - eventHandler.executeEvent (11:41:41.974) - MainThread (20248):
error executing event: gainFocus on <appModules.outlook.CalendarView object at 0x12A77970> with extra args of {}
Traceback (most recent call last):
  File "eventHandler.py", line 246, in executeEvent
    _EventExecuter(eventName,obj,kwargs)
  File "eventHandler.py", line 96, in __init__
    self.next()
  File "eventHandler.py", line 105, in next
    return func(*args, **self.kwargs)
  File "NVDAObjects\__init__.py", line 1137, in event_gainFocus
    self.reportFocus()
  File "appModules\outlook.py", line 387, in reportFocus
    categoriesText = self._generateCategoriesText(p)
  File "appModules\outlook.py", line 361, in _generateCategoriesText
    return categoriesText.format(categories)
KeyError: 'categories'
```

Note that reporting categories on message was already supported in NVDA 2020.4. The new feature added in #11598 with the use of `ngettext` was adding category reporting on appointments. You can add a category to an appointment by context menu on the appointment, the same way as you do for messages.
Anyway, that explains why your manual tests in #12432 were OK.

**Comment by feerrenrut** [comment]
The code here is fine, and it is obviously a bug. But given that I didn't manually test this effectively, it would be great to have proper steps on one of these PRs or issues. Currently none do.

I still can't get reproduce the error. I'm using Office 365.
- Press `ctrl+tab` until the "navigation bar grouping" is announced
- Use left / right arrows to find the calendar view button and press enter
- Down arrow until I find an appointment (which I know has a category applied)
- Press `NVDA+tab`
Speech from speech viewer:
```
1:30 PM to 2:00 PM
Has appointment 2:00 PM to 2:30 PM
, , 2:00pm to 2:30pm Thursday, 20 May 2021, 1 event, 1 Busy  cell  Calendar Day View  focused  selected  Calendar Day View
```

**Review by feerrenrut — APPROVED** [review]
I'm going to go ahead with this merge, we can update the description once we understand what we are doing differently.

**Comment by CyrilleB79** [comment]
@feerrenrut here are the requested clarifications.

Here is the STR that lead to the error that I have pasted above:
* Open Outlook
* Press control+2 to go to calendar view
* Tab or shift+tab to an appointment in the current week that has an associated category (or more than one)
I am using Outlook 2016 and the calendar view is 'working week'.

If you do not have an appointment with a category, you can add one the following way:
* Open Outlook
* Press control+2 to go to calendar view (working week for me)
* Tab to an appointment
* Press context menu key
* Select "categorize" item
* Select a category in the sub-menu

Note that with the STR you indicate, I can see 2 differences:
* control+tab does not get me to the navigation bar group; i have to press shift+F6. Would it be a difference between 2016 and 365?
* more important, if I use arrow keys in calendar instead of tab/shift+tab, the appointments are reported but not selected and the corresponding category is not reported, neither before this PR, nor after.

I hope that this clarifies things. Let me know if something is still unclear.

**Comment by feerrenrut** [comment]
Yes, that helps. I had to tab to the appointment, then reading categories works as expected.

**Comment by feerrenrut** [comment]
I have added this to the PR description.

**Comment by feerrenrut** [comment]
@CyrilleB79 This usage will be removed for now, we believe it is causing trouble for the po file checker in the translation system. We can revisit this after the release of 2021.1

**Comment by zstanecic** [comment]
I am sorry, but this string will now sound very unnatural in polish and other slavic languages. Maybe i  am going to receive complaints.

**Comment by feerrenrut** [comment]
I understand, this is not idea. This matches the behavior of the of many similar plural strings in NVDA. We will look at re-introducing this for the next release.

**Pull request merged**
