### PR TITLE
Use Python launcher if present

### PR DESCRIPTION
**Pull request by francipvb**
I was having some problems because I have two Python interpreters installed.

Sometimes various interpreters registered to run python scripts can cause problems when running in Windows 10, mainly if you have Python3 installed alongside with python2.

This is a quick workaround to fix this thing.

I've tested it and it works well.

Cheers,

### CODE REVIEW

**Comment by josephsl** [comment]
Hi, somewhat of an important blocker for #7105. Thanks.

**Comment by francipvb** [comment]
Hello,

I know, but I think that this is a trivial change to do later when migration happens.

Cheers,

**Review by josephsl — APPROVED** [review]

**Comment by josephsl** [comment]
Hi,

@MichaelDCurran, any comments? I think this could be useful for our eventual Python 3 transition (#7105). Thanks.

**Comment by michaelDCurran** [comment]
On my Windows 10 machine build 16291  scons.bat always tries to call 'py' which on my system does not exist.  It is as if where py succeeds with an errorlevel of 0. However, manually running it and echoing errorlevel its 1, not 0. Is the syntax of the if check correct?

**Comment by francipvb** [comment]
Hello,

I've fixed it. `errorlevel` appears to be not working as expected.

Cheers,

**Comment by michaelDCurran** [comment]
This is better. Can we also redirect stderr to nul as well? As if where does not locate the executable, an annoying info message is shown. Thanks

**Review by michaelDCurran — APPROVED** [review]

**Pull request merged**
