### PR TITLE
Ensure that when character normalization results in a character with symbol definition, the symbol replacement is spoken

### PR DESCRIPTION
**Pull request by LeonarddeR**
### Link to issue number:
Fixup for #16622 

### Summary of the issue:
When unicode normalization of a character (e.g. `·`) resulted into a character that had a symbol definition (e.g. `·`, middle dot), the symbol definition wasn't applied to the normalization. This resulted in NVDA speaking nothing or only the word `normalized`.

### Description of user facing changes
NVDA will now properly speak the `·` character (Greek Ano Teleia) as `middle dot` when normalizing. This also applies to other characters where normalization results in a character that's part of the symbol dictionary.

### Description of development approach
When normalizing a character, ensure it is thrown through `characterProcessing.processSpeechSymbol`.

### Testing strategy:
- Tested speaking of the Greek Ano Teleia as middle dot normalized when navigating across it with left/right arrow and normalization was on.
- Validated unit tests

### Known issues with pull request:
None known

### Code Review Checklist:

- [x] Documentation:
  - Change log entry
  - User Documentation
  - Developer / Technical Documentation
  - Context sensitive help for GUI changes
- [x] Testing:
  - Unit tests
  - System (end to end) tests
  - Manual testing
- [x] UX of all users considered:
  - Speech
  - Braille
  - Low Vision
  - Different web browsers
  - Localization in other languages / culture than English
- [x] API is compatible with existing add-ons.
- [x] Security precautions taken.

## Summary by CodeRabbit

- **Style**
	- Enhanced code readability with consistent spacing and improved formatting in method definitions.
	- Standardized use of double quotes for string literals across multiple files.
	- Consolidated multi-line conditions and method calls into single lines for clarity.
- **Bug Fixes**
	- Improved processing logic for character handling in speech functions, resulting in more accurate speech output.
- **Tests**
	- Added new test cases for the `_getSpellingSpeechWithoutCharMode` function to validate the normalization feature under various conditions.

### CODE REVIEW

**Comment by LeonarddeR** [comment]
@seanbudd it looks like @pre-commit-ci is pretty agressive here. I don't know how to tackle that really.

**Comment by seanbudd** [comment]
I've had to suspend pre-commit. Hopefully this won't be a problem for long if we avoid PRs to beta.

**Review by seanbudd — APPROVED** [review]
Thanks @LeonarddeR

**Comment by seanbudd** [comment]
@coderabbitai resolve

**Comment by seanbudd** [comment]
@coderabbitai full review

**Pull request merged**
