### PR TITLE
Ensure that clipboard manager does not steal focus when starting  MS Office programs

### PR DESCRIPTION
**Pull request by lukaszgo1**
### Link to issue number:
None, related to #4199, Originally reported on one of the Polish mailing  lists (I cannot link to the conversation archives cannot be accessed for non subscribers)

### Summary of the issue:
As described in #4199 when starting Office programs Word, Excel clipboard manager can sometimes steal accessibility focus making it impossible to interact with the document / spreadsheet.
Most cases were fixed but it seems one has been missed - focus lands on something called Collect  and Paste 2.0 ,making interaction with the actual document difficult.

### Description of how this pull request fixes the issue:
Since the "Collect and paste" has a custom eventObjectID `SDM~has not been applied to it causing focus to be incorrect. This custom ID has been added to the list of objects for which `SDM~applies.
### Testing strategy:
Started Excel from the run box - made sure that focus lands on the actual spreadsheet whereas previously it didn't.

### Known issues with pull request:
None known
### Change log entries:
Bug fixes
 - Clipboard manager pane should no longer incorrectly steal focus when opening some Office programs

### Code Review Checklist:

- [X] Pull Request description is up to date.
- [X] Unit tests.
- [X] System (end to end) tests.
- [X] Manual testing.
- [X] User Documentation.
- [X] Change log entry.
- [X] Context sensitive help for GUI changes.
- [X] UX of all users considered:
  - Speech 
  - Braille
  - Low Vision
  - Different web browsers

### CODE REVIEW

**Comment by lukaszgo1** [comment]
cc @michaelDCurran

**Comment by lukaszgo1** [comment]
@michaelDCurran  Have you seen this? The person who reported this problem to me asked if it would be possible to get this bug fix into 2021.3 that's why I've decided to ping you again.

**Comment by lukaszgo1** [comment]
@michaelDCurran  Given the small size of this PR it would be a real pity not to get it into 2021.3. Is there anything which can be done on the reviewer side (aside from pinging you from time to time and hoping you would look at the code) to avoid small fixes like this being stuck for several months?

**Comment by lukaszgo1** [comment]
It is reproducible for both the user who reported this to me and on my machine  (in my case on Win 7) in theirs on Win 10 20H2. I'm not sure what is different perhaps version of Office or specific things set in Excel's settings. At any rate even if this would be reproducible only for original reporter assuming this fix has no adverse side effects there is no reason not to merge it IMO.

**Comment by josephsl** [comment]
Hi, at least asking around could help us point out other possible reasons for this PR – at least that’s the ideal situation, but I do understand that delay in review and merge reduces productivity. I’m not looking at overengineering it – I just simply want to see data that says this problem has potential to affect more people if not mitigated, which was justified in the overall PR discussion. Hope this clarifies things.

**Review by michaelDCurran — APPROVED** [review]

**Pull request merged**
