### PR TITLE
Added Lithuanian Braille table to the list of available tables

### PR DESCRIPTION
**Pull request by rimas-kudelis**
Lithuanian table was recently overhauled in https://github.com/liblouis/liblouis/pull/218 .

### CODE REVIEW

**Comment by josephsl** [comment]
Hi, is this included in Liblouis 3? If so, @jcsteh should know about this at this point. Thanks.

**Comment by rimas-kudelis** [comment]
> Hi, is this included in Liblouis 3? If so, @jcsteh should know about this at this point. Thanks.

No, this is planned for 3.1. But nevertheless, the file in question exists in older releases as well, except it's not as complete as my overhauled version.

**Comment by josephsl** [comment]
Hi, in this case, let’s push it back to 2017.1. Thanks.

**Comment by jcsteh** [comment]
liblouis 3.1 has not yet been released, so the new table can't yet be included. @rimas-kudelis, do you still want this for 2017.1 even if it's only the liblouis 3.0 table?

**Review by jcsteh — APPROVED** [review]
Change looks fine, but whether we want it for 2017.1 is still an open question; see https://github.com/nvaccess/nvda/pull/6550#issuecomment-271190393.

**Comment by rimas-kudelis** [comment]
@jcsteh That current table is incomplete. On the other hand, my impression is that there are very few Braille users in Lithuania in general.
I'll check with Paulius and let you know how we want to proceed.

**Comment by rimas-kudelis** [comment]
Okay, let's wait until after liblouis 3.1 is released.

**Comment by josephsl** [comment]
Hi,

Update: Liblouis 3.1.0 includes this (I think), so I'd say let's do this as part of 3.1.0 upgrade. Thanks.

**Comment by josephsl** [comment]
Reference: #6935

**Comment by rimas-kudelis** [comment]
Yes please!

**Comment by jcsteh** [comment]
Superseded by #7364.

**Pull request closed without merging**
