### PR TITLE
Add ability to check for, download, and apply add-on updates

### PR DESCRIPTION
**Pull request by josephsl**
Hi,

Added (July 2018): reformatted to use PR template.

### Link to issue number:
#3208

### Summary of the issue:
The client portion of add-on update facility

### Description of how this pull request fixes the issue:
Add abilitty to check for, download, and apply add-on updates from NVDA itself.

Note that this is a prototype client implementation. This does not support automatic updates nor actual download as the server portion and data exchange format isn't available yet. 

Automatic add-on update checks require careful design, as NVDA Core update should be given priority when it comes to checking for updates (that is, if NVDA Core is being updated or an update is available, add-on updates should not take place).

### Testing performed:
Checked for, downloaded, and applied various add-on updates from community add-ons website (through use of fake JSON dictionaary+PHP file provided by the add-ons website).

### Known issues with pull request:
This is a prototype implementation and will be ready to go once the server, database, and exchange format are published. Also, this PR will rely on changes made in #7491 (checkable list box), as well as looking at minimum NVDA version (#6275).

### Change log entry:
New feature: NVDA can now check, download, and apply add-on updates. (#3208)
Changes for developers: Add-ons can specify update channel in their manifest, used to look up add-on update channel.

Thanks.

### CODE REVIEW

**Comment by josephsl** [comment]
@DerekRiemer, may I request additional reviews such as catching unforseen errors, design versus implementation and so on? Thanks.

**Comment by josephsl** [comment]
Hi,

Somehow, when checking for updates, Add-ons Manager must be hidden, otherwise update status dialog will not be shown properly. Also, after downloading multiple updates, add-ons manager window will not receive focus afterwards (perhaps due to GUI programming), as well as the progress dialogs not closing if at least one add-on has an installation UI that users must deal with. Apart from that and the automatic check issue outlined above, the client side is done.

At the moment the highest priority is to fix add-on update experience when updating multiple add-ons, then deal with window focus problem.

Thanks.

**Comment by josephsl** [comment]
Hi,

In regards to serialization issue discussed in the original ticket, one possible workaround might be use of events (where the download initiator will wait until the previous add-on installs or fails to install). I spent all day today trying to come up with a suitable fix for that, but getting tired.

Thanks.

**Comment by josephsl** [comment]
I'll reopen this once GUI and synchronization issues are fixed. Thanks.

**Comment by josephsl** [comment]
Hi,

Major technical hurdle fixed: thanks to @JCSTeh and @LeonardDer for generator suggestion (it works). I'm reopening this PR to gather additional comments.

At this point, the issues to be resolved has to do with automatic add-on updates when NVDA starts, as well as making sure users don't update add-ons when NVDA is waiting for add-ons to be installed. Thanks.

**Comment by josephsl** [comment]
Hi,

Client portion is done and is ready for code review. Once the data exchange format is finalized, I'll make necessary changes in add-on handler module. Thanks.

**Comment by leonardder** [comment]
@josephsl: Is this still up to date? If so, may be you could ask a current NV Access team member to review this?
I suppose your code is quite stable given my positive experiences with your add-ons.

**Comment by feerrenrut** [comment]
I'm happy to review this, though since I'm not familiar with the history behind this, would you be able to update the description. Please assign this to me to review when it is ready to go. Sorry this has been pending so long!

**Comment by jcsteh** [comment]
While a precursory review might be useful, I tend to feel this isn't something that can really be signed off until the server infrastructure is integrated with the official add-ons repository. There's a small chance that the server implementation might need to be changed based on review of the client, but the likelihood of (and the extent of the changes in) that case is much lower than server design decisions influencing the client.

**Comment by josephsl** [comment]
Hi,

I'll need to merge in 2018.1 code first. I'm happy for this to be reviewed from theoretical angle for now, but as @JCSTeh pointed out, we need to gather info on client/server exchanges, server-side changes and what not before it is ready for testers.

Thanks.

**Comment by feerrenrut** [comment]
michaelDCurran and I need to go over the history of this and work out what needs to be done in order to progress this PR, specifically around the server implementation.

**Comment by josephsl** [comment]
Hi,

Blocked by #7104 - once unblocked, I'll rebase this work on master (including letting it be built on Appveyor).

Thanks.

**Comment by josephsl** [comment]
Hi,

There are some small things here and there, but apart from these (such as inability to open add-ons manager while NVDA is running from source), the client is ready. As noted earlier, it isn't really ready for review until server infrastructure and data exchange format is in place.

Also, to support possibility of add-on update channel variability, I'll let add-on authors (including myself) specify update channels if any (default is stable builds).

Thanks.

**Comment by Adriani90** [comment]
As also stated in #3208, @yplassiard and @josephsl can Combine their work accordingly, the infrastructure is already in place. It just Needs to be adapted to work properly with Github and the addon Website. @feerrenrut could NV Access provide Server space and support to implement a sustainable solution?

Thank you all for your very important work.

**Comment by leonardder** [comment]
Have you considered that checking for and downloading add-on updates implies that information about installed add-ons is shared, and that this can be considered as gathering usage statistics? I think this should be properly documented if not already done.

**Comment by josephsl** [comment]
Hi, ah yes, I once thought about that. I’ll document that as part of user guide edits after merging latest master commits. Thanks.

**Comment by leonardder** [comment]
[**@josephsl**](https://github.com/josephsl) commented on [24 Nov 2018, 07:21 CET](https://github.com/nvaccess/nvda/pull/6930#issuecomment-441346893 "2018-11-24T06:21:45Z - Replied by Github Reply Comments"):
> One particular concern is a huge conflict due to file moves: when I tried to merge in i6275 branch into a custom branch based on 3208 work, one of the conflicts had to deal with entire file contents.

This is caused by addonHandler/__init__.py being converted to crlf line endings. If you convrt addonhandler.py to crlf with notepad++, you might have less issues to merge this.

**Comment by josephsl** [comment]
Hi,

Yes, experiments show that changing line endings helps a lot. I'll do that for add-on handler (current version) before merging master into my branch once #8006 is approved.

Thanks.

**Comment by josephsl** [comment]
Hi,

Update on this PR: I will wait until #7105 comes to master due to massive differences between Python 2 and 3.

Thanks.

**Comment by feerrenrut** [comment]
We will leave this PR open, hopefully it can be adapted to work with the [Addon store proposal ](https://github.com/nvaccess/addon-store-submission/blob/master/README.md#add-on-store-proposal) when that is implemented in the near future. 

Before we review this, it would be good to know more (updated description) about the cases this PR specifically handles.

**Comment by josephsl** [comment]
Hi,

Ah yes...

The mechanism in this PR is similar to Add-on Updater add-on except that this PR does not specify where to obtain the add-on update metadata. This is intentional, as it stems from a long discussion in #3208 regarding server-side mechanics of this PR.

Specifically, this PR introduces a new button in Add-ons Manager to check for updates, along with a way to configure update channels and such (at least the foundation is there).

If the add-ons store proposal is adopted, I recommend not merging this PR directly at first - I think it would be best to integrate the work done on this PR into the larger Store proposal work, which by then can piece together the missing puzzle pieces in this PR.

Thanks.

**Comment by josephsl** [comment]
Hi,

As for the cases it covers:

* Downloading an update from a URL specified.
* Possibility to update add-ons automatically at startup after NVDA Core checks for its own updates.
* Enabling/disabling add-on update checks globally or on per add-on basis (the latter done through a button in Add-ons Manager).

Let me know if you need more clarifications.

Add-on Updater repo:
https://github.com/josephsl/addonupdater

**Comment by dingpengyu** [comment]
> Given this is blocked and really depends on the server-side before it can be finished, I've converted it to a draft.
hello
Is it possible to use github actions + cloud storage with sftp upload to distribute NVDA? The add-ons?
github actions is mainly used to compile and upload the compiled plugin to the cloud storage.
The last part is a bulk download link back to the plugin updater for users to download.
thanks

**Comment by josephsl** [comment]
Hi,

As a gift to NV Access and NVDA community, I would like to donate this entire branch for further refinements in preparation for a future add-ons store implementation (and until add-ons store opens, I'll maintain Add-on Updater add-on, which provided basis for this branch).

Thanks.

**Comment by feerrenrut** [comment]
If I'm interpreting you right @josephsl, you are saying that you won't continue to work on this? In that case I'm going to close it. Given we have our own plans at NV Access to fill this need it might be simpler if we take it on anyway.

**Comment by josephsl** [comment]
Hi, it’s all yours. Thanks for all the advice for many years.

**Pull request closed without merging**
