### PR TITLE
Update configobj to 5.1.0dev commit f9a265c4

### LINKED ISSUE #10939: Update configobj to 5.1.0dev commit f9a265c4
Hi,

For future Python compatibility:

### Background:
As part of #4470, configobj was updated to a 5.1.0dev commit. Since Python 3 transition preparation was in the works then, there has not been any test done to make sure configobj is ready for newer Python 3 releases. In 2020, things have changed, with NVDA running on Python 3.7 and configobj has been updated to provide better support for Python 3.7 and resolving errors.

### Is your feature request related to a problem? Please describe.
Config imports collections.abc.Mapping class. In Python 2, it was okay to import collections.Mapping directly, which is no longer the case in Python 3.3 and later. IN fact, Python 3.9 will prevent direct import of abstract base collection classes, affecting configobj.

Along with this change, current version of configobj (shipping iwth NVDA 2020.1) does not support Python 3.7 properly - assumes Python 3.4 is the latest version compatible.

### Describe the solution you'd like
Update configobj to 5.1.0dev commit f9a265c4 (December 8, 2019). This includes:

* Improved support for Python 3.7.
* Mapping class will be imported from collections.abc if running on Python 3.4 or later.
* Path-like object is supported when specifying confspec and opening config files.

### Describe alternatives you've considered
Leave configobj as is.

### Additional context
Not only this change would make configobj compliant with Python 3.7, it would also make it easier for NVDA to update to newer Python releases with a dependency that has been proven to work with newer Python releases.

Note that since configobj is a crucial dependency, extensive regression testing must be performed, including reading and writing NVDA and add-on settings across versions with and without the new configobj commits.

Thanks.

### PR DESCRIPTION
**Pull request by josephsl**
### Link to issue number:
Fixes #10939 

### Summary of the issue:
Current version of configobj used by NVDA produces errors when run from source copy of NVDA with Python warnings set to "error".

### Description of how this pull request fixes the issue:
Recent configobj commits include:

* Official support for python 3.7
\* Resolve warnings with collections.abc imports

### Testing performed:
Tested with:

1. Loading and saving NvDA settings with or without new commits applied.
2. Migrating settings files between commits - master to the PR, PR to master.

### Known issues with pull request:
None so far

### Change log entry:
Changes for developers:

Updated configobj to 5.1.0dev commit f9a265c4. (#10939)

### CODE REVIEW

**Comment by feerrenrut** [comment]
@josephsl Could you also test the upgrade paths with this change:
1. Create a config file from pre config update using an old build of NVDA using a few features that have later config update steps.
1. Run this with you branch and inspect the config folder / log.

**Review by lukaszgo1 — COMMENTED** [review]
Commit of ConfigObj in the readme should also be updated.

**Comment by josephsl** [comment]
Hi, I’ll test this step with NVDA 2018.3, 2019.2.1, and 2019.3.1 (I have installers for these and can create portable copies of them, then “upgrade” them with a launcher I can generate from source).

**Comment by josephsl** [comment]
Hi, I’ll do so once I perform config upgrade tests (thanks for reminding me).

**Comment by josephsl** [comment]
Hi,

Config schema upgrade tests were successful:

* 2018.3: yes
* 2019.2: yes
* 2019.3: yes

Thanks.

**Review by feerrenrut — APPROVED** [review]
Thanks @josephsl

**Pull request merged**
