### PR TITLE
IA2: Do not treat huge base64 data as NVDA might freeze in Google Chrome (#10227) - Py2 backport to beta

### PR DESCRIPTION
**Pull request by JulienCochuyt**
### Link to issue number:

Issue #10227
Backport of #10231 into beta

### Summary of the issue:

Huge base64 embedded in the `src` attribute of a focusable `img` element can freeze Google Chrome.

### Description of how this pull request fixes the issue:

When the IA2 attribute string exceeds a threshold of 4096 characters, truncate the base64 from the text passed to `IAccessibleHandler.splitIA2Attribs` before treating it.

### Known issues with pull request:

The huge base64 is still uselessly present in the Virtual Buffer data.
The NVDAHelper thus would probably benefit from an impact on that regard.

### Change log entry:

Section: Bug fixes

NVDA no longer crashes in Google Chrome when an image contains huge base64 data.

### CODE REVIEW

**Comment by JulienCochuyt** [comment]
cc @michaelDCurran

**Comment by michaelDCurran** [comment]
As I feel the other pr is not yet complete, and there is no public real-life testcase to point to, and we really want to get 2019.2.1 out soon, I think I need to refuse this pr sorry.

**Comment by JulienCochuyt** [comment]
@michaelDCurran I understand the schedule for 2019.2.1 is a matter of importance.
Please excuse my insistance: This release is expected to live quite long.
A user facing this freeze and holding on threshold would need to downgrade as far as 2017.4.
I have just attached an HTML example of the issue in #10249 
Here it is for convenience: [i10227.html.txt](https://github.com/nvaccess/nvda/files/3645959/i10227.html.txt)
(Please remove the `.txt` extension to open this `.html` file.)

I agree the proposed fix is not fully satisfactory as it misses the Gecko vbufBackend impact you mentioned in https://github.com/nvaccess/nvda/pull/10231#issuecomment-534328150
Nevertheless, it still at least allows a regular end user not to get frozen.
Please reconsider your decision.

I'll try to work asap on the Gecko vbufBackend side, but I have other obligations towards my customers. Thus, this complementary part of the fix won't for sure be ready for 2019.2.1
Thus, I renew my request to include this workaround

**Comment by michaelDCurran** [comment]
thank you for the testcase, that helps a great deal. I will take a look at it tomorrow, then I can better feel the actual impact.

**Comment by JulienCochuyt** [comment]
Thank you for your time and consideration.

**Review by michaelDCurran — APPROVED** [review]

**Pull request merged**
