### PR TITLE
Revert "refactor the exit of nvda and gui.terminate"

### PR DESCRIPTION
**Pull request by seanbudd**
Reverts nvaccess/nvda#12286

### CODE REVIEW

**Review by michaelDCurran — APPROVED** [review]

**Comment by Brian1Gaff** [comment]
You are aware that the current alpha as of yesterday is seriously broken, 
and will not run sensibly on anything I suppose?
 Brian

***@***.***
Sent via blueyonder.
Please address personal E-mail to:-
***@***.***, putting 'Brian Gaff'
in the display name field.
Newsgroup monitored: alt.comp.blind-users
----- Original Message -----

**Comment by seanbudd** [comment]
> You are aware that the current alpha as of yesterday is seriously broken, and will not run sensibly on anything I suppose? Brian ***@***.*** Sent via blueyonder. Please address personal E-mail to:- ***@***.***, putting 'Brian Gaff' in the display name field. Newsgroup monitored: alt.comp.blind-users ----- Original Message ----- From: "Michael Curran" ***@***.***> To: "nvaccess/nvda" ***@***.***> Cc: "Subscribed" ***@***.***> Sent: Friday, April 23, 2021 4:56 AM Subject: Re: [nvaccess/nvda] Revert "refactor the exit of nvda and gui.terminate" (#12326)
> […](#)
> Merged #12326 into master. -- You are receiving this because you are subscribed to this thread. Reply to this email directly or view it on GitHub: [#12326 (comment)](https://github.com/nvaccess/nvda/pull/12326#event-4634618226)

Just to confirm, you are referring to the latest alpha `alpha-22498,d9afe35d`, which includes this PR that has reverted the broken change?

**Comment by CyrilleB79** [comment]
@seanbudd, @michaelDCurran:
Since #12286 was reverted through this PR, shouldn't #12238 be reopened?

**Comment by seanbudd** [comment]
Yes, thanks @CyrilleB79

**Pull request merged**
