### PR TITLE
Python 3 imports: try importing Python 3 version before resorting to using Python 2 names

### LINKED ISSUE #8527: Python 3: unify and standardize imports around Python 3 version before resorting to Python 2 implementation
Hi,

The overall picture is powered by #7105:

### Background:
For a number of years, NV Access and the community have been thinking about moving NVDA's source code to Python 3. The prerequisite for this work has been preparation of Python 3 versions of various dependencies, the biggest ones being wxPython, SCons, py2exe, ConfigObj and many others.

In July 2018, NVDA was switched to use wxPython 4.0.3, a milestone in Python 3 transition planning. This lays the theoretical foundation to transitoin to Python 3, specifically Python 3.7. As noted in issue #7105, NVDA 2018.3 is considered "version N", with research and porting to take place in the very near future (ideally throughout 2019).

### Specific issue at hand:
At the moment NVDA imports Python 2 versions of various modules. However, in Python 3, some of them are renamed. The most notable case being "_winreg", which has been renamed to "winreg" (without the underscore). Some fragments use aliased import (of the form "import _winreg as winreg"), while others import this module directly. There are other renamed modules, but winreg is the most notable one.

Thus it is proposed to do two things:

1. Unify the import statements.
2. Try importing Python 3 name first, and if it fials, resort to Python 2.

Applying this to `_winreg`:

Old:
```
import _winreg
```

New:
```
try:
  import winregexcept ImportError:
  import _winreg as winreg
```

Which then allows winreg functions and attributes to be accessed via Python 3 name.

Note that for the rest of the template, because this issue concerns future work, most fields are not applicable.

### Steps to reproduce:
Import various modules that have both Python 2 and 3 implementations, or are renamed in Python 3.

#### Name and version of other software in use when reproducing the issue:
Python 2.7.15, Python 3.7.0

### LINKED ISSUE #8590: Python 3 foundation: syntax compatibility for extensionPoints.util and others
Hi,

Most of the template below does not apply, although some minor points do.

This issue is based on #7105 and serves as a venue for discussing concrete implementations. For this one, syntax compatibility should be discussed.

## Description:
When loading a file that is part of a package, Python 2.7 would happily accept the import statement of the form:

from foo import spam, eggs, ...

But Python3 prefers:

from .foo import spam, eggs, ...

Possibly because of prevalence of absolute imports. So far, this was observed with extensionPoints.util, but I'm sure this kind of syntax compatibility problem exists in other modules.

### Steps to reproduce:
On Python 2.7 and 3.7, do:

1. Create a package with several files and an __init__.py file.
2. In __init__ module, try writing and running the following statement via Python 2.7 and 3.7:

from fileInPackage import something

### Actual behavior:
Python 3 throws import error.

### Expected behavior:
Both Python 2 and 3 imports specified modules.

#### NVDA Installed/portable/running from source:
Not applicable, as this is Python 3 transition/research/foundation discussion.

#### NVDA version:
Not applicable

#### Windows version:
Windows 10 Version 1803

#### Name and version of other software in use when reproducing the issue:
Python 2.7.15, 3.7.0

#### Other information about your system:
None

#### Does the issue still occur after restarting your PC?
N/A

#### Have you tried any other versions of NVDA?
N/A

## Possible solution:
I propose standardizing on absolute import statement (Python 3 version) provided that it works in Python 2 as well.

Thanks.

### LINKED ISSUE #8649: App modules/aliases/Python 3: use relative import statement
Hi,

Another potential issue with Python 3 transition: app module aliases may raise import issues.

### Steps to reproduce:
1. Create a package of Python files (a folder) with several Python files inside.
2. From one or more files inside this package, do "from anotherMod import something".

### Actual behavior:
Python's import machinery gets confused regarding where the package lives.

### Expected behavior:
Python should be able to load the correct package/file.

#### NVDA Installed/portable/running from source:
Not applicable

#### NVDA version:
Not applicable

#### Windows version:
Windows 10 Version 1803

#### Name and version of other software in use when reproducing the issue:
Python 2.7, 3.7

#### Other information about your system:
N/A

#### Does the issue still occur after restarting your PC?
Yes

#### Have you tried any other versions of NVDA?
N/A

### Impact:
The import machinery issue is most prominent in app modules where several modules are aliases of one another (win32calc.py as an alias of calc.py, for instance). There are other modules where this issue arises, including extensionPoints and synthDrivers.espeak.

### Solution:
As part of the pull request on Python 3 imports, a straightforward relative import will be used. This means changing "from someAlias import *" to "from .someAlias import *" in app modules and other modules where this problem occurs.

Thanks.

### PR DESCRIPTION
**Pull request by josephsl**
Hi,

Part of preparation for Python 3 transition:

### Link to issue number:
Fixes #8527
Fixes #8590
Fixes #8649

### Summary of the issue:
Use Python 3 module names before resorting to using python 2 names.

### Description of how this pull request fixes the issue:
Python 3 has renamed several modules. These include _winreg to winreg and Queue to queue. At the moment some NVDA modules import affected modules directly or load one or two things from these. Thus a try/except block has been added to load Python 3 version first before resorting to Python 2 names, and for some, edited various code fragments to use Python 3 names.

### Testing performed:
Compiled and ran NVDA from source, along with running Python 2.7 and 3.7 interpreters to make sure names are correct.

### Known issues with pull request:
None

### Change log entry:
None

Thanks.

### CODE REVIEW

**Comment by leonardder** [comment]
[**@josephsl**](https://github.com/josephsl) commented on [8 aug. 2018 04:00 CEST](https://github.com/nvaccess/nvda/pull/8606#issue-206872698 "2018-08-08T02:00:33Z - Replied by Github Reply Comments"):
> ### Testing performed:
> Compiled and ran NVDA from source, along with running Python 2.7 and 3.7 interpreters to make sure names are correct.

Could you elaborate on how you've tested that this pr is actually complete with regard to module changes? I.e. what is the expected result when you run your pr code with the python 3.7 interpreter?

**Comment by josephsl** [comment]
Hi,

It did load the modules correctly when I attempted to run NVDA under Python 3.7. I also ran interpreters and attempted to load Python 3 modules.

The other issue is abolute versus relative imports 9extension points, for example), which I'll address in another issue/pull request pair (I'm still looking for these imports at the moment).

Thanks.

**Comment by josephsl** [comment]
Hi,

Regarding relative versus absolute imports, I'll address this in this pull request as well.

Thanks.

**Comment by feerrenrut** [comment]
for the blocks that try importing and catch the import error exception, could you please add comments to explain why this is happening. In the context of this PR it's obvious, but without perhaps not. I would suggest something along the lines of:
```
# module as named in python 2.7
# module name in python 3.7
```

**Comment by josephsl** [comment]
Hi, ah yes, thanks for catching that – will be documented tonight before I go to sleep, along with dealing with another renamed module (thread -> _thread) in BDDetect. Thanks.

**Comment by josephsl** [comment]
Hi,

@feerrenrut, done as suggested.

For others: the keyword to look for will be "python 3 import". Alternatively, when using grep, use "Python 2\.+" (2.x, 2.7, etc.).

Thanks.

**Review by feerrenrut — APPROVED** [review]

**Pull request merged**
