### PR TITLE
Revert "Add appModule for Visual Studio Code Insiders"

### LINKED ISSUE #10888: VS Code: Reduce the number of times one has to use NVDA+Space to switch modes.
I just filed [this issue](https://github.com/microsoft/vscode/issues/93087) against VS Code where I suggest to use targeted role="document" in those places that produce HTML output for consumption, to make NVDA switch in and out of browse mode in a smart, automated, manner, reducing the number of times one has to use NVDA+Space to toggle modes. Examples I found while using the 1.44 VS Code Insider builds were:

* The Welcome page
* The details page for an extension
* The ReadMe file that may be displayed after an extension has been installed.

@leonardder suggested that, once this lands in stable, a modification might be needed for the VS Code app module. So filing this issue here.

### PR DESCRIPTION
**Pull request by MarcoZehe**
Reverts nvaccess/nvda#10858. Fixes #10888 for VS Code insider builds now that microsoft/vscode#93087 is fixed.

### CODE REVIEW

**Comment by josephsl** [comment]
Hi, I think it might be advisable to keep the Insider version around just in case we need to resolve future accessibility issues/mitigate issues that would show up in future Insider releases. Thanks.

**Comment by leonardder** [comment]
To clarify

This appModule was created to avoid enabling browse mode by default in VS Code Insiders. Effort has been put in improving the overall experience of vs code, in particular the alerts are now part of the application container.


> Hi, I think it might be advisable to keep the Insider version around just in case we need to resolve future accessibility issues/mitigate issues that would show up in future Insider releases.

The only thing that this appModule does is disabling browse mode by default. Note that we can also do this on configuration profile level. Therefore, I second this pull request.

**Review by LeonarddeR — APPROVED** [review]
Could you please change the target branch to beta. I think that it makes sense to revert this from beta so this won't be in 2020.1 and will be out in 2020.2 again.

There's also a whats new entry that has to be removed, though I leave it up to @michaelDCurran to decide whether that has to be done in this pr or in a subsequent manual commit.

**Comment by MarcoZehe** [comment]
> Could you please change the target branch to beta. I think that it makes sense to revert this from beta so this won't be in 2020.1 and will be out in 2020.2 again.

I don't seem to have the power to retarget this. It doesn't give me that option anywhere. Note that I don't have any extended permissions, so this must probably be done by someone with write access.

**Review by michaelDCurran — APPROVED** [review]

**Pull request merged**
