### PR TITLE
Use FullDescription for UIA

### PR DESCRIPTION
**Pull request by LeonarddeR**
### Link to issue number:
Reported in https://github.com/nvaccess/nvda/issues/8604#issuecomment-508486905

### Summary of the issue:
When getting the description of an element, we are currently ignoring the UIA full description property. Instead, we're using UIA Help Text, which causes some issues, see https://github.com/nvaccess/nvda/issues/9585, https://github.com/nvaccess/nvda/issues/8987

According to the UIA helptext docs:

> Identifies the HelpText property, which is a help text string associated with the automation element.
> The HelpText property can be supported with placeholder text appearing in edit or list controls. For example, "Type text here for search" is a good candidate the HelpText property for an edit control that places the text prior to the user's actual input. However, it is not adequate for the name property of the edit control.
> When HelpText is supported, the string must match the application UI language or the operating system default UI language.

### Description of how this pull request fixes the issue:
This pull request fetches UIA Full Description and uses it as the description of an object. If UIAFullDescription is empty, we fall back to HelpText.

### Testing performed:
Tested that descriptions are still read in cases where HelpText is used.

### Known issues with pull request:
I would like to introduce a suggestion, namely to stop providing UIA HelpText as part of the description property. Instead of that, we should introduce a generic helpText property on objects that is reported when reporting of help text is enabled. Reporting helptext should be enabled by default.

### Change log entry:
* Bug fixes
    + In applications using QT 5.11 or newer, object descriptions are again reported. (#8604)

### CODE REVIEW

**Comment by josephsl** [comment]
To some degree, affects #2699 implementation.

**Comment by michaelDCurran** [comment]
Have you done testing in places such as MS Edge, with aria-describedby etc? Does fullDescription sometimes duplicate text that was in the name? How about on MS Office Ribbons. Does it behave itself? In principle I agree with this pr. 
Also for completeness, here is what the description for fullDescription says in Microsoft's documentation:
```
The FullDescription property exposes a localized string which can contain extended description text for an element. FullDescription can contain a more complete description of an element than may be appropriate for the element Name.
```

**Comment by leonardder** [comment]
> Have you done testing in places such as MS Edge, with aria-describedby etc? 

Yes.

> Does fullDescription sometimes duplicate text that was in the name? 

I've seen this in Edge Legacy, yes. However, this was already the case. That's just bad usage of full description IMO.

> How about on MS Office Ribbons. Does it behave itself? 

With basic testing, I didn't see any strange behavior.

> In principle I agree with this pr.

What do you think about my alternative suggestion for help text? In my opinion, description and help text are and should be treated as separate things.

**Comment by michaelDCurran** [comment]
Adding a helpText property is okay, though perhaps a little too 
over-engineered if there are no cases of both of them returning valid 
info at the same time. Do you think that there are situations in UIA 
where helpText and fullDescription do give different (and valid) results?

Rather than perhaps just using fullDescription but falling back to 
helpText if empty.

If we do implement a helpText property, then we can map 
IAccessible::accHelp to that as well I guess.

**Comment by leonardder** [comment]
> Adding a helpText property is okay, though perhaps a little too over-engineered if there are no cases of both of them returning valid info at the same time. Do you think that there are situations in UIA where helpText and fullDescription do give different (and valid) results?

Honestly, I couldn't think of any.

**Comment by leonardder** [comment]
@michaelDCurran I think we can leave this as is.

**Review by michaelDCurran — APPROVED** [review]

**Pull request merged**
