### PR TITLE
Fix the wrong rendering format of command line options in userGuide

### PR DESCRIPTION
**Pull request by hwf1324**
### Link to issue number:

none

### Summary of the issue:

In the Command Line Options section of the user guide, a pair of ``--``s on the line ``-copy-portable-config`` resulted in strikethrough rendering in the output HTML.

### Description of user facing changes

All options are \`\` by backticks.

### Description of development approach

All options are \`\` by backticks.

### Testing strategy:

View the HTML built after the changes.

### Change log entries:
New features
Changes
Bug fixes
For Developers

### Code Review Checklist:

- [ x] Pull Request description:
  - description is up to date
  - change log entries
- [ x] Testing:
  - Unit tests
  - System (end to end) tests
  - Manual testing
- [ ] API is compatible with existing add-ons.
- [ ] Documentation:
  - User Documentation
  - Developer / Technical Documentation
  - Context sensitive help for GUI changes
- [x ] UX of all users considered:
  - Speech 
  - Braille
  - Low Vision
  - Different web browsers
  - Localization in other languages / culture than English
- [ ] Security precautions taken.

### CODE REVIEW

**Comment by hwf1324** [comment]
https://github.com/nvaccess/nvda/blob/1e30951ea2a53f0732c7f6afe200b3d559dcf48c/user_docs/en/userGuide.t2t#L3946

Is `routing set 1` correct?

**Comment by hwf1324** [comment]
Is there a way I can undo the first commit? I accidentally let it introduce a fix for too many trailing spaces.

**Review by seanbudd — DISMISSED** [review]
Thanks @hwf1324!

**Comment by seanbudd** [comment]
>In the Command Line Options section of the user guide, a pair of --s on the line -copy-portable-config resulted in strikethrough rendering in the output HTML.

It seems like there are no changes related to this in the diff?

>
Is there a way I can undo the first commit? I accidentally let it introduce a fix for too many trailing spaces.

`git rebase` can help, however i'm not aware of any accessible documentation on this feature. most guides rely on diagrams.

It may be easier to start again, or fix these manually.

**Comment by hwf1324** [comment]
> Is there a way I can undo the first commit? I accidentally let it introduce a fix for too many trailing spaces.

has been re-changed.

**Comment by XLTechie** [comment]
Git revert

might have helped with this. For your future reference, here's a nice article on 
how to un-do (most) things with git:
https://github.blog/2015-06-08-how-to-undo-almost-anything-with-git/

**Review by seanbudd — APPROVED** [review]
Thanks @hwf1324

**Pull request merged**
