### PR TITLE
soffice: Report page-relative caret position when available

### LINKED ISSUE #11696: LibreOffice Writer: Unusable coordinates announced
### Steps to reproduce:
1. Open Writer.
2. Working with screenreader NVDA hit NVDA + Delete.

### Actual behavior:
The Screeader announces a two part number, withou anyone knoing what this is about to be.

### Expected behavior:
A clear position shound be announced (lef, right, high and low) position should be announced.

#### NVDA installed/portable/running from source:
installed
#### NVDA version:
2020.2

#### Windows version:
Edition	Windows 	10 Home
Version				1909
Operating system build	18363.1016

#### Name and version of other software in use when reproducing the issue:
LibreOffice
Version:	7.0.0.3 (x64)
Build ID:	8061b3e9204bef6b321a21033174034a5e2ea88e
CPU-Threads: 	4; BS: Windows 10.0 Build 18363; UI-Render: Skia/Vulkan; VCL: win
Locale: 	de-DE (de_DE); UI: de-DE
Calc: 	threaded

#### Other information about your system:
---
#### Does the issue still occur after restarting your computer?
Yes.

#### Have you tried any other versions of NVDA? If so, please report their behaviors.
No.

#### If addons are disabled, is your problem still occuring?
Not tested.

#### Did you try to run the COM registry fixing tool in NVDA menu / tools?
Not tested.

### PR DESCRIPTION
**Pull request by michaelweghorn**
### Link to issue number:

Fixes #11696
Related LibreOffice bug report:
https://bugs.documentfoundation.org/show_bug.cgi?id=136760

### Summary of the issue:

When reporting the review cursor location in LibreOffice Writer, the announced position was not particularly useful to determine where in the document/page the cursor is currently located.

### Description of user facing changes

Similar to how it is done for Microsoft Word, report the current cursor/caret location relative to the current page when that information is available for LibreOffice Writer.

### Description of development approach

To retrieve the page-relative cursor/caret location, this introduces and makes use of a new `SymphonyDocumentTextInfo` class that retrieves the page-relative cursor position via accessible attributes from the document object.

These attributes are added to LibreOffice in this corresponding LibreOffice change:
https://gerrit.libreoffice.org/c/core/+/149051

The values returned by LibreOffice Writer are in twips, so convert that to inches or centimetres, depending on whether or not imperial measurement units are expected.

If the attributes are not available, fall back to the handling that was already used so far.

### Testing strategy:

Testing strategy:
* use a LibreOffice build that includes the changes from https://gerrit.libreoffice.org/c/core/+/149051
* start LibreOffice Writer
* trigger reporting the review cursor location by pressing NVDA+shift+numpadDelete
* verify that the current caret position is announced in centimetres or inches from the left and top edge of the page

### Known issues with pull request:

none

### Change log entries:

*Changes*
`When reporting the review cursor location, the current cursor/caret location is now reported relative to the current page in LibreOffice Writer for LibreOffice versions >= 7.6, similar to what is done for Microsoft Word. (#11696)`

### Code Review Checklist:

- [x] Pull Request description:
  - description is up to date
  - change log entries
- [x] Testing:
  - Unit tests
  - System (end to end) tests
  - Manual testing
- [x] API is compatible with existing add-ons.
- [x] Documentation:
  - User Documentation
  - Developer / Technical Documentation
  - Context sensitive help for GUI changes
- [x] UX of all users considered:
  - Speech 
  - Braille
  - Low Vision
  - Different web browsers
  - Localization in other languages / culture than English
- [x] Security precautions taken.

### CODE REVIEW

**Comment by michaelweghorn** [comment]
If there are any suggestions on different approaches or adapting the attributes reported by LibreOffice, I'm happy for any feedback on that and won't merge the corresponding LibreOffice change ( https://gerrit.libreoffice.org/c/core/+/149051 ) before there is an agreed way on how to expose/retrieve the required information.

**Review by michaelDCurran — CHANGES_REQUESTED** [review]
This looks good, accept that I don't believe you need the `__init__` methods on SymphonyDocument or SymphonyDocumentTextInfo. They don't seem to do anything, and Python will automatically call super's constructor if they are not defined.

**Comment by michaelweghorn** [comment]
> This looks good, accept that I don't believe you need the `__init__` methods on SymphonyDocument or SymphonyDocumentTextInfo. They don't seem to do anything, and Python will automatically call super's constructor if they are not defined.

Indeed, I've dropped them now. Thanks!

**Comment by michaelweghorn** [comment]
> @[michaelweghorn](https://github.com/michaelweghorn) michaelweghorn requested review from [michaelDCurran](https://github.com/michaelDCurran) and removed request for [seanbudd](https://github.com/seanbudd)

@michaelDCurran I pressed the "Re-request review" (or similarly labeled) button next to your username now that the requested change has been implemented. This resulted in the above action, but I didn't intentionally want to remove any reviewers. Can you give me any hint on what's the proper process?

**Review by michaelDCurran — APPROVED** [review]

**Pull request merged**
