### PR TITLE
Report row and column span for table cells in speech and braille

### PR DESCRIPTION
**Pull request by LeonarddeR**
### Link to issue number:
Partial fix for #2642.

### Summary of the issue:
When a table cell spans multiple rows and/or columns, this is currently not reported by NVDA by default, only in Microsoft Excel.

### Description of how this pull request fixes the issue:
This pr reports row and column span with both speech and braille.

#### Examples
* For a cell in row 1 and column 1, spanning two columns
    + Old output: row 1 column 1
    + New speech output: row 1 column 1 through 2
    + New braille output: r1 c1-2

* For a cell in row 1 and column 1, spanning two rows
    + Old output: row 1 column 1
    + New speech output: row 1 through 2 column 1
    + New braille output: r1-2 c1

* For a cell in row 1 and column 1, spanning two rows and two columns
    + Old output: row 1 column 1
    + New speech output: row 1 column 1 through row 2 column 2
    + New braille output: r1-2 c1-2

The reason why the latter speech output differ from the former, is that, especially with faster speech rates, it feels a bit more clear to only have the word through once. However, this is open to a debate.

### Testing performed:
Tested the following applications

* Mozilla Firefox
* Google Chrome
* Internet Explorer
* Microsoft Edge
* Microsoft Excel in UIA mode, don't ask me how, it was hacky.

### Known issues with pull request:
This does not work for Word yet as noted in #2642. However, I'm pretty sure that this code will work out of the box for the UIA implementation of Word (#7849).

### Change log entry:
* New features
    + Reporting of column or row span is now supported in more cases when working with tables. (#2642)

### CODE REVIEW

**Comment by derekriemer** [comment]
Suggested change to 
"Reporting of column or row span is now supported in more cases when working with tables."

**Comment by michaelDCurran** [comment]
It would be good to implement columnSpan / rowSpan NVDAObject properties for IAccessible NVDAObject and UIA NVDAObject, so that row and column spans are announced outside of documents.  I can take a look at this at some point if you're not sure where to start.

**Comment by michaelDCurran** [comment]
Actually, I'm required by another contract to support row / col span for IAccessible2.  I'll add this support on top of this branch.

**Comment by leonardder** [comment]
[**@michaelDCurran**](https://github.com/michaelDCurran) commented on [26 Jan 2018, 02:00 CET](https://github.com/nvaccess/nvda/pull/7872#issuecomment-360652345 "2018-01-26T01:00:14Z - Replied by Github Reply Comments"):
> It would be good to implement columnSpan / rowSpan NVDAObject properties for IAccessible NVDAObject and UIA NVDAObject, so that row and column spans are announced outside of documents. 

This has already been done for UIA.

> Actually, I'm required by another contract to support row / col span for IAccessible2. I'll add this support on top of this branch.

In that case, I'll leave this branch alone until further notice.

Note that it might be good to think about a generic way to present row and column span when there is cellCoordsText (i.e. when a cell in Google Sheets is merged). In Excel, cellCoordsText is actually always empty, it seems.

**Review by michaelDCurran — APPROVED** [review]
I just pushed support for IAccessible2 row/column span.

**Review by LeonarddeR — COMMENTED** [review]
Your two last commits look ok, thanks a lot. You could consider changing the Copyright headers while at it.

**Comment by leonardder** [comment]
@michaeldcurran: Have you actually tested this IAccessible2 code somewhere it can be easily confirmed to work? LibreOffice, for example?

**Comment by michaelDCurran** [comment]
It has been tested on Amazon Kindle  for PC with table support, not yet 
publically available... but I can now talk about it.

A separate PR specific to that work will be coming very soon.

**Comment by michaelDCurran** [comment]
The following html file can be used to test rowspan and colspan in Focus mode in Firefox. Open the page in Firefox, switch to focus mode and tab through the links. The table is a 3 by 3 grid of cells, each one containing a link. However, row 1 column 1 has a colspan of 2, and row 2 column 1 has a rowspan of 2. 
[cellSpans.html.txt](https://github.com/nvaccess/nvda/files/1709697/cellSpans.html.txt)

**Comment by leonardder** [comment]
I've done some research on support row/columnspan in LibreOffice, but it looks like they don't implement IAccessibleTableCell. I'm afraid it is therefore impossible at the moment.

**Comment by leonardder** [comment]
I've done some research on support row/columnspan in LibreOffice, but it looks like they don't implement IAccessibleTableCell. I'm afraid it is therefore impossible at the moment.

**Pull request merged**
