### PR TITLE
Performance increase interacting with Visual Studio

### PR DESCRIPTION
**Pull request by michaelDCurran**
### Link to issue number:
None.

### Summary of the issue:
Users are reporting bad performance in NVDA 2020.4 when interacting with Visual Studio.
Performance seemed to decrease after NVDA 2020.3 due to PR #11421.
In NVDAObjects.UIA.visualStudio.findExtraOverlayClasses, parent is fetched for any object given. This causes a great deal of recursion as many ancestors of a given object in Visual Studio will also run through this findExtraOverlayClasses.

### Description of how this pull request fixes the issue:
In NVDAObjects.UIA.visualStudio.findExtraOverlayClasses: make sure to only fetch parent when absolutely necessary. 
Specifically, reverse a check that would look at parent's type and then check a UIA property on self.

### Testing strategy:
* Moved up and down Solution explorer, opening and closing branches of the solution. Confirming that there is much less of a delay.
* Tabbing into a property page in Visual Studio options. NVDA starts speaking sometimes up to 4 times quicker.

Other users should try and confirm that performance has improved for them.
Users should confirm that support for auto complete / intellisense s is still read correctly by NVDA.

### Known issues with pull request:
None known.

### Change log entry:
Bug fixes:
* Performance when interacting with Visual Studio has been improved.

### Code Review Checklist:

This checklist is a reminder of things commonly forgotten in a new PR.
Authors, please do a self-review and confirm you have considered the following items.
Mark items you have considered by checking them.
You can do this when editing the Pull request description with an x: `[ ]` becomes `[x]`.
You can also check the checkboxes after the PR is created.

- [ ] Pull Request description is up to date.
- [ ] Unit tests.
- [ ] System (end to end) tests.
- [ ] Manual tests.
- [ ] User Documentation.
- [ ] Change log entry.
- [ ] Context sensitive help for GUI changes.

### CODE REVIEW

**Comment by cary-rowen** [comment]
It seems that he has indeed improved performance, can it be further optimized?
In addition, NVDA and VS freeze together in the Winform form designer, which can also be reproduced in 2020.4.

thanks.

**Review by LeonarddeR — APPROVED** [review]
I'm very sorry for causing this regression

**Comment by cary-rowen** [comment]
Maybe someone else can test this build.

**Comment by cary-rowen** [comment]
I tested the latest build version and it still freezes in the window designer and causes VS to crash. The crash happened after adding a combo box to the window.
The following is the log:
[nvda.log](https://github.com/nvaccess/nvda/files/6145236/nvda.log)

**Comment by leonardder** [comment]
> I tested the latest build version 

TO make sure, did you test latest Alpha or the build for this pull request? Also, did the problem you describe occur in 2020.3 as well? In latter case, this pr won't fix this. It will only fix a regression introduced in NVDA 2020.4.

**Comment by cary-rowen** [comment]
@leonardder 
Yes, I tested the latest Alpha Version and the issue exists, but it should not be a regression from 2020.4. And the issue only appears within the form designer of .net5 WinForm apps.
If this is the case, I will try to open a new Issue.
Thanks!

**Comment by cary-rowen** [comment]
I have confirmed that my situation is exactly the same as #12146.
@leonardder

**Pull request merged**
