### PR TITLE
No more focus event issue after reloading appModules

### LINKED ISSUE #17323: Focused objects not reported after a plugins reload
The issue seems to be reproducible with any browseable message. Here is an example with the format reporting command.

### Steps to reproduce:
* Go somewhere where the formatting command has something to report, e.g. in Windows commands console (cmd).
* Press twice NVDA+f to display formatting information in a browseable message
* `Alt+Tab` to the console
* Reload the plugins with `NVDA+control+f3`
* `Alt+Tab` somewhere else or move the focus elsewhere in some way.

### Actual behavior:
The new focus is not reported.
### Expected behavior:
The new focus should be reported.
### NVDA logs, crash dumps and other attachments:
```
ERROR - eventHandler.executeEvent (15:30:42.709) - MainThread (18484):
error executing event: gainFocus on <NVDAObjects.Dynamic_IAccessibleEditWindowNVDAObject object at 0x00CC1630> with extra args of {}
Traceback (most recent call last):
  File "eventHandler.pyc", line 348, in executeEvent
  File "eventHandler.pyc", line 382, in doPreGainFocus
  File "api.pyc", line 155, in setFocusObject
  File "treeInterceptorHandler.pyc", line 83, in cleanup
  File "baseObject.pyc", line 39, in __get__
  File "virtualBuffers\MSHTML.pyc", line 286, in _get_isAlive
AttributeError: 'NoneType' object has no attribute 'appName'

```
#### NVDA installed/portable/running from source:
Installed
#### NVDA version:
2024.4rc1
#### Windows version:
Windows 10 22H2 (AMD64) build 19045.5011
#### Name and version of other software in use when reproducing the issue:
N/A
#### Other information about your system:
N/A
#### Does the issue still occur after restarting your computer?
Yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
Already present in previous versions of NVDA, at least 2024 cycle, but probably much earlier.
#### If NVDA add-ons are disabled, is your problem still occurring?
Yes
#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
Yes

### PR DESCRIPTION
**Pull request by CyrilleB79**
### Link to issue number:
Fixes #17323

### Summary of the issue:
After a reload of plugins (`NVDA+control+f3`), focus events do not report the new focus as expected.

During focus event, NVDA tests which tree interceptors are alive or not to clean up those which are dead. In this test, for MSHTML, NVDA looks at `root.appModule.appName`, `root` being the root object associated to the virtual MSHTML buffer.

However, `root.appModule` may be `None` after plugins are reloaded.

### Description of user facing changes
After plugins are reloaded while a browseable message is opened, the focus will no longer fail to be reported.
### Description of development approach
Fixed the logic for MSHTML

### Testing strategy:
Tested STR in #17323.
### Known issues with pull request:
None
### Code Review Checklist:

- [x] Documentation:
  - Change log entry
  - User Documentation
  - Developer / Technical Documentation
  - Context sensitive help for GUI changes
- [x] Testing:
  - Unit tests
  - System (end to end) tests
  - Manual testing
- [x] UX of all users considered:
  - Speech
  - Braille
  - Low Vision
  - Different web browsers
  - Localization in other languages / culture than English
- [x] API is compatible with existing add-ons.
- [x] Security precautions taken.

@coderabbitai summary

### CODE REVIEW

**Comment by seanbudd** [comment]
I merged #17334 from @LeonarddeR - can you resolve conflicts?

**Comment by CyrilleB79** [comment]
@seanbudd, I have upmerged from latest master.

The changes that I had made in `source/keyboardHandler.py` have been taken by @LeonarddeR in #17334 so this file is not part of this PR anymore.

**Comment by CyrilleB79** [comment]
Also updated the initial description consequently.

**Review by seanbudd — APPROVED** [review]
Thanks @CyrilleB79

**Pull request merged**
