### PR TITLE
UI Automation in Windows Console: fix setEndPoint/compareEndPoints

### LINKED ISSUE #10035: UIA in Windows consoles: current character does not show up in braille
cc @codeofdusk 

### Steps to reproduce:
1. With braille enabled, open a windows console with UIA enabled
2. type hello
3. Press left arrow multiple times.

### Actual behavior:
Braille does not show the character the caret is at. When hello was typed, the whole word is shown. However, when pressing left arrow N times, the result after the prompt is as follows:

1. hell
2. helo
3. helo
4. hllo
5. ello

### Expected behavior:
The current character is not stripped from braille output

#### NVDA installed/portable/running from source:
Installed

#### NVDA version:
alpha-18290

#### Windows version:
Windows 10 1903 build 18362.239
#### Name and version of other software in use when reproducing the issue:
Command prompt (cmd)

#### Does the issue still occur after restarting your PC?
Yes

#### Have you tried any other versions of NVDA? If so, please report their behaviors.
No

### PR DESCRIPTION
**Pull request by codeofdusk**
### Link to issue number:
Closes #10035. Related to #9614.

### Summary of the issue:
Braille does not properly track the system caret in Windows Console.

### Description of how this pull request fixes the issue:
#9802 introduced a patched implementation of `_get_isCollapsed`. As suggested by @leonardder, this code has been factored out into a new `_endPointHelper` method which normalizes endPoints for `compareEndPoints` and `setEndPoint` (used by `_get_isCollapsed`, Braille support, and possibly others).

### Testing performed:
Tested that the `isCollapsed` property behaves as expected (in the Python console). Testing by @leonardder indicates that Braille behaves as expected after the change.

### Known issues with pull request:
None.

### Change log entry:
None.

### CODE REVIEW

**Comment by codeofdusk** [comment]
Cc @feerrenrut @leonardder

**Comment by leonardder** [comment]
I see why you brought back isCollapsed. I have a small concern though.

1. The base TextInfo implementation of TextInfo.isCollapsed calls compareEndPoints
2. Now. your implementation of compareEndPoints indirectly calls is Collapsed.
3. If the implementation of isCollapsed ever calls super, this causes an endless loop. Currently it does not, but I see why it at some point would if Microsoft fixes things in the UIA implementation.

I think it makes sense to rename _get_isCollapsed to _get_isEmpty. endPointHelper can get ifEmpty and isCollapsed can just return it.

**Comment by codeofdusk** [comment]
Closing to possibly work around a Github bug. Identical PR pending.

**Comment by feerrenrut** [comment]
This PR does not seem to be updating from the source branch, it is missing commit 
5544ede. See diff between master and source branch: https://github.com/nvaccess/nvda/compare/master...codeofdusk:cmduia10-fix-compareendpoints

**Comment by leonardder** [comment]
I think that if there is a possible github bug, in most cases there are 
better ways to work around them than simply closing the pull request and 
opening a new one. A force push can help, for example. Same applies to 
switching the base branch. In the future, could you please ask for 
assistance to work around a bug rather than opening a new pr? This also 
offers the benefit of finding out what went wrong in order to avoid it 
in the future. Thanks a lot!

**Comment by feerrenrut** [comment]
@leonardder, Bill opened a new PR at my request. I wanted to preserve the state of this PR for the Github bug report. I hadn't considered that opening a new PR would close this one.

**Comment by leonardder** [comment]
thanks for clarifying!

**Pull request closed without merging**
