### PR TITLE
Update espeak Synchronization official

### PR DESCRIPTION
**Pull request by dpy013**
### Link to issue number:
none
### Summary of the issue:
From [espeak-ng](https://github.com/espeak-ng/espeak-ng) Synchronize the latest version to NVDA
### Description of how this pull request fixes the issue:
Update espeak Synchronization official
### Testing performed:
The local environment has been used for compilation testing, and the test passes
### Known issues with pull request:
none
### Change log entry:

Section: Changes
Update Espeak to cbf3c99fbdfad3e948a9c905c31a22d2b3eb342f

thanks

### CODE REVIEW

**Comment by leonardder** [comment]
Could you elaborate on what makes this update necessary? Espeak is known to introduce regressions pretty easily, therefore I think we need a real case that justifies this update.

**Comment by Brian1Gaff** [comment]
Yes many synths do this. For example on my Iphone a while back they improved 
it and yesterday became yestertay.
 It is always a good idea to at least  run some tests before you go the 
whole hog, so to speak.
 Brian

bglists@blueyonder.co.uk
Sent via blueyonder.
Please address personal E-mail to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.
Newsgroup monitored: alt.comp.blind-users
----- Original Message -----

**Comment by dingpengyu** [comment]
> Could you elaborate on what makes this update necessary? Espeak is known to introduce regressions pretty easily, therefore I think we need a real case that justifies this update.

hello leonardder
Mainly did a compilation test.
The reason for the update is mainly to synchronize the latest code and use the latest features of espeak.
thanks.

**Comment by feerrenrut** [comment]
We won't update espeak in the 2020.2 release, but perhaps for the 2020.3 release.

What is new in espeak that you think is useful for NVDA?
Why this particular commit?
I'm going to close this PR until this information is provided.

**Comment by leonardder** [comment]
I Agree with @feerrenrut that closure is justified here,

**Pull request closed without merging**
