### PR TITLE
Fix HTML characters in mozilla rich edit causing error

### LINKED ISSUE #12542: Thunderbird: certain characters with some HTML codes break braille output in the compose window
### Steps to reproduce:
1. Open Thunderbird.
2. Create a new message (CTRL+n).
3. Set the focus on the message body field.
4. Insert the following HTML code from Insertion menu (alt+i) → HTML... (H).
   `<div>😄<br /><hr /><a href="https://nvaccess.org/">nvaccess.org</a></div>`
  Please note that this is an intentionally minimal HTML code. I originally encountered this bug with more complex codes.
5. Once back on the message body field, press uparrow to go the first line.

### Actual behavior:
Braille output is not refreshed and the following is raised in the log (speech output OK):

<details><summary>Log</summary>

```
IO - inputCore.InputManager.executeGesture (11:58:43.062) - winInputHook (14280):
Input: kb(laptop):upArrow
DEBUG - editableText.EditableText._hasCaretMoved (11:58:43.117) - MainThread (12080):
Caret move detected using bookmarks. Elapsed: 0 ms
ERROR - scriptHandler.executeScript (11:58:43.162) - MainThread (12080):
error executing script: <bound method EditableText.script_caret_moveByLine of <NVDAObjects.Dynamic_EditableTextWithAutoSelectDetectionDocumentEditorMozillaIAccessible object at 0x08AD8470>> with gesture 'flèche haut'
Traceback (most recent call last):
  File "scriptHandler.pyc", line 208, in executeScript
  File "editableText.pyc", line 224, in script_caret_moveByLine
  File "editableText.pyc", line 163, in _caretMovementScriptHelper
  File "NVDAObjects\behaviors.pyc", line 177, in _caretScriptPostMovedHelper
  File "editableText.pyc", line 149, in _caretScriptPostMovedHelper
  File "speech\speech.pyc", line 1128, in speakTextInfo
  File "speech\types.pyc", line 42, in __iter__
  File "speech\speech.pyc", line 1168, in getTextInfoSpeech
  File "NVDAObjects\IAccessible\ia2TextMozilla.pyc", line 390, in getTextWithFields
  File "NVDAObjects\IAccessible\ia2TextMozilla.pyc", line 329, in _getText
  File "NVDAObjects\IAccessible\ia2TextMozilla.pyc", line 261, in _iterRecursiveText
  File "NVDAObjects\IAccessible\ia2TextMozilla.pyc", line 38, in _getRawTextInfo
AttributeError: 'NoneType' object has no attribute 'role'
```

</details>

### Expected behavior:
Braille output should be updated, no error.

#### NVDA installed/portable/running from source:
Installed

#### NVDA version:
alpha-23069,94b8fa28

#### Windows version:
21H1

#### Name and version of other software in use when reproducing the issue:
Thunderbird 78.11.0 (64 bits)

#### Other information about your system:
N/A

#### Does the issue still occur after restarting your computer?
Yes

#### Have you tried any other versions of NVDA? If so, please report their behaviors.
No

#### If add-ons are disabled, is your problem still occurring?
Yes

#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
Yes

### PR DESCRIPTION
**Pull request by mwhapples**
### Link to issue number:
Closes #12542 
### Summary of the issue:
In mozilla applications when pasting certain HTML into rich edit controls it can lead to errors when navigating through the text. One such example is in the thunderbird compose message edit area.
### Description of how this pull request fixes the issue:
The function _getEmbedded in ia2TextMozilla.py returns Optional, however the return value is never checked to be not None and this assumption leads to errors later on when the value is used. This pull request adds a check for None being returned from _getEmbedded and skips it if None is found.
### Testing strategy:
Manually tested.
### Known issues with pull request:
None known.
### Change log entries:
New features
Changes
Bug fixes No longer give errors when navigating certain text in Mozilla rich edit controls.
For Developers

### Code Review Checklist:

- [x] Pull Request description:
  - description is up to date
  - change log entries
- [x] Testing:
  - Unit tests Unsure how to add tests for this.
  - System (end to end) tests Unsure how to add tests for this.
  - Manual testing Done
- [x] API is compatible with existing add-ons.
- [x] Documentation:
  - User Documentation
  - Developer / Technical Documentation
  - Context sensitive help for GUI changes
- [x] UX of all users considered:
  - Speech 
  - Braille
  - Low Vision
  - Different web browsers
  - Localization in other languages / culture than English

### CODE REVIEW

**Review by seanbudd — APPROVED** [review]

**Comment by seanbudd** [comment]
I'm unable to push changes to the `aphtech` fork. I believe you need to invite us as collaborators to the fork to be able to push changes.

The changelog entry I was trying to add is as follows:

`- Fix braille output when navigating certain text in Mozilla rich edit controls, such as drafting a message in Thunderbird. (#12542)`

**Comment by mwhapples** [comment]
I thought I had set the pull request to want to merge into nvaccess/nvda master branch. I will need to check if I have done anything wrong when creating the pull request and how to change my work flow./

**Comment by seanbudd** [comment]
@mwhapples - you'll need to add NV Access developers as contributors to the aphtech/nvda repository

**Comment by seanbudd** [comment]
Thanks - you might be able to invite @nvaccess/developers otherwise, @feerrenrut and @michaelDCurran getting an invite should be fine for now.

**Pull request merged**
