### PR TITLE
Remove Adobe Flash support from NVDA

### LINKED ISSUE #11131: Adobe Flash content no longer appears to read in NVDA
### Steps to reproduce:
1. Load a page with at least somewhat accessible Flash Content in Internet Explorer or the new Microsoft Edge.
2. Press enter on the flash object.

### Actual behavior:
In Internet Explorer, chosen because it tends to support Flash by default, the only thing that happens is that the name of the object gets spoken after "embedded object". No focus change, the content of the object remains unreachable. In the logs, nothing at all is reported when pressing enter or loading the relevant page, not even in Debug mode.

In Edge based on Chrome, the embedded object reports as being "unavailable", and this, possibly relevant, log output shows up. Note: This might also be happening because of me navigating to the permissions popup to allow flash.
```
DEBUGWARNING - NVDAObjects.IAccessible.IAccessible._get_IAccessibleRole (13:55:26.198) - MainThread (5608):
accRole failed: (-2147024809, 'The parameter is incorrect.', (None, None, None, 0, None))
DEBUGWARNING - NVDAObjects.IAccessible.IAccessible._get_IAccessibleRole (13:55:26.659) - MainThread (5608):
accRole failed: (-2147024809, 'The parameter is incorrect.', (None, None, None, 0, None))
IO - speech.speak (13:55:26.669) - MainThread (5608):
Speaking [LangChangeCommand ('en'), 'Laden voltooid']
IO - braille.BrailleBuffer.update (13:55:26.670) - MainThread (5608):
Braille regions text: ['Laden voltooid']
IO - braille.BrailleHandler.update (13:55:26.670) - MainThread (5608):
Braille window dots: 6 123 1 145 15 1345 - 1236 135 123 2345 135 135 24 145
IO - inputCore.InputManager.executeGesture (13:55:28.397) - winInputHook (8388):
Input: kb(laptop):f6
DEBUG - treeInterceptorHandler.killTreeInterceptor (13:55:28.428) - MainThread (5608):
Killed treeInterceptor: <NVDAObjects.IAccessible.chromium.ChromeVBuf object at 0x07209630>
DEBUG - treeInterceptorHandler.update (13:55:28.446) - MainThread (5608):
Adding new treeInterceptor to runningTable: <NVDAObjects.IAccessible.chromium.ChromeVBuf object at 0x07277B90>
DEBUG - virtualBuffers.VirtualBuffer._loadBuffer (13:55:28.447) - NVDAObjects.IAccessible.chromium.VirtualBuffer.loadBuffer (18740):
Buffer load took 0.001 sec, 1 chars
DEBUGWARNING - RPC process 22284 (msedge.exe) (13:55:28.471) - Dummy-5 (152):
Thread 14452, build\x86_64\vbufBase\storage.cpp, VBufStorage_buffer_t::findNodeByAttributes, 967:
 offset 1 is past end of buffer, returning NULL

DEBUGWARNING - RPC process 22284 (msedge.exe) (13:55:28.478) - Dummy-5 (152):
Thread 14452, build\x86_64\vbufBase\storage.cpp, VBufStorage_buffer_t::locateTextFieldNodeAtOffset, 859:
Offset 1 out of range. Returnning NULL

DEBUGWARNING - RPC process 22284 (msedge.exe) (13:55:28.487) - Dummy-5 (152):
Thread 14452, build\x86_64\vbufBase\storage.cpp, VBufStorage_buffer_t::locateControlFieldNodeAtOffset, 879:
Could not locate node at offset, returning NULL

DEBUGWARNING - virtualBuffers.VirtualBufferTextInfo._getNVDAObjectFromOffset (13:55:28.487) - MainThread (5608):
Couldn't get NVDAObject from offset 1
DEBUGWARNING - browseMode.BrowseModeDocumentTreeInterceptor._set_selection (13:55:28.487) - MainThread (5608):
Invalid NVDAObjectAtStart

IO - speech.speak (13:55:28.488) - MainThread (5608):
Speaking [LangChangeCommand ('en'), 'Game Page']
IO - speech.speak (13:55:28.489) - MainThread (5608):
Speaking [<speech.commands.CallbackCommand object at 0x005EB330>]
DEBUGWARNING - RPC process 22284 (msedge.exe) (13:55:28.498) - Dummy-5 (152):
Thread 14452, build\x86_64\vbufBase\storage.cpp, VBufStorage_buffer_t::getLineOffsets, 1055:
Offset of 1 too big for buffer, returning false

```

### Expected behavior:
The contents of the flash object should be readable.
#### Does the issue still occur after restarting your computer?
Yes

#### Have you tried any other versions of NVDA? If so, please report their behaviors.
No
#### If addons are disabled, is your problem still occuring?
Yes
#### Did you try to run the COM registry fixing tool in NVDA menu / tools?

No

### PR DESCRIPTION
**Pull request by LeonarddeR**
### Link to issue number:
Closes #11131

### Summary of the issue:
Adobe Flash is no longer supported and even actively removed from every PC and browser.

### Description of how this pull request fixes the issue:
Remove Flash support from NVDA.
Flash code was dug  up by using `git grep -i flash` in the NVDA repo.

### Testing strategy:
This only has to do with removing code. It is hard to test something that has been removed, especially now Flash is also no longer available to test this with. There were also several reports of things being broken already beforehand.

### Known issues with pull request:
People who still need Flash will have to use an older version of NVDA. I think this is fine, as the use of Flash is strongly discouraged en is actively opposed. People really need to know what they do.

### Change log entry:
* Changes
     + Support for Adobe Flash content has been removed from NVDA due to the use of Flash being actively discouraged by Adobe.  (#11131)

### Code Review Checklist:

This checklist is a reminder of things commonly forgotten in a new PR.
Authors, please do a self-review and confirm you have considered the following items.
Mark items you have considered by checking them.
You can do this when editing the Pull request description with an x: `[ ]` becomes `[x]`.
You can also check the checkboxes after the PR is created.

- [x] Pull Request description is up to date.
- [x] Unit tests.
- [x] System (end to end) tests.
- [x] Manual tests.
- [x] User Documentation.
- [x] Change log entry.
- [x] Context sensitive help for GUI changes.

### CODE REVIEW

**Comment by leonardder** [comment]
Ideally we update miscdeps after merging https://github.com/nvaccess/nvda-misc-deps/pull/21

**Comment by alexarnaud** [comment]
> People who still need Flash will have to use an older version of NVDA. I think this is fine, as the use of Flash is strongly discouraged en is actively opposed. People really need to know what they do.

If it has no real downside for the NVDA maintainability, it'd suggest keeping the Flash support until 2022.1 to ensure to not disturb business users. There are maybe users still needing Flash and the Flash end of the support is quite recent.

**Comment by Brian1Gaff** [comment]
It seems though that although flash sites are out there in the small 
independent space, many of them were never very accessible since the writers 
chose to make them that way. If it does no harm leaving it though, why not 
save any hassle that this might cause and leave it in?
 Brian

***@***.***
Sent via blueyonder.
Please address personal E-mail to:-
***@***.***, putting 'Brian Gaff'
in the display name field.
Newsgroup monitored: alt.comp.blind-users

**Comment by dingpengyu** [comment]
I support removing adobe flash support from NVDA

**Comment by Brian1Gaff** [comment]
Its still on my machine from what I can see, it apparently was last used 
three days ago, but I don't remember it, I think it may have been an audio 
player embedded on a page though.
 Brian

***@***.***
Sent via blueyonder.
Please address personal E-mail to:-
***@***.***, putting 'Brian Gaff'
in the display name field.
Newsgroup monitored: alt.comp.blind-users
----- Original Message ----- 
From: "Leonard de Ruijter" ***@***.***>
To: "nvaccess/nvda" ***@***.***>
Cc: "Subscribed" ***@***.***>
Sent: Monday, March 22, 2021 7:44 AM
Subject: [nvaccess/nvda] Remove Adobe Flash support from NVDA (#12207)

**Comment by feerrenrut** [comment]
Just for reference, the major browsers have all dropped support for flash:
- Firefox: https://blog.mozilla.org/futurereleases/2020/11/17/ending-firefox-support-for-flash/
  - On January 26, 2021 when we release Firefox version 85, it will ship without Flash support.
- Microsoft browsers:  https://docs.microsoft.com/en-us/lifecycle/announcements/adobe-flash-end-of-support
- Chrome: https://www.blog.google/products/chrome/saying-goodbye-flash-chrome/

Someone wishing to continue using Flash will need to be using an out of date browser.

**Review by feerrenrut — COMMENTED** [review]
The changes look fine to me. Though I'd ask that you please update the description to include your process for finding and removing Flash support. We can then review that process rather than just the changed files.

I'd also like @michaelDCurran to take a look at this.

**Comment by tapper82** [comment]
This is good. The code for flash is just ded code rite now. I am happy to see the back of flash.

**Comment by leonardder** [comment]
@feerrenrut I updated the description. The procedure was quite simple, Flash code was dug  up by using `git grep -i flash` in the NVDA repo.

**Comment by alexarnaud** [comment]
> Someone wishing to continue using Flash will need to be using an out of date browser.

It still exists Firefox ESR version which will be supported until 2021-09-07. See there for details: https://wiki.mozilla.org/Release_Management/Calendar

**Comment by lukaszgo1** [comment]
While normally keeping support for Flash would have no disadvantage IMHO in this case it is broken already ((see #11131) and therefore people needing to use it are required to use older version of NVDA already. Since trying to fix it at this stage of Flash's lifetime is no good use of anyone's time I agree with the removal.

**Review by michaelDCurran — APPROVED** [review]

**Comment by DrSooom** [comment]
This PR also closes issue #12162.

**Pull request merged**
