### PR TITLE
add pronunciation for raw Unicode braille cells

### PR DESCRIPTION
**Pull request by saizai**
If Unicode braille occurs within text — for instance, ⠐⠣⠃⠗⠇⠐⠜ says "(braille)" in UEB — NVDA currently just skips over the braille entirely. This makes it at least pronounce the braille cells.

Because this is pronunciation for the Unicode characters themselves, it is braille-code-agnostic and just pronounces individual braille characters in the usual "dot 3 5 7" way. If the input table is known, this default should get overridden, but it's at least a fallback, and allows one to read text that's _about_ braille.

I've left level & preserve in defaults.

### Change log entries:
New features
Changes
Bug fixes
For Developers

### Code Review Checklist:

- [ ] Pull Request description:
  - description is up to date
  - change log entries
- [ ] Testing:
  - Unit tests
  - System (end to end) tests
  - Manual testing
- [ ] API is compatible with existing add-ons.
- [ ] Documentation:
  - User Documentation
  - Developer / Technical Documentation
  - Context sensitive help for GUI changes
- [ ] UX of all users considered:
  - Speech 
  - Braille
  - Low Vision
  - Different web browsers
  - Localization in other languages / culture than English

### CODE REVIEW

**Comment by seanbudd** [comment]
Please fill out the pull request template

**Comment by seanbudd** [comment]
Instead of "dot" please use "braille". This is similar to what other synthesizers or screen readers provide.

**Comment by seanbudd** [comment]
With no context, a screen reader user reading the symbol as "dot 3" will have no idea that the symbol refers to braille. In a given sentence "dot 1 3 5" is not as obvious as "Braille 1 3 5".  "1 3 5 Braille dot" might be better so users can skip the end when reading many of these in a row.

I don't think there is a way to hook into symbol pronunciation like that without doing work similar to what was dropped in #12710

Filling out the template allows your work to be understood clearly by other contributors. 
Without filling out the template fully this PR will not be accepted, and NV Access or other contributors will have to schedule picking it up.

**Comment by saizai** [comment]
> With no context, a screen reader user reading the symbol as "dot 3" will have no idea that the symbol refers to braille. In a given sentence "dot 1 3 5" is not as obvious as "Braille 1 3 5". "1 3 5 Braille dot" might be better so users can skip the end when reading many of these in a row.

I've added a complex sequence regex to capture the beginning and end of a braille sequence and say this.

I think it's better to not have each cell have a long reading, because that requires manual character by navigation to skip the extra language. This way, it can read them quickly as a paragraph.

> I don't think there is a way to hook into symbol pronunciation like that without doing work similar to what was dropped in #12710

:shrug: I've no idea either way.

> Filling out the template allows your work to be understood clearly by other contributors. Without filling out the template fully this PR will not be accepted, and NV Access or other contributors will have to schedule picking it up.

What other info can I supply that's in the form, not already given, and relevant here?

* AFAICT there's no applicable testing; https://github.com/nvaccess/nvda/blob/master/tests/system/robot/symbolPronunciationTests.py seems the closest and doesn't seem to be used for specific mappings like this.
* No API effect or documentation need AFAICT.
* I discussed UX above.
* It's in the English locale file, so obviously other languages will need to override to get localised versions; though I do speak several others, but I don't know how blind people natively pronounce braille cells in other languages.
* Change log seems something for devs to edit, not me.

So… what have I omitted?

**Comment by CyrilleB79** [comment]
@saizai the template fields are almost empty and you have put your description at the beginning.
As indicated in the PR's initial description edit box when you first open it, you can look at [Creating PR's on the NVDA project](https://github.com/nvaccess/nvda/blob/master/devDocs/githubPullRequestTemplateExplanationAndExamples.md) documentation to know how to fill each paragraph.

First of all you should probably split the content of your initial description in the applicable paragraphs, mainly "Summary of the issue" and "Description of how this pull request fixes the issue".

If a paragraph should not contain any information, please add "N/A" so that it is more explicit.

Regarding testing, you should describe how you have tested your changes. Probably, you have done manual testing, i.e. you have read a series of braille unicode character and have checked that they are now reported vocally.

Regarding the change log, it's your role to provide a short description of your work which will appear in the change log page. When this PR is merged, NVAccess people will then copy what you have written in the change log file.

At least regarding the "Code Review Checklist", as indicated in the documentation, you should check the checkbox to indicate that you have considered these tasks. For example if you check the "Documentation" item that means that you have thought to the documentation, either because you have actually updated some documentation or because you have confirmed by checking this checkbox that no upgrade of the documentation is needed in this PR.

But again, all is in the [documentation](https://github.com/nvaccess/nvda/blob/master/devDocs/githubPullRequestTemplateExplanationAndExamples.md)documentation to know how to fill each paragraph.

You can also look at the initial description of [already-merged PRs](https://github.com/nvaccess/nvda/pulls?q=is%3Apr+is%3Amerged+sort%3Aupdated-desc+) to see other examples of PR initial description.

HTH

**Comment by TheQuinbox** [comment]
@saizai, do you plan to move forward with this PR? It's something that would be extremely useful to say the least, and not filling out a template seems like a pretty silly reason to block it from being merged, on both sides. It seems NVAccess has been given enough info to merge this, but I also don't see why you won't just do it.

For the actual speaking, I like how VoiceOver on iOS does it . Braille dots 1 3 5, braille dots 1 3, braille dot 1, braille dots 1 3 4 5 6.

**Comment by seanbudd** [comment]
@TheQuinbox - as mentioned by Cyrille, information on testing is missing. As the PR stands right now, it is unclear what the new UX is, e.g. there is no example of speech. 

As I mentioned earlier, without @saizai doing the work, someone else must do it instead. With ~50 open PRs, I have added this to the schedule to be picked up later. In the mean time, anyone willing to do the tiny amount of work remaining is welcome to do so.

**Comment by seanbudd** [comment]
It would be ideal that these symbols were displayed on braille devices as readable braille as well

**Comment by lukaszgo1** [comment]
> It would be ideal that these symbols were displayed on braille devices as readable braille as well


@seanbudd In most (all I'm regularly using) LibLouis tables their are. Have you tested this and found a case in which they aren't?

**Comment by seanbudd** [comment]
Closing in favour of #14548 

The strategy in this PR has been abandoned as:
- sequences starting and ending are needlessly verbose
- sequences starting and ending were not being detected correctly when manually testing the following cases

```
# Read one symbol as: 1 dot
⠁
# Read two adjacent symbols as: start Unicode braille 1 dot 2 dot end Unicode braille
⠁⠂
# Read two symbols with spacing as: start Unicode braille 1 dot 2 dot end Unicode braille
⠁ ⠂
# Read a sentence with a mix of braille and text as: start Unicode braille 1 dot 2 dot foo 1 dot bar 1 dot 2 dot end Unicode braille
⠁⠂foo ⠁bar ⠁⠂
# Read a sentence with a mix of braille and text as: foo start Unicode braille 1 dot 2 dot bar 1 dot end Unicode braille lorem
foo ⠁ ⠂bar ⠂ lorem
```

**Pull request closed without merging**
