### PR TITLE
Create discord.py

### PR DESCRIPTION
**Pull request by signalsender103**
TODO: add support for [Discord](http://discordapp.com/) desktop client

### CODE REVIEW

**Comment by josephsl** [comment]
Hi, can we combine this with #7120 if possible please? Thanks.

**Comment by signalsender103** [comment]
I'm not sure how to combine them, could we just delete one of them so the other can be the only one to refer to? I created both of them by mistake; I couldn't find my proposed change in my own fork and now I realize why.

**Comment by josephsl** [comment]
Hi, whichever has more info, let’s use that and close the other. Thanks.

**Comment by signalsender103** [comment]
Ok, I'll close this one then.

**Pull request closed without merging**
