### PR TITLE
Appveyor improvements: Add a .pot translation template to NVDA CI

### PR DESCRIPTION
**Pull request by dpy013**
hi
Currently when appveyor builds NVDA, the default is to delete the .pot translation template.
### Link to issue number:
Resubmit
#10433 
### Summary of the issue:
It is recommended that nvaccess can Reserved the .pot translation template in appveyor, which can bring convenience to NVDA localization maintainers. If there is a new interface change, the translation maintainer can get the translation template in the first time and then perform the rehearsal test in the local community.
### Description of how this pull request fixes the issue:
First delete:
- del output\*.pot code
Then add:
Push-AppveyorArtifact "$Output\*.pot"
### Testing performed:
Already in the pr #10435 Did a test
### Known issues with pull request:
none
### Change log entry:
No need**
Section: Changes
thanks

### CODE REVIEW

**Comment by dingpengyu** [comment]
cc @feerrenrut

**Comment by dingpengyu** [comment]
cc @michaelDCurran and @feerrenrut 
Pr can be reviewed
thanks

**Comment by feerrenrut** [comment]
This seems fine to me, if you think it will help. However, I don't understand the use-case for it. Can you explain what your plan is with the `pot` file?

**Review by feerrenrut — APPROVED** [review]

**Comment by dingpengyu** [comment]
hi @feerrenrut It is recommended that nvaccess can Reserved the .pot translation template in appveyor, which can bring convenience to NVDA localization maintainers. If there is a new interface change, the translation maintainer can get the translation template in the first time and then perform the rehearsal test in the local community.
thanks

**Comment by dingpengyu** [comment]
The current pr allows the NVDA translation maintainer to obtain the translation template in advance. After obtaining the template, the translation maintainer can perform the translation test and preview in advance, so that the translation maintainer can directly put the translation result into the NVDA after the beta version is released.
Originally NVDA's appveyor defaults to removing the .pot translation template.
I added and removed the following code:
remove:
 - del output\*.pot
add:
     Push-AppveyorArtifact "$Output\*.pot"
The goal is to allow translators and maintainers to get the latest translation templates for testing and rehearsal in the first place.
thanks

**Comment by feerrenrut** [comment]
> so that the translation maintainer can directly put the translation result into the NVDA after the beta version is released.

I think this is fine.
Note: the text that requires translation can change many times during the alpha period. This may be difficult to manage. This is the reason that we use the beta branch as the base for translations. The beta branch has less changes.

**Pull request merged**
