### PR TITLE
Added a utils.urls module to manage and centralize URLs in NVDA, and to allow convenient patching by add-ons

### PR DESCRIPTION
**Pull request by XLTechie**
### Link to issue number:

Per a tangent discussion held in #14974

### Summary of the issue:

Add-ons needed to be able to easily patch the URL used for accessing the add-ons store assets. @seanbudd thought it appropriate to create a module in `utils`, dedicated to the task of centralizing and managing URLs.

### Description of user facing changes

If I've done it right, none.

### Description of development approach

* Added a new `util.urls` module, per discussion in #14974, as `utils/urls.py`.
* Added several URLs from various modules to `urls.py` as an initial test set.
* Replaced all of the URLs in the gui package with URLs entries.
* Added a deprecation warning for CHECK_URL in updateCheck.py, and used the appropriate URLs entry there.
* Used URLs entries in versionInfo.py

Can do more, the rest of the source in fact, but wanted to have @seanbudd look over the approach, to make sure I hadn't gone down an unexpected road with the way I did this. Though there aren't many more.

The module has the following features:

* Implements a singleton object of class URLManager, called URLs, which consumers are expected to use to manage all URLs in NVDA.
* Provides an `add` method which takes a handle string by which to identify the URL, the URL itself, and a flag to allow use of an insecure http URL instead of the otherwise required https URL.
* Provides a `divert` method, by which an add-on may change an already configured URL. Takes the same parameters as `add`, but requires the setting of a "reason", which is intended to briefly describe the purpose of the diversion for the log.
* Allows access of the form `URLs.handle`, where `handle` is the `add` or `divert` handle previously stored. Returns a string in as many contexts as possible.
* Attempts to prevent consumers from bypassing the `add`/`divert` methods, by storing data in a frozen `dataclass`. E.g. `URLs.nvAccess = "my.pirate.site"` will fail, for what that's worth. Mainly intended to prevent accidents.
* Logs the creation or diversion of URLs at debug level.
    + In the case of diversions, logs the reason, the caller, and the caller's file.
* Logs the access of URLs at info level, including whether they were diverted.

### Testing strategy:

* Checked that logs are correct.
* Tested the "NV Access Home Page" menu item.
* Diverted the NVA Home Page URL, and tested that it worked.
* In manual runs of this code, tested various error conditions and unexpected usages.

### Change log entries:

Bug fixes
For Developers
- All URLs in NVDA code are now managed through the `utils.urls.URLs` object, and are to be stored centrally in `source/utils/urls.py`. (#15073)
    - Add-ons can add their own URLs, or divert existing URLs (e.g. for proxying), by using methods of the `URLs` object.

### Code Review Checklist:

- [x] Pull Request description:
  - description is up to date
  - change log entries
- [x] Testing:
  - Unit tests
  - System (end to end) tests
  - Manual testing
- [X] API is compatible with existing add-ons.
- [x] Documentation:
  - User Documentation
  - Developer / Technical Documentation
  - Context sensitive help for GUI changes
- [X] UX of all users considered:
  - Speech 
  - Braille
  - Low Vision
  - Different web browsers
  - Localization in other languages / culture than English
- [x] Security precautions taken.

### CODE REVIEW

**Comment by seanbudd** [comment]
I'm a bit concerned with the implementation strategy here - is there a reason why the implementation structure like `WritePaths` wasn't used?
Is there a need to manually add `add/divert` methods - when monkeypatching could suffice?

**Comment by XLTechie** [comment]
Do we want to encourage monkeypatching when it isn't necessary? I thought we were moving to avoid that sort of thing, e.g. with extensionPoints, accessors for various properties, etc. I'll take a look at writePaths.

My thinking behind the add/divert concept was logging and security. If an add-on is patching a URL, that should be logged. Not only so there is a record of it happening, but so there is some hope of resolving conflicts (e.g. two add-ons altering the same URL, such as two different proxy add-ons running).

Also, it was the only way to prevent accidental use of http-only URLs without specific intent.

I was also thinking of add-ons adding their own internal URLs to this. Nothing is ever only used as originally intended.

**Comment by seanbudd** [comment]
I can understand the reasoning for the alternative approach, however I think there are some things missing which that structure supported and would be a nice to have.

- discoverability and typing of attributes. It would be ideal if you could read and write variables via `URLs.nvAccess = "example"` syntax, rather than `URLs.add("nvAccess", "example")`
- a shared base string for API endpoints using nvaccess.org so that all URLs using that domain can easily replace the source.
- other examples of inheritance - e.g. 
```py
urls.serverAPI = "nvaccess.org"
urls.addonStore = f"{urls.serverAPI}/addonStore/"
urls.addonStoreLocalised = f"{urls.addonStore}/{langCode}"
```

**Comment by XLTechie** [comment]
Thanks for the comments @seanbudd. I already developed a plan to refactor in 
a similar direction, but was awaiting your thoughts.

One thing that won't work in the "URLs.nvaccess =" structure, is supporting the 
flag-based blocking of http only URLs.

That is, I can either block all http URLs and require https URLs, or I can 
not enforce and just log a warning or some such for http URLs.

Which do you prefer?

**Comment by seanbudd** [comment]
I think it's fine if it's unenforced but logs at warning level

**Comment by cary-rowen** [comment]
Hi @XLTechie 

Does this PR fix the issue encountered in [this comment](https://github.com/nvaccess/nvda/issues/14974#issuecomment-1607164172)?

> Because "initializing addonStore data manager" happens before the addon system is initialized.

Thanks

**Comment by cary-rowen** [comment]
Hi @XLTechie 

Is there any progress?

Thanks

**Comment by seanbudd** [comment]
Closing as abandoned

**Pull request closed without merging**
