### PR TITLE
Windows 11 emoji panel: do not let NVDA assign arrow keys to search field scripts

### LINKED ISSUE #13104: new emoji panle on windos 11 isn't accessible for nvda.
new emoji panle on windos 11 isn't accessible with screen reader.
### Steps to reproduce:
1- load windos or any other app like notepad that you want to write some emojies.
2- press windos key +full stop .
3- press any key to navigate throo emojis.
### Actual behavior:
it is saying blank and you can not press enter on a emoji to write.
### Expected behavior:
it has to navigate throo emojis and read the emojis and when you press the enter key it has to write the emojis on the notepad or any other word processer that you are in.
### System configuration
 NVDA installed
instaled the beta version of nvda.
#### NVDA version:
nvda 2021.3 beta 2.
#### Windows version:
Windows 11 21H2 (x64) build 22000.348
#### Does the issue still occur after restarting your computer?
yes it does.
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
yes. it happens on every version of nvda.
#### If NVDA add-ons are disabled, is your problem still occurring?
yes.
#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
yes.
[nvda.log](https://github.com/nvaccess/nvda/files/7618575/nvda.log)

### PR DESCRIPTION
**Pull request by josephsl**
Hi,

If the approach is okay, please merge the PR.

### Link to issue number:
Closes #13104 

### Summary of the issue:
In Windows 11's emoji panel, users cannot use the arrow keys to navigate the emoji panel.

### Description of how this pull request fixes the issue:
Removes editable text field overlay class from emoji search field so arrow keys can be used to navigate the emoji panel, along with performing general lint.

### Testing strategy:
Manual testing on Windows 10 and 11 to make sure emoji panel is working with the PR applied, especially more so on Windows 11. System tests would be ideal for Windows 11, although Appveyor uses Windows Server 2019 image (limited to Windows 10 Version 1809 assumptions).

### Known issues with pull request:
None

### Change log entries:
Bug fixes:
```
- In Windows 11, NVDA will no longer prevent navigation in emoji panel when selecting emojis. (#13104)
```
Or a variation of that.

### Code Review Checklist:

- [x] Pull Request description:
  - description is up to date
  - change log entries
- [x] Testing:
  - Unit tests
  - System (end to end) tests
  - Manual testing
- [x] API is compatible with existing add-ons.
- [x] Documentation:
  - User Documentation
  - Developer / Technical Documentation
  - Context sensitive help for GUI changes
- [x] UX of all users considered:
  - Speech 
  - Braille
  - Low Vision
  - Different web browsers
  - Localization in other languages / culture than English

### Additional context:
I'm sure there is something better than removing editable text overlay class, and if there is, do let us now so it can be incorporated.

Thanks.

### CODE REVIEW

**Comment by alireza1385mamani** [comment]
it is Ok. I think that it is OK.

**Review by LeonarddeR — APPROVED** [review]

**Review by seanbudd — APPROVED** [review]

**Comment by josephsl** [comment]
@seanbudd, ping, milestone update please i.e. when do you expect this will be merged into master. Thanks.

**Review by feerrenrut — APPROVED** [review]
Looks good to me. @seanbudd is there any reason not to merge?

**Comment by seanbudd** [comment]
@feerrenrut  - no, I was just not requested as the original reviewer. merging now

**Pull request merged**
