### PR TITLE
Only show dev channel add-ons for pre-release NVDA

### LINKED ISSUE #15: Add support for pre-release NVDA
When using a prerelease copy of NVDA (from source, alpha, beta, rc, or try builds) there is no available endpoint for add-on listings, resulting in an error. For prototype purposes, the version used has been hard coded see PR: [Add-on store](https://github.com/nvaccess/nvda/pull/13985) #13985

Endpoints are available for each of the transforms based on the [set of available releases](https://github.com/nvaccess/addon-datastore-transform/blob/main/nvdaAPIVersions.json), however, by definition a pre-release version of NVDA is not going to be available in that list. Instead, a "latest" transform should be added.

Combining this 'latest' endpoint with: [Allow 'dev' version of add-on](https://github.com/nvaccess/addon-datastore/issues/40)
 #40 ensures that all combinations of stable and pre-release are supported for both add-ons and NVDA:

### Stable NVDA
NVDA has been released final and has been published as a release.
Stable NVDA builds will access the API version specific endpoint.
#### Stable add-on
This is the standard case. Stable add-ons are offered to users of stable NVDA as long as they are compatible.
#### Beta add-on
Allows add-on authors to target a stable NVDA release and get feedback from early adopter users before publishing add-on as stable. 
#### Dev add-on
Not offered when to users of stable NVDA.

### Pre-release NVDA
alpha, beta, rc, try, or dev builds
These builds will access the "latest" endpoint.
#### Stable add-on
Add-on is presented as long as the API backwards compatible to has not been updated in this version of NVDA.
This allows NVDA developers/testers using pre-release NVDA versions to use the add-ons they usually use.
#### Beta add-on
Add-on is presented as long as the API backwards compatible to has not been updated in this version of NVDA.
This allows NVDA developers/testers using pre-release NVDA versions to use the add-ons they usually use.
#### Dev add-on
A special add-on channel for developing add-ons against the newest unreleased additions to NVDA, or to stay up to date with compatibility breaking changes. 

- "compatible" means add-ons are only to be offered if there is overlap in API support (I.E. manifest and supported API range suggests the add-on is expected to be compatible with NVDA).
- This means that source copies for old NVDA versions may not have compatible add-ons. This is another issue, which could be solved by accessing the API version specific endpoint for the NVDA version the source copy was going to become.

### How should latest be created:
For add-on ID X, the first submission should be taken when the submissions are ordered by:
1. Last tested addon API: the most recently tested add-on API version should be preferred.
2. Addon-version number: later add-on version numbers should be preferred.
3. Stable > beta > dev : if an add-on author promotes a dev version to beta or stable, those should be preferred. Note the implicit (filesystem) constraint applied by the add-on datastore prevents two submissions that have equal ID and version number. This last ordering is only theoretical. If this raises the question of "why have a dev channel?", remember that it allows the validation step to API compatibility constraints.

### PR DESCRIPTION
**Pull request by seanbudd**
### Link to issue number:
Closes https://github.com/nvaccess/addon-datastore-transform/issues/15

### Summary of the issue:
The "dev" channel is designed to be used for pre-release versions of NVDA only, and allow installation to incompatible API versions.

### Description of user facing changes
Makes "dev" channel add-ons always compatible with pre-release versions of NVDA
Filters incompatible add-ons from the add-on store.
For stable NVDA releases:
 - this removes dev versions
For NVDA pre-releases:
 - this removes unsupported stable and beta versions, and shows dev versions.

### Description of development approach
Check the channel when checking addon compatibility.

filter compatible add-on versions in the main view of the store.

### Testing strategy:
Test add-on store views for stable and pre-release NVDA, by changing `buildVersion`

### Known issues with pull request:
None

### Change log entries:
None

### Code Review Checklist:

- [x] Pull Request description:
  - description is up to date
  - change log entries
- [x] Testing:
  - Unit tests
  - System (end to end) tests
  - Manual testing
- [x] API is compatible with existing add-ons.
- [x] Documentation:
  - User Documentation
  - Developer / Technical Documentation
  - Context sensitive help for GUI changes
- [x] UX of all users considered:
  - Speech 
  - Braille
  - Low Vision
  - Different web browsers
  - Localization in other languages / culture than English
- [x] Security precautions taken.

### CODE REVIEW

**Comment by XLTechie** [comment]
@seanbudd
> For stable NVDA releases:
>
>  *  this removes dev versions

Do I understand correctly, that for add-on developers who currently release new 
features in dev versions, so that adventurous users can download and test these 
in stable NVDA: stable NVDA users will not have access to these through 
the store, even if the dev versions are in the store?

(I.e. such developers will need to devise an alternative distribution mechanism, 
such as direct GitHub downloads)

If that is the case, may I suggest a feature flag or something to turn this back 
on, for users who want it?

**Comment by seanbudd** [comment]
>Do I understand correctly, that for add-on developers who currently
release new
features in dev versions, so that adventurous users can download and test
these
in stable NVDA

This case you describe is what the beta channel is for.

We plan to allow channel selection in a future PR (to allow opting into
dev, opting out of stable/beta, etc)

**Comment by CyrilleB79** [comment]
Is there an impact for legacy add-ons, i.e. the ones migrated from addonFiles to addon-datastore? For some of them, the dev channel was used as what is now called beta channel in the add-on store.

More general note:
With the add-on store some terms have slightly changed their meaning with respect to what was used in the add-on community and on the [NVDA Community Add-ons website](https://addons.nvda-project.org/index.en.html):
* "legacy":
  * community website: add-ons declared end-of-life or not compatible with last NVDA version
  * add-on store: add-ons that were migrated from addonFiles to addon-dataStore
* "dev channel":
  * community website: a channel for early adopters; this covers both the new beta and dev channels of the add-on store
  * add-on datastore: a channel for add-ons working with alpha version of NVDA even when API-breaking NVDA release dev cycle is on-going

**Comment by Brian1Gaff** [comment]
Yes this seems to be reinventing the wheel to me. For example, systray list 
add on has just got a new test version and the author wants it tested on 
older Windows versions. Just as well as it fails to initialise at all on 
Windows 7. Many add on authors wish to support things that NVDA newer 
versions do not, and this seems to be complicating it all a bit.
 Brian

-- 
***@***.***
Sent via blueyonder.(Virgin media)
Please address personal E-mail to:-
***@***.***, putting 'Brian Gaff'
in the display name field.
----- Original Message -----

**Comment by seanbudd** [comment]
We've decided to close this, in favour of allowing any add-on version compatibility check to be manually overwritten.
This covers the use-case of testing unreleased breaking API changes, that the dev channel was intended for.

The documentation proposed in https://github.com/nvaccess/addon-datastore/pull/109 has been updated to match this.

**Pull request closed without merging**
