### PR TITLE
Language handler: use kernel32.dll function, add Kurdish language support

### PR DESCRIPTION
**Pull request by josephsl**
### Link to issue number:
#8488, #8489, #8490

### Summary of the issue:
Updates language handler to use kernel32 function, remove LCID's supported on Windows 7 and later as they are included by default, add Kurdish language support.

### Description of how this pull request fixes the issue:
Updates language handler:

* Uses kernel32.dll function for obtaining LCID's.
* Removes our definition of certain LCID's as Windows 7 ships with them.
* Adds Kurdish family of languages.

### Testing performed:
Tested on Windows 7, 8.1 and 10, along with adding Kurdish locale files.

### Known issues with pull request:
None

### Change log entry:
None (for now as Kurdish language files are not really ready yet).

Thanks.

### CODE REVIEW

**Comment by michaelDCurran** [comment]
Were you able to test that all the LCIDs we used to have listed really 
are supported on Windows 7?

**Comment by josephsl** [comment]
Hi,

Yes:

1. Nepali: supported on Windows 7.
2. Latin Serbian: supported on Windows 7.
3. Arabic: supported on Windows 7.
4. Aragonese: see #6259.

I believe those are the LCID's that were not supported on older releases. If I recall correctly, these were added specifically for Windows XP users way back in 2013.

Thanks.

**Comment by josephsl** [comment]
Hi,

Forgot to add Amharic, which is also supported on Windows 7.

Thanks.

**Review by michaelDCurran — APPROVED** [review]

**Comment by leonardder** [comment]
@josephsl: Could you please close the associated issues by hand that can be closed because of the merge of this pr?

**Comment by josephsl** [comment]
Hi, sure, will take care of that in just a second. Thanks.

**Pull request merged**
