### PR TITLE
Move is64BitProcess out of appModuleHandler to work around wrong assumptions in syslistview32

### PR DESCRIPTION
**Pull request by LeonarddeR**
### Link to issue number:
None

### Summary of the issue:
In some situations, appModule.is64BitProcess returns True even though the process itself is 32 bit. This happens in cases where the processHandle on the app module is 0, i.e. because the call to openProcess fails.
I've been able to reproduce this in the [Rohitab API Monitor software](http://rohitab.com/apimonitor). This software contains sysliestview32 controls which aren't read properly due to this.

### Description of how this pull request fixes the issue:
1. Move all the logic from AppModuleHandler.AppModule._get_is64BitProcess to a convenience wrapper in winKernel. This wrapper raises errors instead of returning False when there is something wrong. This wrapper is now called by _get_is64BitProcess
2. IN the syslistview32 code, rather than getting is64bit process from the appModule, it now retrieves this information using the new wrapper and the processHandle on the object itself, that is retrieved using oleac.
3. is64BitProcess on appModules is now set to False instead of True in the case that the process handle is 0. This behaviour is more in line with how we handle cases where calling IsWOW64Process fails

### Testing performed:
Tested in the Rohitab API Monitor software that the list of processes reads fine.

### Known issues with pull request:
1. For syslistview32, using the is64BitProcess property on the appModule had the advantage of calling IsWOW64Process only once, where as now, it is called for every initialization of the overlay class. I don't think that this would cause serious performance regression though.
2. I wonder whether we could do anything about the way we now get the process handle for app modules.
3. I don't know whether there ever is a process with a handle of 0. I assumed there isn't, but I expected IsWOW64Process to fail for a 0 process handle, which it doesn't.

### Change log entry:
* Bug fixes
    + NVDA now properly reads the contents of list views in Rohitab API Monitor.

### CODE REVIEW

**Comment by leonardder** [comment]
@jcsteh: I requested your review since you were the one who last touched this code, feel free to ignore if you prefer, though.

**Comment by jcsteh** [comment]
> 2. I wonder whether we could do anything about the way we now get the process handle for app modules.

It occurs to me that we almost always have an HWND when we want to create an AppModule. There are two places that call appModuleHandler.update:

1. IAccessibleHandler, where we definitely have an HWND.
2. NVDAHelper. I can't quite remember how this works, but I think it's possible for NVDAHelper to create an AppModule before IAccessibleHandler does. In that case, we might not have an HWND (but maybe we actually do, because nvdaHelperRemote injects based on win events?). Even if we don't, NVDA could eventually update this itself.

In that case, we could just call oleacc.GetProcessHandleFromHwnd and use that for the AppModule's processHandle. That would eliminate the confusion between the two types of processHandle and would mean sysListView32 can happily rely on appModule.is64BitProcess as it does now.

> 3. I don't know whether there ever is a process with a handle of 0. I assumed there isn't, but I expected IsWOW64Process to fail for a 0 process handle, which it doesn't.

Task Manager calls process id 0 "system idle process". So, perhaps it has some internal significance, but there's no "real" process with id 0.

**Comment by leonardder** [comment]
@jcsteh wrote:

> It occurs to me that we almost always have an HWND when we want to create an AppModule. There are two places that call appModuleHandler.update:
> 
>     1. IAccessibleHandler, where we definitely have an HWND.
> 
>     2. NVDAHelper. I can't quite remember how this works, but I think it's possible for NVDAHelper to create an AppModule before IAccessibleHandler does. In that case, we might not have an HWND (but maybe we actually do, because nvdaHelperRemote injects based on win events?). Even if we don't, NVDA could eventually update this itself.
> 
> 
> In that case, we could just call oleacc.GetProcessHandleFromHwnd and use that for the AppModule's processHandle. That would eliminate the confusion between the two types of processHandle and would mean sysListView32 can happily rely on appModule.is64BitProcess as it does now.

GetProcessHandleFromHwnd returns a process handle as follows:

> The returned handle has the following privileges: PROCESS_DUP_HANDLE | PROCESS_VM_OPERATION | PROCESS_VM_READ | PROCESS_VM_WRITE | SYNCHRONIZE.

NVDA opens a process as follows:

> `self.processHandle=winKernel.openProcess(winKernel.SYNCHRONIZE|winKernel.PROCESS_QUERY_INFORMATION,False,processID)`

So, these access rights differ, particularly regarding querying information. I think this might be problematic at some point when used on appModules.

**Comment by jcsteh** [comment]
Ah. I didn't realise the olacc function didn't give us
PROCESS_QUERY_INFORMATION. That's irritating.

**Comment by leonardder** [comment]
@michaelDCurran I think this is ready for review now. I'm afraid I can't address @jcsteh's suggestion in https://github.com/nvaccess/nvda/pull/9221#issuecomment-459501856

**Comment by leonardder** [comment]
Currently, I no longer use the application with which I could reproduce this. I'm happy to fix small review comments if any, but if there's anything major required to bring this further, I'm afraid I won't be able to contribute them any time soon.

**Comment by Adriani90** [comment]
cc: @Robert-J-H

**Comment by leonardder** [comment]
This has been open for over a year now. I'm closing this to clean up. Happy for anyone to take over or reopen.

**Pull request closed without merging**
