### PR TITLE
Build the NVDA Controller client zip archive for release builds

### PR DESCRIPTION
**Pull request by LeonarddeR**
### Link to issue number:
None

### Description of pull request
The NVDA Controller client library is currently not build automatically. Even though the controller client itself hasn't been updated for ages, the build environment has changed over time. This pr, although very low on the priority list, intends to ensure automatic publication of the most recent controller client.

### Testing performed:
Ran scons client locally, this properly resulted in a zip archive containing the controller code.

### Known issues with pull request:
None

### Change log entry:
None

### CODE REVIEW

**Comment by derekriemer** [comment]
Will this cause appVeyor to publish this to NV Access's website somehow? If not, should we handle this now?

**Comment by leonardder** [comment]
[**@derekriemer**](https://github.com/derekriemer) commented on [10 Apr 2018, 16:43 CEST](https://github.com/nvaccess/nvda/pull/8159#issuecomment-380126547 "2018-04-10T14:43:23Z - Replied by Github Reply Comments"):
> Will this cause appVeyor to publish this to NV Access's website somehow? If not, should we handle this now?

It looks like all appveyor release artifacts end up at nvaccess.org somehow, but either @jcsteh or @michaeldcurran might be able to tell more about that.

**Review by feerrenrut — APPROVED** [review]
I'll merge this straight to master, I don't think the regular incubation period makes sense here.  We can look at how this can be automatically published later, at least this way there is a regular build available.

**Comment by feerrenrut** [comment]
@michaelDCurran FYI

**Comment by jcsteh** [comment]
Changes in the build environment really shouldn't affect the controller client, since it just uses RPC. The only thing that would affect the controller client in any practical sense are changes to the idl interfaces or the client bootstrap code (or changes to MSRPC, but that isn't going to happen).

I guess it does no harm to publish new builds, but my concern is that consumers will feel the need to update regularly when there's no actual change. It also means we have to find a way to dynamically update the download link for every release, which is painful. More on that below.

[**@derekriemer**](https://github.com/derekriemer) commented on [Apr 11, 2018, 12:43 AM GMT+10](https://github.com/nvaccess/nvda/pull/8159#issuecomment-380126547 "2018-04-10T14:43:23Z - Replied by Github Reply Comments"):
> Will this cause appVeyor to publish this to NV Access's website somehow? If not, should we handle this now?

No. I'm not convinced the main nvaccess.org site is the right place for this; there's no place for developer centric stuff there. I guess we could have a separate site (subdirectory or subdomain) for developer stuff like this and the dev docs. That would require new code on the server, though.

[**@leonardder**](https://github.com/leonardder) commented on [Apr 11, 2018, 3:05 AM GMT+10](https://github.com/nvaccess/nvda/pull/8159#issuecomment-380175769 "2018-04-10T17:05:16Z - Replied by Github Reply Comments"):
> It looks like all appveyor release artifacts end up at nvaccess.org somehow

No, only the NVDA build itself, the changes document, and, for a final release, the User Guide and Developer Guide. The two guides aren't kept in a version specific directory; those two files are just overwritten, since they're linked from the main site and must always be the latest version. I guess we could modify the AppVeyor hook and release script to stage fetch and deploy the controller client as well, but it'd also have to auto generate a page with links to the right files.

**Comment by leonardder** [comment]
[**@jcsteh**](https://github.com/jcsteh) commented on [11 apr. 2018 12:12 CEST](https://github.com/nvaccess/nvda/pull/8159#issuecomment-380400734 "2018-04-11T10:12:09Z - Replied by Github Reply Comments"):
> Changes in the build environment really shouldn't affect the controller client, since it just uses RPC. 

How about the recent drop of XP and Vista support, which included a subsystem change? I know it will not have any user visible impact on the code, but I assume there will be some obtimisations in current builds that weren't in old ones.

> The two guides aren't kept in a version specific directory; those two files are just overwritten, since they're linked from the main site and must always be the latest version. I guess we could modify the AppVeyor hook and release script to stage fetch and deploy the controller client as well, but it'd also have to auto generate a page with links to the right files.

I assume that it will be sufficient to have one url that is always up to date, similar to the guides? Then link to that URL from the controller client readme in the source tree.

**Comment by jcsteh** [comment]
[**@leonardder**](https://github.com/leonardder) commented on [Apr 11, 2018, 8:26 PM GMT+10](https://github.com/nvaccess/nvda/pull/8159#issuecomment-380404405 "2018-04-11T10:26:48Z - Replied by Github Reply Comments"):
> How about the recent drop of XP and Vista support, which included a subsystem and sdk change? I know it will not have any user visible impact on the code, but I assume there will be some obtimisations in current builds that weren't in old ones.

In theory, yes, but because all this is doing is calling some remote RPC functions (and the real work gets done in the server), I'll wager optimisations don't even come into the picture... and if they do, the impact would be super negligible.

> I assume that it will be sufficient to have one url that is always up to date, similar to the guides? Then link to that URL from the controller client readme in the source tree.

We could do that, but that would mean the version number isn't included in the archive file name at all, which probably isn't great for a download like this. (In contrast, the guides are intended for reading online.)

**Pull request merged**
