### PR TITLE
Revert search history

### LINKED ISSUE #9954: Search history of NVDA find dialog does not handle Escape correctly when using Japanese IME
### Steps to reproduce:

1. start NVDA and Internet Explorer
2. make sure NVDA is in browse mode
3. press NVDA+Ctrl+F and open search dialog of NVDA
4. enable Japanese IME. editing of reading string starts.
5. type Latin characters, such as: t e s u t o
6. press Escape key, instead of IME translation key

### Actual behavior:

Search dialog closes.

### Expected behavior:

The reading string of IME is cleared.
Search dialog should not close.

#### NVDA installed/portable/running from source:

installer

#### NVDA version:

nvda_snapshot_beta-18133,b29acb42

#### Windows version:

Windows 10 version 1903 (Japanese)

#### Have you tried any other versions of NVDA? If so, please report their behaviors.

2019.1.1 works as expected.

We believe it is related to #8482

### PR DESCRIPTION
**Pull request by josephsl**
### Link to issue number:
Fixes #9954 

### Summary of the issue:
Search history combo box does not handle input method editor windows correctly, affecting languages such as Chinese, Japanese, Korean and others.

### Description of how this pull request fixes the issue:
Reverts the mechanics of search history.

### Testing performed:
Tested to make sure find dialog works as expected.

### Known issues with pull request:
Many languages will require editing user documentation and what's new documents.

### Change log entry:
None

### Follow-up notes:
First, contact wxWidgets and/or wxPython developers to see if it is specific to older wxWidgets releases. If this is fixed in wxPython 4.1.0 (wxWidgets 3.1.x), hold off on adding search history combo box until NVDA is powered by wxPython 4.1.0; otherwise, look for a suitable solution, and then restore search history with the pull request based on master/Python 3.

Thanks.

### CODE REVIEW

**Comment by josephsl** [comment]
Hi,

For @Nishimotz, once the PR build is compiled, can you test to make sure things are back to what it was before? I can confirm that this is resolved for me when I use Korean IME.

Thanks.

**Comment by Cleversn** [comment]
Hi, is there any hope this feature is implemented again by other means in the future? Was quite useful...

**Comment by josephsl** [comment]
Hi, provided that we come up with something that allows searching in other languages, then yes. Thanks.

**Comment by nishimotz** [comment]
Thank you.
Tested nvda_snapshot_pr9993-18230,3c295cc4.exe.
It resolves #9954, i.e., search edit can handle Escape as expected when Japanese IME is used.

**Comment by josephsl** [comment]
Hi, so this proves that we do need to talk to wxWidgets/wxPython developers in regards to why combo boxes do not support IME window correctly. Thanks.

**Comment by leonardder** [comment]
Unfortunately, this feature is the first listed feature in the new features list, so it might be a bit confusing when it is removed without translations being updated. Could we do something about this?

**Comment by josephsl** [comment]
Hi, this is one of the reasons why I originally proposed doing it as part of 2019.2.1. I’ll wait for Reef’s reply before proceeding. Thanks.

**Comment by feerrenrut** [comment]
We will delay the 2019.2 release to fix this issue:
- I have tried replacing the combo box with wx.SearchCtrl (see branch [useSearchCtrl](https://github.com/nvaccess/nvda/tree/useSearchCtrl)), however there is no way to activate the menu using the keyboard, and I could not find a work around. I have created an [issue on wxWidgets trac](https://trac.wxwidgets.org/ticket/18457).
- A minor release will consume more of our time, and have the unwelcome outcome that this search feature is first added then removed.
- There are no in code translation changes when reverting this feature.
- Translated user guides and changes files will need updates.

For the userguide and changes file, we might be able to achieve an acceptable outcome by manually deleting the sections added from each of the xx/changes.t2t and xx/userguide.t2t files. @josephsl what is your opinion of this idea, would this allow us to avoid waiting for another translation freeze period?

**Comment by josephsl** [comment]
Hi, I’ll inform translators and see if we can get this propagated by this weekend. Changes file is easy, but the user guide may need more work. Thanks.

**Comment by leonardder** [comment]
couldn't we manually treat the escape key when the control has focus?

**Comment by josephsl** [comment]
Hi, perhaps. Note that this affects wxPython 4.1.0 as well, so it might be something we have to write a workaround or ask wxPython people to resolve this. Thanks.

**Comment by feerrenrut** [comment]
> couldn't we manually treat the escape key when the control has focus?

This would make it pretty annoying to cancel the search dialog, and still may not actually result in IME getting the escape.

@josephsl Are you saying that it will cause a problem for the translation system if we just manually remove these new sections? Since they are self contained sections, I think we can just delete them from all the translated files.

**Comment by josephsl** [comment]
Hi, at least for what’s new, it is possible. Note that when the original PR was submitted it moved things around in the user guide, hence my initial difficulty reverting it. Thanks.

**Comment by zstanecic** [comment]
Hi Reef and Joseph,

I advice the following

Give this to translators and let’s do a short five-day freeze.

**Review by feerrenrut — APPROVED** [review]
Thanks @josephsl

**Pull request merged**
