### PR TITLE
Vertical QuickNav

### LINKED ISSUE #15999: Feature request: add QuickNav command for Vertical navigation in browse mode
I propose to add  Vertical navigation QuickNav command to NVDA.  I I will implement this feature request myself if green light is given by NVDA team.
* We define vertical navigation to be jumping to next or previous paragraph, which is  vertically aligned visually with the current paragraph, that is their `x` coordinate is exactly the same.
* This can be useful on websites that visually display data as a table, but for whatever reason NVDA doesn't see the table. This command can be used to navigate to next/previous cell in the same column.
* A good example of this is [issues list on github](https://github.com/nvaccess/nvda/issues/) - with this feature users will be able to find the first issue and then navigate between issues in the list using vertical navigation with a single keystroke.
* I propose to assign by default  Left bracket `[` and `Shift+[` gestures to this command.
* This feature has already been implemented in [BrowserNav add-on](https://addons.nvda-project.org/addons/browsernav.en.html) and by default assigned to `NVDA+Control+Up/Down` gestures.

### PR DESCRIPTION
**Pull request by mltony**
### Link to issue number:
Fixes #15999
### Summary of the issue:
Feature request: QuickNav command for Vertical navigation 
### Description of user facing changes
Added new unassigned QuickNav command that jumps to previous/next vertically aligned paragraph.
### Description of development approach
Making use of `_iterSimilarParagraph` function and passing a lambda that extracts `x` coordinate of a paragraph.
### Testing strategy:
* Tested in Chrome; Firefox
* Tested in MSWord
### Known issues with pull request:
N/A
### Code Review Checklist:

- [x] Documentation:
  - Change log entry
  - User Documentation
  - Developer / Technical Documentation
  - Context sensitive help for GUI changes
- [x] Testing:
  - Unit tests
  - System (end to end) tests
  - Manual testing
- [x] UX of all users considered:
  - Speech 
  - Braille
  - Low Vision
  - Different web browsers
  - Localization in other languages / culture than English
- [x] API is compatible with existing add-ons.
- [x] Security precautions taken.

### CODE REVIEW

**Comment by amirsol81** [comment]
@mltony Thanks for incorporating this into the project! Just a question: do you have any plans to also incorporate your awesome bookmarking feature from BrowserNav into NVDA? This is a killer and powerful BrowserNav facility.

**Comment by mltony** [comment]
@amirsol81 , not at this time. Even if I aim at including only one type of bookmarks, I estimate it'll take me probably at least 2 months to do it - I don't have this much time now. And also this would be subject to NVAccess approval. I plan to maintain BrowserNav for the time being - will soon update it to be compatible with NVDA v2024. But thanks for showing your interest!

**Comment by amirsol81** [comment]
Thanks @mltony for offering extremely powerful add-ons like BrowserNav. It makes life much easier on the web and its bookmarking facility is a huge boon to NVDA users.

**Review by seanbudd — APPROVED** [review]
Thanks @mltony !

**Pull request merged**
