### PR TITLE
User Guide: Indicate incompatibility of screen curtain with inverted colors in the Magnifier

### LINKED ISSUE #10545: Error at screen curtain activation when Windows Magnifier is active
### Steps to reproduce:

* Launch Windows Magnifier (Windows+PavNumPlus)
* Alt+Tab to Magnifier window
* Press "Display" button and select "Full screen" option
* Press "Options" button and check the "Invert colors" checkbox
* Open Vision panel in NVDA settings
* Uncheck the "Always show a warning" checkbox (probably does not matter but I did this way)
* Check the "Enable screen curtain" checkbox

### Actual behavior:

* Screen curtain is not enabled
* an error beep is heard: cf. [logWinMagnifier+ScreenCurtain.txt](https://github.com/nvaccess/nvda/files/3886970/logWinMagnifier%2BScreenCurtain.txt)
* a message box indicating"Could not load the Screen Curtain vision enhancement provider" appears.

### Expected behavior:

* Best choice: screen curtain is enabled and the screen becomes black
* Mid choice: screen curtain is enabled, but the screen is white due to color inversion of the magnifier
* Minimal choice: screen curtain cannot be activated, no error appears in the log and the message explains to the user why screen curtain cannot be activated

### Other tests performed

* Test 2: Windows Magnifier with normal colors + screen curtain: no error, the screen becomes black
* Test 3: Zoomtext 11 (normal colors) + screen curtain: no error, the screen becomes black
* Test 4: Zoomtext 11 (inverted colors) + screen curtain: no error, the screen becomes white
* Test 5:
  * Start Windows Magnifier with normal colors
  * Activate screen curtain: no error, screen black
  * Invert Windows Magnifier colors: no error, the screen remains black (so this seems possible...)

#### NVDA installed/portable/running from source:
From source

#### NVDA version:

Version : source-master-c750926
(last version)

#### Windows version:

Windows 10 1709

#### Name and version of other software in use when reproducing the issue:

For test 1: none.
For some other tests: Zoomtext 11

#### Does the issue still occur after restarting your PC?

Yes

#### Have you tried any other versions of NVDA? If so, please report their behaviors.

No other stable version.
I have already seen this issue few time after the screen curtain was merged into alpha but did not bother to fill an issue at the time. I do not remember however the version of the alpha in which I have already seen the issue.

### PR DESCRIPTION
**Pull request by CyrilleB79**
### Link to issue number:
Partial fix for #10545
### Summary of the issue:
Screen curtain cannot be activated while Windows Magnifier is running with inverted screen colors.
An error message can be heard when trying to activate the screen curtain.
Though, this incompatibility is not documented in the User Guide.

### Description of user facing changes
Update the User Guide.
### Description of development approach
N/A
### Testing strategy:
Check User Guide.
### Known issues with pull request:
None
### Code Review Checklist:

- [x] Documentation:
  - Change log entry
  - User Documentation
  - Developer / Technical Documentation
  - Context sensitive help for GUI changes
- [x] Testing:
  - Unit tests
  - System (end to end) tests
  - Manual testing
- [x] UX of all users considered:
  - Speech 
  - Braille
  - Low Vision
  - Different web browsers
  - Localization in other languages / culture than English
- [x] API is compatible with existing add-ons.
- [x] Security precautions taken.

### CODE REVIEW

**Comment by seanbudd** [comment]
I don't think this should close #10545. While its good to document this behaviour, I think #12701 is needed to close #10545. Thoughts?

**Review by seanbudd — APPROVED** [review]

**Comment by seanbudd** [comment]
Is there a UX message or just an error sound when screen curtain fails to activate?

**Comment by Qchristensen** [comment]
When trying to enable screen curtain with Magnifier on (windows+numpad plus) and set to invert colours (control+alt+i), NVDA speaks "Could not enable screen curtain".  No error dialog is presented.  The follow log fragment is generated:

IO - inputCore.InputManager.executeGesture (11:42:00.359) - winInputHook (14740):
Input: kb(desktop):control+NVDA+escape
DEBUG - visionEnhancementProviders.screenCurtain.ScreenCurtainProvider.__init__ (11:42:00.361) - MainThread (5216):
Starting ScreenCurtain
WARNING - vision.visionHandler.VisionHandler.initializeProvider (11:42:00.361) - MainThread (5216):
Error initialising screenCurtain. Disabling in config.
ERROR - globalCommands._enableScreenCurtain (11:42:00.361) - MainThread (5216):
Screen curtain initialization error
Traceback (most recent call last):
  File "globalCommands.pyc", line 4332, in _enableScreenCurtain
  File "vision\visionHandler.pyc", line 261, in initializeProvider
  File "vision\visionHandler.pyc", line 256, in initializeProvider
  File "visionEnhancementProviders\screenCurtain.pyc", line 354, in __init__
  File "visionEnhancementProviders\screenCurtain.pyc", line 350, in __init__
  File "visionEnhancementProviders\screenCurtain.pyc", line 42, in _errCheck
OSError: [WinError 87] The parameter is incorrect.
IO - speech.speech.speak (11:42:00.378) - MainThread (5216):
Speaking [LangChangeCommand ('en_GB'), 'Could not enable screen curtain']

**Review by Qchristensen — APPROVED** [review]
User guide text reads well

**Comment by CyrilleB79** [comment]
There are 4 ways to activate screen curtain:
- using the gesture (now `NVDA+control+escape`): a `ui.message` reports "Could not enable screen curtain"
- checking the checkbox in Vision settings: an error dialog box is displayed
- triggered by profile switching: nothing is reported; only error ding can be heard in test builds
- when starting NVDA: nothing is reported; only error ding can be heard in test builds

I agree that #10545 should remain open until something is reported in these four cases. #12701  may be a solution but another solution based on error catching in the two last cases is also acceptable IMO; What do you think?

In any case, I have updated the initial description to remove the auto-closing word so that the documentation update can already be merged.

**Pull request merged**
