### PR TITLE
Run the uninstaller with administrator privileges

### PR DESCRIPTION
**Pull request by wmhn1872265132**
### Link to issue number:
none

### Summary of the issue:
NVDA cannot be uninstalled correctly by directly running `"%ProgramFiles(x86)%\NVDA\uninstall.exe"`. You must run it as an administrator to uninstall it correctly.

### Description of user facing changes
You can directly run `"%ProgramFiles(x86)%\NVDA\uninstall.exe"` to uninstall NVDA

### Description of development approach
Change `RequestExecutionLevel` to `admin`

### Testing strategy:
Manually run `"%ProgramFiles(x86)%\NVDA\uninstall.exe"`, the uninstaller should correctly apply for administrator rights and uninstall NVDA

### Known issues with pull request:
The portable version of NVDA's `uninstall.exe` will also apply for administrator rights when running.

### Code Review Checklist:

- [x] Documentation:
  - Change log entry
  - User Documentation
  - Developer / Technical Documentation
  - Context sensitive help for GUI changes
- [x] Testing:
  - Unit tests
  - System (end to end) tests
  - Manual testing
- [x] UX of all users considered:
  - Speech 
  - Braille
  - Low Vision
  - Different web browsers
  - Localization in other languages / culture than English
- [x] API is compatible with existing add-ons.
- [x] Security precautions taken.

### CODE REVIEW

**Review by seanbudd — APPROVED** [review]

**Comment by seanbudd** [comment]
>The portable version of NVDA's uninstall.exe will also apply for administrator rights when running.

I think that's okay. I assume that tool is used to uninstall NVDA from a computer, not delete the portable copy. A portable copy cannot be installed or uninstalled

**Comment by seanbudd** [comment]
I'm reverting this PR as it makes admin permissions required to generate the uninstaller. I don't believe this is setup correctly.
The installer doesn't require this and uses `RequestExecutionLevel user`.

Please file an issue first describing the problem you are facing, as generally the uninstaller works for me and requests admin level.

**Comment by michaelDCurran** [comment]
It seems that When running the uninstaller from control panel / programs and features, or Windows Settings -> Apps -> installed apps: Windows automatically elevates the uninstaller. I.e. I get a UAC screen each time.
However, when running uninstall.exe directly from c:\program files (x86)\nvda, for instance using File Explorer, the uninstaller ls launched with no UAC elevation.
I would not think it is a very likely / supported pattern to run it directly. Generally people should use the installed apps / programs and features UI.

**Comment by michaelDCurran** [comment]
Good point.

Yes, we should either remove that shortcut, or change it to use the 
shell to request elevation.

**Comment by wmhn1872265132** [comment]
In addition, I really don’t think that running the uninstall program directly should not be supported, unless the program is invisible to the user, otherwise there should be no position to prevent the user from doing this.

**Comment by seanbudd** [comment]
Please open a new issue for the shortcut bug

**Pull request merged**
