### PR TITLE
Fixes in the change log for NVDA 2022.2

### PR DESCRIPTION
**Pull request by CyrilleB79**
### Context
When checking the change log translation, I have found a wrong reference in an item of the change log. I have thus checked all the refs for 2022.2.

### Link to issue number:
None
Follow-up of various issues.

### Summary of the issue:
Some of the GitHub references in the change log were targetting wrong issue or PR.

### Description of user facing changes
The references have been fixed in the change log document.

### Description of development approach
Fixed the following references:
* #13386 replaced by #13383
* #13508 replaced by #13506 
* #13386 (bis) replaced by #13688

Also, I have replaced #13276 (Libre Office issue) by #13277 (associated PR) since the issue description is not related at all with the change for developers.

### Testing strategy:

Manual test: Check each change log item in the change log generated by appVeyor in this PR.

### Known issues with pull request:
I have also found some PR refs even if there are associated issues. The rule is usually to reference the issue when there is one. But I have not bothered to fix it since it is easy to find the issue when you have the PR.

## Additional note:
* There have been 3 wrong references in the 2022.2 dev cycle. Maybe a checkof the ref  should be added in NVAccess' protocol:
  *  either check the ref just before merging a PR to master
  * or check all the refs (as I did in this PR) when you finalize the change log adding the intro text of the release

### Change log entries:
None
### Code Review Checklist:

- [x] Pull Request description:
  - description is up to date
  - change log entries
- [x] Testing:
  - Unit tests
  - System (end to end) tests
  - Manual testing
- [x] API is compatible with existing add-ons.
- [x] Documentation:
  - User Documentation
  - Developer / Technical Documentation
  - Context sensitive help for GUI changes
- [x] UX of all users considered:
  - Speech 
  - Braille
  - Low Vision
  - Different web browsers
  - Localization in other languages / culture than English

### CODE REVIEW

**Comment by CyrilleB79** [comment]
Note: for a few weeks/months, appVeyor builds take more time and sometimes are aborted due to excessive time. E.g. for the first commit of this PR, appVeyor issues the following message:
> • Build execution time has reached the maximum allowed time for your plan (60 minutes).

NVAccess guys, is this issue tracked?
Thanks.

**Comment by CyrilleB79** [comment]
Also @seanbudd, @feerrenrut, please have a look at this PR before declaring translation freeze. Thanks.

**Comment by seanbudd** [comment]
>• Build execution time has reached the maximum allowed time for your plan (60 minutes).

This is likely a bug, and not related to the length of build times increasing.

**Review by seanbudd — APPROVED** [review]

**Comment by seanbudd** [comment]
>or check all the refs (as I did in this PR) when you finalize the change log adding the intro text of the release

I think this was missed, and needs to be added to the process.

**Pull request merged**
