### PR TITLE
Convert NVDA's code base to use output reasons from enum in controlTypes and remove deprecated REASON_* module level constants

### PR DESCRIPTION
**Pull request by lukaszgo1**
### Link to issue number:
Discussion in #10703 and #10732
### Summary of the issue:
PR #10703 introduced new `OutputReason` class which should be used in place of previously used `REASON_*` constants from the `controlTypes` module. To provide backward compatibility old module level constants were kept in place, but marked as deprecated. Since 2021.1 intents to break backwards compatibility anyway it makes sense to use output reasons from the new enum throughout the code and remove these deprecated constants.
### Description of how this pull request fixes the issue:
This pr converts all usages of `REASON_*` constants to the new enum (git grep was used to look for all occurrences of them) and removes old constants from the `controlTypes` and `browseMode` modules.
### Testing performed:
- Ensured that unit tests still passes.
- Used NVDA for around a day with these changes without experiencing any regressions in functionality.
- With git grep ensured that only mentions of `REASON_` in the code is in the changelog file
### Known issues with pull request:
I'd be great to merge this soon not only to give it a good amount of testing on Alpha, but it touches many files and therefore is quite  prone to conflicts.
### Change log entry:
Changes for developers:
- Module level  `REASON_*` constants are removed from `controlTypes` - please use `controlTypes.OutputReason` instead.
- `REASON_QUICKNAV` has been removed from `browseMode` - use `controlTypes.OutputReason.QUICKNAV` instead

### CODE REVIEW

**Comment by lukaszgo1** [comment]
@feerrenrut As I've predicted in the PR description due to the amount of modified files this had conflicts already. Would it be possible to review this to avoid multiple back and forth of fixing merge conflicts here?

**Comment by feerrenrut** [comment]
Ok, I'll get #10732 delivered first , then I'll come and review this. To speed up the review, please go over the approach in #10732 to ensure the approach here is consistent.

**Comment by feerrenrut** [comment]
Sorry, I meant PR #11782, I'll edit my last comment.

**Comment by lukaszgo1** [comment]
@feerrenrut This PR merely starts using enum added in #10703 so I believe consistency should not be an issue. In deed `OutputReason` matches style used in #11782

**Review by michaelDCurran — APPROVED** [review]

**Pull request merged**
