### PR TITLE
Updated misc-deps

### PR DESCRIPTION
**Pull request by feerrenrut**
New misc-deps includes new HanSoneConnect dll.
See nvaccess/nvda-misc-deps#2
and nvaccess/nvda#6063

This builds without errors in a clean repo.
NVDA seems to run ok, including the braille options. I have not tested
with the braille display as I don't have access to one.

### CODE REVIEW

**Comment by feerrenrut** [comment]
@jcsteh are you ok with incubating this change?

**Comment by jcsteh** [comment]
Yup. Please go ahead.

**Comment by feerrenrut** [comment]
Holding off on merging this until some further testing has been done. See #6436

**Comment by jcsteh** [comment]
We're backing this out because it causes a regression (#6436) and we don't have a clear path to resolving this yet. In order to consider reinstating this, we need clear information on exactly what changed in this dll, including the new display identifiers and how to handle them, as well as an updated NVDA driver.

CC @leonardder.

**Comment by feerrenrut** [comment]
Reverted this change on the `misc-deps` repo, and on the `next` branch.

**Pull request closed without merging**
