### PR TITLE
Normalize references to Insert keys

### LINKED ISSUE #13648: Use consistent terminology for insert key between User Guide and Welcome Screen
### Is your feature request related to a problem? Please describe.

On the "Welcome Screen", there is a line which reads:
"By default, the numpad Insert and main Insert keys may both be used as the NVDA key."

In the User Guide, in section 4.2.1, the second paragraph reads:
"NVDA can be configured so that the numpad Insert, Extended Insert and/or Caps Lock key can be used as the NVDA modifier key. By default, both the numpad Insert and Extended Insert keys are set as NVDA modifier keys."

### Describe the solution you'd like

We should be consistent and use either "Main Insert" or "Extended Insert".

The Microsoft Style Guide simply notes the "Insert key" without distinguishing between them: https://docs.microsoft.com/en-us/style-guide/a-z-word-list-term-collections/term-collections/keys-keyboard-shortcuts

Wikipedia gives screen readers a mention but also doesn't offer a disctinction beween the different insert keys: https://en.wikipedia.org/wiki/Insert_key (in fact the text doesn't mention the number pad insert at all, although it is highlighted on the image of a keyboard).

I can't find any reference specifying what to call that insert key near delete, home, end etc.  I've heard it called "extended insert" before although I am not sure how many people are familiar enough with either term?

So, I don't mind either way, but we should endeavour to be consistent, whatever we call it.

### Describe alternatives you've considered

Doing nothing.  That has mostly worked well until now, but it is probably worth neatening it up.

### PR DESCRIPTION
**Pull request by truthless-dev**
### Link to issue number:

Fixes #13648 

### Summary of the issue:

The Welcome Screen and User Guide used different terms, "main Insert" and "Extended Insert" respectively, to refer to the same key.

### Description of user facing changes

Both the Welcome Screen and User Guide now call Extended/main Insert by simply "Insert."

### Description of development approach

Modified wording in userGuide and startupDialogs files, as well as the startup system test that checks the Welcome Screen text.

### Testing strategy:

Rebuilt NVDA with `scons source user_docs` and `scons dist` and checked both places where changes are made. Ran all system tests.

### Known issues with pull request:

* No translations of either the Welcome Screen or User Guide were updated.

### Code Review Checklist:

- [x] Documentation:
  - Change log entry
  - User Documentation
  - Developer / Technical Documentation
  - Context sensitive help for GUI changes
- [x] Testing:
  - Unit tests
  - System (end to end) tests
  - Manual testing
- [x] UX of all users considered:
  - Speech 
  - Braille
  - Low Vision
  - Different web browsers
  - Localization in other languages / culture than English
- [x] API is compatible with existing add-ons.
- [x] Security precautions taken.

### Notes

Translations were not attempted, as I don't speak any other languages, and it looks to me like there are other people and processes to handle that. I am new to NVDA, though, so if I need to do anything to make that happen, or if I forgot anything or made any errors in the code or starting the PR, please let me know. Thank you in advance.

### CODE REVIEW

**Comment by zstanecic** [comment]
Hi,
I am rather against this change. Main insert and extended insert are keys which are located in a different places on a keyboard. You need to make differences somehow.

**Comment by TylerChristie302** [comment]
Thanks for the quick feedback, @zstanecic. :)

The few commenters on #13648 seemed all to agree that the naming conventions should be made the same in both areas. So, to clarify, should I have called it something other than simply "Insert", or is the change not needed overall? I know it's a pretty old issue, so maybe thoughts on it have changed since then.

Thank you again. :)

**Comment by zstanecic** [comment]
In my opinion, change is not needed overall, because we have two insert keys, which are differently named in the windows terminology. This change may confuse users.

**Comment by CyrilleB79** [comment]
@zstanecic main insert and extended insert refer to the same key in NVDA's documentation and GUI. On a normal keyboard, it's located on the 6-key pad above the 4 arrow keys. On the other side, you have the numpad insert key, which is the 0 key of the numpad when numlock is off.

Thus, you have the numpad insert key and the other one. The current PR'aims to use a unique term (or expression) for this other insert key.

**Comment by seanbudd** [comment]
Unfortunately you'll need to redraft this due to the timing of https://github.com/nvaccess/nvda/issues/16419 and https://github.com/nvaccess/nvda/pull/16492, to update your changes to markdown in userGuide.md

**Comment by TylerChristie302** [comment]
Sorry about that. I should've double-checked the status of the freeze before posting.

Updated my branch and redid my changes. Should be good now. If not, I'm happy to fix anything I broke. :)

**Review by seanbudd — APPROVED** [review]

**Review by Qchristensen — APPROVED** [review]
Looks good.  I have never found a reference to "Extended insert".  The Microsoft Style Guide only references the "Insert key" (although doesn't distinguish between the two): https://learn.microsoft.com/en-us/style-guide/a-z-word-list-term-collections/term-collections/keys-keyboard-shortcuts

**Comment by seanbudd** [comment]
Could you please update the system tests so that they pass? The strings in the welcome dialog need updating

**Comment by TylerChristie302** [comment]
@seanbudd I seem to be having the same problem with running system tests as was raised in #13894, where crash dumps are not being generated during the crash tests. I've spent quite a while looking through the test libraries, my temp directories, running tests individually, running on a fresh repo, etc., and can't figure what's going on. The "read welcome dialog" test is passing, though, so I decided to push changes and see what AppVeyor says. Hope that's acceptible.

And this is why I started with a very small issue...

**Pull request merged**
