### PR TITLE
Report 'AC connected' rather than 'charging battery'

### LINKED ISSUE #14726: System tray battery message contradicts Windows and is inaccurate
### Steps to reproduce:
Issue the NVDA announce battery status command, NVDA shift b is the desktop layout command.
### Actual behavior:
NVDA says "100 percent" if the level is 100 percent and then says "charging battery."
Use "Speak command keys" (NVDA+4) and speech viewer to copy and paste here. 
Use braille viewer to copy and paste here.
You may additionally include an explanation.
-->

### Expected behavior:
NVDA should say what it said before, "AC power on."
Use "Speak command keys" (NVDA+4) and speech viewer to copy and paste here. 
Use braille viewer to copy and paste here.
You may additionally include an explanation.
I'm not sure if this should be submitted as a bug or a feature request.  At any rate, when the battery is fully charged, charging stops.  If the charge drops below 100 percent, charging resumes until it reaches 100 percent.  The battery is thus not overcharged.  Saying charging when the battery is at one-hundred percent is factually incorrect and contradicts the information provided by Windows.  The System tray icon says "fully charged, 100 percent" in Windows 10.  A screen-reader shouldn't present contradictory information to the system.-->

#### NVDA installed/portable/running from source:
NVDA installed
#### NVDA version:
2022.4
#### Windows version:
Windows 10 version 22H2
#### Does the issue still occur after restarting your computer?
Doesn't apply.
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
I checked an older version I have on the system and run as a portable version.  It is version 2021.3.5.
#### If NVDA add-ons are disabled, is your problem still occurring?
Yes.
#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
Doesn't apply.

### PR DESCRIPTION
**Pull request by seanbudd**
### Link to issue number:
Closes #14726

### Summary of the issue:
When the AC is connected, reporting "Charging battery" may be misleading, e.g. when the battery is fully charged.
It is more accurate to state "AC connected"

### Description of user facing changes
"AC connected" is reported instead of "charging battery" when reporting battery status

### Description of development approach
Update string

### Testing strategy:
None

### Known issues with pull request:
None

### Change log entries:
Not worthwhile

### Code Review Checklist:

- [x] Pull Request description:
  - description is up to date
  - change log entries
- [x] Testing:
  - Unit tests
  - System (end to end) tests
  - Manual testing
- [x] API is compatible with existing add-ons.
- [x] Documentation:
  - User Documentation
  - Developer / Technical Documentation
  - Context sensitive help for GUI changes
- [x] UX of all users considered:
  - Speech 
  - Braille
  - Low Vision
  - Different web browsers
  - Localization in other languages / culture than English
- [x] Security precautions taken.

### CODE REVIEW

**Comment by XLTechie** [comment]
@seanbudd

As I commented on the original issue, "plugged in" is the term Microsoft seems 
to have decided for this state. That is what is indicated in the system 
generated text of the battery icon in the notification area.

While I think "AC Connected" is fine, and an improvement in factualness (and is 
the name of the state of the flag in the library), I wanted to point out the 
"plugged in" phrasing that Microsoft uses, as an alternative to consider.

It may be that the reason they use "plugged in", is, as someone pointed out, 
because it isn't actually "AC" that's connected, but DC which **MAY** be running 
from an AC transformer-rectifier. I have no idea if that's why though.

That's all the further comment I have--glad to see this changed with either 
phrase you choose to use.

**Comment by CyrilleB79** [comment]
Hello

I have not revisited all the tickets on this topic. However, it seems that there are actually two requests from users that are handled together:
1. Is the battery charging? Yes/No; and as an addition, what is the charge level?
2. Is the charger plugged in?

For sighted people the first question is answered by the icon in the system tray.

Regarding the second question, I think that there is no visual indicator in Windows UI for sighted people. However blind people have expressed several times the need to know if the wire was plugged in (and correctly) or not.

I think that the issue should be handled more globally than this PR, if possible, and provide the 3 following information upon NVDA+B:
* x%, charger disconnected
* x%, charging battery (and obviously charger connected)
* x%, charger connected, battery fully charged

This would allow to make modifications back and forth between "charging battery" / "AC connected"

**Comment by XLTechie** [comment]
@CyrilleB79

I agree with you in general. See my comments at the end of the linked ticket 
about what is going on and why.

What you request is possible, and can be done, but it will require a full 
rewrite of our battery module.
I may work on that in the future, if nobody else gets to it first.

But for now, I think what Sean has done is a quick solution that solves the 
immediate problem.

We have a saying in the U.S.: don't let the perfect get in the way of the good.

The perfect is what you ask. The good is what this does.
Perhaps the immediate good can happen, while the perfect is figured out down the 
road?

**Review by michaelDCurran — CHANGES_REQUESTED** [review]
Please change these strings to `Plugged in` and `Unplugged` to remove the mention of AC.

**Comment by CyrilleB79** [comment]
> @CyrilleB79 I agree with you in general. See my comments at the end of the linked ticket about what is going on and why. What you request is possible, and can be done, but it will require a full rewrite of our battery module. I may work on that in the future, if nobody else gets to it first. But for now, I think what Sean has done is a quick solution that solves the immediate problem. We have a saying in the U.S.: don't let the perfect get in the way of the good. The perfect is what you ask. The good is what this does. Perhaps the immediate good can happen, while the perfect is figured out down the road?

Yes this makes sense. This PR is already an improvement and I support it to be merged (including the change requested by Mick).

Then for something more elaborated as described in my previous comment, a new ticket should be opened or, more likely, an old ticket that was recently closed could be reopened (Cc @Adriani90)

**Comment by Adriani90** [comment]
@CyrilleB79 the issue referenced in this PR is still open and covers your suggestions. The one I've closed is an old one which had less details so I closed it in favor of the new one.
I think this PR should say solves partially #14726 but does not fix it completely so that the issue remains open.

**Review by michaelDCurran — APPROVED** [review]

**Pull request merged**
