### PR TITLE
Downgrade espeak to aafd2e720

### LINKED ISSUE #12465: eSpeak NG Attempts to Pronounce Certain Strings of Non-English Characters Strangely
### Steps to reproduce:
Read the following string with eSpeak NG and NVDA 2021.1beta1:
Warning: Will cause broken English speech. This can be fixed by restarting NVDA or by changing the variant or language and then setting it to the previous setting.
ᎯℳℐℕᎯ
### Actual behavior:
After reading the string (or other strings like it), eSpeak NG attempts to read English in a strange, unintelligible accent. This can be fixed by restarting NVDA or by changing the variant or language and then setting it to the previous setting.
### Expected behavior:
NVDA should read the string (or strings like it), but should not try to speak other English words in a strange accent.
#### NVDA installed/portable/running from source:
Installed
#### NVDA version:
2021.1beta1
#### Windows version:
Windows 10 Pro version 20H2
#### Name and version of other software in use when reproducing the issue:
N/A
#### Other information about your system:
eSpeak NG settings
Voice: English (America)
Variant: Nguyen
Rate: 40
Rate boost: checked
Pitch: 51 (caused by issue #9811/#11832)
Inflection: 51 (caused by issue #9811/#11832)
Volume: 100
Automatic language switching (when supported): unchecked
Automatic dialect switching (when supported): unchecked
Punctuation/symbol level: most
Trust voice's language when processing characters and symbols: Checked
Include Unicode Consortium data (including emoji) when processing characters and symbols: checked
Capital pitch change percentage: 50
Say cap before capitals: unchecked
Beep for capitals: unchecked
Use spelling functionality if supported: checked
#### Does the issue still occur after restarting your computer?
Yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
NVDA 2020.4 does not do this.
#### If add-ons are disabled, is your problem still occurring?
Yes
#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
Yes

### PR DESCRIPTION
**Pull request by seanbudd**
### Link to issue number:

Closes #12465 

### Summary of the issue:

The latest espeak, used in beta, has a blocking issue. As such, we are reverting to the last known stable espeak. 

### Description of how this pull request fixes the issue:

Reverts to espeak in release 2020.4 which is `aafd2e720`.

The strategy to updating was to follow [the updating espeak readme](https://github.com/nvaccess/nvda/blob/master/include/espeak.md).

Choosing the commit:

```diff
git diff master release-2020.4 include/espeak
diff --git a/include/espeak b/include/espeak
index f6d092a9c..aafd2e720 160000
--- a/include/espeak
+++ b/include/espeak
@@ -1 +1 @@
-Subproject commit f6d092a9c13d864ede78c493f64a7d32cde41f09
+Subproject commit aafd2e720582d7ccdadef675ce656903bc775c1d
```

And then applying the results of `git diff f6d092a9c13d864ede78c493f64a7d32cde41f09 aafd2e720582d7ccdadef675ce656903bc775c1d Makefile.am` within the espeak project.

### Testing strategy:

NVDA builds, ensure espeak continues to work as expected like 2020.4. 

### Known issues with pull request:

None

### Change log entries:

Changes: remove mention of update to espeak. 

Note: 2020.4 didn't mention the upgrade to espeak. As such, those using the changelog to figure out the latest espeak version may be misled. 

### Code Review Checklist:

- [x] Pull Request description is up to date.
- [x] Unit tests.
- [x] System (end to end) tests.
- [x] Manual testing.
- [x] User Documentation.
- [x] Change log entry.
- [x] Context sensitive help for GUI changes.
- [x] UX of all users considered:
  - Speech 
  - Braille
  - Low Vision
  - Different web browsers

### CODE REVIEW

**Comment by feerrenrut** [comment]
For reference, information about Chinese dictionary compilation: https://github.com/espeak-ng/espeak-ng/issues/933

**Comment by leonardder** [comment]
How about the references to speech player?

**Comment by Brian1Gaff** [comment]
I was not aware this still worked.
 Brian

***@***.*** 
Sent via blueyonder. 
Please address personal E-mail to:-
***@***.***, putting 'Brian Gaff'
in the display name field.
Newsgroup monitored: alt.comp.blind-users
----- Original Message -----

**Comment by seanbudd** [comment]
> How about the references to speech player?

Which references? If you mean within the `sconscript`, these should just reflect undoing change to the espeak Makefile since 2020.4.

**Comment by leonardder** [comment]
Ah, thanks for clarifying. I wasn't aware speech player was merged in espeak upstream.

**Review by feerrenrut — APPROVED** [review]

**Comment by feerrenrut** [comment]
This is weird, the appveyor build has completed and succeeded, but GitHub still shows it as pending. I'm going to go ahead and merge this.

**Pull request merged**
