### PR TITLE
Fixed "list" is reported on every line of a list in Chrome rich text editors

### LINKED ISSUE #7562: Chrome: "list" is reported on every line of a list in rich text editors
### Steps to reproduce:
1. Open this URL in Chrome:
    `data:text/html,<div contentEditable="true" role="textbox" aria-multiline="true">Before<ul><li>a</li><li>b</li></ul>After</div>`
2. Focus the text box and ensure you are in focus mode.
3. Press control+home.
4. Read through the content line by line using the down arrow key.

### Expected behavior:
```
Before
list  bullet  a
bullet  b
out of list  After
```

### Actual behavior:
```
Before
list  bullet  a
list  bullet  b
After
```

Note: Whether you hear "bullet" depends on your symbol level; I have mine set to "all".

### System configuration:
NVDA version: next-14373,6bbe5915
NVDA Installed or portable: installed
Windows version: Windows 10 Version 1703 (OS Build 16251.0)
Name and version of other software in use when reproducing the issue: Chrome Version 62.0.3201.2 (Official Build) canary (64-bit)

### Technical info:
This happens because a contentEditable list (the `ul` tag) does not get the read-only state. Lists and list boxes both get the same role (list), but they're normally differentiated by the read-only state; a `<ul>` has read-only, whereas a `<select size="2">` doesn't. However, in this case, I can kinda understand why Chrome doesn't set read-only; after all, it does have the editable state.

I think we should probably just tweak `TextInfo.getPresentationCategory` to treat editable liss as being containers; i.e. allow for the editable state as well as the read-only state in the rule for `PRESCAT_CONTAINER`. Alternatively, we could file a bug against Chrome requesting this get fixed on their side.

P2 because this is quite annoying when dealing with rich text editors in Chrome, including the Gmail composer.

### PR DESCRIPTION
**Pull request by awalvie**
### Link to issue number:
Fixes #7562 

### Summary of the issue:
contentEditable list currently does not test for read-only state. In some text rich editors Lists and list boxes both get the same role (list) but what differentiates them is the read-only state. For example to read 
```
Before 
* a
* b
After
```

It should read

```Before
list  bullet  a
bullet  b
out of list  After
```
it may read 

```Before
list  bullet  a
list  bullet  b
After
```
Fully described [here](https://github.com/nvaccess/nvda/issues/7562#issue-254939604)

### Description of how this pull request fixes the issue:
Currently the `Textinfo.getPresentationCategory` function returns `self.PRESCAT_SINGLELINE` when we focus on lists with multiple `<ul>`. I have removed the condition that returns `PRESCAT_SINGLELINE` and replaced it in the condition that returns `PRESCAT_CONTAINER`.

### Testing performed:
Replicated the issue and it works as it is supposed to.

### CODE REVIEW

**Comment by dingpengyu** [comment]
hi Awalvie
Please follow the format of PULL_REQUEST_TEMPLATE to write pr. Your current pr description is very doubtful after I read it.
https://github.com/nvaccess/nvda/wiki/Github-pull-request-template-explanation-and-examples

**Comment by Awalvie** [comment]
I did try to follow the PR Templates but maybe I made some mistakes. Could you maybe recommend some changes in the PR so I have an understanding of how I should modify it ?

**Comment by leonardder** [comment]
@Awalvie: I changed the title of the issue to be more descriptive. Please also provide a short description in the initial description of the pr, instead of referring to another issue that contains a description. You can even copy parts of that issue, it's just that one shouldn't have to click a link to read the description.

**Comment by Awalvie** [comment]
Got it. I'll do that

**Comment by Awalvie** [comment]
@leonardder Is this better ?

**Comment by michaelDCurran** [comment]
This breaks the announcement of  <select> lists with size>=2. E.g.:
```
data:text/html,<p>Before</p><select size="2"><option>Frogs</option><option>Birds</option></select><p>after</p>
```
When arrowing down through the document in browse mode, Normally NVDA would say:
```
before
list clickable frogs
after
```
But now it says:
```
Before
list clickable Frogs
out of list
after
```
I believe that the rule to return singleline in getPresentationCategory should still mention list, but only if it does not have the readonly or editable states.
So rather than removing that rule completely, also check to ensure it does not have the editable state.
In the end:
* lists with no readonly or editable state (E.g. select with size>=2) should be singleline
* ul lists in a contenteditable should be container
 * read-only ul lists should be container

**Comment by Awalvie** [comment]
Got it will try to implement that too.

**Comment by leonardder** [comment]
@Awalvie: Have you made the requested changes yet?

**Comment by Awalvie** [comment]
I am really sorry for not being able to make the suggested changes, I am
currently busy with submissions I am supposed to make at my college which
will then be followed up with exams. I'll try my best to get this fixed as
soon as possible.

**Comment by Adriani90** [comment]
@awalvie any updates on this?

**Comment by michaelDCurran** [comment]
As there are edge cases this pr does not successfully cover, and because Google has filed a bug against Chrome to probably address this in Chrome: https://crbug.com/1087551
We will close this pr.

**Pull request closed without merging**
