### PR TITLE
Fixup #13131, ensure speech doesn't interrupt when scrolling braille display

### PR DESCRIPTION
**Pull request by seanbudd**
### Link to issue number:
Fixup of #13131 
### Summary of the issue:
#13131 incorrectly checks the script commands. The initial PR did not use the correct instance of global commands, rather references to the class methods.

### Description of user facing changes
#13131 works as intended.

### Testing strategy:
Get a braille user to test the PR build

This patch scrolls the braille viewer display forward every 2 seconds once opened. 
Confirmed speech wasn't interrupted.
```diff
diff --git a/source/brailleViewer/brailleViewerGui.py b/source/brailleViewer/brailleViewerGui.py
index 33f3ead0a..a8bf947dc 100644
--- a/source/brailleViewer/brailleViewerGui.py
+++ b/source/brailleViewer/brailleViewerGui.py
@@ -451,6 +451,9 @@ class BrailleViewerFrame(
 			self._newCellCount = currentCellCount
 
 		self._triggerGuiUpdate()
+		import core
+		from globalCommands import commands
+		core.callLater(2000, commands.script_braille_scrollForward, "")
 
 	def _triggerGuiUpdate(self):
 		continuousTimerRunning = self._timer.IsRunning() and not self._timer.IsOneShot()
```

### Known issues with pull request:
None
### Change log entries:
None - Unreleased feature

### Code Review Checklist:

- [x] Pull Request description:
  - description is up to date
  - change log entries
- [x] Testing:
  - Unit tests
  - System (end to end) tests
  - Manual testing
- [x] API is compatible with existing add-ons.
- [x] Documentation:
  - User Documentation
  - Developer / Technical Documentation
  - Context sensitive help for GUI changes
- [x] UX of all users considered:
  - Speech 
  - Braille
  - Low Vision
  - Different web browsers
  - Localization in other languages / culture than English

### CODE REVIEW

**Comment by burmancomp** [comment]
Unfortunately display keys do not work anymore.
[nvda.log](https://github.com/nvaccess/nvda/files/9157360/nvda.log)

**Review by feerrenrut — DISMISSED** [review]

**Comment by feerrenrut** [comment]
After https://github.com/nvaccess/nvda/pull/13946 is merged the base branch will be set to beta, right?

**Comment by seanbudd** [comment]
@burmancomp can you test [this build](https://ci.appveyor.com/api/buildjobs/9sfys0pcdisw288h/artifacts/output%2Fnvda_snapshot_pr13932-25974%2Ca051c37a.exe)

**Review by feerrenrut — APPROVED** [review]

**Comment by burmancomp** [comment]
Works for me.

**Pull request merged**
