### PR TITLE
Abbreviate landmark names in braille

### PR DESCRIPTION
**Pull request by dkager**
Re #3975 

Summary of proposed changes:
The order of the word landmark and the type of landmark is swapped. Landmark becomes "lmk". The names of each of the landmarks are altered as follows:
```
"banner": "bnnr"
"complementary": "comp"
"contentinfo": "cinf"
"main": "main"
"navigation": "nav"
"search": "srch"
"form": "frm"
"region": "rgn"
```

Example: "navigation landmark" becomes "lmk nav".

### CODE REVIEW

**Comment by feerrenrut** [comment]
Thanks for the contribution!
Also please could you outline the testing that you have done on this. Ideally I would love to see a test case document.

**Review by feerrenrut — APPROVED** [review]

**Comment by dkager** [comment]
Testing was mostly just running this code in the wild. The patch is simple enough to reason about its correctness. There are no good standards for these abbreviations. So I tested this by simply using it a few days. This resulted in changing the abbreviation for banner from "bnr" to "bnnr". I'm hoping that its incubation will reveal any remaining issues, though I don't think there will be any.

**Review by feerrenrut — CHANGES_REQUESTED** [review]
Out of curiosity, why did you change banner to "bnnr"? Have you tried output of all of the other landmarks?

Please can you update the user guide with these changes too.

**Comment by dkager** [comment]
> Out of curiosity, why did you change banner to "bnnr"?

Because it felt a bit more intuitive, based on emperical testing by me and @leonardder. We also thought it would be good if most landmark names had a consistent 4-character length. There are some exceptions. For example, we couldn't agree on a good 4-character abbreviation for region. Looking back at it now, I also feel we should use form instead of frm, because the latter could be mistaken to mean frame.

> Have you tried output of all of the other landmarks?

Yes. This includes the somewhat special case of region, which isn't strictly a landmark.

**Comment by dkager** [comment]
Updated some landmark abbreviations (see commit message) and added them to the user guide.

I don't have the lists of websites anymore that I used for testing. But one could also write a short HTML document containing all landmarks and verify that the abbreviations come out correctly. I did have a short test document for named landmarks, but can't find it at the moment.

**Comment by dkager** [comment]
@feerrenrut Here is a test HTML document that has all the landmarks in it. I also had a stab at writing a unit test, but that's not so straight-forward because of all the TextInfo stuff.


[nvda-braille-landmark-test.html.txt](https://github.com/nvaccess/nvda/files/974422/nvda-braille-landmark-test.html.txt)

**Review by feerrenrut — APPROVED** [review]
Thanks for the updates.

**Pull request merged**
