### PR TITLE
Add driver for seika notetaker braille display

### PR DESCRIPTION
**Pull request by larry801**
### Link to issue number:
#9478
### Summary of the issue:
Add support for  seika notetaker braille display

### Description of how this pull request fixes the issue:
Currently NVDA only supports seika braille display v3 v5 v80
seika notetaker is not supported
### Known issues with pull request:
None:
### Change log entry:
- Add support for seika notetaker braille display
Section: New features

### CODE REVIEW

**Comment by leonardder** [comment]
Thanks for your contribution. I have several questions:

1. Is this driver your work, or mainly written by someone else? I'm not seeing your name in the copyright header, only the name of Ulf Beckmann. Does he agree with having his driver included in NVDA core?
2. This driver communicates wit the display using dll files and ctypes. While this is a valid way to communicate with the display, using dll's, driver authors are strongly encouraged to use the hwIo framework for their display drivers instead. This also guarantees that the display integrates within NVDA"s braille display auto detection system, which this driver does not support. See the baum, ALVA, hims, handyTech and eurobraille drivers as examples.

I don't know NV Access' standpoint on this, but I'd be very reluctant to add new drivers that aren't based on hwIo and don't implement braille display auto detection.

**Comment by larry801** [comment]
Staff of manufacturer is not familiar with github. They let me created this pull request.
I will ask them about these problems

**Comment by leonardder** [comment]
It's good to know what NV Access thinks in this case, cc @feerrenrut.

**Comment by leonardder** [comment]
@larry801 wrote:
> I will ask them about these problems

Do you have any news about this?

**Comment by leonardder** [comment]
@larry801: As it is now, I'm afraid this pr can't be accepted. Have you received additional details and answers from the manufacturer?

**Comment by larry801** [comment]
They say the driver is written by their partner in German, which is Ulf Beckmann and they may rewrite the driver in hwIO "in the future".

**Comment by feerrenrut** [comment]
Since we do not have contact with the original author, it will require a fair bit of work from us to get this driver ready for inclusion. Without a device to test on this will be quite difficult. I am going to close this PR for now, if anyone with a device wants to take over development or act a tester please comment on the issue or get in touch with NV Access.

**Comment by moyanming** [comment]
Hi @feerrenrut ,
We are the manufacturer of the Seika mini Notetaker Braille display. We have released the Seika Patch for NVDA v3.2, and @accessolutions(https://github.com/accessolutions/seikamini-nvda) release the "seikamini-3.2.2019.1.1.nvda-addon" base on the v3.2 patch. We have tested the "seikamini-3.2.2019.1.1.nvda-addon" with Seika mini16, mini24, Seika v6, and Seika v7 and all work fine.
We want to add a new item "Seika Notetaker" within the NVDA for good user experience. Please note that the "Seika" which already within the NVDA is only working for the Seika v3/v5 Braille display. Seika v3/v5 is not compatible with the Seika Notetaker because the keys are not compatible.
Please contact me feel free.
Best Regards

**Comment by Ulf-Beckmann** [comment]
Hello, I am Ulf Beckmann from Germany and I have get the message: "But this PR was blocked because they can't contact you for the copyright.". My work for NVDA is free. You can find my email address also in the source files of the drivers. In the near future I will also have a look at the hwID and autodetect problem.
Best regards

**Comment by feerrenrut** [comment]
@Ulf-Beckmann and @moyanming Thanks for getting in touch. This driver will need to be updated to become compatible with NVDA 2019.3. Are you willing to make these adjustments? The driver will need to be made compatible with Python 3, there is also feedback from @leonardder which needs to be address: https://github.com/nvaccess/nvda/pull/9479#issuecomment-481635673

I will re-open this pull request.

**Review by feerrenrut — CHANGES_REQUESTED** [review]
As mentioned, please update this to be compatible with Python 3 and address feedback from  @leonardder

**Comment by moyanming** [comment]
Hi @feerrenrut ,
Yes, we are working on the update of the driver to Python 3. @Ulf-Beckmann and I will make sure all components work fine and the Seika Notetaker will be a good test too.
Thank you for your great work!

**Comment by Ulf-Beckmann** [comment]
Hello,
    I have the first Version for miniseika (Python 3) but I am
      wondering becouse the routing keys do not work and I get no
      error... Is the a error in NVDA? Sorry I have notlonger time today
      to try....
    
    
    regards ulf
    
    Am 07.02.2020 um 13:25 schrieb
      moyanming2013:
    
    
      
      Hi @feerrenrut
        ,
        Yes, we are working on the update of the driver to Python 3. @Ulf-Beckmann
        and I will make sure all components work fine and the Seika
        Notetaker will be a good test too.
        Thank you for your great work!
      —
        You are receiving this because you were mentioned.
        Reply to this email directly, view it on GitHub, or unsubscribe.
      [
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/nvaccess/nvda/pull/9479?email_source=notifications\u0026email_token=AJLBFLGVISG4HV4PUKORJHTRBVHNJA5CNFSM4HE2QCS2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOELCYCEI#issuecomment-583368977",
"url": "https://github.com/nvaccess/nvda/pull/9479?email_source=notifications\u0026email_token=AJLBFLGVISG4HV4PUKORJHTRBVHNJA5CNFSM4HE2QCS2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOELCYCEI#issuecomment-583368977",
"name": "View Pull Request"
},
"description": "View this Pull Request on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by moyanming** [comment]
Hi @Ulf-Beckmann ,
Thank you for your great work!
Which version of the NVDA you have test with the miniseika(python 3)? You should test the new miniseika(python 3) with the NVDA 2019.2 first because the miniseika(python 2) works fine with the NVDA 2019.2.
You can send the new patch and I will test this too.
Best Regards

**Comment by moyanming** [comment]
Hi @Ulf-Beckmann ,
Please [note that](https://github.com/nvaccess/nvda#dependencies):
Python, version 3.7, 32 bit
Don't use 3.7.6 it causes an error while building, for now use 3.7.5 see #10696 
[Here](https://github.com/nvaccess/nvda/commits/master/source/brailleDisplayDrivers/seika.py) is the "seika.py" which already converts to the Python 3.
mini16, mini24, Seika6 and Seika 7 are kinds of the “Seika Notetaker”.
Seika v3, Seika v5 and Seika v80 are kinds of the ”Seika“.

**Comment by Ulf-Beckmann** [comment]
Hello, I have test the driver with NVDA2019.3; I have copy the miniseika.py in the library.zip - folder brailleDisplayDdriver and I have copy the 3 DLLs to the 'normal' folder brailleDisplayDriver subfolder Seika, 
it would be great if this driver could be added to the list at NVDA.
regards ulf
[seikamini.zip](https://github.com/nvaccess/nvda/files/4198780/seikamini.zip)

**Comment by moyanming** [comment]
Hi @Ulf-Beckmann ,
Could you please give the detailed steps on how to test the "seikamini.zip"?
I have made a patch for the test by using the "seikamini.py". There are 2 issues should be improved:
1. Please change the "seikamini.py" for only use one copy of the 3 DLLs.
2. Please use the latest version of the "SeikaDevice.dll".
Please find the 
[Seika Patch for NVDA v3.3.zip](https://github.com/nvaccess/nvda/files/4203770/Seika.Patch.for.NVDA.v3.3.zip) and here are the steps can be used for the test, I have tested this patch and the Seika Notetaker works fine with the NVDA 2019.3.1:
1. Install and run the NVDA 2019.3 and newer.
2. Right-click the NVDA icon and select "Preferences > settings".
3. Select the "Advanced" within the "Categories".
4. Check on the "I understand that changing these settings may cause NVDA to function incorrectly."
5. Check on the "Enable loading custom code from Developer Scratchpad directory".
6. Click the "Apply" button.
7. Click the button "Open developer scratchpad directory".
8. Open the folder "brailleDisplayDrivers".
9. Unzip the "Seika Patch for NVDA v3.3.zip" and copy all files to the "brailleDisplayDrivers" folder.
10. Restart the NVDA.
11. Connect the Seika Notetaker with PC by using the USB cable.
12. Power on the Seika Notetaker and select the "USB Connection" and press Dot8.
13. Right-click the NVDA icon and select "Preferences > settings".
14. Select the "Braille" within the "Categories".
15. Click the "Change..." button in the "Braille display".
16. Select the "Seika Notetaker" and click the "OK" button.
17. The Seika Notetaker working with the NVDA now.
18. The Seika Notetaker can be connected with the NVDA automatically without settings next time.

**Comment by lijianwei2019** [comment]
@JulienCochuyt

**Comment by Adriani90** [comment]
@larry801 or who ever is allowed to maintain this pull request, it seems there are failed test in the Appveyor artifacts. Please fix them.
This braille display should also be integrated into the automatic braille detection in NVDA. We get quite often user reports where new users are complaining that it is too complicated to update the driver and to successfully run the braille display.
cc: @leonardder maybe you can give some advice here if your time permits. This would be very appreciated.

**Comment by JulienCochuyt** [comment]
@Ulf-Beckmann 
We've just published an updated version of the Seika notetakers driver add-on compatible with NVDA 2019.3
It is partly based on your work on the driver patch Python 3 compatibility and routing cursors seem to be working just fine.
Repository: https://github.com/accessolutions/seikamini-nvda
Packaged release: https://github.com/accessolutions/seikamini-nvda/releases/download/3.2.2019.3.1/seikamini-3.2.2019.3.1.nvda-addon

**Comment by feerrenrut** [comment]
Is the goal of this PR to get the driver integrated into core? Is anybody working on this?

**Comment by moyanming** [comment]
> Is the goal of this PR to get the driver integrated into core? Is anybody working on this?

Hi @feerrenrut ,
We are the manufacturer of the Seika Notetaker Braille Display. We have released a patch "Seika Notetaker addon for NADA v3.3.nvda-addon" for add supports the Seika Notetaker about two months ago. We have well tested the addon and all work fine by using the NVDA 2019.3 and newer version, the Seika Notetaker can be connected automatically every time after installing the addon.
But we are not the author of this PR (#9479 ), please find the "Seika Notetaker addon for NADA v3.3.zip" [here](https://github.com/nvaccess/nvda/files/4205268/Seika.Notetaker.addon.for.NADA.v3.3.zip):
[Seika v3v5v80 addon for NADA v1.0.zip](https://github.com/nvaccess/nvda/files/4205268/Seika.Notetaker.addon.for.NADA.v3.3.zip).

The driver files in the addon are the newest and could you please replace the file in this PR(#9479 ) by using the "Seika Notetaker addon for NADA v3.3.zip"? Or, I can create a new PR if needed.
Best Regards.


.

**Comment by feerrenrut** [comment]
#10961 has been created to continue this work. Thanks to everyone who contributed here.

**Comment by JulienCochuyt** [comment]
@feerrenrut wrote:
> #10961 has been created to continue this work. Thanks to everyone who contributed here.

IMNW, #10961 targets only Seika displays (3/5/80), but not Seika notetakers (mini16/mini24/6/7...).
These are indeed two distinct drivers.
Here at Accessolutions, we also developed and published a driver add-on for these notetakers around 2019.1.1 later updated for 2019.3.1
We were discussing last year inclusion of this driver into NVDA core with @michaelDCurran.
This driver uses DLLs from the manufacturer.
Back then, Mick was reluctant - with reason - to add more third-party DLLs to NVDA, but said he might consider accepting them into the `nvda-misc-deps` submodule based on the number of users.

Now that @moyanming has posted an official updated add-on, I guess their version is preferable to ours.
Do you wish I prepare two linked PRs (targeting the `nvda` and `nvda-misc-deps` repos to propose inclusion into NVDA core of the latest official driver posted by @moyanming?

**Comment by moyanming** [comment]
> #10961 has been created to continue this work. Thanks to everyone who contributed here.
Hi @feerrenrut ,
I am sorry for the confusion of the Seika Device.
The Seika v3/5/80 is just for the Braille display and there is no Perkins Braille keyboard on it. We have updated the driver by using Python v3 and this PR (#10961) can fixed bug of issue #10787.
We have published a new type of the Seika device called Seika Notetaker which has the Perkins Braille keyboard and can type in characters. We also have released an addon for the Seika Notetaker which works with the NVDA 2019.3 and newer. But lots of the Seika Notetaker users want to integrate the addon to the NVDA for good user experience. I will create a new PR for the Seika Notetaker because I can't modify the files in the PR #9479.
It is appreciated that the NVDA can integrate the driver of the Seika Notetaker.
Best regards.

**Comment by feerrenrut** [comment]
Thanks for the clarification @JulienCochuyt & @moyanming.  I think a new PR is wise since this one now has lots of unrelated history on it, but first I'll talk to @michaelDCurran to confirm.

**Comment by moyanming** [comment]
Hi @JulienCochuyt 
Thank you for your great work!
I have created PR #10991, the seikamini.py has updated by ULF for use with the NVDA 2019.3 and later.

**Comment by JulienCochuyt** [comment]
@moyanming, you're welcome. I'm just serving here our customers of your great device.
Regarding PR #10991, please see https://github.com/nvaccess/nvda/pull/10991#issuecomment-612869624

**Pull request closed without merging**
