### PR TITLE
Update espeak version

### PR DESCRIPTION
**Pull request by feerrenrut**
### Summary of the issue:
Update to the latest development version of espeak.

### Testing performed:
Built nvda locally and on buildsystem.
Ran NVDA with espeak set as the synthesizer.

Built NVDA with emoji dictionaries. Confirmed that the fix in PR: "Remove all eSpeak emoji dictsource files #7810" is still required.

### Known issues with pull request:
When emoji dictionaries are included, recent crashes with hindi and tamil symbols still occur.

### Change log entry:
Changes:
`eSpeak has been updated to version...`

### CODE REVIEW

**Review by michaelDCurran — APPROVED** [review]

**Comment by feerrenrut** [comment]
I have pushed a further update Espeak. This builds, and passes some basic smoke tests (running from source, changing language and voice)

**Review by michaelDCurran — CHANGES_REQUESTED** [review]
We must remember to keep updating the espeak version string in nvdaHelper/espeak/config.h. Right now I think it says 1.49.1dev, but I think it is 1.49.2.   The version seems to be hardcoded through out eSpeak's various platform files which we don't use. But I think the best place to always check is in its configure.ac.

**Comment by feerrenrut** [comment]
Ah yes, that is a good point, and easy to forget. The version I have pushed is 1.49.3-dev. I have updated the version string now.

**Review by michaelDCurran — APPROVED** [review]

**Comment by feerrenrut** [comment]
I have updated this branch. The new version no longer deletes emoji files. With the emoji support compiled into the espeak dictionaries, I am no longer able to reproduce the freezes that were previously occurring.

**Review by michaelDCurran — DISMISSED** [review]

**Comment by derekriemer** [comment]
@feerrenrut Is this ready for an incubation period?

**Comment by feerrenrut** [comment]
michaelDCurran found a regression in the way certain English words are being spoken and is investigating. I'll update to the latest Dev version again next week and see if it is better.

**Comment by feerrenrut** [comment]
michaelDCurran found a regression in the way certain English words are being spoken and is investigating. I'll update to the latest Dev version again next week and see if it is better.

**Comment by michaelDCurran** [comment]
I have incubated this. However, i'd like to get peoples' opnions on  a possible change in eSpeak english.
To me, words like 'selected" and "return" and "recycle" now sound strange.
For example, both "selected" and "selectered" now sound identical. Similarly, "return" now sounds more like "rer turn" rather than "ree turn".
I have tracked down the change to espeak-ng/espeak-ng:223ff9c. Where "return" is now rendered in espeak phonemes as "r@t'3:n" rather than "rI2t'3:n". Similarly, "selected" is now rendered in eSpeak phonemes as "sI2l'Ekt@d" rather than "sI2l'EktI2d".  
Clearly this commit was very deliberate, so perhaps  my issue with it is rather subjective.

**Comment by beqabeqa473** [comment]
hi.

this version of espeak is very degraded.

i can confirm about letter e in words and in russian language there
are too much mistakes which makes it almost inusable

On 4/13/18, Michael Curran <notifications@github.com> wrote:
> I have incubated this. However, i'd like to get peoples' opnions on  a
> possible change in eSpeak english.
> To me, words like 'selected" and "return" and "recycle" now sound strange.
> For example, both "selected" and "selectered" now sound identical.
> Similarly, "return" now sounds more like "rer turn" rather than "ree turn".
> I have tracked down the change to espeak-ng/espeak-ng:223ff9c. Where
> "return" is now rendered in espeak phonemes as "r@t'3:n" rather than
> "rI2t'3:n". Similarly, "selected" is now rendered in eSpeak phonemes as
> "sI2l'Ekt@d" rather than "sI2l'EktI2d".
> Clearly this commit was very deliberate, so perhaps  my issue with it is
> rather subjective.
>
> --
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/nvaccess/nvda/pull/7846#issuecomment-380987638


-- 
with best regards beqa

**Comment by michaelDCurran** [comment]
And the problems with russian were not in the previous version of eSpeak 
we had in NVDA?

**Comment by beqabeqa473** [comment]
no, we weren't

On 4/13/18, Michael Curran <notifications@github.com> wrote:
> And the problems with russian were not in the previous version of eSpeak
> we had in NVDA?
>
>
>
>
> --
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub:
> https://github.com/nvaccess/nvda/pull/7846#issuecomment-381019711


-- 
with best regards beqa

**Comment by michaelDCurran** [comment]
Please report these issues directly to the eSpeak-ng project if you can.


I have already reported the selected/return issue, but information from 
more users would greatly help.

**Comment by beqabeqa473** [comment]
i've already reported but unfortunately they strangely respond.

On 4/13/18, Michael Curran <notifications@github.com> wrote:
> Please report these issues directly to the eSpeak-ng project if you can.
>
>
> I have already reported the selected/return issue, but information from
> more users would greatly help.
>
>
>
>
> --
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub:
> https://github.com/nvaccess/nvda/pull/7846#issuecomment-381031704


-- 
with best regards beqa

**Comment by jiangtiandao** [comment]
This will bring about a fix concerning Chinese too.
Great
Will this commit be included in 2018.2?

**Comment by rhdunn** [comment]
@beqabeqa473 I've asked for specifics on what the issue with the Russian language is, so we can identify and fix it. That is why I asked for specific words that show the problem. Failing that, knowing which commit (change) broke Russian for you means that that change can be rolled back to the previous behaviour.

**Comment by beqabeqa473** [comment]
hi.

please update to latest master to solve some of very annoying bugs in russian language.

also, i am facing an issue in georgian language, when reading text in cyrilic such as 
из за
nvda gives an error.

could you please look in to that?

**Comment by derekriemer** [comment]
That fixed it!

**Comment by beqabeqa473** [comment]
hi.

please update espeak to fix some russian things again.

**Review by michaelDCurran — APPROVED** [review]

**Comment by michaelDCurran** [comment]
I'm going to merge this pr with espeak at commit e7e59f9. There does not seem to be an eSpeak release coming any time soon.

**Comment by zstanecic** [comment]
Hi michael!
please revert this pull request, because this commit brokes the macedonian language. Ot brokes ancient greek and macedoniann, i.e these languages are completelly unusable.
it makes conflicts with the language naming, see armenian language.
Thanks!

**Comment by michaelDCurran** [comment]
I will look into getting these issues fixed in eSpeak. It would greatly 
help if you could file issues with eSpeak clearly explaining the problems.
We were very very far behind with eSpeak versions, and many other 
languages were pushing us to upgrade. We need to stick with espeak 
1.49.3 and address issues in eSpeak rather than reverting back to 1.49.1 
again.

**Comment by zstanecic** [comment]
Hi michael,
kostadin reported the issue with bulgarian, too.
please ensure that you use the newer executables for espeak Ng,
this is the answer from valdis
so can you see do we have the latest espeak-ng executables?

**Comment by michaelDCurran** [comment]
No, that advice was incorrect.
We compile all espeak executables from a fresh checkout.

**Pull request merged**
