### PR TITLE
UIA handler: load highest supported interface by traversing CUIAutomation8 interfaces in reverse

### LINKED ISSUE #8338: UIA handler: use CUIAutomation8 COM interfaces to retrieve highest supported UIA version
Hi,

This is a follow-up to #8009:

In #8009, when locating highest supported UIA interface, a static list of UIA interfaces were queried (IUIA5 to IUIA2). It turns out CUIAutomation8 includes a list of supported UIA interfaces (UIAHandler.CUIAutomation8._com_interfaces_). Thus it would be better to consult this static list instead of hunting from a static list of interfaces defined by programmers.

Thanks.

### PR DESCRIPTION
**Pull request by josephsl**
### Link to issue number:
Fixes #8338

### Summary of the issue:
UIA Handler: select highest supported interface by traversing through CUIAutomation8 interfaces in reverse

### Description of how this pull request fixes the issue:
Previously, when looking for highest supported interface, NVDA will traverse from IUIA5 to IUIA2 inclusive. It turns out CUIAutomation8 lists supported UIA interfaces, so it makes sense to consult this list in reverse when looking for supported interfaces. This foundation is needed for Windows 10 RS5 and later (especially when supporting future UIA interfaces).

### Testing performed:
Tested using a custom UIA interface based on Windows 10 Insider Preview build 17682 and beyond.

### Known issues with pull request:
None

### Change log entry:
N/A

### CODE REVIEW

**Review by LeonarddeR — APPROVED** [review]

**Comment by josephsl** [comment]
Hi,

Reminder to self: merge master before eventually getting it approved for merging into master in the future. This allows pull request status from Appveyor to show up.

Thanks,

**Comment by josephsl** [comment]
Hi,

Requesting permission to merge it into master please. Thanks.

**Comment by michaelDCurran** [comment]
I can't see when/if this was incubated.

**Comment by josephsl** [comment]
Hi, incubated two weeks ago, although the incubation message refers to 8338. Thanks.

**Pull request merged**
