### PR TITLE
Announce description after all other properties and an end utterance 

### PR DESCRIPTION
**Pull request by michaelDCurran**
### Link to issue number:
None.

### Summary of the issue:
Currently, a control's description property is spoken quite early on in the order of information spoken for a control. It is in fact spoken before position info, keyboard shortcut and cell coordinates. 
As the description is usually extra information that could be quite long (sometimes a full sentence or more), it might be better if this were spoken at the very end. 
Examples of where this has an impact would be buttons on an MS Office ribbon: you need to hear the entire tooltip before hing its shortcut key or position info. And in future with supporting Excel via UI Automation, description (input prompt on a cell) would be currently spoken before the cell coordinates which seems strange.

### Description of how this pull request fixes the issue:
speech.getPropertiesSpeech outputs description after all other properties, and also separates it from the properties befoe with an EndUtterance command. this provides a tiny pause which separates the description.
We could extend the pause with an actual pause command, or we can remove the idea of pausing completely... though other Screen Readers do seem to pause before descriptions these days.

### Testing strategy:
* Opened MS Word. Moved to the Ribbon with alt. Moved into the Home tab and Clipboard grouping with downArroww, landing on the Paste split button.
* Listened to the speech and ensured that the description was spoken after the keyboard shortcut I.e. "Paste split button alt,h,v. Pick a paste option, such as keeping formatting or pasting only content." 

### Known issues with pull request:
None so far.

### Change log entry:
Changes:
* A control's description is now spoken after all other information (such as position and keyboard shortcut).

### Code Review Checklist:

This checklist is a reminder of things commonly forgotten in a new PR.
Authors, please do a self-review and confirm you have considered the following items.
Mark items you have considered by checking them.
You can do this when editing the Pull request description with an x: `[ ]` becomes `[x]`.
You can also check the checkboxes after the PR is created.

- [ ] Pull Request description is up to date.
- [ ] Unit tests.
- [ ] System (end to end) tests.
- [ ] Manual tests.
- [ ] User Documentation.
- [ ] Change log entry.
- [ ] Context sensitive help for GUI changes.

### CODE REVIEW

**Review by feerrenrut — COMMENTED** [review]
The code changes look fine to me. Note this is still marked as a draft and the checklist hasn't been ticked, so I'm not sure if you intend to take this further. It would be nice if there was a simple system test that demonstrated the change with an example that caused description to speak. I notice that the welcome dialog test changes. I guess because of the new endUtterance?

**Comment by RichCaloggero** [comment]
Will this also do same for descriptions in HTML linked via `aria-describedby` attribute?

**Comment by MarcoZehe** [comment]
> Will this also do same for descriptions in HTML linked via `aria-describedby` attribute?

Yes, once past the browser, an AccDescription is an AccDescription is an AccDescription, regardless of whether it came from aria-describedby, the title attribute, or something else.

**Comment by seanbudd** [comment]
Closing as abandoned

**Pull request closed without merging**
