### PR TITLE
handle aria-invalid="spelling,grammar"

### PR DESCRIPTION
**Pull request by michaelDCurran**
### Link to issue number:
None.

### Summary of the issue:
A web page author can indicate to ATs that text is a spelling error, grammar error, or both, via the aria-invalid attribute.
NVDA currently supports "spelling" and "grammar" but does not handle both at the same time.
Web applications such as Google Docs would like to specify that text is both a spelling and grammar error, but right now cannot, as if they expose "spelling, grammar" NVDA will not announce anything at all.

### Description of how this pull request fixes the issue:
When NVDA collects the "invalid" IAccessible2 text attribute, it splits the value on "," and removes whitespace, and then looks for one or more of "spelling" or "grammar" separately.

### Testing performed:
Added a system test which tests three paragraphs in Chrome, containing a spelling error, a grammar error, and both spelling and grammar error.

### Known issues with pull request:
Although this has been done generically for all Gecko IA2 compatible browsers in NvDA, this does not work in Firefox as Firefox does not currently expose multiple values for aria-invalid via IAccessible2, rather it just exposes "true" in this case. This should be fixed in Firefox.

### Change log entry:
Bug fixes:
- Text marked both as being a spelling and grammar error at the same time in Google Chrome will be appropriately announced as both a spelling and grammar error by NVDA.

### CODE REVIEW

**Comment by lijianwei2019** [comment]
@ jcsteh

**Comment by jcsteh** [comment]
Note that this violates the [ARIA spec](https://w3c.github.io/aria/#aria-invalid) as it currently stands. The spec only allows a single token for aria-invalid, not a token list. If we were going to support this in Firefox, I'd want to see this accepted in at least the editor's draft of ARIA.

Furthermore, ARIA properties accepting multiple values should use a token list, which is [defined](https://w3c.github.io/aria/#typemapping) as "Space-separated tokens". Thus, comma + space is a further spec violation.

**Comment by feerrenrut** [comment]
Thanks for the heads up Jamie, we'll discuss this further.

**Comment by michaelDCurran** [comment]
what is your view @aleventhal , as you were driving this request I believe? Are there plans in ARIA to allow for a set of values? I'm not too keen on supporting this in NVDA if there are no documented plans to get this in to ARIA, especially also if there is no real-world web app doing this yet...
Though having said all of this, if we see this pr just as supporting the idea of a set of values for the 'invalid' object attribute in IAccessible2, which Chrome does in deed expose, then perhaps things are okay.

**Comment by jcsteh** [comment]
For what it's worth, if someone wants to propose the spec change to ARIA,
I'd support it, assuming we go with a space separated token list instead of
comma + space.

**Comment by feerrenrut** [comment]
Although we care about the ARIA spec for this and advocate for any issues to be resolved, I believe we are consuming the IA2 spec correctly and think we should push forward on this. If the spec is updated, it will be a minor change to our sample. Perhaps a note should be added to the sample to highlight that it is still under discussion.

**Comment by michaelDCurran** [comment]
@feerrenrut  I have fixed conflicts and added a note about it not yet being standard ARIA and how it may need to change.

**Review by feerrenrut — DISMISSED** [review]
Thanks @michaelDCurran

**Review by feerrenrut — APPROVED** [review]

**Pull request merged**
