### PR TITLE
LibLouis 3, UEB table name/file names, and provisions for other enhancements.

### LINKED ISSUE #4194: Switch to new UEB tables
**Reported by jteh on 2014-06-13 05:52**
NVDA is still using the old UEBC-* tables instead of the newer en-ueb-* tables. Originally, we didn't switch to the new tables because of some serious regressions such as computer braille being used for URLs. However, this was quite some time ago and these issues are very likely fixed now. The computer braille issue certainly is. Furthermore, the old tables are no longer being maintained at all. We should switch to the new tables (at least on next) and get any remaining regressions fixed in liblouis.

### LINKED ISSUE #6109: Upgrade to LibLouis 3.0.0
Hi,

LibLouis 3.0.0 includes promising features, namely vastluy improved emphasis handling, next generation UEB table set and others. at the moment version 3.0.0 has entered alpha testing phase:
https://github.com/liblouis/liblouis/releases/tag/v3.0.0.alpha1

Important things to note:

* A new file named "pattern.c" is introduced that handles various patterns. Without including this file, MS Linker says unresolved symbols.
* We need to test UEB table set to make sure it is more compliant to the standard.
* A lot of testing will be required to make sure braille tables aren't broken and that NVDA can handle them well.

Thanks.

### LINKED ISSUE #6140: Braille/Liblouis 3: provide a way to detect and change table names if old tables are no longer included
Hi,
Part of #6109:

As noted in the following LibLouis issue:
https://github.com/liblouis/liblouis/issues/182

There might be instances where NVDA's own tables tuple may refer to deleted tables. If this happens, the following may result:

1. Braille Settings: no table seems to be selected. This is a minor thing (for about 99 percent of tables, table names are the same).
2. Runtime translation issues are noted due to the fact that some tables rely on other tables.

Thus it would be handy to provide the following migration strategy:

1. Add config checker in braille.initialize that reads in config.conf["braille"]["*Table"] key.
2. Based on the name of the file it read, look up a dictionary which tells NVDA the new filename for the given table.
3. Replace the old name with the new name.

Potential problems:

* What if no replacements are provided? In this case, tell users to specify the new table from braille settings.
* Do we know which tables are gone or renamed? We need to wait until LibLouis 3 beta comes out before proceeding.

The needed change(s) will be committed as part of #6109 branch (#6110 for PR). Comments are appreciated. Thanks.

### LINKED ISSUE #6220: New slovak braille table with liblouis 3.0
Issue #6109 is tracking update to liblouis 3.0. When that is done it would be nice to change the UI to offer new [slovak table](https://github.com/liblouis/liblouis/blob/master/tables/sk-g1.ctb) which is a part of this release.

### PR DESCRIPTION
**Pull request by josephsl**
What's New entry: in Changes:

```
- Updated liblouis braille translator to 3.0.0. This includes significant enhancements to Unified English Braille. (#6109, #4194, #6220, #6140)
```

Fixes #6109. Fixes #4194. Fixes #6220. Fixes #6140.

### CODE REVIEW

**Comment by josephsl** [comment]
@jcsteh @dkager

**Comment by dkager** [comment]
The Dutch table name also changed, and possibly the Norwegian one.
Note that this is an alpha release.

**Comment by josephsl** [comment]
@dkager: Do you know the file names of these tables? I found Norwegian (no-no-comp8) but would like to get a list of file name changes so I can commit them in a single commit. Thanks.

**Comment by josephsl** [comment]
In case of te-in: it is actualy called Telugu, not Telegu. No impact for translators (just English label has been corrected). Thanks.

**Comment by derekriemer** [comment]
Hey Joseph,

I wouldn't be worried about commit cleanlyness too much, because @jcsteh 
squashes them once he commits to master, and you can squash them if you 
like before pr.



On 6/24/2016 3:03 PM, Joseph Lee wrote:
>
> In case of te-in: it is actualy called Telugu, not Telegu. No impact 
> for translators (just English label has been corrected). Thanks.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub 
> <https://github.com/nvaccess/nvda/pull/6110#issuecomment-228461491>, 
> or mute the thread 
> <https://github.com/notifications/unsubscribe/AFGivbSFq8HwoM1clWD93Ak-ZaAL6tUDks5qPEY4gaJpZM4I9R6q>.
>

-- 
------------------------------------------------------------------------


    Derek Riemer

  * Department of computer science, third year undergraduate student.
  * Proud user of the NVDA screen reader.
  * Open source enthusiast.
  * Member of Bridge Cu
  * Avid skiier.

Websites:
Honors portfolio <http://derekriemer.com>
Awesome little hand built weather app! 
<http://django.derekriemer.com/weather/>

email me at derek.riemer@colorado.edu <mailto:derek.riemer@colorado.edu>
Phone: (303) 906-2194

**Comment by dkager** [comment]
The Dutch tables are nl-BE-g0.utb (Belgium) and nl-NL-g0.utb (Netherlands).

**Comment by josephsl** [comment]
Hi, how about g1 files? Thanks.

**Comment by dkager** [comment]
The table has been renamed.

**Comment by jcsteh** [comment]
> The Dutch tables are nl-BE-g0.utb (Belgium) and nl-NL-g0.utb (Netherlands).

Ug. As is far too often the case in liblouis land, this is ridiculously confusing. The old tables still exist... but now we have these new ones.

1. How is anyone supposed to know which tables to use?
2. Why the rename? If these supersede the old ones, why not just replace the old ones?
3. What do we call these? Currently, NVDA calls nl-NL-g1.ctb "Dutch (Netherlands) grade 1". Should this now be grade 0? Or does Dutch only have one grade and we should just drop the "grade 1" bit?
4. Is this computer braille, uncontracted braille or contracted braille? I assume the last.

**Comment by dkager** [comment]
> 2.	Why the rename? If these supersede the old ones, why not just replace the old ones?

I thought they had been replaced. Something to look at.

> 3. What do we call these?

Dutch only has one grade, so dropping the "grade 1" in the name sounds fine. This is uncontracted literary braille.

**Comment by josephsl** [comment]
Hi,

@dkager: Thanks for the answer. Will apply it.

For other table maintainers: I think now is the time to tell us which tables are which, especially those that were modified (not due to opcode changes). Thanks.

**Comment by leonardder** [comment]
What do we call these?
    
      
        
        
      
      Dutch only has one grade, so dropping the "grade 1" in the name
        sounds fine. This is uncontracted literary braille.
      
    
    Don't we also have a Dutch computer braille code, even though it
    isn't in liblouis? Honestly, I think removing the grade from the
    name can cause confusion at some point.

**Comment by josephsl** [comment]
For @dkager: @jcsteh is thinking we should use LibLouis's own liblouis.def instead of nVDA's own. Doi you think it's safe to do now, and do you see some benefits and outstanding issues? Thanks.

**Comment by josephsl** [comment]
Hi,

In the end, due to file inclusion issues and build issues on Windows (vanilla Liblouis def), it was decided that NVDA will use its own liblouis.def. Thanks.

**Comment by jcsteh** [comment]
Merge note: This should not be merged to master until liblouis 3.0.0 final is released. Once that happens, do the following:

* [ ] Update the submodule.
* [ ] Update the liblouis version in readme.md.

What's New entry: in Changes:

```
- Updated liblouis braille translator to 3.0.0. (#6109, #4194)
 - If you are using either Dutch or Unified English Braille Code tables, you will need to manually select these again from NVDA's Braille Settings dialog.
```

**Comment by dkager** [comment]
Instead of the NMake file using liblouis.def we should probably have MSVC generate one. This requires some code changes I'll have to discuss with Christian.
Currently you can't compile findTable.c with MSVC, which is why the .def file causes trouble. Not a big fan of gnulib... :)

**Comment by dkager** [comment]
> Don't we also have a Dutch computer braille code, even though it isn't in liblouis? Honestly, I think removing the grade from the name can cause confusion at some point. 

No, the 2005 braille standard only includes an uncontracted 6-dot code. In the past we had multiple levels of contractions (3 I believe), but now we don't. So this is grade 0, but since there are no other grades we can leave that out IMO.

On a final note, the Netherlands and Belgium tables differ only in some character definitions. The rules are the same for the whole Dutch language region. At some point we wanted to consolidate the two tables, but it hasn't happened yet.

**Comment by jcsteh** [comment]
Merge note: On further reflection and discussion, this should not be merged to master until #6140 (backwards compat for renamed tables) is done.

**Comment by josephsl** [comment]
Hi, first commit on #6140 (for UEB series and Norwegian) will be done tonight, the rest will be done once beta comes out. Thanks.

**Comment by jcsteh** [comment]
I want to get this into 2016.3, so in the interest of speed, I've made a few tiny changes myself (rather than going back and forth with a tiny review).

**Comment by jcsteh** [comment]
@MichaelDCurran, can you please review [these commits](https://github.com/nvaccess/nvda/pull/6110/files/df8e22d3bc0e61b990c49fd07fb72ac1dbe56a6c..123b08d5ecb45ee138b2890c6c3271f84170e1c6)? I reviewed most of this, but then made some minor tweaks myself in the interest of speed when I was trying to get this into 2016.3 (a decision we obviously reversed). So, my small tweaks should probably be reviewed.

**Comment by michaelDCurran** [comment]
I am happy with these 4 commits.

**Pull request merged**
