### PR TITLE
Add advanced setting to allow UIA in chromium based browsers

### PR DESCRIPTION
**Pull request by LeonarddeR**
### Link to issue number:
Related to #10555 

### Summary of the issue:
UIA is now forcefully disabled in chrome based browsers. While this makes perfect sense, it could be beneficial for developers and/or development purpose to circumvent this without hacking.

### Description of how this pull request fixes the issue:
1. Adds an advanced setting that allows using UIA in Chromium based browsers, particularly in Edge. This option defaults to only when necessary, which is when UIA is exposed by the browser and we are unable to inject. If yes, UIA is used, but still only when UIA is exposed by the browser (not by default in Chrome). If no, there's just no browse mode when we can't inject.
2. Added NVDAObjects.UIA.web and NVDAObjects.UIA.chromium. The chromium module is meant to contain (Edge) Chromium specific code. The web module is meant to contain code shared between Edge Chromium and Edge Legacy. The Edge module contains Edge Legacy specific code. The code I moved to the web module was moved mainly by guessing what we'd need and what not, so some code in there can still be considered Edge legacy specific. It is very hard to assess this, though. I haven't considered renaming edge to edgeLegacy.

### Known issues (Todo)
- [ ] Update documentation
- [ ] Headings announcements are duplicated, probably because Edge Chromium both exposes them as control and format field. We'd have to decide what to use and whether the EdgeHeadingQuicknavIterator should be moved to the Web module.
- [ ] The makeTextInfo implementation of the Edge tree interceptor has been moved to the web tree interceptor, so is also used for Chromium. Without this, I"m getting lots of errors indicating that a range couldn't be cloned. This is either a bug in Edgium, or we need another workaround, as navigation in browse mode is still pretty buggy and bouncy.
- [ ] It looks like navigation by line is also broken, as I've seen several cases (e.g. at the top of babbage.com) where lines are broken into words.

### Testing performed:
* Tested in Edge that the config flag works.

### Change log entry:
t.b.d.

### CODE REVIEW

**Comment by codeofdusk** [comment]
On my machine, NVDA completely freezes with this PR in use:

1. Download the Appvayor build, and opt to continue running.
2. Set UIA in Chrome to "yes".
3. Start chrome (at the run dialog "chrome --enable-experimental-ui-automation").
4. Tab into the document.

**Comment by leonardder** [comment]
What version of chrome was this? I think it is likely that Microsoft works on the UIA implementation separately from the chromium project and that it's only merged into chromium when a major milestone has been reached. Therefore, we couldn't be sure that the UIA implementation in Edge 81 is the same as in Chrome 81, etc.

**Comment by codeofdusk** [comment]
Running Chrome 83.0.4103.34.

**Comment by codeofdusk** [comment]
I've just installed Chrome Canary (version 84) and retested. I get the following in the log:

```none
DEBUGWARNING - _UIAHandler.UIAHandler.IUIAutomationFocusChangedEventHandler_HandleFocusChangedEvent (03:12:56.765) - Dummy-3 (15196):
HandleFocusChangedEvent: Ignoring duplicate focus event
DEBUGWARNING - watchdog._watcher (03:13:07.013) - watchdog (16652):
Trying to recover from freeze, core stack:
  File "nvda.pyw", line 215, in <module>
  File "core.pyc", line 545, in main
  File "wx\core.pyc", line 2134, in MainLoop
  File "gui\__init__.pyc", line 1032, in Notify
  File "core.pyc", line 515, in run
  File "queueHandler.pyc", line 83, in pumpAll
  File "queueHandler.pyc", line 50, in flushQueue
  File "sayAllHandler.pyc", line 172, in nextLine
  File "speech\types.pyc", line 49, in _flattenNestedSequences
  File "speech\types.pyc", line 49, in <genexpr>
  File "speech\__init__.pyc", line 1116, in getTextInfoSpeech
  File "treeInterceptorHandler.pyc", line 231, in getTextWithFields
  File "NVDAObjects\UIA\__init__.pyc", line 716, in getTextWithFields
  File "NVDAObjects\UIA\__init__.pyc", line 686, in _getTextWithFieldsForUIARange
  File "NVDAObjects\UIA\__init__.pyc", line 686, in _getTextWithFieldsForUIARange
  File "NVDAObjects\UIA\__init__.pyc", line 686, in _getTextWithFieldsForUIARange
  [Previous line repeated 263 more times]
  File "NVDAObjects\UIA\__init__.pyc", line 594, in _getTextWithFieldsForUIARange
  File "NVDAObjects\UIA\__init__.pyc", line 428, in _getControlFieldForObject
  File "baseObject.pyc", line 42, in __get__
  File "baseObject.pyc", line 145, in _getPropertyViaCache
  File "NVDAObjects\UIA\__init__.pyc", line 1533, in _get_positionInfo
  File "NVDAObjects\UIA\__init__.pyc", line 811, in _getUIACacheablePropertyValue
  File "comtypesMonkeyPatches.pyc", line 26, in __call__

DEBUGWARNING - queueHandler.flushQueue (03:13:14.991) - MainThread (6988):
Error in func nextLine from eventQueue
Traceback (most recent call last):
  File "queueHandler.pyc", line 50, in flushQueue
  File "sayAllHandler.pyc", line 172, in nextLine
  File "speech\types.pyc", line 49, in _flattenNestedSequences
  File "speech\types.pyc", line 49, in <genexpr>
  File "speech\__init__.pyc", line 1116, in getTextInfoSpeech
  File "treeInterceptorHandler.pyc", line 231, in getTextWithFields
  File "NVDAObjects\UIA\__init__.pyc", line 716, in getTextWithFields
  File "NVDAObjects\UIA\__init__.pyc", line 686, in _getTextWithFieldsForUIARange
  File "NVDAObjects\UIA\__init__.pyc", line 686, in _getTextWithFieldsForUIARange
  File "NVDAObjects\UIA\__init__.pyc", line 686, in _getTextWithFieldsForUIARange
  [Previous line repeated 456 more times]
  File "NVDAObjects\UIA\__init__.pyc", line 704, in _getTextWithFieldsForUIARange
  File "NVDAObjects\UIA\__init__.pyc", line 489, in _getTextWithFields_text
  File "NVDAObjects\UIA\__init__.pyc", line 455, in _getTextFromUIARange
  File "comtypesMonkeyPatches.pyc", line 26, in __call__
_ctypes.COMError: (-2147220991, 'An event was unable to invoke any of the subscribers', (None, None, None, 0, None))
DEBUGWARNING - NVDAObjects.IAccessible.IAccessible._get_IAccessibleRole (03:13:16.347) - MainThread (6988):
accRole failed: (-2147024809, 'The parameter is incorrect.', (None, None, None, 0, None))
DEBUGWARNING - NVDAObjects.UIA.UIATextInfo.__init__ (03:13:16.361) - MainThread (6988):
Could not clone range
Traceback (most recent call last):
  File "NVDAObjects\UIA\__init__.pyc", line 296, in __init__
  File "comtypesMonkeyPatches.pyc", line 26, in __call__
_ctypes.COMError: (-2147220991, 'An event was unable to invoke any of the subscribers', (None, None, None, 0, None))
DEBUGWARNING - NVDAObjects.UIA.web.UIAWebTreeInterceptor.makeTextInfo (03:13:16.361) - MainThread (6988):
selection died. Using first position instead
ERROR - scriptHandler.executeScript (03:13:16.362) - MainThread (6988):
error executing script: <bound method CursorManager.script_moveByLine_back of <NVDAObjects.UIA.chromium.ChromiumUIATreeInterceptor object at 0x093FA950>> with gesture 'up arrow'
Traceback (most recent call last):
  File "NVDAObjects\UIA\__init__.pyc", line 296, in __init__
  File "comtypesMonkeyPatches.pyc", line 26, in __call__
_ctypes.COMError: (-2147220991, 'An event was unable to invoke any of the subscribers', (None, None, None, 0, None))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "NVDAObjects\UIA\web.pyc", line 392, in makeTextInfo
  File "cursorManager.pyc", line 448, in makeTextInfo
  File "treeInterceptorHandler.pyc", line 179, in copy
  File "NVDAObjects\UIA\__init__.pyc", line 759, in copy
  File "NVDAObjects\UIA\__init__.pyc", line 300, in __init__
RuntimeError: Could not clone range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "NVDAObjects\UIA\__init__.pyc", line 316, in __init__
  File "comtypes\__init__.pyc", line 279, in __getattr__
  File "comtypesMonkeyPatches.pyc", line 26, in __call__
_ctypes.COMError: (-2147220991, 'An event was unable to invoke any of the subscribers', (None, None, None, 0, None))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "scriptHandler.pyc", line 205, in executeScript
  File "cursorManager.pyc", line 214, in script_moveByLine_back
  File "cursorManager.pyc", line 114, in _caretMovementScriptHelper
  File "NVDAObjects\UIA\web.pyc", line 399, in makeTextInfo
  File "NVDAObjects\UIA\web.pyc", line 402, in makeTextInfo
  File "NVDAObjects\UIA\web.pyc", line 392, in makeTextInfo
  File "cursorManager.pyc", line 453, in makeTextInfo
  File "documentBase.pyc", line 24, in makeTextInfo
  File "treeInterceptorHandler.pyc", line 173, in __init__
  File "NVDAObjects\UIA\__init__.pyc", line 319, in __init__
RuntimeError
DEBUGWARNING - NVDAObjects.UIA.UIATextInfo.__init__ (03:13:16.372) - MainThread (6988):
Could not clone range
Traceback (most recent call last):
  File "NVDAObjects\UIA\__init__.pyc", line 296, in __init__
  File "comtypesMonkeyPatches.pyc", line 26, in __call__
_ctypes.COMError: (-2147220991, 'An event was unable to invoke any of the subscribers', (None, None, None, 0, None))
DEBUGWARNING - NVDAObjects.UIA.web.UIAWebTreeInterceptor.makeTextInfo (03:13:16.373) - MainThread (6988):
selection died. Using first position instead
ERROR - scriptHandler.executeScript (03:13:16.373) - MainThread (6988):
error executing script: <bound method CursorManager.script_moveByLine_forward of <NVDAObjects.UIA.chromium.ChromiumUIATreeInterceptor object at 0x093FA950>> with gesture 'down arrow'
Traceback (most recent call last):
  File "NVDAObjects\UIA\__init__.pyc", line 296, in __init__
  File "comtypesMonkeyPatches.pyc", line 26, in __call__
_ctypes.COMError: (-2147220991, 'An event was unable to invoke any of the subscribers', (None, None, None, 0, None))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "NVDAObjects\UIA\web.pyc", line 392, in makeTextInfo
  File "cursorManager.pyc", line 448, in makeTextInfo
  File "treeInterceptorHandler.pyc", line 179, in copy
  File "NVDAObjects\UIA\__init__.pyc", line 759, in copy
  File "NVDAObjects\UIA\__init__.pyc", line 300, in __init__
RuntimeError: Could not clone range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "NVDAObjects\UIA\__init__.pyc", line 316, in __init__
  File "comtypes\__init__.pyc", line 279, in __getattr__
  File "comtypesMonkeyPatches.pyc", line 26, in __call__
_ctypes.COMError: (-2147220991, 'An event was unable to invoke any of the subscribers', (None, None, None, 0, None))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "scriptHandler.pyc", line 205, in executeScript
  File "cursorManager.pyc", line 218, in script_moveByLine_forward
  File "cursorManager.pyc", line 114, in _caretMovementScriptHelper
  File "NVDAObjects\UIA\web.pyc", line 399, in makeTextInfo
  File "NVDAObjects\UIA\web.pyc", line 402, in makeTextInfo
  File "NVDAObjects\UIA\web.pyc", line 392, in makeTextInfo
  File "cursorManager.pyc", line 453, in makeTextInfo
  File "documentBase.pyc", line 24, in makeTextInfo
  File "treeInterceptorHandler.pyc", line 173, in __init__
  File "NVDAObjects\UIA\__init__.pyc", line 319, in __init__
RuntimeError
DEBUGWARNING - NVDAObjects.UIA.UIA._prefetchUIACacheForPropertyIDs (03:13:16.395) - MainThread (6988):
IUIAutomationElement.buildUpdatedCache failed given IDs of {30019, 30086, 30022, 30025, 30036, 30070, 30103, 30008, 30009, 30010, 30046, 30079}
DEBUGWARNING - eventHandler.executeEvent (03:13:16.396) - MainThread (6988):
error executing event: typedCharacter on <NVDAObjects.UIA.chromium.ChromiumUIA object at 0x0928BFD0> with extra args of {'ch': '\x17'}
Traceback (most recent call last):
  File "eventHandler.pyc", line 155, in executeEvent
  File "eventHandler.pyc", line 92, in __init__
  File "eventHandler.pyc", line 100, in next
  File "NVDAObjects\__init__.pyc", line 1047, in event_typedCharacter
  File "speech\__init__.pyc", line 966, in speakTypedCharacters
  File "api.pyc", line 264, in isTypingProtected
  File "baseObject.pyc", line 42, in __get__
  File "baseObject.pyc", line 145, in _getPropertyViaCache
  File "NVDAObjects\__init__.pyc", line 921, in _get_isProtected
  File "baseObject.pyc", line 42, in __get__
  File "baseObject.pyc", line 145, in _getPropertyViaCache
  File "NVDAObjects\UIA\web.pyc", line 321, in _get_states
  File "baseObject.pyc", line 42, in __get__
  File "baseObject.pyc", line 145, in _getPropertyViaCache
  File "NVDAObjects\UIA\__init__.pyc", line 1234, in _get_states
  File "NVDAObjects\UIA\__init__.pyc", line 814, in _getUIACacheablePropertyValue
  File "comtypesMonkeyPatches.pyc", line 26, in __call__
_ctypes.COMError: (-2147220991, 'An event was unable to invoke any of the subscribers', (None, None, None, 0, None))
```

**Comment by leonardder** [comment]
I also installed Chrome Canary. The point is that, when using alpha and force UIA so it will at least work on the address bar, the address bar itself isn't very accessible. Therefore I don't think these UIA implementations are in sync.

**Comment by michaelDCurran** [comment]
NV access is interested in this pr, specifically to support Edge on Windows 10 S with the NVDA store app (which cannot inject in-process). Edge 81 does not have the UIA freezing bugs last time I tested. I think we should only enable UIA for msEdge. Not all of Chromium, if this is possible.

**Comment by codeofdusk** [comment]
> I think we should only enable UIA for msEdge.

If the improved UIA implementation makes it to Chrome, wouldn't it significantly improve performance to enable it there as well?

**Comment by michaelDCurran** [comment]
We are still a long way off from UIA surpassing 
IAccessible2+virtualBuffers on the web in performance and quality. This 
may be a goal we are heading towards, but right now I feel we should 
only do it where it is absolutely necessary.

Also, This pr should honor both the advanced setting, and also if NvDA 
can't inject (appModule.helperLocalBindingHandle is 0) similar to how 
Microsoft Word works.

**Comment by josephsl** [comment]
Hi, provided that Google follows UIA best practices in Chromium/Chrome combo. Thanks.

**Comment by leonardder** [comment]
I'm happy to change this into something that only works in Edge, but it might help to know how Chrome and Edge UIA implementations related to each other. @michaelDCurran, would this be something Microsoft and/or Google could inform us about?

Note that in Chrome, the UIA support is still considered to be experimental and still needs a command line parameter to work. If they are the same implementations though, I don't see a reason to block UIA from working in Chrome if someone explicitly passes the experimental uiautomation cmd parameter.

**Comment by michaelDCurran** [comment]
I don't believe that Google has any plans to turn on UIA by default any 
time soon. Therefore, I think I agree it is okay to allow UIA to be used 
for all Chromium implementations if it is available and either the 
advanced setting in NVDA is on or NVDA cannot inject in-process.

But we would not want to publish the idea of UIA with Chromium too 
heavily here. UIA right now is not yet at all a suitable replacement 
where IAccessible2/virtualBuffers is possible.

This may very well change in the near future, but even if it did, it 
would only be useful in the latest builds of Windows 10.

But, for Edgium in Windows 10 S, it is necessary that NVDA can use UIA 
in that scenario.

**Comment by leonardder** [comment]
> But we would not want to publish the idea of UIA with Chromium too heavily here.

Agreed. So either the documentation should contain a huge disclaimer, or we should advertise the option as Edge specific, yet being chromium specific under the hood. I'd go for the former. We can reword the option in such a way that it mentions Edge and supported Chromium based browsers, for example.

**Comment by josephsl** [comment]
Hi, maybe the label would say something to the effect of “Use UIA in Chromium-based Microsoft Edge (experimental)”? Thanks.

**Comment by leonardder** [comment]
@michaelDCurran I have updated the initial description to reflect the current state of the pr. While I started this work, I"m afraid I neither have the time nor the skills to work further on this. You really know UIA much better than I do. May be @josephsl might be interested to take a look as well?

Note that the new UIA.web module contains code from the edge module, all moved around, so that makes reviewing this code a bit easier.

**Comment by josephsl** [comment]
Hi, I think it might be best to rename UIA.web to UIA.chromium for sake of consistency with IAccessible.chromium so that EdgeHTML code can be kept for backward compatibility and to support PWA’s. Thanks.

**Comment by leonardder** [comment]
At this time, access to the menu bar in Edge Canary is severely broken.

Letting my hands off this until things get more stable.

**Comment by leonardder** [comment]
> Hi, I think it might be best to rename UIA.web to UIA.chromium for sake of consistency with IAccessible.chromium so that EdgeHTML code can be kept for backward compatibility and to support PWA’s.

I'm a bit confused. UIA.web is meant for code that's shared between the legacy and the new Chromium code, but there's definitely a UIA.chromium package.

**Comment by josephsl** [comment]
Hi, in this case, ignore my comment above. Thanks.

**Comment by dingpengyu** [comment]
hi @leonardder 
 The following appears Conflicting files
source/NVDAObjects/UIA/edge.py
source/config/configSpec.py

**Comment by leonardder** [comment]
This pr has no priority yet, as collaboration with Microsoft might be 
necessary to get this right.

I will resolve conflicts whenever I'm able to resume work on this.

**Comment by leonardder** [comment]
@michaelDCurran Thanks for taking this further!
Just to make sure, I assume you are aware that every change done to UIA.web has to be tested in legacy Edge as well, at least on older versions of Windows 10? Even on current versions, the legacy Edge implementation is still used when searching in the start menu, for example.

**Comment by michaelDCurran** [comment]
In order for existing logic around when NVDA should and should not report the accessible name for a control, Chromium / Edge needs to expose aria-label in the UIA element's AriaProperties property. Edge classic did this previously, but Chrimum's UIA implementation does not.
See Chromium bug 1147700: 
https://bugs.chromium.org/p/chromium/issues/detail?id=1147700

**Comment by Adriani90** [comment]
cc: @aleventhal, @ObjectInSpace

**Comment by michaelDCurran** [comment]
@codeofdusk  Would you mind testing this branch again, and let me know if you see any freezes. Rememeber to turn on  Use UIA in Edge and other Chromium-based brwosers in NvDA's advanced panel.

**Comment by feerrenrut** [comment]
@michaelDCurran Could you double check the PR description to make sure it is still accurate please?

**Comment by dingpengyu** [comment]
The current pr build is not fully successful:
Some checks were not successful
1 failing and 1 successful checks
— AppVeyor build failed

thanks

**Comment by codeofdusk** [comment]
Running chrome with the --enable-experimental-ui-automation flag now uses UIA as expected (confirmed in Python console) and documents are browsable.

Opening [this page](https://en.wikipedia.org/wiki/Wikipedia:List_of_Wikipedians_by_number_of_edits) in IA2 chrome causes a hang of several seconds. The same page in UIA chrome loads almost instantly, but attempting to move by heading causes the browser to crash:

<details>
ERROR - scriptHandler.executeScript (05:10:01.927) - MainThread (15344):
error executing script: <bound method CursorManager.script_moveByLine_forward of <NVDAObjects.UIA.chromium.ChromiumUIATreeInterceptor object at 0x072F9630>> with gesture 'down arrow'
Traceback (most recent call last):
  File "NVDAObjects\UIA\__init__.pyc", line 297, in __init__
  File "comtypesMonkeyPatches.pyc", line 26, in __call__
_ctypes.COMError: (-2147220991, 'An event was unable to invoke any of the subscribers', (None, None, None, 0, None))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "NVDAObjects\UIA\web.pyc", line 411, in makeTextInfo
  File "cursorManager.pyc", line 481, in makeTextInfo
  File "treeInterceptorHandler.pyc", line 180, in copy
  File "NVDAObjects\UIA\__init__.pyc", line 780, in copy
  File "NVDAObjects\UIA\__init__.pyc", line 301, in __init__
RuntimeError: Could not clone range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "NVDAObjects\UIA\__init__.pyc", line 317, in __init__
  File "comtypes\__init__.pyc", line 279, in __getattr__
  File "comtypesMonkeyPatches.pyc", line 26, in __call__
_ctypes.COMError: (-2147220991, 'An event was unable to invoke any of the subscribers', (None, None, None, 0, None))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "scriptHandler.pyc", line 208, in executeScript
  File "cursorManager.pyc", line 255, in script_moveByLine_forward
  File "cursorManager.pyc", line 129, in _caretMovementScriptHelper
  File "NVDAObjects\UIA\web.pyc", line 418, in makeTextInfo
  File "NVDAObjects\UIA\web.pyc", line 421, in makeTextInfo
  File "NVDAObjects\UIA\web.pyc", line 411, in makeTextInfo
  File "cursorManager.pyc", line 486, in makeTextInfo
  File "documentBase.pyc", line 24, in makeTextInfo
  File "treeInterceptorHandler.pyc", line 174, in __init__
  File "NVDAObjects\UIA\__init__.pyc", line 320, in __init__
RuntimeError
</details>

**Comment by feerrenrut** [comment]
I've been looking at this, but I'm not sure how to review it effectively. Without tests or further documentation about why the changes are made and the circumstances in which they are required I'd only be rubber stamping it. 

I'd like to see a plan for making this area of the code easier to understand. How can we move away from large recursive functions with many pathways?

**Comment by josephsl** [comment]
Hi, one thing to keep in mind is what Narrator is doing these days – accessing Chromium’s IAccessible2 implementation through UIA, and a discussion around this time last year about making NVDA work with Edge 79 and later through IAccessible and a renewed effort to use UIA for Chromium support (required on Windows 10 in S mode). Thanks.

**Comment by feerrenrut** [comment]
One option is to rebase these commits to clean up the history. So that each commit message can explain the need for the change. Move classes / functions around first (without further modification), then further commits to fix up the things that need fixing with full explanations of why it needs to change in the commit message (eg the scenario where there is an issue). This would be with the goal to merge this rather than squash merge.

**Comment by feerrenrut** [comment]
Closing this PR as it is replaced by #12025

**Pull request closed without merging**
