### PR TITLE
Report list levels in MS Word without UIA

### LINKED ISSUE #2446: Allow NVDA to speak the bullets and numbering, and list levels  in Microsoft Word lists
**Reported by jhomme on 2012-06-13 11:00**
In Microsoft Word, NVDA knows that a paragraph has the list paragraph stile and other list styles. It would be very helpful to know which list item you are reading, and what level in the list you are working with if you are dealing with a multi-level list, such as an outline. The same goes with bullets of various kinds.

### PR DESCRIPTION
**Pull request by LeonarddeR**
N.b. this work is initiated by @vrdhn and was initially filed in pr #5506. I rebased the branch on current Master.

### Link to issue number:
Closes #2446

### Summary of the issue:
NVDA currently does not report the levels of nested lists in MS Word.

### Description of how this pull request fixes the issue:
Patches NVDAHelper to allow reporting of list levels.

### Testing performed:
Much testing needs to be done. For example,  I'm not yet sure whether @michaeldcurran's https://github.com/nvaccess/nvda/issues/2446#issuecomment-158818042 has been addressed yet. I will ask for review when I think that this is code is ready, but beforehand, testing is appreciated.

### Known issues with pull request:
Needs more testing

### Change log entry:
* New features
    + NVDA is now able to report the level of list items in Microsoft Word when dealing with nested lists. (#2446)

### CODE REVIEW

**Review by LeonarddeR — COMMENTED** [review]
It turns out that the review comments in https://github.com/nvaccess/nvda/issues/2446#issuecomment-158818042 haven't been addressed yet. I will take care for that.

**Comment by leonardder** [comment]
[**@michaelDCurran**](https://github.com/michaelDCurran) commented on [23 nov. 2015 00:26 CET](https://github.com/nvaccess/nvda/issues/2446#issuecomment-158818042 "2015-11-22T23:26:54Z - Replied by Github Reply Comments"):
> - In winword.cpp: rather than fetching the list level when getting the bullet, fetch it with the initial format fields (i.e. when we fetch line numbers and alignment).

A problem is that paragraphs also get a list level of 1, so we really need to fetch it around where it is fetched now.

> - in speech.py: handle list-level like we handle alignment etc... don't limit it to the existence of line-prefix.

Done, and it now also uses the cache.

I'm still struggling with cases where list items start with punctuation, in which case the list level is omitted in the announcements.

**Comment by leonardder** [comment]
@michaeldcurran: I've addressed all your concerns now, not sure whether I'm very happy with the approach though, since it will probably result in an increase in object model calls. However, as far as I understand it now, the list level has to be there in every format field, similar to how this work for page numbers and text column numbers. So, the code that makes NVDAHelper only fetch list formatting information in the first iteration of the loop has been removed.

I also added list level information in braille, removing a redundant space between lv and the level number while at it.

One additional thing is that I found it a bit of a weird experience when NVDA anounced list level information without out of list announcements. This would mean that, when you have a list item with multiple lines with a new paragraph below that is not part of the list, you wouldn't be able to know when you're leaving the list. Therefore, NVDA will now say out of list when getting out of a list. However, It causes the following issue:

1. type "1. test one" and press enter
2. NVDA anounces "list level 1 2.".
3. Press enter once more.
4. NVDA announces nothing
5. Start typing, you're outside the list already
6. Press enter. NVDA announces out of list.

**Comment by Adriani90** [comment]
There is an Explanation from @dkager related to list Levels also in #6815. If I confused something, we can reopen #2446 as well.

**Comment by leonardder** [comment]
This is currently far from stable. Closing this for now, might revisit it at a later date.

**Pull request closed without merging**
