### PR TITLE
Add-on store: Use close button instead of OK/Cancel

### PR DESCRIPTION
**Pull request by seanbudd**
### Link to issue number:
Part of #13985 

### Summary of the issue:
The add-on store makes more sense with a "Close" button instead of "OK/Cancel".
When exiting the dialog, users should be prompted to restart if they have changed the status of any add-ons.

### Description of user facing changes
The "OK/Cancel" buttons have been replaced by a single "Close" button.
Pressing enter no longer closes the dialog, but "escape" does.

### Description of development approach
The `SettingsDialog` now accepts "buttons" as a parameter. A developer can specify a set of buttons including OK, Cancel, Apply, Close.

### Testing strategy:
Manual testing:

**Closing the dialog prompts the user to restart when appropriate**
1. Open the add-on store
1. Disable an installed add-on
1. Try closing the dialog each of the following ways:
    - Pressing Escape
    - The dialog close button
    - The window close button - X at the top right of screen
1. Each time, the user should be prompted to restart NVDA.

**Enter keeps the dialog open**
1. Open the add-on store
1. Disable an installed add-on
1. Try closing the dialog by pressing Enter
1. Ensure the dialog remains open, as enter saves and exits the settings dialog by default

### Known issues with pull request:
None

### Change log entries:
N/A

### Code Review Checklist:

- [x] Pull Request description:
  - description is up to date
  - change log entries
- [x] Testing:
  - Unit tests
  - System (end to end) tests
  - Manual testing
- [x] API is compatible with existing add-ons.
- [x] Documentation:
  - User Documentation
  - Developer / Technical Documentation
  - Context sensitive help for GUI changes
- [x] UX of all users considered:
  - Speech 
  - Braille
  - Low Vision
  - Different web browsers
  - Localization in other languages / culture than English
- [x] Security precautions taken.

### CODE REVIEW

**Comment by seanbudd** [comment]
@XLTechie - no, that selects the filter by channel as of #14852 
Maybe the accelerator key needs to change in that PR.
I'll fix up and ensure the key works on this PR as well

**Comment by seanbudd** [comment]
@XLTechie - it seems like `alt+c` might not be easily supported. with the settings dialog it seems like having escape to close (via a button labelled by wx) and `alt+c` (a button we label) are mutually exclusive.
Given this, would `alt+c` be fine to filter by channel? I think escape to close is more common in NVDA.
I only see 3 dialogs with a `&Close` label (update check, add-ons manager, and incompatible add-ons dialog). There's no labels with `&Cancel` either.

**Comment by XLTechie** [comment]
I was afraid of that, but thought maybe you knew a way around it. Escape will be 
fine.

**Comment by XLTechie** [comment]
I haven't merged a copy of this PR to try it out yet, but I will remind of issue 
#14613. If there is no copy button or similar function in the new add-ons store 
interface, there likely will be eventually, and it will want a shortcut key.

I wrote an implementation for that in March, but ditched it when I realized you 
were replacing the manager entirely.

**Comment by seanbudd** [comment]
I imagine `ctrl+c` would be more appropriate for copying rather than `alt+c`

**Comment by XLTechie** [comment]
@seanbudd
> I imagine ctrl+c would be more appropriate for copying rather than alt+c

Agreed, but I wanted you to be aware of it in case there was some issue.

**Comment by CyrilleB79** [comment]
> @XLTechie - it seems like alt+c might not be easily supported. with the settings dialog it seems like having escape to close (via a button labelled by wx) and alt+c (a button we label) are mutually exclusive.

@seanbudd, if possible, could you explain why it was possible to have these two options in the add-on manager, and why they become mutually exclusive in the add-on store?

Regarding #14613, @seanbudd writes and @XLTechie agrees with:
> I imagine ctrl+c would be more appropriate for copying rather than alt+c

This may finally be a design discussion in #14613, but I think that control+c usually copies the current selection what is not expected here. Instead if there is a button to copy the whole add-on list with their information, a single button to copy them all is expected. And the best way to have a self-advertising shortcut is to use alt+letter so that the shortcut is reported and also discoverable with shift+pavNum2.

**Review by michaelDCurran — APPROVED** [review]

**Pull request merged**
