### PR TITLE
Determine add-on status based on tab of add-on store

### LINKED ISSUE #15029: Add-on Store: disabled add-ons should be checked for updates
### Steps to reproduce:

1. Disable an add-on which has an update available.
2. Restart NVDA.
3. Check for available updates.

### Actual behavior:

The add-on isn't listed as having any updates.

### Expected behavior:

Even though the add-on is disabled, if it has an update in the store, that update should be available to install.

### Reasoning:

If a version of an add-on is broken with respect to current NVDA, and it must be disabled in order to access the store, there is no way to acquire an updated version even if the store has one, short of removing the add-on, or going external.

Alternate: a version of an add-on currently does something I don't like. The newly released version fixes the issue. I don't want to enable it until I upgrade. I can't currently upgrade without enabling.

Example:
I currently have an external version (dev, though that doesn't matter) of an add-on installed.

Something about the latest alpha of NVDA doesn't cooperate with that version, and it breaks the speech.speech.speak method.
There is a stable version with a higher version number available in the store.

Because the add-on is preventing the store (and many other things) in NVDA from working, I can't leave it enabled when checking for updates. However if I disable it, NVDA doesn't show any updates available. Nor does it show in the store's list of available add-ons, so obviously NVDA recognizes that these are the same add-on.

Installed, it is 23.1.0-dev6 (external).
The store currently includes 23.1.1 (stable) of this add-on.
No update is offered while the add-on is disabled.

#### NVDA installed/portable/running from source:

Installed

#### NVDA version:

alpha-28447,cc222a06

#### Windows version:

10 Home 22H2

#### Does the issue still occur after restarting your computer?

Yes

#### Have you tried any other versions of NVDA? If so, please report their behaviors.

No

#### If NVDA add-ons are disabled, is your problem still occurring?

Yes

#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?

Yes

### LINKED ISSUE #15568: Add-on store: no updates present for add-ons forcefully enabled despite marked incompatible
Hi,

A variation of #15029 but applies mostly to NVDA alpha snapshots (for now):

### Prerequisites:
NVDA 2024.1 alpha, one or more add-ons marked incompatible with 2024.1 API, one or more of these add-ons enabled (overriding compatibility). updates released for at least one of these add-ons.

### Steps to reproduce:
1. From add-on store, make sure incompatible add-ons are enabled (forcefully a.k.a. overriding compatibility).
2. Restart NVDA when prompted.
3. Open add-on store, then go to available add-ons tab.
4. Make sure "include incompatible add-ons" is checked and channel is set to "all".
5. If updates are available, the new versions will be shown from available add-ons tab, hopefully these updates should be compatible with 2024.1 API (preferably dev builds).
6. Try installing add-on updates via context menu for "incompatible" add-ons.

### Actual behavior:
There is no "install/update" option in add-on context menu despite the updated add-on (or a dev build) declaring compatibility (and actually tested) with 2024.1 API (alpha).
 
### Expected behavior:
Updates can be installed (either from available or updatable add-ons tab).

#### NVDA installed/portable/running from source:
Installed

#### NVDA version:
alpha-29490,2adb77cb

#### Windows version:
Windows 11 23H2 beta (build 22631.2338)

#### Name and version of other software in use when reproducing the issue:
None

#### Other information about your system:
Add-on development workstation

#### Does the issue still occur after restarting your computer?
Yes

#### Have you tried any other versions of NVDA? If so, please report their behaviors.
NVDA 2023.2/2023.3 exhibits similar issues, although the main issue being discussed occurs with alpha builds

#### If NVDA add-ons are disabled, is your problem still occurring?
Yes

#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
Not applicable

### Additional context:
Some add-on authors would like to test their add-on(s) with alpha level code (with dev builds) and would like to also test add-on updating functionality provided by the add-on store.

Thanks.

### PR DESCRIPTION
**Pull request by seanbudd**
### Link to issue number:
Fixes #15029
Fixes #15568

### Summary of the issue:
Disabled add-ons were not listed in the updatable add-ons tab.
Add-ons with overridden compatibility were also not listed in the updatable add-ons tab.
Disabled incompatible add-ons should trigger the dialog to override when attempting to update.

Add-on statuses were the same for each tab of the add-on store, this limited determining actions for the add-on.

### Description of user facing changes
Add-on status is now contextual. to the add-on store tab Updatable/downloadable information is only shown on the updatable and available add-ons tab. Installed add-ons tabs now only show statuses relevant to installed add-ons. This means "update available" and "downloaded, pending install" will not be listed in the installed add-ons tab.

Disabled and incompatible add-ons can now be updated.
### Description of development approach
Created a new status and action for incompatible add-ons with an incompatible update available.

Ensure available and updatable statuses are checked before statuses for installed add-ons.
Ensure available and updatable statuses are only checked for their relevant tabs.
This means disabled and incompatible add-ons  return updatable status before checking their disabled/compatibility state.

### Testing strategy:
Manual testing with various states across various add-ons.
Particular cases:
- Updating "clip contents" in disabled/enabled state from incompatible version 27.1 to incompatible version 29.0.0 to compatible version 29.0.1

### Known issues with pull request:
None

### Code Review Checklist:

- [x] Documentation:
  - Change log entry
  - User Documentation
  - Developer / Technical Documentation
  - Context sensitive help for GUI changes
- [x] Testing:
  - Unit tests
  - System (end to end) tests
  - Manual testing
- [x] UX of all users considered:
  - Speech 
  - Braille
  - Low Vision
  - Different web browsers
  - Localization in other languages / culture than English
- [x] API is compatible with existing add-ons.
- [x] Security precautions taken.

### CODE REVIEW

**Comment by seanbudd** [comment]
cc @XLTechie and @josephsl as reporters of the issues

**Comment by Adriani90** [comment]
Why is the status „update available“ not shown in the installed addons tab? At least for me I would look at the installed addons and hope to see if there is an update available or not. From an Ux Perspektive, why are the updatable addons tab and the installed tabs as well as the incopatible addons tab not merged?
1. Under  The tab installed addons NVDA could report „Update available“ <addon name> when landing on the respective addon name with the system focus or the mouse cursor. Also addons which have an update available could be shown at the top of the list, similar to what poedit does for translation strings which should be updated. 
2. Since there is a filter to show incopatible addons already in place, why is this tab still needed? This filter could be added to the installed addons tab as well which would make the incompatible tab obsolete.

**Comment by seanbudd** [comment]
>Why is the status „update available“ not shown in the installed addons tab? At least for me I would look at the installed addons and hope to see if there is an update available or not. 

>Under The tab installed addons NVDA could report „Update available“ when landing on the respective addon name with the system focus or the mouse cursor. 

There's a wide range of statuses with similar importance which conflict with update available: for example "disabled", "disabled (incompatible)", "pending remove", etc. We could start showing a list of multiple current statuses, but that would get very verbose potentially.

>Also addons which have an update available could be shown at the top of the list, similar to what poedit does for translation strings which should be updated.

I think this would be better suited to a separate feature request, but I think the "updatable" tab much better handles the case you describe here. I think we should keep sorting methods in favour of #15277 

>From an Ux Perspektive, why are the updatable addons tab and the installed tabs as well as the incopatible addons tab not merged?

The idea of separate tabs is to be able to filter by different status groups. Initially this was done as a select control like the other filters, but tabs with headers are more common for this type of filtering.

>Since there is a filter to show incopatible addons already in place, why is this tab still needed? This filter could be added to the installed addons tab as well which would make the incompatible tab obsolete.

These are separate controls. For available and update tabs, this is to include both incompatible add-ons, which should be filtered out by default. For installed add-ons, it's to view incompatible add-ons separately.
This is because users often want to manage incompatible add-ons separately to currently installed ones. We had a separate list for these in add-ons manager.
This is similar logic to the update/available split based on action/intention, users often want to see the subset e.g. updateable/incompatible of the wider lists.

**Comment by XLTechie** [comment]
iOS offers sounds for many of these overly verbose but still important messages. 
However none of them are enabled by default. This is a good example to follow.
Earcons should always be "opt-in".

**Comment by Adriani90** [comment]
I agree. Then the user can decide if he or she wants to have higher or lower verbosity.Von meinem iPhone gesendetAm 30.11.2023 um 13:12 schrieb Luke Davis ***@***.***>:﻿
iOS offers sounds for many of these overly verbose but still important messages. 
However none of them are enabled by default. This is a good example to follow.
Earcons should always be "opt-in".

**Comment by seanbudd** [comment]
I think these feature requests are out of scope for this issue - which intends to fix 2 moderate bugs. I'd encourage separate issue proposals.

**Review by michaelDCurran — APPROVED** [review]

**Pull request merged**
