### PR TITLE
L10n fix typo for: de

### PR DESCRIPTION
**Pull request by mtelgkamp**
### Summary of the issue:
Fix small translation spelling errors

### Code Review Checklist:

- [x] Documentation:
  - Change log entry
  - User Documentation
  - Developer / Technical Documentation
  - Context sensitive help for GUI changes
- [x] Testing:
  - Unit tests
  - System (end to end) tests
  - Manual testing
- [x] UX of all users considered:
  - Speech 
  - Braille
  - Low Vision
  - Different web browsers
  - Localization in other languages / culture than English
- [x] API is compatible with existing add-ons.
- [x] Security precautions taken.

### CODE REVIEW

**Comment by zstanecic** [comment]
Hi,

For the translations fixups, use another repo, and consult with translators.

 

From: Michael Telgkamp ***@***.***> 
Sent: Friday, October 13, 2023 12:32 PM
To: nvaccess/nvda ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [nvaccess/nvda] L10n fix typo for: de (PR #15622)

 


Summary of the issue:


Fix small translation spelling errors


Code Review Checklist:


*	[X] Documentation: 

*	Change log entry
*	User Documentation
*	Developer / Technical Documentation
*	Context sensitive help for GUI changes

*	[X] Testing: 

*	Unit tests
*	System (end to end) tests
*	Manual testing

*	[X] UX of all users considered: 

*	Speech
*	Braille
*	Low Vision
*	Different web browsers
*	Localization in other languages / culture than English

*	[X] API is compatible with existing add-ons.
*	[X] Security precautions taken.

  _____  


You can view, comment on, or merge this pull request online at:


  https://github.com/nvaccess/nvda/pull/15622


Commit Summary


*	bfb4e2b <https://github.com/nvaccess/nvda/pull/15622/commits/bfb4e2b725f5fba4af3eaaf2aaca6719f67035e7>  L10n fix typo for: de


File Changes 


(1 <https://github.com/nvaccess/nvda/pull/15622/files>  file)

*	M source/locale/de/LC_MESSAGES/nvda.po <https://github.com/nvaccess/nvda/pull/15622/files#diff-56dde86a352f608efc03538e4b3779d824d23496e155e31e9895ba8e2bc01fae>  (2) 


Patch Links:


*	https://github.com/nvaccess/nvda/pull/15622.patch
*	https://github.com/nvaccess/nvda/pull/15622.diff

**Comment by CyrilleB79** [comment]
Grüss Gott @mtelgkamp!
And welcome to NVDA.

Thanks for your contribution.
However, the translations are not managed via GitHub but through another SVN repo contributed by translators of NVDA.

Most recent German translators are Rene Linke (do not know if he has a GitHub account), @Adriani90 and @hozosch.
Could you take this request into account? Thanks.

**Comment by hozosch** [comment]
Was it just this one string in the NVDA po file? I will fix this as soon as I can use my private machine again on which I've got the SVN repository.

**Comment by mtelgkamp** [comment]
I did not look for other strings. This was a mistake easy to fix, so I decided to create a pull request which was quick for me, but obviously not the way it should have been done.

Thank you, @hozosch, for bringing it forward.

**Comment by CyrilleB79** [comment]
> I did not look for other strings. This was a mistake easy to fix, so I decided to create a pull request which was quick for me, but obviously not the way it should have been done.

Yes. This show the lack of documentation on NVDA's side to report translation issues. Sorry.

**Comment by mtelgkamp** [comment]
> Yes. This show the lack of documentation on NVDA's side to report translation issues. Sorry.

Actually the documentation is available:
https://github.com/nvaccess/nvda/wiki/Translating
https://github.com/nvaccess/nvda/wiki/TranslatingUsingAutomaticProcess

But the process is not appealing for two small typos. (Joining the list, request to join "the workflow", ...).

Maybe it would have been better if I just had opened an issue with the typos.

But for issues, there are only templates for "Bug report", "Feature request" and "security vulnerability", where none of them really fits to my problem. As you responded very quickly here and there was already the assistance offered by @hozosch it might be worth considering adding a shortcut option for reporting simple translation problems.

**Comment by hozosch** [comment]
Just went ahead and fixed it. I think it's probably worked, but I didn't receive the SRT changeset Email. Oddly enough, I did receive a mail a few days ago where changes were made to French. What is wrong here?

**Comment by CyrilleB79** [comment]
> > Yes. This show the lack of documentation on NVDA's side to report translation issues. Sorry.
> 
> Actually the documentation is available: https://github.com/nvaccess/nvda/wiki/Translating https://github.com/nvaccess/nvda/wiki/TranslatingUsingAutomaticProcess
> 
> But the process is not appealing for two small typos. (Joining the list, request to join "the workflow", ...).

But this documentation is for people who want to contribute regularly to translations. It's not intended for a one-shot contribution to fix a typo.

> Maybe it would have been better if I just had opened an issue with the typos.
> 
> But for issues, there are only templates for "Bug report", "Feature request" and "security vulnerability", where none of them really fits to my problem. As you responded very quickly here and there was already the assistance offered by @hozosch it might be worth considering adding a shortcut option for reporting simple translation problems.

Yes. I have just opened #15627 for this. Feel free to comment there rather than in this now closed PR.

**Pull request closed without merging**
