### PR TITLE
Switch to official CLDR repository

### LINKED ISSUE #10955: Remove CLDR from the submodules
### Steps to reproduce:
CLDR files should be updated manually.
### Actual behavior:
Submodule repository is not always updated.
### Expected behavior:
NVDA's CLDR repository should be always updated. We should not rely on third-parties.
CC: @feerrenrut, @josephsl

### PR DESCRIPTION
**Pull request by OzancanKaratas**
### Link to issue number:
Fixes #10955
### Summary of the issue:
We are currently using an unofficial submodule repository.
### Description of how this pull request fixes the issue:
This pull request will migrate our submodule to the official repository.
### Testing performed:
1. Checked out to release 38.
2. The files were compiled for NVDA.
3. It works as expected.
### Known issues with pull request:
See the discussion in #10955.
### Change log entry:

Section: Changes
- Updated CLDR emoji annotation to version 38.

Note: I want to be officially maintainer for this. I will track the changes and open a pull request if new updates arrived.

Thanks.

### CODE REVIEW

**Comment by OzancanKaratas** [comment]
@leonardder, Linting error cannot be fixed. What should I do?

**Comment by OzancanKaratas** [comment]
CC: @michaelDCurran

**Comment by leonardder** [comment]
@feerrenrut I think we should consider disabling flake8 tests for our scons files. They are simply non-standard python files and will never conform to Flake8 checks unless ugly workarounds are applied.

**Review by LeonarddeR — DISMISSED** [review]
I think it is safe to ignore these linter errors for now.

**Comment by feerrenrut** [comment]
Yes, I agree, lets exclude the scons files from the linter for now.

**Comment by leonardder** [comment]
@OzancanKaratas If you don't mind, I've excluded the scons files from linting. Let's see whether it passes the tests now.

**Review by feerrenrut — DISMISSED** [review]
Thanks @OzancanKaratas and @leonardder

**Review by feerrenrut — APPROVED** [review]

**Comment by cary-rowen** [comment]
Hi,

I found an error in zh_CN.

In the file "NVDA\locale\zh_CN\cldr.dic", line 61
The content of this line is "@	@ 符号	none"
This will cause NVDA to report "@" as "at-sign sign". 
In fact, the content of this line should be "@	at	none".

Thanks.

**Comment by OzancanKaratas** [comment]
@cary-rowen:

> The content of this line is "@ @ 符号 none"
> This will cause NVDA to report "@" as "at-sign sign".
> In fact, the content of this line should be "@ at none".

This problem is caused by NVDA's lack of this mark in the Chinese dictionary file. To understand better, please refer to the symbols.dic file of the corresponding language file in the locale folder. Please contact the team that translated NVDA into Chinese to fix the issue. Unless this mark is translated, NVDA gets the description of the mark from the file cldr.dic.

**Comment by cary-rowen** [comment]
Hi,

Thanks for your reply.
I have corrected this in "symbols.dic" in Simplified Chinese, but I still hope that "CLDR.dic" can also correct it.

Thanks
@OzancanKaratas

**Pull request merged**
