### PR TITLE
Place the "Don't show this message again" checkbox to the left of it.

### LINKED ISSUE #15426: Add-on Store GUI: The "Don't show this message again" checkbox of the "Add-on Store Warning" dialogue box should be on the left side of its label.
The "Don't show this message again" checkbox in the "Add-on Store Warning" dialogue box should be on the left side of its label, but is currently on the right side of its label.
This should be consistent with the rest of the NVDA GUI, but I'm not sure if this point in #15246 commit serves any other purpose?

> Add support for creating labelled checkboxes using the `BoxSizerHelper`, `LabelledControlHelper` and `associateElements`

### Steps to reproduce:

In nvda.ini:

```
[addonStore]
	showWarning = False
```

open Add-on Store

### Actual behavior:

Visually the "Don't show this message again" checkbox is located to the right of its label.

### Expected behavior:

Visually the "Don't show this message again" checkbox is located to the left of its label.

#### NVDA installed/portable/running from source:

installed

#### NVDA version:

2023.2

### PR DESCRIPTION
**Pull request by hwf1324**
### Link to issue number:

Fixes #15426

### Summary of the issue:

The "Don't show this message again" checkbox in the "Add-on Store Warning" dialogue box should be on the left side of its label, but is currently on the right side of its label.

### Description of user facing changes

Visually the "Don't show this message again" checkbox is located to the left of its label.

### Description of development approach

Change the way to add `CheckBox` from `addLabeledControl` to `addItem` to be consistent with other GUIs.

### Testing strategy:

Visual check.

### Known issues with pull request:

none

### Change log entries:

Not needed

### Code Review Checklist:

- [x] Pull Request description:
  - description is up to date
  - change log entries
- [x] Testing:
  - Unit tests
  - System (end to end) tests
  - Manual testing
- [x] API is compatible with existing add-ons.
- [x] Documentation:
  - User Documentation
  - Developer / Technical Documentation
  - Context sensitive help for GUI changes
- [x] UX of all users considered:
  - Speech 
  - Braille
  - Low Vision
  - Different web browsers
  - Localization in other languages / culture than English
- [x] Security precautions taken.

### CODE REVIEW

**Comment by seanbudd** [comment]
Hi @hwf1324 - I forced pushed some changes to fix the underlying issue, rather than avoiding relying on our helper functions

**Review by seanbudd — APPROVED** [review]

**Comment by CyrilleB79** [comment]
@seanbudd why was it a problem to avoid using NVDA's helper functions? Everywhere in NVDA code base, NVDA does not use `addLabeledControl` but inserts directly the checkbox with `addItem`.

As https://github.com/nvaccess/nvda/issues/15426#issuecomment-1713913199 indicates, please have a look at screen curtain warning dialog.

**Comment by seanbudd** [comment]
@CyrilleB79 - it's better to fix the root problem, otherwise other instances of trying to use the helper function to add a labelled checkbox would cause the same issue.

The support for checkboxes in the helper function was added recently, for the same convenience reasons that the helper function exists for other controls.
Older instances which use the more verbose method can always be converted later.

**Comment by seanbudd** [comment]
@hwf1324 - can you explain the reasoning for the changes you pushed?

**Comment by CyrilleB79** [comment]
> @CyrilleB79 - it's better to fix the root problem, otherwise other instances of trying to use the helper function to add a labelled checkbox would cause the same issue.
> 
> The support for checkboxes in the helper function was added recently, for the same convenience reasons that the helper function exists for other controls. Older instances which use the more verbose method can always be converted later.

I do not know for which use case the support of checkbox in the helper function was added; it may be worth looking at it to understand if these are specific cases or not.

But on the contrary to combobox or edit field, wxPython's checkbox already implements the checkbox square and its label in the same control. Thus, there is no need to create a `wx.Checkbox` with no label and then associate our static text label thanks to our custom helper function. I feel that this encapsulation is more confusing.
The only case in which it can be useful is if you want to have the square located at the right of the label instead of having it located at its left as `wx.Checkbox` does.
Just my opinion though; the final decision is yours.

**Comment by hwf1324** [comment]
> @hwf1324 - can you explain the reasoning for the changes you pushed?

@seanbudd, I'm not sure I understand what you mean. 

My first thought was that it didn't match the look of the existing GUI interface, so I wanted them to be unified.

Then I found out through the "wxPython Widget Inspection Tool" that the checkbox is actually a combination of two controls.

For the mouse user, when they turn on the role of the object that reports what the mouse has moved to, the role for the `StaticText` control is just text, not a checkbox.

**Pull request merged**
