### PR TITLE
Fix port listing for seikantk driver

### LINKED ISSUE #13121: getPossiblePorts error with Seika Notetaker driver
### Steps to reproduce:
1. ctrl+nvda+a follow the usual steps to select the braille display.
2. Click the change button, Select Seika Notetaker in the combo box and press Enter;
3. Click the change button again;

### Actual behavior:
Perform step 2, the dialog box is closed, the device can display Braille, and an error sound is heard.
<details><summary>Log snippet
</summary><pre><code>
ERROR - unhandled exception (17:11:04.027) - MainThread (11824):
Traceback (most recent call last):
  File "gui\settingsDialogs.pyc", line 3437, in onDisplayNameChanged
  File "gui\settingsDialogs.pyc", line 3419, in updatePossiblePorts
  File "braille.pyc", line 2429, in getPossiblePorts
ValueError: need more than 1 value to unpack
Perform step 3, the braille display selection dialog box is not opened, and the following log is generated:
ERROR - unhandled exception (17:19:19.400) - MainThread (6204):
Traceback (most recent call last):
  File "gui\settingsDialogs.pyc", line 3328, in onChangeDisplay
  File "gui\settingsDialogs.pyc", line 194, in __init__
  File "gui\settingsDialogs.pyc", line 3380, in makeSettings
  File "gui\settingsDialogs.pyc", line 3411, in updateBrailleDisplayLists
  File "gui\settingsDialogs.pyc", line 3419, in updatePossiblePorts
  File "braille.pyc", line 2429, in getPossiblePorts
ValueError: need more than 1 value to unpack
</code></pre></details>

### Expected behavior:
Perform step 2 and there should be no errors.
Perform step 3 should be able to open the dialog box without errors.

#### NVDA installed/portable/running from source:
installed and portable

#### NVDA version:
2021.3rc1

#### Windows version:
Windows 10 21H2 (x64) build 19044.1387

#### Name and version of other software in use when reproducing the issue:
None

#### Other information about your system:
None

#### Does the issue still occur after restarting your computer?
Yes

#### Have you tried any other versions of NVDA? If so, please report their behaviors.
NVDA2021.2 has the same behavior

#### If NVDA add-ons are disabled, is your problem still occurring?
Yes

#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
Yes

### PR DESCRIPTION
**Pull request by feerrenrut**
### Link to issue number:
fixes #13121

### Summary of the issue:
Although the braille display can be used via automatic detection, trying to configure manually results in an error.
Braille expects to be able to call `ports.update(cls.getManualPorts())`, other drivers all return an iterator of tuples, each containing two strings. However the seikantk driver attempts to return the device path, from the log:
```
DEBUG - hwPortUtils.listHidDevices (12:56:39.981) - MainThread (1252):
{'hardwareID': 'HID\\VID_10C4&PID_EA80&REV_0100', 'devicePath': '\\\\?\\hid#vid_10c4&pid_ea80#6&392c7606&5&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}', 'provider': 'usb', 'usbID': 'VID_10C4&PID_EA80', 'vendorID': 4292, 'productID': 60032, 'versionNumber': 256, 'manufacturer': 'Silicon Laboratories', 'product': 'CP2110 HID USB-to-UART Bridge', 'HIDUsagePage': 65280}
```

### Description of how this pull request fixes the issue:
- Use the same approach as other device drivers, relying on `braille.getSerialPorts()`
- Corrects / adds missing type information.

### Testing strategy:
Since I do not have a device, I'll rely on reporters to test this PR.

### Known issues with pull request:
None

### Change log entries:
New features
Changes
Bug fixes
For Developers

### Code Review Checklist:

- [x] Pull Request description:
  - description is up to date
  - change log entries
- [x] Testing:
  - Unit tests
  - System (end to end) tests
  - Manual testing
- [x] API is compatible with existing add-ons.
- [x] Documentation:
  - User Documentation
  - Developer / Technical Documentation
  - Context sensitive help for GUI changes
- [x] UX of all users considered:
  - Speech 
  - Braille
  - Low Vision
  - Different web browsers
  - Localization in other languages / culture than English

### CODE REVIEW

**Comment by lukaszgo1** [comment]
While you're at it would it be possible to register the Seika driver for auto-detection the same way as other drivers i.e. by providing its data in `bdDetect` rather than inside the driver?

**Comment by feerrenrut** [comment]
@lukaszgo1 That sounds like a separate issue. Is there one open already? I think it should be done in an independent PR.

**Comment by lukaszgo1** [comment]
It looks like there are more mistakes in this driver i.e. the `check` method is overridden to unconditionally return `True` even when no Seika display is connected to the machine.

**Comment by feerrenrut** [comment]
@lukaszgo1 it seems like many of the drivers do this. I agree it doesn't look quite right, but it seems unlikely to be a unique problem. I think perhaps we should consider tidying that up in the 2022.1 release.

**Comment by feerrenrut** [comment]
I'm not confident that this change substantially fixes this driver, without a device or clear descriptions / logs of the remaining issues we won't know in the short term. I don't want to delay the 2021.3.1 release further, so I'll retarget this to master (it will become available in alpha builds).

It seems there are a number of issues remaining when using the seika notetaker device, anyone with one of these devices that is willing to work with us to test / and provide logs, please get in touch.

**Comment by cary-rowen** [comment]
Hello, as @moyanming said in #13121: This PR solves #13121 but there is another problem, which is unable to connect to Seika Notetaker using Bluetooth.
I have Seika Notetaker and I am very willing to assist with the test.

**Comment by cary-rowen** [comment]
@feerrenrut 

This fix is ​​completely effective for #13121, and I very much hope that it will appear in 2021.3.1 because #13121 is enough to bother all users who use Seika Notetaker.
Just imagine how boring you can’t open the dialog box as long as you use Seika. This is a serious bug, and 2022.1 is an add-on compatibility broken version. Many people may need to wait for the add-ons they depend on to be released before updating To 2022.1.
I very much hope to assist NVAccess in providing test logs, because I have Seika Notetaker.

Thanks

**Comment by feerrenrut** [comment]
@lukaszgo1 I have moved the `addUsbDevices` call to `bdDetect`.

**Comment by lukaszgo1** [comment]
> it seems like many of the drivers do this. I agree it doesn't look quite right, but it seems unlikely to be a unique problem.

Driver for a Seika Notetaker is the only driver for which we can auto-detect the display yet `check` returns `True` rather than fall back to the superclass implementation which ensures that display is listed only when connected. All other drivers for which `check` is shadowed either do not support auto-detection yet or cannot be detected passively i.e. because they're using a serial connection.

**Comment by feerrenrut** [comment]
Thanks @lukaszgo1, it's a helpful observation. I have removed the override for the check method.

**Review by seanbudd — APPROVED** [review]

**Comment by feerrenrut** [comment]
build of RC to test merged changes: https://ci.appveyor.com/api/buildjobs/pl56jgcjg2ym6xap/artifacts/output%2Fnvda_snapshot_rc-24378%2Ccaf14822.exe

**Pull request merged**
