### PR TITLE
Readme.md: upgrade windows10 sdk dimension 10.0.18362.0

### LINKED ISSUE #10332: Readme.md: upgrade windows10 sdk dimension 10.0.18362.0
hi NVDA currently used in appveyor windows10 sdk dimension 10.0.18362.0
### Steps to reproduce:
[From appveyor download log](https://ci.appveyor.com/api/buildjobs/l9y14i211uod8hl5/log)
Then find it from the log notepad: [00:01:14] Processing C:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um\oaidl.idl
### Actual behavior:
Update the windows10 sdk version of readme.md to 10.0.18362.0
### Expected behavior:
update windows10 sdk version
#### NVDA installed/portable/running from source:
no
#### NVDA version:
no
#### Windows version:
no
#### Name and version of other software in use when reproducing the issue:
no
#### Other information about your system:
no
#### Does the issue still occur after restarting your PC?
no
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
no
thanks

### PR DESCRIPTION
**Pull request by dpy013**
Readme.md: upgrade windows10 sdk dimension 10.0.18362.0
### Link to issue number:
Closes #10332 
### Summary of the issue:
Integrate the Windows 10 SDK version of NVDA readme.md with appveyor
### Description of how this pull request fixes the issue:
Readme.md: upgrade windows10 sdk dimension 10.0.18362.0
### Testing performed:
Tested using clone's NVDA repository
### Known issues with pull request:
no
### Change log entry:
no
Section: Changes
thanks

### CODE REVIEW

**Comment by leonardder** [comment]
I think we should consider removing the version of the SDK altogether, as it updates once in a while.

**Comment by lukaszgo1** [comment]
Perhaps saying something like:
> Windows 10  SDK version xxx or never

would be better.
I think that there probably is version of SDK too old for NVDA, and as far as I remember VS installer allows installing any version way back to the 10240. I have no idea what is the minimum required version - I personally have installed 17134 and build works.

**Comment by dingpengyu** [comment]
> I think we should consider removing the version of the SDK altogether, as it updates once in a while.
hi leonardder
Then does this PR need to be closed?
thanks

**Comment by josephsl** [comment]
Ideally 16299 due to Win10 utils and OneCore, but 10240 should work. Thanks.

**Pull request closed without merging**
