### PR TITLE
Fix #5267

### LINKED ISSUE #5267: Certain bullets not reported in Microsoft Word
**Reported by csm120 on 2015-08-05 09:05**
I have tried this in NVDA 2015.2 and in the latest snapshots.
Steps to reproduce:
1. In Microsoft Word 2010 through 2016 open a blank document
2. Press the star key (Shift 8 on numbers row) then type a line of text and press enter.
3. Type another line and press enter twice.
4. You should now have a bulleted list with 2 items.
5. Arrow through the list and on my end NVDA won't indicate that bullets are there.
6. Do the same steps above but instead of typing a star, type 1. As you type lines of text word automatically puts numbers pressing enter twice stops the auto-numbered list. Again NVDA doesn't indicate numbers here.

### PR DESCRIPTION
**Pull request by vrdhn**
This patch reads out commonly auto-converted bullet types in Word.
It converts these symbol from PUA to Unicode, and adds these to symbols.dic

### CODE REVIEW

**Comment by jcsteh** [comment]
Looks like you have to reference it in the comment, rather than the summary. So, this is for #5267.

**Comment by dkager** [comment]
Alternative solution: instead of replacing the PUA symbols with other Unicode symbols, we could replace them with the ASCII characters you type to get them. E.g. =>, <>, etc.
Advantage is that they are more likely to appear in the user's braille table.

**Comment by dkager** [comment]
[This](http://www.alanwood.net/demos/wingdings.html) looks like a good resource for mapping from the Wingdings font Word uses for some bullets to standard Unicode. Remove the 0xF0 prefix from the PUA codes and look them up in the table. Unfortunately, this doesn't quite match what is done in the PR. I will discuss it also with sighted users.

**Comment by dkager** [comment]
In Word you can also Save As --> Plain text --> UTF-8. This way Word transforms PUA codes into Unicode, although the result is not unambiguous. E.g. U+F0B7 and U+F0A8 are both transformed into U+2022 (bullet). Still, in my opinion it is a good idea to do what Word itself does.

The only problem is that you can no longer identify each individual list level, because some will share the same bullet symbol. But this is already a problem if you make a list with more than 3 levels, because then the bullets start repeating.

**Comment by dkager** [comment]
Closing this because #6778 supercedes it. This provided a valuable basis for the other PR, but I don't think we will be merging this one as-is. However, please reopen if I am overlooking something.

**Pull request closed without merging**
