### PR TITLE
Update contributing.md

### PR DESCRIPTION
**Pull request by simmocha**
Added steps for developers to quickly set up a development environment near the top of the document.  Relating to issue  #16601.

### Link to issue number:
https://github.com/nvaccess/nvda/issues/16601
### Summary of the issue:
Compiled a list of steps for developers to set up a development environment on their machines into the contributing.md document.  Steps were adapted mainly from documents in the "Overview of contribution process" section.
### Description of user facing changes
No changes for end-users.  Because of this, I did not make any updates to the changes.md file, but if that was incorrect, please let me know and I will update it right away.
### Description of development approach
Written using Github's built in editor to check the formatting and changes in real time.  There were only changes to the documentation, no coding changes.
### Testing strategy:
Github's editor to check formatting.
### Known issues with pull request:
None
### Code Review Checklist:

- [x] Documentation:
  - Change log entry
  - User Documentation
  - Developer / Technical Documentation
  - Context sensitive help for GUI changes
- [x] Testing:
  - Unit tests
  - System (end to end) tests
  - Manual testing
- [x] UX of all users considered:
  - Speech 
  - Braille
  - Low Vision
  - Different web browsers
  - Localization in other languages / culture than English
- [x] API is compatible with existing add-ons.
- [x] Security precautions taken.

### CODE REVIEW

**Comment by seanbudd** [comment]
@simmocha - I would encourage keeping specific instructions to `createDevEnvironment`, I don't think we want to encourage a case where someone sets up a dev environment while missing a step/information in `createDevEnvironment`. I don't think a "quick start guide" is necessarily a good idea, following the full steps is important. Would a brief summary of `createDevEnvironment` solve the issue you have?

**Comment by simmocha** [comment]
Oh, my apologies, I think I misunderstood what you meant in the Issue Request.  Yes, I could take a look into updating the createDevEnvironment file with a summary.  Thank you!

**Comment by seanbudd** [comment]
@simmocha - it doesn't have to be that specifically, I'm just trying to understand the problem you are trying to solve and the best way forward for it

**Comment by simmocha** [comment]
Thank you, and I think it might help clarify what I was trying to do if I start from the top.  When I had found the NVDA project, I wanted to download the source code to check it out.  However, I missed the guide in contributing.md, and instead navigated through the directory structure until I had found the projectDocs/dev directory, and used the createDevEnvironment.md and buildingNVDA.md files to get started.  

Because of the sort of roundabout path that I had taken, I had tried condensing the steps from those two files into a single guide, thinking it may make things easier for others.  But I see that the steps are already well laid-out in contributing.md and it was more my fault for overlooking them than a deficiency in the documentation.

So, I guess what I was originally looking to do was to make the steps for getting a dev environment a bit more prominent.  I am happy to try and make some edits in a PR if we still think that it may help with visibility/navigation; or if not, we can of course chalk it up to a simple human error on my part earlier.

Thank you!

**Comment by seanbudd** [comment]
> I am happy to try and make some edits in a PR if we still think that it may help with visibility/navigation

If you have any ideas for this it would be more than welcome, you aren't the only person to have this problem so improving the discoverability/navigability of our docs would be great

**Comment by simmocha** [comment]
Thank you, I'm happy to do some work on the documentation.  This time I think I'll start a little smaller.  I added a direct link to the setup steps in CONTRIBUTING.md, and made a minor change in projectDocs/dev/contributing.md to move the Visual Studio pre-configured environment into the same group as the other VS instructions.

Please let me know what you think! I'm fine making any recommended changes.

**Review by seanbudd — APPROVED** [review]
Looks good, thanks for the changes @simmocha !

**Pull request merged**
