### PR TITLE
Use locale for delayed character descriptions

### LINKED ISSUE #13966: Delayed descriptions for characters on cursor movement and Chinese characters
First of all I would like to say, I am not sure if this is a bug, please correct me if I am wrong.

### Steps to reproduce:
1. enabled the function Delayed descriptions for characters on cursor movement of the latest nvda beta, 2023.1 beta1, 
2. open a notepad and type some Chinese words, e.g. 香港
3. I try switching to Chinese Taiwan and Chinese Hong Kong locale to test this function
4. under each of the locale I use  arrow keys to move the edit cursor to check the character descriptions
5. the character description reported by nvda beta is the same for both of the characters in Chinese Taiwan and Chinese Hong Kong locale (where using the enhance phonetic addon switching locale will generate different character description)
6. Under both locale, nvda beta only reported the first available character description of both of the characters here (where using the enhance phonetic addon switching locale will report all of the available character descriptions)

Specifically using the character 港 as an example.
Using the nvda beta here, the character description for 港 is "香港" under hk and tw locale
but using the enhance phonetic reading addon, the character description under hk locale is "港	香港	港澳	港口	海港	商港	軍港	漁港	港區	港務局	轉運港	駐港領事館" and under tw locale is "港	港口	港灣	香港	海港	避風港	高雄港	(左半三點水，右半巷口的巷)"

### Expected behavior:
1. as Chinese locale has different character description under different locale, the character description being reported should be based on the current locale of the nvda
2. I am not sure if it is an intended function of the pull request to only report the first available character description instead of reporting all the available character description of a character, but I would really appreciate the nvda core to retain the function of enhance phonetic reading to report all available character description 

#### NVDA installed/portable/running from source:
portable

#### NVDA version:
nvda 2022.3 beta 1
#### Windows version:
windows 10 home ed 21h2
#### Does the issue still occur after restarting your computer?
not tried
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
not tried
#### If NVDA add-ons are disabled, is your problem still occurring?
this is a nvda portable version without any addon
#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
not tried

### LINKED ISSUE #13969: Delayed character description: language not honored
### Steps to reproduce:
NVDA in French (default) with a synthesizer able to speak French and Italian, e.g. eSpeak.

1. Open a webpage in Italian
2. Ensure automatic language switching is enabled in speech setting.
3. Press NVDA+Numpad2 twice
4. Press Numpad3, then numpad1 and wait for 1 second.

### Actual behavior:
* At step 3, the character description is in Italian and read with Italian TTS.
* At step 4, the character description is in Italian and read with French TTS (wrong pronunciation).

### Expected behavior:
* At step 3 and 4, the behaviour should be the same, i.e.: the character description is in Italian and read with Italian TTS.

### NVDA logs, crash dumps and other attachments:
Log can be provided if needed, but the issue seems quite simple. Please ask if needed.

#### NVDA installed/portable/running from source:
Installed
#### NVDA version:
2022.3beta1
#### Windows version:
10
#### Name and version of other software in use when reproducing the issue:
N/A
#### Other information about your system:
N/A
#### Does the issue still occur after restarting your computer?
Yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
No; new feature in 2022.3.
#### If NVDA add-ons are disabled, is your problem still occurring?
Yes
#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
Not tested but unrelated.

### Additional notes
* The processing done in `getSingleCharDescription` should be the same as the one done for one character in `_getSpellingSpeechWithoutCharMode`, so that what is reported when Numpad2 is pressed twice is the same as what is reported when "Delayed character description" feature is enabled.
* Issue due to same cause as #13966.

### PR DESCRIPTION
**Pull request by seanbudd**
### Link to issue number:
Fixes #13969 
Fixes #13966 

Background for the feature in PR https://github.com/nvaccess/nvda/pull/13550

### Summary of the issue:
NVDA does not correctly handle language switching commands when speaking character descriptions.

### Description of user facing changes
Ensure character descriptions are read in the proper locale where known.

### Description of development approach
Use the same code other spelling commands use, `_getSpellingSpeechWithoutCharMode`, which handles language switching.

### Testing strategy:

1. Enable delayed character descriptions
1. Open a browser window using the following data string: `data:text/html,<div lang="de" contenteditable="true">Hello! World</div>`
1. Navigate character by character, ensure characters are described with German phonetic descriptions.
1. Ensure "!" and space aren't described.

### Known issues with pull request:
None

### Change log entries:
None: unreleased feature

### Code Review Checklist:

- [x] Pull Request description:
  - description is up to date
  - change log entries
- [x] Testing:
  - Unit tests
  - System (end to end) tests
  - Manual testing
- [x] API is compatible with existing add-ons.
- [x] Documentation:
  - User Documentation
  - Developer / Technical Documentation
  - Context sensitive help for GUI changes
- [x] UX of all users considered:
  - Speech 
  - Braille
  - Low Vision
  - Different web browsers
  - Localization in other languages / culture than English

### CODE REVIEW

**Comment by CyrilleB79** [comment]
The test done in this PR checks #13969 has been fixed, but there is no test to check that #13966.

@LittleStar-VIP, would you mind test the build of this PR and check that all the descriptions are reported for a character if you enable delayed character description? Thanks.

**Comment by seanbudd** [comment]
@LittleStar-VIP  Here it is: https://ci.appveyor.com/api/buildjobs/gmt9bpa7aaud0yvv/artifacts/output%2Fnvda_snapshot_pr13972-26067%2C8c74c19b.exe

**Comment by LittleStar-VIP** [comment]
@seanbudd 
I tested this pr and there is a very strange result.
After creating a portable copy with the link provided above, I enabled the delay character description in nvda setting.
I test the function with the same word "香" which I had mentioned in the issue.
This time, both delay character description and pressing numpad 2 generate the same character description
however, both tw and hk locale still generate the same character description for the character 香 and the character description is 
香	香港	香蕉	香煙	蚊香	香味	香料	香水	芳香	檀香	中國香港	在香港以外

After comparing the character description of the respective folder, the above line of character description is found in the file "X:\NVDA PR\locale\zh\characterDescriptions.dic"

I remember somewhere else mentioned that the character description here is a no longer maintained file of character description.

**Comment by seanbudd** [comment]
@LittleStar-VIP - if the description is consistent across gestures, I think https://github.com/nvaccess/nvda/issues/13966 is fixed.
The changes since 2022.3beta1 should have no affect on the numpad2 character description.
`zh` and `zh_tw` both have the same description for `香` in `locale\zh\characterDescriptions.dic` and `locale\zh_tw\characterDescriptions.dic`: `香 香港 香蕉 香煙 蚊香 香味 香料 香水 芳香 檀香 中國香港 在香港以外`

**Comment by LittleStar-VIP** [comment]
@seanbudd 
If both the hk and tw locale generate the same set of character description then it is a great problem.
Currently, the character description for china, hong kong and taiwan are maintained by different group of people, and the character description of each of these locale are adapted to the local culture.

**Comment by LittleStar-VIP** [comment]
the character description for the word 香should be "香	香水	香港	香味	芳香	百里香	焚香頂禮" in tw

**Comment by seanbudd** [comment]
This PR is blocked by a test sample and STR for #13966, so that the behaviour for the sample can be compared with 2022.2 and this PR.

**Comment by LittleStar-VIP** [comment]
I have created a new issue regarding the character description problem which I mentioned above 
#13978

**Comment by seanbudd** [comment]
as the problem described in #13978 is not specific to delayed character description, I'm unblocking this PR and suggesting it closes #13966 as is

**Review by feerrenrut — APPROVED** [review]

**Pull request merged**
