### PR TITLE
Fix braille next line command for documents of Notepad++

### LINKED ISSUE #17430: Notepad++: braille doesn't move to the next line if last line is empty
### Steps to reproduce:
1. Open Notepad++.
2. In the opened document, type several lines.
3. Type `enter` to add an empty line.
4. Press `control+end` to move the system cursor to the end of the document.
5. Press `up arrow` to move the cursor to the previous line.
6. Try to run the `next line` command in a braille display.
### Actual behavior:
The cursor is not moved to the last line of the document
### Expected behavior:
The cursor should be moved to the last line of the document.

#### NVDA installed/portable/running from source:
Running from source
#### NVDA version:
source-master-c32e0e7 x86
#### Windows version:
Windows 11 23H2 (10.0.22631) workstation AMD64

#### Name and version of other software in use when reproducing the issue:
Notepad++ 7.81
#### Does the issue still occur after restarting your computer?
Yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
NVDA 2024.4.1, with same behavior.
#### If NVDA add-ons are disabled, is your problem still occurring?
Yes
#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
Yes

[nvda.log](https://github.com/user-attachments/files/17882085/nvda.log)

### PR DESCRIPTION
**Pull request by nvdaes**
### Link to issue number:
Fixes #17430 
### Summary of the issue:
Next braille line command doesn't work in Notepad++ documents when the last line is empty.
### Description of user facing changes
Next braille line command works as expected in Notepad++ documents.
### Description of development approach
The collapse method is overriden for Scintilla textInfo, so that textInfo is expanded to line before collapsing to end. In this way the cursor is properly moved to the end of the document when running the braille next line command.
### Testing strategy:
Tested manually in portable Notepad++ on Windows 11.
### Known issues with pull request:
None. Should be tested in different versions of Notepad++ and Windows.
### Code Review Checklist:

- [x] Documentation:
  - Change log entry
  - User Documentation
  - Developer / Technical Documentation
  - Context sensitive help for GUI changes
- [x] Testing:
  - Unit tests
  - System (end to end) tests
  - Manual testing
- [x] UX of all users considered:
  - Speech
  - Braille
  - Low Vision
  - Different web browsers
  - Localization in other languages / culture than English
- [x] API is compatible with existing add-ons.
- [x] Security precautions taken.

## Release Notes for NVDA 2024.1

- **New Features**
	- Support for the new HID Braille specification for automatic detection of multiple Braille displays.
	- Introduced "on-demand" speech mode, allowing users to control when speech is spoken.
	- Added "Native Selection" mode for Mozilla Firefox for improved text selection.
	- Add-on Store now alerts users of available updates at startup.
	- Support for Unicode normalization in speech and braille output.

- **Bug Fixes**
	- Resolved cursor movement issues in Notepad++ documents with new text handling features.

- **Improvements**
	- Enhanced performance and stability, especially in Microsoft Office applications.

### CODE REVIEW

**Comment by nvdaes** [comment]
I think that this is an API break change since the collapse method is changed in Scintilla TextInfo. So I'll document this in changes for developers.
I'll mark this as ready for review in case coderabbit can provide suggestions.
This bug was commented by @SaschaCowley in PR #17401

**Comment by nvdaes** [comment]
@coderabbitai review

**Comment by nvdaes** [comment]
@coderabbitai review

**Comment by nvdaes** [comment]
Since ScintillaTextInfo doesn't have unit tests, I'll wait for developers comments about this.

**Comment by nvdaes** [comment]
Thanks for your review, @seanbudd . I've applied your suggestions.

**Review by seanbudd — APPROVED** [review]

**Pull request merged**
