### PR TITLE
Recognize Windows 10 build 19043 as Version 21H1 (May 2021 Update)

### PR DESCRIPTION
**Pull request by josephsl**
Hi,

I guess ti has become sort of a tradition to do this semi-annually:

### Link to issue number:
None

### Summary of the issue:
Windows 10 build 19043 is Version 21H1 as noted in the following Windows Insider Program blog post:
https://blogs.windows.com/windows-insider/2021/03/25/releasing-windows-10-build-19043-906-21h1-to-beta-channel/

### Description of how this pull request fixes the issue:
Recognize build 19043 as Version 21H1. This is done in winVersion module and AppX XML.

### Testing strategy:
Manual testing - running NVDA from source on a computer running build 19043 to make sure the system is recognized as running 21H1.

### Known issues with pull request:
None

### Change log entry:
None

### Code Review Checklist:

This checklist is a reminder of things commonly forgotten in a new PR.
Authors, please do a self-review and confirm you have considered the following items.
Mark items you have considered by checking them.
You can do this when editing the Pull request description with an x: `[ ]` becomes `[x]`.
You can also check the checkboxes after the PR is created.

- [x] Pull Request description is up to date.
- [x] Unit tests.
- [x] System (end to end) tests.
- [x] Manual tests.
- [x] User Documentation.
- [x] Change log entry.
- [x] Context sensitive help for GUI changes.

## Additional context:
For @MichaelDCurran, I think it is safe to update AppX XML, as 19041/19042/19043 would support UIA Access privilege for converted desktop app such as NVDA.

Thanks.

### CODE REVIEW

**Comment by josephsl** [comment]
Hi,

IMPORTANT: April/May 2021 Update label guess is based on past experiences i.e. Version 2004 as May 2020 Update.

Thanks.

**Comment by feerrenrut** [comment]
@josephsl I'm not sure what your "Important note" is trying to tell me. Could you explain it in detail please?

I'm hesitant to merge this while based on a 21H1 beta announcement. Is there any chance the number might change? I'm going to convert this to a draft until we are confident about the plan.

**Comment by josephsl** [comment]
Hi,

The note refers to the marketing name for Version 21H1.

At the moment 21H1 is being tested by beta channel Insiders and commercial customers subscribing to release preview channel. I expect consumers on release preview channel will bet build 19043 at any day now, and when that happens, I'll transition this PR is ready for review (once a build goes out to release preview channel, the build number doesn't change unless a really serious showstopper shows up that affects critical system files, in which a new build number is generated; this was the case with Version 1803).

Thanks.

**Comment by josephsl** [comment]
Hi,

And indeed build 19043 is final (sent out to release preview channel subscribers):

https://blogs.windows.com/windows-insider/2021/04/28/preparing-the-windows-10-may-2021-update-for-release/

Thanks.

**Review by feerrenrut — APPROVED** [review]
Thanks @josephsl

**Pull request merged**
