### PR TITLE
Don't hide installed add-ons in available add-ons list

### LINKED ISSUE #15374: In the add-on store, if an add-on is already installed, it isn't shown in the list of available add-ons when working in that category
### Is your feature request related to a problem? Please describe.
At present, if you use the available add-ons category, add-ons already installed are not shown in the list.  I am assuming for this discussion, that the user is using the correct category such as all or stable when looking for the add-on.
### Describe the solution you'd like
All add-ons in the category, such as all stable add-ons, should be shown in the list when in available add-ons.  Available doesn't mean only uninstalled.  It means all add-ons offered in the store in the category..
### Describe alternatives you've considered
None.
### Additional context
The current method is going to cause a lot of confusion.  I check, from time to time, to see if there is an add-on for something someone asks about on a users list.  If I already have an add-on installed, such as Clipspeak and I look in available add-ons, I won't see it.  I may conclude that it is no longer offered in the store.
The correct way to do this is to show all add-ons in a category, then if someone mistakenly tries to install one that is already installed. bring up an error message that the add-on is already installed.  Or the add-on could show that it is installed next to the name such as, Clipspeak, installed.

### PR DESCRIPTION
**Pull request by seanbudd**
### Link to issue number:
Fixes #15374

### Summary of the issue:
At present, if you use the available add-ons category, add-ons already installed are not shown in the list. 
This is causing confusion, where users expect add-ons to listed in the available add-ons tab, regardless if installed.

The main use case is the following user story:
I am a user who has installed VeryCoolAddon. I want to recommend a friend to use it. I check in the add-on store via the "Add-on catalog" tab (formerly "Available add-ons" tab) that the add-on is still in the store and its version. Note: add-ons may be removed from the store for various reasons, so you cannot be certain if the add-on is still available in the add-on store if it is already installed.

### Description of user facing changes
add-ons which are already installed will no longer be hidden in the available add-ons list

### Description of development approach
Include all the same statuses in the installed add-ons tab in the available add-ons tab. (#15374)

### Testing strategy:
Manual testing

### Known issues with pull request:
None
### Change log entries:
Changes
- Add-on Store: Installed add-ons will now be listed in the Available Add-ons tab, if they are still available in the store.

### Code Review Checklist:

- [x] Pull Request description:
  - description is up to date
  - change log entries
- [x] Testing:
  - Unit tests
  - System (end to end) tests
  - Manual testing
- [x] API is compatible with existing add-ons.
- [x] Documentation:
  - User Documentation
  - Developer / Technical Documentation
  - Context sensitive help for GUI changes
- [x] UX of all users considered:
  - Speech 
  - Braille
  - Low Vision
  - Different web browsers
  - Localization in other languages / culture than English
- [x] Security precautions taken.

### CODE REVIEW

**Comment by leonardder** [comment]
I would honestly only include add-ons that are available in the add-ons store on the available tab. In other words, the available list should just contain all add-ons available in the add-ons store, regardless whether installed or not.
I think yet including installed add-ons no longer available in the store on the available tab causes more confusion than it solves.
That said, I wonder whether we could either have a status for add-ons that were installed from the store but no longer available, or mark these add-ons as external.

**Comment by seanbudd** [comment]
@leonardder - that is the current implementation, I'll update the PR description to be clearer

**Comment by leonardder** [comment]
Thanks. So just to make sure, installed add-ons either from an external source or no longer available in the store won't be listed? That's perfect!

**Comment by seanbudd** [comment]
Yes exactly

**Comment by CyrilleB79** [comment]
Users have no knowledge of "hidden" add-ons. Thus for the change log, I'd rather see something like:
Add-ons installed from the Add-on Store will now appear too in the available add-ons list

**Comment by seanbudd** [comment]
@CyrilleB79 - I don't think that description is accurate for this change. I also disagree that the notion of something being hidden is confusing.

**Comment by seanbudd** [comment]
@Qchristensen - what do you think about the change log entry here? would you be able to suggest an alternative changelog entry for this?

For reference:
The current behaviour is that if an add-on is currently installed, and no updates are available, it is filtered so that is not shown in the available add-ons list. This PR ensures that this filtering no longer happens.

**Comment by seanbudd** [comment]
>Add-ons installed from the Add-on Store will now appear too in the available add-ons list

 >installed add-ons either from an external source
 
 I just thought I'd mention that if an add-on has been installed from an external source but is available in the add-on store it will also be shown in the available add-ons tab

**Comment by CyrilleB79** [comment]
Testing this PR:
* When an add-on is installed, in the available list the status is "Enabled" or "Disabled". It would be better to have "Installed". Or if you prefer, "Installed, enabled" and "Installed, disabled", but I do not feel this precision is necessary.
* In the available add-on list, you can migrate to add-on store, install an add-on, enable or disable installed add-ons, but not uninstall installed add-ons. IMO uninstalling from available list should be added for coherence with the opposite possible actions (install or migrate)
* Any feedback to the suggestion to rename "Available add-ons" tab to "Add-on catalog"? No problem if you do not accept it, but just wanted to clarify it.

**Comment by XLTechie** [comment]
Thanks @seanbudd.

**Comment by XLTechie** [comment]
How about "Installed add-ons will now be listed in the Available Add-ons tab, if 
they are still available in the store."

I agree with Cyrille about documentation not previously discussing hidden 
add-ons, so users shouldn't be expected to understand about that.

**Comment by seanbudd** [comment]
thanks @XLTechie , that's a bit more accurate

**Comment by seanbudd** [comment]
>When an add-on is installed, in the available list the status is "Enabled" or "Disabled". It would be better to have "Installed". Or if you prefer, "Installed, enabled" and "Installed, disabled", but I do not feel this precision is necessary.

I understand that the status texts aren't ideal, however we believe it may be more confusing/misleading if the statuses are different depending on the add-on list tab you are viewing,

>In the available add-on list, you can migrate to add-on store, install an add-on, enable or disable installed add-ons, but not uninstall installed add-ons. IMO uninstalling from available list should be added for coherence with the opposite possible actions (install or migrate)

Making actions available depending on the add-on list being viewed is currently intended behaviour.

>Any feedback to the suggestion to rename "Available add-ons" tab to "Add-on catalog"? No problem if you do not accept it, but just wanted to clarify it.

I don't see a clear reason to rename this, but if there is popular support for this change we can consider it in future.

**Review by michaelDCurran — DISMISSED** [review]

**Comment by XLTechie** [comment]
@seanbudd Since external add-ons may have never been in the store, maybe the 
word "still" from my wording shouldn't be in that change listing.

**Pull request merged**
