### PR TITLE
displayModel: second try at recording the actual background color for text when a transparant background color is set.

### LINKED ISSUE #6467: Display model reports the wrong background color for text drawn in transparent mode
When text is written with the GDI background mode set to transparent, the display model doesn't necessary report the correct background color for that text. In this case, the GDI hook should look at the actual background color before the text is drawn, rather than using the result of `GetBkColor`.

### PR DESCRIPTION
**Pull request by michaelDCurran**
This PR is based on PR #6844 which was reverted due to performance reasons.

It improves upon #6844 by only calling GetPixel if the text being written  is using a bk mode of transparent, greatly reducing the amount of calls.

This extra commit from @mwcampbell was provided as a patch attached to #6467. 
Fixes #6467

### CODE REVIEW

**Review by michaelDCurran — COMMENTED** [review]
I had previously reviewed and approved pr #6844.  This last commit looks good.

**Comment by derekriemer** [comment]
@michaelDCurran It looks like you updated this, can you give a status report on what is in next?

**Comment by michaelDCurran** [comment]
@derekriemer:  This pr was a little bit stuffed up. I think because git doesn't handle adding back duplicate code after a revert. I have now re-done the branch by cherry picking all mat's commits, and force pushed to this pr. I have also triggered a try build... Please test the try build and let me know if this works again. If so, I will re-incubate to next. 
https://ci.appveyor.com/project/NVAccess/nvda/build/try-i6467-14259%2c69dba6ce

**Comment by derekriemer** [comment]
it worked!!!!! Thanks for expediting this.

**Comment by Rob-Hudson** [comment]
This commit causes a lag when switching windows a document interface such as mIRC. Specifically edcf518a405823d439f3c5fea23d4434267c3992is.

**Comment by derekriemer** [comment]
We need steps to reproduce please.

**Comment by tspivey** [comment]
I can also reproduce this.
Run mIRC, connect to a server and repeatedly press control tab to switch windows. After this commit, NVDA is much slower at reporting the window switch. Roughly 100 MS vs. 400-500, using gestureTiming.
That was with the window full of channel text.

**Comment by derekriemer** [comment]
@michaelDCurran

**Comment by michaelDCurran** [comment]
I'm not going to pull this out at this late stage as it was already in 2017.3. However,  as this is now the second time this has caused a problem, it is very likely this will be removed again.  Perhaps in future we can come up with a way to configure this, so that it is only used for Dictation Bridge.

**Comment by leonardder** [comment]
[**@michaelDCurran**](https://github.com/michaelDCurran) commented on [27 nov. 2017 08:04 CET](https://github.com/nvaccess/nvda/pull/7440#issuecomment-347095482 "2017-11-27T07:04:39Z - Replied by Github Reply Comments"):
> it is very likely this will be removed again.  Perhaps in future we can come up with a way to configure this, so that it is only used for Dictation Bridge.

I'd prefer this to be at least configurable with a hidden config parameter or something similar.

**Comment by Rob-Hudson** [comment]
No, this was not in 2017.3 and there is, therefore, no lagging.

**Comment by michaelDCurran** [comment]
Ah, you're right. It was Merged just after.

**Comment by derekriemer** [comment]
> I'd prefer this to be at least configurable with a hidden config parameter or something similar.

Or an attribute on the NVDA objject? That way it only turns on in certain areas.

**Comment by michaelDCurran** [comment]
Sadly, we currently have no mechanism to convey configuration to 
nvdaHelperRemote right now. This would have to be invented.
Some options are:
* Add another shared memory variable to store flags for 
nvdaHelperRemote. Injection_initialize would take an extra argument and 
set this variable on initialization. DisplayModel could read this 
variable in-process.
* Add a new RPC function to specifically enable displayModel transparent 
color detection. Note though that this would only work for future text 
writes, anything written up to when the function was could would not 
have its transparent color detected. thus the user would have to some 
how refresh the screen either by alt+tabbing or, code could call 
redrawWindow (though that is some what  expensive).

I think I like the first option the best.

So, moving forward, either we:
* Back this out completely for now. Ship an rc3, wait a few days, and 
then release.
* Don't back this out and ship the release, dealing with the consequence 
of NVDA being slower for some people (again).
* Create a new pr to make this configurable, review it, merge it to both 
rc and master. Release rc3. Wait  a good while (over a week preferably), 
and then release.

**Comment by leonardder** [comment]
[**@michaelDCurran**](https://github.com/michaelDCurran) commented on [27 nov. 2017 22:58 CET](https://github.com/nvaccess/nvda/pull/7440#issuecomment-347342473 "2017-11-27T21:58:36Z - Replied by Github Reply Comments"):
> * Back this out completely for now. Ship an rc3, wait a few days, and 
> then release.

I think I prefer this.

**Comment by Brian1Gaff** [comment]
I have to say I'm very confused what this is about. From comments does it 
only come into play in Dictation bridge? If so, then maybe this belongs in 
an add on in any case?

But reading a bit further it seems its in need of deep system access, and if 
that does mean speed is reduced, then we do not want it to affect stuff 
people use  a lot for something that they might not.
 In the end, I'd agree why chance it when there are no doubt other niggles 
going to come up, like the one with Chrome and comboo boxes that might 
affect more people given so many switching away from firefox.
 Brian

**Comment by michaelDCurran** [comment]
@Rob-Hudson and @tspivey:   
A try build with this pr reverted: https://ci.appveyor.com/api/buildjobs/vumey63f8kg079cv/artifacts/output%2Fnvda_snapshot_try-pr7440_revert-14666%2C89ad5a5d.exe
Please test and let me know as sppon as possible if the performance issue has been fixed. This is a build of pr #7803 which simply reverts this pr, removing the calls to GetPixel.
If all is okay, #7803 will be merged into rc, and rc3 will be made, and then a final release next week.

**Comment by Rob-Hudson** [comment]
This snapshot seems to have reversed the issue. All is well again, on this end.

**Pull request merged**
