### PR TITLE
Announce context menus in Outlook 2016 and existance of submenus

### PR DESCRIPTION
**Pull request by michaelDCurran**
### Link to issue number:
Fixes #9171 

### Summary of the issue:
With the merging of #8919 context menus in Outlook started using UI Automation. However, this caused them not to be announced when they first appeared.
The UIA implementation for NetUI context menus does some strange things like focusing a fake unlabeled menu item when the menu first appears. This fake menu item does not have the focused state.
Also, menu items in these menus that have a submenu is not conveyed to the user, as they expose the collapsed/expanded states, rather than the haspopup state.
But, NVDA currently filters out collapsed/expanded states on all menu items.

### Description of how this pull request fixes the issue:
Create an overlay class for the special UIA fake placeholder NetUI menu item, which bounces focus up to the menu itself so that it is better presented.
Also, now only suppress collapsed/expanded states from menu items if the menu item has the haspopup state.

### Testing performed:
Opened a context menu in the Outlook inbox. NVDA announced the context menu. Arrow3ed down the menu listening to the options. NVDA announced collapsed for all menu items with submenus.

### Known issues with pull request:
None.

### Change log entry:
None needed.

### CODE REVIEW

**Review by LeonarddeR — APPROVED** [review]
This works as expected, two things I'd like to bring up though:

1. The context menu of mail items in Outlook is announced as "context menu menu", probably because the name of the context menu has menu in it. I guess there's nothing to do about this and we can safely ignore it. It is not a bug in our end, Microsoft just should not use the word menu in the name of a menu
2. When expanding a sub menu, NVDA quickly announced expanded before descending into the sub menu. This makes sense to me because you realise you're entering the sub menu. Still, I'm slightly bothered with the inconsistency this pr introduces, most sub menus being announced with the submenu state, others with the collapsed state.

**Comment by michaelDCurran** [comment]
In regards to collapsed / expanded: I would argue that is just the way 
Microsoft is heading with things. This pr is certainly more literal as 
to what Microsoft implemented / expects.

Obviously this is not going to change older menus that use haspopup.

We could instead map both collapsed/expanded to haspopup for menu 
items... but is that removing some information simply for the sake of 
history? I'm not sure.

**Comment by leonardder** [comment]
> We could instead map both collapsed/expanded to haspopup for menu items... but is that removing some information simply for the sake of history? I'm not sure.

Hmm it looks like the UIA MSAA proxy is doing it the other way around, mapping haspopup to collapsed. When I enforce UIA in notepad for example, the zooming submenu has the collapsed state. Mapping haspopup to collapsed might also make sense with regard to #9096.

**Comment by josephsl** [comment]
Hi, it isn’t just Outlook – I may have seen this in some Windows 10 menus (particularly Start menu/context menu for items). Also, in Edge, existence of submenus are not reported for items which does expose expand/collapse state. Thanks.

**Pull request merged**
