### PR TITLE
run ruff format to fix whitespace changes

### LINKED ISSUE #12261: Fix a load of linting issues
I am analysing the NVDA codebase for a university course and I noticed there are many linting issues such as whitespaces that show up when you run Flake8 on the whole source folder instead of the diffs.

### Is your feature request related to a problem? Please describe.
There are many linting issues in the source code that can be fixed with auto-formatting.

### Describe the solution you'd like
Apply an auto-formatter on all or the most important files. 

### Describe alternatives you've considered
Not all Flake8 erros are fixed with auto-formatting, so you could fix all the auto-format warnings in one go and leave in the other problems, or you could focus file by file and fix the other issues manually. In that case it would probably be a good plan to focus on important files first.
Regardless of that, it might be more practical to do only a couple of files at a time, since other people are also working on changes of course.

### Additional context
Currently linting is only checked on the diffs. When you check the full project, it is full of old linting issues. If a large batch of these are fixed in one go, it would become easier for others to contribute, since they will not have to deal with as many existing issues they are asked to fix, just because they had to change those lines.
I would be happy to take up this issue if the community thinks this is a good thing to do. If so, my main question is if I should focus on a couple of files and any thoughts on what files would be the most important.

### PR DESCRIPTION
**Pull request by seanbudd**
**Must be merge commit not squash merge**

### Link to issue number:
Follow up to #16767 
Closes #12261

### Summary of the issue:
When migrating to ruff in #16751, we failed to lint scons files, and also run `ruff format` on the repository.
Ruff format fixes whitespaces issues in python files.

### Description of user facing changes
None

### Description of development approach

Perform lint fixes on scons files and run ruff format.
```cmd
# lint scons files
ruff check --fix
ruff check --add-noqa

# add trailing commas
pre-commit run --all-files add-trailing-comma

# format and re lint
ruff format
ruff check --fix
ruff check --add-noqa
```

### Code Review Checklist:

- [ ] Documentation:
  - Change log entry
  - User Documentation
  - Developer / Technical Documentation
  - Context sensitive help for GUI changes
- [ ] Testing:
  - Unit tests
  - System (end to end) tests
  - Manual testing
- [ ] UX of all users considered:
  - Speech 
  - Braille
  - Low Vision
  - Different web browsers
  - Localization in other languages / culture than English
- [ ] API is compatible with existing add-ons.
- [ ] Security precautions taken.

@coderabbitai ignore

## Summary by CodeRabbit

- **Refactor**
    - Updated code formatting for consistency and readability across multiple scripts.
    - Standardized string delimiters to double quotes in various scripts.
    - Simplified function signatures and command calls for better code clarity.

- **Style**
    - Made comments compliant with PEP 8 guidelines.
    - Improved alignment and spacing in variable assignments and import statements.

### CODE REVIEW

**Comment by seanbudd** [comment]
@coderabbit ignore

**Comment by LeonarddeR** [comment]
It looks like ruff collapses several function definitions into one line that were previously split into multiple lines.
I wonder [Add-trailing-comma](https://github.com/asottile/add-trailing-comma) can help us here.

**Comment by LeonarddeR** [comment]
Yes, it definitely helps. It leaves single line definitions alone while adding trailing commas to multi line definitions. I think this is exactly what we need to make our formatting a bit more conservative.

@coderabbitai what is your opinion about using the `add-trailing-comma` package from pip?

**Comment by seanbudd** [comment]
blocked by https://github.com/nvaccess/nvda/pull/16804

**Pull request merged**
