### PR TITLE
Emoji panel and clipboard history system tests

### PR DESCRIPTION
**Pull request by seanbudd**
### Link to issue number:

None

### Summary of the issue:

To aid reviewing future work on the emoji panel and clipboard history and #11485, system tests for these Windows features are needed.

### Description of how this pull request fixes the issue:

Introduces system tests which (covers most of the manual testing in #11485):

- Opening clipboard history and navigating it
- Opening emoji panel, ensure the first item read is an emoji. (Note: excluded, see known issues)
- Toggling between emoji panel and clipboard history without closing them. (Note: excluded, see known issues)
- Searching for emoji items, navigating them. (Note: excluded, see known issues)

### Testing strategy:

See PR builds. Run system tests locally as well as windows versions implement these features differently.

### Known issues with pull request:

As discussed on https://github.com/nvaccess/nvda/pull/11485#issuecomment-841047715, Windows versions implement these features differently and Microsoft plans to update them further. As a result, the AppVeyor tests may need to be updated or excluded if they start to fail and work on fixing the emoji panel or clipboard history can be prioritised. Additionally, these tests ideally should be run on various Windows versions to ensure nothing has broken across implementations. 

For example: searching for emojis is not implemented on the AppVeyor implementation of the emoji panel. As such, this test fails and needs to be excluded.
https://ci.appveyor.com/project/NVAccess/nvda/builds/39392852/tests

Emoji related tests need to be excluded until #11485, as the emoji panel does not always announce an emoji when opening the 
emoji panel. This can be observed with this build, where 2 tests involve opening the emoji panel and expecting an emoji announced but only one passes. https://ci.appveyor.com/project/NVAccess/nvda/builds/39404151/tests

### Change log entries:

None needed

### Code Review Checklist:

- [x] Pull Request description is up to date.
- [x] Unit tests.
- [x] System (end to end) tests.
- [x] Manual testing.
- [x] User Documentation.
- [x] Change log entry.
- [x] Context sensitive help for GUI changes.
- [x] UX of all users considered:
  - Speech 
  - Braille
  - Low Vision
  - Different web browsers

### CODE REVIEW

**Comment by josephsl** [comment]
CC @MichaelDCurran as it could open up a possibility to test IME candidates support in the future (IME candidates also covers hardware keyboard input suggestions, but not sure how to get that going in the future).

Thanks.

**Comment by leonardder** [comment]
Could we ensure that these tests never run on older versions, i.e. Windows 8.1 and older? This doesn't matter for appveyor, but for manual testing, exclusion would be appreciated.

**Comment by josephsl** [comment]
Hi, I think perhaps a condition flag should be specified in Robot somehow that will exclude certain tests from being performed if winVersion.getWinVer() </>= winVersion.WIN*. For Windows Insider Preview, we need to rely on winVersion.getWinVer().build as we won’t know what the final build number will be until it ships to beta channel. Thanks.

**Comment by seanbudd** [comment]
>Could we ensure that these tests never run on older versions, i.e. Windows 8.1 and older? This doesn't matter for appveyor, but for manual testing, exclusion would be appreciated.

Would it be troublesome to just include `--exclude windowsTests` if you wish to ignore these? Having expected failures locally shouldn't really be an issue if it is clear why they are failing. I think ideally we should make a separate robot args files for appveyor and various developer environments. As it stands now, system tests are used mostly by appveyor. Locally, I tend to only run tests relevant to the work I'm doing.

**Comment by seanbudd** [comment]
I've added some more explicit tags so that you can `--exclude emoji` and `--exclude clipboard` instead if preferred.

**Comment by seanbudd** [comment]
I want to change this to use our notepad system tests when that is merged in on #11856

**Pull request closed without merging**
