### PR TITLE
Support IA2_ROLE_BLOCK_QUOTE.

### PR DESCRIPTION
**Pull request by jcsteh**
### Link to issue number:
None.

### Summary of the issue:
1. The new ARIA role="blockquote" is exposed by Firefox 63, but NVDA does not report it.
2. HTML blockquote in Firefox 63 is reported as "unknown" when using object navigation.

### Description of how this pull request fixes the issue:
This PR adds support for the new IA2_ROLE_BLOCK_QUOTE, which is used by Firefox 63.

### Testing performed:
1. Tested that with `data:text/html,<div role="blockquote">ARIA</div>`, the presence of a block quote is reported in Firefox Nightly in both browse mode and focus mode.
2. Tested that with `data:text/html,<blockquote>HTML</blockquote>`, the presence of a block quote is reported in Firefox Nightly in both browse mode and focus mode.
3. Tested that with `data:text/html,<blockquote>HTML</blockquote>`, the presence of a block quote is reported in Chrome Canary in both browse mode and focus mode.

Note that Chrome doesn't currently use this role, so the third test verifies backwards compatibility. role="blockquote" is not yet supported in Chrome, so this wasn't tested.

### Known issues with pull request:
None.

### Change log entry:

Section: New features

`- Content marked as a block quote using ARIA (role blockquote) is now supported in Mozilla Firefox 63. (#8577)`

### CODE REVIEW

**Review by michaelDCurran — DISMISSED** [review]

**Comment by jcsteh** [comment]
Oh, I'm sorry. I should have thought of that. 🤦

**Comment by jcsteh** [comment]
For what it's worth, the quick nav change looks fine to me.

**Comment by michaelDCurran** [comment]
Merging with @jcsteh's manual approval.

**Review by feerrenrut — COMMENTED** [review]
I'm a bit late, but it looks good to me!

**Pull request merged**
