### PR TITLE
Add missing capitals to messages and GUI dialogs

### PR DESCRIPTION
**Pull request by dkager**
This will cause a ton of fuzzy strings for translators. Initially posted as a comment in #5557. Opening a new PR now to separate the discussion about the use of ui.message from the discussion on capitalization and punctuation.

The commits in this PR try to make the use of capitalization and punctuation more consistent. But there are still some points for debate:
- Should this even be attempted? Can it be made into a simple policy (that code reviewers can follow)?
- Should we sift through the messages that are only spoken, e.g. through the speak\* functions? There should be no audible difference, but these messages could be shown in the speech viewer. I left them alone for now.
- It'll never be perfect. Some strings are used in multiple contexts so you can't capitalize them.

@josephsl and @derekriemer: any thoughts?

### CODE REVIEW

**Comment by derekriemer** [comment]
This now has merge conflicts. Be aware if you decide to work on it.

**Comment by josephsl** [comment]
GUI helper and other friends...

@DKager, be careful - try rebasing first before continuing. CC @feerrenrut

**Comment by dkager** [comment]
I did a rebase last week but things tangled up a bit. I also don't quite remember what was still left to do anyway. Will pick it up ASAP.

**Comment by dkager** [comment]
Closing this since it is rather old. Will open something new if more inconsistencies show up.

**Pull request closed without merging**
