### PR TITLE
Add a global command to move braille to the current focus

### PR DESCRIPTION
**Pull request by dkager**
Related issues: #5250, #5410

This patch aims to support the default action of the middle thumb key on the Alva BC6 braille displays (#5206). Also useful for other displays, though they don't have a dedicated button for this. It is based on [this branch](https://github.com/dkager/nvda/tree/t5410) in order to get the 'move to selection' functionality as well.

### CODE REVIEW

**Comment by dkager** [comment]
This is the final one I'd like some feedback on. AFAIK it's the last piece to fully support the Alva BC6 braille displays.

**Comment by jcsteh** [comment]
What's New Entry: in New Features:

```
- There is now a command to move the braille display to the current focus. Currently, only the ALVA BC640/680 series has a key assigned to this command, but it can be assigned manually for other displays in the Input Gestures dialog if desired. (#5250)
```

**Comment by derekriemer** [comment]
"Moving the braille display " might be confusing for many users. Can a 
more clear bit of language be found for this ?


On 7/4/2016 9:22 PM, James Teh wrote:
>
> What's New Entry: in New Features:
>
> |- There is now a command to move the braille display to the current 
> focus. Currently, only the ALVA BC640/680 series has a key assigned to 
> this command, but it can be assigned manually for other displays in 
> the Input Gestures dialog if desired. (#5250) |
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub 
> <https://github.com/nvaccess/nvda/pull/5491#issuecomment-230380308>, 
> or mute the thread 
> <https://github.com/notifications/unsubscribe/AFGivToioQJqp59AlO61MAlAtijezVP7ks5qSc4FgaJpZM4GiVQx>.
>

-- 
------------------------------------------------------------------------


    Derek Riemer

  * Department of computer science, third year undergraduate student.
  * Proud user of the NVDA screen reader.
  * Open source enthusiast.
  * Member of Bridge Cu
  * Avid skiier.

Websites:
Honors portfolio <http://derekriemer.com>
Awesome little hand built weather app! 
<http://django.derekriemer.com/weather/>

email me at derek.riemer@colorado.edu <mailto:derek.riemer@colorado.edu>
Phone: (303) 906-2194

**Comment by dkager** [comment]
> "Moving the braille display " might be confusing for many users. Can a more clear bit of language be found for this ?

Good point, I remember struggling with that too. Maybe "scrolling"? That is accurate for focus mode, for review mode it uses an existing command.

**Comment by jcsteh** [comment]
Scrolling isn't really accurate in some cases; e.g. when the review object was moved away from the focus. It's worth noting that we do use the "Move the braille display" terminology for other commands; e.g. next/previous line.

**Pull request merged**
