### PR TITLE
Add @codeofdusk attributions for Python 3.11 upgrade

### PR DESCRIPTION
**Pull request by codeofdusk**
### Link to issue number:
Fix-up of #15513 #15514 . 

### Description of how this pull request fixes the issue:
Add @codeofdusk attributions for Python 3.11 upgrade 

### Testing strategy:
N/A

### Known issues with pull request:
None known

### Code Review Checklist:

- [x] Documentation:
  - Change log entry
  - User Documentation
  - Developer / Technical Documentation
  - Context sensitive help for GUI changes
- [x] Testing:
  - Unit tests
  - System (end to end) tests
  - Manual testing
- [x] UX of all users considered:
  - Speech 
  - Braille
  - Low Vision
  - Different web browsers
  - Localization in other languages / culture than English
- [x] API is compatible with existing add-ons.
- [x] Security precautions taken.

### CODE REVIEW

**Comment by seanbudd** [comment]
Please do not accredit authors on their behalf. It is up to the author to opt into accreditation

**Comment by codeofdusk** [comment]
This PR includes contributions by me. How do I opt into accreditation?

**Comment by codeofdusk** [comment]
This PR includes contributions by me. How do I opt into accreditation?

**Comment by seanbudd** [comment]
Apologies, the PR description was misleading:

>Many community contributions in 2024.1 are missing attributions.

**Pull request merged**
