### PR TITLE
Support for the Baum SuperVario2, Baum Vario 340 and HumanWare Brailliant2 braille displays.

### LINKED ISSUE #6116: adding USB Hid support to BAUM braille displays Vario 340 and SuperVario2
on a SightCity exebision in Frankfurt Germany BAUM introduced a new 40 cells braille display Vario 340.  this new braille display is supporting only USB HID connection. additionally, Baum has also another braille display model SuperVario 2. this braille display is supporting USB cirial port connection, bluetooth and USB HID connection. currently existing driver for the BAUM braille displays is not supporting Vario 340. it is supporting SuperVario 2  Vi USB cirial port and via bluetooth, but it doesn't support this display via USB HID. so i'm asking to add support for the USB HID connection for Vario 340 and  for SuperVario 2. 
for SuperVario 2 and humanware brilliant models produced by BAUM  i found following USB HID  idis:
  6001 hex  
 SuperVario2 40  
 
  6002 hex  
 SuperVario2 24  
 
  6003 hex  
 SuperVario2 32  
 
  6004 hex  
 SuperVario2 64  
 
  6005 hex  
 SuperVario2 80  
 
  6006 hex  
 Brailliant2 40  
 
  6007 hex  
 Brailliant2 24  
 
  6008 hex  
 Brailliant2 32  
 
  6009 hex  
 Brailliant2 64  
 
  600A hex  
 Brailliant2 80  
 for Vario 340 i found following USB HID idies:
Vario340 ="0x6201" 

    
  6010 hex

### PR DESCRIPTION
**Pull request by jcsteh**
Fixes #6116.

### CODE REVIEW

**Comment by jcsteh** [comment]
@feerrenrut, mind taking a look? This basically just adds USB IDs to a braille display driver and updates documentation accordingly.

**Comment by feerrenrut** [comment]
@jcsteh Could you add a small comment to this PR to explain the process you took to the the Vendor / Product IDs? Also some information on how has been/ will be tested?

**Comment by jcsteh** [comment]
Do you mean a code comment or an issue/PR comment? There is a discussion 
on #6116 where ids were provided by someone from the manufacturer and I 
then provided a try build and had them confirm it worked.

**Review by feerrenrut — APPROVED** [review]

**Comment by feerrenrut** [comment]
Ah awesome. Serves me right for not reading the issue properly.

**Pull request merged**
