### PR TITLE
Add-on store: Handle bulk install

### LINKED ISSUE #15347: NVDA 2023.2rc1 - CRITICAL error logged when ctrl+tabbing while an add-on is downloading
This is sort of a stress test of the Add-on Store trying to download a lot of add-ons.

### Steps to reproduce:
* Start a brand new NVDA (no personal config)
* Open Add-on Store
* Install all the add-ons starting with letters "T" and "U"
* Control+tab forth and back to leave the "available add-ons" tab and turn to it
* In the "T" or "U" add-ons, there are add-ons reported as "Available" (strangely); install them again

### Actual behavior:
First, it is strange that add-ons that have been installed are available again when turning in the "available add-ons" tab

Second, I get a CRITICAL error in the log. NVDA does not freeze nor crash, but I guess a CRITICAL is quite worrying in any case.

### Expected behavior:

First the add-ons that have been installed should all appear as Downloading or pending install.

Second, no CRITICAL error should occur.

### NVDA logs, crash dumps and other attachments:
[nvda.log](https://github.com/nvaccess/nvda/files/12478202/nvda.log)

#### NVDA installed/portable/running from source:
Installed
#### NVDA version:
2023.2rc1
#### Windows version:
Windows 10 21H2 (AMD64) build 19044.3324

#### Name and version of other software in use when reproducing the issue:
N/A
#### Other information about your system:
N/A
#### Does the issue still occur after restarting your computer?
Not tested
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
N/A
#### If NVDA add-ons are disabled, is your problem still occurring?
N/A, but no add-on initially installed since the STR uses a brand new config.
#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
Not tested, unrelated.

### PR DESCRIPTION
**Pull request by seanbudd**
### Link to issue number:
None

### Summary of the issue:
To be able to stress test the add-on installation system, a method of bulk installing add-ons is useful.
There is also a general request from users to be able to perform bulk actions like installing, updating or removing add-ons.

### Description of user facing changes
Users are now able to bulk install add-ons.
This can be done by selecting multiple add-ons in the available add-ons tab, then activating the context menu on the selection and choosing the install action.

### Description of development approach
Create a separate context menu for bulk actions. This creates an API for future bulk actions.

### Testing strategy:
Manually test STR in #15347 

Test selecting multiple add-ons and performing bulk install

### Known issues with pull request:
None

### Change log entries:
New features
- The Add-on Store now supports installing add-ons in bulk by selecting multiple add-ons.

### Code Review Checklist:

- [x] Pull Request description:
  - description is up to date
  - change log entries
- [x] Testing:
  - Unit tests
  - System (end to end) tests
  - Manual testing
- [x] API is compatible with existing add-ons.
- [x] Documentation:
  - User Documentation
  - Developer / Technical Documentation
  - Context sensitive help for GUI changes
- [x] UX of all users considered:
  - Speech 
  - Braille
  - Low Vision
  - Different web browsers
  - Localization in other languages / culture than English
- [x] Security precautions taken.

### CODE REVIEW

**Comment by cary-rowen** [comment]
Hi @seanbudd 

Here is an important problem for Chinese users:

As we all know, in a list control that supports multiple selections, the user can hold down the Ctrl key and then press the arrow keys to find the item they want to be selected and press the space key. This is useful for selecting multiple, non-adjacent items.

However, there are some differences in the Chinese version of Windows: Ctrl+Space This set of shortcut keys is used to switch input languages ​​globally.

This means that when Chinese users need to select multiple non-adjacent items in the list, an alternative is needed.

The solution given by Microsoft is to still hold down the Ctrl key when looking for the list item of interest, and then use the arrow keys to find it.
During this process, if the user wants to select an item, they need to release the Ctrl key briefly, and then just press the space key alone to select the current item. If the user wants to continue to select other items, they need to continue to hold down the Ctrl key. and repeat the above steps.

The current problem is: the action button is activated when I press the space key alone.
I can only select adjacent items by pressing Shift+four arrow keys, however, I cannot select non-adjacent items.

BTW, the interaction of pressing the space key to activate an action button when a list item is focused is a bit confusing and I almost never see it.

Cheers
Cary

**Comment by CyrilleB79** [comment]
> Hi @seanbudd
> 
> Here is an important question for Chinese users:
> 
> As we all know, in a list control that supports multiple selections, users can hold down the Ctrl key and then press the arrow keys to locate the item they wish to select. After finding the item, they can press the space key. This process is valuable for selecting multiple non-adjacent items.
> 
> However, there are certain differences in the Chinese version of Windows: the Ctrl+Space shortcut is utilized to globally switch input languages.
> 
> Consequently, Chinese users encounter a need for an alternative method when attempting to select multiple non-adjacent items in the list.
> 
> The solution provided by Microsoft is to maintain the Ctrl key pressed while searching for the desired item within the list. After locating the item, if the user wishes to select it, they need to momentarily release the Ctrl key and then press the space key to select the current item. If the user intends to continue selecting other items, they must keep the Ctrl key held down and repeat the aforementioned steps.
> 
> The existing issue is that the action button activates when I press the space key by itself. While I can select adjacent items by pressing Shift along with the arrow keys, I am unable to select non-adjacent items.
> 
> By the way, the interaction of pressing the space key to activate an action button when a list item is focused is somewhat perplexing, and I rarely encounter it.
> 
> Cheers Cary

Note that pressing space on an unselected item in a list (Windows Explorer) also selects it, even on non-Chinese Windows (tested on French). Thus @cary-rowen's suggestion to remove space shortcut key in the add-on list fully makes sense. Enter or Appplication key (or shift+F10) will still allow to open the context menu of an add-on.



@cary-rowen out of curiosity, how do you unselect an item when performing a multi-selection in list on a Chinese system? E.g. when you want to select all items (control+A) and unselect only one in the middle of them?

**Comment by cary-rowen** [comment]
Hi @CyrilleB79 

Thanks for letting me know that this issue is also affecting French users.

> @cary-rowen  out of curiosity, how do you unselect an item when performing a multi-selection in list on a Chinese system? E.g. when you want to select all items (control+A) and unselect only one in the middle of them?

In this case my steps are as follows:
1. Press Ctrl+A;
2. Hold down the CTRL key and press the arrow keys to navigate to an item I don't want selected.
3. Press Ctrl+Alt+Space NVDA will report "Not selected".
4. However, in Windows Explorer, an easier way might be to use invert selection LOL but this doesn't seem to have a shortcut key.
BTW, starting from Windows 10, the default shortcut key for Microsoft Pinyin input method interferes with the shortcut key I mentioned in step (3), because the shortcut key is also used to switch Chinese or English input.

Cheers
Cary

**Comment by CyrilleB79** [comment]
> Hi @CyrilleB79
> 
> Thanks for letting me know that this issue is also affecting French users.

No, this issue does not affect French users. I just wanted to say that the way Chinese people perform selection in list is not a specificity of Chinese systems and is doable on other systems.

>

**Comment by seanbudd** [comment]
>1. When no add-on is selected in the list (control+space), calling context menu does nothing (as well as when the list is empty). Since you have added "No actions available for the selected add-ons" message when many add-ons are selected, it would be coherent to have a ui.message too in this case.

It appears that windows doesn't fire a context menu event if nothing is selected so this can't be done

>6. From the description, I can see that you will allow other actions on multipe add-ons. Will you do this in this PR or not?

Adding other actions is out of scope of this PR. The changes here are fairly complex. I think it should be easy to implement a bulk migrate/update once this has been merged. Other bulk actions would be considered on a case-by-case basis.

>However, there are certain differences in the Chinese version of Windows: the Ctrl+Space shortcut is utilized to globally switch input languages.

This is a Windows issue that we really can't avoid. I would encourage reporting this to Windows so that they can implement an alternative control for multi-select for Chinese Windows.

**Comment by seanbudd** [comment]
>Thus @cary-rowen's suggestion to remove space shortcut key in the add-on list fully makes sense. 

Note that this is triggered by `EVT_LIST_ITEM_ACTIVATED`. We don't have specific handling for the `space` key coming from NVDA

**Comment by seanbudd** [comment]
We could potentially switch to a [wxCheckListBox](https://docs.wxwidgets.org/3.0/classwx_check_list_box.html) instead of a typical list view to make selecting multiple add-ons easier

**Comment by cary-rowen** [comment]
Hi @seanbudd 

> This is a Windows issue that we really can't avoid. I would encourage reporting this to Windows so that they can implement an alternative control for multi-select for Chinese Windows.


Chinese users who use Windows are so accustomed to this method of selecting list items that it feels as natural as quenching their thirst with water. 

I believe it's nearly impossible, or would take an excessively long time, to wait for Microsoft to address this issue. 

Whatever, I suspect that Chinese users might not be the only ones facing this problem. 

If we can't find a solution to this issue, the multi-select feature in the add-on store will lose its significance for Chinese users. So, is there anything NVDA can do to address this?


Cheers

Cary

**Comment by seanbudd** [comment]
@cary-rowen - I've figured out a solution to this now which allows using space to select items rather than trigger the context menu

**Review by michaelDCurran — APPROVED** [review]

**Review by Qchristensen — APPROVED** [review]
Looks good.

**Pull request merged**
