### PR TITLE
Use routines introduced or changed past Windows XP and Vista

### PR DESCRIPTION
**Pull request by josephsl**
### Link to issue number:
None

### Summary of the issue:
Uses new and changed functions introduced after Windows XP and Vista.

### Description of how this pull request fixes the issue:
Old assumptions from Windows XP days are gone, including:

* App modules: uses new way of querying executable image name.
* Core: calls DPI Aware function directly.
* NVDA helper will process all messages without regard to version of Windows it is running on.

### Testing performed:
Tested on Windows 10: compiling and running.

### Known issues with pull request:
None

### Change log entry:
Not to be documented as it is internal to NVDA.

## Additional notes

* As it is too late for 2017.4, it would be best to let this PR come into master later (no problem with incubating for a while).

### CODE REVIEW

**Comment by Brian1Gaff** [comment]
What is the point of this, is it just to speed things up by not having to 
check things in a look up table where operating system calls differ either 
in address or function between versions of windows?
 Brian

bglists@blueyonder.co.uk
Sent via blueyonder.
Please address personal email to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.
-----

**Review by feerrenrut — APPROVED** [review]

**Comment by codeofdusk** [comment]
Why are we too late for 2017.4?

**Comment by josephsl** [comment]
Hi, because translatable string freeze is about two weeks away, which is what’s usually considered feature freeze. Also, because we need to keep an eye on possibly broken functionality, thus I requested that this be incubated a bit longer. Thanks.

**Comment by derekriemer** [comment]
What about now removing old assumptions about UIA like that XP UIA shouldn't be used?

**Comment by josephsl** [comment]
Hi, for majority of cases, I believe that’s already taken care of through existing code at the moment. Thanks.

**Pull request merged**
