### PR TITLE
Proposed Add-on Store user guide section revisions

### PR DESCRIPTION
**Pull request by XLTechie**
Replaced by PR #14966

### CODE REVIEW

**Comment by XLTechie** [comment]
@seanbudd and/or @Qchristensen While I did not try to change it here, why are we still using the old "`addonsManager`" internal link to reach the add-on store section of the user guide? I vaguely remember this being explained somewhere, but not sure where.

In any case, it seems strange since the store is an entirely new concept.

**Comment by CyrilleB79** [comment]
> @seanbudd and/or @Qchristensen While I did not try to change it here, why are we still using the old "`addonsManager`" internal link to reach the add-on store section of the user guide? I vaguely remember this being explained somewhere, but not sure where.
> 
> In any case, it seems strange since the store is an entirely new concept.

In the wild, there may be links on the user guide targeting this paragraph. Keeping the old add-on manager anchor allows to avoid these links to be broken and to point to the paragraph which describes what has become the add-on manager.

**Comment by XLTechie** [comment]
> In the wild, there may be links on the user guide targeting this paragraph. Keeping the old add-on manager anchor allows to avoid these links to be broken

So would creating an HTML anchor immediately before the Add-on Store section, that manually redirects links there, while still enabling us to name the chapter appropriately. E.g.:

```
'''
<a style="visibility: hidden" name="AddonsManager">&nbsp;</a>
'''
```

That is valid T2T code, according to the spec.

**Comment by CyrilleB79** [comment]
> > In the wild, there may be links on the user guide targeting this paragraph. Keeping the old add-on manager anchor allows to avoid these links to be broken
> 
> So would creating an HTML anchor immediately before the Add-on Store section, that manually redirects links there, while still enabling us to name the chapter appropriately. E.g.:

Yes, this fully makes sense to me.

**Comment by seanbudd** [comment]
Strangely, GitHub will not let me re-open and re-target this PR

**Comment by XLTechie** [comment]
Opened as a new PR with a clean branch. Had to cherry-pick it back into master, as it wouldn't let me rebase in.

**Pull request closed without merging**
