### PR TITLE
Visual studio fixes and enhancements for newer versions

### PR DESCRIPTION
**Pull request by mohammad-suliman**
here is a list of issues this add-on addresses:
- #6021 I open this issue and made a PR #6025 
  the app mod includes the same code in that PR
- #5880  this is a duplicate of the previous issue
- #5773 fixed. VS exposes menu items with sub menus with the collapsed / expanded  state. don't know if this is a wrong implementation or an intended one with UIA
- #5619 fixed I believe. tested with VS 2013 however. will comment on that issue to make sure I understand correctly what the exact problem is. will ask the user for testing when we need to.
- #5618 I have a fix for this also. will wait for the final decision regarding this though.
- #5052 haven't seen this when testing, needs more info and investigation.
- #3030 fixed. tested with 2013 and 2015. I am mostly sure it will work for 2012, however we need to test to verify.
- #3025 same as previous issue
- #2471 same as previous
- #2233  same as previous.
- #943 basic support, needs an external fix by MS to work properly

a note about older versions of VS, the UI of Vs 2010 to 2015 is so similar, so fixes witch haven't been tested yet are likely to work as expected. other screen readers still use same scripts of 2010 for latest version of VS.

### CODE REVIEW

**Comment by mohammad-suliman** [comment]
forgot to mention that I renamed previous app module for VS to devenv-old.py and the new code is in devenv.py
also, express editions has other executable name, so, when major issues is handled, will add it.

**Comment by mohammad-suliman** [comment]
Any status update on this? have been asked several times to provide a compiled version, so I am thinking to release this as an add-on currently, until the devs have some time to review this. Is there any  chance  This can be included in 16.3? I am aware that there are issues with higher priority, so not expecting / asking to give this pr a higher priority.
thanks and keep the great work.

**Comment by derekriemer** [comment]
ping

**Comment by leonardder** [comment]
Could you please address the following for this pr?

1. Remove everything that is Visual studio <=2008 specific. VS2008 is now 10 years old, and I don't think that we should aim versions older than 2010, to draw a line.
2. Update the initial description of your pr according to the pull request template, i.e. provide a list of issues addressed by this pr and how you have fixed them. It would really help if we'd have an overview from the pr itself, rather than having to open every separate issue which you have addressed.
3. Remove all first person comments "i.e. I did this or that) from your code and provide relevant information out of these comments in the pr description instead.

**Comment by feerrenrut** [comment]
This change primarily targets older versions of visual studio, we would prefer this to be implemented in an addon. Newer versions of Visual Studio have improved their accessibility and Microsoft continues to work on this. Many of these changes are now not necessary, so I will close this pull request.

**Comment by Adriani90** [comment]
In mS Word for example, performance is being addressed especially for older MS Word versions (see recent merged pull request by @michaelDCurran). Why not fixing things in older version of software if voluntary developers are providing the solutions? I vote for reopening and reviewing this PR because there are lots of people out there working with older versions of VS.

**Comment by Adriani90** [comment]
If the software was totally deprecated, then I would agree with just closing this PR.

**Comment by leonardder** [comment]
There is an important difference between Visual Studio and Word. Visual Studio 2017 has a free community version, whereas Word is always a paid product. This means that, at least for community use, people should be able to update to Visual Studio 2017 without cost.

**Comment by Adriani90** [comment]
Well, not if people are using it in a professional environment. Update cycles in companies can last years and so people must work in old versions though.

**Pull request closed without merging**
