### PR TITLE
Merge security fixes from 2021.3.4

### PR DESCRIPTION
**Pull request by feerrenrut**
### Link to issue number:
- [GitHub Advisory GHSA-wg65-7r23-h6p9](https://github.com/nvaccess/nvda/security/advisories/GHSA-wg65-7r23-h6p9)
- [GitHub Advisory GHSA-mvc8-5rv9-w3hx](https://github.com/nvaccess/nvda/security/advisories/GHSA-mvc8-5rv9-w3hx)
- [GitHub Advisory GHSA-354r-wr4v-cx28](https://github.com/nvaccess/nvda/security/advisories/GHSA-354r-wr4v-cx28)

### Summary of the issue:
Several security fixes have been introduced to address (soon to published) security advisories.

### Description of how this pull request fixes the issue:
Note about the state of the rc branch:
- Initially changes for 2021.3.1 were delivered to beta, subsequently it was decided to avoid complications with translations, to make changes directly on RC.
- The changes were cherry picked from beta.
- There were then several more changes made squashed / merged to RC
- These changes need to be cherry picked back into the beta branch.
- This was done in https://github.com/nvaccess/nvda/pull/13185

Similarly, the security fixes already merged into the rc branch must be merged separately to beta then to master.
To ensure the same commits are in the history of the 2021.3.4 release, 2022.1 release and master, the changes were merged (not squashed) into rc, and now with this PR also into beta, then beta can be merged back to master.
Merge in:
- https://github.com/nvaccess/nvda/pull/13487
- https://github.com/nvaccess/nvda/pull/13488
- https://github.com/nvaccess/nvda/pull/13489
- https://github.com/nvaccess/nvda/pull/13490

### Testing strategy:
See individual PRs

### Known issues with pull request:
None

### Change log entries:
Included

### Code Review Checklist:
- [x] Pull Request description:
  - description is up to date
  - change log entries
- [x] Testing:
  - Unit tests
  - System (end to end) tests
  - Manual testing
- [x] API is compatible with existing add-ons.
- [x] Documentation:
  - User Documentation
  - Developer / Technical Documentation
  - Context sensitive help for GUI changes
- [x] UX of all users considered:
  - Speech 
  - Braille
  - Low Vision
  - Different web browsers
  - Localization in other languages / culture than English

### CODE REVIEW

**Review by seanbudd — DISMISSED** [review]

**Comment by seanbudd** [comment]
I rebased this to update the cherry-picks to the latest beta. However, the merge commits were removed. I don't think this should be an issue, as rc and beta has diverged already. The commit history will still be consistent between beta and master, when merging from beta to master.

**Review by seanbudd — DISMISSED** [review]

**Comment by seanbudd** [comment]
I've had to rebase again due to a lint failure from a rebase conflict resolution mistake in b51a3f3

**Comment by feerrenrut** [comment]
If rebased the commits will no longer match.

**Comment by feerrenrut** [comment]
Each of the commits: 
- fa876b716
- 196a7918b
- 8faadd6f9

Are on this branch and on `release-2021.3.4`, but they are connected via merge commits.
It's much easier to follow this with `git log --graph`. You can also follow it by looking at the parent SHAs for the merges.
Merge commits have two (or more) parents. 

Merge commits:
- [`fed87d9c5c5e`](https://github.com/nvaccess/nvda/commit/fed87d9c5c5e0f35079196e433e9597eec2a46e4) has 2 parents `117e54e` + `fa876b7`
- [`117e54ea8545`](https://github.com/nvaccess/nvda/commit/117e54ea8545a035b6e3251bd7b8fb1c3f760492) has 2 parents `b458a41` + `8faadd6`
- [`b458a4129023`](https://github.com/nvaccess/nvda/commit/b458a4129023e3e72632c3a5881328361f2b51cc) has 2 parents `d40a6d8` + `196a791`

**Review by seanbudd — APPROVED** [review]

**Pull request merged**
