### PR TITLE
Navigator object vaidation before recognition in contentRecog

### LINKED ISSUE #11380: Validating navigator object before content recog
### Is your feature request related to a problem? Please describe.
`contentRecog.ContentRecognizer` is an abstract class that can be used to define a content recognizer. A `recognizer` object derived from it can be passed to `contentRecog.recogUI.recognizeNavigatorObject` to perform content recognition on the currently focused navigator object using the `recognizer`. However, `contentRecog.recogUI.recognizeNavigatorObject` currently has no mechanism for validating the navigator object before passing it to the `recognizer` for content recognition. Most content recognition applications are specific to the content they recognize and so it would save user time to filter out navigator objects that are known to produce bad or no results.

### Describe the solution you'd like
Adding a `validateNavigatorObject` function to `contentRecog.ContentRecognizer` class that users can override in derived classes to add code that validates the navigator object and defines what to do when validation fails. This function could then be called from within `contentRecog.recogUI.recognizeNavigatorObject`, before recognition is started.

### Describe alternatives you've considered
Writing a custom implementation for `contentRecog.recogUI.recognizeNavigatorObject` that performs application specific validation.

### Additional context
 --

### PR DESCRIPTION
**Pull request by ShubhamJain7**
### Link to issue number:
fixes https://github.com/nvaccess/nvda/issues/11380

### Summary of the issue:
`contentRecog.recogUI.recognizeNavigatorObject` currently has no mechanism for validating the navigator object before passing it to the recognizer for content recognition. This allows navigator objects that are known to produce bad or no results to be processed for content recognition and waste user time.

### Description of how this pull request fixes the issue:
This pull request adds a `validateNavigatorObject` to `contentRecog.ContentRecognizer` that can then be overridden by users to define validation code for their application and also define what to do when validation fails. This function is then called in `contentRecog.recogUI.recognizeNavigatorObject` to ensure that the currently focused navigator object is valid before it is passed to the `recognizer` for content recognition.

### Testing performed:
I overrode the `validateNavigatorObject` function when creating a class that derives from `contentRecog.ContentRecognizer` to ensure that the width and height of the navigator object are greater than a specific threshold. I then tested the code on navigator objects with dimensions both greater and lower than the specified threshold and got expected results. Which is, content recognition was performed for navigator objects that passed the validation test and not on navigator objects that failed the test.

### Known issues with pull request:
None

### CODE REVIEW

**Comment by Adriani90** [comment]
@ShubhamJain7 could you please also add a note for change log? Something like:
* NVDA no longer presents incomplete or bad OCR results on certain navigator objects

**Comment by Adriani90** [comment]
Moreover, did you test this in pdf documents which contain pictures or scan images? Note that if you run an OCR on a pdf page after you switched to it, NVDA will recognize the whole page at once. But if you move on the page with arrow keys, NVDA will only recognize the navigator object.
Ideally this functionality should not be broken by this pull request.

**Comment by Adriani90** [comment]
Sometimes even bad results give enough detail for an user to understand what the object is about.
cc: @lukaszgo1 or @CyrilleB79 your ghoughts on this are also appreciated.

**Comment by lukaszgo1** [comment]
@Adriani90 I'm afraid you misunderstood what this PR implements. There is no change in functionality here - it just makes it easier to implement additional validation for developers but there is none implemented by default.

**Comment by ShubhamJain7** [comment]
@Adriani90, @lukaszgo1 is correct. This PR doesn't change existing functionality, it only adds a mechanism for users to validate a navigator object before it is used for content recognition. By default, it is treated as valid so any previous use of this code segment will not be affected.

**Comment by leonardder** [comment]
This code assumes that we're recognising the navigator object. I don't think this should be true always. have you considered to make this more generic, e.g. validateObject?

**Comment by ShubhamJain7** [comment]
@leonardder 
Thanks for pointing that out! I'll update the method name.

**Comment by feerrenrut** [comment]
It probably is better that the validate method name is generic, but at the moment the object is the result of `api.getNavigatorObject()`.

**Review by feerrenrut — APPROVED** [review]
Thanks @ShubhamJain7

**Pull request merged**
