### PR TITLE
GUI: Make Input Gestures Dialog resizeable (#6332)

### PR DESCRIPTION
**Pull request by JulienCochuyt**
### Link to issue number:

Progress on #6332

### Summary of the issue:

As stated by @feerrenrut in https://github.com/nvaccess/nvda/issues/6332#issue-175024733

> Some of the dialogs would benefit from being resizable. Dialogs with list controls (single or multi-column) or tree views often have entries that are much bigger than the space allocated to them. This can make them more difficult to read. While ideally all dialogs would have a layout that finds the balance between ease to read and not looking oversized, a fairly simple fallback option is to make the dialogs resizable. A user can just resize the dialog in order to fit the content they are interested in on the screen.

### Description of how this pull request fixes the issue:

Make the Input Gestures dialog resizeable.

### Testing performed:

Shrunk and enlarged the dialog with different proportions to ensure its layout stays coherent.

### Change log entry:

I do not think this change deserves to be announced.

### CODE REVIEW

**Comment by feerrenrut** [comment]
The dialog probably needs a minimum size, have you tested shrinking it as small as it will go? The window should not be able to shrink to a point where controls are hidden. While here, you could also update any sizes we hard-code to use `self.scaleSize` which should adjust for screen scaling used on high dpi screens. To test this, you have to change "make everything bigger" in the windows display settings, log out, and log in again. Get it looking right at the "recommended" setting for your computer, and ensure that the size is maintained at other scaling settings (ie doesn't become tiny or very large)

**Comment by JulienCochuyt** [comment]
> The dialog probably needs a minimum size, have you tested shrinking it as small as it will go? The window should not be able to shrink to a point where controls are hidden.

Done.
cf30e1e forbids any resizable setting dialog to shrink below its minimum size.
Depending on how the layout of each dialog is coded, this often leads to the dialog refusing to shrink below its initial size. I guess this is a reasonable side effect, as we primarily make dialogs resizable to allow them to grow.
8ad6f04 allows the Input Gesture dialog to shrink below its initial size despite the above change.
This can be taken as an example on how to allow other dialogs to do the same.

> While here, you could also update any sizes we hard-code to use `self.scaleSize` which should adjust for screen scaling used on high dpi screens. To test this, you have to change "make everything bigger" in the windows display settings, log out, and log in again. Get it looking right at the "recommended" setting for your computer, and ensure that the size is maintained at other scaling settings (ie doesn't become tiny or very large)

This PR currently does not change the scale size of the impacted dialogs.
What you suggest doing is of course the right way to go, but is pretty tedious as every single change on every hardcoded value is to be checked carefully.
If you don't mind, I'd prefer having this small PR merged before I or anyone else takes on the burden of migrating all harcoded the sizes to scale sizes.

**Review by feerrenrut — CHANGES_REQUESTED** [review]
Generally looks good. I think the minimum size of the input gestures dialog should be larger. At least on my machine the minimum size is too small to be useable. Does this match the behaviour on your machine?

Initial size:
image

Minimum size:
image

**Review by feerrenrut — APPROVED** [review]
Looks good, thanks for making this change!

I think it is low risk, but it would be good to confirm that any settings dialogs that are already resizeable are not made worse by this new minimum size.

**Comment by JulienCochuyt** [comment]
> I think it is low risk, but it would be good to confirm that any settings dialogs that are already resizeable are not made worse by this new minimum size.

No risk at all: This last change applies only to the Input Gestures dialog.
Among the other dialogs made resizable by the remaining PRs:
 - Speech Symbols is almost not shrinkable
 - Dictionary and Addons dialogs can be shrunk a little bit vertically, but not horizontally

The sole side effect of the merged change, as mentioned in https://github.com/nvaccess/nvda/pull/10189#issuecomment-530447123 is:
> cf30e1e forbids any resizable setting dialog to shrink below its minimum size.
Depending on how the layout of each dialog is coded, this often leads to the dialog refusing to shrink below its initial size. I guess this is a reasonable side effect, as we primarily make dialogs resizable to allow them to grow.

Since I wrote that comment, I could check that no other dialog in NVDA is badly impacted by this.

**Pull request merged**
