### PR TITLE
adding bitwarden module

### PR DESCRIPTION
**Pull request by zuhairmahd**
### Change log entries:
New features
Changes
Bug fixes
For Developers

### Code Review Checklist:

- [ ] Pull Request description:
  - description is up to date
  - change log entries
- [ ] Testing:
  - Unit tests
  - System (end to end) tests
  - Manual testing
- [ ] API is compatible with existing add-ons.
- [ ] Documentation:
  - User Documentation
  - Developer / Technical Documentation
  - Context sensitive help for GUI changes
- [ ] UX of all users considered:
  - Speech 
  - Braille
  - Low Vision
  - Different web browsers
  - Localization in other languages / culture than English

### CODE REVIEW

**Comment by zuhairmahd** [comment]
Not yet ready for primetime.  Will open a new PR once ready.

**Comment by josephsl** [comment]
Hi, in the future, can you please fill out the PR template completely, as well as create an issue to go with the pull request that describes what Bitwarden is? Thanks.

**Comment by zuhairmahd** [comment]
@josephsl absolutely.  This PR was opened way prematurely.  Bitwarden is another password manager, just like 1password.

**Comment by josephsl** [comment]
Hi, I see. In the meantime let’s discuss Bitwarden in a new issue (do document accessibility issues if any), and do let us know if the app developer is willing to resolve accessibility issues. Thanks for the prompt response.

**Comment by mazen428** [comment]
Hello.
I'm wondering why did you base this on the one password module? Even though Bitwarden is completely different in that it's an electron program and doesn't use UIA?
Thanks.

**Comment by zuhairmahd** [comment]
@mazen428  it was an arbitrary choice just to get the module template created. I was going to take out its contents and replace it with my own. You've given mme an idea though -- which is to start with an app that is more similar to Bitwarden. Like I said, the PR was opened way prematurely. :-).

**Pull request closed without merging**
