### PR TITLE
Fix OneCore rateboost always initialized at 50% rate and SSML converter issues

### LINKED ISSUE #9558: NVDA does not save One core voices settings with Rate boost on
With new rate boost option introduced in the newest Alpha releases NVDA is not able to save the configuration for One core voices while the rateboost is on. When changes for rate and pitch are made for One core voices, it is possible to save the settings, but after restarting NVDA or after switching to another synth and going back to One core voices, the settings go to their default values. However if rate boost for One core voices is turned off, than all the settings are saved and reloaded correctly.
It is happening on Windows 10 1809 with the last Alpha release alpha-17205,93ccd518

### LINKED ISSUE #9576: nvda threshold does not advertise and makes an error sound when pruning capital letter
### Steps to reproduce:
Open Notepad.
Please enter a capital letter.
Now navigate left with the arrow and try to read the character in uppercase.
### Actual behavior:
When typing an uppercase letter or trying to read an uppercase letter, nvda makes the error tone and does not speak the uppercase character.
### Expected behavior:
nvda should read the uppercase characters normally, either when navigating character by character, or when typing a capital character.
### System configuration
using the windows voice one core in Portuguese Brazil, voice Maria.
#### NVDA installed/portable/running from source:
install
#### NVDA version:
threshold 17249
#### Windows version:
10 17763.475
#### Does the issue still occur after restarting your PC?
yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
yes
alpha versions of nvda do not have this problem
[capital.txt](https://github.com/nvaccess/nvda/files/3187265/capital.txt)

### PR DESCRIPTION
**Pull request by LeonarddeR**
### Link to issue number:
fixes #9558, regression from #8934 
Fixes #9576 
 
### Summary of the issue:
In #8934, a new method was introduced to set pitch, volume and rate for OneCore voices. When setting these parameters, NVDA queues an entry to self._queuedSpeech, which is then processed in self._processQueue. This means that there is a delay between changing and applying the parameter.

Now the following happens when initializing the driver with rate boost on:

1. Volume, pitch, rate and rate boost are loaded from config
2. Volume, pitch and rate changes are queued. Rate boost fetches the current rate, enables rate boost and than sets the rate again, which again queues a change of the rate to the speech queue. However, when fetching the rate during that action, the rate change queued earlier has not yet been processed.
3. After that, when the actual queue is processed, the queue contains two rate changes, namely the initial rate change according to the config, and the second rate change that was initiated by enabling rate boost, effectively reseeting it to the default rate.

### Description of how this pull request fixes the issue:
When setting pitch, volume and rate, parameters are still queued to the speech queue. However, the set values are also cached in _pitch, _volume and _rate attributes, respectively. Rate boost now fetches the rate from self._rate, making sure that the proper rate is used when calculating the new rate after enabling rate boost.

This pr also fixes errors caused when processing speech.Pitch/Volume/RateCommands.

### Possible alternative
Forcefully process the speech queue before fetching the rate when setting rate boost. I decided not to do this, as this could have unexpected side effects whe enabling rate boost while speech is in the queue.

### Testing performed:
1. Tested the steps from #9558, I was no longer able to reproduce the issue.
2. Spelled a long line of text with mixed case. Ensured that pitch changes occur as they should.
3. Turned on speak typed characters and tested that typing upper case and lower case letters changes pitch as it should.
4. Adjusted rate in the Settings dialog. Ensured that the rate is changed appropriately as the new percentage is spoken. Tested with up arrow/down arrow/Page up/page down/home/end
5. Did the same with the settings ring.
6. Tested Pitch/Volume/RateCommands

### Known issues with pull request:
Volume and pitch are cached without actually using the cached attributes later on. However, it made more sense to cache them all than creating a unbalanced approach.

### Change log entry:
None

### CODE REVIEW

**Comment by jcsteh** [comment]
My recollection is a bit vague, but I believe historically, we've queued
parameters to happen after any speech in progress (e.g. in the eSpeak
driver) because of problems with capital pitch change and parameter changes
in the settings dialog/synth settings ring. For example, with capital pitch
change, we reset the pitch to the old pitch after we send the capitalised
letter. Because the synth processes speech async, the pitch might get reset
to the old pitch before it's even started speaking the capitalised letter,
which effectively means the pitch change never happened. I don't recall
what was causing issues in the Voice Settings dialog, but I do know that
adjusting parameter sliders sometimes wouldn't reflect the change when the
new percentage was spoken. I don't recall whether I observed these issues
with OneCore or whether I just followed the existing pattern.

I would suggest you test the following things:

1. Spell a long line of text with mixed case. Ensure that pitch changes
occur as they should.
2. Turn on speak typed characters and test that typing upper case and lower
case letters changes pitch as it should.
3. Adjust rate in the Settings dialog. Ensure that the rate is changed
appropriately as the new percentage is spoken. (Page up/page down/home/end
are probably the best ways to test this; the changes can be hard to verify
with the arrow keys.)
4. Do the same with the settings ring.

Note that once speech refactor lands, capital pitch changes will no longer
be an issue, since they're handled with speech commands (as they should be)
instead of faffing with the properties on the synth.

**Comment by michaelDCurran** [comment]
Testing with both Microsoft George and Microsoft Zira, and having NVDA spell the following line: 
"Hello, This Is A Test"
(That is with the first letter of each word capitalized)
Only the 'H' of 'Hello' has its pitched raised. The rest do not. 
Testing of synth settings ring and Speech settings panels seems to work okay.
The spell line test will work fine in conjunction with speech refactor. So, we  *could* merge this into threshold instead of master? or wait until threshold is merged to master.

**Comment by michaelDCurran** [comment]
Or alternative, we could try the other possibilities noted on the description of this pr which might be faster and more specifically addresses the problem.

**Comment by leonardder** [comment]
You're right. I tested this by spellin gwith arrow keys, I should have tested this with spell current line.

I think from the two options we have, I prefer the second.

**Comment by leonardder** [comment]
@michaeldcurran: I've fixed all this with a different approach. I also tested the issue related to SSML found in Threshold, where it is much more prevalent.

**Review by michaelDCurran — APPROVED** [review]

**Pull request merged**
