### PR TITLE
Modify nvwave.playWaveFile to check NVDA's config path for sounds

### PR DESCRIPTION
**Pull request by ctoth**
This allows users to override their NVDA sounds without worrying about losing these changes upon NVDA update.
To use, simply create a waves folder inside your NVDA config path, usually %appdata%\NVDA, and place your replacement earcons in this folder.

### Known issues with pull request:
- This patch checks for files in the alternate location every time the function is called to support placing the files in at runtime, but this may be considered too inefficient
### Change log entry:
Support placing NVDA sounds in a waves folder under the NVDA Configuration directory

### CODE REVIEW

**Comment by leonardder** [comment]
I wonder, have you also considered adding the possibility to override sounds at the add-on level? May be do this the pythonic way and use a path list variable for sounds. Than, let nvwave.playWaveFile lookup the sound in the folders defined in path variable list order.

**Comment by ctoth** [comment]
@leonardder I believe this is out of scope for this PR, which is extremely simple. If you want to support adding multiple sound paths, please open an issue for this particular feature. This is a response to a simple problem and I really, strongly, extremely, supremely do not want to get it caught up in bikeshedding as that is literally the problem that caused this to even be necessary in the first place.

**Comment by tuukkao** [comment]
> May be do this the pythonic way and use a path list variable for sounds. Than, let nvwave.playWaveFile lookup the sound in the folders defined in path variable list order.

This sounds reasonable to me: build a list of files in <nvda_install_dir>\waves and <nvda_config>\waves and look up the requested file from those lists. Would be more performant than checking file existence everytime a sound is played. Naturally it would break if you were to add new waves while NVDA is running but I don't think that is much of an issue.

**Comment by leonardder** [comment]
[**@ctoth**](https://github.com/ctoth) commented on [13 Sep 2017, 21:44 CEST](https://github.com/nvaccess/nvda/pull/7603#issuecomment-329275925 "2017-09-13T19:44:42Z - Replied by Github Reply Comments"):
> @leonardder I believe this is out of scope for this PR, which is extremely simple.

The simplicity of this pr is actually what bothers me here. I agree that in some situations, it might be desirable to override sounds, but the current pr only allows for this to be done in a way that is quite user unfriendly for many people. 

Thoughts from @feerrenrut and @michaeldcurran are appreciated.

**Comment by dkager** [comment]
In addition to https://github.com/nvaccess/nvda/pull/7603#issuecomment-329261023 a simple, hidden config variable `useCustomSounds` would also suffice. I expect that more than half of the users will not use custom sounds, so for the majority of users this implementation is inefficient.

**Comment by derekriemer** [comment]
I don't think this implementation harms anyone. We already allow custom plugins to work this way, although we might want to deprecate the old globalPlugins/ folder and such.
While I'd prefer sound schemes long term, having a quick and dirty solution for power users in the short-term is unlikely to slow the system down for anyone else.

**Review by michaelDCurran — CHANGES_REQUESTED** [review]
I am happy to take this with the following change: check if the original path given is absolute or not. Use os.path.isabs for this. Only if it is not absolute, then try the redirection.

**Comment by michaelDCurran** [comment]
This pr will be taken as a temprary solution. In the long-term we would like to support sound packs via add-ons or some such. However, NV Access does not currently have the time to invest in this, thus this pr can be used for now. I don't believe  a path existance check would affect performance in any noticeable way.

**Comment by feerrenrut** [comment]
Rather than store the files in the base NVDA directory, I think a subfolder would be preferable. Something like `%appdata%\NVDA\userSounds`. This will make it easier to migrate these sounds to a newer sound pack feature in the future without losing data. That way we know the location of all the custom sound files that the user expects to be able to use with NVDA.

**Comment by leonardder** [comment]
[**@feerrenrut**](https://github.com/feerrenrut) commented on [29 jan. 2018 04:46 CET](https://github.com/nvaccess/nvda/pull/7603#issuecomment-361132835 "2018-01-29T03:46:03Z - Replied by Github Reply Comments"):
> Rather than store the files in the base NVDA directory, I think a subfolder would be preferable. Something like `%appdata%\NVDA\userSounds`. This will make it easier to migrate these sounds to a newer sound pack feature in the future without losing data. That way we know the location of all the custom sound files that the user expects to be able to use with NVDA.

May I suggest the "waves" folder, to stick in line with where the files are saved in NVDA's application folder?


[**@michaelDCurran**](https://github.com/michaelDCurran) commented on [28 jan. 2018 06:22 CET](https://github.com/nvaccess/nvda/pull/7603#issuecomment-361039273 "2018-01-28T05:22:23Z - Replied by Github Reply Comments"):
> I don't believe  a path existance check would affect performance in any noticeable way.

I agree, instead of checking a paths existence we might as well just access it. :)
Still, I belief @dkager brings up a valid concern, saying that the majority of users won't use these custom sounds. 

Recently, I've been in a corporate environment where NVDA's user configuration was saved on a network share. First and foremost, I'd like to state that saving NVDA"s config on a network share is really not what I should do or advice, but one of this organisation's policies enforced this.

In this particular organisation's case, this pr will try to play a sound from that network share. If the latency of that network share is significant, this will most likely impact performance.

Therefore, I concur with @dkager's request to put this behavior behind a (hidden) config parameter.

**Comment by feerrenrut** [comment]
Sorry my last comment confused things here a bit, I misread the description. The current proposed approach of storing the users custom sounds in `%AppData%\waves` and the standard sounds continue to be stored in `<NVDA install directory\waves` is fine by me.

Checking for absolute paths is a good idea, again there may be addons that refer to a sound file in a absolute way.

michaelDCurran and myself discussed the idea of converting all references to the current relative paths, to just the file name. So code that referred to `"waves\\start.wav"` would now refer to just `"start.wav"'. There are some concerns about breaking backwards compatibility here, for instance there may be addons that rely on this.

**Comment by dkager** [comment]
@leonardder This is collecting dust. What to do with it? I maintain that the original patch is not what we want.

**Comment by leonardder** [comment]
[**@dkager**](https://github.com/dkager) commented on [15 Jun 2018, 17:37 CEST](https://github.com/nvaccess/nvda/pull/7603#issuecomment-397660078 "2018-06-15T15:37:23Z - Replied by Github Reply Comments"):
> it? I maintain that the original patch is not what we want.

I agree and am closing this pr for now.

@ctoth: If you'd like to pick up your work again, feel free to request a reopen. Anyone else is free to open a new pr as well, of course.

**Pull request closed without merging**
