### PR TITLE
add Appveyor status badges 

### PR DESCRIPTION
**Pull request by marcosptf**
this change dont need a new issue!

just see in github index page nvda, if the AppVeyor is passing by badges svg image

just add one AppVeyor line code that show the svg badges

### Testing performed:
None

None

was added a new badges to see AppVeyor CI
> * Changes
> * Bug fixes

> For examples see the changes file in your NVDA repo: `user_docs/en/changes.t2t` or on github: https://github.com/marcosptf/nvda/blob/appveyor-status-badges/readme.md

### CODE REVIEW

**Comment by leonardder** [comment]
Why do you think this should be there? You can always see the appveyor status on the branches page, and for me, this is enough.

**Comment by marcosptf** [comment]
@leonardder 

follow examples that anothers big projets use it to see the status of ci in one place:

https://github.com/php/php-src#the-php-interpreter
https://github.com/python/cpython#this-is-python-version-370-alpha-2
https://github.com/Microsoft/vscode#visual-studio-code---open-source
https://github.com/ruby/ruby#whats-ruby
https://github.com/IBM/watson-online-store#creating-a-retail-chatbot-using-watson-conversation-discovery-and-database-services

and many many others projects use this way to see ci status :D

**Comment by michaelDCurran** [comment]
It looks like these status badges are inaccessible to blind people as  they do not convey the status via any kind of textual label. I'm assuming the image simply changes based on the status? Therefore as this is not useful for the majority of our developers, it would not be appropriate to ad this... unless a solution can be found to address the inaccessibility.

**Comment by marcosptf** [comment]
i undertand @michaelDCurran you are right !

**Comment by leonardder** [comment]
@marcosptf: Do you think @michaeldcurran's point can be addressed? If not, it might be best to close this.

**Comment by marcosptf** [comment]
@leonardder 
okey ill close this PR

Thanks for all

**Pull request closed without merging**
