### PR TITLE
Allow disabling automatic focus of focusable elements in browse mode

### PR DESCRIPTION
**Pull request by LeonarddeR**
### Link to issue number:
Follow up of #9114 and #9360. Initial work by @mltony 

### Summary of the issue:
From https://github.com/nvaccess/nvda/pull/9114#issue-241609465

> NVDA has systematic problems with browse mode in all browsers, such as:
> - Rubber band effect: NVDA sporadically undoes the last browse mode keystroke by jumping to the previous location
> - Edit boxes steal system focus when arrowing down through them on some websites
> - Browse mode keystrokes are slow to respond.

A pull request was provided by @mltony to fix this, but unfortunately had to be reverted. Another pull request (#9360) had also be closed.

### Description of how this pull request fixes the issue:
This pr takes the work by @mltony, stripping it down to the absolute basics. Changes since #9360 are.

1. Reworded the new option in browse mode settings. Honestly, I considered the wording "focus follows browse mode" a bit vague, given that the focus is usually updated explicitly. It is also not very clear from the initial wording when the focus is updated and when it is not. I reworded this to "Automatically set system focus to focusable elements" which in my opinion more closely resembles what's happening under the hood. As always, this change is open to debate and I"m happy to revert it.

2. #9360. contained an issue that caused state changes to be reported inconsistently. I'm pretty sure this is fixed now.

3. In comparison with #9114, this removes all the asynchronous logic. This is actually not exactly true, since the whole work still relies on async logic (i.e. calling setFocus and than handling focus changes in event_gainFocus). However, setting the focus to objects is no longer queued asynchronously. I also removed the uniqueID property from the several NVDAObjects, since it's no longer used.

4. I added shift+applications and shift+f10 as additional gestures that should cause the focus to be set to the last focusable object.

5. Reworded some additional method names, such as changing `maybeSyncFocus` to `focusLastFocusableObject`. To avoid confusion, `focusLastFocusableObject` is now explicitly delegated to this new functionality, i.e. only supposed to be used when automatic focus of focusable elements is off.

### Testing performed:
Tested on several websites, including examples as provied by @mltony and others. This is still a draft pr due to the error sensitivity of this code.

### Known issues with pull request:
1. When opening the following from an address bar:
    `data:text/html, <details><summary>Collapse or expand this</summary>Some text</details>`
    and pressing the button when unfocused, NVDA reports unknown and then returns back to the browse mode document.

2. When enabling pass through with NVDA+Space, NVDA announces the last focusable object as it now gains focus.

### Change log entry:
t.b.d.

### CODE REVIEW

**Comment by lukaszgo1** [comment]
What about the bug described in [this](https://github.com/nvaccess/nvda/pull/9114#issuecomment-457552665) commend? Is it fixed with the current approach?

**Review by michaelDCurran — APPROVED** [review]

**Comment by leonardder** [comment]
@mltony: Congrats on having this merged. We really couldn't have done this without you starting it.
Note that, after discussion with @feerrenrut and @michaeldcurran, we decided to store the gui option in the advanced settings for now.

Having said that, I'm pretty happy with the feature as is. The only thing that pisses me of is the regular unknown announcements. I really want to know how to avoid these.

**Comment by bramd** [comment]
Nice feature, glad it has been merged.

I have issues activating dialogs of my Lastpass extension in Chrome when this experimental option is used. The extension injects a frame with a dialog at the end of the DOM for example when a new account can be saved or a password change is detected. I didn't find an easy reproduceable minimal test case for this.

**Comment by MarcoZehe** [comment]
The performance improvements when navigating busy sites like Facebook are very cool. Here are some observations I have made across several browsers while playing with it in the latest Alpha snapshots:

1. I have issues activating certain links or buttons with this. One example is when downloading an attachment in Gmail, I have to press the button twice before the download starts.
2. Enter also often does not do anything while Space works. Also, tabbing to links within a table and pressing Enter doesn't activate them when in browse mode.
3. In WhatsApp Web, when virtual cursor is on one of the chat list entries, pressing Enter does not focus that particular entry and opens the chat. I have to turn browse mode off to get it to work.
4. Some buttons which have images as children don't activate. An example is Threema Web, where those buttons are even inside a list item. I haven't come up with a distilled testcase to repro this.
5. Application role seems to sometimes confuse things. One example is the Microsoft Community forum, when writing or replying to a forum post. It uses TinyMCE as the editor, which is inside an application role container. You can tab out of it onto the Post button, but activating that doesn't work undless you press Insert+Space first.

**Comment by leonardder** [comment]
I just noticed that I didn't post another try build to here:
https://ci.appveyor.com/api/buildjobs/p37e7tstnse63hu9/artifacts/output%2Fnvda_snapshot_try-focusFix-17256%2C72316d5e.exe

The bug underlying most of the issues reported by @MarcoZehe and @bramd, is that when focus follows browse mode is off, it is not possible to activate elements that are not focusable. This try build should fix that. Yet, it is again no longer possible to activate some of the show options buttons in github with this try build.

**Comment by MarcoZehe** [comment]
This try build actually fixes the issues I was reporting earlier, but it is over-chatting, e. g. each focusable element is repeated when pressing enter, like a link or form field. But you are probably aware of this. Easily observable on Github, or on Mobile Twitter when activating one of the links at the top like Home, Notifications etc.

**Comment by jcsteh** [comment]
When enabling pass through with NVDA+space, NVDA doesn't seem to set focus to the element under the cursor. For example:

1. Go to google.com.
2. Tab to the Google Search button.
3. Press shift+e to quick nav back to the search box.
4. Press NVDA+space to force focus mode.
5. Press NVDA+tab.
    - Expected: "Search  combo box  ..."
    - Actual: "Google Search button"

Is this intentional? This also happened with the original PR, but this comment in the PR description made me think it was fixed here:

> When enabling pass through with NVDA+Space, NVDA announces the last focusable object as it now gains focus.

**Pull request merged**
