### PR TITLE
Bump API version for 2024.1

### PR DESCRIPTION
**Pull request by seanbudd**

### CODE REVIEW

**Comment by nvdaes** [comment]
@cyrilleB79, imo the current approach of merging this early is right. If 
authors don't maintain available channels following recommendations for 
channels, it's the authors responsibility.

I think that it was anticipated here, and explained that this is to 
allow to post on the legacy website testable versions:


https://github.com/nvaccess/addon-datastore-transform/pull/2021/09/2023 
a las 14:12, Cyrille Bougot escribió:

> @seanbudd or @michaelDCurran:
> This PR has been merged early in the alpha cycle.
>
> Currently, some add-ons are setting 2024.1 as their last tested version.
> Since these add-on want to maintain only stable channels we end up with stable add-ons compatible with 2024.1 (Say product name and version, Resource monitor). With the changes that are still expected for 2024.1 (Python upgrade, wxPython upgrade, etc.), there is a non-zero probability that something break in these add-ons.
>
> Was it a mistake to update API version so early? I have the feeling that such behaviour was not anticipated nor expected.
>
> Thanks.
>
>
>

**Comment by leonardder** [comment]
I think @CyrilleB79 raises a valid point here that might best be discussed in https://github.com/nvaccess/addon-datastore-validation

In short, I think that an API or last tested version of 2024.1 should be denied for stable and beta add-ons and only accepted for dev add-ons. As soon as there's a 2024.1 beta, beta add-ons could be accepted but stable add-ons should still be denied until a stable version of that NVDA release is available. This is at least how I handle compatibility with my add-ons.

**Comment by XLTechie** [comment]
In the case of Say Product Name and Version:

This is a very simple add-on, which is very easy to maintain. It does not make 
sense to run a dev channel and a stable channel.
I have committed to keep it current with alpha.

This will not be the case for my complex add-ons like Speech Logger or Numpad 
Nav Mode, which will most definitely require dev channels and extensive testing.

I can not speak for other add-ons, as this is the only one of mine for which I 
have this plan.

My understanding, and I admit it could be faulty, was that the old rule as 
stated by @leonardder--that you can not release a compatible last tested until 
after beta1--has been rendered into a best practice instead of a hard 
requirement.

**Comment by CyrilleB79** [comment]
> In short, I think that an API or last tested version of 2024.1 should be denied for stable and beta add-ons and only accepted for dev add-ons.

I do not know if this can be enforced by NVDA, but it should at least be clarified if it is recommended as a good practice or even as a requirement to be followed by add-on authors.
This clarification may be done in [File metadata and controls](https://github.com/nvaccess/addon-datastore/blob/master/docs/submitters/jsonMetadata.md), but maybe there are other places where this should also be added.

**Comment by nvdaes** [comment]
This was an old rule applied for addonFiles, and was a rule for reviewers. We reviewers needed to look at this taking care so people didn"t break this rule. Now conlention is that beta channel is for add-ons for early adopters, tested with beta, stable or rc of NVDA, stable channel for stable addons tested with stable, and dev, with any preview versions, to test API changes. This is a recommendation, see the documentation for metadata in case >i"m missing something, but is not a hard rule, but I would follow it even for small add-ons.Enviado desde mi iPhoneEl 21 sept 2023, a las 15:55, Luke Davis ***@***.***> escribió:﻿
In the case of Say Product Name and Version:

This is a very simple add-on, which is very easy to maintain. It does not make 
sense to run a dev channel and a stable channel.
I have committed to keep it current with alpha.

This will not be the case for my complex add-ons like Speech Logger or Numpad 
Nav Mode, which will most definitely require dev channels and extensive testing.

I can not speak for other add-ons, as this is the only one of mine for which I 
have this plan.

My understanding, and I admit it could be faulty, was that the old rule as 
stated by @leonardder--that you can not release a compatible last tested until 
after beta1--has been rendered into a best practice instead of a hard 
requirement.

**Comment by seanbudd** [comment]
Please create new issues rather than discussion on closed PRs.

We cannot really stop add-on authors from releasing add-ons which falsely claim compatibility with an unstable version of NVDA. They are making this decision at their own risk, and it will cause users trouble in the future, if they try and install these add-on versions with a stable version of NVDA in the future.

We have been fairly clear in the:
- [JSON metadata file](https://github.com/nvaccess/addon-datastore/blob/master/docs/submitters/jsonMetadata.md#channel)
- [the user guide](https://www.nvaccess.org/files/nvda/documentation/userGuide.html#AddonStoreFilterChannel)

I am not sure what else we can do here other than removing add-ons and rejecting approval for submitters who falsely claim compatibility with stable channel add-ons.

**Pull request merged**
