### PR TITLE
Added DBeaver AppModule

### PR DESCRIPTION
**Pull request by JosielSantos**
This is a fix to [DBeaver](https://dbeaver.io/), an accessible database
tool that lets us explore graphically almost all types of databases (MySQL, SQL server, PostgreSQL, ...).

It is based on Eclipse SDK, so it has same problems that Zend Studio and Eclipse for Java.
Basically I copied the file *source/appModules/zendstudio.py* to *source/appModules/dbeaver.py*.

### Changelog entry
New features

### CODE REVIEW

**Comment by ehollig** [comment]
Does this PR fix #8426

**Review by LeonarddeR — APPROVED** [review]
Could you add a copyright header as in eclipse.py? The proper copyright would be:
`#Copyright (C) 2018 NV Access Limited, Josiel Santos`

**Comment by JosielSantos** [comment]
Thanks for approving!
I added and committed the copyright message.

**Comment by leonardder** [comment]
Great!

**Review by michaelDCurran — APPROVED** [review]

**Comment by Adriani90** [comment]
@JosielSantos there is issue #8426 regarding this software. Could you have a look at it? It seems there are still some problems with the grids.

**Pull request merged**
