### PR TITLE
Properly support MSVC 14.40 toolset for getting the universal CRT files

### PR DESCRIPTION
**Pull request by LeonarddeR**
### Link to issue number:
None

### Summary of the issue:
Microsoft is about to introduce Visual Studio 2022 version 17.10 in the near future. They decided to change the minor toolset version number, so we're going from MSVC 14.39 to 14.40. 
See [this](https://devblogs.microsoft.com/cppblog/msvc-toolset-minor-version-number-14-40-in-vs-2022-v17-10/) blog post for details.
Note that they'll stick with version 143 in the crt version string, which is very weird.

### Description of user facing changes
Building NVDA on visual studio 2022 version 17.10 (to be released) will work correctly.

### Description of development approach
Rather than expecting all toolset directories to start with 14.3, we expect them to start with the major version part only (i.e. 14).

### Testing strategy:
- Test with Visual Studio 2022 Preview. Note that you have to patch scons for this to work.
In the scons directory: `tool\MSCommon\vc.py`, change line 680 by adding the `-prerelease` parameter:
`        vswhere_cmd = [vswhere_path] + vswhere_version_args + ["-prerelease", "-property", "installationPath"]`
- Visual Studio 2022 stable is covered by appveyor.

### Known issues with pull request:
None known

### Code Review Checklist:

- [x] Documentation:
  - Change log entry
  - User Documentation
  - Developer / Technical Documentation
  - Context sensitive help for GUI changes
- [] Testing:
  - Unit tests
  - System (end to end) tests
  - Manual testing
- [x] UX of all users considered:
  - Speech 
  - Braille
  - Low Vision
  - Different web browsers
  - Localization in other languages / culture than English
- [x] API is compatible with existing add-ons.
- [x] Security precautions taken.

### CODE REVIEW

**Comment by LeonarddeR** [comment]
This is ready for review. I'm tempted to leave out a changelog entry, since it's only a cosmetic build system change.

**Review by seanbudd — APPROVED** [review]

**Comment by XLTechie** [comment]
@LeonarddeR wrote:

> I'm tempted to leave out a changelog entry, since it's only a cosmetic build system change.

Those of us who work on the build system, or use the instructions for running our own Appveyor builds, would appreciate a changelog entry.

**Comment by LeonarddeR** [comment]
In that case, I'm happy to add one as soon as the changelog for 2024.3 has been initiated.

**Comment by seanbudd** [comment]
That should be ready now, thanks for your patience

**Review by seanbudd — APPROVED** [review]

**Pull request merged**
