### PR TITLE
WASAPI: Switch back to the preferred device if it becomes available.

### LINKED ISSUE #15759: NVDA with wasapi does not reload current audio device on enter in audio settings panel
### Steps to reproduce:
* Switch NVDA to wasapi mode;
* In audio settings panel select not default audio device;
* Disconnect this audio device;
* NVDA should fall back to default device;
* Reconnect selected audio device again;
* Open audio settings panel and see that your custom audio output is still selected;
* Press enter to re-apply settings.

### Actual behavior:
NVDA does not switch back to custom audio device when it reconnects and does not try to reapply custom audio device setting when opening audio settings panel and pressing enter.
When not using wasapi, NVDA automaticaly tries to switch back to custom device when it reconnects or at least recovers it when pressing enter in audio panel.

### Expected behavior:
Wasapi behavior should be identical to the old audio behavior.

### NVDA logs, crash dumps and other attachments:
[nvda2023-11-08.log](https://github.com/nvaccess/nvda/files/13300555/nvda2023-11-08.log)

#### NVDA installed/portable/running from source:
Installed.

#### NVDA version:
alpha-29899,cb356535 (2024.1.0.29899)

#### Windows version:
Windows 11 23H2 (AMD64) build 22631.2506

#### Name and version of other software in use when reproducing the issue:
N/A.

#### Other information about your system:
N/A.

#### Does the issue still occur after restarting your computer?
Yes.

#### Have you tried any other versions of NVDA? If so, please report their behaviors.
Any NVDA version with wasapi.

#### If NVDA add-ons are disabled, is your problem still occurring?
Yes.

#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
Yes.

### PR DESCRIPTION
**Pull request by jcsteh**
### Link to issue number:
Fixes #15759.

### Summary of the issue:
If the audio output device is set to something other than the default and that device is (or becomes) unavailable (e.g. it is disconnected), NVDA will switch to the default device. However, when that device becomes available again (e.g. it is reconnected), NVDA continues to use the default device instead of switching back to the configured device. Worse, this can't be fixed by opening the audio preferences and pressing OK, since the Settings dialog only looks at the configuration and doesn't realise that the WASAPI code has fallen back to the default device.

### Description of user facing changes
If the audio output device is set to something other than the default and that device becomes available again after being unavailable, NVDA will now switch back to the configured device instead of continuing to use the default device. (#15759)

### Description of development approach
1. Pass the device name to the WasapiPlayer C++ code instead of the device id. This means that WasapiPlayer is created with the device name of the preferred device, even if that device is unavailable, allowing us to manage that in the C++ code.
2. Removed wasPlay_getDevices and its Python callers, since they are no longer needed.
3. Changed WasapiPlayer::open to detect whether the specified device is unavailable using an error code. If so, it falls back to the default device. We leave the preferred device name alone so we can use it later.
4. If the device is unavailable, WasapiPlayer::feed still falls back to the default device, but again does not clear the device name.
5. In NotificationClient, we now track device state change notifications in the same way we track default device changes.
6. In WasapiPlayer::feed, we now handle device state changes similar to how we handle default device changes.
7. If a device state change occurs, we scan for the preferred device by name. If it is available, we switch back to that.

### Testing strategy:
1. Configured NVDA to use a USB headset.
2. Set the Windows default device to laptop speakers.
3. Unplugged the headset.
4. Observed that NVDA switches to speakers.
5. Plugged the headset back in.
6. Observed that NVDA switches back to the headset.
7. Restarted NVDA.
9. Observed that NVDA uses the headset.
10. Exited NVDA.
11. Unplugged the headset.
12. Started NVDA.
13. Observed that NVDA uses the speakers.
14. Plugged the headset back in.
15. Observed that NVDA uses the headset.
16. Configured NVDA to use Microsoft Sound Mapper.
17. Observed that NVDA switches to the speakers.
18. Switched the Windows default device to the headset.
19. Observed that NVDA switches to the headset.

### Known issues with pull request:
None.

### Code Review Checklist:

- [x] Documentation:
  - Change log entry
  - User Documentation
  - Developer / Technical Documentation
  - Context sensitive help for GUI changes
- [x] Testing:
  - Unit tests
  - System (end to end) tests
  - Manual testing
- [x] UX of all users considered:
  - Speech 
  - Braille
  - Low Vision
  - Different web browsers
  - Localization in other languages / culture than English
- [x] API is compatible with existing add-ons.
- [x] Security precautions taken.

### CODE REVIEW

**Comment by kirill-jjj** [comment]
@jcsteh Very strange bug, when changing audio devices, some of them do not change. That is, despite the selected device, nvda speaks to the default device. When I rename the playback devices through properties, it starts working as expected. But when the devices have there original names, i.e. Virtual Out 1/2; NEOM USB, Virtual Out 3/4; NEOM USB, Virtual Out 5/6; NEOM USB, they don’t work, but if I, for example, replace the capital o in the word Out with a lowercase one, then the device for which I changed the letter starts working. Attaching a log file, here I'm switching between audio devices. The only one nvda  Actually switched to is Virtual Out 5/6.
[nvda devices.log](https://github.com/nvaccess/nvda/files/13339689/nvda.devices.log)

**Comment by jcsteh** [comment]
Urgh. My guess is that you have multiple devices with the same names, but some of them are unavailable, possibly from previous installations of the driver or something like that. In order to support switching back to preferred devices, NVDA has to look at unavailable devices as well as available ones because the preferred device might be unavailable when NVDA starts.

I'm not really sure how to fix this cleanly. I don't see how we can tell which is the actual preferred device, since we only store the name in the config, but both of them have the same name. Ideally, we'd store the id in the config instead of the name, but that would break existing configurations.

I guess we could make the C++ code take names instead of ids and then scan for the name instead of the id. That's rather ugly, but we might have to live with it.

**Comment by OzancanKaratas** [comment]
I'm not convinced that the problem mentioned above needs to be solved. It is the user's responsibility to remove old devices from the system. Complicating NVDA code may create problems that will be harder to deal with in the future. I think @seanbudd should also join the discussion.

**Comment by seanbudd** [comment]
Wouldn't there be a way to safely upgrade the config? I think we should probably display and store name/id pairs, so we can show all available devices. This makes it clear duplicates need to be cleaned up.

**Comment by jcsteh** [comment]
1. Upgrading the config isn't a great idea while we still have WinMM support. Maybe we can do this after WinMM is removed, but for now, we would break users that switch between WASAPI and WinMM.
2. Windows does have a tendency to leave old device crap lying around. Sometimes, this is beyond the control of the user; e.g. it could be due to an updated driver or something like that. Most of the time, users can't even see this unless they do some obscure stuff in Device Manager. There's not even a way to show these in the Windows Sound properties. Thus, I don't think cleaning up duplicates is a reasonable expectation for most users.
3. I think showing all devices, even unavailable ones, would be really confusing for the user. No other application does this.

**Review by michaelDCurran — APPROVED** [review]

**Pull request merged**
