### PR TITLE
Fix movement at end of document for modern UIA providers

### LINKED ISSUE #12808: Some UIA text ranges have no apparent bottom
### Steps to reproduce:
In various modern UIA text providers (notepad with UIA forceably enabled with `nav.appModule.isGoodUIAWindow = lambda hwnd: True` in console), an upcoming/private build of conhost, and Word/Edgium with UIA enabled):

1. Navigate to the last line of text with the review cursor.
2. Attempt to move to the next line of text.

### Actual behavior:
The review cursor is moved to the end of the current line, and "bottom" is not announced. Technical: `UIATextInfo.move` (`IUIAutomationTextRange::move`) returns 1.

### Expected behavior:
"bottom" is announced.

### Context:
It seems that, per Microsoft Word's behaviour (other UIA providers are copying this): when moving a degenerate (collapsed) range past the end of the document, the correct UIA behaviour is to permit the move and move to the end of the requested unit, whereas expanded ranges should not permit the move when attempting to go past the end. Is this correct UIA behaviour (the docs seem unclear) and therefore an NVDA bug, or are providers incorrectly implementing this (so I should raise it upstream)? Cc @csauls, @michaelDCurran and @leonardder.

### PR DESCRIPTION
**Pull request by codeofdusk**
### Link to issue number:
Closes #12808.

### Summary of the issue:
In Microsoft Word, new builds of Windows Console, and Edgium with UIA enabled, "bottom" is not reported when moving past the end of the document in review. These providers return nonzero when moving collapsed `textInfo`s forward past the end, but simply set them to `POSITION_LAST` (i.e. collapsed at the very end of the document).

### Description of how this pull request fixes the issue:
If a UIA provider reports that a collapsed range has successfully been moved forward (i.e. `move` returns nonzero), but the new range is collapsed at `POSITION_LAST`, return `0` and restore the range to its original position.

### Testing strategy:
Tested that movement in review works as expected in Word, `FORMATTED` consoles, and Edgium.

### Known issues with pull request:
This might have a slight performance impact, but I've tried to optimize this so that we only make extra UIA calls for this specific case.

### Change log entries:
== Bug Fixes ==
- "bottom" is reported when attempting to move the review cursor past the end of Microsoft Word documents and other modern UI Automation controls. (#12808)

### Code Review Checklist:

- [x] Pull Request description:
  - description is up to date
  - change log entries
- [x] Testing:
  - Unit tests
  - System (end to end) tests
  - Manual testing
- [x] API is compatible with existing add-ons.
- [x] Documentation:
  - User Documentation
  - Developer / Technical Documentation
  - Context sensitive help for GUI changes
- [x] UX of all users considered:
  - Speech 
  - Braille
  - Low Vision
  - Different web browsers
  - Localization in other languages / culture than English

### CODE REVIEW

**Comment by codeofdusk** [comment]
Marking this for review, though the build is failing and I can't figure out why.

**Comment by leonardder** [comment]
This pr doesn't solve the following case:

```
>>> nav.makeTextInfo("last").move("character", 1)
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "NVDAObjects\UIA\web.pyc", line 186, in move
  File "NVDAObjects\UIA\web.pyc", line 177, in _collapsedMove
  File "NVDAObjects\UIA\web.pyc", line 144, in _moveToEdgeOfReplacedContent
  File "baseObject.pyc", line 26, in __get__
  File "NVDAObjects\UIA\web.pyc", line 115, in _get_UIAElementAtStartWithReplacedContent
  File "monkeyPatches\comtypesMonkeyPatches.pyc", line 30, in __call__
_ctypes.COMError: (-2147467259, 'Unspecified error', (None, None, None, 0, None))
```

How are those degenerate ranges supposed to behave? Is it expected behaviour that you can't move from position last at all, even not backwards?

**Comment by codeofdusk** [comment]
> How are those degenerate ranges supposed to behave? Is it expected behaviour that you can't move from position last at all, even not backwards?

Word and `FORMATTED` conhost return 0 for these.

**Comment by seanbudd** [comment]
>Marking this for review, though the build is failing and I can't figure out why.

Apologies, ignore the build failure, we had to fix something to work with the latest Windows SDK - see #12903. 
I've triggered another build for this PR now - hopefully it works.

**Comment by codeofdusk** [comment]
Thanks @seanbudd. It looks like this PR built successfully so is now ready for review.

**Comment by leonardder** [comment]
If we change the move method on OffsetsTextinfo in such a way that it moves to the end of the range when moving from the start of the last line, we can change the global command to fetch the last position of the textInfo

`api.getReviewPosition().obj.makeTextInfo(textInfos.POSITION_LAST)`

Then, we can compare the new position with that and report bottom appropriately. This is somehow similar to how script_review_nextCharacter works to ensure that the review cursor doesn't move past the end of the line.

**Pull request closed without merging**
