### PR TITLE
Add supports Seika Notetaker Braille display

### PR DESCRIPTION
**Pull request by moyanming**
Add supports Seika Notetaker Braille display.
Add driver files by using the Seika Notetaker addon for NADA v3.3.
### Link to issue number:
#9479 
### Change log entry:

Section: New features, Changes, Bug fixes
New features.

### CODE REVIEW

**Comment by dingpengyu** [comment]
hi@moyanming 
The following error occurred during the build:
PR introduces Flake8 errors
thanks

**Comment by moyanming** [comment]
Hi @dingpengyu ,
Thanks for the reply. I will fix the Flake8 errors very soon.

**Comment by JulienCochuyt** [comment]
@moyanming, the DLLs most likely belong to the `nvda-misc-deps` repo - as all other binary dpendencies do - and will thus require a second PR just for them.
As stated by @feerrenrut in https://github.com/nvaccess/nvda/pull/9479#issuecomment-611061131, we're waiting for @michaelDCurran thoughts on this matter.

**Comment by feerrenrut** [comment]
Blocked pending feedback from @michaelDCurran

**Comment by michaelDCurran** [comment]
What is the license for these 3 dlls? Is the source code available? Our policy these days is usually not to add device dlls to NVDA, preferring pure Python code, or at very least, public access to the source code, what ever the language.

**Comment by leonardder** [comment]
This looks like a new incarnation of #9479. I expressed my concrn with this driver in https://github.com/nvaccess/nvda/pull/9479#issuecomment-481637672.

**Comment by Adriani90** [comment]
@moyanming could you please respond to the last two comments above?

**Comment by feerrenrut** [comment]
Looking at the properties for these dll's, they are "Copyright Silicon laboratories, Inc". We have no license to use and distribute them. Given there is no indication that the PR author is going to seek a license to use these files, unfortunately means I will have to close this PR. I'll also mark it as abandoned, we haven't heard from the author since April.

I would like to welcome anyone interested to seek a license for the NVDA project to use these files.

**Comment by leonardder** [comment]
I'd rather see a native driver, avoiding the use of DLLs altogether.

**Comment by feerrenrut** [comment]
Yes, I agree.

**Comment by moyanming** [comment]
> @moyanming could you please respond to the last two comments above?

Hi @Adriani90 ,
Thanks for the feedback about the Seika Notetaker.
We already add a new driver all by using the Python3 code and please find here #11514 .

**Pull request closed without merging**
