### PR TITLE
Add extension points to eliminate NVDA Remote monkey patching

### PR DESCRIPTION
**Pull request by LeonarddeR**
### Link to issue number:
None. Some discussion around https://github.com/nvaccess/nvda/pull/7484#issuecomment-322806698 though
Follow up of #7594, now in draft form

### Summary of the issue:
NVDA Remote requires monkey patching to be notified of several actions on a controlled system (e.g. selecting a braille display or playing beeps).

### Description of how this pull request fixes the issue:
Implemented the following extension points:

* braille.handler.filter_writeCells: To filter raw cells before sending them to a braille display
* braille.handler.filter_displaySize: to filter the display size, e.g. when a remote system has a smaller display
* braille.handler.decide_enabled: to allow remote to forcefully disable the local braille handler
* braille.handler.pre_writeCells: To notify of cells about to be written to a display.
* inputCore.manager.decide_executeGesture: Decider to block some gestures from executing
* tones.decide_beep: to notify a remote system of beeps, allowing to disable local beeping
* nvwave.decide_playWaveFile: to notify a remote system of waves played, allowing to disable local playing

### CODE REVIEW

**Comment by leonardder** [comment]
Investigating the NVDA Remote source code and the possible upgrade path to Python 3, I discovered that some additional extension points could be considered. Here is a quick run down of my ideas, particularly for @feerrenrut 

* Optionally, an extension point could be added that could filter or process a speech sequence before it is delivered at the speech manager. This could be added to `speech.speak`, after the sequence normalisation part.
* Below that, an extension point could be added that notifies any registered parties about a speech sequence about to be send to the speech manager. This can be used by NVDA Remote to send the speech sequence to the remote system. It is important that this sequence doesn't contain index commands, in other for the controlling system to do its own indexing.
* cancelSpeech should also contain an extensionPoint to notify the remote system that speech is cancelled.

NVDARemote on python 2 does al sorts of stuff with monkey patching synthDriverHandler.getSynth, in order to be able to monkeypatch the synthesizer driver. This should no longer be necessary, neither if NVDARemote is converted to Python 3 without implementing extension points in NVDA. In the latter case however, it might be better to monkeypatch speech._manager.speak and speech._manager.cancel instead.

**Comment by zstanecic** [comment]
Hi @leonardder,

Will this involve yet another synthdriver changes?

**Comment by leonardder** [comment]
Nope, it's not necessary to change synth drivers again. Note that this 
pr is just a prototype.

**Comment by leonardder** [comment]
This has always been a draft. As this was only a reference pr and nvda remote 2.3 for python 3 works ok for now, I"m closing this.

**Pull request closed without merging**
