### PR TITLE
Reintroduce our custom build of wxPython with the onAssert fix and debug symbols into miscDeps

### LINKED ISSUE #6641: custom wxPython accidentally dropped from NVDA master
It looks like although the custom wxPython got into 2016.3, it
was then dropped out of master in commit
 03e1de9  (September 19), pr #6268.

In pr #6268, miscDeps was updated to commit
c1f4f7df89be9e1499e5175baae55b14f483ed94.

However, its parent was 792a25485cc0029b4160779a161d8802f75d888a (April
29), but it should have been 66534082b60d4266d9352f7462953213eb05156a
(July 17).

### PR DESCRIPTION
**Pull request by michaelDCurran**
Fixes #6641

Originally introduced in #6268, but dropped some time in September 2016.

### CODE REVIEW

**Review by feerrenrut — APPROVED** [review]
Its hard for me to verify that these are the same files as the  missing commit.

One thing I would note, is that the `i6641_reintroduceCustomWXPython` branch has not been merged to the misc-deps master. This could result in this commit being left out again in the future.

**Comment by michaelDCurran** [comment]
That commit in miscDeps is currently held at a branch tip in miscDeps 
called i6641_reintroduceCustomWXPython


We shouldn't really update miscDeps' master until that commit is in 
NVDA's master in my opinion. Say for instance you had several separate 
commit tips in miscDeps, referenced by prs in NVDA not yet in next or 
master, they couldn't really be put in miscDeps master as they are 
simply not related.


True though we should try and keep miscDeps master up to date with NVDA 
master in future at least. However, I feel it is still up to the owner 
of the NVDA pr to ensure that they base their miscDeps change on the 
miscDeps commit referenced by NVDA master at the time of the pr, rather 
than perhaps assuming miscDeps master is correct.


As to validating that these are the same files added in July:

The i6641_reintroduceCustomWXPython pr #6642 branch points at the new 
miscDeps commit: b49d2f7


That miscdeps commit is made up of a merge of the commits:

c1f4f7d (miscDeps commit currently pointed to by NVDA master)

and

6653408 (miscDeps commit pointed to by NVDA commit 8f25239 which 
introduced custom wxPython into NVDA master).

**Comment by feerrenrut** [comment]
Ok cool I double checked the commits are all good. Perhaps opening a PR is one thing we could do for updates to misc-deps that are in limbo. That way we can easily see what needs merging to misc-deps master.

**Review by jcsteh — APPROVED** [review]
Just for extra certainty, I used git diff to confirm this:

```
$ newWx=66534082 # When the new wx got added
$ boost=c1f4f7df # When Boost got added and wx got removed
$ merge=b49d2f77 # Mick's reinstatement of new wx
$ # Confirm that wx was (accidentally) changed when Boost got added
$ git diff --name-status $newWx..$boost
A       include/boost/LICENSE_1_0.txt
A       include/boost/optional.hpp
M       python/wx/_activex.pyd
M       python/wx/_animate.pyd
...
M       python/wx/build/config.py
$ # Confirm that wx was changed by merge
$ git diff --name-status $boost..$merge
M       python/wx/_activex.pyd
M       python/wx/_animate.pyd
...
M       python/wx/build/config.py
$ # Confirm that wx hasn't changed between newWx and merge and that Boost is added
$ git diff --name-status $newWx..$merge
A       include/boost/LICENSE_1_0.txt
A       include/boost/optional.hpp
```

**Comment by michaelDCurran** [comment]
Do we want this in Next, or just straight to master?

Fine with either.

**Comment by jcsteh** [comment]
Next first please.

**Pull request merged**
