### PR TITLE
In MS Word, fixed table quick navigation when include layout table option is enabled

### PR DESCRIPTION
**Pull request by CyrilleB79**
### Link to issue number:

None

### Summary of the issue:

In MS Word/Outlook browse mode, layout tables (i.e. tables with no border) are skipped when using table quick navigation key (T and shift+T), even if "Include layout tables" options is enabled in Browse mode settings.

### Description of how this pull request fixes the issue:

In `NVDAObjects\window\winword`, I have modified the `TableWinWordCollectionQuicknavIterator` `filter` method so that the iterator returns a table if borders are enabled or if layout tables should be included.

I have checked in `nvdaHelper\remote\winword.cpp` that the presence or the absence of a border was already the criterion that defines if a table is a layout table or not. (so nothing done in this file)

### Testing performed:

In MS word checked table quick navigation commands (T and shift+T):
* with include layout tables enabled: they stop on any table
* with include layout tables disabled: they stop on tables with borders but skip tables without borders

### Known issues with pull request:

None

### Change log entry:

Section: Bug fixes

`In MS Word or Outlook, table quick navigation key can now jump to layout table if "Include layout tables" option is enabled in Browse mode settings (#11899).`

### CODE REVIEW

**Comment by lukaszgo1** [comment]
@CyrilleB79 wrote:
>In MS Word/Outlook browse mode, layout tables (i.e. tables with no border) are skipped when using table quick navigation key (Y and shift+Y), even if "Include layout tables" options is enabled in Browse mode settings.

Just to make sure - you mend T and Shift+T, right?

**Comment by CyrilleB79** [comment]
> @CyrilleB79 wrote:
> 
> > In MS Word/Outlook browse mode, layout tables (i.e. tables with no border) are skipped when using table quick navigation key (Y and shift+Y), even if "Include layout tables" options is enabled in Browse mode settings.
> 
> Just to make sure - you mend T and Shift+T, right?

Yes, sorry. I have modified the initial description with the correct shortcuts.

**Comment by CyrilleB79** [comment]
@seanbudd: just tried to convert to draft and ready again in order to have a reviewer assigned...
This PR is quite small so maybe it has still a chance to target 2021.1?

**Review by seanbudd — APPROVED** [review]
LGTM, thanks @CyrilleB79

**Pull request merged**
