### PR TITLE
Handle menu start events processed after the menu item

### LINKED ISSUE #12624: First item not read when opening context submenu
This issue gives a STR in Outlook French.
The issue is not specific to French but it's just the language of my Office/Windows.
Update: This issue occurs also in sub-menus in other applications; Thunderbird has been confirmed.

### Steps to reproduce:
1. Go in Outlook's message list and select a message
2. Press the application key to open the context menu
3. Press down arrow many times until you reach an item which has a submenu (you will hear "collapsed")
4. Press right arrow to open the submenu
5. Go to advanced options and set 'Attempt to cancel speech for expired focus events' option to 'No'
6. Re-execute steps 1. to 4.

### Actual behavior:
At step 4. you can hear:
'expanded' (interrupted), 'list', 'menu'

The log is the following when pressing right arrow:
```
IO - inputCore.executeGesture (17:07:55.077) - winInputHook (10864):
Input: kb(desktop):rightArrow
IO - speech.speech.speak (17:07:55.167) - MainThread (13900):
Speaking ['expanded']
IO - speech.speech.speak (17:07:55.307) - MainThread (13900):
Speaking ['list', CancellableSpeech (still valid)]
IO - speech.speech.speak (17:07:55.327) - MainThread (13900):
Speaking ['Boîte de réception', 'not selected', CancellableSpeech (still valid)]
IO - speech.speech.speak (17:07:55.337) - MainThread (13900):
Speaking ['menu', CancellableSpeech (still valid)]
```
We can see in the log that 'Boîte de réception' and 'not selected' are spoken but they are actually not heard at all.

At step 6. you can hear:
'expanded' (interrupted), 'list', 'Boîte de réception', 'not selected', 'menu'
Note: 'Boîte de réception' stands for 'Inbox' in French and was the first item of the submenu.

The log is the following when pressing right arrow:
```
IO - inputCore.executeGesture (17:18:47.738) - winInputHook (10864):
Input: kb(desktop):rightArrow
IO - speech.speech.speak (17:18:47.827) - MainThread (13900):
Speaking ['expanded']
IO - speech.speech.speak (17:18:47.960) - MainThread (13900):
Speaking ['list']
IO - speech.speech.speak (17:18:47.977) - MainThread (13900):
Speaking ['Boîte de réception', 'not selected']
IO - speech.speech.speak (17:18:47.997) - MainThread (13900):
Speaking ['menu']

```

### Expected behavior:
The first menu item's name ('Boîte de réception') should be reported when the menu is opened, whatever the setting of the option 'Attempt to cancel speech for expired events'.

### Note
* This may be considered regression of NVDA 2021.1 since the advanced option was not enabled by default in 23020.4
* I imagine such a minor bug will not stop the release in any case.
* I think this issue is not specific to Outlook. I have read messages describing the same issue in submenus of Thunderbird. I have not verified it by myself however.

#### NVDA installed/portable/running from source:
Installed
#### NVDA version:
NVDA 2021.1rc2
#### Windows version:
Windows 10 1809 (64-bit) build 17763.1935
#### Does the issue still occur after restarting your computer?
Yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
2020.4 with default config: issue not present.
But 2020.4 with cancellable speech activated: issue present.

#### If add-ons are disabled, is your problem still occurring?
Yes

#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
Yes

### PR DESCRIPTION
**Pull request by seanbudd**
### Link to issue number:

Fixes #12624 

### Summary of the issue:

When opening a submenu in certain applications (like Thunderbird 78.12),
NVDA can process a menu start event after the first item in the menu is focused.
The menu start event causes a focus event on the menu, taking NVDA's focus from the menu item.
Additionally, the "menu" parent of the submenu item is not keyboard focusable, and is separate from
the menu item which triggered the submenu.
The object tree in this case (menu item > submenu (not keyboard focusable) > submenu item).
The focus event order after activating the menu item's sub menu is (submenu item, submenu).

### Description of how this pull request fixes the issue:

Before cancelling speech, check that the focus is now on the parent menu.

### Testing strategy:

Manual testing (note that this does not always occur and is hard to consistently reproduce):
1. Enable debug logging
1. With a Thunderbird 78.12 context menu (activate one on an email, for example)
1. navigate to a menu item with a submenu. 
1. Activate it.
1. Examine the logs for an event (submenu item, submenu) - eg the speech is announced in this order in the logs, as are the events if event debugging is enabled.
On this PR: Confirm that this case has extensive logging when it occurs. When this event occurs confirm that the menu item is spoken, followed by the submenu. If you want to hear a beep on this event, change the logging to an error beep.
On 2021.1: Confirm that only menu item is spoken, as the seubmenu item is cancelled.

### Known issues with pull request:

This may be an overzealous check. Speech in similar contexts that should be cancelled may continue to be spoken.
As such, debug logs are added to make handling new cases easier until the root problem of event processing is addressed.

### Change log entries:
Bug Fixes

```
- Fixed bug where the first menu item is not announced in a submenu in some contexts. (#12624)
```

### Code Review Checklist:

- [x] Pull Request description is up to date.
- [x] Unit tests.
- [x] System (end to end) tests.
- [x] Manual testing.
- [x] User Documentation.
- [x] Change log entry.
- [x] Context sensitive help for GUI changes.
- [x] UX of all users considered:
  - Speech 
  - Braille
  - Low Vision
  - Different web browsers

### CODE REVIEW

**Comment by lukaszgo1** [comment]
I'm not sure this would be a complete fix for #12624 - its original STR mentioned context menu in Outlook which depending on the version (unfortunately @CyrilleB79 forgot to mention version of his Outlook) can be  UIA not IAccessible. Were you able to  reproduce the Outlook issue?

**Comment by seanbudd** [comment]
>Were you able to reproduce the Outlook issue?

I could not reproduce this in my version of Outlook, I realised I mistakenly deleted a comment on the issue which mentioned that, so I've reposted it on the issue (see https://github.com/nvaccess/nvda/issues/12624#issuecomment-893016643).

@CyrilleB79 - could you confirm this PR build works to fix the issue on your version of Outlook, as well list the Outlook version info?

**Review by feerrenrut — DISMISSED** [review]
Looks good, can you confirm this fixes the Thunderbird case?

>This may be overzealous and lead to less unwanted speech being cancelled.

I'm struggling to parse this, is the concern it will lead to more unwanted speech?

**Comment by seanbudd** [comment]
Yep, the Thunderbird case it what I tested with and I can confirm this fixes it. 

This is just noting that if any other scenario matches the check, speech won't be cancelled. I've rephrased the comment to
>This may be an overzealous check. Speech in similar contexts that should be cancelled may continue to be spoken.

Because I updated the changes, this will need reapproval.

**Review by feerrenrut — APPROVED** [review]

**Comment by CyrilleB79** [comment]
> @CyrilleB79 - could you confirm this PR build works to fix the issue on your version of Outlook, as well list the Outlook version info?

Unfortunately NVDA 2021.2beta1 does not fix the Outlook issue. The version of Outlook is Outlook 2016 version 16.0.5182.1000. More details in https://github.com/nvaccess/nvda/issues/12624#issuecomment-896315286.

**Pull request merged**
