### PR TITLE
Support for ARIA 1.1 combo boxes in Firefox and Chrome.

### LINKED ISSUE #9616: Handling ARIA 1.1 Combobox is broken in Chrome and Firefox
ARIA 1.0 combobox role should be applied to `<input>`, but ARIA 1.1 combobox role is being applied to a container.

NVDA seems to handle ARIA 1.0 comboboxes ok. But handling ARIA 1.1 comboboxes is broken:
  1. In Browse mode NVDA just skips the combobox and its entire contents including `<input>` inside the container with `role=combobox`.
  2. I can use Tab to focus the `<input>` inside the container with `role=combobox`, but when that `<input>` has focus, switching between Browse/Focus modes doesn't work.
  3. The Next Combobox shortcut doesn't work as well (saying «no next combobox»).

The reference example: https://www.w3.org/TR/wai-aria-practices/examples/combobox/aria1.1pattern/listbox-combo.html.

Installed NVDA 2019.1.1, Windows 10.

### PR DESCRIPTION
**Pull request by jcsteh**
### Link to issue number:
Fixes #9616 .

### Summary of the issue:
ARIA 1.1 combo boxes (where the combo box contains a text box and a pop-up such as a list box) often weren't rendered in browse mode at all, making them effectively non-existent. Even if they were, you couldn't read the value or press enter to interact with the text box.

### Description of how this pull request fixes the issue:
1. If the first child of a combo box is a text box, render that text box in browse mode.
2. Previously, we treated anything inside a combo box as being outside a browse mode document (#8687). Don't do this for text boxes. Otherwise, you can't switch back to browse mode when the text box has focus.

### Testing performed:
1. In Firefox, tested the [ARIA 1.1 Combobox with Listbox Popup Examples](https://www.w3.org/TR/wai-aria-practices/examples/combobox/aria1.1pattern/listbox-combo.html). Ensured that the combo box and its text box were rendered in browse mode, that pressing enter focused the text box and switched to focus mode and that it's possible to switch back to browse mode with escape or NVDA+space.
2. In Firefox, tested a simple HTML select with size 1. Confirmed that the behaviour is unchanged; i.e. the combo box and its value are rendered in browse mode.

### Known issues with pull request:
This assumes that a text box will always be the first child of the combo box. All the examples (including the official spec examples) do this and this is what I've seen in the wild. We could change this to scan all children, but I'm reluctant to do this unless we have to.

### Change log entry:

Bug Fixes:
`- ARIA 1.1 combo boxes are now supported in Mozilla Firefox and Google Chrome. (#9616)`

### CODE REVIEW

**Comment by leonardder** [comment]
Some things I observed.

1. The aria comboboxes aren't expandable with alt+down arrow. I expected that that would happen.
2. The third example, opening it and pressing down arrow populates the edit box with apple. ANother press of down arrow focuses the list. This might be expected behavior based on the widget's implementation, though.
3. When the list gets focus instead of the edit box, the name of the control is repeated. I would expected that only list is announced, but again, this might be related to the implementation.

**Comment by jcsteh** [comment]
>     1. The aria comboboxes aren't expandable with alt+down arrow. I expected that that would happen.

Do you mean pressing alt+downArrow from browse mode or focus mode? Those combo boxes seem to have weird behaviour with alt+downArrow. That said, downArrow is usually enough to open an autocomplete if appropriate.

>     2. The third example, opening it and pressing down arrow populates the edit box with apple. ANother press of down arrow focuses the list. This might be expected behavior based on the widget's implementation, though.

When you say "opening it", do you mean alt+downArrow? That behaves strangely for me with these examples; it seems to open, but when you release alt, it collapses.

>     3. When the list gets focus instead of the edit box, the name of the control is repeated. I would expected that only list is announced, but again, this might be related to the implementation.

The implementation has the label on both the text box and the list, so yes, this is related to the implementation. If that's common, we could potentially filter this out, but I think that's out of scope for this PR.

**Comment by leonardder** [comment]
> 
> 
> > ```
> > 1. The aria comboboxes aren't expandable with alt+down arrow. I expected that that would happen.
> > ```
> 
> Do you mean pressing alt+downArrow from browse mode or focus mode? Those combo boxes seem to have weird behaviour with alt+downArrow. That said, downArrow is usually enough to open an autocomplete if appropriate.

In both browse and focus mode.

> > 2. The third example, opening it and pressing down arrow populates the edit box with apple. ANother press of down arrow focuses the list. This might be expected behavior based on the widget's implementation, though.
> > ```
> 
> When you say "opening it", do you mean alt+downArrow? That behaves strangely for me with these examples; it seems to open, but when you release alt, it collapses.
> 

Exact sstr are:

1. Go to the third example in browse mode
2. Press space on the combo box to activate it (switch to focus mode)
3. Press down arrow: I hear apple
4. Press down arrow again, i hear Choice 3 Fruit or Vegetable list, Artichoke

**Comment by jcsteh** [comment]
> > > ```
> > > 1. The aria comboboxes aren't expandable with alt+down arrow. I expected that that would happen.
> > > ```
> > 
> > 
> > Do you mean pressing alt+downArrow from browse mode or focus mode?
>
> In both browse and focus mode.

The fact that this doesn't work in focus mode is because the test cases don't support it. I don't know of any ARIA 1.1 combo boxes that do. They tend to expand when you start typing or when you press down arrow.

My feeling is that we shouldn't do anything for browse mode here unless we can find a combo box that actually supports this. That can be done as a follow-up. Does that work for you?

>     1. Go to the third example in browse mode
> 
>     2. Press space on the combo box to activate it (switch to focus mode)
> 
>     3. Press down arrow: I hear apple

For me, the list gets focus when I press down arrow here. However, I'm using Firefox nightly. I suspect you're being bitten by https://bugzilla.mozilla.org/show_bug.cgi?id=1571327 , which I fixed a month ago (targeting Firefox 70).

**Comment by leonardder** [comment]
> My feeling is that we shouldn't do anything for browse mode here unless we can find a combo box that actually supports this. That can be done as a follow-up. Does that work for you?

Sure!

> For me, the list gets focus when I press down arrow here. However, I'm using Firefox nightly. I suspect you're being bitten by https://bugzilla.mozilla.org/show_bug.cgi?id=1571327 , which I fixed a month ago (targeting Firefox 70).

Ah, in that case, let's assume it will be fixed in FF70 for me as well.

**Review by LeonarddeR — APPROVED** [review]

**Review by michaelDCurran — APPROVED** [review]

**Pull request merged**
