### PR TITLE
Ticket #2446 -> Saying bullet levels in word/powerpoint

### PR DESCRIPTION
**Pull request by vrdhn**
Add speaking out of  'List Level' in Word and Powerpoint Lists.

### CODE REVIEW

**Comment by vrdhn** [comment]
closed because it's showing ticket 5506,  will reopen for ticket 2446

**Comment by bdorer** [comment]
@vrdhn I think your pr has been forgotten. If you want to have it included, you should fix merge conflicts.

**Comment by feerrenrut** [comment]
This is a feature that we would like to accept. We would like to review this, however the merge conflicts will need to be addressed before it can be incubated.

**Comment by Adriani90** [comment]
@vrdhn, I see that you do not have the NVDA project forged anymore. Will you continue working on this PR? Or should someone else do it? Is this PR still valid?

**Comment by vrdhn** [comment]
Hi.  _we_ are group of people working in this fork https://github.com/nvda-india/nvda 
I'm dormant right now, but @dineshkaushal may like to pick this up.

**Comment by leonardder** [comment]
@vrdhn: Could you please allow commits from maintainers so I can push in such a way that the merge conflicts are fixed?

**Comment by vrdhn** [comment]
hi @leonardder , I'm afraid we are not doing a good job of keeping the fork up to date.
I'ld strongly recommend copy the change from here and work directly on a fork from
nvaccess/nvda, 

Thanks

**Comment by leonardder** [comment]
There's no need to keep the fork up to date for this. Giving maintainers 
push access will allow me to push within the branch of your fork, 
allowing me to update this particular pr without having to create a new one.

**Pull request closed without merging**
