### PR TITLE
Support opening the Elements List dialog in focus mode (#10453)

### LINKED ISSUE #10453: Support opening the Elements List dialog in focus mode
### Is your feature request related to a problem? Please describe.

The Elements List dialog can currently be opened (with `NVDA+F7`) only when in browse mode.
It is confusing for beginners, and uselessly tedious for more experienced ones.

### Describe the solution you'd like

Support invoking it when in focus mode too.
I guess the lesser impact UX would be to switch to browse mode when invoking the dialog from focus mode.

### Additional context

PR on its way.

### PR DESCRIPTION
**Pull request by JulienCochuyt**
### Link to issue number:

Fixes #10453

### Summary of the issue:

The Elements List dialog can currently be opened (with NVDA+F7) only when in browse mode.
It is confusing for beginners, and uselessly tedious for more experienced ones.

### Description of how this pull request fixes the issue:

Flag the Elements List dialog script with `ignoreTreeInterceptorPassThrough`.
When invoking, first switch back to browse mode and report the eventual change.

### Change log entry:

Section: Changes

In web browsers and supporting applications, the Elements List dialog (`NVDA+F7`) can now be invoked when in focus mode. NVDA will then switch back to browse mode before opening the dialog.

### CODE REVIEW

**Comment by leonardder** [comment]
Have you tested this in Excel as well as along with the "Enable browse mode on page load" option disabled?

Note that in cases where browse mode is off by default, which is always the case in MS Word, there is no tree interceptor, so there is no script and no elements list until you have enabled browse mode for the first time.
On the other hand, in Microsoft Excel, the tree interceptor is force created en de elements list is also available in focus mode..

**Comment by leonardder** [comment]
Ugh, my firefox bounced focus there.

**Comment by JulienCochuyt** [comment]
@leonardder, nope, I must confess I mostly had browsers in mind as this feature is actually ported from WebAccess where our users did request this change a while back.
Thanks for the precision, I'll thoroughly test Word and Excel and report my results here.
Would you know of other BrowseModeTreeInterceptor implementations that might require special attention?

**Comment by Brian1Gaff** [comment]
I've been getting a lot of that lately, trying to get at some parts of a 
page is definitely odd with nvda on recent versions of firefox. I was in our 
talking newspaper the other day and the only way I could find I could get 
the play button was to use the elements list set to buttons, it just skipped 
past it in normal brows or even tabbing in focus mode.

 I did do a ticket for this, but it might be a duplicate of something else 
and I can't get the number right now. It also intermittently happens on 
waterfox, but not on chrome or IE 11.
 Brian

bglists@blueyonder.co.uk
Sent via blueyonder.
Please address personal E-mail to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.
Newsgroup monitored: alt.comp.blind-users
-----

**Comment by JulienCochuyt** [comment]
@Brian1Gaff, I guess you are referring to #10379 

@leonardder we actually did not bother switching back to browse mode when setting `ignoreTreeInterceptorPassThrough = True` on the `elementsList` script in WebAccess, but I felt it would be more comprehensive that way. Seems I did not think it enough, as I'm far from being an expert on Word and Excel implementations.
Maybe should I try the following alternative approach:
- Not switching modes at all prior to opening the dialog
- Alter `ElementsListDialog.onAction` so that it does not call `item.report`
- Alter `TextInfoQuickNavItem.moveTo` so that:
    - if currently in browse mode, move as usual but also call `item.report`
    - if currently in focus mode:
        - if attempting to move to a focusable object, focus it
        - if attempting to move to a not focusable place, switch to browse mode, move, and report.

What do you think?

**Comment by leonardder** [comment]
@JulienCochuyt wrote;

> What do you think?

I think that's better. It also means that if automatic focus mode is enabled, invoking the elements list and then focussing an element doesn't have to switch on browse mode at all.

> Btw. I just noticed `ElementsListDialog.onAction` does not care about #8831 as does `BrowseModeTreeInterceptor._quickNavScript`. Thus, I guess we should report before moving in the Elements List as well.

Why report before moving in? I don't think that's very important.

**Comment by JulienCochuyt** [comment]
@leonardder wrote:
> Why report before moving in? I don't think that's very important.

The comment from Jamie on 2019-10-21 in `BrowseModeTreeInterceptor._quickNavScript` as of PR #10389 says:
(I hadn't noticed how recent it was before blaming it for reference here.)
> #8831: Report before moving because moving might change the focus, which
> might mutate the document, potentially invalidating info if it is
> offset-based.

**Comment by leonardder** [comment]
I assume that for quicknav, it is important to report something has been 
focused before actually focussing it, but I don't think it has to be 
considered for the elements list.

**Comment by michaelDCurran** [comment]
I agree switching to browse mode only when moving to, if necessary, is the better way to go. I would not have liked switching to browse mode when opening the dialog.

**Review by michaelDCurran — APPROVED** [review]

**Pull request merged**
