### PR TITLE
Move Key Commands doc script out of base repo folder

### PR DESCRIPTION
**Pull request by seanbudd**
### Link to issue number:
Clean up of #15945 
### Summary of the issue:
The key commands doc generator script is in the base folder of the repository - it should be moved to a folder to keep the base repo tidy.
I propose it is moved to user_docs - particularly because of its relation to the docs, and the fact that the t2tconf files will be removed.

The documentation for key commands is lacking in the wiki: https://github.com/nvaccess/nvda/wiki/TranslatingUserGuide
The inline documentation in the module covers the syntax more thoroughly and should be moved to project docs.
### Description of user facing changes
None

### Description of development approach
Move folder
### Testing strategy:
Test building user docs including key commands.
### Known issues with pull request:
None
### Code Review Checklist:

- [x] Documentation:
  - Change log entry
  - User Documentation
  - Developer / Technical Documentation
  - Context sensitive help for GUI changes
- [x] Testing:
  - Unit tests
  - System (end to end) tests
  - Manual testing
- [x] UX of all users considered:
  - Speech 
  - Braille
  - Low Vision
  - Different web browsers
  - Localization in other languages / culture than English
- [x] API is compatible with existing add-ons.
- [x] Security precautions taken.

### CODE REVIEW

**Comment by lukaszgo1** [comment]
Shouldn't `keyCommandsDoc.py` be removed from the top level directory? For now it appears to be duplicated in `user_docs`.

**Comment by seanbudd** [comment]
Thanks @lukaszgo1 - missed committing it

**Review by michaelDCurran — APPROVED** [review]

**Comment by hwf1324** [comment]
@seanbudd 

Because setup.py doesn't set the corresponding exclusions, the documentation folder contains redundant files.

Can you set these exclusions at the same time as the git-tracked documentation files are converted to markdown?

**Comment by seanbudd** [comment]
This appears to not be relevant to this PR. Please open a new issue with more information - I'm not sure what you mean by this comment. Please include in the issue what files are causing problems, what the problems are, etc.

**Pull request merged**
