### PR TITLE
WinVersion: add support for Windows 10 October 2020 Update (Version 20H2/2009)

### PR DESCRIPTION
**Pull request by josephsl**
### Link to issue number:
None

### Summary of the issue:
Let's NVDA detect build 19042 as Windows 10 Version 20H2/2009 (October 2020 Update). Note that release Id of 2009 is used for consistency with other Windows 10 version map until the spec is changed.

### Description of how this pull request fixes the issue:
Adds "2009" entry to Windows 10 version map to record build 19042.

### Testing performed:
Tested to make sure Version 20H2 is properly detected (source code copy).

### Known issues with pull request:
None

### Change log entry:
None

### Additionao context:
October 2020 Update is May 2020 Update (Version 2004/build 19041) with an enablement package. Also, at some point in the future, it would be handy to update Windows 10 version map spec to include string keys so versions such as 20H2 and such can be recorded easily.

Thanks.

### CODE REVIEW

**Review by codeofdusk — APPROVED** [review]
Looks good to me!

* Is there a new Windows SDK to merge (like #10922)?
* Maybe `isWin10` could map xxh1 to xx03 and xxh2 to xx09?

**Comment by josephsl** [comment]
Hi, no SDK at the moment, and I expect none as 19042 is 19041 with an enablement package. I think it might not make sense to define “H1” and “H2” as “03” and “09”, respectively because we already have a version that broke that expectation (Version 2004/20H1), along with uncertainty over whether or not Microsoft will opt for one feature update or two next year (next year’s feature update will be a long-term support version, by the way). Thanks.

**Comment by feerrenrut** [comment]
It would be helpful if this (and similar PRs in the future) include a link to an official source to verify this is the appropriate build number.

**Comment by josephsl** [comment]
Hi, for reference (for anyone planning to post similar PR’s in the future), please post a link to WIP release preview channel announcements (a link will be provided below). Thanks.

**Comment by josephsl** [comment]
Hi,

As requested by Reef, official reference for 20H2:

https://blogs.windows.com/windows-insider/2020/09/18/preparing-the-windows-10-october-2020-update-ready-for-release/

Thanks.

**Comment by feerrenrut** [comment]
Thanks for adding the link @josephsl

**Comment by feerrenrut** [comment]
As for:
> it would be handy to update Windows 10 version map spec to include string keys so versions such as 20H2 and such can be recorded easily.

I'd suggest making the keys for `WIN10_VERSIONS_TO_BUILDS` strings and then doing the following:
``` python
def isWin10(version: int = 1507, atLeast: bool = True):
```
``` python
def isWin10(version: Union[int, string] = 1507, atLeast: bool = True):
	if isinstance(version, int):
		version = str(version)
	assert isinstance(version, str)
```

Though this should be done in a subsequent PR.

**Review by feerrenrut — APPROVED** [review]
Thanks @josephsl

**Pull request merged**
