### PR TITLE
An alternative implementation of audio ducking for Windows build 14986 and up: Play silence while we expect to be ducked.

### LINKED ISSUE #6684: win10-14986 nvda next latest build, audio ducking not working
hello.

please test if you also are experiencng this problem, i have only one device for this time and cannot test on other.

audioducking is not working for me.

### PR DESCRIPTION
**Pull request by michaelDCurran**
An alternative to PR #6799

Fixes #6684

### CODE REVIEW

**Comment by michaelDCurran** [comment]
This PR gives us back all we had (initial delay /  delayed fade up, and always duck).
However, there could be questions in regards to battery drain while using 'always duck' as it is constantly playing silence.

**Comment by michaelDCurran** [comment]
Thus #6799 may still be more suitable for 2017.1... I'm not sure.

**Comment by jcsteh** [comment]
This is very nice work. :) However, I'm not sure we want to go down this path.

1. It's going to be difficult to prove whether this has a significant impact on battery life, especially before 2017.1. Given the resources we have, evidence will be anecdotal at best, even if we delay this to a future release.
2. We can say for certain that this will cause continual additional processing and context switching at worst, even if that turns out to be negligible in terms of battery life in the short term. We should be reducing the amount of "idle" processing we do, not increasing it.
3. Given this, I don't think we should give Microsoft an option to "back out" of fixing this properly. It is a regression of functionality users desire, simple as that. If we go with this option, we'll have a much harder time convincing them this should be fixed because we will already have "released" a fix and any hope we might have of getting users to push back at Microsoft will thus be lost.

**Comment by michaelDCurran** [comment]
Closing as this was corrected in Windows build 15048 or there abouts.

**Pull request closed without merging**
