### PR TITLE
Add 2020.3 blurb

### PR DESCRIPTION
**Pull request by feerrenrut**
Janitorial PR.

Add a 2020.3 blurb so that we can release the first 2020.3 beta.

### CODE REVIEW

**Comment by feerrenrut** [comment]
Currently the blurb is a little short, despite there being lots of great changes in this release. Happy to take suggestions for what are the most important elements.

**Comment by josephsl** [comment]
Hi, I think it would be worth it to add something about toggling graphics and highlighted text announcement, nvwave improvements, fixing regressions from recent releases (such as #11384) and such. Thanks.

**Comment by Qchristensen** [comment]
How about:

This release includes several large improvements to stability and performance particularly in Microsoft Office applications.  There are new settings to toggle touchscreen support and graphics reporting.  The existence of marked (highlighted) content can be reported in browsers, and there are new German braille tables.

**Review by Qchristensen — CHANGES_REQUESTED** [review]
Reef, if you could update the description as per our conversation, that would be great.

**Comment by feerrenrut** [comment]
@Qchristensen yep, sounds good. I'll go ahead with your suggestion for now. If any adjustments are necessary, they can be made during the beta phase.

**Pull request merged**
