### PR TITLE
Remove duplicate section heading from change log.

### PR DESCRIPTION
**Pull request by ThomasStivers**
### Link to issue number:
N/A

### Summary of the issue:
There are 2 changes for developers headings for 2018.4.

### Description of how this pull request fixes the issue:
Delete the second heading.

### CODE REVIEW

**Comment by ThomasStivers** [comment]
@josephsl: It is not possible to change the source branch after the PR is created, so here is a replacement PR. I also merged with latest master.

**Review by josephsl — DISMISSED** [review]
Thanks for catching this early.

**Comment by lukaszgo1** [comment]
@ThomasStivers  in the sentence
>IN NVDA's keyboard settings, the checkboxes to enable or disable NVDA modifier keys are now displayed in a list rather than as separate checkboxes.

the n in the first word is capitalized by mistake. Could you fix this one while at it?

**Comment by leonardder** [comment]
Looks like this has already been fixed as part of another pr.

**Pull request closed without merging**
