### PR TITLE
Revisit of speak selection changes in delphi grids and other inaccessible controls

### LINKED ISSUE #7418: Speak selection changes in Delphi grids
Delphi applications tend to use grid controls which don't expose information to MSAA. The only way to reach the grid contents is by means of the display model. When navigating through the particular grids using arrow keys, NVDA doesn't speak any information.

There are two ways this can be fixed, and even though this most of the time happens in Delphi applications, I'd go for generalized approaches (e.g. in NVDAObjects.behaviors).

1. Handle the displayModel_drawFocusRectNotify event on the object. When triggered, create a DisplayModelTextInfo limited to the provided rectangle and speak the text info. Note that this should really only be done on a mix-in class, for some objects, displayModel_drawFocusRectNotify will interfere with IAccessible focus events, for example.
2. Delphi grids change the foreground and background color for the selected grid cell. Move some base functionality of behaviors.LiveText into a new base class behaviors.TextMonitor. Create a new TextSelectionMonitor based on TextMonitor and for every textChange event, speak the text range that is associated with the selectionOffsets.

Although the latter approach might be more far-fetched, it will be of great assistance in applications where no focus events are fired even though parts of the screen are focused that are only accessible by means of the display model. So where the first approach only covers cases for which the displayModel_drawFocusRectNotify event is triggered, the latter will also cover cases where this event isn't triggered even thoug there is a visible selection.

### PR DESCRIPTION
**Pull request by LeonarddeR**
### Link to issue number:
Closes #7418
Improves 8414

### Summary of the issue:
In many legacy applications that have a bad accessibility implementation, we can still make these applications quite accessible using the display model. Even when an application does not fire focus events or doesn't implement accessibility API support, the display model can be used to find out what part of a window is relevant to report. An example of this is a Delphi Grid, where all information in the grid is only accessible by means of the display model, and in which case we can track the focus based on whether the text is considered selected.

### Description of how this pull request fixes the issue:
This pr is based on #8414. It no longer included code from #1040 and #8414. doesn't implement a class to speak changes based on a drawn focus rectangle.

#### Changed behaviors structure
1. The monitoring specific stuff in behaviors.LiveText is now abstracted into behaviors.TextMonitor. LiveText inherrits from TextMonitor. This was also proposed in #9869 
2. Based on this change, there is now a DisplayModelTextMonitor class. DisplayModelLiveText now inherrits from LiveText and DisplayModelTextMonitor

#### New module: selectableText
1. The selection support from editableText.EditableText has been abstracted into selectableText.SelectableText. editableText.EditableText now inherrits from selectableText.SelectableText. The major reason why I did this, is that the fact that selectable text in a container doesn't necessarily mean that the window contains a caret.
2. While most functionality from SelectbaleText is coming from editableText.EditableText, I've made an additional change which allows unselected text not to be spoken. speech.speakSelectionChange  is updated accordingly.

#### New behaviors
1. As behaviors.TextMonitor is now abstract, we can build more types of monitors upon its functionality. the NonEditableSelectableText class combines the TextMonitor with selectableText.SelectableText to automatically announce selection changes when there is a change in the text.
2. Based on this, there is window.DisplayModelNonEditableSelectableText that announces the selection when the display model detects a change in the text.

### User visible changes
* NVDA will now speak selection updates in Delphi grids
* { } A change that we'll have to debate on, NVDA will now add the DisplayModelNonEditableSelectableText overlay class for ContentGenericClient objects when the selection can be detected within these object's windows. This is intended to improve the base line level of accessibility within ContentGenericClient windows.

### Testing performed:
Tested NonEditableSelectableText in several work place specific applications (including delphi grids)

### Known issues with pull request:
Similar to terminal announcement behavior, the Selection based monitor is a bit limited in how it detects new selections and announces them. For example, when you select a list item that is continuously updating its value (e.g. when the selected item contains a counter) the whole item might be repeated when the counter updates.

### Change log entry:
* Changes
    + NVDA will now try to speak selection changes in controls that were previously only accessible by means of the review cursor. (#8414)
    + NVDA will now announce the selection in many grids in Delphi applications. (#7418).

### CODE REVIEW

**Comment by leonardder** [comment]
@engineeringmario: Would you be able to upload an example executable that contains an inaccessible Delphi grid? It should be possible to do so on Github by putting the executable in a zip file.

**Comment by codeofdusk** [comment]
Any updates on this PR?

**Comment by leonardder** [comment]
To me, it's ready, but it's awaiting review.

**Comment by feerrenrut** [comment]
We are waiting on a test sample (see https://github.com/nvaccess/nvda/pull/10058#issuecomment-547870142).  I also suspect it needs to be master merged in, I'm not sure that the changes are limited to only this feature.

**Comment by leonardder** [comment]
> We are waiting on a test sample (see [#10058 (comment)](https://github.com/nvaccess/nvda/pull/10058#issuecomment-547870142)). 

I will ask for one.

> I also suspect it needs to be master merged in, I'm not sure that the changes are limited to only this feature.

I do'nt understand. This pr is filed against master as always?

**Comment by feerrenrut** [comment]
> This pr is filed against master as always?

Master was last merged in Oct 2019. We have reverted some things (like UIA in windows console) since then, so this PR might be trying to re-introduce them. It might be that the changes are as expected and it's my unfamiliarity with this PR that is showing, but there are changes I didn't expect in the current diff.

**Comment by leonardder** [comment]
Ah, in that case, I will do a merge and if that doesn't work, a rebase.

**Comment by feerrenrut** [comment]
@leonardder It might be worth checking the diff first, I'm not very familiar with this PR, and didn't look at it carefully.

**Comment by leonardder** [comment]
Diff looks fine now

**Comment by feerrenrut** [comment]
Marking this as blocked, review pending an example test case.

**Comment by leonardder** [comment]
@EngineeringMario: Another friendly reminder 😎

**Comment by leonardder** [comment]
I'm afraid this pr is getting to be a story without an end. As I no longer have access to software in which I can reliably reproduce the benefits of this pr, there's nothing I can do to bring this closer to a merge.

**Comment by Adriani90** [comment]
cc: @JulienCochuyt maybe you at access solutions have some test cases for this?

**Comment by JulienCochuyt** [comment]
@Adriani90 wrote:
> cc: @JulienCochuyt maybe you at Accessolutions have some test cases for this?

I'll ask @frederic-brugnot if he can come up with one.
The cases that come to my mind right now are lists in SysInternals Process Explorer or SAM Broadcaster, in which we must detect item selection based on colors.
@leonardder would this PR help in that context? (With the addition of a dedicated Monitor, I guess...)

@EngineeringMario, it would really be helpful if you could provide a Delphi grid test case, even privately sent under NDA,

**Comment by leonardder** [comment]
> The cases that come to my mind right now are lists in SysInternals Process Explorer or SAM Broadcaster, in which we must detect item selection based on colors.
> @leonardder would this PR help in that context? (With the addition of a dedicated Monitor, I guess...)

Sure, or at least it should work with very minimal changes, only adding the proper overlay to the object and setting the proper colors, if necessary.

**Comment by leonardder** [comment]
This has been open for over a year now. Despite several attempts to get this of the ground again, the requested test cases haven't been provided yet. I'm closing this to clean up. Happy for anyone to take over or reopen.

**Comment by feerrenrut** [comment]
Now that a [demo program has been published]( https://github.com/BabbageCom/DelphiGridTest), we are ready to commit time to review this and ensure that it is ready to be merged if someone is willing to commit to own the project and work with us in a timely way.

However I'm hesitant to re-open this since @leonardder has moved on from Babbage. Ideally we need someone who is willing to own this project. This PR has been plagued by long gaps in responses (from all parties). For us as reviewers, waiting for more information or changes make the review process very inefficient. We have to re-familiarize ourselves with the change each time we come back to it.

If someone is willing to champion this change, I'd recommend creating a new PR from the branch, and copying information from the description.

**Comment by leonardder** [comment]
I think I might have a use case to pick this up again, certainly the test program makes things a whole lot easier. I also think that a feature flag should be considered for this to make the behavior experimental to start with.

**Pull request closed without merging**
