### PR TITLE
UI Automation in Windows Console: make speaking of passwords configurable

### PR DESCRIPTION
**Pull request by codeofdusk**
### Link to issue number:
Split from #9646 (builds on #9614).

### Summary of the issue:
Currently, in consoles with UI Automation enabled:

* When "speak typed characters" or "speak typed words" is enabled, typed text that is not displayed onscreen (such as passwords) is still reported.

### Description of how this pull request fixes the issue:
When "speak passwords in UIA consoles" is disabled and one of "speak typed characters" or "speak typed words" is enabled, `typedCharacter` events are trapped and queued until a `textChange` event is received. In `winConsoleUIA.event_textChange`, typed characters are removed from the queue and `typedCharacter` events are fired. In `winConsoleUIA.script_clear_isTyping`, this queue is flushed. Since password prompts do not update the screen while the user is typing, no `textChange` events are received, so no `typedCharacter` events are fired and therefore no characters are announced.

### Testing performed:
Tested password entry (by authenticating with `ssh`) on Windows 10 versions 1803 and 1903.

### Known issues with pull request:

* When "speak passwords in UIA consoles" is disabled and one of "speak typed characters" or "speak typed words" is enabled, `typedCharacter` events are only dispatched once `textChange` is received. This may introduce a small performance penalty.

See #9646 for all UIA console known issues to date.
### Change log entry:
None.

### CODE REVIEW

**Comment by codeofdusk** [comment]
CC @feerrenrut, @leonardder, @michaelDCurran.

**Comment by leonardder** [comment]
For reference, may be you could elaborate on why passwords aren't spoken with the legacy implementation, and why this method does not work for UIA console?

**Comment by codeofdusk** [comment]
> For reference, may be you could elaborate on why passwords aren't spoken with the legacy implementation, and why this method does not work for UIA console?

The legacy console support implements "speak typed characters" by looking at the proximity of new text to the caret. If characters appear close to the caret, they are presumed to be typed characters and read out as such. While this prevents typed passwords (or other off-screen characters) from being announced, it leads to #513. The UIA console captures typed characters using `keyboardHandler`, which has no way of knowing whether a character actually caused the screen to update.

**Review by michaelDCurran — APPROVED** [review]

**Comment by michaelDCurran** [comment]
Before merging this, I'd like to know whether you do notice a lag in speak typed characters when speak passwords is off?

**Comment by codeofdusk** [comment]
Not really on my system, but it’s theoretically possible.

Bill

**Comment by michaelDCurran** [comment]
You'll need to merge master into this branch and fix conflicts before I can merge this. Conflicts probably due to the merging of pr #9651

**Review by michaelDCurran — CHANGES_REQUESTED** [review]
In gui/settingsDialogs.py:
You need to change both haveConfigDefaultsBeenRestored and restoreToDefaults methods on the advancedSettingsPanel class to handle your new setting.

**Review by michaelDCurran — APPROVED** [review]

**Pull request merged**
