### PR TITLE
Add a command to check formatting for the text under the caret.

### LINKED ISSUE #9505: Add ability to retrieve formatting for the text under the cared
### Is your feature request related to a problem? Please describe.
I am working all the time with review cursor and object navigation not following the cared mainly to be able to for instance read some instructions with the review cursor in the one window and work at the same time in the other program like sighted people are working by placing two windows side by side. Therefore each actions which require me to move review cursor from its current position  slows me down considerably. One thing which I need to check relatively often is formatting of the text either when working in MS Word, or when composing some CSS. Currently to do this I have to either move my review cursor to my working window and lost my place of reading, or have braille display connected and use command to check formatting for the specific braille cell.
I propose adding script to check formatting under the cared not only for workflows like mine, but also not to make non braille users disadvantaged.
### Describe the solution you'd like
As by default position of the review cursor and the cared is the same for most users pressing NVDA+F would report formatting of the character under the cared. In my opinion it makes sense to make NVDA+F report formatting under the cared and assign script for reporting formatting under the review cursor to the NVDA+Shift+F.
### Describe alternatives you've considered
We can leave current assignment as is and create new script for reporting formatting under the cared unassigned.
### Additional context
In most screen readers retrieving formatting under the cared is possible, and ad least for me it would be very beneficial.
I can work on this it don't seems to be hard in terms of coding, however it would be nice to have confirmation from @michaelDCurran or @feerrenrut that the feature would be approved and which of the two above solutions would you prefer.

### PR DESCRIPTION
**Pull request by lukaszgo1**
### Link to issue number:
Closes #9505 
First step towards #7314
### Summary of the issue:
It is not possible to check formatting for the text under the caret without moving review cursor to its position. This is problematic for people working with review cursor not following caret. In addition this can be done with a braille display, so it should also be possible for speech only users.
### Description of how this pull request fixes the issue:
I've created a separate script assigned to NVDA+f to check formatting at the caret position. The current command for checking it at the review cursor has been reassigned to NVDA+shift+f because for most users checking formatting happens  more often at the caret not at the review cursor. As by default review follows caret there is no functional difference for people who haven't changed this.
While at it I've also split up these scripts into a separate ones as per #7314 - they are obviously not assigned.
### Testing performed:
1. Tested that formatting can still be checked and displayed in browse mode with NVDA+shift+f at the review position,
2. Tested that with the new script formatting at caret is properly announced/displayed in browse mode.
3.  Assigned a keyboard command to each of the separate scripts and confirmed that they are functioning as expected.
4. Compiled user guide - made sure that the changes to the keyboard commands are displayed as they should be.
### Known issues with pull request:
- I haven't documented the new separate scripts - I don't think this should be done at this early stage.  When #7314 would be fully implemented we should add a general note to one of the UG sections though.
### Change log entry:

New features:
It is now possible to check formatting at the caret with NVDA+f
Changes:
Command used to check formatting at review position has been reassigned to NVDA+shift+f

### CODE REVIEW

**Comment by michaelDCurran** [comment]
I personally agree with the change here. But:
@Qchristensen  what do you think the impact to our Basic Training module is for this pr?
Does it specifically talk about the fact that NVDA+f actually uses the review cursor rather than the caret?

**Comment by Qchristensen** [comment]
Thanks for the heads up here - yes I agree with the change and the reasoning.  It will necessitate an update to Basic Training, as you mention @michaelDCurran the module does note that the command reports formatting at the review cursor rather than text caret.

I'm happy to update the module before this change makes it to a stable release.  I'll also need to check the NVDA Certified Expert Exam questions as it is in there too.

**Comment by Adriani90** [comment]
This will probably need to be adjusted accordingly also in the user guide. I can have alook and do it unless @lukaszgo1 has time to do it.

**Comment by lukaszgo1** [comment]
@Adriani90 I've updated User guide as part of this PR. Could you please take a look and tell me if it's sufficient in your opinion?

**Comment by Adriani90** [comment]
@lukaszgo1 it looks good. One question though, the command for reporting text under the braille cell, which formatting is there applied? On review, on carret, or does it deppend on to which cursor the braille display is tethered?
According to user guide there is only one command for reporting formatting. I think it makes sense to implement also an emulated command for the braille displays for formating at system carret.
cc: @leonardder, @bramd

**Comment by lukaszgo1** [comment]
@adri wrote:

> 
> @lukaszgo1 it looks good. One question though, the command for reporting text formatting under the braille cell, which formatting is there applied? On review, on carret, or does it deppend on to which cursor the braille display is tethered?

It depends on the location of braille cursor.

> According to user guide there is only one command for reporting formatting under the braille cell. I think it makes sense to implement also an emulated command for the braille displays for formating at system carret.


I don't think so. You can check formatting at the position of the braille cursor with the current gesture from a braille display, and if someone wants to check formatting for the different cursor one of the gestures added in this PR could be assigned to a key combination on a braille display from the input gestures dialog already.

**Review by Qchristensen — APPROVED** [review]
Only commenting on the user guide text, which looks fine, well done.

**Review by michaelDCurran — APPROVED** [review]

**Pull request merged**
