### PR TITLE
Update CLDR to version 38.1

### PR DESCRIPTION
**Pull request by OzancanKaratas**
Please merge the beta branch.
@leonardder @feerrenrut

### CODE REVIEW

**Comment by OzancanKaratas** [comment]
Sorry for forgetting some changes. Please don't close this. We can merge it using patch.

**Comment by leonardder** [comment]
We're not going for beta with CLDR 38.1. It will have to be 2021.1 instead.

**Comment by josephsl** [comment]
Hi, in addition, one important consideration: although things are not done with beta, we have to focus on stability. Although CLDR 38.1 may introduce new emoji characters, we have to give it a chance to be tested by testers, and beta is not a good branch at this time. This is more so now that 2020.4 beta 1 was just declared, which to me means stability takes priority (personally, I’m against applying dependency updates to beta branch when a beta cycle is active unless the dependency fixes an issue introduced in a beta release). Therefore, I’m in agreement with Leonard, and move to target 2021.1. Thanks.

**Comment by OzancanKaratas** [comment]
Ok, now it's ready for review. Thanks for the branch change @leonardder.

**Review by michaelDCurran — APPROVED** [review]

**Pull request merged**
