### PR TITLE
Exclude git tracked files when running scons -c

### LINKED ISSUE #7070: source/comInterfaces contains some files which should be ignored
When working with current master, scons -c removes files below:

```
On branch master
Your branch is up-to-date with 'origin/master'.
Changes not staged for commit:
  (use "git add/rm <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

        deleted:    source/comInterfaces/UIAutomationClient.py
        deleted:    source/comInterfaces/_944DE083_8FB8_45CF_BCB7_C477ACB2F897_0_1_0.py
```

Usually such files should be ignored by .gitignore.

### LINKED ISSUE #10833: Unable to run NVDA alpha
### Steps to reproduce:

Build and run NVDA alpha.

### Actual behavior:

Critical error. Here is the log:

<details> <summary>Log</summary>
INFO - __main__ (18:18:04.681) - MainThread (4004):
Starting NVDA version source-master-1e139d4
INFO - core.main (18:18:04.919) - MainThread (4004):
Config dir: D:\Cyrille\Dev\GIT\nvdaNew\source\userConfig
INFO - config.ConfigManager._loadConfig (18:18:04.919) - MainThread (4004):
Loading config: .\userConfig\nvda.ini
INFO - core.main (18:18:05.036) - MainThread (4004):
Using Windows version 10.0.18362 workstation
INFO - core.main (18:18:05.036) - MainThread (4004):
Using Python version 3.7.5 (tags/v3.7.5:5c02a39a0b, Oct 14 2019, 23:09:19) [MSC v.1916 32 bit (Intel)]
INFO - core.main (18:18:05.036) - MainThread (4004):
Using comtypes version 1.1.7
INFO - core.main (18:18:05.036) - MainThread (4004):
Using configobj version 5.1.0 with validate version 1.0.1
CRITICAL - __main__ (18:18:05.451) - MainThread (4004):
core failure
Traceback (most recent call last):
  File "source\nvda.pyw", line 215, in <module>
  File "core.py", line 256, in main
    import appModuleHandler
  File "appModuleHandler.py", line 27, in <module>
    import NVDAHelper
  File "NVDAHelper.py", line 19, in <module>
    import eventHandler
  File "eventHandler.py", line 9, in <module>
    import api
  File "api.py", line 19, in <module>
    import NVDAObjects.IAccessible
  File "NVDAObjects\IAccessible\__init__.py", line 22, in <module>
    import IAccessibleHandler
  File "IAccessibleHandler.py", line 18, in <module>
    import UIAHandler
  File "UIAHandler.py", line 11, in <module>
    from _UIAHandler import *  # noqa: F403
  File "_UIAHandler.py", line 29, in <module>
    from comtypes.gen import UIAutomationClient as UIA
ImportError: cannot import name 'UIAutomationClient' from 'comtypes.gen' (D:\Cyrille\Dev\GIT\nvdaNew\include\comtypes\comtypes\gen\__init__.py)

</details>

### Expected behavior:

NVDA running.

#### NVDA installed/portable/running from source:
Source

#### NVDA version:

Alpha (commit 1e139d4dad6e44cced4250365a6e75a1ac332c4b)

#### Windows version:

Win 10 1903

#### Name and version of other software in use when reproducing the issue:

Visual Studio 2019.

#### Does the issue still occur after restarting your PC?
Yes

#### Have you tried any other versions of NVDA? If so, please report their behaviors.
Running other versions from source is also failing. I did not succeed in running from source since I have built with VS2019.

### PR DESCRIPTION
**Pull request by hwf1324**
### Link to issue number:

Fixes #7070
Fixes #10833

### Summary of the issue:

The `Clean` function of `comInterfaces_sconscript` cleans up the files tracked by git

### Description of user facing changes

None

### Description of development approach

Add exclusion items in the cleanup matching function in `comInterfaces_sconscript`

### Testing strategy:

1. Run `scons source`
2. Run `scons -c`
3. Run `git status`
4. Run `scons source`
5. Run `git status`
6. Run `runnvda`

Check if the tracked files in git have been deleted after observation and cleaning

### Known issues with pull request:

When the tracked files in git change, the exclusion parameters need to be modified synchronously

### Code Review Checklist:

- [x] Documentation:
  - Change log entry
  - User Documentation
  - Developer / Technical Documentation
  - Context sensitive help for GUI changes
- [x] Testing:
  - Unit tests
  - System (end to end) tests
  - Manual testing
- [x] UX of all users considered:
  - Speech 
  - Braille
  - Low Vision
  - Different web browsers
  - Localization in other languages / culture than English
- [x] API is compatible with existing add-ons.
- [x] Security precautions taken.

### CODE REVIEW

**Comment by CyrilleB79** [comment]
Does it also fix #10833?
If not, is there a simple way to have this also fixed in this PR?

**Comment by hwf1324** [comment]
> Does it also fix #10833?
> If not, is there a simple way to have this also fixed in this PR?
> 

I think so, looks like #10833 is the same as #15865

**Comment by CyrilleB79** [comment]
> > Does it also fix #10833?
> > If not, is there a simple way to have this also fixed in this PR?
> 
> I think so, looks like #10833 is the same as #15865

Cool!

§Could you add a more precise test process?
1. Build NVDA
2. scons -c
3. Build NVDA again
4. Run NVDA

Thanks
Also, could you add a change log item in the "Change for developers" section? Or in the bugfix one?

**Comment by seanbudd** [comment]
Also please link all fixed issues in the issue description

e.g.
Fixes # 123
Fixes # 256

**Review by seanbudd — APPROVED** [review]

**Pull request merged**
