### PR TITLE
Multiple dictionary dialogs can now be opened simultaneously if the dictionaries are of different types

### PR DESCRIPTION
**Pull request by CyrilleB79**
Opened against beta branch since it is a follow-up of #12800.
Cc @seanbudd 

### Link to issue number:

Fix-up of #12800.
Described in https://github.com/nvaccess/nvda/pull/12800#issuecomment-911676751, paragraph "Test almost successful", "Test 2".

### Summary of the issue:

Since the merge of #12800, trying to re-open an already opened dialog allows to focus it rather than issuing an error as done previously. However, in the case of dictionaries, if you try to open the voice dictionary while the default is already open will lead to focus the default dictionary rather than opening the voice dictionary dialog;

### Description of how this pull request fixes the issue:

Since the check of an existing opened dialog is made on the class of the dialog, I have sub-classed `DictionaryDialog` for the three types of dictionaries to make them distinct one from another.

### Testing strategy:

Test 1:
* Tried to open the 3 dictionary dialogs simultaneously, either with the menu or with keyboard shortcut.

Test 2:
* Open the three dictionaries windows
* Updated them all (at least adding one entry for each)
* Close them all
* Re-open them all one by one to check that the content has been correctly updated.

### Known issues with pull request:

Maybe it would be interesting to forbid to instance an object of class `DictionaryDialog` directly, i.e. force subclassing.
I do not know however how it can be acheived and do not even know if it is pythonic.
Comments are welcome.

### Change log entries:
Not needed if merged along with #12800 in 2021.3.

### Code Review Checklist:

- [x] Pull Request description:
  - description is up to date
  - change log entries
- [x] Testing:
  - Unit tests
  - System (end to end) tests
  - Manual testing
- [x] API is compatible with existing add-ons.
- [x] Documentation:
  - User Documentation
  - Developer / Technical Documentation
  - Context sensitive help for GUI changes
- [x] UX of all users considered:
  - Speech 
  - Braille
  - Low Vision
  - Different web browsers
  - Localization in other languages / culture than English

### CODE REVIEW

**Comment by seanbudd** [comment]
Have you tested updating and saving a dialog, with multiple dialogs open, and then reopening the dialog to confirm the changes were saved?

>Maybe it would be interesting to forbid to instance an object of class DictionaryDialog directly, i.e. force subclassing.
I do not know however how it can be acheived and do not even know if it is pythonic.

This can be done by using the [Abstract Base Class](https://www.python.org/dev/peps/pep-3119/) pattern ([other docs](https://docs.python.org/3/library/abc.html#module-abc)).

**Comment by lukaszgo1** [comment]
> Maybe it would be interesting to forbid to instance an object of class `DictionaryDialog` directly, i.e. force subclassing. I do not know however how it can be acheived and do not even know if it is pythonic. Comments are welcome.


Assuming this is going to be merged in 2021.3 we cannot do that, as there are some add-ons (I know about Application dictionary but there are probably others) which would be broken as a result of this change.

**Comment by seanbudd** [comment]
>Then, for 2022.1 we could make another PR to make DictionaryDialog abstract.
Do you agree with this way to do?

I agree, this is probably the best approach. Making sure that `DictionaryDialog` is properly abstracted might be a complicated process as well, and this has the potential to be merged before the first beta as is.

**Review by seanbudd — APPROVED** [review]
Thanks @CyrilleB79, I've confirmed your manual testing.
@feerrenrut - can this be included in 2021.3 beta1 ?

**Review by feerrenrut — APPROVED** [review]

**Pull request merged**
