### PR TITLE
Braille Viewer: Add a close button on the title bar for use with pointing devices

### PR DESCRIPTION
**Pull request by JulienCochuyt**
### Link to issue number:

As argued IMHO with reason by @bhavyashah in https://github.com/nvaccess/nvda/issues/10791#issuecomment-646978487
This PR does **not** address #10791 which targets Speech Viewer.

### Summary of the issue:

The Braille Viewer currently presents no close control on its GUI.
It can only be closed with `alt+F4` or by means of the dedicated NVDA Tools menu entry.

### Description of how this pull request fixes the issue:

Add a standard close button on the title bar of the Braille Viewer dialog.

### Testing strategy:

Ensured the dedicated check-able NVDA Tools menu entry gets unchecked as it properly does when closing the dialog with `alt+F4`.
Ensured proper behavior is maintained during restarts with or without "show at start-up" being checked.

### Change log entries:

Changes
The Braille Viewer now has a standard close button for easier interaction with users of pointing devices. The other ways of interacting with this dialog remain otherwise unchanged.

### Code Review Checklist:

- [x] Pull Request description is up to date.
- [x] Unit tests.
- [x] System (end to end) tests.
- [x] Manual tests.
- [x] User Documentation.
- [x] Change log entry.
- [x] Context sensitive help for GUI changes.

### CODE REVIEW

**Comment by XLTechie** [comment]
> This change IMHO does not deserve a change log entry.

I (mildly) disagree. Someone who has previously been frustrated by its absence, 
may like to learn that now it's there.

**Comment by JulienCochuyt** [comment]
@XLTechie, @alexarnaud,
Thanks for your feedback.
Please find a proposed change log entry in the updated description.
Glad you find this functionality useful.

**Comment by XLTechie** [comment]
Can it also be reached by keyboard nav (either standard or braille)?
If so, I would suggest the following for changes:

```
The Braille Viewer now includes a visible close button for added convenience.
```

**Comment by JulienCochuyt** [comment]
@XLTechie wrote:
> Can it also be reached by keyboard nav (either standard or braille)?

Only through object navigation. It is a standard dialog close button positioned at the right of the title bar and has no special UX whatsoever. It's sole intent is to be activated using a pointing device such as mouse or touch screen.

Still, feel of course really free to propose a better wording of the change log entry than the one I quickly wrote.
I'm not a native English speaker.

**Review by seanbudd — APPROVED** [review]
LGTM, thanks @JulienCochuyt!

**Pull request merged**
