### PR TITLE
Fix-up of #13366: Replace dots with underscores before trying to check if the given App Module exists to work around bug in the Python import system

### LINKED ISSUE #13813: Regression: Attempt to import wrong appModule
### Steps to reproduce:
1. Enable loading custom code from Developer Scratchpad directory;
2.Try to create a new empty file qq.py in scratchpad/appModules;
3. Now feel free to start an application named '6.5.qq.exe' with a GUI;

### Actual behavior:
You get a bunch of errors and NVDA can't report anything in the application;
Error log attached: [NVDA.log](https://github.com/nvaccess/nvda/files/8933578/NVDA.log)

### Expected behavior:
NVDA can read the application normally, consistent with the 2022.1 behavior.
#### NVDA installed/portable/running from source:
installed
#### NVDA version:
2022.2Beta1
#### Windows version:
Windows 10 21H2 (x64) build 19044.1766
#### Name and version of other software in use when reproducing the issue:
None
#### Other information about your system:
None
#### Does the issue still occur after restarting your computer?
Yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
2022.1 can work well
#### If NVDA add-ons are disabled, is your problem still occurring?
No(but this has nothing to do with any of the add-ons)
#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
Yes

### PR DESCRIPTION
**Pull request by lukaszgo1**
Opened against beta since this fixes regression introduced during 2022.2 development cycle.
### Link to issue number:
Fix-up of #13366
Fixes #13813
### Summary of the issue:
As part of PR #13366 I've modified the code responsible for retrieving application name from process id so that it no longer tries to import an App Module for a hosting process if it does not exist. Unfortunately Python `find_Module` method seems to have a bug - it returns a module when the provided string contains dots and the file named exactly like the last segment of the provided name exists in the package. For example if you have module named `qq` in the package, and you would like to check if the module named `6.5.qq` exists `True` is returned even though there is no such module. I haven't yet tested how this behaves with more recent versions of Python nor opened an issue against them.

### Description of user facing changes
NVDA no longer fails to work in applications containing dots in their file names in cases where you have an App Module for an application named exactly like the last segment of the application name.
### Description of development approach
Dots are normalized to underscores before checking if the given module exists. While we did this already before trying to import a standard App Module this has not been done before trying to get module for a hosting process.
### Testing strategy:
- Performed steps from #13813 
- Tested that an App Module for AZARDI (it binary file contains dot in the file name) is loaded successfully
- Tested that the correct name is retrieved for a Java application from its hosting process
### Known issues with pull request:
None known
### Change log entries:
None needed - unreleased regression.
### Code Review Checklist:

- [X] Pull Request description:
  - description is up to date
  - change log entries
- [X] Testing:
  - Unit tests
  - System (end to end) tests
  - Manual testing
- [X] API is compatible with existing add-ons.
- [X] Documentation:
  - User Documentation
  - Developer / Technical Documentation
  - Context sensitive help for GUI changes
- [X] UX of all users considered:
  - Speech 
  - Braille
  - Low Vision
  - Different web browsers
  - Localization in other languages / culture than English

### CODE REVIEW

**Comment by cary-rowen** [comment]
I seem to have discovered a new error introduced by this PR: After running Windows Power Shell with administrator privileges, I get an error, NVDA cannot read the content in Power Shell.
Here is the log:
[NVDA.log](https://github.com/nvaccess/nvda/files/8935903/NVDA.log)

**Comment by lukaszgo1** [comment]
This is not caused by this PR. Non signed versions of NVDA cannot access applications running as administrator.

**Comment by cary-rowen** [comment]
sorry i overlooked this, I will collapse the above comment.

**Comment by seanbudd** [comment]
@lukaszgo1 

From reading [Python importlib docs](https://docs.python.org/3/library/importlib.html) `find_module` is deprecated, and we should use `find_spec` instead. As the function is deprecated, I don't think reporting the bug to python is a good use of time.

Can you test using `find_spec` instead of `find_module` and see if this is still an issue?

I would test this but I am struggling to understand the Python bug described in the issue a summary. A minimal python sample would be helpful here.

**Comment by seanbudd** [comment]
@lukaszgo1 I'm looking into using `find_spec` with the STR in https://github.com/nvaccess/nvda/issues/13813

**Comment by seanbudd** [comment]
It appears that `find_spec` has the same bug

**Review by seanbudd — APPROVED** [review]

**Comment by seanbudd** [comment]
Note the documentation from `iter_importers`, which is what we are using as the base for `find_module`:

> Yield finders for the given module name
> 
> If fullname contains a '.', the finders will be for the package
> containing fullname, otherwise they will be all registered top level
> finders (i.e. those on both sys.meta_path and sys.path_hooks).
> 
> If the named module is in a package, that package is imported as a side
> effect of invoking this function.
>
>If no module name is specified, all top level finders are produced.

**Pull request merged**
