### PR TITLE
reduce braille.BrailleHandler.update redundant executions

### LINKED ISSUE #16456: Redundant braille.BrailleHandler.update executions
### About
There are following code lines in `braille.BrailleHandler._handlePendingUpdate`:

`
			if scrollTo is not None:
			self.scrollToCursorOrSelection(scrollTo)
			if self.buffer is self.mainBuffer:
				self.update()
`

`scrollToCursorOrSelection` should execute `scrollTo` when region is type of TextInfoRegion. `scrollTo` in turn executes `updateDisplay` which executes `braille.BrailleHandler.update`.

Because region is type of TextInfoRegion and thus buffer should be mainBuffer, `braille.BrailleHandler.update` is executed twice.

There is similar case in `braille.BrailleHandler._doNewObject` function:

`
		self.scrollToCursorOrSelection(region)
		if self.buffer is self.mainBuffer:
			self.update()
`

What is the harm? At least log file, when using debug level, contain redundant ""Braille window dots" lines.
### Steps to reproduce:
Log level to debug and investigation of log when there is braille display in use (I have not looked at log when braille display is no display).
### Actual behavior:

redundant log lines
### Expected behavior:

no redundant log lines
#### NVDA installed/portable/running from source:
running from source
#### NVDA version:
current main branch code
#### Windows version:
windows 10 22h2
#### Does the issue still occur after restarting your computer?
yes

### PR DESCRIPTION
**Pull request by burmancomp**
### Link to issue number:
closes #16456
### Summary of the issue:
There are often two `BrailleHandler.update` executions which produce duplicate log entries when log level is debug. As an example, when navigating with up/down arrows in notepad debug level log shows this.

There should not be good reason for two executions.
### Description of user facing changes
Less duplicate "Braille window dots" log lines on debug level. This should facilitate debugging a little.
### Description of development approach
removed `updateDisplay` call from `BrailleBuffer.scrollTo`
### Testing strategy:
daily use
### Known issues with pull request:
no clear evidence
### Code Review Checklist:

- [x] Documentation:
  - Change log entry
  - User Documentation
  - Developer / Technical Documentation
  - Context sensitive help for GUI changes
- [x] Testing:
  - Unit tests
  - System (end to end) tests
  - Manual testing
- [x] UX of all users considered:
  - Speech 
  - Braille
  - Low Vision
  - Different web browsers
  - Localization in other languages / culture than English
- [x] API is compatible with existing add-ons.
- [x] Security precautions taken.

## Summary by CodeRabbit

- **Bug Fixes**
  - Improved performance of Braille display scrolling by removing redundant display updates.

### CODE REVIEW

**Comment by LeonarddeR** [comment]
I think your assumption is correct this time.
Can I trigger this?
@coderabbitai review

**Review by LeonarddeR — APPROVED** [review]
1. `updateDisplay` updates the braille handler, so `scrollTo` no longer does this.
2. The only place where `scrollTo` is called on the buffer from within the braille module itself, is in `BrailleHandler.scrollToCursorOrSelection`
3. All functions that call `scrollToCursorOrSelection` explicitly update the braille handler after the `scrollToCursorOrSelection` call.
4. There are two cases where `globalCommands` call `scrollTo`, both in `script_braille_toFocus`. That script explicitly calls `updateDisplay` on the buffer as well.

**Comment by burmancomp** [comment]
> I think your assumption is correct this time.
Thanks @LeonarddeR

**Comment by seanbudd** [comment]
@burmancomp - the testing strategy section doesn't describe a testing strategy, rather a summary of the issue.
Please describe how you tested this PR.
I'd also encourage you to seek wider testing from other braille users using the build artifact.

**Comment by burmancomp** [comment]
@irrah68 and @jykke67 could you test if you have any braille related problem with this pr which are not present with other versions:

[https://ci.appveyor.com/api/buildjobs/3bjm7mgqed6q41bg/artifacts/output%2Fnvda_snapshot_pr16550-31927%2Cd1f186a7.exe](https://ci.appveyor.com/api/buildjobs/3bjm7mgqed6q41bg/artifacts/output%2Fnvda_snapshot_pr16550-31927%2Cd1f186a7.exe)

**Comment by Jykke67** [comment]
I’ve recently updated NVDA to this version, and no problems in basic usage have appeared so far.

Just to mention, in case this has any inpact, my braille display is Braille Star 80.

In order to get more evidence I probably have to test this in various situations and during a longer period of time.

**Comment by irrah68** [comment]
I tested this pr with my Braillex EL 80c display. Perhaps there is one thing that feels a little bit strange to me, but on the other hand, I don't know if this feature is meant to work this way.

In gestures.ini I have: braille_toFocus = br(papenmeier):upperrouting

When I set Braille messages to show indefinitely, press NVDA + t and read the message, then press a upper routing key, I hear the content of the line where the cursor is at the moment but the display keeps on showing the message which I got after pressing nvda +t. When or if I press a routing key of the first touch cursor line, the Display starts showing the current cursor location normally.

Otherwise I didn't notice strange behaviour and everything seemed to work normally.

**Comment by burmancomp** [comment]
As far as I understand behavior is as @irrah68 describes it. I tried it with current main branch code so this pr has not changed that.

I noticed something interesting when running from main branch source. In albatross gestures there is gestures to go to desktop, to open "this computer", to go to windows settings, and to go to notification area (I mean same as pressing windows+b). When "show messages" was "show indefinitely" those gestures worked but they did not dismissed braille message. But when pressed directly from keyboard they dismissed braille message. But this is separate issue.

**Comment by Jykke67** [comment]
Quite interesting. I have to admit that I have never been that good in replacing standard Windows gestures like Win+B with braille display specific ones even though I am a everyday user of a braille display.

I have tried to keep the standard Windows gestures in mind in case that no braille display is always available.

Of course I do use the tc buttons of the braille display in order to perform klicks, button pressings etc.

**Comment by burmancomp** [comment]
I was somewhat (am maybe less) concerned about freeze related log entries. With this pr there at least seemed to be more than with main branch code. But I do not know why. Only difference between this pr and main branch code is that line containing `updateDisplay` in `scrollTo` is removed.

I am testing by running from source. Then (some time ago) I realized that when switching between branches I have not run scons source. If I run it some building is done. So is this explanation for more log entries?

Can you @irrah68 and @Jykke67 do some testing by comparing build of this pr to some development snapshot with debug logging to see if this pr has more freeze related log entries.

I have used windows search box by activating it with windows key then typed "wordpad", and then pressed escape, and repeated same steps.

I noticed quite sure way to get freeze (from which nvda recovered). When nvda is started:

- open search box
- type "wordpad" and press enter
- close wordpad window
- goto search box and
- start type wordpad.

Can you also test if you can reproduce this? It should be case with both versions - with one cycle it likely did not occured with main branch code.

I have windows 10 and you likely have windows 11 so results may differ.

**Comment by seanbudd** [comment]
@burmancomp - I would encourage testing with AppVeyor builds just to more closely mimic release code. This isn't always necessary but if you're smoke testing a build over time it's a better approach.
At the very least you should be creating launchers locally with `scons launcher`

**Comment by burmancomp** [comment]
What are recommended use cases for "running from source"?

**Comment by Jykke67** [comment]
I made a quick test as requested and no freezing occured, so there may be differences.

I have Win 11 updated from Win 10 by ignoring Microsoft’s hardware requirements, if that matters.

**Comment by seanbudd** [comment]
@burmancomp - there shouldn't be a difference for most situations that don't require an installed build, (e.g. portable copy is fine). I would say with targeted testing it should be fine. I would just encourage launcher builds when smoke testing, i.e. running a build over a long period of time to check for any regressions against an official build. Generally good smoke testing would involve situations that require an installed build, sometimes a signed build is needed too. If certain components have changed you may need to clean your build with `scons -c` or sometimes a full git clean is required.

**Comment by irrah68** [comment]
I tested this pr with --debug-logging and didn't notice any freezes. There were some error sounds and the log file contains error messages, but this has happened wit other NVDA test versions as well.

**Comment by Jykke67** [comment]
Yes. The error sound is typical for test versions of NVDA, but with logging level disabled one can get rid of it.

It took me a while to find this out, and before it I switched between test and stable versions, which was unnecessary.

BTW, the test version was updated to alpha-31971,c5954630, and audio ducking started to work again like in beta and rc versions before. Better to continue using alpha or return to 2024.2beta1 for stability purposes?

**Pull request merged**
