### PR TITLE
Update eSpeak-ng to latest master (commit 919f3240cbb).

### PR DESCRIPTION
**Pull request by michaelDCurran**
### Link to issue number:
None.

### Summary of the issue:
NVDA 2018.3 contained a copy of espeak-ng with several regressions for Russian and Portuguese.
These regressions have been addressed in later eSpeak-ng commits but are not yet in NVDA.

### Description of how this pull request fixes the issue:
Update eSpeak-ng to commit 919f3240cbb 

### Testing performed:
Ran NVDA in English using this eSpeak commit. 
Try builds have been provided to both Russian and Portuguese users.
* Portuguese have reported the issues are solved.

 ### Known issues with pull request:
None.

### Change log entry:
Changes:
* eSpeak-ng has been updated to commit 348e7ecbd6274.

### CODE REVIEW

**Comment by zstanecic** [comment]
Hi mick,

There is yet another fix which fixes the pt-br pronounciation.

Please update to the very latest espeak master

**Comment by Brian1Gaff** [comment]
Just an idea, but rather than create a limited access version, why not use 
the current release branch and create a beta snap on the web site containing 
it so many more can test in case there are some other issues in other 
languages in Espeak latest build?
Brian

bglists@blueyonder.co.uk
Sent via blueyonder.
Please address personal E-mail to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.
-----

**Comment by Brian1Gaff** [comment]
Is that the Portuguese issue one?
 Brian

bglists@blueyonder.co.uk 
Sent via blueyonder. 
Please address personal E-mail to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.
-----

**Review by feerrenrut — APPROVED** [review]
Did you notice https://github.com/nvaccess/nvda/pull/8827#issuecomment-427745904.

It suggests that there were later fixes to pt-br.

**Pull request merged**
