### PR TITLE
Properly convert strings to booleans when upgrading profiles to the new schema

### PR DESCRIPTION
**Pull request by lukaszgo1**
Opened against branch for 2022.4 since this fixes regression which ideally should not get into the release.

### Link to issue number:
None, fix-up of #14132
### Summary of the issue:
When upgrading configurations to the new versions of the schema we often need to check what value was set previously as not to change user preferences. In our profile upgrade steps we relied on the fact that false values in the config are falthy in the boolean context, but at the state where profile is upgraded these are not yet transformed into right types, so a value set to `False` is set to literal string `"False"` which is always truthy in a boolean context.
I've discovered this when, after #14132 got merged, in the profile where I had reporting of row and column headers disabled it got re-enabled after the schema update.

### Description of user facing changes
People who have reporting of row and column header disabled would still have them disabled after updating to NVDA 2022.4.

### Description of development approach
In places where we check if the option is set to `True` in our profile upgrade steps I used the default `configobj` converter between string and booleans to convert options into the right values. In addition I've removed some unnecessary `pass` statements and some variables capturing exceptions which weren't used.
While fixing previous upgrade steps would not help people who are upgrading  NVDA regularly it still made sense to do so, to support people who skipped several upgrades and to have consistent style for the upgrade steps.
### Testing strategy:
With a config profile using previous version of the schema and with reporting of row and column headers disabled upgraded into the latest schema - made sure reporting of row and column headers remained disabled.

### Known issues with pull request:
People on Alpha who had reporting of rows and column disabled still have to set the  configuration manually - there is no way to fix this automatically.
### Change log entries:
None needed - unreleased regression.
### Code Review Checklist:

- [X] Pull Request description:
  - description is up to date
  - change log entries
- [X] Testing:
  - Unit tests
  - System (end to end) tests
  - Manual testing
- [X] API is compatible with existing add-ons.
- [X] Documentation:
  - User Documentation
  - Developer / Technical Documentation
  - Context sensitive help for GUI changes
- [X] UX of all users considered:
  - Speech 
  - Braille
  - Low Vision
  - Different web browsers
  - Localization in other languages / culture than English
- [X] Security precautions taken.

### CODE REVIEW

**Comment by lukaszgo1** [comment]
cc @seanbudd  @feerrenrut

@CyrilleB79  You may also want to review this.

**Comment by CyrilleB79** [comment]
Good catch @lukaszgo1, many thanks!
That's a case where type hints would have been very useful!

**Review by seanbudd — APPROVED** [review]

**Comment by seanbudd** [comment]
@lukaszgo1 - can you open temp

**Comment by seanbudd** [comment]
I've changed the base to master temporarily to run the build system and tests on AppVeyor.

This needs to retarget `branchFor2022.4` after these succeed.

**Comment by feerrenrut** [comment]
Is it possible that this fixes the cause of:
- #8720

**Comment by seanbudd** [comment]
I think that's really unlikely, #8720 is thought to be caused by an issue with fetching/setting the registry.

It would also be difficult to confirm if this fixes the issue, as #8720 cannot be consistently reproduced

**Pull request merged**
