### PR TITLE
Several spelling and grammar corrections to a few source files

### PR DESCRIPTION
**Pull request by XLTechie**
### Link to issue number:

None

### Summary of the issue:

While *using the source* recently, I came across several comments and docstrings that had spelling and grammar errors.
There are many others, but I wanted to keep this PR small, in case I managed to mess it up in some way.

### Description of how this pull request fixes the issue:

Corrections/changes made:

+ scriptHandler.py: "sript" => "script"
+ addonHandler/addonVersionCheck.py:
    * Amended comment "version high enough to meets the addon's minimum requirements": "meets" to "meet", and "addon's" to "add-on's".
+ addonHandler/__init__.py:
    * Capitalization (1), hyphenate "addon" to "add-on" in docstrings and comments (~5)
    * "informatinon" => "information".
    * getTranslationsInstance(): "tranlation" => "translation" in docstring.
    * getTranslationsInstance(): properly closed the angled brackets around the variable part of the path name in the docstring.
    * getTranslationsInstance(): escaped the backslash in the docstring so it linted correctly.
    * _getDefaultAddonPaths(): added missing closing angled bracket around "<userConfig" in docstring.
    * getCodeAddon(): "howmany" => "how many" in docstring.
    * initTranslation(): "shall we retrieve" => "should we retrieve" in comment.
    * "Eg" => "EG" in apiVersion comment.
    * createAddonBundleFromPath(): Comment "...bundle at the same level of the add-on's top directory" to "...bundle at the same level as the add-on's top-level directory".
+ inputCore.py:
    * class InputGesture: "floodding" => "flooding" in a comment.
    * registerGestureSource(): "parenthesised" => "parenthesized" in the docstring.

### Testing performed:

Linting caused me to have to escape a backslash on line 452 of `addonHandler/__init__.py`.
Reviewed the docstring for `addonHandler.Addon.getTranslationsInstance` in the Python console, and verified that the docstring still appears the same.

### Known issues with pull request:

None.

### Change log entry:

None needed.

### CODE REVIEW

**Comment by feerrenrut** [comment]
Note this appears to be changing the file permissions for the edited files. Adding the executable bit, eg 0644 -> 0755. I don't think we have any guideline on what they SHOULD be, but most other python files are 0644.

**Comment by XLTechie** [comment]
I can probably fix that. Although i note that some other files I didn't touch, 
such as XMLFormatting.py, winInputHook.py, wincon.py, and others, are showing 
here as 755. No idea why, but I'm pretty sure my setup isn't causing that.

**Comment by XLTechie** [comment]
I believe I know why this happened to some (but not all) of the files.
I did the lint fixes in notepad++ on Windows, accessing a Linux shared 
filesystem.
The others I edited directly on Linux.
The Windows edited files got the execution bit.  Will monitor that in the 
future.

Corrections pushed.

That doesn't explain why some of the py and other files already have the 
execution bit set; maybe something similar has happened in the past.

If you would welcome a pr to normalize these across the codebase, I'll be happy 
to do.

**Review by feerrenrut — COMMENTED** [review]
Thanks @XLTechie, I'll target this to 2020.4

**Review by feerrenrut — APPROVED** [review]

**Pull request merged**
