### PR TITLE
Clean up Mozilla specific code

### PR DESCRIPTION
**Pull request by jcsteh**
### Link to issue number:
None.

### Summary of the issue:
There's quite a bit of code lying around to support Mozilla Firefox/Gecko versions which are now many years out of date. Aside from being messy, there are some checks which run frequently (e.g. fetching NODE_CHILD_OF for parent NVDAObject), which may have some performance impact.

### Description of how this pull request fixes the issue:
Broken into commits to make it easier to look at each piece if you wish:

1. Don't fetch NODE_CHILD_OF when fetching parent NVDAObject, since this is no longer needed (or useful) for combo boxes (which is why it was originally implemented).
2. Get rid of mozilla.RootApplication, since this object is no longer reachable without NODE_CHILD_OF.
3. accParent is broken in Firefox for same-process iframe documents, so we must still use NODE_CHILD_OF for Documents (but nowhere else). So, this is now isolated to mozilla.Document.
4. Gecko now prunes aria-hidden objects from the tree, so the hidden attribute is no longer used. Remove support for it.
5. NVDA core: Drop code specific to supporting very old versions of Gecko (Gecko 1.9.x, Gecko < 14).
6. Gecko vbuf backend: Drop code specific to supporting very old versions of Gecko (Gecko 1.9.x, Gecko < 14).
7. Gecko always sets the focused state correctly now, so drop BrokenFocusedState code.
8. Remove unnecessary imports.
9. We only allow show/hide/reorder events for specific cases anyway, so the code to ignore these events for the Firefox location bar is redundant. Remove it.
10. Firefox hasn't had a status bar for a long time, so the Firefox app module does nothing. Remove it.

### Testing performed:
Daily web stuff with multiple tabs (Gmail, Slack, other pages), plus specifically tested:

- Add-on panels (Google Translate, Greasemonkey), including focusing text boxes
- `<select size="1">` combo box controls
- iframes, both same-process and out-of-process

### Known issues with pull request:
None.

### Change log entry:

Not user visible.

### CODE REVIEW

**Comment by MarcoZehe** [comment]
So glad to see all this stuff go away.

**Comment by jcsteh** [comment]
It turns out that we still need  NODE_CHILD_OF for same-process iframe documents due to a Gecko bug I was unaware of. :( I'll fix that, but in the meantime, I've added this back, but just for documents. This still saves us calling it for all other Mozilla objects where we don't need to.

**Comment by codeofdusk** [comment]
Any updates on this PR?
Cc @feerrenrut @michaelDCurran

**Comment by jcsteh** [comment]
This causes a regression in Firefox Dev Tools which I need to address. The regression isn't so much due to code in this PR, but rather, it removes some code which has hitherto been hiding a bug elsewhere. Nevertheless, this can't be merged until that's dealt with.

**Review by michaelDCurran — APPROVED** [review]
A lot of old memories there...

**Comment by akash07k** [comment]
@michaelDCurran 
@feerrenrut 
After merger of this pull request, I'm unable to browse the web while using firefox.
NVDA is not switching to the browse mode.
Even NVDA+Space is also not working.
Below are the errors:
Traceback (most recent call last):
  File "api.pyc", line 128, in setFocusObject
  File "treeInterceptorHandler.pyc", line 37, in update
  File "baseObject.pyc", line 41, in __get__
  File "baseObject.pyc", line 144, in _getPropertyViaCache
  File "C:\Users\akash\AppData\Roaming\nvda\addons\NVDAExtensionGlobalPlugin\globalPlugins\NVDAExtensionGlobalPlugin\browseModeEx\NVDAObjectsIAccessible.py", line 22, in _get_treeInterceptorClass
    ver=NVDAObjects.IAccessible.mozilla.getGeckoVersion(self)
AttributeError: module 'NVDAObjects.IAccessible.mozilla' has no attribute 'getGeckoVersion'
ERROR - api.setFocusObject (11:42:39.928) - MainThread (11124):
Error updating tree interceptor
Traceback (most recent call last):
  File "api.pyc", line 128, in setFocusObject
  File "treeInterceptorHandler.pyc", line 37, in update
  File "baseObject.pyc", line 41, in __get__
  File "baseObject.pyc", line 144, in _getPropertyViaCache
  File "C:\Users\akash\AppData\Roaming\nvda\addons\NVDAExtensionGlobalPlugin\globalPlugins\NVDAExtensionGlobalPlugin\browseModeEx\NVDAObjectsIAccessible.py", line 22, in _get_treeInterceptorClass
    ver=NVDAObjects.IAccessible.mozilla.getGeckoVersion(self)
AttributeError: module 'NVDAObjects.IAccessible.mozilla' has no attribute 'getGeckoVersion'
ERROR - api.setFocusObject (11:42:50.487) - MainThread (11124):
Error updating tree interceptor
Traceback (most recent call last):
  File "api.pyc", line 128, in setFocusObject
  File "treeInterceptorHandler.pyc", line 37, in update
  File "baseObject.pyc", line 41, in __get__
  File "baseObject.pyc", line 144, in _getPropertyViaCache
  File "C:\Users\akash\AppData\Roaming\nvda\addons\NVDAExtensionGlobalPlugin\globalPlugins\NVDAExtensionGlobalPlugin\browseModeEx\NVDAObjectsIAccessible.py", line 22, in _get_treeInterceptorClass
    ver=NVDAObjects.IAccessible.mozilla.getGeckoVersion(self)
AttributeError: module 'NVDAObjects.IAccessible.mozilla' has no attribute 'getGeckoVersion'
ERROR - eventHandler.executeEvent (11:42:50.547) - MainThread (11124):
error executing event: documentLoadComplete on <NVDAObjects.Dynamic_EditableTextExNVDAObjectMozillaDocumentExMozillaIAccessible object at 0x08D542F0> with extra args of {}
Traceback (most recent call last):
  File "eventHandler.pyc", line 211, in executeEvent
  File "eventHandler.pyc", line 264, in doPreDocumentLoadComplete
  File "treeInterceptorHandler.pyc", line 37, in update
  File "baseObject.pyc", line 41, in __get__
  File "baseObject.pyc", line 144, in _getPropertyViaCache
  File "C:\Users\akash\AppData\Roaming\nvda\addons\NVDAExtensionGlobalPlugin\globalPlugins\NVDAExtensionGlobalPlugin\browseModeEx\NVDAObjectsIAccessible.py", line 22, in _get_treeInterceptorClass
    ver=NVDAObjects.IAccessible.mozilla.getGeckoVersion(self)
AttributeError: module 'NVDAObjects.IAccessible.mozilla' has no attribute 'getGeckoVersion'
ERROR - api.setFocusObject (11:43:22.881) - MainThread (11124):
Error updating tree interceptor
Traceback (most recent call last):
  File "api.pyc", line 128, in setFocusObject
  File "treeInterceptorHandler.pyc", line 37, in update
  File "baseObject.pyc", line 41, in __get__
  File "baseObject.pyc", line 144, in _getPropertyViaCache
  File "C:\Users\akash\AppData\Roaming\nvda\addons\NVDAExtensionGlobalPlugin\globalPlugins\NVDAExtensionGlobalPlugin\browseModeEx\NVDAObjectsIAccessible.py", line 22, in _get_treeInterceptorClass
    ver=NVDAObjects.IAccessible.mozilla.getGeckoVersion(self)
AttributeError: module 'NVDAObjects.IAccessible.mozilla' has no attribute 'getGeckoVersion'
ERROR - api.setFocusObject (11:43:34.256) - MainThread (11124):
Error updating tree interceptor

**Comment by josephsl** [comment]
Hi, this is an add-on issue, not NVDA Core. Please ask the add-on author to update the add-on. Thanks.

**Comment by akash07k** [comment]
Ok, thanks.

**Pull request merged**
