### PR TITLE
Disable reporting of link types by default

### PR DESCRIPTION
**Pull request by codeofdusk**
### Link to issue number:
Fix-up of #16994.

### Summary of the issue:
NVDA now reports internal links by default. This extra verbosity isn't always wanted, and might be confusing to new users.

### Description of how this pull request fixes the issue:
Disable this feature by default on new installations.

### Testing strategy:
Alpha testing

### Known issues with pull request:
None known

### Code Review Checklist:

- [x] Documentation:
  - Change log entry
  - User Documentation
  - Developer / Technical Documentation
  - Context sensitive help for GUI changes
- [x] Testing:
  - Unit tests
  - System (end to end) tests
  - Manual testing
- [x] UX of all users considered:
  - Speech
  - Braille
  - Low Vision
  - Different web browsers
  - Localization in other languages / culture than English
- [x] API is compatible with existing add-ons.
- [x] Security precautions taken.

### CODE REVIEW

**Comment by XLTechie** [comment]
Per the contribution guide, PRs that are potentially controversial, need to be discussed in issues first.

This one definitely qualifies.

I vote for closure until discussed.

**Comment by nvdaes** [comment]
@codeofdusk, I agree with @XLTechie comment. This has been enabled by default after a discussion in #141.
If for any reason this needs to  be reverted, this should be discussed first  with opinions of users.

**Comment by amirsol81** [comment]
@codeofdusk I agree with @nvdaes here - the feature should be kept enabled IMO - like other screen readers which provide the same functionality.

**Comment by CyrilleB79** [comment]
@codeofdusk I agree with the opinions expressed here.

You may have a good reason to wish this feature to be disabled by default. But the default value has been discussed in the past (in #141, so I'd encourage you to open a specific issue for that.
There you can list all the pros and cons (yours and from other people) and explain why your arguments to disable the feature are stronger.

You write:
> This extra verbosity isn't always wanted,

I'd say: OK, no problem, it can be disabled anyway.

And you also write:
> and might be confusing to new users.

Could you be more specific in the issue that you will open. The feature is available in Jaws by default and I have never heard of people being confusing. If it's something specific to NVDA, please explain in the issue. Thanks.

**Comment by SaschaCowley** [comment]
@codeofdusk per our [contributing guide](https://github.com/nvaccess/nvda/blob/master/projectDocs/dev/contributing.md), please open an issue for anything other than minor bug fixes so that they can be discussed before you create a PR.

This feature is enabled by default for maximum discoverability, and because it is what a lot of users, especially those who are used to other screen readers, expect. Disabling it is not difficult for those of us who do not desire this functionality.

**Pull request closed without merging**
