### PR TITLE
Update Help menu to include more links - split out docs

### LINKED ISSUE #14631: Add link to "Get Help" page to NVDA help menu
### Is your feature request related to a problem? Please describe.

Some users don't know resources such as the mailing lists or training material exist.  Having these available from NVDA"s Help menu might make them easier to find for more users.

### Describe the solution you'd like

The Help menu currently contains:
- User guide
- Commands quick reference
- What's new
- NVDA web site
- License
- Contributors
- Welcome dialog
- Check for updates
- About

This is already quite a bit.  My suggestion is:

- "About" already mentions the license, with a suggestion that you can view the license from the help menu.  I propose removing "License" and "Contributors" from the help menu, and adding buttons or links for them on the about page.
- Note the presence of the Quick Start Guide in the User Guide entry
- Note the presence of the license and contributors in the "About" entry
- Add a new entry "Get Help (Training and support)" which links to https://www.nvaccess.org/get-help/

The Help menu would then contain:
- User guide (with Quick Start Guide)
- Commands quick reference
- What's new
- NVDA web site
- Welcome dialog
- Get Help (Training and support)
- Check for updates
- About (version, license, contributors)

This does make some menu items long, however the pertinent information ("User Guide" and "About") is still read first by NVDA.  In quick testing, for low vision / magnification users, the magnification level would need to be over ~800% before that length of text won't fit on screen.  At that level of magnification, they will be experiencing that in many places.

### Describe alternatives you've considered

There are numerous ways this menu could be changed.  These are about the simplest, and most immediate I can think of which are likely to have the most positive impact.

### PR DESCRIPTION
**Pull request by seanbudd**
### Link to issue number:
Fixes #14631

### Summary of the issue:
* Documentation (user guide, changes, licence, etc) could be moved out of the help menu to be better grouped.
* The NVDA help menu would be improved with a link to NV Access's "Get help" web page, as well as the NV Access Shop for training materials.

### Description of user facing changes
New menu structure, previously these were all under "Help"

- Documentation
  - User Guide
  - Key commands
  - Changes
  - License
  - Contributors
- Help
  - NV Access website
  - NV Access Get Help page
  - NV Access Shop page
  - Welcome dialog
  - Check for update
  - About dialog

Accelerator keys had to be updated due to the moving of items.

### Description of development approach

- New helper functions were created for each updated section of the NVDA menu.
- The usage of `https://nvda-project.org/` was updated to the current NV Access website URL, and the entry for the Menu item has changed from "NVDA website" to "NV Access website".
- The donation URL was updated to use the `https` version of the NV Access website URL

### Testing strategy:
Test opening menu items manually

### Code Review Checklist:

- [x] Documentation:
  - Change log entry
  - User Documentation
  - Developer / Technical Documentation
  - Context sensitive help for GUI changes
- [x] Testing:
  - Unit tests
  - System (end to end) tests
  - Manual testing
- [x] UX of all users considered:
  - Speech 
  - Braille
  - Low Vision
  - Different web browsers
  - Localization in other languages / culture than English
- [x] API is compatible with existing add-ons.
- [x] Security precautions taken.

### CODE REVIEW

**Comment by lukaszgo1** [comment]
Aside from the fact that changing accelerator keys would (as it always does) cause annoyance for users (but I assume you have considered that and decided that these improvements justify it), I'm not sure I understand the reasoning behind moving of the 'check for updates' item out of the help menu. Looking at other programs I have installed the only one in which ability to check for updates is not in the help menu is MS Office, though that is likely because it auto-updates in the background. In all other cases (Firefox, JAWS, Acrobat Reader, Notepad++, VS Code...) this option is in the help menu, so that seems to be standard placement. It is also worth pointing out, though this may may affect only more advanced users, that for try  builds, source copies, etc. this option is hidden, so if i weren't following this thread, updated to the version with this change,pressed NVDA + N -> H -> C (as I've been doing for years to check for updates), and notice that the option is not there, it is likely I would try to debug why my update check stopped working, and don't think to look  throughout the entire menu. If you want to group these options together it appears more logical to move "install pending update' to the help menu, rather than the other way around. Also has it been considered to make 'documentation' a sub menu of the help menu, instead of its own, independent menu?

**Comment by seanbudd** [comment]
We'd like more feedback on these changes before making a decision and merging

**Comment by seanbudd** [comment]
>Also has it been considered to make 'documentation' a sub menu of the help menu, instead of its own, independent menu?

Depth is more annoying to navigate, and only 2 of the docs in the submenu are related to "help" (user guide, key commands).

**Comment by cary-rowen** [comment]
I'm not a big fan of changing the entry for checking for updates and documentation, besides breaking the accelerator habit would be confusing, there are many external tutorials or add-on documentation that may also mention the path to these documents.

**Comment by XLTechie** [comment]
Many applications include the Check for/Install updates option, at the top of 
their About dialog, with the version number. That doesn't mean we should, it is 
just one of the common placements.

Others, as @lukaszgo1 said, put it in the Help menu if they have one.

Rarely have I noticed it in the main Window, which for us would be on the main 
menu.

Personally I prefer that it remain where it has traditionally been.

**Comment by XLTechie** [comment]
The only way I think a Documentation submenu would be a good idea, is if we 
start encouraging add-on authors to place documentation there as well, or if we 
do that programatically like the Add-on Documentation add-on does.

Otherwise, if it's just the few NVDA docs themselves, a submenu seems like 
overkill, and I agree with @seanbudd's approach.

**Comment by seanbudd** [comment]
>Many applications include the Check for/Install updates option, at the top of their About dialog, with the version number. That doesn't mean we should, it is just one of the common placements. Others, as @lukaszgo1 said, put it in the Help menu if they have one. Rarely have I noticed it in the main Window, which for us would be on the main menu. Personally I prefer that it remain where it has traditionally been.

The main reason to move it is for discoverability and to keep it with the "install pending update" item. Moving the other item to the help menu would decrease the discoverability of pending updates. We can stick with convention but checking for an update doesn't really fit under "Help" logically.
I think being able to check for update from the about dialog as well would be a nice to have.

**Comment by lukaszgo1** [comment]
> The main reason to move it is for discoverability and to keep it with the "install pending update" item. Moving the other item to the help menu would decrease the discoverability of pending updates. 


It may be more discoverable visually, but for blind users this does not really matter - they need to move through the entire menu to find it regardless in which one these options are placed. I would say the main way people install pending updates is either from the pending update reminder on startup, or from the exit dialog, though I don't have any scientific evidence to back this up.

**Comment by seanbudd** [comment]
Considering it is safer to stick with convention for the check for update, that change has been reverted

**Review by michaelDCurran — APPROVED** [review]

**Comment by cary-rowen** [comment]
I think this PR was merged too early. He doesn’t seem to be hearing enough from the community. In my opinion, "documentation" also falls under the category of help.
Sorry, I don't see any obvious benefit to having Documents as a separate menu.

**Comment by CyrilleB79** [comment]
I also comment a bit late.
I have no very strong impression about this change and will not fight in any direction to have it modified, i.e. I will not open a new issue or PR to optimize this.

Anyway here is my personal impression:
The documentation menu does not bring anything interesting. Specifically, in many applications, the help doc (user guide) can be found in the Help menu. I feel that separating Help and Documentation may lead to confusion, i.e. "I do not remember if User Guide is in Help or in Documentation".
Maybe the scope for splitting the help menu was to avoid a menu with too much items? In this case, a submenu "Useful links" under the Help menu can group all the links on NV Access website.
I agree that the User Guide should not be put in a 2nd sublevel menu; but for links on NV Access website, I think that it may be acceptable.

At last, I note that adding more items pointing on NV Access website may not be so interesting for non-English speaking users of NVDA; this issue was already present with the link on the main page of NV Access website, but adding these new links makes it more noticeable.

**Comment by codeofdusk** [comment]
It looks like the "check for updates" reversion wasn't successful, and its placement in the root menu is confusing, misleading, and breaks years of muscle memory.

I like the proposal by @CyrilleB79 to restore the "documentation" items back to the help menu, and add a "useful links" (or similar) submenu.

**Comment by leonardder** [comment]
Lets move the discussion to #15740. Comments on closed pull requests are easily missed.

**Comment by CyrilleB79** [comment]
Actually the discussion takes place in #15749.

**Pull request merged**
