### PR TITLE
Fix documentation formatting

### LINKED ISSUE #17159: The Commands Quick Reference contains text from the User Guide that should not belong to it
### Steps to reproduce:

1. Open Commands Quick Reference
2. Go to"MiniSeika (16, 24 cells), V6, and V6Pro (40 cells)" paragraph
3. Look at the content of this paragraph after the first table

### Actual behavior:
You have some extra text and table that actually belong to "Papenmeier BRAILLEX Newer Models" in the User Guide, from "The following Braille displays are supported:"
to "Following are the Papenmeier command assignments for NVDA:"

### Expected behavior:

In any case, this extra text does not need to be in the Commands quick reference, neither in "MiniSeika (16, 24 cells), V6, and V6Pro (40 cells)", paragraph nor in "Papenmeier BRAILLEX Newer Models" paragraph.

### NVDA logs, crash dumps and other attachments:
N/A
#### NVDA installed/portable/running from source:
N/A
#### NVDA version:
2024.4beta3
#### Windows version:
N/A
#### Name and version of other software in use when reproducing the issue:
N/A
#### Other information about your system:
N/A
#### Does the issue still occur after restarting your computer?
N/A
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
Not checked again but I think that this issue was already present in 2024.3
#### If NVDA add-ons are disabled, is your problem still occurring?
N/A
#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
N/A

### PR DESCRIPTION
**Pull request by CyrilleB79**
Closing tag issue found while reviewing ja user guide following @nishimotz's [message on the translators mailing list](https://groups.io/g/nvda-translations/message/4239).

### Link to issue number:
Fixes #17159

### Summary of the issue:
Commands Quick Reference includes text that was not intended to be included, due to missing closing tag `<!-- KC:endInclude -->`

### Description of user facing changes
The Commands Quick Reference will no longer include text unrelated to shortcut keys.

### Description of development approach
Added the closing tag in the User Guide.
### Testing strategy:
Check the newly generated Commands Quick Reference.
### Known issues with pull request:
None
### Code Review Checklist:

- [x] Documentation:
  - Change log entry
  - User Documentation
  - Developer / Technical Documentation
  - Context sensitive help for GUI changes
- [x] Testing:
  - Unit tests
  - System (end to end) tests
  - Manual testing
- [x] UX of all users considered:
  - Speech
  - Braille
  - Low Vision
  - Different web browsers
  - Localization in other languages / culture than English
- [x] API is compatible with existing add-ons.
- [x] Security precautions taken.

## Summary by CodeRabbit

- **Documentation**
	- Updated the user guide to improve structural organization with a new comment tag for better section management.

### CODE REVIEW

**Comment by CyrilleB79** [comment]
Strangely, the issue in the key commands document is not fixed (on appVeyor artifacts).

**Comment by seanbudd** [comment]
@CyrilleB79 - could you open an issue to explain the problem being faced more thoroughly?

**Comment by CyrilleB79** [comment]
@seanbudd this PR is now ready.

I have opened #17159 to describe the issue with more details.

After merging last beta, the issue described in https://github.com/nvaccess/nvda/pull/17121#issuecomment-2332680891 is not present anymore; I do not know why.

In the meantime, the translation freeze period has started. Since it is quite long (more than usual), I wonder if you would still accept this PR against beta. If not, let me know and I'll rebase on master.

**Comment by CyrilleB79** [comment]
Please note that this change should have no impact for translators using the new framework to translate the user guide through Crowdin.

For translators still using the old framework (SVN), it would have an impact, but I guess that new changes won't be merged  anymore in SVN. So no problem.

**Review by michaelDCurran — APPROVED** [review]

**Pull request merged**
