### PR TITLE
Disable style navigation in Outlook and non-UIA word

### PR DESCRIPTION
**Pull request by mltony**
### Link to issue number:
N/A
### Summary of the issue:
We have discovered multiple problemds with non-UIA textInfo implementation in MS Word. Some examples are #16527, #16459, #16458. Also TextInfo implenetation in Outlook has proven to be too slow for style navigation. Therefore disabling both.
### Description of user facing changes
"Not supported in this document" message is spoken.
### Description of development approach
Raising an error when Outlook or non-UIA Word is detected.
### Testing strategy:
Manual
### Known issues with pull request:
N/A
### Code Review Checklist:

- [x] Documentation:
  - Change log entry
  - User Documentation
  - Developer / Technical Documentation
  - Context sensitive help for GUI changes
- [x] Testing:
  - Unit tests
  - System (end to end) tests
  - Manual testing
- [x] UX of all users considered:
  - Speech 
  - Braille
  - Low Vision
  - Different web browsers
  - Localization in other languages / culture than English
- [x] API is compatible with existing add-ons.
- [x] Security precautions taken.

### CODE REVIEW

**Comment by CyrilleB79** [comment]
@seanbudd, what did happen with this PR? It has been merged to master according to GitHub, but it does not seem present in master branch anymore. And anyway, it contains unrelated content.

**Comment by seanbudd** [comment]
I didn't merge this PR, I think merging beta to master caused this bug to appear. it's very strange. @mltony can you please reopen this PR?

**Comment by mltony** [comment]
I don't see a way to reopen this pr. Shall I create a new one?

**Comment by cary-rowen** [comment]
Yes, in this case you may indeed need to open another

**Comment by Adriani90** [comment]
Is nvda translation automation allowed to merge PRs? This might have caused this bug.

**Comment by seanbudd** [comment]
I've experienced this bug with GitHub's stacked PRs feature in the past a couple times. If one PR is stacked against another on the sometimes merging the base branch on the stacked PR causes it to close. Particularly if merge conflicts had been introduced.

**Comment by CyrilleB79** [comment]
It's worth noting that there are no commit from Tony in the commit list of this PR.

The most probable step to have reached this situation is:
1. Tony creates locally his `disableStyleWord` branch on top of beta
2. Tony performs modifications but do not commit them
3. Tony pushes `disableStyleWord` to his remote nvda repo. At this stage branch `disableStyleWord` in Tony's remote repo points to the same commit than `beta`.
4. Tony opens the corresponding PR, by mistake against master; at this stage, the list of comits in the PR are the ones from beta branch from the point it diverges from master.
5. Sean merges beta to master; at this stage `disableStyleWord`, `beta` and `master` point to the same commit.
6. Since there are no more modifications specific to Tony's PR to be merged, GitHub closes it upon Sean's merge action.

**Comment by mltony** [comment]
It is possible I screwed up something with this PR. As requested, I just created a  duplicate PR #16569. Hopefully I didn't screw it up.

**Pull request merged**
