### PR TITLE
MoveFileEx: catch WindowsError instead of WinError

### PR DESCRIPTION
**Pull request by josephsl**
### Link to issue number:
Follow-up to #9847 

### Summary of the issue:
In installer, MoveFileEx catches wrong exception.

### Description of how this pull request fixes the issue:
Instead of catching WinError, catch WindowsError (an alias of OSError in Python 3).

### Testing performed:
Tested in Python 3 interpreter and NvDA console.

### Known issues with pull request:
None

### Change log entry:
None

### CODE REVIEW

**Comment by leonardder** [comment]
I don't think WinError was ever an exception. Should have been WindowsError, which is an alias of OSError on Python 3.

**Comment by josephsl** [comment]
Hi, ctypes.WinError was just a function after all, and as for WindowsError, confirmed that this is an alias (editing). Thanks.

**Comment by feerrenrut** [comment]
Can you confirm that this will put the windows error code in the log please?

**Comment by josephsl** [comment]
Hi, I’ll add exc_info parameter since error code isn’t logged yet. Thanks.

**Review by LeonarddeR — APPROVED** [review]

**Comment by leonardder** [comment]
@feerrenrut: I think this is important to go into threshold_py3_staging before merging it into threshold. It is currently preventing me from updating a copy.

**Review by feerrenrut — APPROVED** [review]
Thanks @josephsl

**Pull request merged**
