### PR TITLE
{liblouis3.6.0 brailletables}

### LINKED ISSUE #8437: add new braille tables to NVDA
the template cannot be applyed for this issue, so i am describing it in the following way.
Liblouis version 3,6.0 arrived in master, so these changes which i propose can be merged straightforward, as i verified that the braille tables don't crash NVDA.
Recently, i mentioned that there is a new czech 8-dots table in NVDA, and i have mentioned it as a part of the pull request regarding the upgrade, but this is not applied. 
Now, i discovered that tere are few braille tables, which are correct, and these can be merged straight to master, as these are not breaking the functionality of NVDA itself.
these are:
ckb-g1.ctb central kurdish , sorani braille table, grade1
cs-comp8.utb czech 8-dots braille table, standard computer braille
eo-g1.ctb esperanto grade 1 table 
hu-hu-g2.ctb hungarian grade2, contracted table
urdu braille removed, as it causes serious issues.
thanks,
Zvonimir

### PR DESCRIPTION
**Pull request by zstanecic**
### Link to issue number:
closes #8437

### Summary of the issue:
In the liblouis 3.6.0, there are some new braille tables for some languages, and others, which were not added in the past.
### Description of how this pull request fixes the issue:
This pull request adds new braille tables mentioned in the issue above, and corrects the russian braille table to the proper eight'dot table.
the table for russian whic was used in the past is not a proper russian eight'dot standardised table.
The table in the past was a representation for printing braille.
This pull request adds the following tables:
1. central Kurdish
2. czech,
3. esperanto grade 1,
4. hungarian grade 2
5. corrects russian braille table.
### Testing performed:
latest master snapshot from source, on the first review, unit test passed, 
### Known issues with pull request:
none, can be merged to master directly
### Change log entry:
=== new features ===
• added czech eight dots, central kurdish, esperanto and hungarian braille tables
=== changes===
• updated the path to the correct russian eight-dots table

### CODE REVIEW

**Comment by josephsl** [comment]
CC @LeonardDer, @DKager, @DerekRiemer

**Comment by zstanecic** [comment]
I can again say, that it is tested, and it is ready for master, as 
braille tables are not breaking. appvejor assed, as i see.

**Comment by josephsl** [comment]
Hi, not yet, as we still want to see it incubated into next first. Thanks.

**Comment by zstanecic** [comment]
@mdcurran

**Review by michaelDCurran — DISMISSED** [review]

**Comment by zstanecic** [comment]
edited the change files for this PR, who can re-review it again? 
@leonardder,
@dkager,
@michaelDCurran 
@josephsl

**Review by josephsl — DISMISSED** [review]
If this is the same as the one approved weeks ago, then yes, I motion this be included after a second look by NV Access people. Thanks.

**Review by michaelDCurran — DISMISSED** [review]

**Review by michaelDCurran — DISMISSED** [review]

**Review by michaelDCurran — APPROVED** [review]

**Pull request merged**
