### PR TITLE
Show proper display description when listing manually added braille display gestures in the input gestures dialog

### LINKED ISSUE #8108: Input Gestures window shows the name of the last braille display, not the originally defined one
In the "gestures.ini" the braille hotkeys are of course labelled correctly, but the Input Gestures window shows the name of the last set/connected braille display with NVDA. I have set many BAUM hotkeys but after connecting the ALVA BC680 to NVDA all BAUM hotkeys are now labelled as hotkeys for this new ALVA braille display in the GUI.

Example from the German GUI:
"Pfeiltaste nach links
- d2+d3+routing (Optelec ALVA 6-Serien/Protokoll-Konverter)
- d2+d4+d6 (Optelec ALVA 6-Serien/Protokoll-Konverter)
- spleft (Optelec ALVA 6-Serien/Protokoll-Konverter)"

Expected solution:
"Pfeiltaste nach links
- d2+d3+routing (Baum / HumanWare / APH  / Orbit Braillezeilen)
- d2+d4+d6 (Baum / HumanWare / APH  / Orbit Braillezeilen)
- spleft (Optelec ALVA 6-Serien/Protokoll-Konverter)"

The source for the variable (braille display) should be read from the "gestures.ini" file, not from the braille display which was connected/set to NVDA at last..

### PR DESCRIPTION
**Pull request by LeonarddeR**
### Link to issue number:
Closes #8108 

### Summary of the issue:
When adding a braille display gesture to a script using the input gestures dialog, the added gesture shows up along with the description of the current display. However, when changing the current braille display, the gesture added earlier always shows up with the currently active display, not with the display driver description the gesture identifier belongs to.

### Description of how this pull request fixes the issue:
1. Updated braille._getDisplayDriver to accept an additional keyword argument, caseSensitive. If False, this function allows case insensitivity, in which case the source part of an identifier (e.g. "handytech" for the id "br(handytech):b1") can be used to find the handyTech BrailleDisplayDriver class.
2. updated braille.BrailleDisplayGesture.getDisplayTextForIdentifier to find the description of the display the identifier belongs to. This is pretty easy now we can parse braille display gesture identifiers using the braille.BrailleDisplayGesture.ID_PARTS_REGEX.

### Testing performed:
* Added a gesture for the handy tech display. When selected no braille, the gesture still showed up as a gesture belonging to the handy tech driver.
* In gestures.ini, changed handytech into handytechf. The gesture now showed up as referring to "Unknown braille display driver" 

### Known issues with pull request:
None

### Change log entry:
* Bug fixes
    + When manually assigning functions to gestures for a particular braille display, these gestures now always show up as being assigned to that display. Previously, they showed up as if they were assigned to the currently active display. (#8108)

### CODE REVIEW

**Review by michaelDCurran — APPROVED** [review]

**Comment by leonardder** [comment]
@dkager: Would be good to know whether you have anything to say about this, since it was one of your annoyances until now ;)

**Comment by leonardder** [comment]
Hmm yes, I think it should.

**Comment by josephsl** [comment]
Hi,

Appveyor says the build process has failed, with the build log showing that one of the unit tests didn't pass.

Thanks.

**Comment by leonardder** [comment]
Thanks for pointing out. I will undo the incubation and will request for another review after the unit test conflict has been resolved.

**Review by dkager — DISMISSED** [review]

**Comment by leonardder** [comment]
@michaeldcurran: Could you do a review of the last changes before we incubate this again?

**Review by michaelDCurran — DISMISSED** [review]

**Comment by michaelDCurran** [comment]
This has been removed from next again. Unittests failed. If they are succeeding on this branch but not on next, it may be possible that  new merges of this branch into next are breaking as there was a previous revert. Git does not cope well with this.  A casing point as to why we are considering the new release process with PRs squashing merging straight to master.

**Comment by leonardder** [comment]
@michaeldcurran: What would be the best way to incubate this?

**Comment by michaelDCurran** [comment]
You could rebase this branch on master and then we could incubate to next again. However, be aware that this will cause any review comments to become invalid.

**Review by michaelDCurran — DISMISSED** [review]

**Pull request merged**
