### PR TITLE
Solve the problem of character sensitivity in the terminal with nvda/…

### PR DESCRIPTION
**Pull request by ahmad-alajaj**
Hello, I worked on this issue, I located the entry point of nvda software which is nvda.pyw in the source folder.

For the solution I used 'sys' library, I edit all the arguments and lower them using 'lower()' function before any process from the parser. As this parser uses also 'sys.argv', I put the changes in the begining of the file.

here is the code:

for i in range(len(sys.argv)):
	sys.argv[i]=sys.argv[i].lower()

Later I wrote a small program to test this changes using sys and parser and it worked pretty fine, which made me test it on nvda and it ignores the case sensitivity of the commands while using CMD.

…See line 22 + 23
nvda.pyw

### Change log entries:
New features
Changes
Bug fixes
For Developers

### Code Review Checklist:

- [x] Pull Request description:
  - description is up to date
  - change log entries
- [x] Testing:
  - Unit tests
  - System (end to end) tests
  - Manual testing
- [x] API is compatible with existing add-ons.
- [x] Documentation:
  - User Documentation
  - Developer / Technical Documentation
  - Context sensitive help for GUI changes
- [x] UX of all users considered:
  - Speech 
  - Braille
  - Low Vision
  - Different web browsers
  - Localization in other languages / culture than English

### CODE REVIEW

**Comment by seanbudd** [comment]
Just to confirm - this is an attempt to close #12434?

**Comment by seanbudd** [comment]
Please fill out the PR template

**Comment by seanbudd** [comment]
More thorough approaches have been discussed on #12434.
A future PR should consider these approaches and `argparser`, as well as fill out the PR template.

**Comment by ahmad-alajaj** [comment]
#12434

**Comment by ahmad-alajaj** [comment]
I'm sorry I didn't pay attention
Can you open it up so I can fill in the unfinished stuff??
If not, I will create a new request
Best regards > More thorough approaches have been discussed on #12434. A future PR should consider these approaches and `argparse`, as well as fill out the PR template.

**Comment by ahmad-alajaj** [comment]
I created a new request
This link is here 
https://github.com/nvaccess/nvda/pull/13436
> More thorough approaches have been discussed on #12434. A future PR should consider these approaches and `argparse`, as well as fill out the PR template.

**Pull request closed without merging**
