### PR TITLE
Descend into children for dialog text for option pane (Fixes #11687)

### LINKED ISSUE #11687: LibreOffice Writer: in Confirm dialog in Document restore is not announced when using screenreaders
### Steps to reproduce:
1. Crash LibreOffice
2. restart LibreOffice
3. Dissmiss restoring Documents
4. The confirm dialog opens and all you can here from screenreader is "Yes" or "No".

### Actual behavior:
Only the buttons (Yes or No) are announced by screenreader.

### Expected behavior:
The question, which this dialog asks should be announced.

#### NVDA installed/portable/running from source:
installed
#### NVDA version:
2020.2

#### Windows version:
Edition	Windows 	10 Home
Version				1909
Operating system build	18363.1016

#### Name and version of other software in use when reproducing the issue:
LibreOffice
Version:	7.0.0.3 (x64)
Build ID:	8061b3e9204bef6b321a21033174034a5e2ea88e
CPU-Threads: 	4; BS: Windows 10.0 Build 18363; UI-Render: Skia/Vulkan; VCL: win
Locale: 	de-DE (de_DE); UI: de-DE
Calc: 	threaded

#### Other information about your system:
---
#### Does the issue still occur after restarting your computer?
Yes.

#### Have you tried any other versions of NVDA? If so, please report their behaviors.
No.

#### If addons are disabled, is your problem still occuring?
Not tested.

#### Did you try to run the COM registry fixing tool in NVDA menu / tools?
Not tested.

### PR DESCRIPTION
**Pull request by michaelweghorn**
### Link to issue number:

Fixes #11687

### Summary of the issue:

Text in LibreOffice message dialogs is not announced by NVDA.

### Description of how this pull request fixes the issue:

This commit makes sure that the children of objects of role 'controlTypes.Role.OPTIONPANE' are taken into account when determining the text to announce for a dialog, as is done for objects of role 'controlTypes.Role.PANE'.

For LibreOffice (message) dialogs, the dialog text are objects of role 'controlTypes.Role.STATICTEXT'  that are children of an object of type 'controlTypes.Role.OPTIONPANE'.
Those were previously not considered when determining the dialog text to announce. This change ensures that they are now and that the actual dialog text is thus announced by NVDA, just as is done (and has been the case) for objects of role 'controlTypes.Role.PANE'.

Note: In addition to this change in NVDA, it also requires
the following commit recently committed to LibreOffice [1]
(which will be contained in LibreOffice 7.3):

    commit e29f80efc826fdc8a8e4b7cbdd3becf2f074cce4
    Author: Michael Weghorn <m.weghorn@posteo.de>
    Date:   Wed Sep 1 16:25:01 2021 +0200

        tdf#135588 wina11y: Map AccessibleRole::STATIC to ROLE_SYSTEM_STATICTEXT

Its commit message has some more background information.

[1] https://git.libreoffice.org/core/+/e29f80efc826fdc8a8e4b7cbdd3becf2f074cce4%5E%21

### Testing strategy:

* download and set up a recent LibreOffice daily build from https://dev-builds.libreoffice.org/daily/master/current.html (needs to be from 2021-09-02 or newer, since the above mentioned LibreOffice commit is needed as well)
* start NVDA and LibreOffice Writer
* type some text
* press the "Close" button in LibreOffice
* check that the Text in the "Save document?" dialog is announced completely
* kill the LibreOffice process using Task manager
* start LibreOffice again
* follow description in #11687 and ensure that the text in the document recovery dialog is announced

### Known issues with pull request:

none

### Change log entries:
*Changes*
Dialog text from an object of role 'OPTIONPANE' is now retrieved by descending into the objects children. (#11687)

### Code Review Checklist:

- [x] Pull Request description is up to date.
- [ ] Unit tests.
- [ ] System (end to end) tests.
- [x] Manual testing.
- [ ] User Documentation.
- [x] Change log entry.
- [ ] Context sensitive help for GUI changes.
- [x] UX of all users considered:
  - Speech 
  - Braille
  - Low Vision
  - Different web browsers

### CODE REVIEW

**Comment by michaelweghorn** [comment]
This is the first time I'm trying to contribute to NVDA. I went through the documentation for contributing. For those items I haven't marked checked in the code review checklist, it's unclear to me whether those are relevant in this case, so please let me know in case anything is missing.

**Comment by michaelweghorn** [comment]
From what I can see, the failed flake8 check in the test is unrelated to my change, since the added line uses the same indentation as the following lines:

 > source/NVDAObjects/behaviors.py:92:6: ET126 (flake8-tabs) unexpected number of tabs at start of expression line (expected 4, got 5)
> 					controlTypes.ROLE_OPTIONPANE,
>      ^
> 1     ET126 (flake8-tabs) unexpected number of tabs at start of expression line (expected 4, got 5)

Should I adapt indentation for all lines in the commit or add a preparatory commit to change the indentation of the existing code and a separate commit to add the new line (to keep the diff in the "actual change" as small as possible)?

**Comment by CyrilleB79** [comment]
Even if fixing only the tab number of the line you added should be enough to make the linting check pass, this makes sense to fix all the tabs for all the elements of the tuple to which you have added an element.

**Comment by seanbudd** [comment]
This looks ready for review. Considering that it would require la specific application, like libre office, to perform system tests this can be ignored. The other unticked checkboxes are also not necessary for this sort of change.

**Comment by michaelweghorn** [comment]
Thanks, I've marked this as ready for review now.

**Review by LeonarddeR — APPROVED** [review]
Congrats with your first pr! Looks good to me.

**Comment by michaelweghorn** [comment]
Thanks! Is any further action needed from my side or should I just wait for the remaining missing reviews?

**Review by michaelDCurran — APPROVED** [review]

**Pull request merged**
