### PR TITLE
Add missing message box titles (NVDA 2019.3)

### PR DESCRIPTION
**Pull request by CyrilleB79**
### Link to issue number:
None

### Summary of the issue:
1. On 2 message boxes, the caption was not translatedbecause the caption was not specified when calling gui.messageBox (or wx.MessageBox)
2. Moreover, at 2 places in the code wx.MessageBox was used instead of gui.messageBox as recommanded in messageBox function in gui.__init__.py

### Description of how this pull request fixes the issue:
1. Add missing caption parameter when calling gui.messageBox
2. Change wx.MessageBox calls to gui.messageBox call.

### Testing performed:

Tested that the following message boxes appear as expected:
1. Press Reset gestures button in the Input gestures dialog
2. Use the exampleProvider_autoGui.py in scratchpad vision providers and activated this provider
3. Force the appearing of the error dialog by artificially forcing the execution of _nonEnableableGUI in settingsDialogs.py 

### Known issues with pull request:
None

### Change log entry:

Not needed

### CODE REVIEW

**Comment by lijianwei2019** [comment]
cc @feerrenrut

**Comment by CyrilleB79** [comment]
Changed the title to have this issue triaged with 2019.3 issue.
Surely not a critical issue, but if 2019.3.1 is released with translation fixes, we may also think about this PR.

**Comment by feerrenrut** [comment]
I can't recommend including this change in 2019.3 or any subsequent minor release, there is not adequate time for testing. This will have to wait for 2020.1.

You have included a `__pycache__` file in your change. Please remove it.

**Comment by CyrilleB79** [comment]
__pycache__ strange file removed.
No problem to have it included later (2020.1), this is only a minor issue.

**Review by michaelDCurran — APPROVED** [review]

**Pull request merged**
