### PR TITLE
Update build version 2020.3

### PR DESCRIPTION
**Pull request by feerrenrut**
### Link to issue number:
None

### Summary of the issue:
Build version and changes file preparation for 2020.3

### CODE REVIEW

**Review by josephsl — APPROVED** [review]
Let's start the show, shall we?

**Comment by dingpengyu** [comment]
hi
@feerrenrut 
Version 2020.2 translation has not been synchronized to svn.
thanks

**Comment by josephsl** [comment]
Hi, that’ll happen tomorrow, so hold on. Thanks.

**Comment by codeofdusk** [comment]
The highlights for 2020.2 are missing from the changes file on `master`.

**Comment by feerrenrut** [comment]
These are still in progress @codeofdusk see https://github.com/nvaccess/nvda/pull/11264. Beta is temporarily merged back to master, when this happens the changes will appear in the change log.

**Pull request merged**
