### PR TITLE
Change shortcut  for Filter by field in the elements list from ALT+E to ALT+Y to avoid conflicts in MSWord.

### LINKED ISSUE #8728: Change shortcut in MS Word Elements List for Errors to Alt+S
1. Open Microsoft Word.
2. Toggle browse mode.
3. Open the Elements List.
4. Press Alt+E to get the spelling errors.
5. You will be placed in the Filter by field.
6. Press it again, you're stuck.

I propose that Alt+S or Alt+R be used instead to move quickly to the errors. Alt+S would be ideal, since these are spelling errors. However, Alt+R is also available, so it can be used.

### PR DESCRIPTION
**Pull request by lukaszgo1**
### Link to issue number:
Fixes #8728
### Summary of the issue:
When browse mode in Microsoft Word was used it was not possible to select  errors in the elements list due to shortcut key conflicting with filter by field.
### Description of how this pull request fixes the issue:
The shortcut key is now changed to ALT+Y to fix this and hopefully all future conflicts.
Y seems to be reasonable because there is no control starting with Y, and it is only letter include in 'filter by' which isn't used as a quick nav key.
### Testing performed:
Tested, that the shortcut is indeed  changed.
### Known issues with pull request:
None
### Change log entry:
The hotkey for the filter field in the elements list in browse mode has changed from alt+e to alt+y.
Section: Changes

### CODE REVIEW

**Review by LeonarddeR — APPROVED** [review]
As long as we agree that this will be the ever last change is to this shortcut ;) I"m ok with this.

**Comment by dingpengyu** [comment]
What is the current state of this PR?

**Comment by lukaszgo1** [comment]
It was approved by @leonardder but after that nothing. It might be a good idea to have non NV Access collaborators request a review from one of the mail developers after approval.

**Comment by Adriani90** [comment]
cc: @michaelDCurran

**Comment by feerrenrut** [comment]
Can you update the description to explain how you chose `ALT+Y`

**Comment by zstanecic** [comment]
Hi to all,

This will have no effect on some locales.

Croatian, polish and serbian, so this only changes for english

**Comment by lukaszgo1** [comment]
@feerrenrut  done.

**Comment by lukaszgo1** [comment]
@zstanecic wrote:
> This will have no effect on some locales.
 Croatian, polish and serbian, so this only changes for english


Well it is translator responsibility to set shortcut for languages other than English.

**Review by feerrenrut — APPROVED** [review]
Thanks @lukaszgo1

**Pull request merged**
