### PR TITLE
Update CLDR to version 41

### PR DESCRIPTION
**Pull request by OzancanKaratas**
### Link to issue number:
None
### Summary of the issue:
None
### Description of how this pull request fixes the issue:
Unicode has released a new version of the CLDR package.
### Testing strategy:
Manually testing: Download the AppVeyor build and tell me what went wrong.
### Known issues with pull request:
Previously opened issues with Chinese, Persian and Arabic locales: This issues will not be fixed. See #12097, #12086.
### Change log entries:

Changes

- Update CLDR to version 41.0. (#13582)
### Code Review Checklist:

- [x] Pull Request description:
  - description is up to date
  - change log entries
- [x] Testing:
  - Unit tests
  - System (end to end) tests
  - Manual testing
- [x] API is compatible with existing add-ons.
- [x] Documentation:
  - User Documentation
  - Developer / Technical Documentation
  - Context sensitive help for GUI changes
- [x] UX of all users considered:
  - Speech 
  - Braille
  - Low Vision
  - Different web browsers
  - Localization in other languages / culture than English

### CODE REVIEW

**Comment by OzancanKaratas** [comment]
Thanks @CyrilleB79, I updated the first comment.

**Review by seanbudd — APPROVED** [review]

**Comment by OzancanKaratas** [comment]
@CyrilleB79, I didn't see a locale change in CLDR 41 that needed to be added to NVDA. Can you take a look please?

**Comment by CyrilleB79** [comment]
Sorry, I do not understand what you want me to have a look at.

If you are referring to my last comment, you have modified the two points in the initial description (thanks!). I was not asking anything more.

**Comment by OzancanKaratas** [comment]
Okay, thank you. ☺️

**Review by seanbudd — APPROVED** [review]

**Pull request merged**
