### PR TITLE
Clear the filter text when switching element types in Element List

### LINKED ISSUE #5511: Elements list filter when changing element type
After bringing up the elements list (NVDA+f7) and entering text in the filter box, if you then change type (eg between links, headings and landmarks), the list of elements resets to show an unfiltered list of the new element type, however the original filter text is still left in the filter edit box.

### PR DESCRIPTION
**Pull request by dkager**
Fixes #5511.

### CODE REVIEW

**Comment by jcsteh** [comment]
Thanks! Unfortunately, this won't work. The filter method has a newElementType argument (defaulting to False) and it must be True when initialising for a new element type. Otherwise, the correct position in the tree is lost.

STR:

1. Go to www.nvaccess.org.
2. Press control+home.
3. Press 2 to move to the "Home of the free NVDA screen reader" heading.
4. Press NVDA+f7.
5. Press alt+h.
6. Press tab.
 * Expected: You should be on the "Home of the free NVDA screen reader" heading.
 * Actual: You're on the "NV Access" heading.

**Comment by dkager** [comment]
Tis what you get for not reading docs. Fixed.

**Comment by dkager** [comment]
Hmm, one more optimization could be to not perform the whole filtering algorithm, i.e. transforming all element names into lowercase, if the filter text is empty. Should give a slight performance boost unless Python is already clever enough to always mark `"" in blah` as true without evaluating `blah`.

**Comment by jcsteh** [comment]
Nice catch. Done. I also cleaned up some variable assignment that wasn't 
needed.

**Pull request closed without merging**
