### PR TITLE
NVDA 2019.1 what's new: spelling fixes, issue numbering, clarifications

### PR DESCRIPTION
**Pull request by josephsl**
### Link to issue number:
None

### Summary of the issue:
Provides fixes such as spelling for what's new.

### Description of how this pull request fixes the issue:
Specifics:

* Spelling fixes: Qualcom -> Qualcomm
* Clarifications: interface language -> NVDA's interface language
* extendedAria -> Enhanced Aria
* Issue numbering updates for emoji panel work.

### Testing performed:
None (compilation was successful and new issue links are working)

### Known issues with pull request:
None

### Change log entry:
None

### CODE REVIEW

**Comment by ruifontes** [comment]
By the way, ome more misspelling...
- The presence of formulae in LibreOffice and Apache OpenOffice 
spreadsheets is now reported. (#860)

including "formulae" instead of "formulas"...

Rui Fontes

Às 17:53 de 22/02/2019, Joseph Lee escreveu:

**Comment by josephsl** [comment]
Hi, that’s not a misspelling – it is an alternative plural word for “formula”. Thanks.

**Comment by ruifontes** [comment]
Hello Joseph!

Searching in the Net, I found:
Formulas vs formulae
Formulas are 1.) mathematical or chemical rules expressed in symbols 2.) 
specific litanies of words used in ceremonies or proceedings 3.) lists 
of ingredients used in the preparation of something, such as babies’ 
food or medical prescriptions. Formulas is a plural form of formula, the 
alternate plural of formula is formulae. Formula is a Latin word that 
was absorbed into the English language in the 1630s, to mean words used 
in a ceremony or ritual. In Latin, formula means form, draft, 
regulation, rule method. Latin words appropriated by the English 
language usually form their plurals by the English method of adding an 
“s”, except in academic circles where the plural formulae is often the norm.

And are you expecting that everyone knows that?
Remember the discussion about makking documentation for all and not for 
a minority...

Regards,

Rui Fontes



Às 18:02 de 22/02/2019, Joseph Lee escreveu:

**Comment by josephsl** [comment]
Hi, I usually do not edit an entry just to change plural forms of a word. If you want to have a discussion about it, I recommend talking to @CodeOfDusk, who was responsible for the code represented by that entry. Thanks.

**Review by michaelDCurran — APPROVED** [review]

**Comment by leonardder** [comment]
Ah, the --disable-start-on-logon command line parameter is still mentioned. That changelgo entry was outdated when the particular pr was merged. It is now --enable-start-on-logon

**Pull request merged**
