### PR TITLE
Work around pop over menu stealing focus in Ms Teams

### LINKED ISSUE #11821: Microsoft Teams: Menu focused when trying to read a message
### Steps to reproduce:
1. Install most recent Teams
2. Focus an incoming message in a chat or team channel.

### Actual behavior:
NVDA reads the incoming message.

### Expected behavior:
NVDA starts reading the incoming message, but this is suppressed by a menu getting focus. This is the menu that allows you to pick a reaction for a message (e.g. like). A focus triggers this menu. It doesn't strictly gain focus, however NVDA"s handling of the menuStart event redirects focus to it.

#### NVDA installed/portable/running from source:
Installed

#### NVDA version:
alpha-21324

#### Windows version:
Windows 10 20H2

#### Name and version of other software in use when reproducing the issue:
Microsoft Teams 1.3.00.28779
Builds like 1.3.00.26xxx don't suffer from this.

#### Does the issue still occur after restarting your computer?
Yes

#### Have you tried any other versions of NVDA? If so, please report their behaviors.
Yes

#### If addons are disabled, is your problem still occuring?
Yes

#### Did you try to run the COM registry fixing tool in NVDA menu / tools?
N/a

### PR DESCRIPTION
**Pull request by LeonarddeR**
### Link to issue number:
closes #11821 

### Summary of the issue:
In the most recent version of Microsoft Teams, a pop over menu is displayed for every focused message, stealing focus from the message and making it difficult for users to read the message.

### Description of how this pull request fixes the issue:
1. Add a new shouldAllowIAccessibleMenuStartEvent property to IAccessible objects and check it before executing a focus event for SYSTEM_MENUSTART or SYSTEM_MENUPOPUPSTART.
2. Add a Teams appmodule that adds this property to the obnoxious menus, setting it to False, thereby avoiding the menus stealing focus.

### Testing performed:
Tested that the issue does no longer occur. Also tested that pressing enter on a message in Teams correctly focuses the first item in the menu.

### Known issues with pull request:
Given JAWS and Narrator don't suffer from this issue, I think this should be considered a workaround and therefore we should consider looking into how menu start and menu popup start events are handling, trying to filter out the false positives earlier on.

### Change log entry:
* Bug fixes
    + In Microsoft Teams builds with version numbers like 1.3.00.28xxx, NVDA no longer fails reading messages in chats or Teams channels. (#11821)

### CODE REVIEW

**Comment by akash07k** [comment]
@leonardder 
Thanks a lot for this fix buddy.
If possible, can you please give me a try build?
I'm badly plagued by this bug.

**Comment by leonardder** [comment]
[Here](https://ci.appveyor.com/api/buildjobs/p1qx72f0vrtdiuay/artifacts/output%2Fnvda_snapshot_try-teamsPopOverFix-21329%2C4a0cff63.exe) is a try build.

**Comment by leonardder** [comment]
I believe the system test failure is unrelated to this work.

**Comment by akash07k** [comment]
Thanks @leonardder 
It works.
No more that bug. able to read the messages properly now.

> 
> 
> [Here](https://ci.appveyor.com/api/buildjobs/p1qx72f0vrtdiuay/artifacts/output%2Fnvda_snapshot_try-teamsPopOverFix-21329%2C4a0cff63.exe) is a try build.

**Review by michaelDCurran — DISMISSED** [review]
This looks okay. I agree this is a work-around, but for Teams, not NVDA. It looks like each time a message gets focus, focus is then bownced by Teams to the menu which is not appropriate. Further to this, the items in the menu don't have any labels until pressing enter, when the menu becomes usable.

**Comment by leonardder** [comment]
> It looks like each time a message gets focus, focus is then bownced by Teams to the menu which is not appropriate. 

NVDA focuses the menu because of SYSTEM_MENUPOPUPSTART. Are you saying that this might be cause by teams focusing the menu explicitly and does chromium translate this to SYSTEM_MENUPOPUPSTART?
It would be interesting to know why other screen readers don't suffer from this.

> Further to this, the items in the menu don't have any labels until pressing enter, when the menu becomes usable.

That's certainly a bug indeed.

**Comment by michaelDCurran** [comment]
Looking at the Chromium source code, it looks like that if an accessible 
is shown, and its role is menu, then a menuPopupStart is fired.

So, I was wrong assuming that it was because it directly took focus, but 
clearly when a message is focused, the menu is shown (though seems to 
contain no text so no doubt is invisible).


I still think this is a bug in Teams for showing the menu on every 
message focus. But, I also agree we could probably improve our logic 
around menuPopupStart etc. Though we need to be careful making any 
changes here as this code was added a long way back, mostly to do with 
menu bars and context menus obviously.

**Comment by leonardder** [comment]
> clearly when a message is focused, the menu is shown (though seems to contain no text so no doubt is invisible).

I don't think this is true. At least, I've heard reports from sighted people that the menu *is* visible.

**Comment by michaelDCurran** [comment]
Hmm. If I focus a message and get bounced to the menu, with object 
navigation if I look at its child items, they are all menu items with no 
name. Yet when I then presse enter, the items suddenly have names.

Perhaps @feerrenrut can comment on exactly what is shown when a message 
is focused?

**Comment by feerrenrut** [comment]
When focusing a message, visually there is a popup containing multiple emoji, and an overflow menu indicator (three dots). None of these are keyboard focusable until the enter key is pressed. It's pretty hard to guess how this is implemented, there are a lot of different ways it could be done.

**Pull request merged**
