### PR TITLE
Update liblouis to version 3.15.0

### PR DESCRIPTION
**Pull request by LeonarddeR**
Note, aiming at NVDA 2020.4

# Link to issue number:
None

### Description of this pull request
Updates liblouis to [3.15.0](https://github.com/liblouis/liblouis/tree/v3.15.0), which is a minor release with some table improvements.

### Testing performed:
T.b.d.

### Known issues with pull request:
None

### Change log entry:
* Changes
    + Updated liblouis braille translator to [version 3.15.0](https://github.com/liblouis/liblouis/tree/v3.15.0)

### CODE REVIEW

**Comment by zstanecic** [comment]
Hi,

As the part of this release, please add Coptic tables.

**Comment by josephsl** [comment]
Hi, there has been requests to add more tables, which should be discussed in a separate issue that will be tied to this PR if needed. Thanks.

**Comment by leonardder** [comment]
I think it would be good to leave this pr as is, and provide a follow up pr with additional tables, thereby following the naming guidelines from the liblouis project.

**Comment by codeofdusk** [comment]
Maybe consider including this PR (without tables) in 2020.3, and push the new tables to 2020.4? Therefore the Liblouis version won't lag behind the next NVDA release.

**Comment by josephsl** [comment]
Hi, it’s a bit risky, especially as we don’t want to go through regressions like a few years ago. Thanks.

**Review by feerrenrut — DISMISSED** [review]
As suggested, this will target 2020.4

**Review by feerrenrut — APPROVED** [review]

**Pull request merged**
