### PR TITLE
UI Automation in Windows Console: Use UIA by default on Windows 10 version 2004 and later

### PR DESCRIPTION
**Pull request by codeofdusk**
### Link to issue number:
Roles back #10682 and #10684. Blocked by microsoft/terminal#4018.

### Summary of the issue:
Microsoft/terminal#4018 provides native word navigation support and fixes to various UIA text range methods. Since the native implementation can now be trusted in more situations, re-enabling UIA in consoles by default on patched Windows releases is strongly worth considering.

### Description of how this pull request fixes the issue:
* Refactor `consoleUIATextInfo` into `consoleUIATextInfo` (a base class and the `textInfo` implementation to use on newer Windows releases) and `consoleUIATextInfoPre2004` (containing the older workarounds).
* Factor out movement and bounds checking into separate `_move` and `move` methods, respectively.
* Use native word navigation and default `UIATextInfo` movement and comparison methods on Windows 10 2004.
* Use UIA by default on Windows 10 version 2004 and later.

### Testing performed:
Tested with the build provided in the upstream PR. Further testing and feedback from @leonardder and @MichaelDCurran would be highly appreciated.

### Known issues with pull request:
* This PR assumes that microsoft/terminal#4018 will be merged in time for Windows 10 version 2004. If not, the version numbers should be changed accordingly to target the Windows 10 release where that PR is merged.
* `WIN10_VERSIONS_TO_BUILDS[2004]` is a placeholder value since version 2004 has not yet been released. This build number should be updated for the stable release.

### Change log entry:
== New Features ==
- In Command Prompt, PowerShell, and the Windows Subsystem for Linux on Windows 10 version 2004 and later:
 - Vastly improved performance and stability. (#10716)
 - Reporting of typed text that does not appear onscreen (such as passwords) can now be enabled via an option in NVDA's advanced settings panel. (#9649)

### CODE REVIEW

**Comment by leonardder** [comment]
Is it also within the scope of microsoft/terminal#4018 to address other UIA issues, like:

* Many blank lines at the end of the console
* Issues with visible ranges calculation we bumped into earlier

**Comment by codeofdusk** [comment]
May be worth reporting the GetVisibleRanges issues if still reproducible. Can you have a look?

**Comment by leonardder** [comment]
I don't recall the exact issue nor an issue number.

**Comment by codeofdusk** [comment]
> I don't recall the exact issue nor an issue number.

See #10559.

**Comment by codeofdusk** [comment]
Superseded by #10780 4.

**Pull request closed without merging**
