### PR TITLE
Remove all t2t files, committing generated markdown files in their place, as the the new source of truth.

### PR DESCRIPTION
**Pull request by michaelDCurran**
Blocked until final release of 2024.1.
Merging earlier would cause merge conflicts when merging user docs or translated docs from beta to master.
This must be merged before translations begin on the 2024.2beta

### Link to issue number:
None.

### Summary of the issue:
text2tags is now an old file format, and we need to move to something more standard and maintained.
We are already building markdown files from our t2t files for all languages, so we should simply remove the original t2t files and its support, and commit the generated markdown files.
 
### Description of user facing changes
None. The HTML output is the same.

### Description of development approach
* built markdown files for all t2t files.
* Committed the markdown files
* Removed the t2t files.
* Updated scons code to start from the markdown files, rather than the t2t files.
* Removed the t2t scons tool.

### Testing strategy:
* ran scons user_docs to ensure that html files were produced for all languages.

### Known issues with pull request:
None known.

### Code Review Checklist:

- [x] Documentation:
  - Change log entry
  - User Documentation
  - Developer / Technical Documentation
  - Context sensitive help for GUI changes
- [x] Testing:
  - Unit tests
  - System (end to end) tests
  - Manual testing
- [x] UX of all users considered:
  - Speech 
  - Braille
  - Low Vision
  - Different web browsers
  - Localization in other languages / culture than English
- [x] API is compatible with existing add-ons.
- [x] Security precautions taken.

### CODE REVIEW

**Comment by seanbudd** [comment]
Can you also remove:
- user_docs\ca\locale.t2tconf
- site_scons\site_tools\t2t.py
- t2t filtering in setup.py

**Comment by seanbudd** [comment]
I'm not sure if we should update the project docs in this PR, but there are references to t2t files in:
- projectDocs\dev\userGuideStandards.md
- projectDocs\dev\contributing.md

**Review by seanbudd — DISMISSED** [review]

**Review by SaschaCowley — APPROVED** [review]

**Comment by SaschaCowley** [comment]
> I'm not sure if we should update the project docs in this PR

I think that would be wise: they already need work, so it's probably best to not let them get even further behind.

**Comment by seanbudd** [comment]
Closing in favour of #16492

**Pull request closed without merging**
