### PR TITLE
Report sound and speech with NVDA's disable quick nav feature. #6683 

### PR DESCRIPTION
**Pull request by derekriemer**
Report sound with NVDA's disable quick nav feature. #6683 
Report "Browse mode, quick nav off", "browse mode", "Focus mode" when the mode changes.
For example, suppose the user is in focus mode on twitter, has quick nav disabled on gmail, and is in browse mode on nvaccess.org and xkdc.com

1. User switches from Twitter to Gmail. NVDA says "Browse mode, quick nav off" or plays the disabled quicknav sound.
2. User switches from GMAIL to the NV Access website. NVDA says "Browse mode". or bonks as usual.
3. User switches to Twitter again: NVDA says "Focus Mode" or focus mode bonks.
4. User switches to xkdc: NVDA says "Browse Mode" or browse mode bonks.
5. User switches from xkdc to gmail. NVDA says "Browse mode: Quick nav disabled" or bonks the quick nav off bonk.

Note that a sound is needed for the quick nav off case still.

### CODE REVIEW

**Comment by derekriemer** [comment]
Does anyone have a sound suggestion?

**Comment by feerrenrut** [comment]
What are your plans with for this pull request @derekriemer?

**Comment by derekriemer** [comment]
I need a sound for disabling quicknav, then I can add more to this.

**Comment by leonardder** [comment]
@derekriemer: Are you intending to maintain this after the python 3 transition? If not, we might as well close this and leave it up to anyone to reopen a refactor of this code.

**Comment by feerrenrut** [comment]
Closing this since it has been inactive for a long time. It still needs a sound file to complete the feature. We have some questions about the exact problem this is solving, now that we have a PR template I expect these would be answered if it were filled in.

**Pull request closed without merging**
