### PR TITLE
Refactored the COM Registration Fixing Tool, to make it fail more gracefully, and improve its UX

### LINKED ISSUE #12345: If the UAC is cancelled, the COM Reg Fixing Tool still claims to have completed successfully, though an error is logged
### Steps to reproduce:

1. Run the COM Reg Fixing Tool.
2. Select `yes` in the initial dialog.
3. Press escape, or decline the UAC permission request.

### Actual behavior:

NVDA logs an error stating that the process was cancelled, but the user gets the same completion dialog as if the run had been successful.

### Expected behavior:

Either some other message is shown; or no dialog is shown at all, as if the user had selected `no` in the initial dialog.

#### NVDA installed/portable/running from source:

Installed and portable

#### NVDA version:
alpha-22498,d9afe35d

#### Windows version:
10

#### Does the issue still occur after restarting your computer?
yes

#### Have you tried any other versions of NVDA? If so, please report their behaviors.
Same in alpha-22516,a0089a2f

#### If add-ons are disabled, is your problem still occurring?
yes

#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
yes

### LINKED ISSUE #12351: COM Registration Fixing Tool shouldn't start with a warning dialog and off-putting language
### Is your feature request related to a problem? Please describe.

The COM Registration Fixing Tool is a critical utility for maintaining the accessibility of Windows software.
It seems that more and more actions in Windows have the potential to cause COM deregistration, and the tool must be used more than in past years.

In supporting users across a few mailing lists, and in direct phone calls and email support sessions, I have repeatedly experienced the circumstance where a user needs to run the tool, either diagnostically or to fix a problem.
However, the responses I often hear/see are: "I looked at that, but I was afraid to run it", "I didn't understand it and it seemed dangerous to use without knowing more", "I thought we weren't really supposed to use that", and similar.
In many of those cases, running the tool actually did solve the problem.

I have become convinced that the reason for this hesitation, is fear generated by the heavy warning dialog and message that is shown when one starts to run the tool.

### Describe the solution you'd like

Because I believe this utility is more important than it ever was, I would like to see:
* The dialog switched from having a warning icon, to an info icon or no icon;
* The text in the dialog made less off-putting, and more encouraging of using the tool to try to solve problems; and
* The text in the user manual made more friendly.

### Describe alternatives you've considered

The only alternative I know of is leaving it as is, but I believe the existing warning is overkill.

### Additional context

The prime concern here seems to be that the tool modifies the registry.
However there are many programs and situations that modify the registry, which do not hit the user in the face with such a warning window. Many (all?) software installations, for example.

Even Regedit, arguably the most risky piece of software shipped with any Windows installation, doesn't provide an overt warning such as the CRFT warning.

We specifically ask users to run this tool before submitting **any** apparent bug issue on Github--so I can't believe it's as dangerous as all that.

If I am not mistaken, even NVDA itself, installs certain registry keys without warning the user, upon its installation.

And lastly, I find it telling that in #2807, which appears to be the issue which spawned the CRFT, @jcsteh, @michaelDCurran, and others never gave any big warning about running the raw commands which later became the basis for the tool.
It seemed well enough understood that, if you had this problem, getting it fixed was the most important thing; and you needed to use administrative (I.E. abnormal) commands to do it.
Discouraging users from even trying it to fix their problems, did not seem like the intention.

### Follow-up

I have already written code that can implement a better dialog. I can easily include it in #12349 if NV Access agrees to this proposal, or can do it separately if this seems too controversial.

### PR DESCRIPTION
**Pull request by XLTechie**
### Link to issue number:

Fixes #12345 
Fixes #12351 

### Summary of the issue:

The COM Registration Fixing Tool still showed its completion dialog if it failed.
In particular, it showed it if the user initially said yes, but then selected NO or pressed escape in the UAC dialog.
That seemed disconcerting and incorrect.

Additionally, the code needed improvement and linting; and the UX of the tool was not all it could be.

### Description of how this pull request fixes the issue:

Refactored this code to be in line with current coding standards, fix this problem, and to give the tool a better over all UX.

(More changes to come)
* No longer shows success dialog on failure, or when the UAC is canceled or declined.
* If there is a Windows error other than cancel of UAC, alert the user and show the error in a dialog.
* Rewrote initial dialog message mainly based on suggested text in https://github.com/nvaccess/nvda/issues/12351#issuecomment-829529714
* Switched from using YES and NO buttons, to YES_NO.
* Added a CANCEL button for visual closure and escape key use.
* Added a Help button which opens the manual to the section describing the tool.
* Catch the Windows error that signals user cancel of UAC, and return (as if "NO" had been initially chosen).
* Added a docstring. Linted and added more logging.

### Testing strategy:

* Ran with extra debug logging calls, to test logic flow.
* Tested all buttons by tabbing and pressing, and by keyboard shortcuts.
* Tested that all windows appear when and where they should.
* Confirmed that the "completed" message no longer appears on failure or cancellation.
* Simulated a WindowsError other than user cancel, to prove that a message would appear to show the error to the user.

### Known issues with pull request:

1. Upon UAC cancel, or upon successful completion, focus is moved from desktop or where ever it was, to the NVDA systray icon. That seems a little strange to me, although it is not new behavior.
2. Even after being deleted, the progress window's speech appears to hang around until after the completion window is cleared, although this speech seems to be cancelled or interrupted. Again, not new behavior. Log fragment showing this below:

```
IO - speech.speak (02:07:07.616) - MainThread (8368):
Speaking ['COM Registration Fixing Tool', 'dialog', 'The COM Registration Fixing Tool has completed successfully.', CancellableSpeech (still valid)]
IO - speech.speak (02:07:07.621) - MainThread (8368):
Speaking ['OK', 'button', CancellableSpeech (still valid)]
IO - inputCore.InputManager.executeGesture (02:07:09.326) - winInputHook (6992):
Input: kb(desktop):enter
IO - speech.speak (02:07:09.406) - MainThread (8368):
Speaking ['COM Registration Fixing Tool', 'dialog', "Please wait while NVDA attempts to fix your system's COM registrations...", CancellableSpeech (still valid)]
IO - speech.speak (02:07:09.411) - MainThread (8368):
Speaking ['COM Registration Fixing Tool', CancellableSpeech (still valid)]
```

### Change log entries:
New features
* The COM Registration Fixing Tool will now show a message to the user, including the error, in the rare event of a Windows error while attempting COM re-registrations.
* The COM Registration Fixing Tool initial dialog now has a visual close button, and can be exited with the escape key.

Bug fixes
The COM Registration Fixing Tool no longer shows a completion dialog if it was canceled by closing the UAC dialog without accepting. Instead it behaves as if "No" had been selected in the initial dialog.

### Code Review Checklist:

- [X] Pull Request description is up to date.
- [X] Unit tests.
- [X] System (end to end) tests.
- [X] Manual tests.
- [ ] User Documentation.
- [X] Change log entry.
- [ ] Context sensitive help for GUI changes.

### CODE REVIEW

**Comment by CyrilleB79** [comment]
Hello

Glad that you submit such a PR. I had it in mind already for a little time.
I can see it is still in Draft so you probably want to add additional work in it.

Here are my thoughts:
* The errors that may occur in `COMRegistrationFixes\__init__.py` should not only be logged but also notified to the user when running the COM reg fixing tool. This way, we may clarify some comments that we can find on GitHub or on mailing lists such as "I have run the COM reg fixing tool two times because the first time I had strange results."
* But what should be done when such an error occurs during NVDA installation?
* I think you have changed the dialog asking confirmation prior to COM reg fixing tool execution. Could you check if it is now possible to add context help support to it. At the time context help was implemented, I had checked this but it was not supported in simple message box.

**Comment by XLTechie** [comment]
> Glad that you submit such a PR. I had it in mind already for a little time.

Thank you.

> I can see it is still in Draft so you probably want to add additional work in it.

It could go as is; it is already an improvement, but there are a few 
details I think could still be made better.

>  *  The errors that may occur in COMRegistrationFixes\__init__.py should not only be logged but also notified to the user when running

That would be nice. Already I have it reporting the last Windows error 
raised to the user, but I don't know what that covers.
Specifically, I haven't looked deeply into what can be raised from the elevated run, back to the user level caller.
I will research before finalizing this PR, but it may have to go in the 
next one.

>  *  But what should be done when such an error occurs during NVDA installation?

I think either it has to be silently tried again on error, or silently 
ignored like it is now. I don't think bothering the user with it at that 
stage would be helpful.

>  *  I think you have changed the dialog asking confirmation prior to COM reg fixing tool execution. Could you check if it is now possible to add context
>     help support to it. At the time context help was implemented, I had checked this but it was not supported in simple message box.

Maybe with the Help button? I will try to build it.
I intend to improve the dialog further in any case, so it may end up being 
more helpful than the manual anyway.

**Comment by CyrilleB79** [comment]
> > * I think you have changed the dialog asking confirmation prior to COM reg fixing tool execution. Could you check if it is now possible to add context help support to it. At the time context help was implemented, I had checked this but it was not supported in simple message box.
> Maybe with the Help button? I will try to build it. I intend to improve the dialog further in any case, so it may end up being more helpful than the manual anyway.

No, there is no matter of help button. It depends on if you inherit from wx.Dialog or wx.MessageBox/gui.MessageBox. In the latter case, it does not seem possible to me.

**Comment by XLTechie** [comment]
This grew bigger than I originally intended; I will open a new PR from a more appropriate branch.

**Pull request closed without merging**
