### PR TITLE
Support retrieving the status bar of Windows File Explorer (#6769)  taken over after abandoned #12371

### LINKED ISSUE #6769: Can't read status bar in File Explorer (Windows 10)
In File Explorer (WINDOWS+E), pressing NVDA+end (laptop: NVDA+shift+end) reads "No status line found", even if the status line is enabled (it's possible to disable it in the folder options.

Expected behaviour, read the status bar, for instance, "30 items, 1 selected, details view button, large icons view button".

### PR DESCRIPTION
**Pull request by lukaszgo1**
First of all many thanks to @JulienCochuyt   for most of this work.
### Link to issue number:
Fixes #6769
Superseedes #12371

### Summary of the issue:
Currently, the Window File Explorer cannot be retrieved using the `reportStatusLine` global command.
### Description of how this pull request fixes the issue:
- Take advantage of [Status bar handling: allow app modules to define their own routines to fetch status bar and use it in status bar command in global commands #4640](https://github.com/nvaccess/nvda/issues/4640) to implement custom status bar retrieval by the `explorer` app module.
 - Use a UIAWalker to retrieve it, as hinted by @josephsl in [Can't read status bar in File Explorer (Windows 10) #6769 (comment)](https://github.com/nvaccess/nvda/issues/6769#issuecomment-624532165)
- Still, instead of overlaying the status bar of its children for concerns expressed in [Can't read status bar in File Explorer (Windows 10) #6769 (comment)](https://github.com/nvaccess/nvda/issues/6769#issuecomment-833432110), allow app modules to provide their custom implementation of `api.getStatusBarText`
- Implement `explorer.AppModule.getStatusBarText` as inspired by @ruifontes prototype in [Nvda utters unavailable after copying files #6842 (comment)](https://github.com/nvaccess/nvda/issues/6842#issuecomment-410670910) (hinted by @feerrenrut in [Can't read status bar in File Explorer (Windows 10) #6769 (comment)](https://github.com/nvaccess/nvda/issues/6769#issuecomment-411251846)) but in a slightly more complex way - trying to cover more unexpected cases.

### Testing strategy:
@JulienCochuyt 's testing: 
 - Ran from source under Windows 10 20H2 19042.928 & 19042.964 both with a French locale.
 - Ensured expected result whether files are actually selected or not.

Additionally I've tested under Windows 7, Server 2012, Windows 10 1511, 1809 and latest preview of Windows 11 - in all cases status bar has been retrieved successfully.

 ### Known issues with pull request:

May possibly not work under some version of Windows not described in the testing above, but since this code works from Server 2012 up to Windows 11 without any changes I consider this pretty unlikely.
 ### Change log entries:

 Changes
- In Windows 8 and later , the File Explorer status bar can now be retrieved using the standard gesture `NVDA+end` (desktop) / `NVDA+shift+end` (laptop).

 For Developers

 - Status bar text retrieval may now be customized by an AppModule.

### Code Review Checklist:

- [X] Pull Request description is up to date.
- [X] Unit tests.
- [X] System (end to end) tests.
- [X] Manual testing.
- [X] API is compatible with existing addons.
- [X] User Documentation.
- [X] Change log entry.
- [X] Context sensitive help for GUI changes.
- [X] UX of all users considered:
  - Speech 
  - Braille
  - Low Vision
  - Different web browsers

## Changes from #12371 :
- Tested and modified to work under Windows 7 as requested by @michaelDCurran  in #12371  review.
- Eliminated garbage reported when retrieving status bar in Windows 10's quick access
- Converted to use new enums from `controlTypes`
- Removed redundant announcements about no files being selected.

### CODE REVIEW

**Comment by lukaszgo1** [comment]
@michaelDCurran  Since you're already familiar with the code from #12371  would you be able to review this? I believe I've addressed all your concerns from the review on that PR.

**Comment by CyrilleB79** [comment]
Tested on Windows 10 20H2 (64-bit) build 19042.1165.
I confirm that it is working on this version of Windows.

I hope to see it in NVDA 2021.3 for my own usage. This has also been requested many times in the French community.

@michaelDCurran do you think this PR could be added in 2021.3 milestone? Thanks.

**Comment by lukaszgo1** [comment]
@michaelDCurran  Given there is clearly a community demand for this, and that you've explained on #12371 what needs to happen for this being approved and all of these are addressed may I ask what stops this from being looked at?

**Comment by CyrilleB79** [comment]
Also CCing @feerrenrut to set a release milestone for this PR.

**Comment by lukaszgo1** [comment]
There has been several request for this on the users list recently.

**Review by michaelDCurran — APPROVED** [review]

**Pull request merged**
