### PR TITLE
Developer Guide: additions to the initial namespace of the Python Console

### PR DESCRIPTION
**Pull request by JulienCochuyt**
### Link to issue number:

Follow-up of PR #9064
Follow-up of PR #9790

### Summary of the issue:

These two PRs made additions to the initial namespace of the Python Console but missed to update the Developer Guide accordingly. (Yes, I'm one of the culprits...)

### Description of how this pull request fixes the issue:

Add the new initial imports to the existing list.

### Testing performed:

None

### Change log entry:

I don't think these follow-ups deserve a change log entry.

### CODE REVIEW

**Review by feerrenrut — COMMENTED** [review]
It might be useful to point to where to check this list, or temporarily add to it during development / debugging work. What do you think?

**Comment by JulienCochuyt** [comment]
> It might be useful to point to where to check this list, or temporarily add to it during development / debugging work. What do you think?

Might be. However, note that the current way it is implemented doesn't allow one to cleanly add new entries to the initial namespace from say a GlobalPlugin without first initializing the console altogether, which I'd prefer not to advise.
I could describe how to monkey-patch the console to reach that goal. It wasn't possible with the current implementation in Python 2, but the move to Python 3 opened new doors. This kind of trickery is probably out of scope for the Developer Guide...
I've thought I'd rather wait for the current backlog work to finish, then propose to move the namespace dict to a module attribute - where I believe it belongs - then document in the Developer Guide the new and clean way to add there...

Still, I can add now a note like "See `pythonConsole.PythonConsole.initNamespace`" and/or raise right away a three liner change proposal to allow for easier extensions to the initial namespace, as you prefer.

**Comment by feerrenrut** [comment]
> "See `pythonConsole.PythonConsole.initNamespace` "

That's what I had in mind, just a tip to see the working of it. Sometimes if restarting an in development version of NVDA lots of times and needing to run the same commands over and over in the console it's helpful to hack that file.

**Comment by JulienCochuyt** [comment]
> > "See `pythonConsole.PythonConsole.initNamespace` "
> 
> That's what I had in mind, just a tip to see the working of it. Sometimes if restarting an in development version of NVDA lots of times and needing to run the same commands over and over in the console it's helpful to hack that file.

Done: d1a3617

**Review by feerrenrut — APPROVED** [review]
Thanks @JulienCochuyt

**Pull request merged**
