### PR TITLE
Fix for SAPI5 synthesizers missing some messages

### LINKED ISSUE #10901: LH TTS Speech Engine for SAPI5 Is Not Working Correctly With Speech Refactor
### Steps to reproduce:
1. Install the LH TTS voices, you can get them in several ways, either with Office 2003 or by installing Microsoft Reader.
2. Switch to SAPI5 and switch to one of the voices, LH Michael or LH Michelle.
3. Save the settings then go to the Desktop.

### Actual behavior:
NVDA only says the first chunk of text sent to the synthesizer, such as "Folder View List", and it does not speak the selected icon.

### Expected behavior:
As well as saying "Folder View List, NVDA should say the selected icon just as it does when using other SAPI5 voices.

#### NVDA installed/portable/running from source:
NVDA is installed.

#### NVDA version:
2019.3.1

#### Windows version:
Windows 10 19H2 (10.0.18363)

#### Name and version of other software in use when reproducing the issue:
No other software other than the TTS voice is being used.

#### Other information about your system:
A similar issue of this type was fixed for SAPI4 in current Alpha builds, so I'm guessing that a similar fix would have to happen for the SAPI5 driver, but I'm not entirely sure.

#### Does the issue still occur after restarting your computer?
Yes.

#### Have you tried any other versions of NVDA? If so, please report their behaviors.
All versions of NVDA prior to 2019.3 work correctly in this scenario.

#### If addons are disabled, is your problem still occuring?
Yes.
#### Did you try to run the COM registry fixing tool in NVDA menu / tools?
No, as this issue doesn't persist in other versions of NVDA and it's just with a text-to-speech voice.

### PR DESCRIPTION
**Pull request by dawidpieper**
## Issue:
Fixes #10901.

### Summary of the issue:

In NVDA 2019.3, some indexes are not processed by SAPI5 synthesizers. As a result, for example, when expanding Windows tray or navigating using letters (with characters echo enabled), some information is lost: here icon names.

### Description of how this pull request fixes the issue:
As a workaround, we add a 1msec delay after all messages sent to synthesizers, similarly to the workaround for SAPI4 (#10792).

### Testing performed:
All tests passed, problem seems to be fixed.

### Steps to reproduce:
1.	Install demo version of any of the ivona voices from the www.harposoftware.com 
2.	Keep turned speaking of the individual characters nvda+2
3.	On the desktop, press individual letter on which the name of any icon starts. It will speak just the individual letter you pressed, but not the named icons.

We cannot expect fix from the synth manufacturer, as Ivona is now part of Amazon, and harposoftware just sell these

### Known issues with pull request:
None yet.

### Change log entry:
Bug fixes
SAPI5 voices should no longer miss some information

### CODE REVIEW

**Comment by zstanecic** [comment]
Hi,

I vote this to be merged to beta, as it is a minimal change

Cc @feerrenrut

**Comment by feerrenrut** [comment]
@dawidpieper Is there an issue you can reference for this? It would be helpful to have steps to reproduce.

**Comment by feerrenrut** [comment]
This could potentially be included in the beta, it would need to be rebased first though.

**Comment by zstanecic** [comment]
It is a longstanding issue from the speech refactoring in 2019.3

Steps to reproduce are:

1.	Install demo version of any of the ivona voices from the www.harposoftware.com <http://www.harposoftware.com> 
2.	Keep turned speaking of the individual characters nvda+2
3.	On the desktop, press individual letter on which the name of any icon starts. It will speak just the individual letter you pressed, but not the named icons. We cannot expect fix from the synth manufacturer, as Ivona is now part of Amazon, and harposoftware just sell these

**Comment by zstanecic** [comment]
It will be good to have this in beta, as there are users who want to use these synths, and there is no suitable variant, as newer synhs tend to pronounce words wrongly

**Comment by leonardder** [comment]
@dawidpieper Could you rebase this onto beta or do you need any assistance?

**Comment by dawidpieper** [comment]
Sorry for the confusion, I hope it is okay now.

**Comment by dawidpieper** [comment]
I can see now that this issue is already mentioned as #10901

**Comment by feerrenrut** [comment]
After discussing this a little, we'd like to investigate why indexes are sent to the synth without content which seems like the the real cause of the bug. The first step to investigating this would be to add a unit test for speech manager that replicates the behavior. There are lots of other tests for speech manager, see `tests/unit/test_speechManager/__init__.py`

**Comment by zstanecic** [comment]
Hi

It is the driver thing, not the speech synthesizer one.

**Comment by dawidpieper** [comment]
Some synthesizers just complete speech sequence after last command, ignoring last indexes. It does not seem to be NVDA issue. You can test it with simple xml:

<Bookmark Mark="test_1" />
This is a first phrase.
<Bookmark Mark="test_2" />
And this is a second one.
<Bookmark Mark="test_3" />
And this is the last one.
<Bookmark Mark="test_4" />

You get test_1, test_2 and test_3 bookmarks, but some synthesizers will never report test_4.

Tested it also with this example VB code:
https://docs.microsoft.com/en-us/previous-versions/windows/desktop/ee125622(v=vs.85)

**Comment by feerrenrut** [comment]
That is helpful to know, and might be documented better in NVDA. 

We also have `synthDoneSpeaking` which tells us when the final speech is finished. If we can resolve the concerns in this way, then bookmarks / speech indexes can be thought of as belonging "Before some speech" rather than after. IE they notify speech is about to start, rather than some speech just finished.

**Comment by dawidpieper** [comment]
And we can also queue the messages instead of waiting for them with bookmarks, I think.
Nevertheless, I think it would be justified to introduce this bug fix as a temporare workaround - this problem is often reported on polish forums, where Ivona synthesizers are very popular.
I can also document it better, but I don't know, where.

**Review by feerrenrut — APPROVED** [review]
@dawidpieper Thanks, we'll merge this for now. We plan to replace this approach in 2020.4 with #11651

**Comment by btman16** [comment]
Hi,

The issue is not fixed for the LH TTS voices that is described in issue 10901.

I'm still experiencing the same behavior as before this recent change.

Thanks,

Brandon

**Comment by feerrenrut** [comment]
While this this seems to fix Ivona synth, this introduces regressions for other synthesizers. I'm going to revert this from the beta, there is already a more robust fix delivered to master see "Speech manager no longer sends synths utterances containing only param change and index commands." #11651

Further fixes should target 2020.4

**Pull request merged**
