### PR TITLE
Merge master to beta

### PR DESCRIPTION
**Pull request by seanbudd**
Update strings for translators.

**Must be a merge commit not a squash commit.**

### CODE REVIEW

**Comment by seanbudd** [comment]
Blocked by #13338

**Comment by seanbudd** [comment]
Closing so that this doesn't continue to automatically rebuild: Blocked by #13339 and #13338

**Comment by seanbudd** [comment]
@josephsl @akash07k  - please move this offtopic conversation to a separate issue

**Comment by josephsl** [comment]
Hi,

Oops - apolgies, looks like we got carried away in our emoji panel discussion to notice the issue number. Sorry.

**Comment by seanbudd** [comment]
Ah, I see you were commenting on the commit and GitHub was including it in this PR. It would be great to get a summary of this conversation on the issue/PR, as commit conversations get lost easily.

**Review by michaelDCurran — DISMISSED** [review]

**Review by michaelDCurran — APPROVED** [review]

**Pull request merged**
