### PR TITLE
UIA objects and app modules: convert obj.UIAElement.cachedAutomationId to obj.UIAAutomationId

### LINKED ISSUE #11483: UIA Automation Id/modern input facility: replace UIAElement.cachedAutomationId with UIAAutomationId
Hi,

This stems from #11445 and #11454 and may serve as a test bed for other modules:

### Is your feature request related to a problem? Please describe.
As noted in #11445, if a UIA element is not ready by the time NVDA asks for its properties, COM error is thrown. This is noticeable for Automation Id property, hence the reason for #11445.

One of the most prolific users of Automation Id is modern input facility (emoji panel, clipboard history, and friends). The most prominent issue is inability to detect and handle state change event (see #11454 comment for details).

### Describe the solution you'd like
Replace use of UIAElement.CachedAutomationId with UIAAutomationId getter introduced in #11445. As a start, apply this change to modern input facility. This then allows NVDA to deal with more events, potentially helping us discover more efficient ways to support modern input features, including detecting when emoji panel closes.

### Describe alternatives you've considered
Leave it as is.

### Additional context
There are other places such as File Explorer app module where Automation Id comes into play. Although it would be beneficial to switch to UIAAutomationId getter, it will take time and introduces possible regressions. Therefore this issue (and an accompanying PR) will serve as a way for us to test the viability of this maintenance step.

Thanks.

### PR DESCRIPTION
**Pull request by josephsl**
### Link to issue number:
Closes #11483 

### Summary of the issue:
As part of #11445 discussion, a [UIAAutomationId getter was introduced to UIA NVDA object class](https://github.com/nvaccess/nvda/pull/11447) in NVDA 2020.3. subsequent UIA work uses UIAAutomationId property but it wasn't expanded to cover all NVDA source code.

### Description of how this pull request fixes the issue:
Converts obj.UIAElement.cachedAutomationId call to use obj.UIAAutomationId, which fetches (I believe) current Automation Id string. Most source code fragments that call cachedAutomationId were converted except for:

* obj.devInfo: logs exceptions when trying to obtain current Automation Id.
* UIA objects, specifically Word documents: there are places that fetches UIA elements directly, and for these, old syntax is retained.

In addition, general lint was done for modified files, along with recovering COM error handler for UIA search fields, suggestions lists, and parts of Explorer and Open With app modules since obj.UIAAutomationId will catch COM error itself and return an empty string.

### Testing strategy:
Manual, system, and unit tests:

* Manual testing: perform UIA-related tasks such as using Windows Terminal, Settings app in Windows 10, emoji panel, and other apps.
* Unit and system tests were performed.

### Known issues with pull request:
None

### Change log entries:
Unnecessary unless a note on encouraging people to use UIAAutomationId property for UIA objects should be documented in changes for developers section.

### Code Review Checklist:

- [x] Pull Request description:
  - description is up to date
  - change log entries
- [x] Testing:
  - Unit tests
  - System (end to end) tests
  - Manual testing
- [x] API is compatible with existing add-ons.
- [x] Documentation:
  - User Documentation
  - Developer / Technical Documentation
  - Context sensitive help for GUI changes
- [x] UX of all users considered:
  - Speech 
  - Braille
  - Low Vision
  - Different web browsers
  - Localization in other languages / culture than English

### Additional considerations:
PR #13107 comes with lint and changes for emoji panel app module, but it doesn't matter which PR gets tested, reviewed, and integrated first.

Thanks.

### CODE REVIEW

**Comment by josephsl** [comment]
Perhaps postponing this to 2022.2 or 2023.1. Thanks.

**Comment by feerrenrut** [comment]
@josephsl Sorry for the delay. Is there a technical reason to defer this? If so, please mark as a draft.

**Review by feerrenrut — APPROVED** [review]
The changes here are what is described, I don't see any issues. I'd like @michaelDCurran to confirm this approach is expected.

**Comment by josephsl** [comment]
Hi, I was under the impression that, with the exchange between master and beta branches, 2022.1 milestone might be coming to a close in a few weeks a.k.a. NV Access preparing to tag the beta release in a few weeks. I can work on this branch – I need to check if I need to edit some few files, and then the PR should be good to go. I’ll give this a priority boost from my part within a day or so. Thanks for the reminder.

**Comment by josephsl** [comment]
Hi, thanks for getting back to this. Can we make sure we won’t come across cachedAutomationId before we merge it? Thanks.

**Review by michaelDCurran — APPROVED** [review]
This approach seems perfectly fine to me. @feerrenrut  I am approving on this basis. Though I have not read through every specific change myself.

**Comment by feerrenrut** [comment]
Thanks @michaelDCurran, I'll wait for @josephsl to confirm this is ready to merge. Todo:
- [ ] confirm there are no more `cachedAutomationId` usages.
- [ ] resolve conflicts.

**Comment by josephsl** [comment]
Hi,

There are two instances of cachedAutomationId that should be kept:

* Excel app module: in one instance, UIA element is fetched and cached Automation Id is obtained directly from the element.
* In NVDAObjects.UIA.UIA, there is one instance where parent UIA element is fetched and cached Automation Id is retrieved from the element directly.

Therefore, these will not be changed, and apart from that, things should be good to go (conflicts resolved and file headers updated).
Thanks.

**Review by feerrenrut — COMMENTED** [review]
Thanks @josephsl

**Comment by feerrenrut** [comment]
@josephsl could you double check the changes file entry for accuracy please?

**Comment by josephsl** [comment]
Hi, for now the entry looks good. I wish we can come up with some kind of a process to document UIA properties by linking it to Microsoft Docs pages, something I think should be done at some point in the future when folks work on docs improvements. Thanks.

**Pull request merged**
